### PR TITLE
provider/aws: Refresh `aws_lambda_event_source_mapping` from state when NotFound

### LINKED ISSUE #8375: ResourceNotFoundException on a deleted aws_lambda_event_source_mapping
Hello,

After manually deleting a lambda function (and its associated event source mapping) from the AWS Console I am unable to get terraform to work.

I've tried to taint the resource and destroy as per a suggestion in [this comment](https://github.com/hashicorp/terraform/issues/4888#issuecomment-176608033) but no luck.

### Terraform Version
Terraform v0.7.1

### Affected Resource(s)
- aws_lambda_event_source_mapping

### Terraform Configuration Files
```hcl
resource "aws_lambda_event_source_mapping" "dmp_enrichment_event_source_mapping" {
    batch_size = 10
    event_source_arn = "${aws_kinesis_stream.dmp_event_raw_stream.arn}"
    function_name = "${aws_lambda_function.dmp_enrichment_event_lambda.arn}"
    starting_position = "LATEST"
    enabled = true
}
resource "aws_lambda_function" "dmp_enrichment_event_lambda" {
    filename = "${lookup(var.aws_lambda_functions, "event_enrichment")}"
    function_name = "enrichment_event_lambda"
    role = "${aws_iam_role.dmp_lambda_function.arn}"
    handler = "_apex_index.handle"
    source_code_hash = "${base64sha256(file(lookup(var.aws_lambda_functions, "event_enrichment")))}"
}
```

### Debug Output

https://gist.github.com/alexkappa/35ee3871e250680a4b69fe512e777166

### Actual Behavior

Terraform fails with

```
Error refreshing state: 1 error(s) occurred:

* aws_lambda_event_source_mapping.dmp_enrichment_event_source_mapping: ResourceNotFoundException: The resource you requested does not exist.
	status code: 404, request id: a17c641d-6868-11e6-accf-3d0ea71934fa
```

### Steps to Reproduce

1. Create a lambda and event source mapping using terraform
2. Delete lambda from AWS Console
3 Apply terraform changes

### References

- #4888
- #6625

### PR DESCRIPTION
**Pull request by stack72**
Fixes #8375

When a Lambda or an associated Event Source Mapping has been removed via
the AWS Console, Terraform throws an error similar to the following:

```
Error refreshing state: 1 error(s) occurred:

* aws_lambda_event_source_mapping.dmp_enrichment_event_source_mapping:
* ResourceNotFoundException: The resource you requested does not exist.
    status code: 404, request id: a17c641d-6868-11e6-accf-3d0ea71934fa

```

the resource should be refreshed from the state when this happens so
that subsequent plans show it needs to be recreated

```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSLambdaEventSourceMapping_'
==> Checking that code complies with gofmt requirements...
/Users/stacko/Code/go/bin/stringer
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/08/22 16:15:54 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v
-run=TestAccAWSLambdaEventSourceMapping_ -timeout 120m
=== RUN   TestAccAWSLambdaEventSourceMapping_basic
--- PASS: TestAccAWSLambdaEventSourceMapping_basic (120.81s)
=== RUN   TestAccAWSLambdaEventSourceMapping_disappears
--- PASS: TestAccAWSLambdaEventSourceMapping_disappears (104.08s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/aws    224.914s
```

### CODE REVIEW

File: builtin/providers/aws/resource_aws_lambda_event_source_mapping.go [hunk 1]
```diff
@@ -134,6 +134,12 @@ func resourceAwsLambdaEventSourceMappingRead(d *schema.ResourceData, meta interf
 
 	eventSourceMappingConfiguration, err := conn.GetEventSourceMapping(params)
 	if err != nil {
+		if ec2err, ok := err.(awserr.Error); ok && ec2err.Code() == "ResourceNotFoundException" {
```
Comment (jen20) [inline builtin/providers/aws/resource_aws_lambda_event_source_mapping.go]: We are a bit inconsistent about whether we test this directly or write a utility function like `fun isResourceNotFound(err error) bool` - I guess we should decide what the pattern is there and apply that going forward.

Comment (stack72) [inline builtin/providers/aws/resource_aws_lambda_event_source_mapping.go]: There is an RFC going to happen on that really soon :)

Comment (jen20) [inline builtin/providers/aws/resource_aws_lambda_event_source_mapping.go]: :+1: in that case LGTM
