### PR TITLE
core: Loosen output value sensitivity requirement

### LINKED ISSUE #28431: v0.15 - Passing a sensitive value to a non-sensitive module variable causes an error if the module derives a non-sensitive output from that variable
### Terraform Version

```
0.15.0
```

### Terraform Configuration Files

```terraform
variable "db_username" {
  description = "Database administrator username"
  type        = string
  sensitive   = true
}

module "rds" {
  source  = "terraform-aws-modules/rds/aws"
  version = "2.34.0"

  username = var.db_username

  # additional arguments ...
}
```

### Expected Behavior

Both `plan` and `apply` commands should proceed successfully, redacting the passed in `username` argument (and any derived uses) from CLI output as `(sensitive value)`.

### Actual Behavior

Terraform errors out on plan creation with the message:
```
│ Error: Output refers to sensitive values
│
│   on .terraform/modules/rds/modules/db_instance/outputs.tf line 76:
│   76: output "this_db_instance_username" {
│
│ Expressions used in outputs can only refer to sensitive values if the sensitive attribute is true.
```
* Note that the error is coming from an output within the module (actually coming from a submodule output that is getting threaded through).
* The issue occurs regardless of whether the output is used or completely ignored.
* This did not cause an error in Terraform 0.14.x, however Terraform 0.14 ended up not treating the value as sensitive within the module (equivalent to if `username = nonsensitive(var.db_username)` had been passed into the module).
### Steps to Reproduce

1. `terraform init`
2. `terraform plan` or `terraform apply`
### Additional Context

The author of the module did not mark the `username` input variable or the `this_db_instance_username` output as `sensitive = true`, since not all users of the module may consider the administrative username as sensitive for their particular use case or security posture (unlike an argument like `password`, which can be presumed as sensitive in all use cases). However, because the module output `this_db_instance_username` is derived from the input variable `username`, it causes an error when the value passed into `username` is being tracked as sensitive by Terraform.

The requirement for module outputs to be marked with `sensitive = true` should be limited to values and variables defined within the module as sensitive, not values that were marked as sensitive outside the module and then passed into the module through input variables not marked as sensitive. It is impractical for Terraform to force the author of third-party modules to determine what inputs/outputs all users of the module may consider sensitive, as this may vary by use case. Instead, it should allow allow sensitive values passed into a module (and any derived values) to be outputted, without the module author being concerned about whether the passed in value was marked as sensitive by the user. At the very least, the error message is misleading as it implies an issue in the module, when really it was caused by the user passing a sensitive value into the module which the module did not consider sensitive, deriving an output from that value that it did not explicitly mark as sensitive.

### PR DESCRIPTION
**Pull request by alisdair**
Non-root module outputs no longer strip sensitivity marks from their values, allowing dynamically sensitive values to propagate through the configuration. We also remove the requirement for non-root module outputs to be defined as sensitive if the value is marked as sensitive.

This avoids a static/dynamic clash when using shared modules that might unknowingly receive sensitive values via input variables.

Fixes #28431.

### CODE REVIEW

File: terraform/node_output.go [hunk 1]
```diff
@@ -275,16 +275,21 @@ func (n *NodeApplyableOutput) Execute(ctx EvalContext, op walkOperation) (diags
...
-				Summary:  "Output refers to sensitive values",
-				Detail:   "Expressions used in outputs can only refer to sensitive values if the sensitive attribute is true.",
-				Subject:  n.Config.DeclRange.Ptr(),
-			})
+		if n.Addr.Module.IsRoot() {
+			if !n.Config.Sensitive && hasSensitive {
+				diags = diags.Append(&hcl.Diagnostic{
+					Severity: hcl.DiagError,
+					Summary:  "Output refers to sensitive values",
+					Detail:   "Expressions used in outputs can only refer to sensitive values if the sensitive attribute is true.",
```
Comment (apparentlymart) [inline terraform/node_output.go:289]: Given that this is now a little more subtle than it was before, a suggested revised detail message:

> 
>
> 
>

```
To reduce the risk of accidentally exporting sensitive data
that was intended to be only internal, Terraform requires
that any root module output containing sensitive data be
explicitly marked as sensitive, to confirm your intent.

If you do intend to export this data, annotate the output
value as sensitive by adding the following argument:
    sensitive = true
```

File: terraform/node_output.go [hunk 2]
```diff
@@ -275,16 +275,21 @@ func (n *NodeApplyableOutput) Execute(ctx EvalContext, op walkOperation) (diags
...
 		_, hasSensitive := marks["sensitive"]
-		if !n.Config.Sensitive && hasSensitive {
-			diags = diags.Append(&hcl.Diagnostic{
-				Severity: hcl.DiagError,
-				Summary:  "Output refers to sensitive values",
-				Detail:   "Expressions used in outputs can only refer to sensitive values if the sensitive attribute is true.",
-				Subject:  n.Config.DeclRange.Ptr(),
-			})
+		if n.Addr.Module.IsRoot() {
+			if !n.Config.Sensitive && hasSensitive {
```
Comment (apparentlymart) [inline terraform/node_output.go:285]: Not really a big deal, but I think a simpler (and less expensive) way to achieve `hasSensitive` here might be `val.HasMark("sensitive")`, since it seems like we're just discarding the unmarked value above anyway.

**Review by apparentlymart — APPROVED** [review]
This looks reasonable to me! Thanks for digging in to this.

I left some unimportant cosmetic notes inline. Feel free to ignore or adjust them if you disagree; it's all subjective anyway.

File: terraform/node_output.go (hunk 2 above)
Comment (alisdair) [reply terraform/node_output.go:285]: Unfortunately this would fail to catch nested sensitive values. For example, it would cause this to happen:

```hcl
output "a" {
  value = {
    b = sensitive("foo")
  }
}
```

```
Changes to Outputs:
  + a = {
      + b = "foo"
    }
```

Whereas with the code as-is, we get:

```
│ Error: Output refers to sensitive values
│
│   on main.tf line 1:
│    1: output "a" {
│
│ Expressions used in outputs can only refer to sensitive values if the sensitive attribute is true.
```

File: terraform/node_output.go (hunk 1 above)
Comment (alisdair) [reply terraform/node_output.go]: Thanks, added verbatim!

File: terraform/node_output.go (hunk 2 above)
Comment (apparentlymart) [reply terraform/node_output.go:285]: Ahh yes, right... there isn't a `HasMarkDeep` (or such) method, so we're using `UnmarkDeep` here to get the effect of one. Seems reasonable!
