### PR TITLE
provider/aws: fixes double base64 encode

### LINKED ISSUE #10786: Provider AWS: Autoscaling Launch Configuration base64 encodes user_data regardless of input
### Affected Resource(s)
- aws_launch_configuration

### Supporting Links
How EC2 Instance handles User Data: https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_instance.go#L1062
How Launch Config handles User Data:
https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_launch_configuration.go#L313

### Expected Behavior
Based on functionality in aws_instance, launch configuration should base64 encode only if content is not already base64 encoded.

### Actual Behavior
aws_launch_configuration base64 encodes user_data regardless of the input.

### PR DESCRIPTION
**Pull request by curtisallen**
Add a utility that ensures a byte array is not doubly base64 encoded

Reference https://play.golang.org/p/RnEBFCJ9h0
Fixes #10786

### CODE REVIEW

File: builtin/providers/aws/utils.go [hunk 1]
```diff
@@ -0,0 +1,13 @@
+package aws
```
Comment (nathany) [inline builtin/providers/aws/utils.go]: Rather than a generic "utils" file, maybe this file should be named base64.go and likewise for the tests?

File: builtin/providers/aws/utils.go [hunk 2]
```diff
@@ -0,0 +1,13 @@
...
+
+import "encoding/base64"
+
+// Base64Encode encodes data if the input isn't already encoded useing base64.StdEncoding.EncodeToString.
+// If the input is already base64 encoded, return the original input unchanged.
+func base64Encode(data []byte) string {
+	// Check whether the user_data is already Base64 encoded; don't double-encode
+	if _, base64DecodeError := base64.StdEncoding.DecodeString(string(data)); base64DecodeError != nil {
+		return base64.StdEncoding.EncodeToString(data)
```
Comment (nathany) [inline builtin/providers/aws/utils.go]: Since an error represents the expected path of not being encoded and therefore needing encoded, this may be clearer with a new more comments. `// not encoded, so encode it` `// already encoded`.

Or maybe even splitting out an `isBase64Encoded() bool` function?

File: builtin/providers/aws/utils.go (hunk 1 above)
Comment (curtisallen) [inline builtin/providers/aws/utils.go]: Yeah, I was looking for examples in other packages on what to name this file. In the `aws` package, there's an `auth_helper.go`. In other packages there are `utils.go`, just not sure which is the best fit for this use case.

File: builtin/providers/aws/utils.go [hunk 3]
```diff
@@ -0,0 +1,19 @@
+package aws
+
+import "encoding/base64"
+
+// Base64Encode encodes data if the input isn't already encoded useing base64.StdEncoding.EncodeToString.
+// If the input is already base64 encoded, return the original input unchanged.
+func base64Encode(data []byte) string {
+	// Check whether the user_data is already Base64 encoded; don't double-encode
```
Comment (nathany) [inline builtin/providers/aws/utils.go]: in this context it's just `data`, not `user_data`

File: builtin/providers/aws/utils.go [hunk 4]
```diff
@@ -0,0 +1,19 @@
+package aws
+
+import "encoding/base64"
+
+// Base64Encode encodes data if the input isn't already encoded useing base64.StdEncoding.EncodeToString.
```
Comment (nathany) [inline builtin/providers/aws/utils.go]: s/useing/using/

Comment (curtisallen) [inline builtin/providers/aws/utils.go]: whoops good catch

File: builtin/providers/aws/utils.go (hunk 3 above)
Comment (curtisallen) [inline builtin/providers/aws/utils.go]: thanks will fix

**Comment by jen20** [comment]
This LGTM, I'm going to rename the file after merge however. Thanks @curtisallen!

**Comment by nathany** [comment]
Thanks James. Did you mean to rename utils.go?

[hub](https://github.com/github/hub) is pretty useful for amending pull requests (see [article](https://blog.spreedly.com/2014/06/24/merge-pull-request-considered-harmful/))
