### PR TITLE
core: fix provider config inheritence for deeply nested modules

### LINKED ISSUE #2832: Provider configuration not passed to grandchild modules
When calling a module from another module, provider configuration does not seem to be propagated all the way down to the grandchild. This works as expected with a single level of modules, but when 2 or more layers are involved, the issue rears its head.

Terraform v0.6.2-dev (5a15c02cbbea27d3f8345b5fe0f348a08a24fdb9)

#### main.tf
```
provider "aws" {
  access_key = "zip"
  secret_key = "zap"
  region     = "us-east-1"
}

module "foo" {
  source = "./foo"
}
```

#### foo/main.tf
```
module "bar" {
  source = "./bar"
}
```

#### foo/bar/main.tf
```
resource "aws_instance" "baz" {
  ami           = "ami-4c7a3924"
  count         = 1
  instance_type = "t2.micro"
}
```

#### Result:
```
$ terraform plan
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * module.foo.module.bar.provider.aws: "region": required field is not set
  * module.foo.module.bar.provider.aws: "access_key": required field is not set
  * module.foo.module.bar.provider.aws: "secret_key": required field is not set
```

The other weird thing is that the error is not always the same. I've seen 3 (!) different outputs for the same input. The others include an interactive prompt for the credentials:

```
$ terraform plan
provider.aws.access_key
  The access key for API operations. You can retrieve this
  from the 'Security & Credentials' section of the AWS console.

  Enter a value:
```

Or an invalid token error, which I would expect for this example:
```
$ terraform plan
Refreshing Terraform state prior to plan...

Error refreshing state: 1 error(s) occurred:

* 1 error(s) occurred:

* InvalidClientTokenId: The security token included in the request is invalid.
	status code: 403, request id: [11cdaeed-315d-11e5-9c83-7d4a35a9d7b0]
```

### LINKED ISSUE #4443: Level limitation to provider inheritance in modules?
Is there currently a limitation to how many modules you can chain together before a provider definition is ignored?

# One Module
I have a custom module that builds a network in AWS (VPC, subnets, routing tables, etc), which is called by code to define a service. The custom module only contains resources, no providers. The service defines the aws_provider with its keys and region (hardcoded) and all variables have a default value. I shouldn't get prompted for jack. If I do a `terraform get && terraform plan` on the service code, everything works fine, it spits out a plan, I can build a graph, etc.

## Hierarchy...

* service
  * module

## Graph...
Notice how `provider.aws` on root is marked as disabled, but it still works?
```
digraph {
	compound = "true"
	newrank = "true"
	subgraph "root" {
		"[root] module.custom.aws_internet_gateway.ig" [label = "aws_internet_gateway.ig", shape = "box"]
		"[root] module.custom.aws_route_table_association.subnet-a" [label = "aws_route_table_association.subnet-a", shape = "box"]
		"[root] module.custom.aws_route_table_association.subnet-b" [label = "aws_route_table_association.subnet-b", shape = "box"]
		"[root] module.custom.aws_subnet.vpc-a" [label = "aws_subnet.vpc-a", shape = "box"]
		"[root] module.custom.aws_subnet.vpc-b" [label = "aws_subnet.vpc-b", shape = "box"]
		"[root] module.custom.aws_vpc.vpc" [label = "aws_vpc.vpc", shape = "box"]
		"[root] module.custom.provider.aws" [label = "provider.aws", shape = "diamond"]
		"[root] provider.aws (disabled)" [label = "provider.aws (disabled)", shape = "diamond"]
		"[root] module.custom.aws_internet_gateway.ig" -> "[root] module.custom.aws_vpc.vpc"
		"[root] module.custom.aws_route_table_association.subnet-a" -> "[root] module.custom.aws_subnet.vpc-a"
		"[root] module.custom.aws_route_table_association.subnet-b" -> "[root] module.custom.aws_subnet.vpc-b"
		"[root] module.custom.aws_subnet.vpc-a" -> "[root] module.custom.aws_vpc.vpc"
		"[root] module.custom.aws_subnet.vpc-b" -> "[root] module.custom.aws_vpc.vpc"
		"[root] module.custom.aws_vpc.vpc" -> "[root] module.custom.provider.aws"
		"[root] module.custom.provider.aws" -> "[root] provider.aws (disabled)"
	}
}
```

## Two Modules
If make the service code a module and call it from code that defines an environment, then all of a sudden, I get prompted for the AWS provider details. Even though it's hard coded in the files. The environment code contains nothing of it's own (no providers whatsoever, that is defined in service), it literally just calls the service module and passes it's vars to the module.

## Hierarchy...

* environment
  * service
    * module

## Graph...
Notice how `module.service.provider.aws` on root is disabled, which is the `provider.aws` from root in the example above, but now it doesn't work?
```
digraph {
	compound = "true"
	newrank = "true"
	subgraph "root" {
		"[root] module.service.module.custom.aws_internet_gateway.ig" [label = "aws_internet_gateway.ig", shape = "box"]
		"[root] module.service.module.custom.aws_route_table_association.subnet-a" [label = "aws_route_table_association.subnet-a", shape = "box"]
		"[root] module.service.module.custom.aws_route_table_association.subnet-b" [label = "aws_route_table_association.subnet-b", shape = "box"]
		"[root] module.service.module.custom.aws_subnet.vpc-a" [label = "aws_subnet.vpc-a", shape = "box"]
		"[root] module.service.module.custom.aws_subnet.vpc-b" [label = "aws_subnet.vpc-b", shape = "box"]
		"[root] module.service.module.custom.aws_vpc.vpc" [label = "aws_vpc.vpc", shape = "box"]
		"[root] module.service.module.custom.provider.aws" [label = "provider.aws", shape = "diamond"]
		"[root] module.service.provider.aws (disabled)" [label = "provider.aws (disabled)", shape = "diamond"]
		"[root] provider.aws (disabled)" [label = "provider.aws (disabled)", shape = "diamond"]
		"[root] module.service.module.custom.aws_internet_gateway.ig" -> "[root] module.service.module.custom.aws_vpc.vpc"
		"[root] module.service.module.custom.aws_route_table_association.subnet-a" -> "[root] module.service.module.custom.aws_subnet.vpc-a"
		"[root] module.service.module.custom.aws_route_table_association.subnet-b" -> "[root] module.service.module.custom.aws_subnet.vpc-b"
		"[root] module.service.module.custom.aws_subnet.vpc-a" -> "[root] module.service.module.custom.aws_vpc.vpc"
		"[root] module.service.module.custom.aws_subnet.vpc-b" -> "[root] module.service.module.custom.aws_vpc.vpc"
		"[root] module.service.module.custom.aws_vpc.vpc" -> "[root] module.service.module.custom.provider.aws"
	}
}
```

According to the debug output on `plan`, this keeps asynchronously repeating every 5 seconds to the log (same pieces, never in same order)...
```
2015/12/25 22:13:49 [DEBUG] vertex provider.module.service.module.custom.aws (close), waiting for: module.service.module.custom.aws_internet_gateway.ig
2015/12/25 22:13:49 [DEBUG] vertex module.service.module.custom.aws_route_table_association.subnet-a, waiting for: module.service.module.custom.aws_subnet.vpc-a
2015/12/25 22:13:49 [DEBUG] vertex module.service.module.custom.aws_subnet.vpc-b, waiting for: module.service.module.custom.aws_vpc.vpc
2015/12/25 22:13:49 [DEBUG] vertex module.service.module.custom.aws_internet_gateway.ig, waiting for: module.service.module.custom.aws_vpc.vpc
2015/12/25 22:13:49 [DEBUG] vertex module.service.module.custom.aws_route_table_association.subnet-b, waiting for: module.service.module.custom.aws_subnet.vpc-b
2015/12/25 22:13:49 [DEBUG] vertex module.service.module.custom.aws_vpc.vpc, waiting for: module.service.module.custom.provider.aws
2015/12/25 22:13:49 [DEBUG] vertex module.service.module.custom.aws_subnet.vpc-a, waiting for: module.service.module.custom.aws_vpc.vpc
2015/12/25 22:13:49 [DEBUG] vertex root, waiting for: provider.module.service.module.custom.aws (close)
```
The name of that last item looks odd, cause it doesn't exist by that name. Not sure if that's part of the issue or just a mistake in the output.

## Repro

1. Using 0.6.8, clone https://github.com/wholroyd/terraform-bug, and edit `c_service/main.tf` and add in your AWS keys.
2. Navigate to `c_service/` and run `terraform get && terraform plan`. This should work, you should get a plan generated.
3. Navigate to `b_environment/` and run `terraform get && terraform plan`. This should fail as you will get AWS key and region prompts instead.

The only difference between c_service and b_environment is that it's an additional level in the graph and service contains the provider. It's literally the same content in both `main.tf` files with different module name and source values otherwise.

From what I understand, as long as you have a provider defined at the same level or in an ancestral level to a resource that needs to use it, this should work.

### LINKED ISSUE #4865: Providers are not inherited by grandchildren
When you declare a provider and then import a module, the child module has access to the provider declared in the parent. If the imported child module in turn imports a module the grandchild module does not have access to the provider declared in the grandparent.

[terraform-bug-repro.zip](https://github.com/hashicorp/terraform/files/107158/terraform-bug-repro.zip)

In the reproduction sample provided there is a root TF file, and 3 modules. The root calls module 1, which calls module 2, which calls module 3, all 3 modules instantiate a resource. In order for this to execute without error a provider must be declared in the root and module 2. Module 1 inherits its provider from the root, and module 3 inherits its provider from module 2. If the provider is left out of module 2 it will attempt to instantiate a new provider rather than use the one that module one has inherited from the root.

The following issues appear to be relevant to this issue: 
#3285
#1819

### PR DESCRIPTION
**Pull request by phinze**
The flattening process was not properly drawing dependencies between provider
nodes in modules and their parent provider nodes.

Fixes #2832
Fixes #4443
Fixes #4865

### CODE REVIEW

File: terraform/transform_provider.go [hunk 1]
```diff
@@ -340,22 +343,18 @@ func (n *graphNodeDisabledProviderFlat) ProviderName() string {
...
+		n.graphNodeDisabledProvider.DependableName(),
+		modulePrefixStr(n.PathValue))
 }
 
 func (n *graphNodeDisabledProviderFlat) DependentOn() []string {
 	var result []string
 
 	// If we're in a module, then depend on our parent's provider
 	if len(n.PathValue) > 1 {
-		prefix := modulePrefixStr(n.PathValue[:len(n.PathValue)-1])
```
Comment (jen20) [inline terraform/transform_provider.go]: The build failure (terraform/transform_provider.go:357: undefined: prefix) seems related to this?

**Comment by jen20** [comment]
@phinze looks like the build error here is correct and there is a stray deletion in the diff?

**Comment by phinze** [comment]
Yeah final pre-push cleanup was a little overzealous - fixing! :smile:

**Comment by phinze** [comment]
Ok green now, @jen20 PTAL!

**Comment by jen20** [comment]
This LGTM now.

**Comment by evilezh** [comment]
There is still bug with nested modules (0.6.16)
After I've created module, I did comment out it (so it should get destroyed).
here is structure:
root level:  AWS defined, include of module level 2.
level 2: include several modules from level 3 (nothing else)
level 3: do aws stuff 

When I ask to destroy: 
\# terraform apply
provider.aws.region
The region where AWS operations will take place. Examples
are us-east-1, us-west-2, etc.

  Default: us-east-1
  Enter a value:

I enter my value and then it runs refresh nicely through refresh state, but when it should start doing actual changes, then: 
Error refreshing state: 
\* 1 error(s) occurred:

\* No valid credential sources found for AWS Provider.
  Please see https://terraform.io/docs/providers/aws/index.html for more information on
  providing credentials for the AWS Provider

**Comment by hatt** [comment]
Seeing the same as @evilezh, extra confusing when the provider is repeatedly asking which region to use with no context as to which module instance it's even referencing. Running on 0.7.3-dev (git commit 70d9fe8).
