### PR TITLE
provider/scaleway: fix scaleway_volume_attachment with count > 1

### LINKED ISSUE #9417: Scaleway: Adding multiple volumes doesn't work
### Terraform Version

`0.7.6`

### Affected Resource(s)

* `scaleway_server`
* `scaleway_volume`
* `scaleway_volume_attachment`

### Terraform Configuration Files

```hcl
variable "access" {
  type = "string"
}

variable "org" {
  type = "string"
}

provider "scaleway" {
  access_key   = "${var.access}"
  organization = "${var.org}"
}

resource "scaleway_server" "store" {
  name  = "store"
  image = "75c28f52-6c64-40fc-bb31-f53ca9d02de9"
  type  = "C2S"
}

resource "scaleway_volume" "store" {
  count      = "3"
  name       = "vol-${count.index}"
  size_in_gb = "150"
  type       = "l_ssd"
}

resource "scaleway_volume_attachment" "store" {
  count  = "3"
  volume = "${element(scaleway_volume.store.*.id, count.index)}"
  server = "${element(scaleway_server.store.*.id, 0)}"
}
```

### Debug Output

https://gist.github.com/tboerger/c1e36a1ab2d53cfc072c6a9919bcbc66

### Panic Output

n/a

### Expected Behavior

I would expect to have a running server that got 3 additional volumes assigned.

### Actual Behavior

The setup simply fails because one volume attachment invokes a reboot of the server while the next volume attachment fails because the server is not running anymore:

```
2 error(s) occurred:

* scaleway_volume_attachment.store.2: StatusCode: 400, Type: invalid_request_error, APIMessage: server is being stopped or rebooted
* scaleway_volume_attachment.store.0: StatusCode: 400, Type: invalid_request_error, APIMessage: server is being stopped or rebooted
```

After the failed action you can see on the Scaleway web UI that only one volume have been attached to the server:

bildschirmfoto 2016-10-17 um 23 31 16

### Steps to Reproduce

1. Get an `access_key` and the `organization` from your Scaleway account
2. Simply execute `terraform apply` and wait

### Important Factoids

I tried to launch multiple nodes with multiple volumes at once, but I have slimmed down the example to keep it simple. Maybe it would already help to assign volumes while node creation, the API supports that.

### References

Maybe these issues are somehow related or maybe a PR solves the issue partially:

* #9254
* #8678

/cc @nicolai86

### PR DESCRIPTION
**Pull request by nicolai86**
since scaleway requires servers to be powered off to attach volumes to we need
to make sure that we don't power down a server twice, or power up a server while
it's supposed to be modified. classic race condition.

sadly terraform doesn't seem to sport serialization primitives for use cases like
this, but putting the code in question behind a `sync.Mutex` does the trick, too.

this PR also migrates `waitForServerState` over to terraform's internal retry primitive.

fixes #9417

```
TF_ACC=1 go test ./builtin/providers/scaleway -v -run=TestAccScaleway -timeout 120m
=== RUN   TestAccScalewayDataSourceBootscript_Basic
--- PASS: TestAccScalewayDataSourceBootscript_Basic (1.46s)
=== RUN   TestAccScalewayDataSourceBootscript_Filtered
--- PASS: TestAccScalewayDataSourceBootscript_Filtered (1.16s)
=== RUN   TestAccScalewayDataSourceImage_Basic
--- PASS: TestAccScalewayDataSourceImage_Basic (7.22s)
=== RUN   TestAccScalewayDataSourceImage_Filtered
--- PASS: TestAccScalewayDataSourceImage_Filtered (7.17s)
=== RUN   TestAccScalewayIP_importBasic
--- PASS: TestAccScalewayIP_importBasic (1.95s)
=== RUN   TestAccScalewaySecurityGroup_importBasic
--- PASS: TestAccScalewaySecurityGroup_importBasic (2.35s)
=== RUN   TestAccScalewayServer_importBasic
--- PASS: TestAccScalewayServer_importBasic (138.48s)
=== RUN   TestAccScalewayVolume_importBasic
--- PASS: TestAccScalewayVolume_importBasic (3.49s)
=== RUN   TestAccScalewayIP_Basic
--- PASS: TestAccScalewayIP_Basic (10.79s)
=== RUN   TestAccScalewaySecurityGroupRule_Basic
--- PASS: TestAccScalewaySecurityGroupRule_Basic (6.57s)
=== RUN   TestAccScalewaySecurityGroup_Basic
--- PASS: TestAccScalewaySecurityGroup_Basic (2.52s)
=== RUN   TestAccScalewayServer_Basic
--- PASS: TestAccScalewayServer_Basic (129.39s)
=== RUN   TestAccScalewayServer_SecurityGroup
--- PASS: TestAccScalewayServer_SecurityGroup (166.02s)
=== RUN   TestAccScalewayVolumeAttachment_Basic
--- PASS: TestAccScalewayVolumeAttachment_Basic (373.03s)
=== RUN   TestAccScalewayVolume_Basic
--- PASS: TestAccScalewayVolume_Basic (3.27s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/scaleway	854.886s
```

### CODE REVIEW

**Comment by dcharbonnier** [comment]
Wrong tag @catsby ;-)

**Comment by tboerger** [comment]
I will give it a try tomorrow

**Comment by dcharbonnier** [comment]
What do you think about the azure implementation that define a [MutexKV in the provider](https://github.com/hashicorp/terraform/blob/97ad032474db194caeb7e9a6da85e3b98934ccfb/builtin/providers/azurerm/provider.go#L210) and [lock ressources](https://github.com/hashicorp/terraform/blob/97ad032474db194caeb7e9a6da85e3b98934ccfb/builtin/providers/azurerm/resource_arm_route.go). It take advantage of the terraform official helper [mutexkv](https://github.com/hashicorp/terraform/blob/351c6bed79abbb40e461d3f7d49fe4cf20bced41/helper/mutexkv/mutexkv.go), that could be more "elegant" don't you think @nicolai86 ?

File: builtin/providers/scaleway/helpers.go [hunk 1]
```diff
@@ -47,26 +48,21 @@ func deleteServerSafe(s *api.ScalewayAPI, serverID string) error {
...
 }
 
-func waitForServerState(s *api.ScalewayAPI, serverID string, targetState string) error {
-	var server *api.ScalewayServer
-	var err error
+// NOTE copied from github.com/scaleway/scaleway-cli/pkg/api/helpers.go
+// the helpers.go file pulls in quite a lot dependencies, and they're just convenience wrappers anyway
 
-	var currentState string
+func waitForServerState(scaleway *api.ScalewayAPI, serverID string, targetState string) error {
```
Comment (dcharbonnier) [inline builtin/providers/scaleway/helpers.go]: :+1:

**Comment by nicolai86** [comment]
great find, @dcharbonnier . I'll adjust the PR

**Comment by nicolai86** [comment]
tests still pass:

```
TF_ACC=1 go test ./builtin/providers/scaleway -v -run=TestAccScaleway -timeout 120m
=== RUN   TestAccScalewayDataSourceBootscript_Basic
--- PASS: TestAccScalewayDataSourceBootscript_Basic (1.38s)
=== RUN   TestAccScalewayDataSourceBootscript_Filtered
--- PASS: TestAccScalewayDataSourceBootscript_Filtered (1.20s)
=== RUN   TestAccScalewayDataSourceImage_Basic
--- PASS: TestAccScalewayDataSourceImage_Basic (7.30s)
=== RUN   TestAccScalewayDataSourceImage_Filtered
--- PASS: TestAccScalewayDataSourceImage_Filtered (7.37s)
=== RUN   TestAccScalewayIP_importBasic
--- PASS: TestAccScalewayIP_importBasic (2.24s)
=== RUN   TestAccScalewaySecurityGroup_importBasic
--- PASS: TestAccScalewaySecurityGroup_importBasic (2.38s)
=== RUN   TestAccScalewayServer_importBasic
--- PASS: TestAccScalewayServer_importBasic (116.65s)
=== RUN   TestAccScalewayVolume_importBasic
--- PASS: TestAccScalewayVolume_importBasic (3.26s)
=== RUN   TestAccScalewayIP_Basic
--- PASS: TestAccScalewayIP_Basic (11.16s)
=== RUN   TestAccScalewaySecurityGroupRule_Basic
--- PASS: TestAccScalewaySecurityGroupRule_Basic (5.02s)
=== RUN   TestAccScalewaySecurityGroup_Basic
--- PASS: TestAccScalewaySecurityGroup_Basic (2.48s)
=== RUN   TestAccScalewayServer_Basic
--- PASS: TestAccScalewayServer_Basic (161.38s)
=== RUN   TestAccScalewayServer_SecurityGroup
--- PASS: TestAccScalewayServer_SecurityGroup (302.07s)
=== RUN   TestAccScalewayVolumeAttachment_Basic
--- PASS: TestAccScalewayVolumeAttachment_Basic (448.10s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/scaleway
```

**Comment by tboerger** [comment]
Is it possible that there is some kind of race while executing `plan`? It's hanging until I hit Ctrl+c, than it's printing a lot of output. But `apply` seem to work properly with that change, even if it takes some time to setup my cluster.

I'm just running into another issue from Scaleway where a node is hanging from time to time at `starting server (kernel started)`.

**Comment by tboerger** [comment]
I can confirm that this patch correctly fixes the attachment of multiple volumes. It took nearly 8 minutes to launch one server of the type `C2S` with 3 additional volumes:

```
# time terraform apply
data.scaleway_image.store: Refreshing state...
scaleway_server.store: Creating...
  enable_ipv6:  "" => "false"
  image:        "" => "047f1372-3923-471f-82ca-5ff69dbaf0f7"
  name:         "" => "store"
  private_ip:   "" => "<computed>"
  public_ip:    "" => "<computed>"
  state:        "" => "<computed>"
  state_detail: "" => "<computed>"
  type:         "" => "C2S"
scaleway_volume.store.2: Creating...
  name:       "" => "vol-2"
  server:     "" => "<computed>"
  size_in_gb: "" => "150"
  type:       "" => "l_ssd"
scaleway_volume.store.0: Creating...
  name:       "" => "vol-0"
  server:     "" => "<computed>"
  size_in_gb: "" => "150"
  type:       "" => "l_ssd"
scaleway_volume.store.1: Creating...
  name:       "" => "vol-1"
  server:     "" => "<computed>"
  size_in_gb: "" => "150"
  type:       "" => "l_ssd"
scaleway_volume.store.0: Creation complete
scaleway_volume.store.1: Creation complete
scaleway_volume.store.2: Creation complete
scaleway_server.store: Still creating... (10s elapsed)
scaleway_server.store: Still creating... (20s elapsed)
scaleway_server.store: Still creating... (30s elapsed)
scaleway_server.store: Still creating... (40s elapsed)
scaleway_server.store: Still creating... (50s elapsed)
scaleway_server.store: Still creating... (1m0s elapsed)
scaleway_server.store: Still creating... (1m10s elapsed)
scaleway_server.store: Still creating... (1m20s elapsed)
scaleway_server.store: Creation complete
scaleway_volume_attachment.store.0: Creating...
  server: "" => "c0186588-ecd2-44ad-a4de-2926d3654461"
  volume: "" => "0903698a-a952-4e54-bd83-797fe02a410d"
scaleway_volume_attachment.store.2: Creating...
  server: "" => "c0186588-ecd2-44ad-a4de-2926d3654461"
  volume: "" => "e67fc95c-cee8-4dba-9d61-453e4640151a"
scaleway_volume_attachment.store.1: Creating...
  server: "" => "c0186588-ecd2-44ad-a4de-2926d3654461"
  volume: "" => "9df7d61c-41b8-45be-b376-ce927ec10709"
scaleway_volume_attachment.store.0: Still creating... (10s elapsed)
scaleway_volume_attachment.store.2: Still creating... (10s elapsed)
scaleway_volume_attachment.store.1: Still creating... (10s elapsed)
scaleway_volume_attachment.store.0: Still creating... (20s elapsed)
scaleway_volume_attachment.store.2: Still creating... (20s elapsed)
scaleway_volume_attachment.store.1: Still creating... (20s elapsed)
scaleway_volume_attachment.store.0: Still creating... (30s elapsed)
scaleway_volume_attachment.store.2: Still creating... (30s elapsed)
scaleway_volume_attachment.store.1: Still creating... (30s elapsed)
scaleway_volume_attachment.store.2: Still creating... (40s elapsed)
scaleway_volume_attachment.store.0: Still creating... (40s elapsed)
scaleway_volume_attachment.store.1: Still creating... (40s elapsed)
scaleway_volume_attachment.store.2: Still creating... (50s elapsed)
scaleway_volume_attachment.store.1: Still creating... (50s elapsed)
scaleway_volume_attachment.store.0: Still creating... (50s elapsed)
scaleway_volume_attachment.store.0: Still creating... (1m0s elapsed)
scaleway_volume_attachment.store.2: Still creating... (1m0s elapsed)
scaleway_volume_attachment.store.1: Still creating... (1m0s elapsed)
scaleway_volume_attachment.store.2: Still creating... (1m10s elapsed)
scaleway_volume_attachment.store.0: Still creating... (1m10s elapsed)
scaleway_volume_attachment.store.1: Still creating... (1m10s elapsed)
scaleway_volume_attachment.store.1: Still creating... (1m20s elapsed)
scaleway_volume_attachment.store.2: Still creating... (1m20s elapsed)
scaleway_volume_attachment.store.0: Still creating... (1m20s elapsed)
scaleway_volume_attachment.store.1: Still creating... (1m30s elapsed)
scaleway_volume_attachment.store.2: Still creating... (1m30s elapsed)
scaleway_volume_attachment.store.0: Still creating... (1m30s elapsed)
scaleway_volume_attachment.store.2: Still creating... (1m40s elapsed)
scaleway_volume_attachment.store.1: Still creating... (1m40s elapsed)
scaleway_volume_attachment.store.0: Still creating... (1m40s elapsed)
scaleway_volume_attachment.store.0: Still creating... (1m50s elapsed)
scaleway_volume_attachment.store.2: Still creating... (1m50s elapsed)
scaleway_volume_attachment.store.1: Still creating... (1m50s elapsed)
scaleway_volume_attachment.store.0: Creation complete
scaleway_volume_attachment.store.1: Still creating... (2m0s elapsed)
scaleway_volume_attachment.store.2: Still creating... (2m0s elapsed)
scaleway_volume_attachment.store.1: Still creating... (2m10s elapsed)
scaleway_volume_attachment.store.2: Still creating... (2m10s elapsed)
scaleway_volume_attachment.store.2: Still creating... (2m20s elapsed)
scaleway_volume_attachment.store.1: Still creating... (2m20s elapsed)
scaleway_volume_attachment.store.1: Still creating... (2m30s elapsed)
scaleway_volume_attachment.store.2: Still creating... (2m30s elapsed)
scaleway_volume_attachment.store.1: Still creating... (2m40s elapsed)
scaleway_volume_attachment.store.2: Still creating... (2m40s elapsed)
scaleway_volume_attachment.store.1: Still creating... (2m50s elapsed)
scaleway_volume_attachment.store.2: Still creating... (2m50s elapsed)
scaleway_volume_attachment.store.1: Still creating... (3m0s elapsed)
scaleway_volume_attachment.store.2: Still creating... (3m0s elapsed)
scaleway_volume_attachment.store.2: Still creating... (3m10s elapsed)
scaleway_volume_attachment.store.1: Still creating... (3m10s elapsed)
scaleway_volume_attachment.store.1: Still creating... (3m20s elapsed)
scaleway_volume_attachment.store.2: Still creating... (3m20s elapsed)
scaleway_volume_attachment.store.1: Still creating... (3m30s elapsed)
scaleway_volume_attachment.store.2: Still creating... (3m30s elapsed)
scaleway_volume_attachment.store.2: Still creating... (3m40s elapsed)
scaleway_volume_attachment.store.1: Still creating... (3m40s elapsed)
scaleway_volume_attachment.store.1: Still creating... (3m50s elapsed)
scaleway_volume_attachment.store.2: Still creating... (3m50s elapsed)
scaleway_volume_attachment.store.2: Creation complete
scaleway_volume_attachment.store.1: Still creating... (4m0s elapsed)
scaleway_volume_attachment.store.1: Still creating... (4m10s elapsed)
scaleway_volume_attachment.store.1: Still creating... (4m20s elapsed)
scaleway_volume_attachment.store.1: Still creating... (4m30s elapsed)
scaleway_volume_attachment.store.1: Still creating... (4m40s elapsed)
scaleway_volume_attachment.store.1: Still creating... (4m50s elapsed)
scaleway_volume_attachment.store.1: Still creating... (5m0s elapsed)
scaleway_volume_attachment.store.1: Still creating... (5m10s elapsed)
scaleway_volume_attachment.store.1: Still creating... (5m20s elapsed)
scaleway_volume_attachment.store.1: Still creating... (5m30s elapsed)
scaleway_volume_attachment.store.1: Still creating... (5m40s elapsed)
scaleway_volume_attachment.store.1: Still creating... (5m50s elapsed)
scaleway_volume_attachment.store.1: Still creating... (6m0s elapsed)
scaleway_volume_attachment.store.1: Still creating... (6m10s elapsed)
scaleway_volume_attachment.store.1: Creation complete

Apply complete! Resources: 7 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate

real	7m39.445s
user	0m0.604s
sys	0m0.606s
```

**Comment by tboerger** [comment]
And it took 11 minutes to destroy :D

**Comment by nicolai86** [comment]
@tboerger at the moment all `scaleway_volume_attachment`s are executed in serial. This makes the behaviour slow for multiple volumes, but it's correct.

A future optimization would be to add a barrier on stop & start actions, then we could batch the attachments which would speed things up considerably. 

But we should leave this off to future PRs :)

**Comment by tboerger** [comment]
True, at least it should work now properly.

**Comment by dcharbonnier** [comment]
what are we waiting to merge this ?

**Comment by stack72** [comment]
Hi @nicolai86 

Sorry for the time taken to get back to you on this one - can you rebase it for me and I can get it merged?

Paul

**Comment by nicolai86** [comment]
I've rebased the PR and also increased the timeouts 👍 

thanks for looking after this :)

**Comment by stack72** [comment]
This LGTM now @nicolai86 :) Tests are green (as always!) - will squash and merge - thanks for the awesome work as usual

```
% make testacc TEST=./builtin/providers/scaleway                                                                                           1 ↵
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/10/27 16:38:12 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/scaleway -v  -timeout 120m
=== RUN   TestAccScalewayDataSourceBootscript_Basic
--- PASS: TestAccScalewayDataSourceBootscript_Basic (2.99s)
=== RUN   TestAccScalewayDataSourceBootscript_Filtered
--- PASS: TestAccScalewayDataSourceBootscript_Filtered (2.42s)
=== RUN   TestAccScalewayDataSourceImage_Basic
--- PASS: TestAccScalewayDataSourceImage_Basic (14.49s)
=== RUN   TestAccScalewayDataSourceImage_Filtered
--- PASS: TestAccScalewayDataSourceImage_Filtered (11.31s)
=== RUN   TestAccScalewayIP_importBasic
--- PASS: TestAccScalewayIP_importBasic (2.92s)
=== RUN   TestAccScalewaySecurityGroup_importBasic
--- PASS: TestAccScalewaySecurityGroup_importBasic (3.95s)
=== RUN   TestAccScalewayServer_importBasic
--- PASS: TestAccScalewayServer_importBasic (113.34s)
=== RUN   TestAccScalewayVolume_importBasic
--- PASS: TestAccScalewayVolume_importBasic (5.91s)
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccScalewayIP_Basic
--- PASS: TestAccScalewayIP_Basic (15.24s)
=== RUN   TestAccScalewaySecurityGroupRule_Basic
--- PASS: TestAccScalewaySecurityGroupRule_Basic (7.97s)
=== RUN   TestAccScalewaySecurityGroup_Basic
--- PASS: TestAccScalewaySecurityGroup_Basic (3.83s)
=== RUN   TestAccScalewayServer_Basic
--- PASS: TestAccScalewayServer_Basic (126.03s)
=== RUN   TestAccScalewayServer_SecurityGroup
--- PASS: TestAccScalewayServer_SecurityGroup (113.99s)
=== RUN   TestAccScalewayVolumeAttachment_Basic
--- PASS: TestAccScalewayVolumeAttachment_Basic (343.90s)
=== RUN   TestAccScalewayVolume_Basic
--- PASS: TestAccScalewayVolume_Basic (6.41s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/scaleway	774.719s
```

**Comment by nicolai86** [comment]
<3 @stack72
