### PR TITLE
resolve provider types when building the config

### LINKED ISSUE #28407: TF 0.15 module with multiple openstack providers
Hi
Not sure if this is related to the openstack provider or terraform itself, but it feels more terraform related.
Trying to update a module per the warning we got when upgrading to tf 0.15 reults in Error.

### Terraform Version

```
Terraform v0.15.0
on linux_amd64
+ provider registry.terraform.io/terraform-provider-openstack/openstack v1.40.0
```

### Terraform Configuration Files

https://github.com/per-lind/tf-demo

### Debug Output

https://gist.github.com/per-lind/adfedc5a14441833738f69dfcec9a0e1
### Expected Behavior

I expected the new registry.terraform.io/terraform-provider-openstack/openstack provider to be used and no reference to the old registry.terraform.io/hashicorp/openstack
### Actual Behavior

```
 Error: Invalid type for provider module.multi_rule.provider["registry.terraform.io/terraform-provider-openstack/openstack"].Sto2
│ 
│   on main.tf line 34, in module "multi_rule":
│   34:     openstack.Sto2   = openstack.Sto2
│ 
│ Cannot use configuration from
│ provider["registry.terraform.io/hashicorp/openstack"].Sto2 for
│ module.multi_rule.provider["registry.terraform.io/terraform-provider-openstack/openstack"].Sto2.
│ The given provider configuration is for a different provider type.
```

### Steps to Reproduce

1. `terraform init`

To get the initial warning remove commented providers in modules/test/main.tf and comment line 5 in the same file. https://github.com/per-lind/tf-demo/tree/before-upgade

### PR DESCRIPTION
**Pull request by jbardin**
All the information is available to resolve provider types when building
the configuration, but some provider references still had no FQN. This
caused validation to assume a default type, and incorrectly reject valid
module calls with non-default namespaced providers.

Resolve as much provider type information as possible when loading the
config. Only use this internally for now, but this should be useful
outside of the package to avoid re-resolving the providers later on. We
can come back and find where this might be useful elsewhere, but for now
keep the change as small as possible to avoid any changes in behavior.

Fixes #28407

### CODE REVIEW

File: configs/resource.go [hunk 1]
```diff
@@ -374,6 +374,13 @@ type ProviderConfigRef struct {
 	NameRange  hcl.Range
 	Alias      string
 	AliasRange *hcl.Range // nil if alias not set
+
+	// TODO: this may not be set in some cases, so it is not yet suitable for
+	// use outside of this package. We currently only use it for internal
+	// validation, but once we verify that this can be set in all cases, we can
+	// export this so providers don't need to be re-resolved.
+	// This same field is also added to the Provider struct.
+	providerType addrs.Provider
```
Comment (mildwonkey) [inline configs/resource.go:383]: I remember wanting to set this here earlier in the provider source project; I'm glad to see this!

**Review by mildwonkey — APPROVED** [review]
LGTM! I have high hopes for that providerType field in the configs.Resource!!
