### PR TITLE
Handle module source subdirectories in Terraform

### LINKED ISSUE #16138: 0.10.6 regression: can no longer source modules from parent directory
### Terraform Version
```
$ terraform -v
Terraform v0.10.6

```

### Terraform Configuration Files
./main.tf:
```hcl
module "bug" {
  source = "./bug.tgz//foo"
}

output "out" {
  value = "${module.bug.out}"
}
```

./bug.tgz//foo/foo.tf
```hcl
module "bar" {
  source = "../bar"
}

output "out" {
  value = "${module.bar.out}"
}
```

./bug.tgz//bar/bar.tf
```hcl
output "out" {
  value = "baz"
}
```
(tarball [here](https://www.dropbox.com/s/imcvbo4th7uh7yt/issue.tgz?dl=0))

### Expected Behavior
With Terraform 0.10.5:
```
bash-4.4$ brew switch terraform 0.10.5
Cleaning /usr/local/Cellar/terraform/0.10.0
Cleaning /usr/local/Cellar/terraform/0.10.1
Cleaning /usr/local/Cellar/terraform/0.10.2
Cleaning /usr/local/Cellar/terraform/0.10.3
Cleaning /usr/local/Cellar/terraform/0.10.4
Cleaning /usr/local/Cellar/terraform/0.10.5
Cleaning /usr/local/Cellar/terraform/0.10.6
Cleaning /usr/local/Cellar/terraform/0.9.11
Cleaning /usr/local/Cellar/terraform/0.9.4
Cleaning /usr/local/Cellar/terraform/0.9.5
Cleaning /usr/local/Cellar/terraform/0.9.6
Cleaning /usr/local/Cellar/terraform/0.9.8
Cleaning /usr/local/Cellar/terraform/0.9.9
2 links created for /usr/local/Cellar/terraform/0.10.5
bash-4.4$ terraform version
Terraform v0.10.5

Your version of Terraform is out of date! The latest version
is 0.10.6. You can update by downloading from www.terraform.io
bash-4.4$ tar xzf issue.tgz
bash-4.4$ cd issue
bash-4.4$ ls -l
total 16
drwxr-xr-x  3 kreisys  staff  102 20 Sep 14:31 bar
-rw-r--r--  1 kreisys  staff  272 20 Sep 14:31 bug.tgz
drwxr-xr-x  3 kreisys  staff  102 20 Sep 13:38 foo
-rw-r--r--  1 kreisys  staff   93 20 Sep 14:17 main.tf
bash-4.4$ terraform init
Downloading modules...
Get: file:///Users/kreisys/test/issue/bug.tgz
Get: file:///Users/kreisys/test/issue/.terraform/modules/b4d22ef7134539b7ce3b264a60b62ecd/bar

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
bash-4.4$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
bash-4.4$ terraform apply

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

out = baz
```

### Actual Behavior
With Terraform 0.10.6:
```
bash-4.4$ brew switch terraform 0.10.6
Cleaning /usr/local/Cellar/terraform/0.10.0
Cleaning /usr/local/Cellar/terraform/0.10.1
Cleaning /usr/local/Cellar/terraform/0.10.2
Cleaning /usr/local/Cellar/terraform/0.10.3
Cleaning /usr/local/Cellar/terraform/0.10.4
Cleaning /usr/local/Cellar/terraform/0.10.5
Cleaning /usr/local/Cellar/terraform/0.10.6
Cleaning /usr/local/Cellar/terraform/0.9.11
Cleaning /usr/local/Cellar/terraform/0.9.4
Cleaning /usr/local/Cellar/terraform/0.9.5
Cleaning /usr/local/Cellar/terraform/0.9.6
Cleaning /usr/local/Cellar/terraform/0.9.8
Cleaning /usr/local/Cellar/terraform/0.9.9
2 links created for /usr/local/Cellar/terraform/0.10.6
bash-4.4$ terraform version
Terraform v0.10.6

bash-4.4$ tar xzf issue.tgz
bash-4.4$ cd issue
bash-4.4$ terraform init
Downloading modules...
Get: file:///Users/kreisys/test/issue/bug.tgz//foo
Error downloading modules: Error loading modules: module bar: invalid source string: ../bar
```

### Steps to Reproduce
With Terraform 0.10.6:
1. Download issue.tgz
2. `tar xzf issue.tgz`
3. `cd issue`
4. `terraform init`

### Important Factoids
This happens with GitHub-sourced modules as well and I assume with any source that utilizes that double slash (`//`) syntax to determine the root of a module collection. I used a tgz file in the repro because this doesn't happen when using the local syntax `source = "./foo"`. Interestingly, the same error occurs if I try to use the double slash syntax with a local path: `source = ".//foo"`; but I'm not sure if that's even supposed to work in the first place.

### PR DESCRIPTION
**Pull request by jbardin**
In order to remain backward compatible with some modules, we need to
handle subdirs during Load. This means duplicating part of the go-getter
code path for subDir handling so we can resolve any subDirs and globs
internally, while keeping the entire remote directory structure within
the file storage.

Module detection currently requires calling the registry to determine
the subdirectory. Since we're not directly accessing the subdirectory
through FolderStorage, and now handling it within terraform so modules can
reference sibling paths, we need to call out to the registry every
time we load a configuration to verify the subdirecory for the module,
which is returned during the Detect.

This adds a record for the detected subdirectory in the top-level of the FolderStorage path for
retrieval during Tree.Load. This lets us bypass Detection altogether,
modules can be loaded without redetecting.

Fixes #16138

### CODE REVIEW

File: config/module/get_test.go [hunk 1]
```diff
@@ -248,6 +269,54 @@ func TestDetectors(t *testing.T) {
...
+
+	if err := tree.Load(storage, GetModeGet); err != nil {
+		t.Fatalf("err: %s", err)
+	}
+
+	if !tree.Loaded() {
+		t.Fatal("should be loaded")
+	}
+
+	// This should no longer error
```
Comment (apparentlymart) [inline config/module/get_test.go]: I'm not sure what this comment is referring to... it would be helpful to elaborate on what "this" is, and what "no longer" is in reference to (i.e. in what previous situation _did_ it error?)

Comment (jbardin) [reply config/module/get_test.go]: sorry, that was a cut&paste artifact

File: config/module/get_test.go [hunk 2]
```diff
@@ -16,11 +16,26 @@ import (
...
+// Map of module names and location of test modules.
+// Only one version for now, as we only lookup latest from the registry.
+type testMod struct {
+	location string
+	version  string
+}
+
+var testMods = map[string]testMod{
+	"registry/foo/bar": {
+		location: "file:///download/registry/foo/bar/0.2.3//*?archive=tar.gz",
```
Comment (jbardin) [inline config/module/get_test.go]: I forgot the comment explaining the optional scheme prefix for these tests. (this fixture is likely to evolve in the near future anyway)

File: config/module/tree_test.go [hunk 3]
```diff
@@ -209,40 +211,120 @@ func TestTreeLoad_parentRef(t *testing.T) {
...
+	if actual != subDir {
+		t.Fatalf("expected subDir %q, got %q", subDir, actual)
+	}
+
+	// create a fake entry
+	if err := ioutil.WriteFile(subdirRecordsPath(dir), []byte("BAD DATA"), 0644); err != nil {
+		t.Fatal(err)
+	}
+
+	// this should fail because there aare now 2 entries
```
Comment (jbardin) [inline config/module/tree_test.go]: this comment and error are also out of date
