### PR TITLE
configs: Emit a warning for backends in nested modules

### LINKED ISSUE #25933: Backend config has no effect in modules
### Current Terraform Version

```
0.13.0
```

### Use-cases
When things are improperly configured or actions within terraform fail.

### Proposal
There are a few cases where things fail silently and give absolutely no feedback.

1) string interpolation in backend.

The docs say:
```
Only one backend may be specified and the configuration may not contain interpolations. Terraform will validate this.
```
 If you use string interpolation, say in the prefix value, you get no error, nothing. Terraform plan/apply does it's thing, just no state gets stored. If terraform is actually validating this, it doesn't give any feedback on its findings.

2) hard coded backend.
Similarly, without string interpolation (just a straight up string), my state was also not being stored, the target bucket was empty and again, zero feedback from terraform. 

On both of these occasions, it was a long time before I realised no state was being stored (I figured if something so fundamental had gone wrong, it would have at least shown a warning?)

If state has been configured to be stored in a bucket, and storing the state in that bucket fails, this should not be silent, terraform should shout loudly.

### PR DESCRIPTION
**Pull request by apparentlymart**
Terraform considers backend configurations only in the root module, so any declarations in child modules are entirely ignored.

To avoid users mistakenly thinking that a root module backend configuration has taken effect, we'll now emit a warning about it. This is a warning rather than an error because it's reasonable to call a module that would normally be a root module instead as a child module when writing a wrapper module to handle integration testing.

```
Warning: Backend configuration ignored

  on child/nested-backend-config-child.tf line 2, in terraform:
   2:   backend "ignored" {}

The selected backend applies to the entire configuration, so Terraform expects
provider configurations only in the root module.

This is a warning rather than an error because it's sometimes convenient to
temporarily call a root module as a child module for testing purposes, but
this backend configuration block will have no effect.
```

This closes #25933, by giving better feedback that ignoring the child module backends is by design.

### CODE REVIEW

File: configs/config_build.go [hunk 1]
```diff
@@ -78,6 +78,15 @@ func buildChildModules(parent *Config, walker ModuleWalker) (map[string]*Config,
 		child.Children, modDiags = buildChildModules(child, walker)
 		diags = append(diags, modDiags...)
 
+		if mod.Backend != nil {
+			diags = diags.Append(&hcl.Diagnostic{
+				Severity: hcl.DiagWarning,
+				Summary:  "Backend configuration ignored",
+				Detail:   "The selected backend applies to the entire configuration, so Terraform expects provider configurations only in the root module.\n\nThis is a warning rather than an error because it's sometimes convenient to temporarily call a root module as a child module for testing purposes, but this backend configuration block will have no effect.",
```
Comment (mildwonkey) [inline configs/config_build.go:85]: Super-de-duper nitpick; no worries if you disagree and don't change anything: 

My initial interpretation of this phrase, "the selected backend", is "the specific backend I am using in this configuration" as opposed to something more generic, like "Any selected backend ... ". What do you think?

**Review by mildwonkey — APPROVED** [review]

File: configs/config_build.go (hunk 1 above)
Comment (apparentlymart) [reply configs/config_build.go]: Sounds good to me! Thanks :tada:
