### PR TITLE
provider/openstack: openstack_blockstorage_volume_v2 resource

### LINKED ISSUE #2817: OpenStack Cinder v2 API Support
```
openstack_blockstorage_volume_v1.registry_data: Creating...
  attachment.#:      "" => "<computed>"
  availability_zone: "" => "<computed>"
  description:       "" => "docker registry data store"
  metadata.#:        "" => "<computed>"
  name:              "" => "tf-registry-data"
  region:            "" => "RegionOne"
  size:              "" => "40"
  volume_type:       "" => "<computed>"
openstack_blockstorage_volume_v1.registry_data: Error: 1 error(s) occurred:

* Error creating OpenStack volume: Expected HTTP response code [200 201] when accessing [POST http://controller:8776/v2/f3ea7760e6864240ba963e4be7c50826/volumes], but got 202 instead
{"volume": {"status": "creating", "user_id": "2e96f8aab7aa41f0a0797c59afe3fe92", "attachments": [], "links": [{"href": "http://controller:8776/v2/f3ea7760e6864240ba963e4be7c50826/volumes/53dfb65a-a2f0-4cd1-bb19-fd6484ee85ee", "rel": "self"}, {"href": "http://controller:8776/f3ea7760e6864240ba963e4be7c50826/volumes/53dfb65a-a2f0-4cd1-bb19-fd6484ee85ee", "rel": "bookmark"}], "availability_zone": "nova", "bootable": "false", "encrypted": false, "created_at": "2015-07-22T13:54:14.683693", "description": "docker registry data store", "volume_type": null, "name": "tf-registry-data", "replication_status": "disabled", "consistencygroup_id": null, "source_volid": null, "snapshot_id": null, "multiattach": false, "metadata": {}, "id": "53dfb65a-a2f0-4cd1-bb19-fd6484ee85ee", "size": 40}}
Error applying plan:

1 error(s) occurred:

* Error creating OpenStack volume: Expected HTTP response code [200 201] when accessing [POST http://controller:8776/v2/f3ea7760e6864240ba963e4be7c50826/volumes], but got 202 instead
{"volume": {"status": "creating", "user_id": "2e96f8aab7aa41f0a0797c59afe3fe92", "attachments": [], "links": [{"href": "http://controller:8776/v2/f3ea7760e6864240ba963e4be7c50826/volumes/53dfb65a-a2f0-4cd1-bb19-fd6484ee85ee", "rel": "self"}, {"href": "http://controller:8776/f3ea7760e6864240ba963e4be7c50826/volumes/53dfb65a-a2f0-4cd1-bb19-fd6484ee85ee", "rel": "bookmark"}], "availability_zone": "nova", "bootable": "false", "encrypted": false, "created_at": "2015-07-22T13:54:14.683693", "description": "docker registry data store", "volume_type": null, "name": "tf-registry-data", "replication_status": "disabled", "consistencygroup_id": null, "source_volid": null, "snapshot_id": null, "multiattach": false, "metadata": {}, "id": "53dfb65a-a2f0-4cd1-bb19-fd6484ee85ee", "size": 40}}
```

### PR DESCRIPTION
**Pull request by jtopjian**
This commit adds an openstack_blockstorage_volume_v2 resource. This
resource is able to create volumes using the OpenStack Block Storage
v2 API.

Fixes #2817

### CODE REVIEW

File: builtin/providers/openstack/resource_openstack_blockstorage_volume_v2.go [hunk 1]
```diff
@@ -0,0 +1,329 @@
...
+}
+
+func resourceBlockStorageVolumeV2Create(d *schema.ResourceData, meta interface{}) error {
+	config := meta.(*Config)
+	blockStorageClient, err := config.blockStorageV2Client(d.Get("region").(string))
+	if err != nil {
+		return fmt.Errorf("Error creating OpenStack block storage client: %s", err)
+	}
+
+	createOpts := &volumes.CreateOpts{
```
Comment (ncw) [inline builtin/providers/openstack/resource_openstack_blockstorage_volume_v2.go]: This is missing the new parameters `ConsistencyGroupID` and `SourceReplica`.  If you add these you'll need to add them to the docs too!

(Not a team member, just have a set of patches doing the same thing ;-)

Comment (jtopjian) [inline builtin/providers/openstack/resource_openstack_blockstorage_volume_v2.go]: @ncw Good catch. An updated commit is on its way!
