### PR TITLE
preserve resource private data on error

### LINKED ISSUE #27452: resource's custom deletion timeout is not respected after the initial terraform destroy
### Terraform Version

```
$ terraform --version
Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/aws v3.23.0
```

### Terraform Configuration Files

```terraform
provider "aws" {
  access_key = var.ACCESS_KEY_ID
  secret_key = var.SECRET_ACCESS_KEY
  region     = "eu-west-1"
}

resource "aws_vpc" "vpc" {
  cidr_block           = "10.250.0.0/16"
  enable_dns_support   = true
  enable_dns_hostnames = true
}

resource "aws_subnet" "subnet" {
  vpc_id            = aws_vpc.vpc.id
  cidr_block        = "10.250.32.0/20"
  availability_zone = "eu-west-1a"

  timeouts {
    create = "5m"
    delete = "5m"
  }
}
```

### Expected Behavior
`terraform destroy` after the initial one should respect the aws_subnet custom deletion timeout.

### Actual Behavior
`terraform destroy` after the initial one does not respect the aws_subnet custom deletion timeout.

### Steps to Reproduce

1. `terraform apply`

```
$ terraform apply -var-file=creds.tfvars

aws_vpc.vpc: Creating...
aws_vpc.vpc: Creation complete after 6s [id=vpc-1234]
aws_subnet.subnet: Creating...
aws_subnet.subnet: Creation complete after 1s [id=subnet-1234]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
```

Ensure that in the `terraform.tfstate` the subnet contains:

```
            "timeouts": {
              "create": "5m",
              "delete": "5m"
            },
```

2. Add a dependency that blocks the deletion of the subnet

For example launch a sample ec2 instance that use the vpc and subnet from above. Our goal is to have a dependent resource that would block the subnet deletion.

3. `terraform destroy`

Ensure that the initial terraform destroy behaves as expected and the aws_subnet deletion times out after the configured timeout (`5m`):

```
$ terraform destroy -var-file=creds.tfvars

aws_subnet.subnet: Destroying... [id=subnet-1234]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 10s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 20s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 30s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 40s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 50s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 1m0s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 1m10s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 1m20s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 1m30s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 1m40s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 1m50s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 2m0s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 2m10s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 2m20s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 2m30s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 2m40s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 2m50s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 3m0s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 3m10s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 3m20s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 3m30s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 3m40s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 3m50s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 4m0s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 4m10s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 4m20s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 4m30s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 4m40s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 4m50s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 5m0s elapsed]

Error: error deleting subnet (subnet-1234): timeout while waiting for state to become 'destroyed' (last state: 'pending', timeout: 5m0s)
```

4. Ensure that subsequent `terraform destroy`s do not respect the aws_subnet deletion timeout

```
$ terraform destroy -var-file=creds.tfvars

aws_subnet.subnet: Destroying... [id=subnet-1234]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 10s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 20s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 30s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 40s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 50s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 1m0s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 1m10s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 1m20s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 1m30s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 1m40s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 1m50s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 2m0s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 2m10s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 2m20s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 2m30s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 2m40s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 2m50s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 3m0s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 3m10s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 3m20s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 3m30s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 3m40s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 3m50s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 4m0s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 4m10s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 4m20s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 4m30s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 4m40s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 4m50s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 5m0s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 5m10s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 5m20s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 5m30s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 5m40s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 5m50s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 6m0s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 6m10s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 6m20s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 6m30s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 6m40s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 6m50s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 7m0s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 7m10s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 7m20s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 7m30s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 7m40s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 7m50s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 8m0s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 8m10s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 8m20s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 8m30s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 8m40s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 8m50s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 9m0s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 9m10s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 9m20s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 9m30s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 9m40s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 9m51s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 10m1s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 10m11s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 10m21s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 10m31s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 10m41s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 10m51s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 11m1s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 11m11s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 11m21s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 11m31s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 11m41s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 11m51s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 12m1s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 12m11s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 12m21s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 12m31s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 12m41s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 12m51s elapsed]
aws_subnet.subnet: Still destroying... [id=subnet-1234, 13m1s elapsed]
```

### References

This issue was also reported in several terraform providers and I was advised to move the issue under hashicorp/terraform. Please also see:
- https://github.com/hashicorp/terraform-provider-aws/issues/16910
- https://github.com/aliyun/terraform-provider-alicloud/issues/2734

### PR DESCRIPTION
**Pull request by jbardin**
If the provider returns an empty response during apply, we restore the
prior state for the resource, but the private data was not being
restored.

Fixes #27452

### CODE REVIEW

File: terraform/node_resource_abstract_instance.go [hunk 1]
```diff
@@ -2084,18 +2083,12 @@ func (n *NodeAbstractResourceInstance) apply(
...
-		if state.Status == states.ObjectTainted {
-			newStatus = states.ObjectTainted
-		}
+		newState = state.DeepCopy()
 	}
 
 	if !newVal.IsNull() { // null value indicates that the object is deleted, so we won't set a new state in that case
 		newState = &states.ResourceInstanceObject{
-			Status:              newStatus,
+			Status:              states.ObjectReady,
```
Comment (mildwonkey) [inline terraform/node_resource_abstract_instance.go:2091]: What happens if the object was tainted? Should this be `newState.Status`?

Comment (mildwonkey) [reply terraform/node_resource_abstract_instance.go:2091]: James pointed out what I was missing in slack:
> newStatus is only set to tainted if the the value is null, but then only assigned if the value is not null

**Review by mildwonkey — APPROVED** [review]

File: terraform/node_resource_abstract_instance.go (hunk 1 above)
Comment (jbardin) [reply terraform/node_resource_abstract_instance.go:2091]: `newStatus` could only be set to `ObjectTainted` is `newVal` is null, but this requires that `newVal` is not null so it would never be set; so there is no change in behavior here.

I do think that we may lose the `ObjectTainted` status if a provider errors when removing a tainted object _and_ returns a non-null value. Most providers wouldn't be capable of doing this right now, but I'll make sure it's covered in another PR.
