### PR TITLE
Ignore undeclared variable values from the cloud backend

### LINKED ISSUE #38475: Error: Value for undeclared variable
### Terraform Version

```shell
terraform version 
Terraform v1.15.0
on windows_amd64
```

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Expected Behavior

Warning: Value for undeclared variable.

Terraform Plan / Terraform Apply continues

### Actual Behavior

Error: Value for undeclared variable

Terraform Plan / Terraform Apply fails

### Steps to Reproduce

1. Define variable in Terraform Cloud
2. Do not define any variables in configuration files 
3. Terraform init 
4. Terraform plan 

### Additional Context

Our jobs are backed by Terraform Cloud. 

It is showing as a warning in a few workspace but 99% of the time it is erroring out. 

When pinning the version to 1.14.8 on failing workspaces it starts to succeed 

### References

_No response_

### Generative AI / LLM assisted development?

_No response_

### PR DESCRIPTION
**Pull request by dbanck**
We added variables to all commands that interact with configuration in #38276. For users of the cloud backend, we fetch the variable values from HCP Terraform.

Before the change, the code for fetching variables was using by 5 commands: `console`, `graph`, `providers schema`, `state show`, and `import`. But the first four [stubbed variables by default](https://github.com/hashicorp/terraform/blob/1d517c3ae8970d0ee790a1c82efcc2c293ad4d29/internal/cloud/backend_context.go#L94), so only the `import` command ended up fetching variables from HCP Terraform and raising the `Value for undeclared variable` error.

The error is a result of treating remote variable values like CLI supplied ones:
https://github.com/hashicorp/terraform/blob/e6850a514f818187fd498ea4c055adbd485e978b/internal/cloud/backend_context.go#L298-L307

By reusing the same logic for fetching and parsing variables for many more commands now than just `import`,  we make this behavior much more visible. 

The new value source type will not raise any diagnostics or warnings when running any of the commands that accept variables now. With the tradeoff, that running `import` with the cloud backend will now also not raise these kind of diagnostics anymore. 

Fixes #38475

## Target Release

1.15.1

## Rollback Plan

- [x] If a change needs to be reverted, we will roll out an update to the code within 7 days.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

## CHANGELOG entry

- [x] This change is user-facing and I added a changelog entry.
- [ ] This change is not user-facing.

### CODE REVIEW

**Review by jbardin — DISMISSED** [review]

**Review by jbardin — APPROVED** [review]

File: internal/cloud/backend_context.go [hunk 1]
```diff
@@ -303,6 +303,6 @@ func (v *remoteStoredVariableValue) ParseVariableValue(mode configs.VariablePars
 		// roughly speaking, a similar idea to entering variable values at
 		// the interactive CLI prompts. It's not a perfect correspondance,
 		// but it's closer than the other options.
```
Comment (dsa0x) [inline internal/cloud/backend_context.go:305]: We would need to update these comments at some point

Comment (dbanck) [reply internal/cloud/backend_context.go:305]: Good catch 😅
