### PR TITLE
provider/azurerm: Add support for storage container name validation

### LINKED ISSUE #6846: Check for invalid characters within azurerm_storage_container
When running Terraform 0.6.16 with the azurerm provider I noticed that `plan` accepts invalid characters for a `azurerm_storage_container` which will fail when applying the changes to Azure.

```
resource "azurerm_storage_container" "chef_linux_container" {
    name = "linux_disk"
    resource_group_name = "${azurerm_resource_group.chef_test_rg.name}"
    storage_account_name = "${azurerm_storage_account.chef_test_storage.name}"
    container_access_type = "private"
}
```

> Error applying plan:
> 
> 1 error(s) occurred:
> 
> * azurerm_storage_container.chef_linux_container: Error creating container "linux_disk" in storage account "cts20160524": storage: service returned error: StatusCode=400, ErrorCode=InvalidResourceName, ErrorMessage=The specifed resource name contains invalid characters.
> RequestId:7f2285a8-0001-009d-1ab6-b52384000000
> Time:2016-05-24T12:18:24.3800597Z, RequestId=7f2285a8-0001-009d-1ab6-b52384000000, QueryParameterName=, QueryParameterValue=

When you remove `_` it works.
```
resource "azurerm_storage_container" "chef_linux_container" {
    name = "linuxdisk"
    resource_group_name = "${azurerm_resource_group.chef_test_rg.name}"
    storage_account_name = "${azurerm_storage_account.chef_test_storage.name}"
    container_access_type = "private"
}
```

### PR DESCRIPTION
**Pull request by stack72**
Fixes #6846

```
make testacc TEST=./builtin/providers/azurerm TESTARGS='-run=TestValidateArmStorageContainerName'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /vendor/)
TF_ACC=1 go test ./builtin/providers/azurerm -v -run=TestValidateArmStorageContainerName -timeout 120m
=== RUN   TestValidateArmStorageContainerName
--- PASS: TestValidateArmStorageContainerName (0.00s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/azurerm        0.012s
```

### CODE REVIEW

File: builtin/providers/azurerm/resource_arm_storage_container.go [hunk 1]
```diff
@@ -7,6 +7,7 @@ import (
 
 	"github.com/Azure/azure-sdk-for-go/storage"
 	"github.com/hashicorp/terraform/helper/schema"
+	"regexp"
```
Comment (jen20) [inline builtin/providers/azurerm/resource_arm_storage_container.go]: This needs running through `goimports`

File: builtin/providers/azurerm/resource_arm_storage_container.go [hunk 2]
```diff
@@ -47,6 +49,24 @@ func resourceArmStorageContainer() *schema.Resource {
 	}
 }
 
+func validateArmStorageContainerName(v interface{}, k string) (ws []string, errors []error) {
```
Comment (jen20) [inline builtin/providers/azurerm/resource_arm_storage_container.go]: Can we put a link to the relevant document in a comment here so we can refer to it easily in future?

**Comment by jen20** [comment]
Left two comments in line but other than that LGTM!

**Comment by stack72** [comment]
@jen20 made the 2 small changes you asked for - will merge when (if?) Travis goes green :)
