### PR TITLE
account for deposed in terraform show

### LINKED ISSUE #21770: panic: runtime error: invalid memory address or nil pointer dereference
### Terraform Version

```
Terraform v0.12.2
+ provider.aws v2.15.0
+ provider.cloudflare v1.15.0
+ provider.mongodbatlas v1.1.0
```

### Terraform Configuration Files

main.tf
```hcl
terraform {
  backend "remote" {
    organization = "org"

    workspaces {
      prefix = "superlife-"
    }
  }
}
```

versions.tf
```hcl
terraform {
  required_version = ">= 0.12"
}
```

provider.tf
```hcl
provider "aws" {
  version = "~> 2.12"
  region  = "ap-southeast-2"

  //Set AWS_ACCESS_KEY_ID & AWS_SECRET_ACCESS_KEY env variables
}

provider "cloudflare" {
  version = "~> 1.15"

  //Set CLOUDFLARE_TOKEN and CLOUDFLARE_EMAIL env variables
}

provider "mongodbatlas" {
  version = "~> 1.1.0"
  // Set MONGODB_ATLAS_USERNAME and MONGODB_ATLAS_API_KEY env variables
}
```

superlife.tf
```hcl
variable "pvt_key" {
}

variable "pub_key" {
}

variable "docker_pass" {
  type = string
}

variable "docker_user" {
  type = string
}

variable "PORT" {
  type = string
}

variable "SSL_PORT" {
  type = string
}

resource "aws_key_pair" "deployer" {
  key_name   = "${terraform.workspace}_deployer_key"
  public_key = file(var.pub_key)
}

resource "aws_security_group" "allow_ssh" {
  name        = "${terraform.workspace}_allow_ssh"
  description = "Allow ssh inbound traffic"

  ingress {
    # TLS (change to whatever ports you need)
    from_port = 22
    to_port   = 22
    protocol  = "tcp"

    # TODO: Please restrict your ingress to only necessary IPs and ports.
    # Opening to 0.0.0.0/0 can lead to security vulnerabilities.
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name = "ssh"
  }
}

resource "aws_security_group" "allow_http" {
  name        = "${terraform.workspace}_allow_http"
  description = "Allow http inbound traffic"

  ingress {
    # TLS (change to whatever ports you need)
    from_port = 80
    to_port   = 80
    protocol  = "tcp"

    # TODO: Please restrict your ingress to only necessary IPs and ports.
    # Opening to 0.0.0.0/0 can lead to security vulnerabilities.
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name = "http"
  }
}

resource "aws_security_group" "allow_https" {
  name        = "${terraform.workspace}_allow_https"
  description = "Allow https inbound traffic"

  ingress {
    # TLS (change to whatever ports you need)
    from_port = 443
    to_port   = 443
    protocol  = "tcp"

    # TODO: Please restrict your ingress to only necessary IPs and ports.
    # Opening to 0.0.0.0/0 can lead to security vulnerabilities.
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name = "https"
  }
}

resource "aws_security_group" "allow_outbound_tls_mail" {
  name        = "${terraform.workspace}_allow_outbound_tls_mail"
  description = "Allow tls and mail outbound traffic"

  egress {
    # TLS (change to whatever ports you need)
    from_port = 443
    to_port   = 443
    protocol  = "tcp"

    # TODO: Please restrict your egress to github only.
    # See https://help.github.com/en/articles/about-githubs-ip-addresses
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    # TLS (change to whatever ports you need)
    from_port = 465
    to_port   = 465
    protocol  = "tcp"

    # TODO: Please restrict your egress to github only.
    # See https://help.github.com/en/articles/about-githubs-ip-addresses
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name = "allow_outbound_tls_mail"
  }
}

resource "aws_security_group" "allow_outbound_http" {
  name        = "${terraform.workspace}_allow_outbound_http"
  description = "Allow http outbound traffic"

  egress {
    # TLS (change to whatever ports you need)
    from_port = 80
    to_port   = 80
    protocol  = "tcp"

    # TODO: Please restrict your egress to github only.
    # See https://help.github.com/en/articles/about-githubs-ip-addresses
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name = "allow_outbound_http"
  }
}

resource "aws_eip" "superlife_public_ip" {
  lifecycle {
    create_before_destroy = true
  }
}

output "eip" { value = "${aws_eip.superlife_public_ip.public_ip}" }

resource "aws_eip_association" "superlife_public_ip_assoc" {
  instance_id   = aws_instance.superlife.id
  allocation_id = aws_eip.superlife_public_ip.id

  lifecycle {
    create_before_destroy = true
  }
}

resource "cloudflare_record" "superlife" {
  domain  = "org.com.au"
  name    = "${terraform.workspace}-superlife"
  value   = aws_eip.superlife_public_ip.public_ip
  type    = "A"
  proxied = true

  lifecycle {
    create_before_destroy = true
  }
}

output "hostname" { value = "${cloudflare_record.superlife.hostname}" }


data "aws_region" "current" {
}

# TODO have a globals terraform script that
# does things we only want to do once across all
# environments. That's were we would create
# mongodbatlas_project.superlife 
data "mongodbatlas_project" "superlife" {
  name = "superlife"
}

resource "mongodbatlas_cluster" "superlife" {
  name                  = "${terraform.workspace}-superlife"
  group                 = "${data.mongodbatlas_project.superlife.id}"
  mongodb_major_version = "4.0"
  provider_name         = "AWS"
  region                = "AP_SOUTHEAST_2"
  size                  = "M10"
  backup                = true

  lifecycle {
    create_before_destroy = true
  }
}

output "mongo_uri" { value = "${mongodbatlas_cluster.superlife.mongo_uri}" }
output "mongo_uri_with_options" { value = "${mongodbatlas_cluster.superlife.mongo_uri_with_options}" }
output "srv_address" { value = "${mongodbatlas_cluster.superlife.srv_address}" }
output "replication_spec" { value = "${mongodbatlas_cluster.superlife.replication_spec}" }

resource "aws_instance" "superlife" {
  depends_on    = ["mongodbatlas_cluster.superlife"]
  ami           = "ami-0b76c3b150c6b1423"
  instance_type = "t2.medium"
  monitoring    = "true"
  key_name      = "${terraform.workspace}_deployer_key"

  root_block_device {
    volume_size = "16"
  }

  security_groups = [
    "${terraform.workspace}_allow_ssh",
    "${terraform.workspace}_allow_http",
    "${terraform.workspace}_allow_https",
    "${terraform.workspace}_allow_outbound_tls_mail",
    "${terraform.workspace}_allow_outbound_http",
  ]

  tags = {
    Name = "superlife-${terraform.workspace}"
  }

  lifecycle {
    create_before_destroy = true
  }

  connection {
    host        = coalesce(self.public_ip, self.private_ip)
    user        = "ubuntu"
    type        = "ssh"
    private_key = file(var.pvt_key)
    timeout     = "2m"
  }

  provisioner "local-exec" {
    command = "tar zcvf proxy.tgz -C .. proxy && tar zcvf cache.tgz -C .. cache"
  }

  provisioner "file" {
    source      = "../docker-compose.yml"
    destination = "/home/ubuntu/docker-compose.yml"
  }

  provisioner "file" {
    source      = "../docker-compose.override.yml"
    destination = "/home/ubuntu/docker-compose.override.yml"
  }

  # environment config

  provisioner "file" {
    source      = "../common.env"
    destination = "/home/ubuntu/common.env"
  }

  provisioner "file" {
    source      = "../common.env"
    destination = "/home/ubuntu/.env"
  }

  provisioner "file" {
    source      = "../common.bank.env"
    destination = "/home/ubuntu/common.bank.env"
  }
  provisioner "file" {
    source      = "../common.rewards.env"
    destination = "/home/ubuntu/common.rewards.env"
  }
  provisioner "file" {
    source      = "../${terraform.workspace}.env"
    destination = "/home/ubuntu/${terraform.workspace}.env"
  }
  provisioner "file" {
    source      = "../${terraform.workspace}.bank.env"
    destination = "/home/ubuntu/${terraform.workspace}.bank.env"
  }
  provisioner "file" {
    source      = "../${terraform.workspace}.rewards.env"
    destination = "/home/ubuntu/${terraform.workspace}.rewards.env"
  }

  # proxy config and proxied services cache

  provisioner "file" {
    source      = "proxy.tgz"
    destination = "/home/ubuntu/proxy.tgz"
  }
  provisioner "file" {
    source      = "cache.tgz"
    destination = "/home/ubuntu/cache.tgz"
  }
  provisioner "remote-exec" {
    inline = [
      "ls",
      "sudo apt-get --yes update",
      "sudo apt-get --yes install apt-transport-https ca-certificates curl gnupg-agent software-properties-common",
      "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -",
      "sudo apt-key fingerprint 0EBFCD88",
      "sudo add-apt-repository \"deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable\"",
      "sudo apt-get --yes update",
      "sudo apt-get --yes install docker-ce docker-ce-cli containerd.io",
      "docker --version",
      "sudo systemctl enable docker",
      "sudo systemctl start docker",
      "sudo groupadd docker",
      "sudo usermod -aG docker $USER",
      "curl -L \"https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)\" -o /home/ubuntu/docker-compose",
      "chmod +x /home/ubuntu/docker-compose",
      "/home/ubuntu/docker-compose --version",
    ]
  }
  provisioner "remote-exec" {
    # unzip the files needed to build the docker images
    inline = [
      ...
    ]
  }
  provisioner "local-exec" {
    command = <<EOT
fail_count=1

while true
do
  wget --header 'Accept: application/json' --tries=1 --no-check-certificate --timeout=3 -S -q 'https://${self.public_ip}/kitchenSink' -O /dev/null

  if [ $? -eq 0 ] ; then
    echo "$(date -u) ================================================================================"
    echo "$(date -u) Server available"
    echo "$(date -u)   Addresses:"
    echo "$(date -u)     elastic: ${aws_eip.superlife_public_ip.public_ip}"
    echo "$(date -u)     hostname: ${cloudflare_record.superlife.hostname}"
    echo "$(date -u) ================================================================================"    
    exit 0
  else
    if [ $fail_count -eq 61 ]; then
      echo "$(date -u) Server unavailable"
      exit 2
    else
      echo "$(date -u) Attempt $${fail_count}/60: Server not yet available"
      sleep 3
      fail_count=$(($${fail_count} + 1))
    fi
  fi
done

EOT

  }
}
```
### Debug Output

https://gist.github.com/tompahoward/3776b869694c75630fcfb9a9962e9dc8

### Crash Output

https://gist.github.com/tompahoward/e2d4e41dc99e263b7dd0e8ea1e72e30e

### Expected Behavior

Not crash

### Actual Behavior

Crashed

### Steps to Reproduce

Workspace is in a strange stage. Previously did and `plan` and `apply`. Now when trying to taint an was instance, it fails with 
```
Resource instance aws_instance.superlife is currently part-way through a
create_before_destroy replacement action. Run "terraform apply" to complete
its replacement before tainting it.
```

So trying to figure out what's going on. ran `terraform refresh` and `terraform show`. The later resulted in the crash.

### PR DESCRIPTION
**Pull request by jbardin**
Account for deposed instances in show command.
Prevent crash if the current instance is missing.

Besides preventing the panic, this will also add `(N deposed)` to the resource address line, similar to other state outputs.

Fixes #21770

### CODE REVIEW

**Comment by apparentlymart** [comment]
Hmm... I thought we'd already fixed this but I guess that was for the plan rendering rather than for the state rendering.

I believe in the plan we render each object separately rather than rolling up the deposed objects to just be a count in the header, since otherwise there's no way for the user to see the attributes of the deposed objects. For consistency, I'd lean towards making the output be shaped more like this, if that isn't a lot of extra work:

```
# test_resource.baz[0]
resource "test_resource" "baz" {
    woozles = "confuzles"
     nested {
        value = "42"
    }
}

# test_resource.baz[0] deposed object abcd1234
resource "test_resource" "baz" {
    woozles = "confuzles"
     nested {
        value = "42"
    }
}
```

I don't remember if that's _exactly_ how we annotated the deposed objects in the plan; if you can find that then my intent here was to output here in the same format.

(There's an open issue somewhere else to explain better what "deposed" means, but we don't need to solve that here; we already have mentions like this in the UI, so this won't make it any worse.)

---

As an aside... I had no idea there was a special case in `terraform taint` to reject tainting when there's a deposed object present. How long has _that_ been there? :thinking:

**Comment by jbardin** [comment]
I actually reduced the output to match the old count notation, but If we both agree that listing deposed instances completely is favorable, I'll go ahead and refactor this.

**Comment by apparentlymart** [comment]
We do still use the "(n deposed)" notation internally in the tests because it's mimicking the old test string generator for compatibility with the old tests, but since the deposed objects now have unique ids associated we started showing them explicitly and in full in the UI when relevant so that users would be able to correlate the deposed objects they see in different contexts.

**Comment by jbardin** [comment]
Updated the output to include all deposed objects individually, annotated as so:

```
# test_resource.baz[0]:
resource "test_resource" "baz" {
    woozles = "confuzles"

    nested {
        value = "42"
    }
}

# test_resource.baz[0]: (deposed object 1234)
resource "test_resource" "baz" {
    woozles = "confuzles"

    nested {
        value = "42"
    }
}
```

File: command/format/state.go [hunk 1]
```diff
@@ -98,78 +98,109 @@ func formatStateModule(p blockBodyDiffPrinter, m *states.Module, schemas *terraf
...
-				schema, _ = schemas.ResourceTypeConfig(
-					provider,
-					addr.Mode,
-					addr.Type,
-				)
-				if schema == nil {
-					p.buf.WriteString(fmt.Sprintf(
-						"# missing schema for provider %q resource type %s\n\n", provider, addr.Type))
+			// sort the deposed objects
+			sort.Slice(instances[1:], func(i, j int) bool {
```
Comment (pselle) [inline command/format/state.go]: What do these numbers mean? A comment would be helpful to clarify why

File: command/format/state.go [hunk 2]
```diff
@@ -98,78 +98,109 @@ func formatStateModule(p blockBodyDiffPrinter, m *states.Module, schemas *terraf
...
+				return instances[i+1].header < instances[j+1].header
+			})
+
+			for _, obj := range instances {
+				header := obj.header
+				instance := obj.instance
+				p.buf.WriteString(header)
+				if instance == nil {
```
Comment (pselle) [inline command/format/state.go]: Is this the only usage of `instance`? If so why not use `obj.instance`?

Comment (jbardin) [reply command/format/state.go]: Ah, `instance` is created because it's in `instance.Decode` further down.

Comment (pselle) [reply command/format/state.go]: Cool, missed it in the diff, thanks!
