### PR TITLE
[MS] provider/azurerm: fixes for bug #8227 and bug #11226

### LINKED ISSUE #8227: azurerm_subnet does not track route_table_id association.
### Terraform Version

Terraform v0.7.0
### Affected Resource(s)
- azurerm_subnet
### Terraform Configuration Files

``` hcl
resource "azurerm_resource_group" "test" {
    name = "acceptanceTestResourceGroup1"
    location = "West US"
}

resource "azurerm_virtual_network" "test" {
    name = "acceptanceTestVirtualNetwork1"
    address_space = ["10.0.0.0/16"]
    location = "West US"
    resource_group_name = "${azurerm_resource_group.test.name}"
}

resource "azurerm_subnet" "test" {
    name = "testsubnet"
    resource_group_name = "${azurerm_resource_group.test.name}"
    virtual_network_name = "${azurerm_virtual_network.test.name}"
    address_prefix = "10.0.1.0/24"
    route_table_id = "${azurerm_route_table.test.id}"
}

resource "azurerm_route_table" "test" {
    name = "acceptanceTestRouteTable1"
    location = "West US"
    resource_group_name = "${azurerm_resource_group.test.name}"
}
```
### Expected Behavior

The plan should detect that the subnet is not associated with the route table.
### Actual Behavior

No differences were detected.
### Steps to Reproduce
1. `terraform apply`
2. Manually disassociate the subnet and route table (either azure cli or azure portal)
   Portal; You can disassociate by drilling down through  ResourceGroup->RouteTable->Subnets-> Click on ... to dissassociate.
3. `terraform plan`

### PR DESCRIPTION
**Pull request by echuvyrov**
This PR should partially fix #8227 and #11226 which I believe is a duplicate of #8227. The fix should preserve all of the subnet properties, including routeTable association, on vNet update.

### CODE REVIEW

File: builtin/providers/azurerm/resource_arm_virtual_network.go [hunk 1]
```diff
@@ -268,6 +293,40 @@ func resourceAzureSubnetHash(v interface{}) int {
 	}
 	return hashcode.String(subnet)
 }
+func getExistingSubnet(resGroup string, vnetName string, subnetName string, meta interface{}) network.Subnet {
```
Comment (tombuildsstuff) [inline builtin/providers/azurerm/resource_arm_virtual_network.go]: In order to raise an error, can we update this to return a `(*network.Subnet, error)`?

**Comment by echuvyrov** [comment]
@tombuildsstuff I made the changes requested and removed the route_table definition from the vNet - additional tests revealed that there was a collision between this way to add route table to subnet and the other, more preferred way (as a root-level resource). Please review and let me know if the changes address all the comments you've raised.

File: builtin/providers/azurerm/resource_arm_subnet_test.go [hunk 2]
```diff
@@ -171,3 +257,108 @@ resource "azurerm_route" "test" {
...
+resource "azurerm_subnet" "test" {
+    name = "acctestsubnet%d"
+    resource_group_name = "${azurerm_resource_group.test.name}"
+    virtual_network_name = "${azurerm_virtual_network.test.name}"
+    address_prefix = "10.0.2.0/24"
+	route_table_id       = "${azurerm_route_table.test.id}"
+}
+
+resource "azurerm_route_table" "test" {
+  name                = "test-RT"
```
Comment (tombuildsstuff) [inline builtin/providers/azurerm/resource_arm_subnet_test.go]: can we rename this `acctest-%d`, to ensure it's unique across test runs?

File: builtin/providers/azurerm/resource_arm_subnet_test.go [hunk 3]
```diff
@@ -171,3 +257,108 @@ resource "azurerm_route" "test" {
...
+  location            = "West US"
+  resource_group_name = "${azurerm_resource_group.test.name}"
+}
+
+resource "azurerm_route" "route_a" {
+  name                = "TestRouteA"
```
Comment (tombuildsstuff) [inline builtin/providers/azurerm/resource_arm_subnet_test.go]: (same here)

File: builtin/providers/azurerm/resource_arm_subnet_test.go [hunk 4]
```diff
@@ -171,3 +257,108 @@ resource "azurerm_route" "test" {
...
+resource "azurerm_resource_group" "test" {
+    name = "acctestRG-%d"
+    location = "West US"
+	tags {
+		environment = "Testing"
+	}
+}
+
+resource "azurerm_network_security_group" "test_secgroup" {
+    name = "acceptanceTestSecurityGroup1"
```
Comment (tombuildsstuff) [inline builtin/providers/azurerm/resource_arm_subnet_test.go]: (same here)

File: builtin/providers/azurerm/resource_arm_subnet_test.go [hunk 5]
```diff
@@ -171,3 +257,108 @@ resource "azurerm_route" "test" {
...
+  name                = "test-RT"
+  location            = "West US"
+  resource_group_name = "${azurerm_resource_group.test.name}"
+  tags {
+    environment = "Testing"
+  }
+}
+
+resource "azurerm_route" "route_a" {
+  name                = "TestRouteA"
```
Comment (tombuildsstuff) [inline builtin/providers/azurerm/resource_arm_subnet_test.go]: (same here)

File: builtin/providers/azurerm/resource_arm_subnet_test.go [hunk 6]
```diff
@@ -171,3 +257,108 @@ resource "azurerm_route" "test" {
...
+resource "azurerm_subnet" "test" {
+    name = "acctestsubnet%d"
+    resource_group_name = "${azurerm_resource_group.test.name}"
+    virtual_network_name = "${azurerm_virtual_network.test.name}"
+    address_prefix = "10.0.2.0/24"
+	route_table_id       = "${azurerm_route_table.test.id}"
+}
+
+resource "azurerm_route_table" "test" {
+  name                = "test-RT"
```
Comment (tombuildsstuff) [inline builtin/providers/azurerm/resource_arm_subnet_test.go]: (same here)

File: builtin/providers/azurerm/resource_arm_virtual_network.go [hunk 7]
```diff
@@ -257,16 +278,55 @@ func getVirtualNetworkProperties(d *schema.ResourceData) *network.VirtualNetwork
 			DNSServers: &dnses,
 		},
 		Subnets: &subnets,
-	}
+	}, nil
```
Comment (tombuildsstuff) [inline builtin/providers/azurerm/resource_arm_virtual_network.go]: given we're returning two objects here, IMO this would read cleaner if we assigned this to a variable and then returned those, e.g.:

```
properties := &network....
return properties, nil
```

File: builtin/providers/azurerm/resource_arm_virtual_network.go [hunk 8]
```diff
@@ -257,16 +278,55 @@ func getVirtualNetworkProperties(d *schema.ResourceData) *network.VirtualNetwork
...
 	m := v.(map[string]interface{})
-	subnet := m["name"].(string) + m["address_prefix"].(string)
-	if securityGroup, present := m["security_group"]; present {
-		subnet = subnet + securityGroup.(string)
+	buf.WriteString(fmt.Sprintf("%s-", m["name"].(string)))
+	buf.WriteString(fmt.Sprintf("%s-", m["address_prefix"].(string)))
+	if m["security_group"] != nil {
+		buf.WriteString(fmt.Sprintf("%s-", m["security_group"].(string)))
+	}
+	return hashcode.String(buf.String())
```
Comment (tombuildsstuff) [inline builtin/providers/azurerm/resource_arm_virtual_network.go]: given a `-` has been added at the end of each value this hash code is going to be different, and thus a change will show up as required on the plan. To avoid this, we can either [increment the Schema Version and write a State Migration](XXX) - or just remove the `-` from these strings (which I would suggest here :))

File: builtin/providers/azurerm/resource_arm_virtual_network.go [hunk 9]
```diff
@@ -257,16 +278,55 @@ func getVirtualNetworkProperties(d *schema.ResourceData) *network.VirtualNetwork
...
 
 func resourceAzureSubnetHash(v interface{}) int {
+	var buf bytes.Buffer
 	m := v.(map[string]interface{})
-	subnet := m["name"].(string) + m["address_prefix"].(string)
-	if securityGroup, present := m["security_group"]; present {
-		subnet = subnet + securityGroup.(string)
+	buf.WriteString(fmt.Sprintf("%s-", m["name"].(string)))
+	buf.WriteString(fmt.Sprintf("%s-", m["address_prefix"].(string)))
+	if m["security_group"] != nil {
```
Comment (tombuildsstuff) [inline builtin/providers/azurerm/resource_arm_virtual_network.go]: I believe we can make this cleaner by using:

```
if v, ok := m["security_group"]; ok {
 buf.WriteString(v.(string))
}
```

File: builtin/providers/azurerm/resource_arm_subnet_test.go [hunk 10]
```diff
@@ -171,3 +257,108 @@ resource "azurerm_route" "test" {
 	next_hop_in_ip_address = "10.10.1.1" 
 }
 `
+
+var testAccAzureRMSubnet_routeTable = `
```
Comment (tombuildsstuff) [inline builtin/providers/azurerm/resource_arm_subnet_test.go]: FYI for newer test config's we're tending to make these functions which take an Int and handle formatting the string, rather than spreading the string format throughout the test functions (given we're now using them in multiple places), i.e.
```
func testAccAzureRMSubnet_routeTable(rInt int) string {
 return fmt.Sprintf(....., rInt,rInt)
}
```

**Comment by echuvyrov** [comment]
@tombuildsstuff I made the changes requested, I think those will definitely improve code - thanks so much!
