### PR TITLE
provider/aws: Fix issue with checking for ElastiCache cluster status

### LINKED ISSUE #2732: aws: aws_elasticache_cluster doesn't wait till completed
Haven't looked at the aws library to see if this is possible but the aws_elasticache_cluster creation at least for redis doesn't wait until a cache node is created so anything referencing the attribute will fail. 

For example

```
resource "aws_elasticache_cluster" "logstash-redis" {
  cluster_id = "web-logstash-redis"
  engine = "redis"
  node_type = "cache.m3.medium"
  num_cache_nodes = 1
  parameter_group_name = "default.redis2.8"
  port = 6379

  subnet_group_name = "${aws_elasticache_subnet_group.logstash-redis.name}"
  security_group_ids = ["${aws_security_group.internal-redis.id}"]
  parameter_group_name = "default.redis2.8"
}

resource "aws_route53_record" "logstash-redis" {
   zone_id = "${aws_route53_zone.private-zone.id}"
   name = "redis-logstash.${var.env}.urthecast.com"
   type = "CNAME"
   ttl = "30"
   records = ["${aws_elasticache_cluster.logstash-redis.cache_nodes.0.address}"]
}
```

It fails on the route53 creation

```
* Resource 'aws_elasticache_cluster.logstash-redis' does not have attribute 'cache_nodes.0.address' for variable 'aws_elasticache_cluster.logstash-redis.cache_nodes.0.address'
```

Once the cache node is created it works fine

### PR DESCRIPTION
**Pull request by catsby**
Currently we're only checking the first Cache Cluster returned when we query the API to describe our clusters. If you have multiple clusters, you can falsely get a status of `available`. 

- We entered the `waitForState` method without first setting the cluster id, so we were effectively grabbing all clusters by searching for `""`, not just a specific one

- We then examine the first cluster returned, which if we had specified a specific one, would probably be sufficient. Instead, we could possibly get another, existing one which could be available. 

Now we set the id first, then enter the `waitForState` method. There we also filter the results for the specific Cluster. There should be only 1 returned, but I filter anyway. 

This _should_ fix #2732 . Thanks to all in that issue, as well as #2051, for the help and patience.

### CODE REVIEW

**Comment by phinze** [comment]
Nice find! Totally makes sense why repro was tough in our test accounts - we rarely have multiple cache clusters floating around.

File: builtin/providers/aws/resource_aws_elasticache_cluster.go [hunk 1]
```diff
@@ -186,16 +186,18 @@ func resourceAwsElasticacheClusterCreate(d *schema.ResourceData, meta interface{
...
 	}
 
+	d.SetId(*resp.CacheCluster.CacheClusterID)
+
 	pending := []string{"creating"}
 	stateConf := &resource.StateChangeConf{
 		Pending:    pending,
 		Target:     "available",
-		Refresh:    cacheClusterStateRefreshFunc(conn, d.Id(), "available", pending),
+		Refresh:    cacheClusterStateRefreshFunc(conn, *resp.CacheCluster.CacheClusterID, "available", pending),
```
Comment (phinze) [inline builtin/providers/aws/resource_aws_elasticache_cluster.go]: Can leave this as `d.Id()` since you moved the `SetId` up, but not a huge deal either way

**Comment by phinze** [comment]
LGTM

**Comment by mzupan** [comment]
this worked great for me.. thanks for the fix
