### PR TITLE
provider/aws: Refresh `aws_autoscaling_policy` from state on 404

### LINKED ISSUE #8386: Autoscaling policy unable to destroy if autoscaling group not present
A destroy on autoscaling policies attached to an autoscaling group fail if the autoscaling group has already been destroyed or is missing, _even if the asg is missing from the state file_. The simplest fix is to create a dummy autoscaling group and let it get destroyed but this is manual and mucks with the state file. I am still using 0.6.16 because I haven't upgraded with breaking changes in 0.7. If someone can please validate this in 0.7 that would help.

### Terraform Version
I do not believe this is a version-dependent issue.

```
$ /var/tmp/terraform -v
Terraform v0.6.16

Your version of Terraform is out of date! The latest version
is 0.7.1. You can update by downloading from www.terraform.io
```

### Affected Resource(s)
- aws_autoscaling_policy
- aws_autoscaling_group (indirectly)

### Terraform Configuration Files
```hcl
resource "aws_autoscaling_policy" "decrease" {
  name                   = "${var.name}_decrease"
  autoscaling_group_name = "${aws_autoscaling_group.application.name}"
  adjustment_type        = "${var.policy_decrease_adjustment_type}"
  scaling_adjustment     = "${var.policy_decrease_scaling_adjustment}"
  cooldown               = "${var.policy_decrease_cooldown}"
}

resource "aws_autoscaling_policy" "increase" {
  name                   = "${var.name}_increase"
  autoscaling_group_name = "${aws_autoscaling_group.application.name}"
  adjustment_type        = "${var.policy_increase_adjustment_type}"
  scaling_adjustment     = "${var.policy_increase_scaling_adjustment}"
  cooldown               = "${var.policy_increase_cooldown}"
}

resource "aws_autoscaling_group" "application" {
  # See discussion here: https://groups.google.com/forum/#!msg/terraform-tool/7Gdhv1OAc80/iNQ93riiLwAJ
  name                      = "${aws_launch_configuration.application.name}"
  health_check_grace_period = "${var.health_check_grace_period}"
  health_check_type         = "${var.asg_health_check_type}"
  launch_configuration      = "${aws_launch_configuration.application.name}"
  min_size                  = "${var.asg_min_size}"
  max_size                  = "${var.asg_max_size}"
  min_elb_capacity          = "${coalesce(var.elb_min_size,var.asg_min_size)}"
  vpc_zone_identifier       = ["${split(",", var.subnet_ids)}"]
  load_balancers            = ["${aws_elb.application.name}"]

  tag {
    key                 = "Name"
    value               = "${replace(var.name,"-",":")}"
    propagate_at_launch = true
  }

  lifecycle {
    create_before_destroy = true
  }
}
```

### Debug Output
Small enough to fit:

```
* aws_autoscaling_policy.increase: Error retrieving scaling policies: ValidationError: Group sandbox-logs-logstash-wxhsckky3ndpzd7b3kmyontngy not found
        status code: 400, request id: 56a89814-6884-11e6-b3a8-d364cf04223b
* aws_autoscaling_policy.decrease: Error retrieving scaling policies: ValidationError: Group sandbox-logs-logstash-wxhsckky3ndpzd7b3kmyontngy not found
        status code: 400, request id: 56aa6c55-6884-11e6-ba94-dde22754d685
* aws_autoscaling_policy.decrease: Error retrieving scaling policies: ValidationError: Group sandbox-logs-kibana-wf74pecy2bewjaj4vkdextp5ia not found
        status code: 400, request id: 56ad79ca-6884-11e6-bb48-cb6ee63d99db
* aws_autoscaling_policy.increase: Error retrieving scaling policies: ValidationError: Group sandbox-logs-kibana-wf74pecy2bewjaj4vkdextp5ia not found
        status code: 400, request id: 56b36d2c-6884-11e6-8e68-c3949081661b
```

### Expected Behavior
When an autoscaling group has been destroyed, this should be obvious to terraform and it should proceed appropriately: either recreate the resource or decide that it is gone so no further action is required..

### Actual Behavior
Terrfaform is unable to destroy the autoscaling policy if the autoscaling group has already been destroyed or if it is manually deleted or is missing.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. Delete the autoscaling group (Via the console or api)
3. `terraform destroy`

### Important Factoids
The autoscaling group might actually be destroyed incorrectly by terraform: that is, the policies should be destroyed before the group is destroyed. This is likely the source of the confusion. However, it should be a noop either way.

### References
- I've complained about destroy repeatedly, most recently in #6772 but this is probably unrelated (it applies to apply and plan as well).

### PR DESCRIPTION
**Pull request by stack72**
Fixes #8386

When an Autoscaling Group Or an Autoscaling Group Policy has been
deleted manually, terraform was throwing an error as follows:

```
* aws_autoscaling_policy.increase: Error retrieving scaling policies: ValidationError: Group sandbox-logs-logstash-wxhsckky3ndpzd7b3kmyontngy not found
        status code: 400, request id: 56a89814-6884-11e6-b3a8-d364cf04223b
```

We now refresh from state on a ValidationError - this is a common 4xx error according to AWS documentation http://docs.aws.amazon.com/AutoScaling/latest/APIReference/CommonErrors.html

```
%make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSAutoscalingPolicy_disappears'
==> Checking that code complies with gofmt requirements...
/Users/stacko/Code/go/bin/stringer
go generate $(go list ./... | grep -v /terraform/vendor/)
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSAutoscalingPolicy_disappears -timeout 120m
=== RUN   TestAccAWSAutoscalingPolicy_disappears
--- PASS: TestAccAWSAutoscalingPolicy_disappears (203.61s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	203.633s
```

### CODE REVIEW

File: builtin/providers/aws/resource_aws_autoscaling_policy.go [hunk 1]
```diff
@@ -271,6 +272,13 @@ func getAwsAutoscalingPolicy(d *schema.ResourceData, meta interface{}) (*autosca
 	log.Printf("[DEBUG] AutoScaling Scaling Policy Describe Params: %#v", params)
 	resp, err := autoscalingconn.DescribePolicies(&params)
 	if err != nil {
+		//A ValidationError here can mean that either the Policy is missing OR the Autoscaling Group is missing
+		if ec2err, ok := err.(awserr.Error); ok && ec2err.Code() == "ValidationError" {
+			log.Printf("[WARNING] %s not found, refreshing from state", d.Id())
```
Comment (jen20) [inline builtin/providers/aws/resource_aws_autoscaling_policy.go]: should say "removing" from state?

**Comment by jen20** [comment]
Minor gripe on the log message wording otherwise LGTM.
