### PR TITLE
Unmark config values when planning a data source read

### LINKED ISSUE #28535: Crash: panic: value is marked, so must be unmarked first
### Terraform Version

```
Terraform v0.15.1
on linux_amd64
+ provider registry.terraform.io/gitlabhq/gitlab v3.6.0
+ provider registry.terraform.io/hashicorp/archive v2.1.0
+ provider registry.terraform.io/hashicorp/aws v3.37.0
+ provider registry.terraform.io/hashicorp/github v3.0.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v2.3.1
+ provider registry.terraform.io/hashicorp/template v2.2.0

```

### Terraform Configuration Files

```terraform
module "cloudfront" {
  source = "git::https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn.git?ref=0.61.0"
}
```

### Crash Output

```txt
2021-04-28T13:17:48.468+0200 [TRACE] planDataSource: module.cloudfront.data.aws_iam_policy_document.origin_website[0] configuration not fully known yet, so deferring to apply phase
2021-04-28T13:17:48.468+0200 [INFO]  ReferenceTransformer: reference not found: "local.using_existing_cloudfront_origin"
2021-04-28T13:17:48.468+0200 [INFO]  ReferenceTransformer: reference not found: "var.cloudfront_origin_access_identity_path"
2021-04-28T13:17:48.468+0200 [INFO]  ReferenceTransformer: reference not found: "aws_cloudfront_origin_access_identity.default"
2021-04-28T13:17:48.468+0200 [INFO]  ReferenceTransformer: reference not found: "var.origin_ssl_protocols"
2021-04-28T13:17:48.468+0200 [INFO]  ReferenceTransformer: reference not found: "var.acm_certificate_arn"
2021-04-28T13:17:48.468+0200 [INFO]  ReferenceTransformer: reference not found: "var.acm_certificate_arn"
2021-04-28T13:17:48.468+0200 [INFO]  ReferenceTransformer: reference not found: "var.acm_certificate_arn"
2021-04-28T13:17:48.468+0200 [TRACE] vertex "module.cloudfront.data.aws_iam_policy_document.origin_website[0]": visit complete

panic: value is marked, so must be unmarked first

goroutine 57011 [running]:
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.2/cty/marks.go:141
github.com/zclconf/go-cty/cty.Value.LengthInt(0x2c37160, 0xc011b8faa0, 0x24e9360, 0xc000a7a978, 0x0)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.2/cty/value_ops.go:1050 +0x4f
github.com/hashicorp/terraform/plans/objchange.proposedNewNestedBlock(0xc005ba4b40, 0x2c37160, 0xc00e9e2b30, 0x23d1100, 0x3cefe80, 0x2c37160, 0xc011b8faa0, 0x24e9360, 0xc000a7a978, 0xc000a7a978, ...)
	/home/circleci/project/project/plans/objchange/objchange.go:217 +0x11cc
github.com/hashicorp/terraform/plans/objchange.proposedNew(0xc005ba4af0, 0x2c37128, 0xc00e9e2b60, 0x23d1100, 0x3cefe80, 0x2c37128, 0xc011b8fd00, 0x23fab60, 0xc005f5a1b0, 0x2c37128, ...)
	/home/circleci/project/project/plans/objchange/objchange.go:89 +0x33c
github.com/hashicorp/terraform/plans/objchange.ProposedNew(0xc005ba4af0, 0x2c37128, 0xc00e9e2b60, 0x23d1100, 0x3cefe80, 0x2c37128, 0xc011b8fd00, 0x23fab60, 0xc005f5a1b0, 0xc00e9e2b60, ...)
	/home/circleci/project/project/plans/objchange/objchange.go:42 +0x11f
github.com/hashicorp/terraform/plans/objchange.proposedNewNestedBlock(0xc005ba4af0, 0x2c370b8, 0xc00e9e2b70, 0x23d1100, 0x3cefe80, 0x2c370b8, 0xc011b8ff20, 0x22e1560, 0xc00423c138, 0xc00423c138, ...)
	/home/circleci/project/project/plans/objchange/objchange.go:121 +0x432
github.com/hashicorp/terraform/plans/objchange.proposedNew(0xc0052c2330, 0x2c37128, 0xc00e9e2b80, 0x23d1100, 0x3cefe80, 0x2c37128, 0xc011b8ff30, 0x23fab60, 0xc005150780, 0x97, ...)
	/home/circleci/project/project/plans/objchange/objchange.go:89 +0x33c
github.com/hashicorp/terraform/plans/objchange.PlannedDataResourceObject(0xc0052c2330, 0x2c37128, 0xc011b8ff30, 0x23fab60, 0xc005150780, 0x1, 0x0, 0x0, 0x0)
	/home/circleci/project/project/plans/objchange/objchange.go:64 +0x89
github.com/hashicorp/terraform/terraform.(*NodeAbstractResourceInstance).planDataSource(0xc006390380, 0x2c6cc70, 0xc00c09a340, 0xc003aa8120, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/node_resource_abstract_instance.go:1361 +0x7aa
github.com/hashicorp/terraform/terraform.(*NodePlannableResourceInstance).dataResourceExecute(0xc007e72ef0, 0x2c6cc70, 0xc00c09a340, 0x28f33d0, 0xc00007b000, 0xc009785c50)
	/home/circleci/project/project/terraform/node_resource_plan_instance.go:74 +0x478
github.com/hashicorp/terraform/terraform.(*NodePlannableResourceInstance).Execute(0xc007e72ef0, 0x2c6cc70, 0xc00c09a340, 0xc0000c4002, 0xc009785ce8, 0x40bb05, 0x2444540)
	/home/circleci/project/project/terraform/node_resource_plan_instance.go:44 +0x10d
github.com/hashicorp/terraform/terraform.(*ContextGraphWalker).Execute(0xc0044fc0c0, 0x2c6cc70, 0xc00c09a340, 0x7f01e8e1c490, 0xc007e72ef0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/graph_walk_context.go:127 +0xbf
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x2774800, 0xc007e72ef0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/graph.go:59 +0xbd3
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc0028f8b40, 0x2774800, 0xc007e72ef0, 0xc00732ad00)
	/home/circleci/project/project/dag/walk.go:381 +0x288
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/home/circleci/project/project/dag/walk.go:304 +0x1246

```

### Expected Behavior

No crash

### Actual Behavior

Crash.

### Steps to Reproduce

- Update `https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn` from `0.60.0` to `0.61.0` ([diff](https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/compare/0.60.0...0.61.0))
- Run `terraform init` and `terraform apply`
- Crash occurs.

### PR DESCRIPTION
**Pull request by jbardin**
If the configuration is storing sensitive values in a data source which cannot be read at plan time, those values must be unmarked before creating a planned read value.

This also updates the `UpgradeResourceState` codepaths to use `Diagnostics`, and add configuration context when possible. 

Fixes #28535

### CODE REVIEW

File: terraform/node_resource_abstract.go [hunk 1]
```diff
@@ -365,36 +367,42 @@ func (n *NodeAbstractResource) readResourceInstanceState(ctx EvalContext, addr a
...
 	}
-	var diags tfdiags.Diagnostics
-	src, diags = upgradeResourceState(addr, provider, src, schema, currentVersion)
+	src, upgradeDiags := upgradeResourceState(addr, provider, src, schema, currentVersion)
+	if n.Config != nil {
+		upgradeDiags = upgradeDiags.InConfigBody(n.Config.Config, addr.String())
+	}
+	diags = diags.Append(upgradeDiags)
 	if diags.HasErrors() {
+		fmt.Println("DIAGS:", diags.ErrWithWarnings())
```
Comment (mildwonkey) [inline terraform/node_resource_abstract.go:378]: 😁

Comment (jbardin) [reply terraform/node_resource_abstract.go:378]: I knew I missed one!

**Review by mildwonkey — APPROVED** [review]
LGTM!
