### PR TITLE
copyDir: detect if the module install path is a symlink to a directory

### LINKED ISSUE #20539: 0.12 - init fails with multiple uses of a module and module's repo contains symlink
### Terraform Version
```
Terraform v0.12.0-beta1
```

### Terraform Configuration Files

```hcl
module "test" {
  source = "git::ssh://git@github.com/rifelpet/terraform-module-symlink-repro//module"
}
module "test2" {
  source = "git::ssh://git@github.com/rifelpet/terraform-module-symlink-repro//module"
}
```

### Debug Output
```
2019/03/01 09:30:19 [INFO] Terraform version: 0.12.0 beta1
2019/03/01 09:30:19 [INFO] Go runtime version: go1.11.5
2019/03/01 09:30:19 [INFO] CLI args: []string{"/Users/peterr/Downloads/terraform", "init"}
2019/03/01 09:30:19 [DEBUG] Attempting to open CLI config file: /Users/peterr/.terraformrc
2019/03/01 09:30:19 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/03/01 09:30:19 [INFO] CLI command args: []string{"init"}
Initializing modules...
2019/03/01 09:30:19 [TRACE] ModuleInstaller: installing child modules for . into .terraform/modules
2019/03/01 09:30:19 [DEBUG] Module installer: begin test
2019/03/01 09:30:19 [TRACE] ModuleInstaller: test is not yet installed
2019/03/01 09:30:19 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/test prior to install of test
2019/03/01 09:30:19 [TRACE] ModuleInstaller: test address "git::ssh://git@github.com/rifelpet/terraform-module-symlink-repro//module" will be handled by go-getter
2019/03/01 09:30:19 [DEBUG] will download "git::ssh://git@github.com/rifelpet/terraform-module-symlink-repro" to .terraform/modules/test
2019/03/01 09:30:19 [TRACE] fetching "git::ssh://git@github.com/rifelpet/terraform-module-symlink-repro" to ".terraform/modules/test"
Downloading git::ssh://git@github.com/rifelpet/terraform-module-symlink-repro for test...
2019/03/01 09:30:20 [TRACE] expanded "module" to ".terraform/modules/test/module"
2019/03/01 09:30:20 [TRACE] ModuleInstaller: test "git::ssh://git@github.com/rifelpet/terraform-module-symlink-repro//module" was downloaded to .terraform/modules/test/module
2019/03/01 09:30:20 [DEBUG] Module installer: test installed at .terraform/modules/test/module
2019/03/01 09:30:20 [DEBUG] Module installer: begin test2
2019/03/01 09:30:20 [TRACE] ModuleInstaller: test2 is not yet installed
2019/03/01 09:30:20 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/test2 prior to install of test2
- test in .terraform/modules/test/module
2019/03/01 09:30:20 [TRACE] ModuleInstaller: test2 address "git::ssh://git@github.com/rifelpet/terraform-module-symlink-repro//module" will be handled by go-getter
2019/03/01 09:30:20 [DEBUG] will download "git::ssh://git@github.com/rifelpet/terraform-module-symlink-repro" to .terraform/modules/test2
2019/03/01 09:30:20 [TRACE] copying previous install .terraform/modules/test to .terraform/modules/test2
Downloading git::ssh://git@github.com/rifelpet/terraform-module-symlink-repro for test2...
2019/03/01 09:30:20 [TRACE] modsdir: writing modules manifest to .terraform/modules/modules.json

Error: Failed to download module

Error attempting to download module "test2" (main.tf:4) source code from
"git::ssh://git@github.com/rifelpet/terraform-module-symlink-repro":
failed to copy from .terraform/modules/test to .terraform/modules/test2: read
.terraform/modules/test/symlink: is a directory


Error: Failed to download module

Error attempting to download module "test2" (main.tf:4) source code from
"git::ssh://git@github.com/rifelpet/terraform-module-symlink-repro":
failed to copy from .terraform/modules/test to .terraform/modules/test2: read
.terraform/modules/test/symlink: is a directory
```

### Expected Behavior
`terraform init` completes successfully

### Actual Behavior
`terraform init` fails with a copy error

### Steps to Reproduce

[This repo](https://github.com/rifelpet/terraform-module-relative-path-repro) contains a terraform module as well as an unrelated symlink.

When invoking the `module` module in that repo multiple times, terraform 0.12 will download the repo once and then copy it locally as many times as needed, to avoid redundant downloading. If the git repo contains a symlink (even if its not in the module's subdirectory), the copy will fail. Removing the symlink from the repo causes `init` to succeed. I'm not aware of how well terraform supports following symlinks, but in this case its not even used by terraform, it just happens to also be in the repo. It would be great if terraform's module downloading could successfully copy git repos containing symlinks.

### Additional Context
The error is logged [here](https://github.com/hashicorp/terraform/blob/86e6481cc661b2ba694d353aab6d11838c066c7c/configs/configload/getter.go#L108) and I'm guessing that the `copyDir` function isnt looking for symlinks within the directory it is copying, causing [this](https://github.com/hashicorp/terraform/blob/86e6481cc661b2ba694d353aab6d11838c066c7c/configs/configload/copy_dir.go#L63) open to fail.

### References
N/A

### PR DESCRIPTION
**Pull request by mildwonkey**
Take two! With tests!

configs/configload and internal/initwd both had a copyDir function that
would fail if the source directory contained a symlinked directory,
because the os.FileMode.IsDir() returns false for symlinks.

This PR adds a check for a symlink and recreates the symlink in the
target directory. It handles symlinks for both files and directories
(with included tests).

Fixes #20539

### CODE REVIEW

File: configs/configload/copy_dir.go [hunk 1]
```diff
@@ -59,6 +59,20 @@ func copyDir(dst, src string) error {
...
+		// If the current path is a symlink, recreate the symlink relative to
+		// the dst directory
+		if info.Mode()&os.ModeSymlink == os.ModeSymlink {
+			// the original symlink target
+			target, err := filepath.EvalSymlinks(path)
+			if err != nil {
+				return err
+			}
+
+			newTarget, err := filepath.Rel(src, target)
```
Comment (apparentlymart) [inline configs/configload/copy_dir.go]: It occurred to me reading this that the symlink target path in the _source_ directory here is presumably already pointing at a reasonable location relative to the source directory, and we're creating an exact copy of that directory so the exact same target should in principle work in the target too, without the need to use `EvalSymlinks` or `Rel` here to rewrite it.

Could we do the following simpler sequence here instead?

```go
target, err := os.Readlink(path)
if err != nil {
    return err
}

return os.Symlink(target, dstPath)
```

:thinking: Possibly I'm missing a situation where that doesn't work out...

Comment (jbardin) [reply configs/configload/copy_dir.go]: I think most tools opt to copy the symlink exactly, and leave it broken if it was pointing to something outside the tree being copied. 

I agree that just finding the target and making a new symlink is sufficient here.

Comment (mildwonkey) [reply configs/configload/copy_dir.go]: Yes, absolutely! That's what I did originally, but I was concerned that it would be insufficient - I might have been inventing potential issues. Thanks!
