### PR TITLE
Use the apparentlymart/go-versions library to parse module constraints

### LINKED ISSUE #32356: when requesting an exact prerelease version, the = operator cannot be used
### Terraform Version

```shell
Terraform v1.3.6
on linux_amd64
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }
  }
}

provider "aws" {
  region = "us-west-2"
}

provider "aws" {
  alias  = "global_region"
  region = "us-east-1"
}


module "tf_next" {
  source  = "milliHQ/next-js/aws"
  version = "=1.0.0-canary.2"

  providers = {
    aws.global_region = aws.global_region
  }
}
```

### Debug Output

https://gist.github.com/bowtie-ltsa/cb1ef0658cea1433e90531ab0472c066

### Expected Behavior

the requested version should have been downloaded, according to my understanding of the docs

https://developer.hashicorp.com/terraform/language/expressions/version-constraints#version-constraint-behavior

image

### Actual Behavior

# actual behavior
Error: Unresolvable module version constraint

# workaround: 
to work-around this problem, you can remove the exact version operator (=) from the version attribute string --

## this fails:
```terraform
module "tf_next" {
  source  = "milliHQ/next-js/aws"
  version = "=1.0.0-canary.2"
  ...
}
```

## this works:
```terraform
module "tf_next" {
  source  = "milliHQ/next-js/aws"
  version = "1.0.0-canary.2"
  ...
}
```

# proposed fix
change this line?
https://github.com/hashicorp/terraform/blob/main/internal/initwd/module_install.go#L390
Because it is looking for an exact string match, ignoring the "=" operator that may be the first character of the version constraint. Right?

### Steps to Reproduce

👉 just run `terraform init` with the above terraform, but to be more precise:

```bash
curl -o tf.zip https://releases.hashicorp.com/terraform/1.3.6/terraform_1.3.6_linux_amd64.zip
unzip tf.zip
chmod +x terraform

mkdir ex1
cd ex1

cat <<EOF > main.tf
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }
  }
}

provider "aws" {
  region = "us-west-2"
}

provider "aws" {
  alias  = "global_region"
  region = "us-east-1"
}


module "tf_next" {
  source  = "milliHQ/next-js/aws"
  version = "=1.0.0-canary.2"

  providers = {
    aws.global_region = aws.global_region
  }
}
EOF

../terraform init
```

### Additional Context

none. I reproduced this in an isolated simple container.

### References

_No response_

### PR DESCRIPTION
**Pull request by liamcervante**
Update the module constraint checking logic to use the apparentlymart/go-versions library instead of the hashicorp/go-versions library. This copies the logic of the provider installer which relies entirely on the apparentlymart implementation.

A further PR could look into completely stripping out the old version with the new version for all version processing (not just constraint checking). This is a lot of work though, so this PR could be viewed as a first step in that direction, or maybe we should decide that we should fix this only with a bigger migration and I can close this PR?

Fixes #32356 

## Target Release

1.3.6

### BUG FIXES

 

-  Fix exact version constraint parsing for modules using prerelease versions.

### CODE REVIEW

File: internal/initwd/module_install.go [hunk 1]
```diff
@@ -387,9 +389,29 @@ func (i *ModuleInstaller) installRegistryModule(ctx context.Context, req *earlyc
...
+					tfdiags.Warning,
+					"Invalid version constraint string",
+					fmt.Sprintf("The requested version constraint (%s) could not be be parsed: %s", req.VersionConstraints.String(), err.Error()),
+				))
+				continue
+			}
+
+			// We validated the version string previously, so we are quite sure
+			// that MustParseVersion will not crash/panic.
+			if !acceptableVersions.Has(versions.MustParseVersion(v.String())) {
```
Comment (apparentlymart) [inline internal/initwd/module_install.go:411]: I'm not sure if it's 100% safe to assume that successful parsing with `hashicorp/go-version` guarantees successful parsing with `apparentlymart/versions`. For example: I believe `go-version` allows a string like `1.0.0.0.0.0.0.0` (any number of numeric segments) if using its main version parser, although not if using its `NewSemver` function.

If we _have_ been allowing non-semver-syntax version numbers then I suppose this could represent a compatibility regression, so I hope we haven't but I cannot guarantee it off the top of my head. Would probably be worth some testing with some of the examples from [the `New` tests](https://github.com/hashicorp/go-version/blob/78d058c5618891f74d604bd15356fca690b64d8a/version_test.go#L10-L49) and [the `NewSemver` tests](https://github.com/hashicorp/go-version/blob/78d058c5618891f74d604bd15356fca690b64d8a/version_test.go#L51-L90) to get a sense of what is and isn't currently accepted by our module installer, and whether all of those inputs are valid per `apparentlymart/go-versions`.

(If `go-versions` is rejecting any that seems like valid semver syntax then I would consider that to be a bug, but `go-version` was originally more general than semver and _that_ would be out of scope for `apparentlymart/go-versions`, which is focused on the semver sense of version numbers in particular.)

File: internal/initwd/module_install.go [hunk 2]
```diff
@@ -387,9 +389,29 @@ func (i *ModuleInstaller) installRegistryModule(ctx context.Context, req *earlyc
...
+				log.Printf("[TRACE] ModuleInstaller: %s ignoring %s because it is a pre-release and was not requested exactly", key, v)
+				continue
```
Comment (apparentlymart) [inline internal/initwd/module_install.go:413]: It's interesting to note that this effectively means that _any_ prerelease versions announced by the registry will be subject to `apparentlymart/go-versions` matching before we get to the `req.VersionConstraints.Check(v)` call below.

I don't think this is actually a problem -- this is still more general than the direct string comparison it is replacing -- but might be worth a comment noting this in the hope of minimizing confusion for a future maintainer here?

File: internal/initwd/module_install.go [hunk 3]
```diff
@@ -387,9 +389,29 @@ func (i *ModuleInstaller) installRegistryModule(ctx context.Context, req *earlyc
...
-			continue
+		if v.Prerelease() != "" {
+			// Switch over to another library to check these version
+			// constraints. This means our version constraint logic matches
+			// between providers and modules. But it does leave this function
+			// having to switch between the two libraries.
+			acceptableVersions, err := versions.MeetingConstraintsString(req.VersionConstraints.String())
+			if err != nil {
+				// This shouldn't really happen, as we validated the constraints
+				// string earlier. Let's return a nice error message anyway.
```
Comment (apparentlymart) [inline internal/initwd/module_install.go:400]: While I agree that this _should_ be okay, it is possible in principle that `versions.MeetingConstraintsString` is stricter in some cases than the `hashicorp/go-versions` parser.

Given that for now we're just trying to use `apparentlymart/go-versions` only as an extra filter for prereleases and not fully embrace it, I wonder if we should instead make this a `log.Printf` with `[WARN]` so that a regular user will never see any messaging in this case.

I think it should be safe to assume that any version constraint that represents just an exact version selection should always pass `versions.MeetingConstraintsString`, and so it seems pragmatic to assume that if we get any errors here then it's _not_ just an exact match and therefore shouldn't select a prerelease.

(Note that `v` is under the control of the module registry rather than the user, so a user with a version constraint that is somehow valid for `hashicorp/go-version` but not for `apparentlymart/go-versions` would see this warning just because the module registry announced at least one prerelease version, regardless of whether they actually intended to use that prerelease version.)

**Review by apparentlymart — COMMENTED** [review]
I left some notes about details inline, but overall this seems reasonable to me.

Did you find that there wasn't a good place to add tests for this? I must admit I don't recall what the module installer's testing approach is since it's some quite old code at this point, but I hope there's at least something _somewhere_ testing that it's possible to install a prerelease version using an exact match without any operator and so would've hoped we could add a similar test alongside that which uses the `=` operator to get the same effect.

File: internal/initwd/module_install.go (hunk 2 above)
Comment (liamcervante) [reply internal/initwd/module_install.go:424]: I've added additional comments, expanding on the context. Hopefully it's more clear now 😅

File: internal/initwd/module_install.go (hunk 1 above)
Comment (liamcervante) [reply internal/initwd/module_install.go]: I've added a global comment discussing testing more generally. In this case specifically, it checks if the version is parseable now and writes a log message if not.

File: internal/initwd/module_install.go (hunk 3 above)
Comment (liamcervante) [reply internal/initwd/module_install.go]: Done! Changed the tfdiags for a warning log message.

**Review by liamcervante — COMMENTED** [review]
So all the tests in this package are essentially acceptance tests, in that they download real modules from the registry. 

I was wondering if maybe I could add prerelease tag to [terraform-aws-module-installer-acc-test](https://github.com/hashicorp/terraform-aws-module-installer-acctest). Then I could add some acceptance tests around that and make use of the existing testing infrastructure.

I don't think I can add simple unit tests for this easily though. It's all embedded inside the function that is pulling from the actual registry. I'd have to go through and add mocks for the registry etc. Does this functionality exist elsewhere?

Thoughts?
