### PR TITLE
provider/aws: implement CloudFront Lambda Function Associations (supersedes #10985)

### LINKED ISSUE #11295: Applying a change to trusted_signers in default_cache_behavior in aws_cloudfront_distribution plans OK but produces error on apply
### Terraform Version
Terraform 0.8.4

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_cloudfront_distribution

### Terraform Configuration Files
Here's what they look like in the state which causes the error:

```hcl
resource "aws_cloudfront_origin_access_identity" "ORIGIN_BUKKIT-identity" {
  comment = "ORIGIN BUKKIT identity"
}

resource "aws_cloudfront_distribution"  "ORIGIN_BUKKIT_DISTRIBUTION" {
  enabled = true
  is_ipv6_enabled = true
  http_version = "http2"
  price_class = "PriceClass_All"
  comment = "MAH BUKKIT"

  origin {
    domain_name = "${aws_s3_bucket.ORIGIN_BUKKIT.bucket}.s3.amazonaws.com"
    origin_id = "S3-${aws_s3_bucket.ORIGIN_BUKKIT.bucket}"
    origin_path = "/assets"
    s3_origin_config {
      origin_access_identity = "${aws_cloudfront_origin_access_identity.ORIGIN_BUKKIT-identity.cloudfront_access_identity_path}"
    }
  }

  default_cache_behavior {
    allowed_methods = ["DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT"]
    cached_methods = ["GET", "HEAD" ]
    target_origin_id = "S3-${aws_s3_bucket.ORIGIN_BUKKIT.bucket}"
    trusted_signers = ["<account number>"]
    viewer_protocol_policy = "redirect-to-https"
    compress = false
    min_ttl = 0
    default_ttl = 3600
    max_ttl = 86400
    forwarded_values {
      query_string = true
      cookies {
        forward = "none"
      }
    }
  }

  viewer_certificate {
    cloudfront_default_certificate = true
  }

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  tags {
    Environment = "production"
  }

  logging_config {
    include_cookies = false
    bucket = "${aws_s3_bucket.LOG_BUKKIT.bucket}.s3.amazonaws.com"
    prefix = "cloudfront/ORIGIN_BUKKIT"
  }
}
```

**Note**: prior to this, when we created the distribution, I had the following resource also there:
```hcl
data "aws_caller_identity" "current_aws_account" {}
```

...and the trusted_signers field looked like:
```hcl
trusted_signers = ["${data.aws_caller_identity.current_aws_account.account_id}"]
```
...that worked to create the distribution, **BUT** whenever we ran a refresh, we'd get a diff in the state that looked like:

```
diff --git a/terraform/terraform.tfstate b/terraform/terraform.tfstate
index 98c6108..a160cee 100644
--- a/terraform/terraform.tfstate
+++ b/terraform/terraform.tfstate
@@ -1,7 +1,7 @@
 {
     "version": 3,
     "terraform_version": "0.8.4",
-    "serial": 389,
+    "serial": 390,
     "lineage": "c3158160-c23e-4283-88bf-f65e4107caca",
     "modules": [
         {
@@ -25114,10 +25114,10 @@
                     "type": "aws_caller_identity",
                     "depends_on": [],
                     "primary": {
-                        "id": "2017-01-19 19:46:22.518710886 +0000 UTC",
+                        "id": "2017-01-19 19:53:03.227587972 +0000 UTC",
                         "attributes": {
                             "account_id": "<account number>",
-                            "id": "2017-01-19 19:46:22.518710886 +0000 UTC"
+                            "id": "2017-01-19 19:53:03.227587972 +0000 UTC"
                         },
                         "meta": {},
                         "tainted": false
```

...so this change was being made to see if we could stop that happening.  I reasoned that using a hardcoded account ID and getting rid of that aws_caller_identity resource should stop it updating its timestamp in every run.

### Debug Output
We had to back out to get back to clean state, I can't run it with debug on :-( :-(

### Panic Output
No panic.

### Expected Behavior
This distribution was created with the AWS account in trusted_signers being provided by a data aws_caller_identity resource.  However, that caused its own problems, because that resource's timestamp changed in every run, causing diffs in our state for every run.  So I removed that data resource and hardcoded the AWS Account ID as a string containing the numerical account ID in the trusted_signers list.

Running `terraform plan` produced an expected change output, with it destroying the `default_cache_behavior` subresource and building a new one with the correct account number.

I expected executing that plan would update the distribution as it stated would happen.

Here is the plan output:
```
Path: ./plan

~ aws_cloudfront_distribution.percolate-asset-usw1
    default_cache_behavior.371026481.allowed_methods.#:                                                  "0" => "7"
    default_cache_behavior.371026481.allowed_methods.0:                                                  "" => "DELETE"
    default_cache_behavior.371026481.allowed_methods.1:                                                  "" => "GET"
    default_cache_behavior.371026481.allowed_methods.2:                                                  "" => "HEAD"
    default_cache_behavior.371026481.allowed_methods.3:                                                  "" => "OPTIONS"
    default_cache_behavior.371026481.allowed_methods.4:                                                  "" => "PATCH"
    default_cache_behavior.371026481.allowed_methods.5:                                                  "" => "POST"
    default_cache_behavior.371026481.allowed_methods.6:                                                  "" => "PUT"
    default_cache_behavior.371026481.cached_methods.#:                                                   "0" => "2"
    default_cache_behavior.371026481.cached_methods.0:                                                   "" => "GET"
    default_cache_behavior.371026481.cached_methods.1:                                                   "" => "HEAD"
    default_cache_behavior.371026481.compress:                                                           "" => "false"
    default_cache_behavior.371026481.default_ttl:                                                        "" => "3600"
    default_cache_behavior.371026481.forwarded_values.#:                                                 "0" => "1"
    default_cache_behavior.371026481.forwarded_values.2555876073.cookies.#:                              "0" => "1"
    default_cache_behavior.371026481.forwarded_values.2555876073.cookies.2625240281.forward:             "" => "none"
    default_cache_behavior.371026481.forwarded_values.2555876073.cookies.2625240281.whitelisted_names.#: "0" => "0"
    default_cache_behavior.371026481.forwarded_values.2555876073.headers.#:                              "0" => "0"
    default_cache_behavior.371026481.forwarded_values.2555876073.query_string:                           "" => "true"
    default_cache_behavior.371026481.forwarded_values.2555876073.query_string_cache_keys.#:              "0" => "0"
    default_cache_behavior.371026481.max_ttl:                                                            "" => "86400"
    default_cache_behavior.371026481.min_ttl:                                                            "" => "0"
    default_cache_behavior.371026481.smooth_streaming:                                                   "" => ""
    default_cache_behavior.371026481.target_origin_id:                                                   "" => "S3-ORIGIN_BUKKIT"
    default_cache_behavior.371026481.trusted_signers.#:                                                  "0" => "1"
    default_cache_behavior.371026481.trusted_signers.0:                                                  "" => "<account number>"
    default_cache_behavior.371026481.viewer_protocol_policy:                                             "" => "redirect-to-https"
    default_cache_behavior.503536106.allowed_methods.#:                                                  "7" => "0"
    default_cache_behavior.503536106.allowed_methods.0:                                                  "HEAD" => ""
    default_cache_behavior.503536106.allowed_methods.1:                                                  "DELETE" => ""
    default_cache_behavior.503536106.allowed_methods.2:                                                  "POST" => ""
    default_cache_behavior.503536106.allowed_methods.3:                                                  "GET" => ""
    default_cache_behavior.503536106.allowed_methods.4:                                                  "OPTIONS" => ""
    default_cache_behavior.503536106.allowed_methods.5:                                                  "PUT" => ""
    default_cache_behavior.503536106.allowed_methods.6:                                                  "PATCH" => ""
    default_cache_behavior.503536106.cached_methods.#:                                                   "2" => "0"
    default_cache_behavior.503536106.cached_methods.0:                                                   "HEAD" => ""
    default_cache_behavior.503536106.cached_methods.1:                                                   "GET" => ""
    default_cache_behavior.503536106.compress:                                                           "false" => "false"
    default_cache_behavior.503536106.default_ttl:                                                        "3600" => "0"
    default_cache_behavior.503536106.forwarded_values.#:                                                 "1" => "0"
    default_cache_behavior.503536106.forwarded_values.2555876073.cookies.#:                              "1" => "0"
    default_cache_behavior.503536106.forwarded_values.2555876073.cookies.2625240281.forward:             "none" => ""
    default_cache_behavior.503536106.forwarded_values.2555876073.cookies.2625240281.whitelisted_names.#: "0" => "0"
    default_cache_behavior.503536106.forwarded_values.2555876073.headers.#:                              "0" => "0"
    default_cache_behavior.503536106.forwarded_values.2555876073.query_string:                           "true" => "false"
    default_cache_behavior.503536106.forwarded_values.2555876073.query_string_cache_keys.#:              "0" => "0"
    default_cache_behavior.503536106.max_ttl:                                                            "86400" => "0"
    default_cache_behavior.503536106.min_ttl:                                                            "0" => "0"
    default_cache_behavior.503536106.smooth_streaming:                                                   "false" => "false"
    default_cache_behavior.503536106.target_origin_id:                                                   "S3-ORIGIN_BUKKIT" => ""
    default_cache_behavior.503536106.trusted_signers.#:                                                  "1" => "0"
    default_cache_behavior.503536106.trusted_signers.0:                                                  "self" => ""
    default_cache_behavior.503536106.viewer_protocol_policy:                                             "redirect-to-https" => ""

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Actual Behavior
Got an error which makes no sense:

```
Error applying plan:

1 error(s) occurred:

* aws_cloudfront_distribution.ORIGIN_BUKKIT_DISTRIBUTION: InvalidArgument: The parameter Lambda function associations is required.
	status code: 400, request id: f0bc07f8-de85-11e6-b1f8-138f26fea4d2

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

**ADDITIONAL INFO/HYPOTHESIS:** is this blowing up because I'm not using 'self' as the trusted_signer account, but using my own account number?  i.e. is that verboten on AWS, to specify your own account via number in the cloudfront distro?  I note that 'self' is the value in the original distribution.

### Steps to Reproduce

1. Create a cloudfront distribution using an aws_caller_identity data resource as the single element in the trusted_signer array parameter in the default_cache_behavior
2. Modify the source tf files to remove that aws_caller_identity data resource and replace the reference to it in the default_cache_behavior trusted_signers field with a 1-member array holding a straight string containing a numeric AWS account number (the correct one for your account)
3. Run `terraform plan -out=./plan`, note that output seems sane with no errors
4. Run `terraform apply ./plan` - boom

### Important Factoids
We are running in EC2 classic.  We have a VPC as well.   This is our first TF-managed cloudfront distribution.

### References
None

### PR DESCRIPTION
**Pull request by catsby**
Continue the work done in #10985 with just a few tweaks to restore the `TypeSet` in `lambda_function_association`.

Should also fix #11295

### CODE REVIEW

**Comment by stack72** [comment]
Solid work - this LGTM! Nice to see this coming in - it should unblock some people :)

**Comment by MrGossett** [comment]
Thanks!

File: builtin/providers/aws/cloudfront_distribution_configuration_structure_test.go [hunk 1]
```diff
@@ -44,6 +49,35 @@ func trustedSignersConf() []interface{} {
 	return []interface{}{"1234567890EX", "1234567891EX"}
 }
 
+func lambdaSetHash(v interface{}) int {
```
Comment (MrGossett) [inline builtin/providers/aws/cloudfront_distribution_configuration_structure_test.go]: This is essentially where my PR was at [9c5a25d](https://github.com/hashicorp/terraform/pull/11291/files/9c5a25dd480e71a3b0838c4c2f3f1cae47f41757) on Jan 5. I was derailed by the [comment from @apparentlymart](https://github.com/hashicorp/terraform/pull/10985#discussion_r94830032) asking to remove the hash function.

Sorry this got delayed 2 weeks as a result 🤓

Comment (catsby) [inline builtin/providers/aws/cloudfront_distribution_configuration_structure_test.go]: Nah it's not your fault. 

@apparentlymart was correct in that the manually added `Set` function should be omitted, unless there's a really good reason. 

The problem here was reconstructing "sets" in _code_ in the test instead of configuration. All the previous examples I found in the codebase were simple set's of `strings` which is trivial to reconstruct, but `NewSet` is more difficult with sets that have a more complicated schema. 

Like I said you did 99% of the work here I just needed to do some battlefield surgery 😄

Comment (MrGossett) [inline builtin/providers/aws/cloudfront_distribution_configuration_structure_test.go]: Roger. Thanks again 😄

**Comment by catsby** [comment]
Ran some test:

```
=== RUN   TestAccAWSCloudFrontDistribution_importBasic
--- PASS: TestAccAWSCloudFrontDistribution_importBasic (1587.37s)
=== RUN   TestAccAWSCloudFrontDistribution_S3Origin
--- PASS: TestAccAWSCloudFrontDistribution_S3Origin (1626.38s)
=== RUN   TestAccAWSCloudFrontDistribution_S3OriginWithTags
--- PASS: TestAccAWSCloudFrontDistribution_S3OriginWithTags (1734.81s)
```

**Comment by catsby** [comment]
Hold off on this - need to investigate something

File: builtin/providers/aws/cloudfront_distribution_configuration_structure_test.go (hunk 1 above)
Comment (catsby) [inline builtin/providers/aws/cloudfront_distribution_configuration_structure_test.go]: @MrGossett So.... funny enough, I had to reinstate that lambda set hash you were asked to remove 😆  

From Martin's comment:

> We only really continue to support explicit Set for compatibility with schemas that predate the automatic hashing.

This is _true_, but unfortunately `lambda_function_association` is being added as a sub param to two params that do themselves have custom hash function for the IDs. 

So, I had to add `lambda_function_association` to the two `CacheBehaviorHash` (?) method(s), but to do so, I'd need to hash them... so I needed that method 😐 

So anyway it's re-added

**Comment by catsby** [comment]
I added documentation and the `lambda_function_association` objects to the `cacheBehaviorHash` methods to track them, and added docs in https://github.com/hashicorp/terraform/pull/11291/commits/6d4f4007feb1d177f48d5483da4eba537ec44056

File: builtin/providers/aws/cloudfront_distribution_configuration_structure_test.go (hunk 1 above)
Comment (MrGossett) [inline builtin/providers/aws/cloudfront_distribution_configuration_structure_test.go]: :+1:

**Comment by catsby** [comment]
Hey @stack72 when you get a chance can you look this over? Not sure about the TravisCI error 🤔

**Comment by kalbasit** [comment]
```

File: website/source/docs/providers/aws/r/cloudfront_distribution.html.markdown [hunk 2]
```diff
@@ -173,10 +171,13 @@ of several sub-resources - these resources are laid out below.
     object is in a CloudFront cache before CloudFront forwards another request
     in the absence of an `Cache-Control max-age` or `Expires` header.
 
-  * `forwarded_values` (Required) - The [forwarded values
-    configuration](#forwarded-values-arguments) that specifies how CloudFront
+  * `forwarded_values` (Required) - The [forwarded values configuration](#forwarded-values-arguments) that specifies how CloudFront
     handles query strings, cookies and headers (maximum one).
 
+  * `lambda_function_association` (Optional) - A complext config that triggers a lambda function with
```
Comment (tomelliff) [inline website/source/docs/providers/aws/r/cloudfront_distribution.html.markdown]: Typo on `complext`

File: website/source/docs/providers/aws/r/cloudfront_distribution.html.markdown [hunk 3]
```diff
@@ -222,6 +223,19 @@ of several sub-resources - these resources are laid out below.
...
     value of `true` for `query_string`, all query string keys are cached.
+    
+##### Lambda Function Association
+
+Lambda@Edge allows you to associate an AWS Lambda Function with a predefined
+event. You can associate a single function per event type. See [What is
+Lambda@Edge](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/what-is-lambda-at-edge.html) 
+for more information
+
+  * `event_type` (Required) - The specific event to trigger this functionon.
```
Comment (tomelliff) [inline website/source/docs/providers/aws/r/cloudfront_distribution.html.markdown]: Typo on `functionon`

**Comment by stack72** [comment]
@catsby the travis fail is because of this

```
--- FAIL: TestCloudFrontStructure_flattenDefaultCacheBehavior (0.00s)
panic: interface conversion: interface {} is []interface {}, not *schema.Set [recovered]
	panic: interface conversion: interface {} is []interface {}, not *schema.Set
```

**Comment by stack72** [comment]
LGTM! 
image

File: website/source/docs/providers/aws/r/cloudfront_distribution.html.markdown [hunk 4]
```diff
@@ -222,6 +223,19 @@ of several sub-resources - these resources are laid out below.
...
+    
+##### Lambda Function Association
+
+Lambda@Edge allows you to associate an AWS Lambda Function with a predefined
+event. You can associate a single function per event type. See [What is
+Lambda@Edge](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/what-is-lambda-at-edge.html) 
+for more information
+
+  * `event_type` (Required) - The specific event to trigger this function.
+  Valid values: `viewwer-request`, `origin-request`, `viewer-response`,
```
Comment (MrGossett) [inline website/source/docs/providers/aws/r/cloudfront_distribution.html.markdown]: typo: `viewwer-request`

File: builtin/providers/aws/cloudfront_distribution_configuration_structure.go [hunk 5]
```diff
@@ -294,6 +311,9 @@ func flattenCacheBehavior(cb *cloudfront.CacheBehavior) map[string]interface{} {
 	if len(cb.TrustedSigners.Items) > 0 {
 		m["trusted_signers"] = flattenTrustedSigners(cb.TrustedSigners)
 	}
+	if len(cb.LambdaFunctionAssociations.Items) > 0 {
+		m["lambda_function_association"] = flattenLambdaFunctionAssociations(cb.LambdaFunctionAssociations)
```
Comment (MrGossett) [inline builtin/providers/aws/cloudfront_distribution_configuration_structure.go]: is this supposed to be plural? `lambda_function_associations`

Comment (catsby) [inline builtin/providers/aws/cloudfront_distribution_configuration_structure.go]: no, it's a key in the schema. If it were plural then the config to use it would be 

```
lambda_funcation_associations {
  event_type = "blah"
  arn = "blah"
}
lambda_funcation_associations {
  event_type = "blah"
  arn = "blah"
}
...
```

Comment (MrGossett) [inline builtin/providers/aws/cloudfront_distribution_configuration_structure.go]: Makes sense.

File: builtin/providers/aws/cloudfront_distribution_configuration_structure_test.go [hunk 6]
```diff
@@ -337,6 +363,9 @@ func TestCloudFrontStructure_flattenCacheBehavior(t *testing.T) {
 	if out["target_origin_id"] != "myS3Origin" {
 		t.Fatalf("Expected out[target_origin_id] to be myS3Origin, got %v", out["target_origin_id"])
 	}
+	if reflect.DeepEqual(out["lambda_function_associations"], in["lambda_function_associations"]) != true {
```
Comment (MrGossett) [inline builtin/providers/aws/cloudfront_distribution_configuration_structure_test.go]: I have a feeling this is passing because `reflect.DeepEqual` is comparing `nil` to `nil`. The singular version is used in [defaultCacheBehaviorConf](https://github.com/hashicorp/terraform/pull/11291/files#diff-58242079a8a0215c803ef662dacf67e4R19), so the plural `lambda_function_associations` doesn't exist.

Comment (catsby) [inline builtin/providers/aws/cloudfront_distribution_configuration_structure_test.go]: makes sense, I'll investigate

Comment (catsby) [inline builtin/providers/aws/cloudfront_distribution_configuration_structure_test.go]: fixed in fd3f4bbf3de1398cd6f834166053c2676baf5e59

File: website/source/docs/providers/aws/r/cloudfront_distribution.html.markdown (hunk 4 above)
Comment (catsby) [inline website/source/docs/providers/aws/r/cloudfront_distribution.html.markdown]: fixed, thanks!
