### PR TITLE
Check required_version as early as possible

### LINKED ISSUE #29109: configuration_aliases throws misleading error in 0.14.x even though  required_version = ">= 0.15"
### Terraform Version

```
Terraform v0.14.11
```

### Terraform Configuration Files

```terraform
terraform {
  required_version = ">= 0.15"
  required_providers {
    aws = {
      source                = "hashicorp/aws"
      version               = ">= 3.40"
      configuration_aliases = [aws.this]
    }
  }
}
```

### Expected Behavior

Throw the error for unsupported terraform core version first thing on a `terraform init`. This should be the first thing checked because if there is a required version, chances are that a non-supported version is going to have features that will look like errors.

### Actual Behavior

```
$ terraform init

There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Invalid required_providers object

  on versions.tf line 4, in terraform:
   4:     aws = {
   5:       source                = "hashicorp/aws"
   6:       version               = ">= 3.40"
   7:       configuration_aliases = [aws.this]
   8:     }

required_providers objects can only contain "version" and "source" attributes.
To configure a provider, use a "provider" block.


Error: Variables not allowed

  on versions.tf line 7, in terraform:
   7:       configuration_aliases = [aws.this]

Variables may not be used here.
```

### Steps to Reproduce

1. terraform init

### PR DESCRIPTION
**Pull request by jbardin**
Our current check of `required_version` happens after parsing the configuration, which may not be possible if new configuration constructs have been added to the language since the declared `required_version`. This can cause terraform to print rather unhelpful error messages about unknown identifiers in various modules, when the only pertinent information is that the CLI version is not compatible.

Restructure the init command to ensure that we check the core version constraints before handling any parsing diagnostics. We can remove the extra loading of the configuration, which is redundant when the config loader can return the same value along with its diagnostics.

Closes #29109

### CODE REVIEW

File: internal/command/init.go [hunk 1]
```diff
@@ -192,28 +185,30 @@ func (c *InitCommand) Run(args []string) int {
...
+	// incorrect version of terraform may be producing errors for configuration
+	// constructs added in later versions.
 
-	// Before we go further, we'll check to make sure none of the modules in the
-	// configuration declare that they don't support this Terraform version, so
-	// we can produce a version-related error message rather than
-	// potentially-confusing downstream errors.
+	// Before we go further, we'll check to make sure none of the modules in
+	// the configuration declare that they don't support this Terraform
+	// version, so we can produce a version-related error message rather than
```
Comment (apparentlymart) [inline internal/command/init.go:194]: Unless I'm reading this diff wrong, it looks like we lost the last line of this comment here, causing it to now trail off mid-sentence.

**Review by apparentlymart — APPROVED** [review]

**Review by jinhaoqicode — COMMENTED** [review]
test
