### PR TITLE
terraform: improve provider config related error messages

### LINKED ISSUE #20121: Missing context for provider diagnostics
### Terraform Version

ae0be75ae09efb191ecd22f27389b16521c771fb (`Thu Jan 24 17:41:30 2019 -0800`)

### Terraform Configuration Files

```hcl
# no provider block

resource "tfe_workspace" "test" {
  name         = "my-workspace-name"
  organization = "radeksimko"
}
```

### Expected Behavior

A diagnostic which gives some hint about where the error is coming from.

### Actual Behavior

```
Error: required token could not be found

  on <empty> line 0:
  (source code not available)

```

### Steps to Reproduce

```
terraform apply
```

### Additional Context

I have compiled TFE provider from [this branch](https://github.com/terraform-providers/terraform-provider-tfe/compare/radeksimko/v0.12-upgrade) (basically just bumped Terraform to `ae0be75ae09efb191ecd22f27389b16521c771fb`).

I am aware that we want to avoid adding too much context to error messages as we expect these to be presented with the snippet of code. This however isn't always possible, as demonstrated in this issue, where provider block is not in the config at all and settings can be provided via ENV variables.

### PR DESCRIPTION
**Pull request by mildwonkey**
If there is no "provider" block present in the configuration at all,
errors related to missing required arguments lack source information or
even a reference to the provider in question. This PR adds more specific
error messages in three of these situations:
- ValidateProvider
- ConfigureProvider: provider.PrepareProviderConfig
- ConfigureProvider: ctx.ConfigureProvider

To test the last case I added a ConfigureProviderFn to the MockContext.

Screen Shot 2020-12-11 at 9 08 44 AM

Closes #20121, #26707, #23087

### CODE REVIEW

File: terraform/node_provider.go [hunk 1]
```diff
@@ -139,7 +163,29 @@ func (n *NodeApplyableProvider) ConfigureProvider(ctx EvalContext, provider prov
...
 
 	return diags
 }
+
+const providerConfigErr = `%s
+
+Provider %q requires explicit configuration. Add a provider block to the root
+module and configure the provider's required arguments as described in the
+provider documentation.
+`
```
Comment (alisdair) [inline terraform/node_provider.go:191]: Writing this paragraph with embedded newlines has the unfortunate effect of causing odd line-wrapping in the diagnostic output. You can see this in the screenshot below: it wraps awkwardly between "root" and "module" when there's no need to:

image

**Review by alisdair — APPROVED** [review]
Nice solution to a confusing bug!

File: terraform/node_provider.go (hunk 1 above)
Comment (mildwonkey) [reply terraform/node_provider.go:191]: I already tried changing the newlines - including one long single line with no newlines - and it didn't improve the output, do you know how else I might improve this?

Comment (alisdair) [reply terraform/node_provider.go:191]: Huh. Making the last paragraph a single line seemed to work for me:

```patch
diff --git a/terraform/node_provider.go b/terraform/node_provider.go
index 57245fafb..001408bf2 100644
--- a/terraform/node_provider.go
+++ b/terraform/node_provider.go
@@ -185,7 +185,4 @@ func (n *NodeApplyableProvider) ConfigureProvider(ctx EvalContext, provider prov

 const providerConfigErr = `%s

-Provider %q requires explicit configuration. Add a provider block to the root
-module and configure the provider's required arguments as described in the
-provider documentation.
-`
+Provider %q requires explicit configuration. Add a provider block to the root module and configure the provider's required arguments as described in the provider documentation.`
```

Result:

image

Comment (mildwonkey) [reply terraform/node_provider.go:191]: I apologize, my error - I tried what I _thought_ I already tried before and it now looks better. Sorry!
