### PR TITLE
show deprecation warning if -state is used with plan, apply, refresh 

### LINKED ISSUE #35562: show deprecation warning if `-state` is used in conjunction with `plan` or `apply`
### Terraform Version

```shell
$ terraform --version
Terraform v1.8.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v5.62.0
+ provider registry.terraform.io/hashicorp/external v2.3.3
+ provider registry.terraform.io/hashicorp/local v2.5.1
+ provider registry.terraform.io/hashicorp/null v3.2.2
+ provider registry.terraform.io/hashicorp/random v3.6.2
+ provider registry.terraform.io/hashicorp/tls v4.0.5
```
```


### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }

    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }

    # Needed to upgrade old Portal projects
    null = {
      source  = "hashicorp/null"
      version = "~> 3.2"
    }
  }
}

provider "aws" {
  region = local.aws_region
  default_tags {
    tags = {
      Project = local.project_name
    }
  }
}
```

```terraform
# Somewhere in other parts of a cluster configuration
resource "random_uuid" "consul_token" {
}
resource "tls_private_key" "pk" {
  algorithm = "ED25519"
}
```

### Debug Output

```
│ Error: failed to read schema for module.private-cloud.random_uuid.consul_token in registry.terraform.io/hashicorp/random: failed to instantiate provider "registry.terraform.io/hashicorp/random" to obtain schema: unavailable provider "registry.terraform.io/hashicorp/random"
```
```
│ Error: failed to read provider configuration schema for registry.terraform.io/hashicorp/tls: failed to instantiate provider "registry.terraform.io/hashicorp/tls" to obtain schema: unavailable provider "registry.terraform.io/hashicorp/tls"
```

### Expected Behavior

Terraform should load providers automatically for resources to delete them as it done for the same resources to create them.

### Actual Behavior

I need to configure providers explicitly to delete resources not in configuration but in a state.

### Steps to Reproduce

1. We had a configuration without 'tls_private_key' and 'random_uuid' resources and without 'tls' and 'random' providers.
2. We added into a configuration 'tls_private_key' and 'random_uuid' resources. **Still a configuration does not have 'tls' and 'random' providers.**
3. terraform plan/apply works fine
4. Then we decided to rollback cluster to the old configuration without 'tls_private_key' and 'random_uuid' resources and **still without 'tls' and 'random' providers.**
5. terraform plan/apply failed with the errors above

I assume, that terraform should connect tls and random providers automatically for resource delation as it was done to create these resources. For the first case, when resources are created, this is done from the information in a configuration. For the second case, when resources should be deleted, this could be done from the information in a terrafomr.tfstate file.

### Additional Context

Because for the first case terraform core loaded tls and random providers automatically, I decided that the same should be done by terraform core for the second case. Thus this does not belongs to 'terraform-provider-tls' and/or 'terraform-provider-random'.

### References

_No response_

### PR DESCRIPTION
**Pull request by melsonic**
This PR adds the functionality of showing a deprecation warning when `-state` is used along with `plan`, `apply`, and `refresh`. So, to add this functionality, I pushed a warning saying `state is deprecated` in the `diags` slice if the `state` field is not `nil` in all those three files i.e. **plan.go**, **apply.go** and **refresh.go**.

Fixes #35562

## Target Release

1.8.x

## Draft CHANGELOG entry
- shows deprecation warning for the `-state` flag when used with `plan`, `apply`, and `refresh`.

### ENHANCEMENTS 
- `terraform plan -state=mstate.tfstate` shows `**Warning**: state is deprecated`.
- `terraform refresh -state=mstate.tfstate` shows `**Warning**: state is deprecated`.
- `terraform apply -state=mstate.tfstate` shows `**Warning**: state is deprecated`.

### Output
terraform_state_warning

### CODE REVIEW

File: internal/command/apply.go [hunk 1]
```diff
@@ -56,6 +56,11 @@ func (c *ApplyCommand) Run(rawArgs []string) int {
 		return 1
 	}
 
+  if diags.HasWarnings() {
+    view.Diagnostics(diags)
+    diags = nil
+  }
+
```
Comment (liamcervante) [inline internal/command/apply.go:63]: I don't think we need this, the warning should still be printed whenever the diagnostics are chosen to be delayed.

Is there something else that is dropping / ignoring the warning diagnostics later?

File: internal/command/arguments/apply.go [hunk 2]
```diff
@@ -43,6 +43,9 @@ func ParseApply(args []string) (*Apply, tfdiags.Diagnostics) {
 	}
 
 	cmdFlags := extendedFlagSet("apply", apply.State, apply.Operation, apply.Vars)
+	if apply.State != nil {
+		diags = append(diags, tfdiags.SimpleWarning("state is deprecated"))
```
Comment (liamcervante) [inline internal/command/arguments/apply.go:47]: It'd be nice if this error message could present an alternative instead.

The correct thing to do is update the configuration to point to the chosen state file: https://github.com/hashicorp/terraform/issues/35562#issuecomment-2289437736

Maybe we could make this a proper diagnostic with the detail stating to use the path variable in the local backend?

File: internal/command/apply.go (hunk 1 above)
Comment (melsonic) [reply internal/command/apply.go:63]: Actually, it is required to print the diagnostics before, since on line number 73 `planFile, diags := c.LoadPlanFile(args.PlanPath)` returns a new diagnostic slice, it doesn't append to the already available `diags` variable.

File: internal/command/arguments/apply.go (hunk 2 above)
Comment (melsonic) [reply internal/command/arguments/apply.go:47]: Sure, will update and add a commit. And also, I have found a better way to check if the `state` flag is specified, will add this also in the next commit.

File: internal/command/apply.go (hunk 1 above)
Comment (liamcervante) [reply internal/command/apply.go:63]: Cool, I think we can change the other part instead of doing this 👍 It's more in keeping with the way the diagnostics are intended to work to just gather them up and report once.


You can change line 73 to something like:

```
	planFile, moreDiags := c.LoadPlanFile(args.PlanPath)
        diags = diags.Append(moreDiags)
	if moreDiags.HasErrors() {
		view.Diagnostics(diags)
		return 1
	}
```

Comment (melsonic) [reply internal/command/apply.go:63]: > Cool, I think we can change the other part instead of doing this 👍 It's more in keeping with the way the diagnostics are intended to work to just gather them up and report once.
> 
> You can change line 73 to something like:
> 
> ```
> 	planFile, moreDiags := c.LoadPlanFile(args.PlanPath)
>         diags = diags.Append(moreDiags)
> 	if moreDiags.HasErrors() {
> 		view.Diagnostics(diags)
> 		return 1
> 	}
> ```

Yeah, this can be done.

File: internal/command/arguments/apply.go (hunk 2 above)
Comment (melsonic) [reply internal/command/arguments/apply.go:47]: Hi @liamcervante 
image
Does it align with your thoughts? I also added the link to the resource for easier navigation.

File: internal/command/arguments/apply.go [hunk 3]
```diff
@@ -57,6 +57,14 @@ func ParseApply(args []string) (*Apply, tfdiags.Diagnostics) {
 		))
 	}
 
+	if apply.State.StatePath != "" {
+		diags = diags.Append(tfdiags.Sourceless(
+			tfdiags.Warning,
+			"state is deprecated",
+			fmt.Sprintf("use path variable of local backend instead : https://developer.hashicorp.com/terraform/language/settings/backends/local\n"),
```
Comment (liamcervante) [inline internal/command/arguments/apply.go:64]:
```suggestion
			"Deprecated flag: -state",
			fmt.Sprintf("Use `path` attribute within the `local` backend instead: https://developer.hashicorp.com/terraform/language/v1.10.x/settings/backends/local#path"),
```

Just a couple of nits over the language here. 

I'd want to call out that it's the flag specifically that is deprecated.

Also, the documentation can change over time so I think it's better for us to link to the v1.10.x documentation directly given we're adding this deprecation warning for the 1.10 release. That way if we change the `local` backend in the future, people using this version will get a direct link to something that makes sense.

Can you copy these changes over to the other places we raise the warning?

Thanks!

**Review by liamcervante — COMMENTED** [review]
Thanks! Looking good, just some recommendations over the content of the error!

**Comment by liamcervante** [comment]
Oh yeah, the consistency checks make the point that you don't need to use Sprintf for the detail part of the error since the string is constant.

File: internal/command/arguments/apply.go (hunk 3 above)
Comment (melsonic) [reply internal/command/arguments/apply.go:64]: Yeah, that makes sense. 
Thanks

**Review by liamcervante — APPROVED** [review]
Nice, looks good! Will merge after the checks have finished!

**Comment by liamcervante** [comment]
Merged, and CHANGELOG updated. Will be released as part of 1.10.0, thanks for your contribution!

**Comment by melsonic** [comment]
> Merged, and CHANGELOG updated. Will be released as part of 1.10.0, thanks for your contribution!

Thanks for your guidance throughout the PR :)
