### PR TITLE
terraform test: remove marks before passing variables as inputs to a plan

### LINKED ISSUE #34185: Using sensitive values in subsequent run blocks of terraform test not possible: value has marks
### Terraform Version

```shell
$  terraform version
Terraform v1.6.3
on linux_amd64
```

### Terraform Configuration Files

In my actual scenario I use terraform to create a new deployment in Elastic Cloud. As part of this creation process in the first `run` block of the terraform test, I get (among a lot of other information) the URI, username and password needed to contact the Elasticsearch instance. This information is then used in a subsequent `run` block to access the Elasticsearch instance and to query the clusters health state.

I have created the following minimal example to show case the issue. 

File structure:

```none
.
├── examples
│   └── mymodule
│       ├── main.tf
│       └── tests
│           ├── checkmore
│           │   └── main.tf
│           └── mymodule.tftest.hcl
└── mymodule
    └── outputs.tf
```

Files:

`mymodule/outputs.tf`

```terraform
output "password" {
  value     = "foobar"
  sensitive = true
}
```

`examples/mymodule/main.tf`

```terraform
module "mymodule_example" {
  source = "../../mymodule"
}

output "mymodule_example_password" {
  value     = module.mymodule_example.password
  sensitive = true
}
```

`examples/mymodule/tests/mymodule.tftest.hcl`

```hcl
run "mymodule" {
  command = apply

  assert {
    condition     = output.mymodule_example_password == "foobar"
    error_message = "Unexpected password"
  }
}

run "dependent_test" {
  command = apply

  module {
    source = "./tests/checkmore"
  }

  variables {
    secretvalue = run.mymodule.mymodule_example_password
  }

  assert {
    condition     = output.secretvalue == "foobar"
    error_message = "Unexpected secretvalue"
  }
}
```

`examples/mymodule/tests/checkmore/main.tf`

```terraform
variable "secretvalue" {
  type = string
}

output "secretvalue" {
  value     = var.secretvalue
  sensitive = true
}
```

### Debug Output

not provided

### Expected Behavior

The credentials returned during resource creation in a first `run` step should then be available in the subsequent `run` steps.

### Actual Behavior

I always get the following error from terraform:

```none
│ Error: Failed to prepare variable value for plan
│
│ The value for variable "password" could not be serialized to store in the plan: value has marks, so it cannot be serialized.
```

### Steps to Reproduce

1. `cd examples/mymodule`
2. `terraform init`
3. `terraform test`

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by liamcervante**
This PR removes the sensitive marks from variables before passing them as input variables into run blocks. This only affects situations where users are passing outputs from previous run blocks that are marked as sensitive.

In addition, we add a warning if the receiving variable configuration isn't also marked as sensitive, as the sensitive metadata is being lost if the config isn't also marked as sensitive. It might be we want to actually completely disallow this, so add this diagnostic as an error instead of a warning. I'm happy to make that change if we think it's necessary.

Fixes #34185 

## Target Release

1.6.4

### BUG FIXES

 

-  `terraform test`: Fix bug preventing passing sensitive output values from previous run blocks as inputs to future run blocks.

### CODE REVIEW

File: internal/backend/local/test.go [hunk 1]
```diff
@@ -1124,17 +1136,50 @@ func (runner *TestFileRunner) GetVariables(config *configs.Config, run *modulete
 // This function is essentially the opposite of AddVariablesToConfig which
 // makes the config match the variables rather than the variables match the
 // config.
-func (runner *TestFileRunner) FilterVariablesToConfig(config *configs.Config, values terraform.InputValues) terraform.InputValues {
+//
+// warnOnSensitivityChange will prompt this function to add warnings if an input
```
Comment (jbardin) [inline internal/backend/local/test.go:1140]: Is this a name that was refactored out elsewhere?

**Review by jbardin — APPROVED** [review]

File: internal/backend/local/test.go (hunk 1 above)
Comment (liamcervante) [reply internal/backend/local/test.go:1140]: yeah, initially I had an argument that meant the function would only selectively add the warnings if this was true but then I realised the caller could just ignore the diagnostics so we didn't need to modify the function to exclude them internally.

I must've forgot update the doc comment when I removed it!
