### PR TITLE
configs: explicitly nullable variable values

### LINKED ISSUE #24142: null value is not treated per docs when passed to modules
### Terraform Version

```
Terraform v0.12.20
```

### Terraform Configuration Files

`main.tf`:

```hcl
module mod1 {
  source         = "./mod1"
  optional_input = null
}
```

`mod1/main.tf`:

```hcl
variable optional_input {
  default = 5
}

output foo {
  value = var.optional_input / 5
}
```

### Debug Output

https://pastebin.com/raw/NuxLJi2U

### Expected Behavior

As per [docs](https://www.terraform.io/docs/configuration/expressions.html#null):

> `null`: a value that represents absence or omission. If you set an argument of a resource or **module to null**, Terraform behaves as though you had completely omitted it — it will use the argument's default value if it has one

### Actual Behavior

An error message is shown saying that the said argument must not be null:

```
  on mod1/main.tf line 6, in output "foo":
   6:   value = var.optional_input / 5
    |----------------
    | var.optional_input is null

Error during operation: argument must not be null.
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### References
- #22430
- #21702

### PR DESCRIPTION
**Pull request by jbardin**
The current behavior of module input variables is to allow users to
override a default by assigning `null`, which works contrary to the
behavior of resource attributes, and prevents explicitly accepting a
default when the input must be defined in the configuration.

Add a new variable attribute called `nullable` will allow explicitly
defining when a variable can be set to null or not. The current default
behavior is that of `nullable=true`.

Setting `nullable=false` in a variable block indicates that the variable
value can never be null. This either requires a non-null input value, or
a non-null default value. In the case of the latter, we also opt-in to
the new behavior of a `null` input value taking the default rather than
overriding it.

In a future language edition where we make `nullable=false` the default,
setting `nullable=true` will allow the legacy behavior of `null`
overriding a default value. The only future configuration in which this
would be required even if the legacy behavior were not desired is when
setting an optional+nullable value. In that case `default=null` would
also be needed and we could therefor imply `nullable=true` without
requiring it in the configuration.

The possible combinations of variable configuration are:

```
# Variable must be set, but may be explicitly set to null.
# In this case, the module author must deal with var.a possibly being null
variable "a" {
  nullable = true
}

# Variable may be omitted, in which case it takes on the default, or may be
# explicitly set to null in which case it appears as null
# In this case, the module author must deal with var.b possibly being null
variable "b" {
  nullable = true
  default  = "hello"
}

# Optional variable where null is allowed. `nullable=true` is default now, and
# may be inferred in the future from `default=null` value when `nullable=false`
# becomes the default, so setting nullable here should never be required.
# In this case, the module author must deal with var.b possibly being null
variable "c" {
  nullable = true
  default  = null
}

# Non-nullable with a default: if left unset, or set explicitly to null, then
# it takes on the default value
# In this case, the module author can safely assume var.d will never be null
variable "e" {
  nullable = false
  default  = "hello"
}

# Non-nullable with no default: variable must be set, and cannot be null.
# In this case, the module author can safely assume var.d will never be null
variable "e" {
  nullable = false
}

# Non-nullable with a null default: an invalid combination, because a non-nullable
# variable can never be null
variable "f" {
  nullable = false
  default  = null
}
```

Fixes #24142

### CODE REVIEW

File: internal/configs/named_values.go [hunk 1]
```diff
@@ -110,6 +115,15 @@ func decodeVariableBlock(block *hcl.Block, override bool) (*Variable, hcl.Diagno
...
 
+	if attr, exists := content.Attributes["nullable"]; exists {
+		valDiags := gohcl.DecodeExpression(attr.Expr, nil, &v.Nullable)
+		diags = append(diags, valDiags...)
+	} else {
+		// The current default is true, which is subject to change in a future
+		// language edition.
+		v.Nullable = true
+	}
+
```
Comment (apparentlymart) [inline internal/configs/named_values.go:126]: Do we need to do anything special here to deal with override files?

I don't know if there's a real use-case for overriding the "nullability" of a variable, but if we want to support it I think we'd need to have a `NullableSet` field alongside so that the override-merging logic can understand whether the override file is setting it or not.

Alternatively, we could decide that override files are not allowed to change nullability -- it doesn't really seem to be the sort of thing the override files feature is normally used for -- and in that case just return an error in the `exists` case if the `override` flag is also set, effectively making it invalid to set `nullable` in override files.

I initially thought we'd need to allow `nullable = true` in override files so that a future edition upgrade could add it there, but I think that's not actually true because we only allow override files to change the definition of variables already declared and never to declare entirely new variables, and so we'd always be able to add the `nullable = true` to the original declaration and get the same effect as adding it to the override file, assuming we forbid setting it in override files.

**Review by apparentlymart — COMMENTED** [review]
I didn't have time yet to read through all of this because I have a meeting shortly but I wanted to just share the one comment I already left inline here, in case it's helpful in the meantime, and then I'll come back and read more of this a bit later if someone else doesn't get there first!

What I read so far looks good, though!

File: internal/terraform/evaluate.go [hunk 2]
```diff
@@ -268,11 +268,27 @@ func (d *evaluationStateData) GetInputVariable(addr addrs.InputVariable, rng tfd
...
 	val, isSet := vals[addr.Name]
-	if !isSet {
-		if config.Default != cty.NilVal {
-			return config.Default, diags
-		}
-		return cty.UnknownVal(config.Type), diags
+	switch {
+	case !isSet:
+		// The config loader will ensure there is a default if the value is not
+		// set at all.
```
Comment (alisdair) [inline internal/terraform/evaluate.go:274]: I'm a bit confused after reading this comment. Where does the config loader ensure that a variable has a `Default` set?

I was expecting a diag here if `nullable` is `false` and there's no `Default`. Is that handled elsewhere?

**Review by alisdair — COMMENTED** [review]
I like this revised design a lot! There was one part inline that I'm a bit confused by. I think we'll need a docs update for this too.

File: internal/configs/named_values.go (hunk 1 above)
Comment (jbardin) [reply internal/configs/named_values.go:126]: Thanks, I did forget to prevent this from being overridden. I don't see a compelling reason to allow overriding `nullable`, or at least we can start more conservatively and allow it later if it would prove to be useful.

File: internal/terraform/evaluate.go (hunk 2 above)
Comment (jbardin) [reply internal/terraform/evaluate.go:274]: This case is assured because in the absence of a default value, a module call must contain an assignment for the variable, therefore `if !isSet` then we must have a default. The comment is only there because we're not checking `config.Default != cty.NilVal`.

Comment (jbardin) [reply internal/terraform/evaluate.go:274]: Oh, and the case of if nullable is false and there's no Default is handled by the 3rd case in this switch

```
case val.IsNull() && !config.Nullable:
```

Why which time we have also determined from the prior case statements that there is an input value set and there is no default.

File: internal/configs/named_values.go (hunk 1 above)
Comment (jbardin) [reply internal/configs/named_values.go:128]: Actually since we make the nullable value true by default during decoding, and we can override the `Default` value, I had to handle this in both in decoding and merging anyway. Since the merging rules are clearly laid out already I went with them for now, and allowed the explicit overriding of `nullable`, however the implicit `true` setting will not override a given block.

File: internal/terraform/evaluate.go [hunk 3]
```diff
@@ -268,11 +268,27 @@ func (d *evaluationStateData) GetInputVariable(addr addrs.InputVariable, rng tfd
...
+		val = config.Default
+
+	case val.IsNull() && !config.Nullable:
+		// The value cannot be null, and there is no configured default.
+		diags = diags.Append(&hcl.Diagnostic{
+			Severity: hcl.DiagError,
+			Summary:  `Invalid variable value`,
+			Detail:   fmt.Sprintf(`The resolved value of variable %q cannot be null.`, addr.Name),
+			Subject:  &config.DeclRange,
+		})
```
Comment (apparentlymart) [inline internal/terraform/evaluate.go:288]: It feels a bit funny to be catching this definition-related error in here, since the `evaluationStateData` component is normally concerned with validating references to other objects rather than validating those objects themselves. That is, in source range terms we're validating what's in `rng` rather than what's in `config.DeclRange` here.

Is there a "validate input variable" graph node we could check this in instead, so that we can be sure to always catch it even if there aren't any references to the variable? (Perhaps we always end up in here even if there aren't any references as a side-effect of some other quirky decision anyway, but if so I'd rather not rely on that, since if I were looking for this validation rule I'd expect to find it somewhere else. :thinking: )

Comment (jbardin) [reply internal/terraform/evaluate.go:288]: Ah, you're right. This ended up here because that's where I was working to assign the default, but it could be could be done earlier in evaluation, since we have the variable configuration at the point of module call evaluation. 
We use the same variable node for all actions (which is another issue), but I can move this validation check into there.

Comment (apparentlymart) [reply internal/terraform/evaluate.go:288]: On a related note, I'd suggest making this message say something more like "this variable is required", which is what we'd say if someone tried to assign a `null` to a provider argument whose schema says `Required: true`. I assume we already have some error text like this for the situation of omitting a required variable altogether, so maybe we can reuse that either in its entirety or with some adjustments.

Comment (jbardin) [reply internal/terraform/evaluate.go:288]: The reason I chose the wording here is that the biggest stumbling point for users has been when assigning variables in a module expanded with `for_each`, and I though it would be less confusing to state that it cannot be `null` since they _are_ assigning a value, it just requires a non-null value to be assigned and one of the `each.value` may be null. The error from the provider is a good point though, and perhaps ensuring they match is more important for now.

Comment (jbardin) [reply internal/terraform/evaluate.go]: Moved the validation check into the module call evaluation, and created what I think is a better error message, indicating that the variable is required, but the given value evaluated to null.

**Review by alisdair — APPROVED** [review]

File: internal/terraform/node_module_variable.go [hunk 4]
```diff
@@ -253,7 +253,23 @@ func (n *nodeModuleVariable) evalModuleCallArgument(ctx EvalContext, validateOnl
...
 	}
 
+	// If there is no default, we have to ensure that a null value is allowed
+	// for this variable.
+	if n.Config.Default == cty.NilVal && !n.Config.Nullable && val.IsNull() {
+		// The value cannot be null, and there is no configured default.
+		diags = diags.Append(&hcl.Diagnostic{
+			Severity: hcl.DiagError,
+			Summary:  `Invalid variable value`,
+			Detail:   fmt.Sprintf(`The variable %q is required, but the given value resolved to null`, n.Addr),
```
Comment (apparentlymart) [inline internal/terraform/node_module_variable.go:263]: One final nitpick :grimacing: : detail messages should end with a period for consistency with our usual style.

More subjectively, I think we don't normally talk about values being "resolved" so maybe we can just say "but the given value _is_ null".

**Review by apparentlymart — APPROVED** [review]
Looks good to me!

File: internal/terraform/node_module_variable.go (hunk 4 above)
Comment (jbardin) [reply internal/terraform/node_module_variable.go:263]: The resolved term was taken from your other variable evaluation diagnostic 😉
```
The resolved value of variable %q is not appropriate:
```

But I agree a more direct "the value is" ends up sounding better here.

**Comment by jbardin** [comment]
I'll follow up with a separate PR for docs
