### PR TITLE
Structured Renderer: use the new renderer when rendering the state in addition to the plan

### LINKED ISSUE #32621: `terraform show` output incorrectly omits nested attribute values, marking them as "unchanged elements"
### Terraform Version

```
Terraform v1.4.0-dev
on darwin_amd64
+ provider registry.terraform.io/hashicorp/tfcoremock v0.1.2
```

### Terraform Configuration Files

```terraform
resource "tfcoremock_dynamic_resource" "example" {
  nested_map = {
    "foo" = {
      boop = true
      beep = "foop"
    }
    "bar" = {
      beep = "barp"
    }
  }
}
```

`dynamic_resources.json`:
```json
{
  "tfcoremock_dynamic_resource": {
    "attributes": {
      "nested_map": {
        "type": "map",
        "required": true,
        "map": {
          "type": "object",
          "object": {
            "boop": {
              "type": "boolean",
              "optional": true
            },
            "beep": {
              "type": "string",
              "optional": true
            }
          }
        }
      }
    }
  }
}
```

### Debug Output

N/A

### Expected Behavior

```shellsession
$ terraform show
# tfcoremock_dynamic_resource.example:
resource "tfcoremock_dynamic_resource" "example" {
    id         = "77a6363a-c9eb-1b65-7e75-646ec3591b7b"
    nested_map = {
        "foo" = {
            boop = true
            beep = "foop"
        }
        "bar" = {
            beep = "barp"
        }
    }
}
```

### Actual Behavior

```shellsession
$ terraform show
# tfcoremock_dynamic_resource.example:
resource "tfcoremock_dynamic_resource" "example" {
    id         = "77a6363a-c9eb-1b65-7e75-646ec3591b7b"
    nested_map = {
        # (2 unchanged elements hidden)
    }
}
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply -auto-approve`
3. `terraform show`

### Additional Context

`terraform show` (when showing state, not a plan) should not use the concise diff rendering format, as it will never be displaying a change where we want to omit unchanged values.

### References

Noted as part of #32619 (thanks, @bendbennett!)

### PR DESCRIPTION
**Pull request by liamcervante**
Fixes #32621 

This PR adds an additional function to the new structured renderer: `RenderHumanState`. This function is called from the show command so the state rendering and the plan rendering both use the same code path.

There are a few changes to the diffing and rendering code to make this work. 

- Firstly, a new option has been added to the renderer (`HideDiffActionSymbols`) that tells the renderer not to place any indents for symbols or actual symbols into the rendered output. This means the state rendering doesn't use the extra offsets placed in for the symbols that are used in the plan rendering. This is because the state renderer is always rendering no-ops so never has to show any symbols.
- Secondly, the `ComputeChangeForType` function on the differ.Change objects is made public as the state renderer has more information about the types of outputs than the plan renderer and can use this function instead of interpreting the type. 

In addition to the above, I have refactored the renderer code so the plan and state rendering code paths are in their own files as the renderer.go file was getting very full. I think this makes the API of the renderer cleaner and clearer for callers. This change has no functional changes on anything and is just for aesthetics.

There are also numerous changes making the structs in the `jsonstate` package public so the renderer can use them. This also involves making the `Index` attributes into `json.RawMessage` slices instead of keeping them as unparseable objects. This is an okay change, because they are rendered the same in JSON anyway and until now we were not reading them anywhere so the fact they couldn't be read back in was not a problem. Additionally, I update the `AttributeValues` type so that it explicitly states that the values are `json.RawMessage` slices. Previously, they were identified as `interface{}` types but were always being populated as `json.RawMessage` so I don't see why we don't just say that's what they are. This change also doesn't affect the actual output since they were always `json.RawMessage` objects anyway.

A future change could optimise the TFC backend so that it retrieves a JSONified version of the state and passes that directly into the renderer, but for now it can carry on retrieving the full state and converting to JSON locally as the local backend does anyway.

### CODE REVIEW

**Comment by liamcervante** [comment]
I could go through here and make a chain of smaller changes as I did before, if you think this PR is too big/complex to review in one.

File: internal/command/jsonformat/state.go [hunk 1]
```diff
@@ -0,0 +1,124 @@
...
+		case jsonstate.DataResourceMode:
+			renderer.Streams.Printf("data %q %q %s", resource.Type, resource.Name, differ.FromJsonResource(resource).ComputeDiffForBlock(schema.Block).RenderHuman(0, opts))
+		default:
+			panic("found unrecognized resource mode: " + resource.Mode)
+		}
+
+		renderer.Streams.Println()
+	}
+
+	// Render depth-first, so we show children first.
```
Comment (alisdair) [inline internal/command/jsonformat/state.go:95]: I don't understand the "so we show children first" part of this comment. At first I thought this block should be before the loop over resources in this module, but I think the behaviour we have is reasonable, it just doesn't seem to quite line up with the comment. Maybe I'm missing something.

File: internal/command/jsonformat/state_test.go [hunk 2]
```diff
@@ -0,0 +1,437 @@
...
+			onlyDeposedOutput,
+		},
+		{
+			&format.StateOpts{
+				State:   stateWithMoreOutputs(t),
+				Color:   color,
+				Schemas: testSchemas(),
+			},
+			stateWithMoreOutputsOutput,
+		},
```
Comment (alisdair) [inline internal/command/jsonformat/state_test.go:79]: If we care about the order in which we traverse the module graph, it'd be nice to have a test case for that. Something like the following modules with a resource or two in each:

```mermaid
graph TD
    root --> alpha
    root --> beta
    alpha --> gamma
    alpha --> delta
    beta --> epsilon
```

(Only bringing this up because of my confusion over the comment, noted above.)

File: internal/command/views/operation.go [hunk 3]
```diff
@@ -96,8 +96,9 @@ func (v *OperationHuman) Plan(plan *plans.Plan, schemas *terraform.Schemas) {
 	}
 
 	renderer := jsonformat.Renderer{
-		Colorize: v.view.colorize,
-		Streams:  v.view.streams,
+		Colorize:            v.view.colorize,
+		Streams:             v.view.streams,
+		RunningInAutomation: v.inAutomation,
```
Comment (alisdair) [inline internal/command/views/operation.go:101]: Huh. I hadn't realized this wasn't hooked up until now. Nice catch!

File: internal/command/views/show_test.go [hunk 4]
```diff
@@ -53,7 +53,7 @@ func TestShowHuman(t *testing.T) {
 			},
 			testSchemas(),
 			true,
-			"\n",
+			"The state file is empty. No resources are represented.\n",
```
Comment (alisdair) [inline internal/command/views/show_test.go:56]: This seems like a good change in behaviour, and our human-readable output is largely exempt from backwards compatibility guarantees, so I think it's fine. We should probably note it in the changelog, though.

**Review by alisdair — APPROVED** [review]
Nice work!

File: internal/command/jsonformat/state.go (hunk 1 above)
Comment (liamcervante) [reply internal/command/jsonformat/state.go:95]: We don't want to show the children first. This is left over from confusion caused by the old approach.

Previously, the order of the modules was not consistent and AFAICT fairly random. And I was doing diff testing, and noticed in one run that my order was different and thought it was because I had root first and children after. I rearranged the order as described by you and then re-ran my checks and got a different result. So I decided that it makes more sense to show the root first as I had previously, and that we would now have a consistent ordering but I never went back and removed this comment 😓 

I've removed the comment now, and since we're no longer making claims on the ordering I don't think a test is needed.

File: internal/command/jsonformat/state_test.go (hunk 2 above)
Comment (liamcervante) [reply internal/command/jsonformat/state_test.go:79]: We don't care about the order (or at least the old renderer didn't care about the order). I've replied to your comment above as well, but the tl;dr is that comment was left over.

Given we don't care about the ordering, I don't think I'll add this test. But if you think we should start caring about the order then I can add a test. Let me know!

File: internal/command/views/show_test.go (hunk 4 above)
Comment (liamcervante) [reply internal/command/views/show_test.go:56]: I'll update the changelog 👍

File: internal/command/jsonformat/state_test.go (hunk 2 above)
Comment (alisdair) [reply internal/command/jsonformat/state_test.go:79]: Nope! Let's not make more work for ourselves.

File: internal/command/jsonformat/state.go (hunk 1 above)
Comment (apparentlymart) [reply internal/command/jsonformat/state.go]: I'm lacking some context here so this is just "FYI this exists" rather than any assumption it would be appropriate to use here, but I wanted to note that we have [`addrs.AbsResourceInstance.Less`](https://pkg.go.dev/github.com/hashicorp/terraform/internal/addrs#AbsResourceInstance.Less) to define our "default ordering" for sets of resource instances where we don't have any other specific order to use.

That `Less` function takes into account various details, such as sorting first by module membership and then by resource address, and making sure that we use numeric ordering rather than string-based ordering for the integer instance keys caused by the `count` feature.

It looks like this code is currently using a locally-implemented order, I guess in part because it needs to take into account the possibility of "deposed objects" which are outside of what `AbsResourceInstance` can describe. But perhaps we could use the canonical ordering for any pair of addresses that have differences beyond the deposed key.

Comment (liamcervante) [reply internal/command/jsonformat/state.go]: Thanks for this Martin, that's some good context.

I'll leave this as is for now, because I think a better approach if we wanted to do the sorting properly would be to do the sorting in the json packages that generate the JSON structs themselves, and then the renderer can just print the things without sorting. I'll have a look at this in a separate PR.

For this PR, I think it's more important just to make sure the output is consistent and then we don't have to worry about converting back into the Terraform structs. If we do the sorting before we marshal it into JSON then it's already in the Terraform structs.
