### PR TITLE
terraform: allow literal maps to be passed to modules

### LINKED ISSUE #7140: Unable to pass map literals as module parameters
### Terraform Version

master / 2127466280172a7cd0aa1d863cb932aa0107c986 

### Affected Resource(s)

core

### Terraform Configuration Files
```tf
# main.tf
module "mod" {
  source   = "./mod"
  mapparam = { }
}
```

```tf
# mod/main.tf
variable "mapparam" { type = "map" }
```

### Steps to Reproduce

```
terraform get
terraform apply
```

### Expected Behavior

No error message.

### Actual Behavior

```
Error configuring: 1 error(s) occurred:

* variable mapparam in module mod should be type map, got []interface {}
```

### PR DESCRIPTION
**Pull request by phinze**
Passing a literal map to a module looks like this in HCL:

    module "foo" {
      source = "./foo"
      somemap {
        somekey = "somevalue"
      }
    }

The HCL parser always wraps an extra list around the map, so we need to
remove that extra list wrapper when the parameter is indeed of type "map".

Fixes #7140

### CODE REVIEW

File: terraform/eval_variable.go [hunk 1]
```diff
@@ -21,10 +21,6 @@ import (
 //       declared
 //     - the path to the module (so we know which part of the tree to
 //       compare the values against).
-//
-// Currently since the type system is simple, we currently do not make
-// use of the values since it is only valid to pass string values. The
-// structure is in place for extension of the type system, however.
```
Comment (phinze) [inline terraform/eval_variable.go]: This bit of the comment was no longer valid by the time I got here.

File: terraform/eval_variable.go [hunk 2]
```diff
@@ -81,6 +77,12 @@ func (n *EvalTypeCheckVariable) Eval(ctx EvalContext) (interface{}, error) {
 			case map[string]interface{}:
 				continue
 			default:
+				if list, ok := proposedValue.([]interface{}); ok && len(list) == 1 {
+					if m, ok := list[0].(map[string]interface{}); ok {
+						n.Variables[name] = m
+						continue
+					}
+				}
```
Comment (phinze) [inline terraform/eval_variable.go]: I don't like doing the coercion mid-type-check. I'm planning to pull this out into its own `EvalNode`.

Just wanted to get visibility on the strategy before i go further

**Comment by jbardin** [comment]
LGTM (emphasis on the TM here, I'm not sure if there are other implications to consider)

**Comment by phinze** [comment]
👌  will wait for a @jen20 double check here

File: terraform/eval_variable.go [hunk 3]
```diff
@@ -50,10 +47,6 @@ func (n *EvalTypeCheckVariable) Eval(ctx EvalContext) (interface{}, error) {
 	}
 
 	for name, declaredType := range prototypes {
-		// This is only necessary when we _actually_ check. It is left as a reminder
-		// that at the current time we are dealing with a type system consisting only
-		// of strings and maps - where the only valid inter-module variable type is
-		// string.
```
Comment (jen20) [inline terraform/eval_variable.go]: :+1: on removing this comment (added for a late-version 0.6.x)

**Comment by jen20** [comment]
Yup, this LGTM too.
