### PR TITLE
Provider configuration_aliases and module validation

### LINKED ISSUE #26354: Can't find provider with alias
### Terraform Version

```
Terraform v0.13.3
```

### Terraform Configuration Files

`versions.tf`:
```terraform
terraform {
  required_version = ">= 0.13"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.7.0"
    }
    external = {
      source  = "hashicorp/external"
      version = "~> 1.2.0"
    }
  }
}
```
`main.tf`:
```terraform
provider "aws" {
  alias  = "master_va"
  region = "us-east-1"
}

module "master_route53" {
  providers = {
    aws  = aws.master_va
    apex = aws.master_va
  }

  source             = "./modules/organization_route53"
  org                = var.org
  account            = "master"
  public_domain_name = "example.com"
  delegate           = false

  default_tags = merge(
    local.default_tags,
    {
      "account" = "master"
    },
  )
}

module "dev_route53" {
  providers = {
    aws  = aws.dev_va
    apex = aws.master_va
  }

  source             = "./modules/organization_route53"
  org                = var.org
  account            = "dev"
  public_domain_name = "dev.example.com"
  delegate           = true
  apex_zone_id       = module.master_route53.public_zone_id

  default_tags = merge(
    local.default_tags,
    {
      "account" = "dev"
    },
  )
}

```

`modules/organization_route53/main.tf`:
```terraform
provider "aws" {
  alias = "apex"
}

resource "aws_route53_zone" "public" {
  name = var.public_domain_name

  tags = merge(
    var.default_tags,
    {
      "Name" = "${var.account} public"
    },
  )
}

resource "aws_route53_record" "ns_record" {
  provider = aws.apex

  count = var.delegate ? 1 : 0

  type    = "NS"
  zone_id = var.apex_zone_id
  name    = var.account
  ttl     = "172800"
  records = aws_route53_zone.public.name_servers
}

```

### Debug Output

https://gist.github.com/steeef/6a432c498862ef3ded498522b23a3c75

### Expected Behavior

Terraform should use the default `aws` provider to create an AWS Route 53 zone, and then the provider with alias `apex` to create the DNS records to delegate entries for the subdomain in the `aws` provider.
### Actual Behavior

I recieved the error:

```
Error: missing provider provider["registry.terraform.io/hashicorp/apex"].master_va
```

### Steps to Reproduce

1. terraform init
2. terraform plan
### Additional Context

I'm upgrading an existing Terraform configuration from `v0.12.29` to `v0.13.3`. This is a complicated configuration since it manages an entire AWS Organizations organization including AWS account-specific resources in multiple accounts. The intent here is to manage AWS Route53 zones for both the `master` account (referenced by the provider with alias `apex`) and any member accounts (referenced by the default `aws` provider). Each account in the AWS Organization has a copy of the `route53` module, including the `master` account, where both providers (`aws` and `apex`) point to the same `master_va` provider. I can't determine from the error message which one of these entries caused the error. I can paste more if necessary.

I find it odd that it's trying to find a provider with type `apex` when it's really a provider with type `aws` and alias `apex`.

### LINKED ISSUE #26448: Failed to install providers for proxied external providers, e.g. cloudflare
### Terraform Version

```
0.13.3
```

### Terraform Configuration Files

`./main.tf`:
```terraform
terraform {
  backend "local" {}

  required_version = "0.13.3"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3"
    }

    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 2"
    }

    external = {
      source  = "hashicorp/external"
      version = "~> 1.2"
    }
  }
}

provider "aws" {
  region = "eu-west-1"
}

provider "cloudflare" {}

provider "external" {}

module "submodule" {
  source = "./submodule"

  providers = {
    aws                     = aws
    cloudflare              = cloudflare
    external                = external
  }

  (...)
}

(...)
```

`./submodule/main.tf`:
```terraform
terraform {
  backend "local" {}

  required_version = "0.13.3"
}

provider "aws" {
}

provider "cloudflare" {
}

provider "external" {
}

(...)
```

### Crash Output

```
$> terraform init; terraform validate;

Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Using previously-installed hashicorp/external v1.2.0
- Using previously-installed hashicorp/null v2.1.2
- Using previously-installed hashicorp/template v2.1.2
- Using previously-installed hashicorp/aws v3.8.0
- Using previously-installed cloudflare/cloudflare v2.11.0
- Finding latest version of hashicorp/cloudflare...

Error: Failed to install providers

Could not find required providers, but found possible alternatives:

  hashicorp/cloudflare -> cloudflare/cloudflare

If these suggestions look correct, upgrade your configuration with the
following commands:
    terraform 0.13upgrade submodule


Error: Could not load plugin


Plugin reinitialization required. Please run "terraform init".

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints, run "terraform providers".

Failed to instantiate provider "registry.terraform.io/hashicorp/cloudflare" to
obtain schema: unknown provider "registry.terraform.io/hashicorp/cloudflare"
```

### Expected Behavior

Proxied external providers (not the ones from `hashicorp/...` should work the same as the hashicrop's ones) should be passed properly and just work.

### Actual Behavior

It fails the validation, because provider is not passed properly to submodules.

### Steps to Reproduce

1. terraform init
2. terraform validate

### Additional Context

If I add `required_providers` just for `cloudflare` it starts to work.
`./submodule/main.tf`:
```terraform
terraform {
  backend "local" {}

  required_version = "0.13.3"

    required_providers {
      cloudflare = {
        source  = "cloudflare/cloudflare"
        version = "~> 2"
      }
    }
}

provider "aws" {
}

provider "cloudflare" {
}

provider "external" {
}

(...)
```

### LINKED ISSUE #26617: Confusing error message when missing a proxy provider configuration
### Terraform Version
```
$ terraform version
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/aws v3.11.0
```

### Terraform Configuration Files

Initial state

```
$ find -name *.tf | more $(cat) | cat
::::::::::::::
./main.tf
::::::::::::::
variable "aws_access_key" {}

variable "aws_secret_key" {}

provider "aws" {
  access_key = var.aws_access_key
  secret_key = var.aws_secret_key
  region = "us-west-2"
}

module "m" {
  source = "./m"
}
::::::::::::::
./m/main.tf
::::::::::::::
provider "aws" {
  alias  = "us_east_1"
  region = "us-east-1"
}

data "aws_sns_topic" "x" {
  provider = aws.us_east_1
  name = "TLSCertHealthChecks"
}

resource "aws_s3_bucket_object" "X" {
  provider = aws.us_east_1
  bucket = "my-us-east-1-bucket"
  key = "foo"
  content = data.aws_sns_topic.x.arn
}
```

Run `terraform init ; terraform apply` (which works)
Modify the config to:

```
$ find -name *.tf | more $(cat) | cat
::::::::::::::
./main.tf
::::::::::::::
variable "aws_access_key" {}

variable "aws_secret_key" {}

provider "aws" {
  access_key = var.aws_access_key
  secret_key = var.aws_secret_key
  region = "us-west-2"
}

provider "aws" {    // ADD
  alias  = "us_east_1"
  region = "us-east-1"
}

module "m" {
  source = "./m"
  providers = {    // ADD
    aws.us_east_1 = aws.us_east_1
  }
}
::::::::::::::
./m/main.tf
::::::::::::::
// rm aws.us_east_1
data "aws_sns_topic" "x" {
  provider = aws.us_east_1
  name = "thing"
}

resource "aws_s3_bucket_object" "X" {
  provider = aws.us_east_1
  bucket = "my-us-east-1-bucket"
  key = "foo"
  content = data.aws_sns_topic.x.arn
}
```

Try to reapply and get this:

```
$ terraform apply

Error: Provider configuration not present

To work with module.m.aws_s3_bucket_object.X its original provider
configuration at
module.m.provider["registry.terraform.io/hashicorp/aws"].us_east_1 is
required, but it has been removed. This occurs when a provider configuration
is removed while objects created by that provider still exist in the state.
Re-add the provider configuration to destroy module.m.aws_s3_bucket_object.X,
after which you can remove the provider configuration again.
```

Ok, but destroying the object is not an option, it's still in use (true in the non-toy case).

Workaround: `terraform state rm module.m.aws_s3_bucket_object.X` and then re-import the object:

```
$ terraform state rm module.m.aws_s3_bucket_object.X
Removed module.m.aws_s3_bucket_object.X
Successfully removed 1 resource instance(s).
$ terraform state rm module.m.data.aws_sns_topic.health   ### Just to be safe
Removed module.m.data.aws_sns_topic.health
Successfully removed 1 resource instance(s).
$ cat terraform.tfstate  ### Check that terraform knows nothing about anything!
{
  "version": 4,
  "terraform_version": "0.13.4",
  "serial": 8,
  "lineage": "0e6ecb36-fdbd-03e6-0829-d9de9a51b207",
  "outputs": {},
  "resources": []
}
$ terraform import module.m.aws_s3_bucket_object.X foo

Error: Provider configuration not present

To work with module.m.aws_s3_bucket_object.X its original provider
configuration at
module.m.provider["registry.terraform.io/hashicorp/aws"].us_east_1 is
required, but it has been removed. This occurs when a provider configuration
is removed while objects created by that provider still exist in the state.
Re-add the provider configuration to destroy module.m.aws_s3_bucket_object.X,
after which you can remove the provider configuration again.


Error: Provider configuration not present

To work with module.m.aws_s3_bucket_object.X (import id
"delete_me/benjamin.shropshire") its original provider configuration at
module.m.provider["registry.terraform.io/hashicorp/aws"].us_east_1 is
required, but it has been removed. This occurs when a provider configuration
is removed while objects created by that provider still exist in the state.
Re-add the provider configuration to destroy module.m.aws_s3_bucket_object.X
(import id "foo"), after which you can remove the
provider configuration again.
```

Um... *WAHT*?!

How doe sit even know that exists!?

From here I've tried, renaming the resource, renaming the provider pointing the provider at a different region, making the resource refer to a different object, `rm -rf .terraform`, `rm -rf ~/.terraform.d` `pkill -9 $NAMES_OF_PROVIDERS` and even rebooting.

I've even (in the real-world application, for the cases where I could) `terraform destroy`ed the resources before removing the provider. When I try to edit the config of those resource (which are not associated with any resource) trigger similar errors.

I don't see any way to move forward from here.

### Expected Behavior

Moving from the discouraged setup of "providers in sub modules" to the encouraged setup of "all providers at the root config" should be viable, preferably without destroying the resources.

### Actual Behavior

Terraform seems to have some hidden state somewhere that is tracking which provider was used to create resource and then refusing to allow any modification to it regardless of anything.

### LINKED ISSUE #27409: "missing provider" when attempting to override default
If a user attempts to override a default provider in a module, `init` will still find and store the default provider, but `plan` and `apply` will indicate that the provider cannot be found. 

### Config

```
# main.tf
terraform {
  required_providers {
    null = {
      source = "terraform.io/local/null"
    }
  }
}

module "mod" {
  source = "./mod"
  providers = {
    null = null
  }
}
```

```
# ./mod/main.tf
resource "null_resource" "a" {
}
```

### Output

```
% tf init
Initializing provider plugins...
- Reusing previous version of terraform.io/local/null from the dependency lock file
- Reusing previous version of hashicorp/null from the dependency lock file
- Installing terraform.io/local/null v1.0.0...
- Installed terraform.io/local/null v1.0.0 (unauthenticated)
- Installing hashicorp/null v3.0.0...
- Installed hashicorp/null v3.0.0 (signed by HashiCorp)

% tf plan
Error: missing provider provider["registry.terraform.io/hashicorp/null"]
```

Adding a "proxy provider block" to the module config does not change the error condition.

### Expected Result

The specific error is not useful because the provider does appear to be found. We can either allow this type of override, or catch the invalid configuration and indicate what needs to be changed.

### LINKED ISSUE #27539: Error with renamed provider alias in nested modules
Terraform is treating proxy providers with only aliases in nested modules as fully instantiated providers and returning an error that it is not supported when using `depends_on` or `count` on the top level module.

This error only seems to occur if the alias name is changed between the top level module and the nested module. If you change the alias name between the root configuration and the top level module it will not error.

For example, the following two **will NOT work** from the example repo [examples/level-2-count](https://github.com/jasonhuling/terraform-nested-provider-alias-bug/tree/main/examples/level-2-count) and [examples/level-2-depends-on](https://github.com/jasonhuling/terraform-nested-provider-alias-bug/tree/main/examples/level-2-depends-on) where the providers are passed like the following:
```
root [aws.us-west-2] -> module.level_2 [aws.us-west-2] -> module.level_1 [aws]
root [aws.other-us-east-1] -> module.level_2 [aws.other-us-east-1] -> module.level_1 [aws.other]
```

But the following **will work** from the example repo [examples/level-2-alt-count](https://github.com/jasonhuling/terraform-nested-provider-alias-bug/tree/main/examples/level-2-alt-count) where the providers are passed like the following:
```
root [aws.us-west-2] -> module.level_2_alt [aws] -> module.level_1 [aws]
root [aws.other-us-east-1] -> module.level_2_alt [aws.other] -> module.level_1 [aws.other]
```

### Terraform Version
```
Terraform v0.14.4
```
Reproducible from `v0.13.0` to `v0.14.4`

### Terraform Configuration Files

GitHub Repository: https://github.com/jasonhuling/terraform-nested-provider-alias-bug

Repository Layout:
* [examples/level-2-count](https://github.com/jasonhuling/terraform-nested-provider-alias-bug/tree/main/examples/level-2-count):  An example using `count` in the module which will cause the error.
* [examples/level-2-depends-on](https://github.com/jasonhuling/terraform-nested-provider-alias-bug/tree/main/examples/level-2-depends-on): An example using `depends_on` in the module which will cause the error.
* [examples/level-2-alt-count](https://github.com/jasonhuling/terraform-nested-provider-alias-bug/tree/main/examples/level-2-alt-count):  An example using `count` in the module with renamed provider aliases which will NOT cause the error.

### Debug Output
https://github.com/jasonhuling/terraform-nested-provider-alias-bug/blob/main/examples/level-2-count/terraform-init-trace.log

### Expected Behavior
Terraform should have initialized without any issues.

### Actual Behavior
The following error occurred:
```
Error: Module does not support count

  on main.tf line 13, in module "level_2":
  13:   count  = 1

Module "level_2" cannot be used with count because it contains a nested
provider configuration for "aws", at ../../modules/level-1/main.tf:4,10-15.

This module can be made compatible with count by changing it to receive all of
its provider configurations from the calling module, by using the "providers"
argument in the calling module block.


Error: Module does not support count

  on main.tf line 13, in module "level_2":
  13:   count  = 1

Module "level_2" cannot be used with count because it contains a nested
provider configuration for "aws.other", at
../../modules/level-1/main.tf:6,10-15.

This module can be made compatible with count by changing it to receive all of
its provider configurations from the calling module, by using the "providers"
argument in the calling module block.
```

### Steps to Reproduce
1. Navigate to [examples/level-2-count](https://github.com/jasonhuling/terraform-nested-provider-alias-bug/tree/main/examples/level-2-count) or [examples/level-2-depends-on](https://github.com/jasonhuling/terraform-nested-provider-alias-bug/tree/main/examples/level-2-depends-on).
2. Run `terraform init`.

### Additional Context
Using with aws-vault like the following: `aws-vault exec default -- terraform init`

### References
This issue seemed like it could possibly be related: https://github.com/hashicorp/terraform/issues/21699

### PR DESCRIPTION
**Pull request by jbardin**
Here we have the initial implementation of `configuration_aliases` for providers within modules. The idea here is to replace the need for empty configuration blocks within modules as a "proxy" to receive provider configuration passed in from a parent module.  So instead of writing 

```
provider "foo" {
  alias = "bar"
}
```

the `foo.bar` name is declared along with the `foo` provider local name within `required_providers`.

```
terraform {
  required_providers {
    foo = {
      source = "hashicorp/foo"
      configuration_aliases = [ foo.bar ]
    }
  }
}
```

Adding the new field to the `required_providers` attributes required rewriting the parser for `required_providers` in order to allow the aliases to be bare references, matching their usage in other locations within configuration. The overall behavior of the parser should be the same, with the only noticeable changes in tests being some more precise diagnostic locations. The `hcl` and `terraform-config-instpect` packages were updated to work with the new config loader. We can update the `hcl` package to a tagged version before releasing 0.15.

All validation was moved out of the `configload` package, since that package should only be concerned with the loading of configuration, not the interpretation thereof. The output is slightly different from the previous validation, as instead of validating whether the modules are allowed to have provider configurations, we validate all the various combinations of provider structures themselves. Configurations which were working correctly previously should generate no more than diagnostic warnings in the new validation scheme. Configurations which were incorrect, or could produce unpredictable behavior now generate errors.

The most notable of these new warnings will be advice to remove empty configuration blocks from the module config. Each diagnostic produces a contextual message, with the intent of directing users to a supported configuration. For example, an empty configuration with an alias would present the warning:

```
│ Warning: Empty provider configuration blocks are not required
│
│   on mod/main.tf line 9:
│    9: provider "foo" {
│
│ Remove the foo.bar provider block from module.mod. Add foo.bar
| to the list of configuration_aliases for foo in required_providers to 
| define the provider configuration name.
```

Additional checks, like verifying the provider type have also been added. This prevents hard to decipher evaluation time errors like "unknown provider provider["example.com/vendor/name"].foo" when a correct provider config has not been supplied in a child module. Instead the user will receive a message during init like:

```
│ Error: Invalid type for provider module.mod.provider["registry.terraform.io/hashicorp/foo"].bar
│
│   on main.tf line 7, in module "mod":
│    7:     foo.bar = aws
│
│ Cannot use configuration from provider["registry.terraform.io/hashicorp/aws"] for
| module.mod.provider["registry.terraform.io/hashicorp/foo"].bar. The given
| provider configuration is for a different provider type.
```

Closes #27539
Closes #27409
Closes #26617
Closes #26448
Closes #26354

### CODE REVIEW

**Comment by jbardin** [comment]
I forgot that hcl diagnostics don't wrap. I'll reformat those to a more reasonable terminal width.

File: configs/provider_validation.go [hunk 1]
```diff
@@ -0,0 +1,246 @@
...
+// module call, or a parent module call, has used a feature that precludes
+// providers from being configured at all within the module.
+func validateProviderConfigs(call *ModuleCall, cfg *Config, noProviderConfig bool) (diags hcl.Diagnostics) {
+	for name, child := range cfg.Children {
+		mc := cfg.Module.ModuleCalls[name]
+
+		// if the module call has any of count, for_each or depends_on,
+		// providers are prohibited from being configured in this module, or
+		// any module beneath this module.
+		nope := noProviderConfig || mc.Count != nil || mc.ForEach != nil || mc.DependsOn != nil
```
Comment (mildwonkey) [inline configs/provider_validation.go:33]: lulz `nope`

File: configs/provider_validation.go [hunk 2]
```diff
@@ -0,0 +1,246 @@
...
+// provider blocks" are still allowed within modules, though they will
+// generate warnings when the configuration is loaded. The new validation
+// however will generate an error if a suitable provider configuration is not
+// passed in through the module call.
+//
+// The call argument is the ModuleCall for the provided Config cfg. The
+// noProviderConfig argument is passed down the call stack, indicating that the
+// module call, or a parent module call, has used a feature that precludes
+// providers from being configured at all within the module.
+func validateProviderConfigs(call *ModuleCall, cfg *Config, noProviderConfig bool) (diags hcl.Diagnostics) {
```
Comment (mildwonkey) [inline configs/provider_validation.go:26]: Excellent comments and warning/error messages in this entire function, thank you!

File: configs/provider_validation.go [hunk 3]
```diff
@@ -0,0 +1,246 @@
...
+				configAliases[providerName(alias.LocalName, alias.Alias)] = addr
+			}
+		}
+	}
+
+	// there cannot be any configurations if no provider config is allowed
+	if len(configured) > 0 && noProviderConfig {
+		diags = append(diags, &hcl.Diagnostic{
+			Severity: hcl.DiagError,
+			Summary:  fmt.Sprintf("Module %s contains provider configuration.", cfg.Path),
```
Comment (mildwonkey) [inline configs/provider_validation.go:102]:
```suggestion
			Summary:  fmt.Sprintf("Module %s contains provider configuration", cfg.Path),
```

I think we usually leave off that trailing `.` in summaries: 


```
Module module.child.module.child2 contains provider configuration.; Providers cannot be configured within modules using count, for_each or depends_on
```

File: configs/config_build_test.go [hunk 4]
```diff
@@ -154,3 +155,119 @@ func TestBuildConfigChildModuleBackend(t *testing.T) {
...
+					// addresses as relative to the root module
+					sourcePath := filepath.Join(path, req.SourceAddr)
+					mod, diags := parser.LoadConfigDir(sourcePath)
+					version, _ := version.NewVersion("1.0.0")
+					return mod, version, diags
+				},
+			))
+
+			// we can make this less repetitive later if we want
+			for _, msg := range expectedErrs {
```
Comment (mildwonkey) [inline configs/config_build_test.go:209]: This isn't worth blocking the PR on, but I am concerned for future-us.  It isn't testing for an exact match, and I noticed some inconsistency in the expected errors in the test files (mostly trailing punctuation, but I think I saw one where the message was cut short)
This is more something to remember for the future, I guess 🤷

File: configs/provider_requirements.go [hunk 5]
```diff
@@ -26,132 +29,214 @@ type RequiredProviders struct {
 
 func decodeRequiredProvidersBlock(block *hcl.Block) (*RequiredProviders, hcl.Diagnostics) {
 	attrs, diags := block.Body.JustAttributes()
+	if diags.HasErrors() {
```
Comment (mildwonkey) [inline configs/provider_requirements.go:32]: i bet whoever forgot to check that is feeling _pretty silly_ right about now 🤦

File: configs/provider_requirements.go [hunk 6]
```diff
@@ -26,132 +29,214 @@ type RequiredProviders struct {
...
-				diags = append(diags, &hcl.Diagnostic{
-					Severity: hcl.DiagError,
-					Summary:  "Invalid provider name",
-					Detail:   err.Error(),
-					Subject:  attr.Expr.Range().Ptr(),
-				})
-			} else {
-				rp.Type = addrs.ImpliedProviderForUnqualifiedType(pType)
+		// finally add the required provider as long as there were no errors
+		if !diags.HasErrors() {
```
Comment (mildwonkey) [inline configs/provider_requirements.go:222]: I have no objection, but I'm curious why you split this if statement into two?

File: configs/provider_validation.go [hunk 7]
```diff
@@ -0,0 +1,246 @@
...
+			Detail:   detail,
+			Subject:  src,
+		})
+	}
+
+	if diags.HasErrors() {
+		return diags
+	}
+
+	// If we have gotten this far without errors, verify that any passed in
```
Comment (mildwonkey) [inline configs/provider_validation.go:235]: Either you're missing a verification step or forgot to remove a dangling comment :)

File: terraform/transform_provider_test.go [hunk 8]
```diff
@@ -434,69 +434,6 @@ func TestProviderConfigTransformer_grandparentProviders(t *testing.T) {
 	}
 }
 
-// pass a specific provider into a module using it implicitly
-func TestProviderConfigTransformer_implicitModule(t *testing.T) {
```
Comment (mildwonkey) [inline terraform/transform_provider_test.go:438]: I presume these have been removed because it's caught during the earlier configload validate now?

File: terraform/transform_provider.go [hunk 9]
```diff
@@ -605,6 +605,43 @@ func (t *ProviderConfigTransformer) transformSingle(g *Graph, c *configs.Config)
 		t.proxiable[key] = !diags.HasErrors()
 	}
 
+	if mod.ProviderRequirements != nil {
```
Comment (mildwonkey) [inline terraform/transform_provider.go:608]: Is this covered in a test, and if not, can it be? (I know the answer to that isn't always straightforward).

**Review by mildwonkey — APPROVED** [review]
This all looks good, and I'm so glad to see the improved validation and errors/warnings! 

I left a couple of comments; most of them aren't blocking so I'll approve this now and you can decide what to do (or not) about the notes I left.

File: configs/provider_validation.go (hunk 3 above)
Comment (jbardin) [reply configs/provider_validation.go:102]: Thanks, I forgot how hcl diagnostics are slightly different anyway, and I'll follow up with better formatting in these.

File: configs/config_build_test.go (hunk 4 above)
Comment (jbardin) [reply configs/config_build_test.go:209]: Yeah, they just need to match a substring, but rather than just looking for a particular error, I also wanted to match the source locations too. I thought I added a comment in the test fixture, but I'll put one in now. It would be more ergonomic to make this work like the individual file tests with comments doing the annotation, but it's much more work to parse the whole config tree.

File: configs/provider_requirements.go (hunk 6 above)
Comment (jbardin) [reply configs/provider_requirements.go:222]: Oh! It used to have more there, but you're right, the logic can now be collapsed.

File: terraform/transform_provider.go (hunk 9 above)
Comment (jbardin) [reply terraform/transform_provider.go:608]: Yes, there's a context test added which covers this, and I'll be adding more as I re-validate the overall behavior within the terraform package itself. This PR was getting big, and I wanted to get the parser and validation in ASAP.

File: configs/provider_requirements.go (hunk 6 above)
Comment (jbardin) [reply configs/provider_requirements.go:222]: Looking at the expanded file I see why, there is an assignment outside of the inner `if` block. Since I'm updating the file anyway, I'll move the first condition out completely.

File: terraform/transform_provider_test.go (hunk 8 above)
Comment (jbardin) [reply terraform/transform_provider_test.go:438]: Yes, these fail while loading the config, so there's no transformation to test.

File: configs/testdata/valid-modules/provider-aliases/main.tf [hunk 10]
```diff
@@ -0,0 +1,19 @@
+terraform {
+  required_providers {
+    foo-test = {
+      source = "foo/test"
+      // TODO: these are strings until the parsing code is refactored to allow
+      // raw references
+      configuration_aliases = [foo-test.a, foo-test.b]
```
Comment (alisdair) [inline configs/testdata/valid-modules/provider-aliases/main.tf:7]: TO-DONE?

File: configs/provider_validation.go [hunk 11]
```diff
@@ -0,0 +1,243 @@
...
+	for name, src := range emptyConfigs {
+		detail := fmt.Sprintf("Remove the %s provider block from %s.", name, cfg.Path)
+
+		isAlias := strings.Contains(name, ".")
+		_, isConfigAlias := configAliases[name]
+		_, isLocalName := localNames[name]
+
+		if isAlias && !isConfigAlias {
+			localName := strings.Split(name, ".")[0]
+			detail = fmt.Sprintf("Remove the %s provider block from %s. Add %s to the list of configuration_aliases for %s in required_providers to define the provider configuration name.", name, cfg.Path, name, localName)
```
Comment (alisdair) [inline configs/provider_validation.go:214]: I worry a bit that users might not find this easy to understand, given that we're introducing `configuration_aliases` in the same release we're adding these warnings.

Assuming that we're not going to provide an auto-upgrade command, could it make sense to make this warning even _more_ explicit about what to do? Maybe with sample configuration?

**Review by alisdair — APPROVED** [review]
This seems great to me!

File: configs/provider_validation.go (hunk 11 above)
Comment (jbardin) [reply configs/provider_validation.go:214]: Yes, I was thinking the same thing! I'm going to see how this gets formatted with config in the `detail` section. My hesitation was that I can't always generate the complete `required_providers` attribute, and it could cause more confusion than if they just look up the docs 🤔

Comment (jbardin) [reply configs/provider_validation.go:214]: ok, adding config examples is turning into a much larger task. I'll fix the dandling comment, and get this merged. Other improvements can come later.

**Comment by pselle** [comment]
A post-merge 🐘 nudge for user-facing documentation for this featrure!

**Comment by jbardin** [comment]
@pselle, sorry, I should have mentioned it in the PR body, docs will be coming next in a separate PR!
