### PR TITLE
terraform: remove state from `validate` graph walk

### LINKED ISSUE #26035: terraform not properly storing provider args from command line when there is no provider block
### Terraform Version
0.13.2-dev (build from master)

### Terraform Configuration Files

```terraform
resource "aws_bucket" "yo" {
  name = "yo"
}
```

### Expected Behavior
```
  The region where AWS operations will take place. Examples
resource "aws_bucket" {
  are us-east-1, us-west-2, etc.

  Enter a value: us-east-1

Refreshing Terraform state in-memory prior to plan...
```

### Actual Behavior
```
provider.aws.region
  The region where AWS operations will take place. Examples
  are us-east-1, us-west-2, etc.

  Enter a value: us-east-1


Error: Missing required argument

The argument "region" is required, but was not set.
```

### Steps to Reproduce
plan

### References
Could possibly relate to https://github.com/hashicorp/terraform/issues/26027

### PR DESCRIPTION
**Pull request by mildwonkey**
This pull reverts a recent change to `backend/local` which created two context, one with and one without state. Instead I have removed the state entirely from the validate graph (by explicitly passing a `states.NewState()`).

This changed caused a test failure, which (ty so much for the help) @jbardin discovered was inaccurate all along: the test's call to  `Validate()` was actually what was removing the output from state, which should not have been happening during `Validate` anyway. The new expected test output matches terraform's actual behavior on the command line: if you use -target to destroy a resource, an output that references only that resource is _not_ removed from state. 

This includes two tests to cover the expected behavior:
- `TestPlan_varsUnset` has been updated so it will panic if it gets more than one request to input a variable
- `TestPlan_providerArgumentUnset` covers #26035

Fixes #26035, #26027

### CODE REVIEW

File: command/plan_test.go [hunk 1]
```diff
@@ -560,15 +560,15 @@ func TestPlan_varsUnset(t *testing.T) {
...
-
 	// The plan command will prompt for interactive input of var.foo.
 	// We'll answer "bar" to that prompt, which should then allow this
 	// configuration to apply even though var.foo doesn't have a
 	// default value and there are no -var arguments on our command line.
-	defaultInputReader = bytes.NewBufferString("bar\n")
+
+	// This will (helpfully) panic if more than one variable is requested during plan:
+	// https://github.com/hashicorp/terraform/issues/26027
+	close := testInteractiveInput(t, []string{"bar"})
```
Comment (alisdair) [inline command/plan_test.go:570]: Thanks for the comment!

File: terraform/context_apply_test.go [hunk 2]
```diff
@@ -7461,10 +7461,9 @@ func TestContext2Apply_targetedDestroy(t *testing.T) {
 		t.Fatalf("expected 0 resources, got: %#v", mod.Resources)
 	}
 
-	// the root output should have been removed too, since it is derived solely
-	// from the targeted resource
-	if len(mod.OutputValues) != 0 {
-		t.Fatalf("expected 0 outputs, got: %#v", mod.OutputValues)
+	// the root output should not get removed
```
Comment (jbardin) [inline terraform/context_apply_test.go:7464]: Maybe change this comment to indicate that we're verifying the current status-quo, but it's not necessarily incorrect to remove the output if we can manage it in the future.
