### PR TITLE
Continue test execution after an expected failure

### LINKED ISSUE #34969: Terraform test - Subsequent tests should not be skipped when test using expected_failures fails.
### Terraform Version

```shell
Terraform v1.7.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.98.0
```

### Terraform Configuration Files

main.tf:

```terraform
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  name = "my-test-rg"
  location = "uksouth"
}
```

tests/skip-tests-1.tftest.hcl

```terraform
provider "azurerm" {
  features {}
}

run "test_one" {
  command = apply

  expect_failures = [
    azurerm_resource_group.rg
  ]
}

run "test_two" {
  command = apply
}
```

### Debug Output

N/A

### Expected Behavior

Both `test_one` and `test_two` should execute.

Skipping subsequent tests increases cycle time as it forces multiple test runs to understand all failure cases. 

There are cases where multiple related tests may fail for different reasons, and also cases where if `test_one` fails, it is expected that `test_two` would also fail, so some sort of toggle to vary the behaviour based on the context would be ideal.

### Actual Behavior

`test-one` runs and fails, then `test-two` is skipped. I suspect this is deliberate for reasons unknown to me (and not documented), but this behaviour is inconsistent with test failures occurring due to failed `assert` blocks.

```
> terraform test
tests/skip-tests-1.tftest.hcl... in progress
  run "test_one"... fail
╷
│ Error: Missing expected failure
│
│   on tests/skip-tests-1.tftest.hcl line 9, in run "test_one":
│    9:     azurerm_resource_group.rg
│
│ The checkable object, azurerm_resource_group.rg, was expected to report an error but did not.
╵
  run "test_two"... skip
tests/skip-tests-1.tftest.hcl... tearing down
tests/skip-tests-1.tftest.hcl... fail

Failure! 0 passed, 1 failed, 1 skipped.
```

You can work around this by splitting the tests into different files, but this isn't practical with a large number of tests.

### Steps to Reproduce

1. `terraform init`
2. `terraform test`

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by dsa0x**
Fixes #34969

This PR ensures that the test suite continues to execute when a run fails due to an expected failure.

## Target Release

1.11.x

## CHANGELOG entry

- [x] This change is user-facing and I added a changelog entry.
- [ ] This change is not user-facing.

### CODE REVIEW

File: internal/backend/local/test.go [hunk 1]
```diff
@@ -628,7 +610,46 @@ func (runner *TestFileRunner) run(run *moduletest.Run, file *moduletest.File, st
...
+			run.Status = moduletest.Fail
+		default:
+			// Append other diagnostics.
+			nonFailureDiags = nonFailureDiags.Append(diag)
+		}
+	}
+	// If there are other errors, update the run status to error.
+	if nonFailureDiags.HasErrors() {
+		run.Status = moduletest.Error
+	}
```
Comment (liamcervante) [inline internal/backend/local/test.go:648]: Don't need the nonFailureDiags if you just set the error above.

File: internal/backend/local/test.go [hunk 2]
```diff
@@ -628,7 +610,46 @@ func (runner *TestFileRunner) run(run *moduletest.Run, file *moduletest.File, st
...
+	var nonFailureDiags tfdiags.Diagnostics
+	for _, diag := range unexpectedDiags {
+		switch {
+		// If any diagnostic indicates a missing expected failure, update the run status to fail.
+		case diag.Description().Summary == moduletest.MissingFailureSummary:
+			diag.ExtraInfo()
+			run.Status = moduletest.Fail
+		default:
+			// Append other diagnostics.
+			nonFailureDiags = nonFailureDiags.Append(diag)
```
Comment (liamcervante) [inline internal/backend/local/test.go:642]:
```suggestion
			if diag.Severity() == tfdiags.Error {
			    run.Status = moduletest.Error
			    break
			}
```

File: internal/backend/local/test.go [hunk 3]
```diff
@@ -628,7 +610,46 @@ func (runner *TestFileRunner) run(run *moduletest.Run, file *moduletest.File, st
...
+		run.Status = moduletest.Error
+	}
+
+	// Retrieve diagnostics that are either unrelated to expected failures or report missing expected failures.
+	unexpectedDiags := run.ValidateExpectedFailures(diags)
+	var nonFailureDiags tfdiags.Diagnostics
+	for _, diag := range unexpectedDiags {
+		switch {
+		// If any diagnostic indicates a missing expected failure, update the run status to fail.
+		case diag.Description().Summary == moduletest.MissingFailureSummary:
```
Comment (liamcervante) [inline internal/backend/local/test.go:637]: I think the implementation here is fine, but we should use the `Extra` functionality of the diagnostic package instead of matching against the summary text. This just means we're being much more precise.

You could make an interface in the `run` package:

```

type DiagnosticExtraFromMissingExpectedFailure interface {
  DiagnosticFromMissingExpectedFailure() bool
}

func DiagnosticFromMissingExpectedFailure(diag tfdiags.Diagnostic) bool {
	maybe := tfdiags.ExtraInfo[DiagnosticExtraFromMissingExpectedFailure](diag)
	if maybe == nil {
		return false
	}
	return maybe.DiagnosticFromMissingExpectedFailure()
}

```

Then set the extra of the diagnostic to be an implementation of the interface. Then here you can call `moduletest.DiagnosticFromMissingExpectedFailure(diag)`.

File: internal/backend/local/test.go [hunk 4]
```diff
@@ -628,7 +610,46 @@ func (runner *TestFileRunner) run(run *moduletest.Run, file *moduletest.File, st
...
+			diag.ExtraInfo()
+			run.Status = moduletest.Fail
```
Comment (liamcervante) [inline internal/backend/local/test.go:639]:
```suggestion
			run.Status = run.Status.Merge(moduletest.Fail)
```

This just makes sure that if it has already errored earlier for some reason we don't overwrite that with a Fail at this point. Generally, you should do this everywhere but when setting Error it doesn't matter so much as that has the highest priority.

File: internal/backend/local/test.go (hunk 3 above)
Comment (dsa0x) [reply internal/backend/local/test.go]: Addressed in [d0108ed](https://github.com/hashicorp/terraform/pull/36447/commits/d0108eda1d7de1c6f8b6f22a92733f94755e1013)

**Review by liamcervante — APPROVED** [review]
