### PR TITLE
provider/template: don't error when rendering fails in Exists

### LINKED ISSUE #2344: Can't change template_file vars with remote state
I can't change the set of vars declared in a template_file resources when I'm using remote state.

How to repeat:

* Create a template_file resource that declares a variable called `first_name` in its `vars`.
* Interpolate the `first_name` variable into the template file.
* Configure remote state, e.g. `terraform remote config -backend-config="name=hetznerza/terraform-bug"`
* Apply the resource: `terraform apply`.
* Now change the name of the variable to `second_name` in the resource definition and in the template file.
* Run `terraform plan`.
* You will receive the following error:

```
Error refreshing state: 1 error(s) occurred:

* 1 error(s) occurred:

* failed to render example.yml: 8:28: unknown variable accessed: second_name
```

I have created [a repository](https://github.com/sheldonh/terraform-bug) that shows an example in this error state.

It seems to me that the complexity of template_file resources in tfstate doesn't pay for itself. We'd be better of storing only a hash of the rendered template_file, as we do for things like aws_instance.user_data.

### PR DESCRIPTION
**Pull request by phinze**
The Exists function can run in a context where the contents of the
template have changed, but it uses the old set of variables from the
state. This means that when the set of variables changes, rendering will
fail in Exists. This was returning an error, but really it just needs to
be treated as a scenario where the template needs re-rendering.

fixes #2344 and possibly a few other template issues floating around

### CODE REVIEW

File: builtin/providers/template/resource.go [hunk 1]
```diff
@@ -87,6 +94,8 @@ func Read(d *schema.ResourceData, meta interface{}) error {
 	return nil
 }
 
+type TemplateRenderError error
```
Comment (mitchellh) [inline builtin/providers/template/resource.go]: Don't think this needs to be exported, since we only return it from a private function?

**Comment by mitchellh** [comment]
Nitpick, but LGTM

File: builtin/providers/template/resource.go (hunk 1 above)
Comment (phinze) [inline builtin/providers/template/resource.go]: Good call. I was just so excited that this was my first time using error types in Go that I wanted the _whole world_ to see my error type! :grin:
