### PR TITLE
backend/remote: fix panic when loading a 0.12 cached backend

### LINKED ISSUE #21190: terraform 0.11.13 crash on init when remote backend was previously configured with 0.12
terraform 0.11.13 crashes when you run `terraform init` in a directory that was previously configured with a remote backend & terraform 0.12.

1: config w/ remote backend, init/apply/destroy
2: switch back to terraform 0.11.13 and run `terrafrom init`. [crash.log](https://gist.github.com/mildwonkey/b06aebc461e55bc91d29fe2d4fa350a5)

Expected output: a friendly error message that terraform needs to be upgraded.

### PR DESCRIPTION
**Pull request by mildwonkey**
The remote backend schema changed in terraform 0.12, causing a panic
when 0.11 tries to load it. While we do not support downgrading
configurations, we should prevent panics where possible.

We may consider some form of backend schema versioning in the future.

Fixes #21190

NOTE: The error message is not terribly accurate or informative:

```
Error loading previously configured backend:
Error configuring the backend "remote": the cached backend configuration is not valid for this version of terraform

Please update the configuration in your Terraform files to fix this error.
If you'd like to update the configuration interactively without storing
the values in your configuration, run "terraform init".
```

I could add a specific return error type and add a new message that specifically states that an upgrade is required, though I have doubts about the long-term accuracy of such a message. This is also (I believe) a fairly minor edge case, which is why I did not do so yet.

### CODE REVIEW

File: backend/remote/backend_test.go [hunk 1]
```diff
@@ -126,6 +126,42 @@ func TestRemote_config(t *testing.T) {
 	}
 }
 
+// TestRemote_cached_config is similar to the test above, but we mimic loading a
+// cached backend config by skipping the validate call
+func TestRemote_config_cached(t *testing.T) {
```
Comment (svanharmelen) [inline backend/remote/backend_test.go]: I think the convention for naming tests is using only 1 underscore in a name. So that would mean this test should be called something like: `TestRemote_cachedConfig`

File: backend/remote/backend.go [hunk 2]
```diff
@@ -149,8 +149,16 @@ func (b *Remote) configure(ctx context.Context) error {
 	b.hostname = d.Get("hostname").(string)
 	b.organization = d.Get("organization").(string)
 
+	// The backend schema for the workspaces attribute changed in terraform
+	// 0.12, and causes a panic when encountered by 0.11. While we don't support
+	// downgrading, we do want to protect users from that panic.
+	wsConfig := d.Get("workspaces").(*schema.Set).List()
+	if len(wsConfig) == 0 {
+		return fmt.Errorf("the cached backend configuration is not valid for this version of terraform")
```
Comment (svanharmelen) [inline backend/remote/backend.go]: Agree that it's not too informative, but it gets the job done. Maybe making it a specific error is not a bad idea as this doesn't tell the user how to fix it (which is purging the cached config)?

I'm not sure how many people will switch to `0.12` and then back to `0.11`, so no idea if its worth it.

File: command/meta_backend.go [hunk 3]
```diff
@@ -390,16 +390,14 @@ func (m *Meta) backendFromConfig(opts *BackendOpts) (backend.Backend, error) {
 	case c != nil && s.Remote.Empty() && !s.Backend.Empty():
 		// If our configuration is the same, then we're just initializing
 		// a previously configured remote backend.
-		if !s.Backend.Empty() {
```
Comment (jbardin) [inline command/meta_backend.go]: Why are we changing the logic here?
I can't recall exactly why I put that in, and the test for it still passes, but the logic around the backend state is quite finicky and I'd rather not change any of it at if at all possible.

Comment (jbardin) [reply command/meta_backend.go]: oh never-mind, I didn't put that in, and I see how it's redundant wit the check above ;)

File: backend/remote/backend.go (hunk 2 above)
Comment (mildwonkey) [reply backend/remote/backend.go]: I imagine this would only happen if someone was in the middle of testing or upgrading to 0.12 and accidentally switched back to the older binary - that's how I stumbled across it. 

I didn't even consider purging the cached config as an option; I guess if there's no remote state it's fine, but if there's any remote state terraform will fail anyway:
`Error refreshing state: Terraform 0.11.13 does not support state version 4, please update.`

File: command/meta_backend.go (hunk 3 above)
Comment (mildwonkey) [reply command/meta_backend.go]: Ha sorry, I realized after I pushed that should've been in its own commit with a comment!

**Comment by mildwonkey** [comment]
(code tests pass, failure is in website-test)
