### PR TITLE
command/state list: list resources in nested and expanded modules

### LINKED ISSUE #26191: `terraform state list` with module path doesn't recognize nested modules
### Terraform Version

```
0.13.1
```

### Terraform Configuration Files

With a module structure like:

- products
- - distributions 

### Expected Behavior

`terraform state list` should show resources in nested sub-modules when using the filter method.

### Actual Behavior

```
$ terraform state list
[...]
module.products-foo.module.distributions["some-distribution"].data.aws_iam_policy_document.delegated_assume_role_policy["some-distribution-1"]
module.products-foo.module.distributions["some-distribution"].data.aws_iam_policy_document.delegated_assume_role_policy["some-distribution-2"]
module.products-foo.module.distributions["some-distribution"].aws_iam_role.delegated_role["some-distribution-2"]
[...]
```

```
$ terraform state list module.products-foo
module.products-foo.data.aws_acm_certificate.product_cloudfront_distribution_certificate[0]
module.products-foo.data.aws_acm_certificate.scd_cloudfront_distribution_certificate[0]
module.products-foo.data.aws_iam_policy_document.product_s3_bucket_policy
module.products-foo.data.aws_iam_policy_document.replication_iam_policy
module.products-foo.data.aws_route53_zone.service-dns-zone[0]
module.products-foo.aws_cloudfront_distribution.product_cloudfront_distribution[0]
module.products-foo.aws_cloudfront_distribution.scd_cloudfront_distribution[0]
module.products-foo.aws_cloudfront_origin_access_identity.product_access_identity
module.products-foo.aws_iam_policy.replication
module.products-foo.aws_iam_policy_attachment.replication
module.products-foo.aws_iam_role.replication
module.products-foo.aws_route53_record.scd-dns[0]
module.products-foo.aws_s3_bucket.product_bucket
module.products-foo.aws_s3_bucket_object.health_check_object
```

No resources from `module.products-foo.module-distributions` show up.

```
$ terraform state list module.products-foo.module.distributions

Error: Unknown module

The current state contains no module at
module.products-foo.module.distributions. If you've just added
this module to the configuration, you must run "terraform apply" first to
create the module's entry in the state.
```

Terraform believes the module does not exist.

### Steps to Reproduce

1. Create a module hierachy with nested modules.
2. Run terraform apply.
3. `terraform state list` filtering to the submodules.

### Additional Context

Using S3 backend, no additional wrappers or command line flags.

```
Terraform v0.13.1
+ provider registry.terraform.io/hashicorp/aws v3.4.0
+ provider registry.terraform.io/hashicorp/random v2.3.0
+ provider registry.terraform.io/terraform-providers/ns1 v1.8.6
```

### PR DESCRIPTION
**Pull request by mildwonkey**
A few distinct bugs fixed in here:

There was a bug in the logic checking if a given module was the child of
the targetAddr, now fixed. That resolved the basic issue where resources
in nested submodules were not listed.

The logic around `allowMissing` needed some tweaking to allow for empty
modules, as long as those modules had submodules with resources. `state
list` is the only command using `allowMissing` with `false`, so this felt safe
to do.

Finally I extended the logic so `state list` would included expanded modules,
when given a module instance, so for e.g. `list module.foo` would result in resources from
`module.foo[1]`, `module.foo[0]`, etc.

Fixes #26191

### CODE REVIEW

File: command/state_meta.go [hunk 1]
```diff
@@ -103,24 +103,28 @@ func (c *StateMeta) lookupResourceInstanceAddr(state *states.State, allowMissing
...
-		ret = append(ret, c.collectModuleResourceInstances(ms)...)
 		for _, cms := range state.Modules {
-			candidateAddr := ms.Addr
-			if len(candidateAddr) > len(addr) && candidateAddr[:len(addr)].Equal(addr) {
-				ret = append(ret, c.collectModuleResourceInstances(cms)...)
+			if !addr.Equal(cms.Addr) {
+				if addr.IsAncestor(cms.Addr) || addr.TargetContains(cms.Addr) {
+					found = true
+					ret = append(ret, c.collectModuleResourceInstances(cms)...)
+				}
```
Comment (alisdair) [inline command/state_meta.go:117]: I like this a lot more than the slice based approach!

File: command/state_meta.go [hunk 2]
```diff
@@ -103,24 +103,28 @@ func (c *StateMeta) lookupResourceInstanceAddr(state *states.State, allowMissing
 	case addrs.ModuleInstance:
 		// Matches all instances within the indicated module and all of its
 		// descendent modules.
+		found := false
```
Comment (alisdair) [inline command/state_meta.go:106]: I think the logic around `found` is subtle enough that it might warrant a comment explaining that this is here to cope with the case of the empty intermediate module.

**Review by alisdair — APPROVED** [review]
Looks good to me! 👍 

While not essential, I think we might want to update the `state list` docs, specifically [this section about filtering by module](https://www.terraform.io/docs/commands/state/list.html#example-filtering-by-module). It'd be nice to be clear about the fact that Terraform lists all descendent resources, not just in the given module.

**Comment by mildwonkey** [comment]
Ah, thanks for pointing that out @alisdair . The behavior is covered by the [resource addressing](https://www.terraform.io/docs/internals/resource-addressing.html) docs and I hadn't noticed the difference between the two. Unfortunately (but I'm grateful to know!) that also reinforces this PR as an awkward combination bugfix/ breaking change, so I'm also going to remove the backport label which I just added.
