### PR TITLE
configs/configupgrade: detect possible relative module sources

### LINKED ISSUE #19745: v0.12.0-alpha4 requires a slash in the path of the module source
### Terraform Version
```
Terraform v0.12.0-alpha4 (2c36829d3265661d8edbd5014de8090ea7e2a076)
```

### Terraform Configuration Files
```hcl
# main.tf
module "test" {
  source = "test"
}
```
```hcl
# test/test.tf
provider "random" {}
```

### Expected Behavior
Terraform v0.11.11 initialize without error. 

### Actual Behavior
Terraform v0.12.0-alpha4 initialize with error:
```
$ terraform init
Initializing modules...
Downloading test for test...

Error: Failed to download module

  on main.tf line 2, in module "test":
   2:   source = "test"

Error attempting to download module source code from "test": error downloading
'file:///.terraform/modules/test/test': source path error: stat
/.terraform/modules/test/test: no such file or directory


Error: Failed to download module

  on main.tf line 2, in module "test":
   2:   source = "test"

Error attempting to download module source code from "test": error downloading
'file:///.terraform/modules/test/test': source path error: stat
/.terraform/modules/test/test: no such file or directory
```

When I change the path in `main.tf ` to `source = "./test"`, Terraform v0.12.0-alpha4 initializes without error:
```
$ terraform init
Initializing modules...
- test in test

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.random: version = "~> 2.0"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

The same error occurs if the module uses the parent directory as the source path with `source = ".."`.

### PR DESCRIPTION
**Pull request by mildwonkey**
If a module source appears to be a relative local path but does not have
a preceding ./, print a #TODO message for the user.

Together, this and PR #20639 fixes #19745 and #20573

### CODE REVIEW

File: configs/configupgrade/upgrade_body.go [hunk 1]
```diff
@@ -873,3 +924,41 @@ var resourceTypeAutomaticConnectionExprs = map[string]map[string]string{
...
+		}
+	}
+
+	_, err := regsrc.ParseModuleSource(addr)
+	if err == nil {
+		// it is a registry source
+		return false
+	}
+
+	realAddr, err := getter.Detect(addr, ".", getter.Detectors)
```
Comment (apparentlymart) [inline configs/configupgrade/upgrade_body.go]: I think some of the `getter.Detectors` can potentially do non-trivial stuff like API requests when trying to match (e.g. to figure out if a BitBucket repository uses Git or Mercurial) so it may be best here to make our own `[]Detectors` containing just the `FileDetector` to make sure we don't inadvertently do expensive/tricky things during the upgrade.

(I didn't catch this in the other PR where you'd written a similar function, but the same might apply there too.)

File: configs/configupgrade/upgrade_body.go [hunk 2]
```diff
@@ -873,3 +924,41 @@ var resourceTypeAutomaticConnectionExprs = map[string]map[string]string{
...
+	// it's unclear what the problem may be, so we'll
+	// just pass it through normally
+	if err != nil {
+		return false
+	} else {
+		if strings.HasPrefix(realAddr, "file://") {
+			_, err := os.Stat(realAddr[7:])
```
Comment (apparentlymart) [inline configs/configupgrade/upgrade_body.go]: I'm not sure if this'll do quite the right thing on Windows... Windows `file:` URLs can be kinda funny in situations where e.g. it's a UNC path, or where the drive letter is encoded, and so we might end up with extra slashes on the front of the path here.

Perhaps it doesn't matter when we're expecting the path to be relative anyway, but might be worth us testing this on Windows to make sure it doesn't do anything unfortunate.

Comment (mildwonkey) [reply configs/configupgrade/upgrade_body.go]: Oh good point, I just based this off the fact that "file://" is precisely what go-getter adds to the path (https://github.com/hashicorp/go-getter/blob/master/detect_file.go#L59). I will follow up on this one.

File: configs/configupgrade/upgrade_body.go (hunk 1 above)
Comment (mildwonkey) [reply configs/configupgrade/upgrade_body.go]: That's a fair point, and something I was concerned about in the previous PR as well. 

On it's own, `go-getter` FileDetector happily returns "github.com/foo/bar" as "file:///terraform/.terraform/modules/acctest_root/github.com/foo/bar", and I was trying to avoid re-writing go-getter's logic to identify s3 or vcs sources. 

This did remind me that I saw a subset of detectors defined, and I should use those instead of ~everything: 

```
var goGetterDetectors = []getter.Detector{
	new(getter.GitHubDetector),
	new(getter.BitBucketDetector),
	new(getter.S3Detector),
	new(getter.FileDetector),
}
```

Based on this list and my *cursory* look at the getters, only the BitBucketDetector makes an API call, and that's only if the source starts with "bitbucket.org". 

Would using the limited list of detectors be sufficient (with the caveat about bitbucket), or would you prefer I try to capture the most obvious s3/git/bitbucket sources and just update the TODO comment to let the user know that they can ignore the message if it isn't a local source?  

I will push an update to my previous PR, since it's all regarding the same issue, here, so you can look.

Comment (apparentlymart) [reply configs/configupgrade/upgrade_body.go]: Taking a step back here, I wonder if we could get away with just calling `os.Stat` on the string to see what happens? If it succeeds then that suggests it's likely trying to be a filesystem reference. If it fails then it might be a filesystem reference to something that doesn't exist at all, but it's much more likely to be a remote source if this configuration ever worked on Terraform 0.11.

`os.Stat` might not be cheap itself in the unlikely event that it's a reference to a slow network filesystem, but that seems relatively unlikely and we _were_ going to run `os.Stat` eventually anyway, so it shouldn't be much worse, right? (I think this would also mitigate my other concern about Windows, since we wouldn't need to deal with `file:` URLs at all.)

`go-getter` is a very big surface that is subject to change over time, so I'd feel better about doing something simple here that doesn't involve that dependency, if we can make it work reliably enough.

Comment (mildwonkey) [reply configs/configupgrade/upgrade_body.go]: I don't quite follow how that would help answer the question here: "is this maybe an unclear relative path". 
 
`os.Stat` won't find anything if it is given an improper relative path ("module" vs. "./module"), so (from what I think you're saying) we'd assume it's a remote source and move forward.

If the goal is not to use `go-getter` at all (which is a legitimate goal), we would have to run `os.Stat` twice, once treating the module source as an absolute path and (if that fails to find anything) a second time as a relative path. It could still check for the most obvious network module sources, but again at that point we're re-implementing much of go-getters logic just to avoid a potential api call to bitbucket (at least in the current go-getter version).

Comment (apparentlymart) [reply configs/configupgrade/upgrade_body.go]: Sorry, I didn't explain my thought completely here: I was imagining that we first concatenate the given string with the module directory using `filepath.Join` to produce an _effective_ absolute path:

* `module` would become e.g. `foo/bar/baz/module`
* `github.com/example/foo.git` would become e.g. `foo/bar/baz/github.com/example/foo.git`
* `https://example.com/baz.tar.gz` would become e.g. `foo/bar/baz/https://example.com/baz.tar.gz`

Calling `os.Stat` on that result, only the first one would actually succeed because the others are garbage paths. That would make the first one a candidate for showing the `TF-UPGRADE-TODO` comment but exclude from the others.

My concern is only partially related to bitbucket: `go-getter` is a messy beast that is subject to change upstream, and this has caused us problems in the past both in terms of unexpected behavior in the _current_ version (there are a lot of moving parts there which interact in non-obvious ways) and unintended consequences of other upstream changes (introducing new detectors into that detectors map, for example). Ideally our upgrade and install behavior should be simple and predictable, so doing something straightforward-but-imprecise in Terraform feels better to me than doing something that might potentially be more accurate in some cases but may have unintended consequences over time.

This alternative path doesn't seem like it's duplicating any significant behavior from `go-getter`, but I'm sure there are some situations where the above would produce a slightly different result than `go-getter` for sure. I was just trying to find the simplest possible way to ask "does this look like it's trying to be a relative path?", since that's the key question here.

**Comment by mildwonkey** [comment]
Hah, that was a fun diversion:

I (locally) re-enabled the e2e tests and it failed - turns out our test module, hashicorp/vault/aws, uses the improper relative module source 🙄 

```
module "vault_cluster" {
  # When using these modules in your own templates, you will need to use a Git URL with a ref attribute that pins you
  # to a specific version of the modules, such as the following example:
  # source = "github.com/hashicorp/terraform-aws-vault//modules/vault-cluster?ref=v0.0.1"
  source = "modules/vault-cluster"
```

And the error, which is nice but I think the text could use some tweaking:
```
        Error: Failed to locate local module source

        modules/vault-cluster looks like a relative path, but Terraform cannot
        determine the module source. Add ./ at the start of the source string if this
        is a relative path.
```

I forked that module so I could fix the relative module sources, published it to the registry, tweaked the tests, and 🎉 - the module init worked perfectly (and, as expected, the provider installation failed).

File: internal/initwd/module_install.go [hunk 3]
```diff
@@ -487,17 +471,36 @@ func (i *ModuleInstaller) installGoGetterModule(req *earlyconfig.ModuleRequest,
...
+			log.Printf(
+				"[TRACE] ModuleInstaller: %s looks like a local path but is missing ./ or ../",
+				req.SourceAddr,
+			)
+			diags = diags.Append(tfdiags.Sourceless(
+				tfdiags.Error,
+				"Module not found",
+				fmt.Sprintf(
+					"The module address %q could not be resolved.\n\n"+
+						"If you intended this as a path relative to the current module, use\n"+
```
Comment (apparentlymart) [inline internal/initwd/module_install.go]: The diagnostics message printer has its own line wrapping built in, so you only need to insert explicit `\n\n` to separate paragraphs.
