### PR TITLE
removed orphaned data sources from the working state

### LINKED ISSUE #27617: Output shows values from previous applies when using for loop with data source
TerraformShowsDataFromPreviousState
### Terraform Version
Terraform v0.14.5

### Terraform Configuration Files
```terraform
locals {

    ### COLLECTION A ###
    collection = {
        dudeSet1 = {
            name = "Bill"
        }
    }

    ## COLLECTION B ###
    # collection = {
    #     dudeSet2 = {
    #        name = "Ted"
    #    }
    # }
}

### DATA SOURCE BLOCK ###
data "null_data_source" "get_dude" {
    for_each = local.collection

    inputs = {
        dude = each.value["name"]
    }
}

# This should only output the dude from the data source for this run and NOT include data from the previous run.
output output_dude {
    value = {for dudeSetKey in keys(data.null_data_source.get_dude) : dudeSetKey => data.null_data_source.get_dude[dudeSetKey].outputs.dude}
}
```

### Debug Output
https://gist.github.com/DannyArr/3431834b3080890683f6bbbc935344f3

### Expected Behavior
Output should show the results of the data source as per the inputs provided.

### Actual Behavior
Output includes data from previous runs. i.e. data that is not included in any variables or locals. This then disapears on a subsequent run making the results inconsistent.

### Steps to Reproduce
Apply will need to be run 3 times to illustrate the issue. The first time with the local collection A included, and collection B commented out. The second time with Collection B included and Collection A commented out. Then rerun previous config again.

1. `terraform init`
2. `terraform apply`
3. Note the output: It should have "Bill"
4. Comment out the local "Collection A"
5. Remove comments for the local "Collection B"
6. `terraform apply`
7. Note the output: It should have both "Bill" and "Ted"
8. `terraform apply`
9. Note the output: It should now only have "Ted"

NOTE: this only seems to occur when using a for_each loop in a data source. 

### Additional Context
None

### References
None

### PR DESCRIPTION
**Pull request by jbardin**
When removing data source instances via alterations to a `for_each` value, the orphaned instance must be removed from both the refresh state, and the working state.  While the `refreshState` represents what the data source is currently, plan-time evaluations will still happen against the working state.

Fixes #27617

This will require a manual backport for 0.14

### CODE REVIEW

File: terraform/context_plan2_test.go [hunk 1]
```diff
@@ -54,11 +54,6 @@ resource "test_object" "a" {
 			t.Fatalf("expected Create action for missing %s, got %s", c.Addr, c.Action)
 		}
 	}
-
-	_, diags = ctx.Apply()
-	if diags.HasErrors() {
-		t.Fatal(diags.Err())
-	}
```
Comment (jbardin) [inline terraform/context_plan2_test.go:61]: This slipped into the change from the file I had open already, but I left it since it's a bit of code that should have been deleted. `Apply` shouldn't be called in the plan test, and does not check anything.

**Review by mildwonkey — APPROVED** [review]
