### PR TITLE
provider/azurerm: Fixing a bug in `azurerm_network_interface`

### LINKED ISSUE #7986: Status=429 Code="RetryableError" Message="A retryable error occured."
I think this might be related with this issue https://github.com/hashicorp/terraform/issues/7153 I'm open it to provide more information about it and to keep separate from that issue.
### Terraform Version

Terraform v0.7.0
### Affected Resource(s)
- azurerm_subnet
### Terraform Configuration Files

[link](https://gist.github.com/zot24/f6186a1c96ebca2780cf64968efddb89)
### Debug Output

[link](https://gist.github.com/zot24/5973e55c59779a3d286e7c09eac1a651)
### Standard Output

```
Error applying plan:

1 error(s) occurred:

* azurerm_subnet.mod: network.SubnetsClient#CreateOrUpdate: Failure responding to request: StatusCode=429 -- Original Error: autorest/azure: Service returned an error. Status=429 Code="RetryableError" Message="A retryable error occured." Details=[{"code":"ReferencedResourceNotProvisioned","message":"Cannot proceed with operation because resource /subscriptions/614e4618-7e10-4847-be48-a61acdbadff1/resourceGroups/testm1_resource_group_1/providers/Microsoft.Network/networkSecurityGroups/testm1_network_security_group_1 used by resource /subscriptions/614e4618-7e10-4847-be48-a61acdbadff1/resourceGroups/testm1_resource_group_1/providers/Microsoft.Network/virtualNetworks/testm1_virtual_network_1/subnets/testm1_subnet_1 is not in Succeeded state. Resource is in Updating state and the last operation that updated/is updating the resource is PutSecurityRuleOperation."}]
```
### Azure Error

```
    "properties": {
        "statusCode": "429",
        "serviceRequestId": "fa3f97c4-3118-4a93-b625-6a0948b5d9f4",
        "statusMessage": "{\"error\":{\"code\":\"RetryableError\",\"message\":\"A retryable error occured.\",\"details\":[{\"code\":\"ReferencedResourceNotProvisioned\",\"message\":\"Cannot proceed with operation because resource /subscriptions/614e4618-7e10-4847-be48-a61acdbadff1/resourceGroups/testm1_resource_group_1/providers/Microsoft.Network/networkSecurityGroups/testm1_network_security_group_1 used by resource /subscriptions/614e4618-7e10-4847-be48-a61acdbadff1/resourceGroups/testm1_resource_group_1/providers/Microsoft.Network/virtualNetworks/testm1_virtual_network_1/subnets/testm1_subnet_1 is not in Succeeded state. Resource is in Updating state and the last operation that updated/is updating the resource is PutSecurityRuleOperation.\"}]}}"
    },
    "resourceGroupName": "testm1_resource_group_1",
    "resourceId": "/subscriptions/614e4618-7e10-4847-be48-a61acdbadff1/resourceGroups/testm1_resource_group_1/providers/Microsoft.Network/virtualNetworks/testm1_virtual_network_1/subnets/testm1_subnet_1",
    "resourceProviderName": {
        "localizedValue": "Microsoft.Network",
        "value": "Microsoft.Network"
    },
```

### PR DESCRIPTION
**Pull request by tombuildsstuff**
When [using this Terraform configuration](https://gist.github.com/tombuildsstuff/5037aa929df7913033883ed48c6a77c2), which creates multiple NIC's in different Subnets within the same Virtual Network using either Terraform 0.9.4 / the `master` branch this returns an error:

```
Error applying plan:

2 error(s) occurred:

* azurerm_network_interface.test2: 1 error(s) occurred:

* azurerm_network_interface.test2: network.InterfacesClient#CreateOrUpdate: Failure responding to request: StatusCode=429 -- Original Error: autorest/azure: Service returned an error. Status=429 Code="RetryableError" Message="A retryable error occured." Details=[{"code":"ReferencedResourceNotProvisioned","message":"Cannot proceed with operation because resource /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/tharvey-dev7986/providers/Microsoft.Network/virtualNetworks/tharveydev7986nw/subnets/tharveydev7986sn1 used by resource /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/tharvey-dev7986/providers/Microsoft.Network/networkInterfaces/tharveydev7986ni2 is not in Succeeded state. Resource is in Updating state and the last operation that updated/is updating the resource is PutSubnetOperation."}]
* azurerm_network_interface.test1: 1 error(s) occurred:

* azurerm_network_interface.test1: network.InterfacesClient#CreateOrUpdate: Failure responding to request: StatusCode=429 -- Original Error: autorest/azure: Service returned an error. Status=429 Code="RetryableError" Message="A retryable error occured." Details=[{"code":"ReferencedResourceNotProvisioned","message":"Cannot proceed with operation because resource /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/tharvey-dev7986/providers/Microsoft.Network/virtualNetworks/tharveydev7986nw/subnets/tharveydev7986sn1 used by resource /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/tharvey-dev7986/providers/Microsoft.Network/networkInterfaces/tharveydev7986ni1 is not in Succeeded state. Resource is in Updating state and the last operation that updated/is updating the resource is PutSubnetOperation."}]
```

When provisioning using the changes in this PR, which ensures we only modify one subnet/virtual network at a time - this gets provisioned as expected:
```
Apply complete! Resources: 11 added, 0 changed, 0 destroyed.
```

Fixes #7986

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
Ran the entire test suite - the tests pass (ignoring some unrelated/intermittent failures):

screen shot 2017-05-10 at 22 09 10

File: builtin/providers/azurerm/resource_arm_network_interface_card.go [hunk 1]
```diff
@@ -373,9 +396,10 @@ func validateNetworkInterfacePrivateIpAddressAllocation(v interface{}, k string)
 	return
 }
 
-func expandAzureRmNetworkInterfaceIpConfigurations(d *schema.ResourceData) ([]network.InterfaceIPConfiguration, error) {
+func expandAzureRmNetworkInterfaceIpConfigurations(d *schema.ResourceData) ([]network.InterfaceIPConfiguration, *[]string, error) {
```
Comment (paddycarver) [inline builtin/providers/azurerm/resource_arm_network_interface_card.go]: Why return a pointer to a slice? A slice is basically a pointer already, so I don't really see the benefit.
