### PR TITLE
provider/aws: Fix the validateFunc of aws_elasticache_replication_group

### LINKED ISSUE #9895: Elasticache Replication Group ID Error
#Hi,

(1) I have an Elasticache replication group with the name 'xx-yy-66-zz'. I have imported it using the command 'terraform import aws_elasticache_replication_group.xxyy66zz xx-yy-66-zz

I created a configuration file (pasted below) to match the state file.

resource "aws_elasticache_replication_group" "xxyy66zz" {
  replication_group_id          = "xx-yy-66-zz"
  replication_group_description = "xxxx"
  node_type                     = "cache.r3.xlarge"
  number_cache_clusters         = 2
  port                          = 6379
  parameter_group_name          = "xxxx"
  automatic_failover_enabled    = true
  
}

When I run 'terraform plan', I receive an error saying "replication_group_id must contain from 1 to 16 alphanumeric characters or hyphens"

(2)I have another replication group with the name 'xxx-yyy2'. I have imported it and created a similar configuration file (pasted below)

resource "aws_elasticache_replication_group" "xxxyyy2" {
  replication_group_id          = "xxx-yyy2"
  replication_group_description = "xxxx"
  node_type                     = "cache.r3.xlarge"
  number_cache_clusters         = 2
  port                          = 6379
  parameter_group_name          = "xxxx"
  automatic_failover_enabled    = true

}

Terraform plan on this group doesn't result in any errors.

May I know why this is happening?

Thanks,
Anudeep

### PR DESCRIPTION
**Pull request by stack72**
Fixes #9895

The replication_group_id should allow length to be max of 20 not 16

```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestResourceAWSElastiCacheReplicationGroupIdValidation'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/11/07 16:17:52 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v
-run=TestResourceAWSElastiCacheReplicationGroupIdValidation -timeout
120m
=== RUN   TestResourceAWSElastiCacheReplicationGroupIdValidation
--- PASS: TestResourceAWSElastiCacheReplicationGroupIdValidation (0.00s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/aws0.032s
```

### CODE REVIEW

File: builtin/providers/aws/resource_aws_elasticache_replication_group_test.go [hunk 1]
```diff
@@ -235,7 +235,7 @@ func TestResourceAWSElastiCacheReplicationGroupIdValidation(t *testing.T) {
 			ErrCount: 1,
 		},
 		{
-			Value:    randomString(17),
+			Value:    randomString(21),
```
Comment (paddyforan) [inline builtin/providers/aws/resource_aws_elasticache_replication_group_test.go]: Wouldn't this pass prior to your code changes? Is it worth checking that `randomString(17)` now isn't an error?

Comment (stack72) [inline builtin/providers/aws/resource_aws_elasticache_replication_group_test.go]: ErrCount: 1 means that we check that an error is thrown from the validateFunc :)

Comment (stack72) [inline builtin/providers/aws/resource_aws_elasticache_replication_group_test.go]: I want to check that when we create a string > 20 that we fail the validation func - I guess i could add another test if you want to prove both work?

Comment (paddyforan) [inline builtin/providers/aws/resource_aws_elasticache_replication_group_test.go]: Errr. I apparently need to eat something, because I was _super sure_ that `if 17 > 20` would also evaluate to true. For some reason.

Disregard this, I'm speaking nonsense.
