### PR TITLE
Prune unused resources from graph

### LINKED ISSUE #2766: terraform_remote_state output unavailable for module during destroy phase
Steps to reproduce:

**`shared/main.tf`**
```ruby
output "env_name" {
  value = "test"
}
```
```
$ terraform remote config -backend=S3 -backend-config="bucket=terraform-test-bucket" -backend-config="key=terraform.tfstate" -backend-config="region=us-east-1"
```
```
$ terraform apply
```

**`my_module/main.tf`**
```ruby
variable "environment" {}
```

**`example.tf`**
```ruby
resource "terraform_remote_state" "shared" {
  backend = "s3"

  config {
    bucket = "terraform-test-bucket"
    key = "terraform.tfstate"
    region = "us-east-1"
  }
}

module "example" {
  source = "./my_module/"
  environment = "${terraform_remote_state.shared.output.env_name}"
}
```

```sh
$ terraform apply # OK
```
```sh
$ terraform destroy
```
```
Error applying plan:

1 error(s) occurred:

* Resource 'terraform_remote_state.shared' does not have attribute 'output.env_name' for variable 'terraform_remote_state.shared.output.env_name'
```

### PR DESCRIPTION
**Pull request by mitchellh**
Fixes #2766 

This is a hammer approach to fixing #2766. I feel compelled to explain why such a change is necessary.

The issue with #2766 is that we're interpolating a module variable during a destroy plan. As such, of course, the interpolation fails (because the data it is interpolating is from a resource that has been destroyed). 

In an ideal world, what we want to do is say: don't interpolate if this variable is only used by resources that are being destroyed. But, I couldn't think of any clean way to do this. 

This lead to plan B, which is this PR: don't evaluate any nodes that don't need to be evaluated. This is a depth-first optimization that asks every node: are you a noop? if it says yes, it removes it.

This PR makes two prun-able changes:

* Resources can be pruned iff there is a diff (we've already planned) AND there is no diff containing this resource.

* Variables can be pruned if there is a diff AND nothing depends on them except root.

This fixes the bug and passes all other tests.

I'm fairly confident this won't introduce _new_ bugs, but also confident that by tuning the prunes more carefully, we can probably also remove other bugs.

### CODE REVIEW

File: terraform/transform_noop.go [hunk 1]
```diff
@@ -0,0 +1,105 @@
...
+	leaves := make([]dag.Vertex, 0, 10)
+	for _, v := range g.Vertices() {
+		if g.DownEdges(v).Len() == 0 {
+			leaves = append(leaves, v)
+		}
+	}
+
+	// Do a depth first walk from the leaves and remove things.
+	return g.ReverseDepthFirstWalk(leaves, func(v dag.Vertex, depth int) error {
+		println("NAME: " + v.(dag.NamedVertex).Name())
```
Comment (phinze) [inline terraform/transform_noop.go]: Stray print here

File: terraform/graph_config_node_resource.go [hunk 2]
```diff
@@ -249,6 +249,38 @@ func (n *GraphNodeConfigResource) DestroyNode(mode GraphNodeDestroyMode) GraphNo
...
+
+	// If there is no diff, then we aren't a noop
+	if opts.Diff == nil || opts.Diff.Empty() {
+		return false
+	}
+
+	// If we have no module diff, we're certainly a noop
+	if opts.ModDiff == nil || opts.ModDiff.Empty() {
+		return true
+	}
```
Comment (phinze) [inline terraform/graph_config_node_resource.go]: These two clauses threw me off. Why do we know that an empty `Diff` is definitely not a noop but an empty `ModDiff` is definitely a noop?

**Comment by mitchellh** [comment]
Clarified that comment, will merge shortly after tests pass.

**Comment by mitchellh** [comment]
(force pushed with a rebase on master to verify that tests still pass with latest core changes)

**Comment by phinze** [comment]
LGTM
