### PR TITLE
repl: Improved value renderer for console outputs

### LINKED ISSUE #25798: terraform cannot compare `[]` to an empty list; requires `tolist([])`
### Terraform Version
v0.13.0 (build from master)

### Terraform Configuration Files

```terraform
variable empty_list {
  type = list      // same result if type = list(string)
  default = []
}
```

### Debug Output
I feel both qualified and empowered to say it's not helpful.

### Crash Output
n/a

### Expected Behavior
```bash
terraform console
> var.empty_list
[]
> var.empty_list == []
true
```

### Actual Behavior

```bash
terraform console
> var.empty_list
[]
> var.empty_list == []
false
```

### Steps to Reproduce
same as 'actual behavior': `terraform console`

### Additional Context
Now if you remove the `type` attribute from the variable, the comparison works as expected:
```hcl
variable empty_list {
  default = []
}
```

```bash
terraform console
> var.empty_list
[]
> var.empty_list == []
true
```

### Explanation
This behavior occurs because `[]` is an empty _tuple_, not a list, and so when the variable type is explicitly declared as a *list*, the comparison does not work. When the type is removed, `[]` matches the *assumed* variable type, which is `tuple` (thanks @alisdair!)
Note that this comparison works:

```
> var.empty_list == tolist([])
true
``` 

This seems unintuitive I'd expect that it will lead to many questions from users (wearing my user hat I can say this would infuriate me, especially given that I could not easily find documentation to explain it). Note that the behavior is the same within a configuration:
```hcl
output "test" {
  value = var.empty_list == []
}
``` 

```bash
Outputs:

test = false
```

Given that you can write `default = []`, why can't you compare `var.empty_list == []`? I'd almost rather users were required to write `default = tolist([])` so that it's explicit from the start.

There's a hint of a reference to a thing that looks like a list being a tuple in the [Type Constraints Documentation](https://www.terraform.io/docs/configuration/types.html#dynamic-types-the-quot-any-quot-constraint); at minimum we might want to extend this section to make explicit that `[]` is not actually a list:

> If the given value were ["a", "b", "c"] -- whose physical type is tuple([string, string, string]), Terraform analyzes this as follows:

### LINKED ISSUE #26099: Terraform console, incorrect output for object when properties are null
### Terraform Version

```
Terraform v0.13.0
```

### Terraform Configuration Files

```terraform
# main.tf
locals {
  object = {
        "ap-southeast-2": {
            "cognitoMinPasswordLength": null,
            "cognitoTempPasswordValidityInDays": null
        }

        "us-east-1": {
            "cognitoMinPasswordLength": 8,
            "cognitoTempPasswordValidityInDays": 1
        }
  }
}
```

### Expected Behavior

For `local.object.ap-southeast-2 == {}` it should return true, but instead returns false.

The expected behavior should be either:

Return the correct representation of the map without promoting it to {}
```terraform
{
  "ap-southeast-2" = {
    "cognitoMinPasswordLength" = null
    "cognitoTempPasswordValidityInDays" = null
  }
}
```

OR

if terraform is going to promote a map with all the properties null to empty map `{}`, then it should return true when one does this: `local.object.ap-southeast-2 == {}`

### Actual Behavior

See Steps to Reproduce.

### Steps to Reproduce

```text
$ terraform console
> local.object
{
  "ap-southeast-2" = {}
  "us-east-1" = {
    "cognitoMinPasswordLength" = 8
    "cognitoTempPasswordValidityInDays" = 1
  }
}
> local.object.ap-southeast-2
{}
> local.object.ap-southeast-2 == {}
false
> {} == {}
true
> exit
```

### PR DESCRIPTION
**Pull request by alisdair**
Use a slightly modified value renderer from terraform-provider-testing to display values in the console REPL, as well as outputs from the apply and outputs subcommands.

[Derived from code in this repository, MIT licensed](https://github.com/apparentlymart/terraform-provider-testing), as [suggested by Martin](https://github.com/hashicorp/terraform/issues/26099#issuecomment-686012115). Hope this is what he meant! 

Note that this is technically a breaking change for the console subcommand, which would previously error if the user attempted to render an unknown value (such as an unset variable). This was marked as an unintentional side effect, with the goal being the new behaviour of rendering "(unknown)", which is why I changed the behaviour in this commit.

Fixes #26099. Arguably fixes #25798 as well, I think.

### Screenshot

With this configuration:

```hcl
locals {
  object = {
    "foo" : {
      "x" : null,
      "y" : null
    }
    "bar" : {
      "x" : 2,
      "y" : 3
    }
  }
}

variable "animals" {
  type = list(string)
  default = [
    "cat",
    "dog",
    "marmot",
    "possum",
    "tortoise",
  ]
}

variable "integers" {
  type = set(number)
}

variable "versions" {
  type    = map(string)
  default = null
}
```

console

### CODE REVIEW

**Review by mildwonkey — APPROVED** [review]
👏 Lovely!

**Comment by alisdair** [comment]
@apparentlymart No rush for this at all, but I wanted to ask for a second review from you, since this is both your idea & mostly your code 😅

File: repl/format.go [hunk 1]
```diff
@@ -1,116 +1,142 @@
...
-func formatResult(value interface{}, nested bool) (string, error) {
-	if value == nil {
-		return "null", nil
+// FormatValue formats a value in a way that resembles Terraform language syntax
+// and uses the type conversion functions where necessary to indicate exactly
+// what type it is given, so that equality test failures can be quickly
+// understood.
+func FormatValue(v cty.Value, indent int) string {
+	if !v.IsKnown() {
+		return "(unknown)"
```
Comment (apparentlymart) [inline repl/format.go:41]: I'd suggest changing this to `(known after apply)` to match with the `terraform plan` output. We've seen in the past that there are unfortunately a few other edge-cases where things appear as unknown in the console that are _not_ caused by something that would be set after apply, but I believe we addressed the most common of those recently by making an exception to allow the impure (and thus, non-convergent) functions like `timestamp` to be evaluated in the console.

File: repl/format_test.go [hunk 2]
```diff
@@ -0,0 +1,173 @@
...
+			cty.NullVal(cty.Set(cty.Number)),
+			`toset(null) /* of number */`,
+		},
+		{
+			cty.NullVal(cty.Map(cty.Bool)),
+			`tomap(null) /* of bool */`,
+		},
+		{
+			cty.NullVal(cty.Object(map[string]cty.Type{"a": cty.Bool})),
+			`null /* object */`, // Ideally this would display the object attributes, but that depends on a cty change
```
Comment (apparentlymart) [inline repl/format_test.go:69]: Note mostly to myself: I don't actually recall what cty change I was imagining making here, or why this wouldn't be possible to implement already today. 🤔 

It's likely that including a full object type in full detail here would be pretty verbose in many cases, but I guess not more verbose than a non-null value of that type would be, and so perhaps what I was anticipating implementing was a type pretty-printer? If so I'm second-guessing that being `cty` thing now, because we'd likely rather it produce Terraform's type constraint syntax, which lives at the HCL level of abstraction rather than cty.

**Review by apparentlymart — APPROVED** [review]
This looks good to me. Thanks!

The old formatter had a few special exceptions, like showing standalone string values raw rather than quoted, but I always found those exceptions rather confusing so I'm favor of removing them here and being consistent. However, I will note that this does create some risk of users being confused by it in a similar way as we sometimes see for the `terraform plan` output: not everyone seems to understand that Terraform is using (something close to) its own string quoting syntax and thinks that any escape characters are literal. That hasn't come up _incredibly_ often, so I don't think we need to take this as a design constraint, but if we see it coming up more after we release this (not yet) it may behoove us to find a suitable place to write some docs on how to understand the output, which we can then refer users to when they ask questions about it.

I also find the big block license comments at the top of the files annoying, so I'm going to say it's fine to take this into Terraform without the explicit license statements, even though that contradicts the letter of the MIT license text in my other codebase, so that this can just be a contribution under the normal HashiCorp CLA terms, rather than an odd exception.

File: repl/format_test.go (hunk 2 above)
Comment (alisdair) [reply repl/format_test.go:69]: This is one of the changes I made from your original code, and the comment is mine, which is why you don't remember making it 😅

I was referring to [this TODO in cty](https://github.com/zclconf/go-cty/blob/4ad5e68430d39668dcce61d993b938f75a1e42ac/cty/object_type.go#L99-L108):

```go
func (t typeObject) FriendlyName(mode friendlyTypeNameMode) string {
	// There isn't really a friendly way to write an object type due to its
	// complexity, so we'll just do something English-ish. Callers will
	// probably want to make some extra effort to avoid ever printing out
	// an object type FriendlyName in its entirety. For example, could
	// produce an error message by diffing two object types and saying
	// something like "Expected attribute foo to be string, but got number".
	// TODO: Finish this
	return "object"
}
```

I'll update the comment to remove the reference to cty here.
