### PR TITLE
Generalize target addresses before expansion

### LINKED ISSUE #25748: Cannot target a resource inside a module with for_each
Hello,

I opened an issue #25186 with almost the same problem.
I cannot target a resource inside a module.

### Terraform Version

```
Terraform v0.13.0-rc1
```

### Terraform Configuration Files

https://github.com/hashicorp/terraform/tree/guide-v0.13-beta/module-repetition

### Expected Behavior

```
  # module.certificates["example.com"].tls_locally_signed_cert.cert will be created
  + resource "tls_locally_signed_cert" "cert" {
      + allowed_uses          = [
          + "server_auth",
        ]
      + ca_cert_pem           = "89786ea14e2fe52dfbabe2ce359cb7dd254c0c52"
      + ca_key_algorithm      = "RSA"
      + ca_private_key_pem    = (sensitive value)
      + cert_pem              = (known after apply)
      + cert_request_pem      = (known after apply)
      + early_renewal_hours   = 0
      + id                    = (known after apply)
      + ready_for_renewal     = true
      + validity_end_time     = (known after apply)
      + validity_period_hours = 24
      + validity_start_time   = (known after apply)
    }

```

### Actual Behavior

```

Warning: Resource targeting is in effect

You are creating a plan with the -target option, which means that the result
of this plan may not represent all of the changes requested by the current
configuration.
		
The -target option is not for routine use, and is provided only for
exceptional situations such as recovering from errors or mistakes, or when
Terraform specifically suggests to use it as part of an error message.


Warning: Applied changes may be incomplete

The plan was created with the -target option in effect, so some changes
requested in the configuration may have been ignored and the output values may
not be fully updated. Run the following command to verify that no other
changes are pending:
    terraform plan
	
Note that the -target option is not suitable for routine use, and is provided
only for exceptional situations such as recovering from errors or mistakes, or
when Terraform specifically suggests to use it as part of an error message.


Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply -target='module.certificates["example.com"].tls_locally_signed_cert.cert'`

### PR DESCRIPTION
**Pull request by jbardin**
Before expansion happens, we only have expansion resource nodes that
know their ConfigResource address. In order to properly compare these to
targets within a module instance, we need to generalize the target to
also be a ConfigResource.

We can also remove the IgnoreIndices field from the transformer, since
we have addresses that are properly scoped and can compare them in the
correct context.

Fixes #25748

### CODE REVIEW

File: terraform/transform_targets.go [hunk 1]
```diff
@@ -133,25 +127,27 @@ func (t *TargetsTransformer) nodeIsTarget(v dag.Vertex, targets []addrs.Targetab
...
+		case addrs.ConfigResource:
+			// Before expansion happens, we only have nodes that know their
+			// ConfigResource address.  We need to take the more specific
+			// target addresses and generalize them in order to compare with a
+			// ConfigResource.
+			switch target := targetAddr.(type) {
 			case addrs.AbsResourceInstance:
-				targetAddr = instance.ContainingResource().Config()
-			case addrs.ModuleInstance:
-				targetAddr = instance.Module()
```
Comment (alisdair) [inline terraform/transform_targets.go:152]: I was curious about why the module case was removed here, and tried to check if targeting a module instance would work. It doesn't seem to (unless my test is broken), and I couldn't find a way to make it work, but I'm very unfamiliar with this code so that's not surprising.

Should `terraform apply -target=module.mod[1]` work? Does it already and I'm just mistaken?

Comment (jbardin) [reply terraform/transform_targets.go:152]: Thanks @alisdair! It appears I was thinking about this block in terms of only resource addresses (probably because of the case statement), and not the module itself. Let me add some tests in here too, since that was obviously not covered.
