### PR TITLE
terraform test: move override evaluation into expander

### LINKED ISSUE #35019: Variables in overriden modules cause "value for module.redacted.local.redacted was requested before it was provided" crash
### Terraform Version

```shell
Terraform v1.8.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.45.0
+ provider registry.terraform.io/hashicorp/random v3.6.1
```

### Terraform Configuration Files

https://github.com/david1437/terraform-override-module-bug-report

### Debug Output

https://gist.github.com/david1437/233812625b369caecac02a21305181dc

### Expected Behavior

The module should be overridden and just return specified output

### Actual Behavior

terraform test crashes 

### Steps to Reproduce

terraform init
terraform test

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by liamcervante**
This PR makes use of the new expander logic to handle the terraform test module overrides directly where the modules are expanded instead of later within the group as it was doing previously.

Previously, we just generally let the graph expansion happen and then looked for nodes within overridden modules as the graph executed. We'd then skip nodes within overridden modules to ensure they didn't execute, and then sideload values into the output nodes of the overridden modules.

This was actually broken for the expand nodes, as they aren't keyed by a module instance address which means it is impossible for us to tell during graph execution that they should be skipped. This meant that the expansion was still attempted for anything within an overridden module. If that expansion then required a value from something else in the module such as a local variable, the expansion failed with a crash. This is because the local variable execution was skipped (as it was in an overridden module), while the expansion was still attempted by the expansion nodes are not keyed by module instances.

Now, we pass the override information into the expander. When it is asked for module instances, it excludes instances that have been overridden. This means that concrete execute nodes for overridden modules are not even created as a result of that expansion essentially not even existing.

For output nodes, we actually do include the overridden module instances and we implement the logic for checking if the module instance has been overridden directly within the output node. This means the output nodes can load the values from the override, instead of attempting to look at any references which would then fail since the other nodes in the module were not executed.

The change count here is smaller than it looks. I changed some wide-ranging function arguments, which has led to a lot of diffs that simply set `false` or `nil` for the `includeOverrides` and `overrides` arguments within the expander and the "get module instances" functions.

Fixes #35019 

## Target Release

1.8.2

### NEW FEATURES | UPGRADE NOTES | ENHANCEMENTS | BUG FIXES | EXPERIMENTS

 

-  `terraform test`: Prevent crash when referencing local variables within overridden modules.

### CODE REVIEW

File: internal/moduletest/mocking/overrides.go [hunk 1]
```diff
@@ -96,52 +102,36 @@ func (overrides *Overrides) IsOverridden(module addrs.ModuleInstance) bool {
 	return false
 }
 
-// IsDeeplyOverridden returns true if an ancestor of this module is overridden
-// but not if the module is overridden directly.
+// GetResourceOverride checks the overrides for the given resource instance.
+// This function automatically checks if the containing resource has been
+// overridden if the instance is instanced.
```
Comment (jbardin) [inline internal/moduletest/mocking/overrides.go:107]: Not sure I understand that last sentence

**Review by jbardin — APPROVED** [review]
This looks like a lot, but from what I can tell this is well contained within the testing functionality, so should be OK to backport.

File: internal/moduletest/mocking/overrides.go (hunk 1 above)
Comment (liamcervante) [reply internal/moduletest/mocking/overrides.go]: Clarified!
