### PR TITLE
Skip variable validations during destroy plans

### LINKED ISSUE #34052: Terraform Crash: checkable object status report for unexpected checkable object
### Terraform Version

```shell
1.6.0
1.6.1
```

### Terraform Configuration Files

The crash occurs on a variable in an internal module which is a wrapper around some hashicorp aws msk resources.  The variable in question is a string:
```
variable "compression_type" {
  description = "<desc>"
  default = "lz4"
  validation {
    condition = contains(["gzip", "snappy", "lz4", "zstd", "uncompressed", "producer"], var.compression_type)
    error_message = "<error_message>"
  }
}
```

This variable is passed into the `aws_msk_configuration` resource server.properties parameter:
```
resource "aws_msk_configuration" "config" {
  kafka_versions    = [var.msk_kafka_version]
  name              = "<name>"
  server_properties = <<PROPERTIES
    compression.type = ${var.compression_type}
    PROPERTIES

  lifecycle {
    create_before_destroy = true
  }
}
```

### Debug Output
```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

checkable object status report for unexpected checkable object module.msk.var.compression_type
goroutine 8280 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        /opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:16 +0x13
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /home/runner/work/terraform/terraform/internal/logging/panic.go:58 +0x13b
panic({0x2b94ec0?, 0xc00b40e8f0?})
        /opt/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:920 +0x270
github.com/hashicorp/terraform/internal/checks.(*State).reportCheckResult(0xc0031e3bc0, {0x390a1d0, 0xc004490e40}, 0xc000100000?, 0x0, 0x50)
        /home/runner/work/terraform/terraform/internal/checks/state_report.go:106 +0x345
github.com/hashicorp/terraform/internal/checks.(*State).ReportCheckResult(0x2fcdc40?, {0x390a1d0?, 0xc004490e40?}, 0xc001d516a8?, 0x1?, 0x1?)
        /home/runner/work/terraform/terraform/internal/checks/state_report.go:71 +0xc5
github.com/hashicorp/terraform/internal/terraform.evalVariableValidations({{0xc006699040, 0x1, 0x1}, {{}, {0xc0007a3a70, 0x10}}}, 0xc0009c2820, {0x0, 0x0}, {0x3922940, ...})
        /home/runner/work/terraform/terraform/internal/terraform/eval_variable.go:252 +0xb52
github.com/hashicorp/terraform/internal/terraform.(*nodeModuleVariable).Execute(0xc000dc0cc0, {0x3922940, 0xc000e388c0}, 0x5)
        /home/runner/work/terraform/terraform/internal/terraform/node_module_variable.go:198 +0x3f1
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc0018eb0e0, {0x3922940, 0xc000e388c0}, {0x4047af7540, 0xc000dc0cc0})
        /home/runner/work/terraform/terraform/internal/terraform/graph_walk_context.go:143 +0xbe
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x2f09cc0, 0xc000dc0cc0})
        /home/runner/work/terraform/terraform/internal/terraform/graph.go:78 +0x375
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc000dc0d80, {0x2f09cc0, 0xc000dc0cc0}, 0xc003970940)
        /home/runner/work/terraform/terraform/internal/dag/walk.go:384 +0x2e5
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update in goroutine 8007
        /home/runner/work/terraform/terraform/internal/dag/walk.go:307 +0xde8
```

### Expected Behavior

This only occurs at destroy time.  I expect the given objects to be destroyed but terraform crashes instead.

### Actual Behavior

Terraform should destroy the managed objects

### Steps to Reproduce

terraform destroy

### Additional Context

We have some projects internally with scheduled builds and tf version constraints set to something like `~> 1.3`.  When one of these projects builds kicked off post 1.6.0 release it started failing with the attached Terraform Crash error.  Builds still have the same crash using tf 1.6.1.  

When I revert to tf version 1.5.7 the destroy completes without issue so this issue seems exclusive to 1.6.* versions.

### References

_No response_

### PR DESCRIPTION
**Pull request by liamcervante**
This PR makes Terraform skip variable validations during destroy plans and applys. This makes variable validations match the behaviour of other custom conditions which also do not execute during destroy operations.

This has the side effect of fixing the crash in the linked issue, as the variable validations will no longer attempt to sometimes execute during destroy-apply operations after having been skipped during the equivalent plan operation.

Fixes #34052

## Target Release

1.6.2

### BUG FIXES

 

-  Fix occasional crash when destroying configurations with variables containing validations.

### CODE REVIEW

**Comment by apparentlymart** [comment]
The case where an input variable is used to configure one of the providers used to destroy makes me a little concerned about this, since anyone using validation rules as a guardrail against dangerous provider configurations would be surprised if those guardrails were silently ignored during destroy.

I see that there is some care for that in the code here but it isn't clear to me exactly what the behavior is. Do the validation rules still prevent a downstream provider configuration from being considered if it refers to invalid input variables? I think ideally I'd like to see it still do the checks and return error diagnostics in the destroy phase, even if we skip reporting the results via the "checks" concept (since writing the check results to state after a destroy would be a strange thing to do then everything else in the state has been deleted anyway).

I suppose it's true that we already made an exception for situations where a provider configuration refers to a resource that has a precondition or postcondition that is failing, but using input variables to for provider configurations is more common and I think it's more likely that someone would use them for something that is explicitly intended to be a provider configuration guardrail, like making sure that an appropriate region has been selected when running in a particular environment, or that endpoint overrides are only allowed in a development environment, etc.

File: internal/terraform/graph_builder_plan.go [hunk 1]
```diff
@@ -128,8 +128,16 @@ func (b *PlanGraphBuilder) Steps() []GraphTransformer {
...
-		&ModuleVariableTransformer{Config: b.Config, Planning: true},
+		&RootVariableTransformer{
+			Config:     b.Config,
+			RawValues:  b.RootVariableValues,
+			Planning:   true,
+			Destroying: b.Operation == walkPlanDestroy,
+		},
+		&ModuleVariableTransformer{
+			Config:   b.Config,
+			Planning: true,
```
Comment (jbardin) [inline internal/terraform/graph_builder_plan.go:139]: Should `Destroying` get set here instead, and then there are no checks to deal with during apply? This works as is, but it may be easier in the future if we can avoid registering `unknown` (or `invalid`, I can't remember the various states) checks in the first place.

**Comment by jbardin** [comment]
Taking @apparentlymart's comment and mine together, maybe the goal here is to avoid registering "invalid" checks, rather than skipping them entirely? I'm not sure exactly what that means yet, but did notice the failing checks all had that same zero-value state.

**Comment by liamcervante** [comment]
So, the initial statuses are set here: https://github.com/hashicorp/terraform/blob/main/internal/terraform/context_walk.go#L127-L138. Which internally calls this: https://github.com/hashicorp/terraform/blob/main/internal/checks/state.go#L86. 

We could add a bit of logic in there that doesn't do that for destroy only plans but we'd still need all this PR to also tell the input validations to not execute anyway. They don't actually check if a validation has been registered, just assume it has been and then try to report it. We'd just see the same panic we are seeing now.

The `ObjectAddrsKnown` check (from the first link) means it only reports checks that successfully executed during the plan, and because the plan is pruning variable nodes when the apply isn't we get the panic. Essentially the current behaviour is because the validations aren't being registered properly anyway, so just skipping registering them would have the same effect.

I think I could implement @apparentlymart's suggestion by keeping the logic as is but pushing the `if destroying {` check around this block instead: https://github.com/hashicorp/terraform/blob/493056d828ab0cd17def8e0193f71f4bfe8f9628/internal/terraform/eval_variable.go#L249-L253

**Comment by liamcervante** [comment]
FWIW, in a normal destroy operation it actually does a pre-destroy refresh plan first and the input validations do actually still execute during that part of the check. So an invalid input variable would still be caught during that stage.

**Comment by apparentlymart** [comment]
In today's Terraform we always require that the _root_ input variables set during plan will propagate exactly to the apply phase, and so we can assume that validations of those will be checked during planning and will thus block applying the plan.

Unfortunately the story isn't as neat for child module input variables, because they can be unknown during planning and given their final definition only during the apply step. That means we'd set the check result to "unknown" during planning and then only decide the final verdict during apply.

Since we're only talking about the destroy phase and provider configurations though, I think we can _probably_ get away with this loophole: destroy ignores most of the configuration anyway -- today it only evaluates `provider` blocks and `provisioner` blocks that have `when = destroy` set. And during destroy, everything a `provider` block depends on will have a known value because anything that can _produce_ values is resolved only from the state during destroy, and the state can never contain unknown values.

Therefore I think the fact that we should be able to catch it during planning, combined with the fact that the state can only change in very limited ways during a destroy operation (and in particular can't introduce new unknowns), does seem to address what I was concerned about. I don't think we need to tighten this loophole as long as it only happens during apply and only when doing a "full destroy".

**Review by jbardin — APPROVED** [review]
