### PR TITLE
Make sure resource private data is carried through the entire resource lifecycle

### LINKED ISSUE #21528: v0.12: Resource timeouts being ignored on destroy operations
### Terraform Version

terraform version is `0.12.0`
provider is based on plugin SDK version `0.12.0-rc1`

### Terraform Configuration Files

```hcl
resource oci_core_instance instance {
   timeouts {
    create = "60m"
    delete = "60m"
    update = "60m"
  }
}
```

### Expected Behavior

On Delete calls, the provider calls into `ResourceData.Timeout(schema.TimeoutDelete)` and expects to get 60 minutes time value back.

This works in v0.11.7 plugin SDKs

### Actual Behavior

The `ResourceData.Timeout(schema.TimeoutDelete)` is returning a default timeout value instead (20m).

### Steps to Reproduce

This was found on running acceptance tests, but a simple `terraform destroy` should be able to repro this.

### Additional Context

On Create calls, the timeout values are correct. This seems to only affect Delete operations.

Timeout values that are specified in the resource schema are also ignored even if `timeouts` block is removed from config. For example, if my resource has the following schema it will still return the default of 20m.

```
&schema.Resource{
		Timeouts: &schema.ResourceTimeout{
			Create: &OneHour,
			Update: &OneHour,
			Delete: &OneHour,
		},
```

### PR DESCRIPTION
**Pull request by jbardin**
The Private data was lost in a couple places, and not detected due to the Private data not being used heavily by the current SDK.

This also adds the Private data to the `ReadResource` call. While not currently used, it makes the use of the data more consistent, and would allow for more flexibility with future providers.

Fixes #21528

### CODE REVIEW

File: builtin/providers/test/resource_timeout_test.go [hunk 1]
```diff
@@ -27,6 +27,27 @@ resource "test_resource_timeout" "foo" {
 		},
 	})
 }
+
+func TestResourceTimeout_delete(t *testing.T) {
+	// If the delete timeout isn't saved until destroy, the cleanup here will
+	// fail because the default is only 20m.
```
Comment (pselle) [inline builtin/providers/test/resource_timeout_test.go]: Just A Comment: `only 20m` 😭

File: states/state_deepcopy.go [hunk 2]
```diff
@@ -181,14 +184,17 @@ func (obj *ResourceInstanceObject) DeepCopy() *ResourceInstanceObject {
 
 	var private []byte
 	if obj.Private != nil {
-		private := make([]byte, len(obj.Private))
+		private = make([]byte, len(obj.Private))
 		copy(private, obj.Private)
 	}
 
 	// Some addrs.Referencable implementations are technically mutable, but
```
Comment (pselle) [inline states/state_deepcopy.go]: Typo fix opportunity? `addrs.Referenceable` (if we apply the "while we're in the neighborhood" rule)

**Comment by jbardin** [comment]
@pam:

`Private` here isn't meant to be secure, it's provider data that is "private" from terraform core, meaning that core will not attempt to interpret or alter the data. The contract here is that if a provider returns something in `Private`, it expects to get that same data back in the next api call concerning the same resource.

File: command/command_test.go [hunk 3]
```diff
@@ -266,7 +267,7 @@ func testState() *states.State {
 				Type: "test",
 			}.Absolute(addrs.RootModuleInstance),
 		)
-	})
+	}).DeepCopy()
```
Comment (apparentlymart) [inline command/command_test.go]: This `DeepCopy` made me :thinking: a bunch because there's no other variable holding a reference to the state we built here and thus the copying seems superfluous.

However, reading down to see the other changes below I assume the goal here is to make sure that all of the data in the state makes it into the copy, and that makes sense. For the benefit of a future maintainer who won't have the benefit of seeing this line in the context of this PR diff, perhaps a short comment explaining that this is here to implicitly test `DeepCopy` would be helpful so it doesn't get cleaned up.
