### PR TITLE
plan: also validate provider requirements from state

### LINKED ISSUE #35860: failed to read provider configuration schema for registry.terraform.io/hashicorp/null
### Terraform Version

```shell
+ tfenv use 1.7.5
[32mNo installed versions of terraform matched '1.7.5:^1.7.5$'. Trying to install a matching version since TFENV_AUTO_INSTALL=true[0m
[32mInstalling Terraform v1.7.5[0m
[32mDownloading release tarball from https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip[0m

#############################                                             40.4%
######################################################################## 100.0%
[32mDownloading SHA hash file from https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_SHA256SUMS[0m
[33mNot instructed to use Local PGP (/usr/local/bin/tfenv-3.0.0/use-{gpgv,gnupg}) & No keybase install found, skipping OpenPGP signature verification[0m
terraform_1.7.5_linux_amd64.zip: OK
[32mArchive:  /tmp/tfenv_download.HFmbxs/terraform_1.7.5_linux_amd64.zip[0m
[32m  inflating: /usr/local/bin/tfenv-3.0.0/versions/1.7.5/terraform  [0m
[32mInstallation of terraform v1.7.5 successful. To make this your default version, run 'tfenv use 1.7.5'[0m
[32mSwitching default version to v1.7.5[0m
[32mDefault version (when not overridden by .terraform-version or TFENV_TERRAFORM_VERSION) is now: 1.7.5[0m
```

### Terraform Configuration Files

{
    "terraform": {
        "required_version": "1.7.5",
        "required_providers": {
            "aws": {
                "source": "hashicorp/aws",
                "version": "~> 5.35"
            },
            "archive": {
                "source": "hashicorp/archive",
                "version": "~> 2.4"
            }
        }
    }
}

### Debug Output

[0m[1mInitializing the backend...[0m
[0m[32m
Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.[0m
[0m[1mInitializing modules...[0m
- mastering_dlq_fifo in modules/monitored-deadletter-queue
- mastering_merge_requests_dedupe_dlq in modules/monitored-deadletter-queue
- mastering_organization_change_dedupe_dlq in modules/monitored-deadletter-queue
- mastering_organizations_exact_match_indexer_bulk_dlq in modules/monitored-deadletter-queue
- mastering_organizations_exact_match_indexer_dlq in modules/monitored-deadletter-queue
- mastering_organizations_inbound_sfdc_dlq_fifo in modules/monitored-deadletter-queue
- mastering_organizations_opensearch_indexer_bulk_dlq in modules/monitored-deadletter-queue
- mastering_organizations_opensearch_indexer_dlq in modules/monitored-deadletter-queue
- mastering_organizations_sfdc_merge_dlq_fifo in modules/monitored-deadletter-queue
- mastering_survivorship_dlq in modules/monitored-deadletter-queue

[0m[1mInitializing provider plugins...[0m
- Finding hashicorp/aws versions matching "~> 5.35"...
- Finding hashicorp/archive versions matching "~> 2.4"...
- Installing hashicorp/aws v5.71.0...
- Installed hashicorp/aws v5.71.0 (signed by HashiCorp)
- Installing hashicorp/archive v2.6.0...
- Installed hashicorp/archive v2.6.0 (signed by HashiCorp)

Terraform has created a lock file [1m.terraform.lock.hcl[0m to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.[0m

[0m[1m[32mTerraform has been successfully initialized![0m[32m[0m
[0m[32m
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.[0m
+ terraform workspace select -or-create us-west-2
[0m[32mSwitched to workspace "us-west-2".[0m
+ ansi2html
+ terraform plan -var-file=tfvars/env-dev.tfvars -out=/var/task/planned_deploy_us-west-2
[31m╷[0m[0m
[31m│[0m [0m[1m[31mError: [0m[0m[1mfailed to read provider configuration schema for registry.terraform.io/hashicorp/null: failed to instantiate provider "registry.terraform.io/hashicorp/null" to obtain schema: unavailable provider "registry.terraform.io/hashicorp/null"[0m
[31m│[0m [0m
[31m│[0m [0m[0m
[31m╵[0m[0m

### Expected Behavior

Should have run completely without issues 

### Actual Behavior

[0m[1mInitializing the backend...[0m
[0m[32m
Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.[0m
[0m[1mInitializing modules...[0m
- mastering_dlq_fifo in modules/monitored-deadletter-queue
- mastering_merge_requests_dedupe_dlq in modules/monitored-deadletter-queue
- mastering_organization_change_dedupe_dlq in modules/monitored-deadletter-queue
- mastering_organizations_exact_match_indexer_bulk_dlq in modules/monitored-deadletter-queue
- mastering_organizations_exact_match_indexer_dlq in modules/monitored-deadletter-queue
- mastering_organizations_inbound_sfdc_dlq_fifo in modules/monitored-deadletter-queue
- mastering_organizations_opensearch_indexer_bulk_dlq in modules/monitored-deadletter-queue
- mastering_organizations_opensearch_indexer_dlq in modules/monitored-deadletter-queue
- mastering_organizations_sfdc_merge_dlq_fifo in modules/monitored-deadletter-queue
- mastering_survivorship_dlq in modules/monitored-deadletter-queue

[0m[1mInitializing provider plugins...[0m
- Finding hashicorp/aws versions matching "~> 5.35"...
- Finding hashicorp/archive versions matching "~> 2.4"...
- Installing hashicorp/aws v5.71.0...
- Installed hashicorp/aws v5.71.0 (signed by HashiCorp)
- Installing hashicorp/archive v2.6.0...
- Installed hashicorp/archive v2.6.0 (signed by HashiCorp)

Terraform has created a lock file [1m.terraform.lock.hcl[0m to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.[0m

[0m[1m[32mTerraform has been successfully initialized![0m[32m[0m
[0m[32m
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.[0m
+ terraform workspace select -or-create us-west-2
[0m[32mSwitched to workspace "us-west-2".[0m
+ ansi2html
+ terraform plan -var-file=tfvars/env-dev.tfvars -out=/var/task/planned_deploy_us-west-2
[31m╷[0m[0m
[31m│[0m [0m[1m[31mError: [0m[0m[1mfailed to read provider configuration schema for registry.terraform.io/hashicorp/null: failed to instantiate provider "registry.terraform.io/hashicorp/null" to obtain schema: unavailable provider "registry.terraform.io/hashicorp/null"[0m
[31m│[0m [0m
[31m│[0m [0m[0m
[31m╵[0m[0m

### Steps to Reproduce

terraform init
terraform workspace select -or-create
terraform plan 

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by liamcervante**
This PR updates the validation of required providers so that it also makes sure any providers required by the state are included. This improves the error message returned when a resource is in state but not in config and has no included provider.

Before

```
╷
│ Error: failed to read schema for null_resource.resource in registry.terraform.io/hashicorp/null: failed to instantiate provider "registry.terraform.io/hashicorp/null" to obtain schema: unavailable provider "registry.terraform.io/hashicorp/null"
│ 
│ 
╵
```

After

```
╷
│ Error: Missing required provider
│ 
│ This state requires provider registry.terraform.io/hashicorp/null, but that provider isn't available. You may be able to install it automatically by
│ running:
│   terraform init
╵
```

Fixes #35860 

## Target Release

1.9.x

### ENHANCEMENTS

 

-  Improve error message when provider is required by state but has not been downloaded.

### CODE REVIEW

File: internal/terraform/context.go [hunk 1]
```diff
@@ -337,6 +338,51 @@ func (c *Context) watchStop(walker *ContextGraphWalker) (chan struct{}, <-chan s
...
+				// return its own version of this error before calling
+				// into here if not.
+				continue
+			}
+			if !providerAddr.IsBuiltIn() {
+				diags = diags.Append(tfdiags.Sourceless(
+					tfdiags.Error,
+					"Missing required provider",
+					fmt.Sprintf(
+						"This state requires provider %s, but that provider isn't available. You may be able to install it automatically by running:\n  terraform init",
```
Comment (DanielMSchmidt) [inline internal/terraform/context.go:365]: > You may be able to install it automatically

What is that dependent on? The provider being in the required provider section?

**Review by DanielMSchmidt — APPROVED** [review]

File: internal/terraform/context.go (hunk 1 above)
Comment (liamcervante) [reply internal/terraform/context.go:365]: Defined anywhere in the configuration or the state. This basically catches someone running `plan` or `apply` before they ran `init`. We do the same check with a similar error message in case something is in config and hasn't been caught: https://github.com/hashicorp/terraform/blob/main/internal/terraform/context.go#L389

`init` won't install automatically if the configuration is wrong, or it's not a default provider and isn't in the required providers. But all cases `init` will then provide specific error messages for why something couldn't be installed.
