### PR TITLE
provider/aws: Add support for reference_name to aws_route53_health_check

### LINKED ISSUE #8679: Not able to set caller reference in aws_route53_health_check
I have attempted to deploy a couple of Route 53 heath checks with terraform and got the following error:

`I, [2016-09-06T11:00:56.629375 #4836]  INFO -- : * aws_route53_health_check.healthstate.0: HealthCheckAlreadyExists: A different health check has already been created with the specified caller reference.
I, [2016-09-06T11:00:56.629375 #4836]  INFO -- : status code: 409`

I believe the issue it that aws_route53_health_check resource does not support 'reference_name' argument like 'aws_route53_delegation_set' does. Are there any plans to add support for that argument in the future?

Thank you!

### PR DESCRIPTION
**Pull request by stack72**
Fixes #8679

    The CallerReference attribute we passed to AWS in route53_health_checks was
    `time.Now().Format(time.RFC3339Nano)`

    When creating multiple resources with the Count meta-parameter, this was
    causing issues as follows:

    ```
    * aws_route53_health_check.healthstate.0: HealthCheckAlreadyExists: A
    different health check has already been created with the specified caller
    reference.
    ```
    We have now exposed a new attribute called `reference_name` that can be set
    to pass multiple resources to the request

    ``` make testacc TEST=./builtin/providers/aws
    TESTARGS='-run=TestAccAWSRoute53HealthCheck_'
    130 ↵ ✹
    ==> Cecking that code complies with gofmt requirements... go generate $(go
    list ./... | grep -v /terraform/vendor/) 2016/10/31 10:41:07 Generated
    command/internal_plugin_list.go TF_ACC=1 go test ./builtin/providers/aws -v
    -run=TestAccAWSRoute53HealthCheck_ -timeout 120m
    === RUN   TestAccAWSRoute53HealthCheck_importBasic
    --- PASS: TestAccAWSRoute53HealthCheck_importBasic (17.08s)
    === RUN   TestAccAWSRoute53HealthCheck_basic
    --- PASS: TestAccAWSRoute53HealthCheck_basic (28.17s)
    === RUN   TestAccAWSRoute53HealthCheck_withSearchString
    --- PASS: TestAccAWSRoute53HealthCheck_withSearchString (28.07s)
    === RUN   TestAccAWSRoute53HealthCheck_withChildHealthChecks
    --- PASS: TestAccAWSRoute53HealthCheck_withChildHealthChecks (20.71s)
    === RUN   TestAccAWSRoute53HealthCheck_IpConfig
    --- PASS: TestAccAWSRoute53HealthCheck_IpConfig (16.09s)
    === RUN   TestAccAWSRoute53HealthCheck_CloudWatchAlarmCheck
    --- PASS: TestAccAWSRoute53HealthCheck_CloudWatchAlarmCheck (22.42s) PASS
    ok  	github.com/hashicorp/terraform/builtin/providers/aws	132.568s
    ```

### CODE REVIEW

File: builtin/providers/aws/resource_aws_route53_health_check.go [hunk 1]
```diff
@@ -253,8 +258,15 @@ func resourceAwsRoute53HealthCheckCreate(d *schema.ResourceData, meta interface{
 		}
 	}
 
+	callerRef := resource.UniqueId()
+	if v, ok := d.GetOk("reference_name"); ok {
+		callerRef = strings.Join([]string{
+			v.(string), "-", callerRef,
+		}, "")
```
Comment (catsby) [inline builtin/providers/aws/resource_aws_route53_health_check.go]: minor nit: `callerRef = fmt.Sprintf("%s-%s", v.(string), callerRef)`

Comment (stack72) [inline builtin/providers/aws/resource_aws_route53_health_check.go]: you are correct - this is better :)
