### PR TITLE
fix panic when import id is empty string

### LINKED ISSUE #33389: Import block documentation does not provide information regarding for_each import
### Terraform Version

```shell
1.5.0
```

### Affected Pages

https://github.com/hashicorp/terraform/blob/main/website/docs/cli/import/index.mdx

### What is the docs issue?

In the import_block documentation we can read: 

The below example shows how to import a resource that includes [for_each](https://developer.hashicorp.com/terraform/language/meta-arguments/for_each).
```
import {
  to = aws_instance.example["foo"]
  id = "i-abcd1234"
}
```

But the example does not provide any information regarding for_each 

### Proposal

An example with the use of for_each (I tried to figured out myself but I ended with 

```
│ An argument named "for_each" is not expected here.
```

when doing something like
```
import {
for_each = toset(["name1", "name2"])
id = each.key
to = module.my_module.gitlab_project.projects[each.key]
}
```

### References

_No response_

### LINKED ISSUE #33505: Import block with id of "" causes plan to error
Undefined behaviour when an `import` block `id` is empty string `""`.

An empty import ID is not valid, and Terraform should print a friendly error message in this case.

### Config

```hcl
import {
  to = null_resource.foo
  id = ""
}
```

#### Normal plan

```
$ terraform plan

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Resource has no configuration
│ 
│ Terraform attempted to process a resource at null_resource.foo that has no configuration. This is a bug in Terraform; please report it!
╵
```

#### Genconfig plan

```
$  terraform plan -generate-config-out=t.tf

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 101 [running]:
runtime/debug.Stack()
	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/debug/stack.go:16 +0x1c
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/Users/katy/dev/go/src/github.com/hashicorp/terraform/internal/logging/panic.go:58 +0x170
panic({0x104813ba0, 0x105fa1fc0})
	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/panic.go:890 +0x258
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).managedResourceExecute(0x140009a20b0, {0x104c16018, 0x140004cc7e0})
	/Users/katy/dev/go/src/github.com/hashicorp/terraform/internal/terraform/node_resource_plan_instance.go:288 +0xf30
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).Execute(0x0?, {0x104c16018?, 0x140004cc7e0?}, 0x80?)
	/Users/katy/dev/go/src/github.com/hashicorp/terraform/internal/terraform/node_resource_plan_instance.go:74 +0x7c
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0x14000b25200, {0x104c16018, 0x140004cc7e0}, {0x10e10ecd0, 0x140009a20b0})
	/Users/katy/dev/go/src/github.com/hashicorp/terraform/internal/terraform/graph_walk_context.go:143 +0xa8
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x104b83ce0, 0x140009a20b0})
	/Users/katy/dev/go/src/github.com/hashicorp/terraform/internal/terraform/graph.go:78 +0x238
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0x14000656120, {0x104b83ce0, 0x140009a20b0}, 0x14000674200)
	/Users/katy/dev/go/src/github.com/hashicorp/terraform/internal/dag/walk.go:384 +0x2e0
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
	/Users/katy/dev/go/src/github.com/hashicorp/terraform/internal/dag/walk.go:307 +0xbf0
```

### Expected behaviour

A nicer error message.

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
We can only detect this during evaluation since the import id is an hcl expression

Fixes #33505

## Target Release

1.7.x

### BUG FIXES

 

- throw helpful error message if import block is configured with id ""

### CODE REVIEW

File: internal/terraform/eval_import.go [hunk 1]
```diff
@@ -72,6 +72,15 @@ func evaluateImportIdExpression(expr hcl.Expression, ctx EvalContext, keyData in
 		})
 	}
 
+	if importId == "" {
+		return "", diags.Append(&hcl.Diagnostic{
+			Severity: hcl.DiagError,
+			Summary:  "Invalid import id argument",
+			Detail:   fmt.Sprintf("The import ID value is \"\", please provide a valid value."),
```
Comment (liamcervante) [inline internal/terraform/eval_import.go:79]: You don't need the `fmt.Sprintf` here since we're not interpolating anything.

Maybe we could change this to say something like: "The import ID value evaluates to an empty string, please provide a non-empty value". I think that might make it clearer in case people are looking at it and not realising an empty string is coming from several nested/hidden references?

**Review by liamcervante — APPROVED** [review]
Looks good! I think this can be backported as well.
