### PR TITLE
Resource value may be an object in self evaluation

### LINKED ISSUE #23194: Crashing for_each/self regression introduced by #22846
### Terraform Version

```
Terraform v0.12.12
+ provider.random v2.2.1
```

### Terraform Configuration Files

Trivial test case:

```hcl
resource "random_pet" "test" {
    for_each = toset(["testcase"])

    provisioner "local-exec" {
        command = "echo pet name is ${self.id}"
    }
}
```

### Debug Output

[debug.log](https://github.com/hashicorp/terraform/files/3774733/debug.log)

### Crash Output

[crash.log](https://github.com/hashicorp/terraform/files/3774734/crash.log)

### Expected Behavior

Terraform completes without crashing: the `local-exec` provisioner run successfully, printing `pet name is ${self.id}`.

### Actual Behavior

Terraform panics whilst resolving `self.id`:

```
panic: not a list, map, or tuple type
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context

The above test case is simply the most trivial I've found to reproduce the crash which is easily reproducible with multiple providers, and with increasingly complex `for_each` loops. Terraform will crash whenever `self` is referenced within a provisioner. In particular, it has introduced a blocking issue for us with the `vsphere.vmware_virtual_machine` provider with which we use a `for_each = {…}` map. 

### References

- #22846 introduced the regression.
- #23191 is almost certainly a duplicate of this issue.

### PR DESCRIPTION
**Pull request by jbardin**
The fallback type for `GetResource` from an `EachMap` is a `cty.Object`,
because resource schemas may contain dynamically typed attributes.
Check for an Object type in the evaluation of self, to use the proper
`GetAttr` method when extracting the value.

Fixes #23194

### CODE REVIEW

File: lang/eval.go [hunk 1]
```diff
@@ -244,11 +244,17 @@ func (s *Scope) evalContext(refs []*addrs.Reference, selfAddr addrs.Referenceabl
 			case addrs.IntKey:
 				self = val.Index(cty.NumberIntVal(int64(k)))
 			case addrs.StringKey:
-				self = val.Index(cty.StringVal(string(k)))
+				switch {
```
[the remark this answers is not in the document]
Comment (jbardin) [reply lang/eval.go]: Switch to `hcl.Index`, if only for the possible better diagnostics if we somehow get an invalid  self index.

File: lang/eval.go [hunk 2]
```diff
@@ -240,15 +240,17 @@ func (s *Scope) evalContext(refs []*addrs.Reference, selfAddr addrs.Referenceabl
...
+			var hclDiags hcl.Diagnostics
 			switch k := subj.Key.(type) {
 			case addrs.IntKey:
-				self = val.Index(cty.NumberIntVal(int64(k)))
+				self, hclDiags = hcl.Index(val, cty.NumberIntVal(int64(k)), ref.SourceRange.ToHCL().Ptr())
+				diags.Append(hclDiags)
 			case addrs.StringKey:
-				self = val.Index(cty.StringVal(string(k)))
+				self, hclDiags = hcl.Index(val, cty.StringVal(string(k)), ref.SourceRange.ToHCL().Ptr())
+				diags.Append(hclDiags)
```
Comment (apparentlymart) [inline lang/eval.go]: I'm pondering what happens if `hcl.Index` fails here.

It looks like it shouldn't happen because `val` should always be of a suitable type by the time we get here (or else we would've been panicking before anyway), so maybe not a big deal, but perhaps worth adding a comment to that effect anyway to assuage the concerns of future readers.

It looks like `hcl.Index` is consistent with the usual HCL convention that if it returns errors then it also returns an incomplete-but-valid placeholder value (`cty.DynamicVal`, in this case) so later code below will hopefully be okay with `self` being `cty.DynamicVal` and just short-circuit as normal and allow the error to be returned. Might therefore be okay to just add a comment here noting that we're not expecting this to return errors, but if it does then `self` will be `cty.DynamicVal`, in case that's helpful to a future maintainer.

Comment (jbardin) [reply lang/eval.go]: That matches my thoughts here too. I'm actually not sure which is better now, since in the rare case of an internal error making it this far we `panic` with the exact location. I'm still leaning towards collecting the error and passing it along for user ergonomics, so I'll just add another comment for now.

**Comment by vitobotta** [comment]
Hi @isometry so I can safely upgrade now? :)

**Comment by isometry** [comment]
> Hi @isometry so I can safely upgrade now? :)

Not yet. You should wait for the release of 0.12.13.
