### PR TITLE
Check that a named state in s3 doesn't exist before acquiring a lock

### LINKED ISSUE #14666: force-unlock doesn't work with S3 with non-default environment name
### Terraform Version
0.9.5, but verified to exist on master via code examination.

### Affected Resource(s)
- S3 Backend

### Terraform Configuration Files
n/a

### Debug Output
Skipping because the issue is easily verified by reading the code

### Panic Output
n/a

### Expected Behavior
You should be able to use `force-unlock` with an S3 backend with non-default env name

### Actual Behavior
```
 $ terraform force-unlock a18baa01-5c1e-3f7f-2a9d-cc0e12763872
Failed to load state: failed to lock s3 state: ConditionalCheckFailedException: The conditional request failed
	status code: 400, request id: T51HBI07V9KHKQEKPEL0OTP0O3VV4KQNSO5AEMVJF66Q9ASUAAJG
Lock Info:
  ID:        a18baa01-5c1e-3f7f-2a9d-cc0e12763872
  Path:      dev-meteor-terraform-state/env:/test-20170518221643/dev.tfstate
  Operation: OperationTypeApply
  Who:       glasser@glasser-lyrid-2.local
  Version:   0.9.5
  Created:   2017-05-18 22:16:49.76621217 +0000 UTC
  Info:      
```

### Steps to Reproduce
1. Set up S3 backend with DynamoDB locking
2. `terraform env new foo`
3. Start a slow Terraform command and kill it harshly (eg `kill -9`)
4. `terraform plan`, observe expected failure and lock ID
5. `terraform force-unlock LOCKID`

### Why it's happening
The force-unlock command calls `b.State`: https://github.com/hashicorp/terraform/blob/11279963a342174530f34cb7abd740ff214d4f23/command/unlock.go#L56

The S3 implementation of `State` takes out a lock any time that the environment name isn't the default state:
https://github.com/hashicorp/terraform/blob/11279963a342174530f34cb7abd740ff214d4f23/backend/remote-state/s3/backend_state.go#L106-L113

This is clearly not appropriate for the force-unlock command.

Pinging @jbardin who was recently recommended to me as the environment expert and who seems to have written all of this code.

### PR DESCRIPTION
**Pull request by jbardin**
In order to force-unlock a named state, we have to fetch that state first. Don't attempt to acquire a lock if we know the state already exists in s3.

Fixes #14666

### CODE REVIEW

**Comment by jbardin** [comment]
```
$ TF_ACC=1 go test -v
=== RUN   TestBackend_impl
--- PASS: TestBackend_impl (0.00s)
=== RUN   TestBackendConfig
--- PASS: TestBackendConfig (1.60s)
=== RUN   TestBackend
--- PASS: TestBackend (6.03s)
	backend_test.go:248: creating S3 bucket terraform-remote-s3-test-591f3cfb in us-east-1
=== RUN   TestBackendLocked
--- PASS: TestBackendLocked (16.59s)
	backend_test.go:248: creating S3 bucket terraform-remote-s3-test-591f3d01 in us-east-1
	testing.go:222: TestBackend: testing state locking for *s3.Backend
=== RUN   TestBackendExtraPaths
--- PASS: TestBackendExtraPaths (6.62s)
	backend_test.go:248: creating S3 bucket terraform-remote-s3-test-591f3d11 in us-east-1
=== RUN   TestRemoteClient_impl
--- PASS: TestRemoteClient_impl (0.00s)
=== RUN   TestRemoteClient
--- PASS: TestRemoteClient (2.72s)
	backend_test.go:248: creating S3 bucket terraform-remote-s3-test-591f3d18 in us-east-1
=== RUN   TestRemoteClientLocks
--- PASS: TestRemoteClientLocks (8.49s)
	backend_test.go:248: creating S3 bucket terraform-remote-s3-test-591f3d1b in us-east-1
=== RUN   TestForceUnlock
--- PASS: TestForceUnlock (9.62s)
	backend_test.go:248: creating S3 bucket terraform-remote-s3-test-force-591f3d23 in us-east-1
PASS
ok  	github.com/hashicorp/terraform/backend/remote-state/s3	51.692s
```

File: backend/remote-state/s3/backend_state.go [hunk 1]
```diff
@@ -101,9 +101,29 @@ func (b *Backend) State(name string) (state.State, error) {
...
-	//it's listed by States.
-	if name != backend.DefaultStateName {
+	// Check to see if this state already exists.
+	// If we're trying to force-unlock a state, we can't take the lock before
+	// fetching the state. If the state doesn't exist, we have to assume this
+	// is a normal create operation, and take the lock at that point.
+	//
+	// If we need to force-unlock, but for some reason the state no longer
+	// exists, the user will have to use aws tools to manually fix the
+	// situation.
```
Comment (apparentlymart) [inline backend/remote-state/s3/backend_state.go]: I see this comment that says the user needs to fix this manually, but given that I'd also expect to see somewhere an error message explaining that to the user. Is that pre-existing somewhere and I just can't find it?

Comment (jbardin) [inline backend/remote-state/s3/backend_state.go]: No, there isn't any error message to go with this. 

The problem is there's no way that the backend can know here that the "State" is only going to be used to call `Unlock`. So we either have to create the key, and that's not safe without a lock. 

In practice, I don't think this will be a problem because this is a situation that "shouldn't happen", i.e. something has already gone horribly wrong and manual intervention is probably needed anyway.
