### PR TITLE
terraform test: move variable evaluation into the terraform test graph

### LINKED ISSUE #34629: Support `locals` block inside `tftest.hcl` Terraform Test file.
### Terraform Version

```shell
terraform version
Terraform v1.7.2
on darwin_arm64
```

### Use Cases

We don't want to repeat the same template string inside `tftest.hcl` Terraform Test file.

Please support `locals` block inside `tftest.hcl` Terraform Test file.

### Attempted Solutions

```terraform
locals {
  variable_name = "${run.setup_tests.variable_value_one}_${run.setup_tests.variable_value_two}"
}
```

```console
$ terraform init -backend=false && terraform test --verbose --verbose
Initializing modules...
╷
│ Error: Unsupported block type
│ 
│   on tests/main.tftest.hcl line 13:
│   13: locals {
│ 
│ Blocks of type "locals" are not expected here.
```

### Proposal

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by liamcervante**
This PR moves variable evaluation into the Terraform Test graph. This allows variables to reference other variables and run block outputs for the first time. Variable values are now just held in the evaluation context, and can be retrieved directly instead of needing to use the variable cache at all, so the variable cache has been deleted.

There is one test that must be skipped at the moment, because a follow up PR will add providers into the graph and there is a temporary breakage in behaviour until that PR has been completed.

Fixes #34629

### CODE REVIEW

File: internal/moduletest/graph/node_variable.go [hunk 1]
```diff
@@ -0,0 +1,160 @@
...
+func (n *NodeVariableExpression) References() []*addrs.Reference {
+	refs, _ := langrefs.ReferencesInExpr(addrs.ParseRefFromTestingScope, n.Expr)
+	return refs
+}
+
+func (n *NodeVariableExpression) Execute(ctx *EvalContext) {
+	refs, refDiags := langrefs.ReferencesInExpr(addrs.ParseRefFromTestingScope, n.Expr)
+
+	if !ctx.ReferencesCompleted(refs) {
+
```
Comment (dsa0x) [inline internal/moduletest/graph/node_variable.go:110]: would this not be an error if we encounter an expression whose references are missing?

File: internal/moduletest/graph/node_variable.go [hunk 2]
```diff
@@ -0,0 +1,160 @@
...
+	}
+
+	availableVariables := make(map[string]cty.Value)
+	for _, ref := range refs {
+		if input, ok := ref.Subject.(addrs.InputVariable); ok {
+			if variable := ctx.GetVariable(input.Name); variable != nil {
+				availableVariables[input.Name] = variable.Value
+			} else if variable, variableDiags := ctx.EvaluateUnparsedVariable(input.Name, nil); variable != nil {
+				refDiags = refDiags.Append(variableDiags)
+				availableVariables[input.Name] = variable.Value
```
Comment (dsa0x) [inline internal/moduletest/graph/node_variable.go:130]: If the graph is properly ordered, and perhaps this reference is for a variable definition or expression, then a node for that reference should have been resolved at this point. Why would we need this condition?

File: internal/moduletest/graph/transform_config.go [hunk 3]
```diff
@@ -88,7 +88,7 @@ func TransformConfigForRun(ctx *EvalContext, run *moduletest.Run, file *modulete
 				AliasRange: ref.InChild.AliasRange,
 				Config: &hcltest.ProviderConfig{
 					Original:            testProvider.Config,
-					VariableCache:       ctx.VariableCache,
+					AvailableVariables:  ctx.Variables(),
```
Comment (dsa0x) [inline internal/moduletest/graph/transform_config.go:91]: I think this map may need some synchronization protection

File: internal/moduletest/graph/variables.go [hunk 4]
```diff
@@ -53,13 +53,18 @@ func (n *NodeTestRun) GetVariables(ctx *EvalContext, includeWarnings bool) (terr
...
 
 		refs, refDiags := langrefs.ReferencesInExpr(addrs.ParseRefFromTestingScope, expr)
 		for _, ref := range refs {
 			if addr, ok := ref.Subject.(addrs.InputVariable); ok {
-				if value, valueDiags := ctx.VariableCache.GetVariableValue(addr.Name); value != nil {
+				if value := ctx.GetVariable(addr.Name); value != nil {
+					requiredValues[addr.Name] = value.Value
+					continue
+				}
+				if value, valueDiags := ctx.EvaluateUnparsedVariable(addr.Name, run.ModuleConfig.Module.Variables[addr.Name]); value != nil {
```
Comment (dsa0x) [inline internal/moduletest/graph/variables.go:67]: ~Same question I asked earlier. Shouldn't these references have been resolved before we get here?~

I see that the config here is coming from the module configuration. What if we add those variables into the graph as a `VariableDefinition`?

**Review by dsa0x — COMMENTED** [review]
Looks good 👍 , but I have some questions

File: .changes/v1.13/ENHANCEMENTS-20250604-102932.yaml [hunk 5]
```diff
@@ -0,0 +1,5 @@
+kind: ENHANCEMENTS
+body: '`terraform test`: File-level variable blocks can now reference run outputs and other variables."'
```
Comment (dsa0x) [inline .changes/v1.13/ENHANCEMENTS-20250604-102932.yaml:2]: What benefit do we bring by allowing them to reference run output(s)? I think referencing variable definitions and expressions make sense, but run references can lead to confusing configuration

Comment (liamcervante) [reply .changes/v1.13/ENHANCEMENTS-20250604-102932.yaml:2]: User's have asked for this behaviour. If you have a run block that outputs something that future run blocks need, it is easier if you can wrap that output up into an automatic variable that future run blocks will pick up, instead of having to rewrite that variable out into each of the following run blocks.

It's like this:

```
variables {
  value = run.setup.value
}

run "setup" {
 # ...
}

run "step_one" {
  # this implicitly picks up `var.value` as it is defined at the file level.
}

run "step_two" {
  # this implicitly picks up `var.value` as it is defined at the file level.
}
```


vs this:

```
run "setup" {
 # ...
}

run "step_one" {
  variables {
    value = run.setup.value
  }
}

run "step_two" {
  variables {
    value = run.setup.value
  }
}
```

In the second example, we have to write out the variables for each one. It's not that bad for a simple primitive but if the variable they want to construct is a complex object is much easier for them to just do it once instead of repeatedly.

File: internal/moduletest/graph/transform_config.go (hunk 3 above)
Comment (liamcervante) [reply internal/moduletest/graph/transform_config.go:91]: there is a lock inside the `Variables` function, and it returns a new map every time so I think this should be okay? This basically just gives it a snapshot of all available variables at the current point in time.

File: internal/moduletest/graph/variables.go (hunk 4 above)
Comment (liamcervante) [reply internal/moduletest/graph/variables.go:67]: Yeah, so the problem with this is that we basically allow users to just provide "external" variables into the testing framework without definitions. I've called them unparsed variables here, as at this point they are essentially just the raw values of variables arriving from either external files, environment variables, or CLI flags.

These external variables are then interpreted differently depending on when they're needed. This makes sense as a particular run block might have a configuration for a variable that it is expecting, and then it's really good that the testing framework just makes the external variables available to that run block without forcing the user to put them in somewhere in the testing file.

But, we did make a (probably bad) decision early on to just let people reference these in the testing file itself, and that's what you're seeing in the place you made the other comment. With the optional variable blocks introduced earlier, we can make people declare what they're using in the test file but we don't want breaking changes by forcing people to do this.

What this means is that we have these unparsed / external variables that are just hanging around and being lazily evaluated. We could add specific nodes into the graph for them, but we'd have to add nodes for the cross product of each run block with each unparsed variable when they're only going to be referenced once anyway.

One short-term solution, could be to reintroduce the variable cache we had before that makes sure these are only evaluated once lazily. 

A possible long term solution, might be to add a warning / deprecation notice that says "we're going to stop this behaviour soon, you must add variable definition blocks if you want to do this". Then in 2-3 Terraform versions actually come in and break it.

But, we could do either of those in a follow up PR - what do you think?

File: internal/moduletest/graph/node_variable.go (hunk 2 above)
Comment (liamcervante) [reply internal/moduletest/graph/node_variable.go:130]: I've added a longer reply on the other comment, which I think addresses this as well.

File: internal/moduletest/graph/node_variable.go (hunk 1 above)
Comment (liamcervante) [reply internal/moduletest/graph/node_variable.go:110]: In this case, we're not checking that references are missing. A reference to a variable that doesn't exist is ignored by this check - the idea being that the current node will provide a more detailed error about that later. What this check is doing is checking that all the references were successful, so if a previous run block or variable errored or was skipped then this one should be skipped without trying to evaluate it since it will definitely error with a confusing message.

That's not the same as this one erroring - which it should do later if a reference that it requires doesn't exist.

File: internal/moduletest/graph/variables.go (hunk 4 above)
Comment (dsa0x) [reply internal/moduletest/graph/variables.go:67]: Thanks for the detailed explanation. It makes sense to me to make that decision in another PR. The deprecation notice would be nice, even if it takes longer than 2-3 versions to get it removed.

**Review by dsa0x — APPROVED** [review]
