### PR TITLE
cloud: `terraform output` should gracefully handle 503 errors

### LINKED ISSUE #35105: terraform output not display the outputs
### Terraform Version

```shell
Terraform v1.8.2
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.30.0
+ provider registry.terraform.io/hashicorp/aws v5.47.0
+ provider registry.terraform.io/hashicorp/external v2.3.3
```

### Terraform Configuration Files

Relevant parts are:

In a root module:

```
output "a" {
  value = module.terraform-module-ou.a
}

output "b" {
  value = "from root module"
}
```

In a submodule:

```
output "a" {
  value = "from module"
}
```

### Debug Output

I run terraform apply and then a terraform output and see this:

```

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

a = "from module"
b = "from root module"
doylands@HGRSDELTCG30106:~$ terraform output
╷
│ Warning: No outputs found
│
│ The state file either has no outputs defined, or all the defined outputs are empty. Please define an output in your configuration with the `output` keyword and run `terraform refresh` for it to become
│ available. If you are using interpolation, please verify the interpolated value is not empty. You can use the `terraform console` command to assist.
```

### Expected Behavior

The outputs should be displayed

### Actual Behavior

terraform says there are no outputs.

### Steps to Reproduce

terraform apply
terraform output

### Additional Context

I can see the state file has the outputs:

```
{
  "version": 4,
  "terraform_version": "1.8.2",
  "serial": 56,
  "lineage": "1cf6b725-b0a4-0b5f-915f-963481c8eca4",
  "outputs": {
    "a": {
      "value": "from module",
      "type": "string"
    },
    "b": {
      "value": "from root module",
      "type": "string"
    }
  },
```

### References

_No response_

### PR DESCRIPTION
**Pull request by brandonc**
Fixes #35105

When outputs are not available while using cloud backend, terraform will now silently retry while logging attempts. If retries are canceled or time out after one minute, an error is displayed (See below for screenshots)

## Target Release

1.9.x

### ENHANCEMENTS

- `terraform output` with cloud block: terraform no longer suggests that data loss could occur when outputs are not available

## Screenshots

Before:
Screenshot 2024-05-02 at 4 24 40 PM

After (With TF_LOG, canceled):
Screenshot 2024-05-06 at 11 21 45 AM

After (With TF_LOG, deadline exceeded):
Please note the actual message says "within the deadline" not actually "within the timeout"
Screenshot 2024-05-06 at 11 21 36 AM

### CODE REVIEW

File: internal/cloud/retry.go [hunk 1]
```diff
@@ -0,0 +1,106 @@
...
+			}
+
+			err := f()
+			done := false
+			switch e := err.(type) {
+			case nil:
+				done = true
+			case Fatal:
+				errVal.Store(errWrap{e.FatalError()})
+				done = true
```
Comment (jbardin) [inline internal/cloud/retry.go:71]: Maybe return immediately and avoid the `done` variable?

**Review by jbardin — APPROVED** [review]

File: internal/cloud/retry.go (hunk 1 above)
Comment (yemibox51) [reply internal/cloud/retry.go:71]: As a suggestion, would this be clear and concise?
```go
switch e := err.(type) {
case Fatal:
  errVal.Store(errWrap{e.FatalError()})
  fallthrough
case nil:
   return
}
```
