### PR TITLE
Fixes for ignore_changes with unintended provider behavior

### LINKED ISSUE #27097: TF 0.14.0 ignores "ignore_changes" block
### Summary

Terraform 0.14.0 ignores lifecycle block ignore_changes in modules. So far I have only tested aws_instance within a module to see this behavior, but expect it's ignored in other resources. You can help improve this bug report by testing other resource builds in modules and verifying if ignore_changes is respected. 

### Terraform Version

```
Terraform v0.14.0
+ provider registry.terraform.io/hashicorp/aws v3.19.0
```

### Terraform Configuration Files

```terraform
lifecycle {
    ignore_changes = [
      user_data,
      tags["SSM Status"],
      tags["OS Type"],
      tags["OS Name"],
      tags["OS Version"],
    ]
  }
```

I tested different syntaxes, like wrapping these attributes in different styles of quotes, or using `ignore_changes = all` without any change in Terraform behavior. 

### Expected Behavior

Expected Terraform to respect ignore_changes, as 0.13.X Terraform does. 

### Actual Behavior

Terraform doesn't respect ignore_changes. This leads to unexpected impacts when upgrading to 0.14.X. 

```
      ~ tags                         = {
          ~ "OS Name"           = "Microsoft Windows Server 2016 Datacenter" -> ""
          ~ "OS Type"           = "Windows" -> ""
          ~ "OS Version"        = "10.0.14393" -> ""
          ~ "SSM Status"        = "Managed" -> ""
            # (12 unchanged elements hidden)
        }
      - user_data                    = "ae1a2d404aa5d578a1dde597a17b89cd4dadb283" -> null # forces replacement
```

### Steps to Reproduce

1. Create ec2 resource in AWS using terraform (of any version) with a lifecycle `ignore_change` block. 
2. Modify the item manually or using another tool. 
3. Run a `terraform plan` using TF 0.14.0 version and note that Terraform wants to revert the attribute it should be ignoring

### LINKED ISSUE #27103: 0.14: Broken state file compatibility: RFC3339 Timestamp Format errors in aws_s3_bucket
### Terraform Version

```
Terraform v0.14.0
+ provider registry.terraform.io/hashicorp/aws v3.19.0
```

### Terraform Configuration Files

```terraform
resource aws_s3_bucket bucket {
  for_each = local.machines

  bucket = each.key
  acl    = "private"
  tags   = each.value.tags

  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm = "AES256"
      }
    }
  }

  # We have to ignore this as Arq manages its own lifecycle policies.
  lifecycle {
    ignore_changes = [
      lifecycle_rule,
    ]
  }
}
```

### Debug Output

Edit: Added this small bit of debug output to show AWS returning correct data.

```
2020-12-03T10:59:29.417Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5: 2020/12/03 10:59:29 [DEBUG] S3 bucket: the-bucket-name, read lifecycle rule: {
2020-12-03T10:59:29.417Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5:   ID: "Arq S3Glacier Lifecycle Policy DO NOT MODIFY",
2020-12-03T10:59:29.417Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5:   Prefix: "glacier/",
2020-12-03T10:59:29.417Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5:   Status: "Enabled",
2020-12-03T10:59:29.417Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5:   Transitions: [{
2020-12-03T10:59:29.417Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5:       Days: 0,
2020-12-03T10:59:29.417Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5:       StorageClass: "GLACIER"
2020-12-03T10:59:29.417Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5:     }]
2020-12-03T10:59:29.417Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5: }
```

A small snippet showing that AWS seems to be returning the correct information, there is no `""` set in the `date` field here. (See: Additional Context)

### Expected Behavior

I should have been able to execute a `terraform plan` on 0.14.0 with my 0.13.5 state and have it work with no changes.

### Actual Behavior

The following error is produced:

```
Error: "" cannot be parsed as RFC3339 Timestamp Format

  on modules/backups/bucket.tf line 2, in resource "aws_s3_bucket" "bucket":
   2: resource aws_s3_bucket bucket {
```

### Steps to Reproduce

`terraform plan` after updating to 0.14.0.

### Additional Context

If I had to guess, this is happening due to the ignored lifecycle rules. Looking at those rules in the tfstate shows the following:

```json
            "lifecycle_rule": [
              {
                "abort_incomplete_multipart_upload_days": 0,
                "enabled": true,
                "expiration": [],
                "id": "Arq S3Glacier Lifecycle Policy DO NOT MODIFY",
                "noncurrent_version_expiration": [],
                "noncurrent_version_transition": [],
                "prefix": "glacier/",
                "tags": {},
                "transition": [
                  {
                    "date": "",
                    "days": 0,
                    "storage_class": "GLACIER"
                  }
                ]
              },
              {
                "abort_incomplete_multipart_upload_days": 0,
                "enabled": true,
                "expiration": [],
                "id": "Arq IA Lifecycle DO NOT MODIFY <a UUID was here>",
                "noncurrent_version_expiration": [],
                "noncurrent_version_transition": [],
                "prefix": "<a UUID was here>/",
                "tags": {},
                "transition": [
                  {
                    "date": "",
                    "days": 30,
                    "storage_class": "STANDARD_IA"
                  }
                ]
              }
            ],
```

The transition `date` is set to `""` in all of the buckets that show this error.

### LINKED ISSUE #27106: `ignore_changes = all` causes computed fields to be ignored, which the legacy SDK cannot properly validate
### Terraform Version
```
Terraform v0.14.0
+ provider registry.terraform.io/hashicorp/aws v3.19.0
```

### Terraform Configuration Files

```terraform
resource "aws_route53_record" "my_new_dns" {
  zone_id = "ZXXXXXXXX"
  name    = "my.example.com."
  type    = "CNAME"
  ttl     = "300"

  records = ["another.example.com."]
  lifecycle {
    ignore_changes = all
  }
}
```

### Expected Behavior

Terraform plan should run without errors.  

### Actual Behavior

This is the error that appears. 

> Error: Computed attribute cannot be set

>   on main.tf line 1, in resource "aws_route53_record" "my_new_dns":
   1: resource "aws_route53_record" "my_new_dns" {

> Error: Invalid or unknown key

>   on main.tf line 1, in resource "aws_route53_record" "my_new_dns":
   1: resource "aws_route53_record" "my_new_dns" {

### Steps to Reproduce

Copy my configuration above.  Substitute values for your own Route 53 Zone.  

    terraform plan  
    terraform apply  

After applying, run the plan again

    terraform plan

The errors appear.  

### Additional Context

Similar problem seen with `aws_service_discovery_public_dns_namespace` - even if I have hardcoded values. 

```
resource "aws_service_discovery_public_dns_namespace" "my-example-svc" {
  name = "svc.example.com"
  description = "DNS namespace for Service Discovery"
  lifecycle {
    ignore_changes = all
  }
}
```

### PR DESCRIPTION
**Pull request by jbardin**
This covers 3 separate, but related issues that are interacting badly with `ignore_changes` and legacy providers. 

The first is a more straightforward bug, where multiple entries for map keys in `ignore_changes` could cause `cty.Transform` to return early, leaving some values unchanged. Refactor the function to try and separate the fast-path a little better,
and hopefully make it easier to follow.

The second is a side effect of some incorrect provider behavior, but we need to work with it to remain compatible with the legacy SDK. Because we allow legacy providers to depart from the contract and return changes to non-computed values, the plan response may have altered values that were already suppressed with ignore_changes. A prime example of this is where providers attempt to obfuscate config data by turning the config value into a hash and storing the hash value in the state. There are enough cases of this in existing providers that we must accommodate the behavior for now, so for ignore_changes to work at all on these values we re-apply `ignore_changes` to the planned state. 

The effect of this will be limited by the `LegacyTypeSystem` flag, so as not to introduce more unintended `ignore_changes` behavior with new providers. The primary use case above won't be able to happen with providers using a new SDK, because returning a non-conforming plan will be an error. 

The third issue concerns the use of the `ignore_changes = all` option, which when applied to the configuration will currently cause computed values to be populated into the temporary config value. This isn't a problem when generating the plan, but does effect providers' validation, as the legacy provider schema will reject these values. We can work around this by validating the original config before applying `ignore_changes`. 

(In the future it we should probably have a way for `processIgnoreChanges` to skip computed values based on the schema. Since we also want a way to more easily query the schema for "computed-ness" to statically validate the `ignore_changes` arguments, we can fix these at the same time in a future change. This will most likely require some sort of method to retrieve info from the `configschema.Block` via a `cty.Path`, which we cannot easily do right now.)

Fixes #27106
Fixes #27103
Fixes #27097

### CODE REVIEW

File: terraform/eval_diff.go [hunk 1]
```diff
@@ -322,6 +325,23 @@ func (n *EvalDiff) Eval(ctx EvalContext) tfdiags.Diagnostics {
 		}
 	}
 
+	if resp.LegacyTypeSystem {
+		// Because we allow legacy providers to depart from the contract and
+		// return changes to non-computed values, the plan response may have
+		// altered values that were already suppressed with ignore_changes.
+		// A prime example of this is where providers attempt to obfuscate
```
Comment (mildwonkey) [inline terraform/eval_diff.go:332]: thank you for providing a "good" example in the comments, this is really helpful

**Review by mildwonkey — APPROVED** [review]
You're always good at this, but can I just say this PR has exceptionally good comments, thank you 🎉
