### PR TITLE
command: refresh state in old commands for backend

### LINKED ISSUE #12148: Experimental remote backend feature seems to break "taint" and "state" commands
### Terraform Version
`Terraform v0.9.0-dev`
`commit: 757b83aeebffa9c19ea3982ed62124511b910ff2`

### Expected Behavior
When using a remote backend (in my case, it is consul) commands such as `taint`, and `state` should work without having to pass a "-state" flag. They should also work if you do pass a state flag.

### Actual Behavior
`terraform state list` output:

```
$ terraform state list
[WARN] /Users/tomwganem/go/bin/terraform-provider-softlayer overrides an internal plugin for softlayer-provider.
  If you did not expect to see this message you will need to remove the old plugin.
  See https://www.terraform.io/docs/internals/internal-plugins.html
No state file was found!

State management commands require a state file. Run this command
in a directory where Terraform has been run or use the -state flag
to point the command to a specific state location.
```
`terraform state list -state terraform.tfstate.backup` output:

```
$ terraform state list -state terraform.tfstate.backup
[WARN] /Users/tomwganem/go/bin/terraform-provider-softlayer overrides an internal plugin for softlayer-provider.
  If you did not expect to see this message you will need to remove the old plugin.
  See https://www.terraform.io/docs/internals/internal-plugins.html
No state file was found!

State management commands require a state file. Run this command
in a directory where Terraform has been run or use the -state flag
to point the command to a specific state location.
```

`terraform taint` output
```
$ terraform taint chef_environment.environment
[WARN] /Users/tomwganem/go/bin/terraform-provider-softlayer overrides an internal plugin for softlayer-provider.
  If you did not expect to see this message you will need to remove the old plugin.
  See https://www.terraform.io/docs/internals/internal-plugins.html
The state is empty. The most common reason for this is that
an invalid state file path was given or Terraform has never
 been run for this infrastructure. Infrastructure must exist
for it to be tainted.
```

### Steps to Reproduce
1. set a backend for your terraform project
```
terraform {

  backend "consul" {
    path =  "files/dev/terraform"
  }
}
```

and have any number of resources

```
resource "chef_environment" "environment" {
  name                     = "${var.mesos_config["chef_environment_name"]}"
  override_attributes_json = "${data.template_file.override.rendered}"
  default_attributes_json  = "${data.template_file.default.rendered}"
  cookbook_constraints     = "${module.cookbook_versions.berksfile}"
}
```

2. `terraform init`

```
$ terraform init
[WARN] /Users/tomwganem/go/bin/terraform-provider-softlayer overrides an internal plugin for softlayer-provider.
  If you did not expect to see this message you will need to remove the old plugin.
  See https://www.terraform.io/docs/internals/internal-plugins.html
Downloading modules (if any)...
Get: file:///Users/tomwganem/Development/tf-files/aspera-files
Get: file:///Users/tomwganem/Development/as-mesos-?terrterraform/softlayer
Get: file:///Users/tomwganem/Development/cookbook-aspera-files
Initializing the backend...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your environment. If you forget, other
commands will detect it and remind you to do so if necessary.
```

3. `terraform apply`

```
module.aspera-files.chef_environment.environment: Creating...
...
```

4. `terraform state list ` or `terraform taint ${resource}`. Specifying a state file doesn't matter

```
$ terraform state list -state  terraform.tfstate.backup
[WARN] /Users/tomwganem/go/bin/terraform-provider-softlayer overrides an internal plugin for softlayer-provider.
  If you did not expect to see this message you will need to remove the old plugin.
  See https://www.terraform.io/docs/internals/internal-plugins.html
No state file was found!

State management commands require a state file. Run this command
in a directory where Terraform has been run or use the -state flag
to point the command to a specific state location.
```

### PR DESCRIPTION
**Pull request by mitchellh**
Fixes #12148 

The Backend API doesn't automatically `RefreshState` for you like the old Meta State API did. We have to manually do this across all commands.

I considered making it a requirement to do a refresh but we call State() multiple times on a backend and the point of _not_ refreshing it was so that calling State() was cheap. I think its worth it to keep it that way.

### CODE REVIEW

File: terraform/context.go [hunk 1]
```diff
@@ -207,6 +207,7 @@ func (c *Context) Graph(typ GraphType, opts *ContextGraphOpts) (*Graph, error) {
 		opts = &ContextGraphOpts{Validate: true}
 	}
 
+	log.Printf("[INFO] terraform: building graph: %s", typ)
```
Comment (mitchellh) [inline terraform/context.go]: Just added this while we're here since the debug log was unclear what graph was being built. The old graph builders used to do this.

**Comment by jbardin** [comment]
If `Backend.State` is not guaranteed to load the state, which is how it's documented in the interface comments, I think we should make the `Local` backend follow this as strictly as possible too. For example, if I remove the automatic "sanity check" `RefreshState` call from `Local.State()`, we get more state command test failures (though some may simply be failures in tests themselves, I haven't checked). 

Having the most commonly used Local backend instance follow the spec as strictly as possible helps ensure that we don't get any divergence with remote backends which are inherently less tested.

**Comment by mitchellh** [comment]
@jbardin This is a really good idea, doing it now.

**Comment by mitchellh** [comment]
@jbardin Done. The actual number of test failures was "0" in the sense that the failures introduced were actually in the tests themselves. The logic is sound after this PR. Pushed the last commit!
