### PR TITLE
command: adjust exit code of state rm

### LINKED ISSUE #17800: terraform state rm always displays success message as long as you give it a "valid" resource name
### Terraform Version

```
Terraform v0.11.5
```

### Terraform Command

```
$ terraform state rm foo.bar
1 items removed.
Item removal successful.
```
### Expected Behavior

Terraform should give me an error saying the resource does not exist. 

### Actual Behavior

Terraform says it removed 1 item successfully.

### Steps to Reproduce

In any folder, even one that does not contain state run `terraform state rm random_type.random_name`. If there's no `.` Terraform will complain:
```
$ terraform state rm foo
Error removing items from the state: Error parsing address 'foo': invalid resource address "foo"
```
but beyond that it always prints the success message.

### PR DESCRIPTION
**Pull request by jgpacker**
Commands `state rm` will now exit with code 1 when the resource is not found in the current state.
This is consistent with `terraform state show non_existent_resource`.

Fixes #17800

### CODE REVIEW

**Comment by jgpacker** [comment]
Thank you for the feedback. I will correct this soon

**Comment by jgpacker** [comment]
I have updated the code according to the feedback. Unfortunately I have not been able to test it locally because of issues related to limited disk space. So there might be still be some adjustments to be done. Thank you in advance for the review

File: command/state_mv.go [hunk 1]
```diff
@@ -353,13 +353,19 @@ func (c *StateMvCommand) Run(args []string) int {
...
 
-	c.showDiagnostics(diags)
-
 	if moved == 0 {
-		c.Ui.Output("No matching objects found.")
-	} else {
-		c.Ui.Output(fmt.Sprintf("Successfully moved %d object(s).", moved))
+		diags = diags.Append(tfdiags.Sourceless(
+			tfdiags.Error,
+			"Invalid target address",
```
Comment (pselle) [inline command/state_mv.go]: I should've noted this in prior review, but `msgInvalidTarget` is a constant in this file we can use instead of this string literal

**Comment by jgpacker** [comment]
@pselle I opened this PR only to fix `state rm`, but I wanted to make sure other `state` subcommands were consistent with this behavior. I changed `state mv` because there is an `if` related to this condition, but I'm not sure how to reproduce it in this case.
I would not be surprised if this condition is not reached at this moment.
Should we remove this condition? Make the error message more generic?
What do you suggest?

**Comment by pselle** [comment]
Ah in that case (if you haven't been able to replicate through with `state mv` and the goal was `state rm` with `mv` being a "while I'm here...") I would suggest we only fix `state rm` and leave `mv` be. That follows the line of keeping a change focused and tested, so while `mv` might have some tricky bits in it, if changing it is not our goal, we should leave it unchanged and leave that for future work :)

**Comment by jgpacker** [comment]
Thank you for the orientation. I have reverted the changes in `state_mv`. Please review again
