### PR TITLE
Requires replace should not error on missing index steps

### LINKED ISSUE #20294: Requires replacement on removed list block
If an attribute within a list block requires replacement, and the block is removed from the config, the path to the attribute triggering the replacement can't be applied to the new state. The paths are constructed based on the prior state, so this results in an error like:

        Error: Provider produced invalid plan

        Provider "aws" has indicated "requires replacement" on
        aws_batch_job_definition.test for a non-existent attribute path
        cty.Path{cty.GetAttrStep{Name:"retry_strategy"},
        cty.IndexStep{Key:cty.NumberIntVal(0)}, cty.GetAttrStep{Name:"attempts"}}.

### PR DESCRIPTION
**Pull request by jbardin**
RequiresReplace paths with IndexSteps that have been added or removed will fail to apply against one or the other state values. We were previously ignoring the error from apply the path to the `priorVal`, but this can happen in either direction.

Only fail if both values produce an error. In the case of a single error, make sure the other value is a valid Null of the correct type.

Fixes #20294

### CODE REVIEW

File: terraform/eval_diff.go [hunk 1]
```diff
@@ -256,12 +255,18 @@ func (n *EvalDiff) Eval(ctx EvalContext) (interface{}, error) {
...
-				// the same type, but we'll allow it for robustness.
-				reqRep.Add(path)
+
+			// make sure we have valid Values for both
+			switch {
+			case priorChangedVal == cty.NilVal && plannedChangedVal == cty.NilVal:
+				// this should never happen without ApplyPath errors above
+				panic("requires replace path returned 2 nil values")
+			case priorChangedVal == cty.NilVal:
+				priorChangedVal = cty.NullVal(plannedChangedVal.Type())
```
Comment (apparentlymart) [inline terraform/eval_diff.go]: In the case where the thing being changed contains `cty.DynamicPseudoType` attributes in its schema it is possible for the prior and planned to actually _not_ have the same type (contradicting the comment that used to be here, which was incorrect for a number of reasons :confounded: )

In think in this context it doesn't actually matter, since we're only using these values to run `Equals` below and that'll never show a null as equal to a non-null anyway, but maybe it's worth noting here that it's generally more correct to use the schema's implied type to create a null but we're intentionally not doing that here because we know it's safe, just because I worry that a future reader may read this and think it a good general usage example to copy elsewhere, in situations where the exact type of null may be important.

Comment (jbardin) [reply terraform/eval_diff.go]: Ah yes, that was intended here, since It was only for the comparison and I didn't want to traverse the schema to check for a dynamic type. I'll add the comment for our future selves so we don't rely on the type.
