### PR TITLE
provider/aws: Add tagging support to aws_redshift_subnet_group

### LINKED ISSUE #9492: AWS RedShift Subnet Group resource does not support tags
### Terraform Version
Terraform 0.7.7

### Affected Resource(s)
- aws_redshift_subnet_group

### Terraform Configuration Files
```hcl
resource "aws_redshift_subnet_group" "test" {
  name = "redshift_test"
  subnet_ids  =[ "${module.redshift_subnet.subnet_id}" ]
  tags {
    Name = "test_subnet"
    description = "Primary subnet for redshift"
    project = "test"
    managed_by = "Terraform"
  }
}
```

### Expected Behavior
Creates a RedShift subnet group with the specified tags.

### Actual Behavior
`invalid or unknown key: tags`

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
Tags on RedShift subnet groups are supported via the aws-cli as referenced at http://docs.aws.amazon.com/cli/latest/reference/redshift/create-cluster-subnet-group.html

### PR DESCRIPTION
**Pull request by stack72**
Fixes #9492

```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSRedshiftSubnetGroup_'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/10/21 17:16:02 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSRedshiftSubnetGroup_ -timeout 120m
=== RUN   TestAccAWSRedshiftSubnetGroup_importBasic
--- PASS: TestAccAWSRedshiftSubnetGroup_importBasic (86.54s)
=== RUN   TestAccAWSRedshiftSubnetGroup_basic
--- PASS: TestAccAWSRedshiftSubnetGroup_basic (85.50s)
=== RUN   TestAccAWSRedshiftSubnetGroup_updateSubnetIds
--- PASS: TestAccAWSRedshiftSubnetGroup_updateSubnetIds (140.01s)
=== RUN   TestAccAWSRedshiftSubnetGroup_tags
--- PASS: TestAccAWSRedshiftSubnetGroup_tags (136.02s)
PASS
ok	github.com/hashicorp/terraform/builtin/providers/aws	448.075
```

### CODE REVIEW

File: builtin/providers/aws/resource_aws_redshift_subnet_group.go [hunk 1]
```diff
@@ -24,25 +24,27 @@ func resourceAwsRedshiftSubnetGroup() *schema.Resource {
 		},
 
 		Schema: map[string]*schema.Schema{
-			"name": &schema.Schema{
+			"name": {
```
Comment (dennis-bsi) [inline builtin/providers/aws/resource_aws_redshift_subnet_group.go]: Help me understand why `&schema.Schema` was removed.  Simply because it's implied by the type?

File: builtin/providers/aws/resource_aws_redshift_subnet_group.go [hunk 2]
```diff
@@ -97,12 +101,25 @@ func resourceAwsRedshiftSubnetGroupRead(d *schema.ResourceData, meta interface{}
...
 func resourceAwsRedshiftSubnetGroupUpdate(d *schema.ResourceData, meta interface{}) error {
 	conn := meta.(*AWSClient).redshiftconn
+
+	arn, tagErr := buildRedshiftSubnetGroupARN(d.Id(), meta.(*AWSClient).partition, meta.(*AWSClient).accountid, meta.(*AWSClient).region)
+	if tagErr != nil {
+		return fmt.Errorf("Error building ARN for Redshift Subnet Group, not updating Tags for Subnet Group %s", d.Id())
+	} else {
+		if tagErr := setTagsRedshift(conn, d, arn); tagErr != nil {
+			return tagErr
+		} else {
```
Comment (kwilczynski) [inline builtin/providers/aws/resource_aws_redshift_subnet_group.go]: No need for branching with `else` as we have `return` above.

File: builtin/providers/aws/resource_aws_redshift_subnet_group.go [hunk 3]
```diff
@@ -97,12 +101,25 @@ func resourceAwsRedshiftSubnetGroupRead(d *schema.ResourceData, meta interface{}
 	d.Set("name", d.Id())
 	d.Set("description", describeResp.ClusterSubnetGroups[0].Description)
 	d.Set("subnet_ids", subnetIdsToSlice(describeResp.ClusterSubnetGroups[0].Subnets))
+	d.Set("tags", tagsToMapRedshift(describeResp.ClusterSubnetGroups[0].Tags))
```
Comment (kwilczynski) [inline builtin/providers/aws/resource_aws_redshift_subnet_group.go]: Should we check for an error (above too)?

File: builtin/providers/aws/resource_aws_redshift_subnet_group.go (hunk 1 above)
Comment (stack72) [inline builtin/providers/aws/resource_aws_redshift_subnet_group.go]: Yes, since Go 1.7 we have found this is no longer needed
