### PR TITLE
configs: Fix provider requirements panics

### LINKED ISSUE #25366: 0.13.0-beta2 crash report
### Terraform Version

``` 
Terraform v0.13.0-beta2
```

### Terraform Configuration Files

```
hcl https://1drv.ms/u/s!AjA715bdFDs48CF142ZuUVD1IpOW?e=7nuVZT
```

### Crash Output

Placed two crash logs with two different command line inputs to test if crash is repeatable.  It was.

### Steps to Reproduce

terraform init
### Additional Context

I am just learning Terraform and so may have invalid syntax.

### PR DESCRIPTION
**Pull request by alisdair**
When parsing provider requirements we should check the type of the source and version attributes rather than assuming that they are strings. Otherwise an invalid attribute value will cause a panic.

(Probably best reviewed ignoring whitespace.)

Fixes #25366

### CODE REVIEW

File: configs/provider_requirements.go [hunk 1]
```diff
@@ -55,41 +56,61 @@ func decodeRequiredProvidersBlock(block *hcl.Block) (*RequiredProviders, hcl.Dia
...
-				if err != nil {
-					// NewConstraint doesn't return user-friendly errors, so we'll just
-					// ignore the provided error and produce our own generic one.
+				constraint := expr.GetAttr("version")
+				if !constraint.Type().Equals(cty.String) || constraint.IsNull() {
 					diags = append(diags, &hcl.Diagnostic{
 						Severity: hcl.DiagError,
 						Summary:  "Invalid version constraint",
-						Detail:   "This string does not use correct version constraint syntax.",
+						Detail:   "Version must be specified as a string.",
```
Comment (pselle) [inline configs/provider_requirements.go:64]: Helpful additional error!
