### PR TITLE
core: Fix -module for terraform output command

### LINKED ISSUE #7840: No module output displayed  in v0.7.0-rc3
Hi there,

I've upgraded to terraform 0.7 and the output for a module is not being displayed via the command line even though it exists in the tfstate.

### Terraform Version

```
$ terraform version
Terraform v0.7.0-rc3 (3f4857a07a24f3c9e2db6b4458fbf5be19a8b256)
```

### Affected Resource(s)

Core

### Terraform Configuration Files

My module configuration `modules\database\main.tf` contains:

```
output "database.master" {
  value = "${join(",", openstack_compute_instance_v2.dbmaster.*.access_ip_v4)}"
}

output "database.slave" {
  value = "${join(",", openstack_compute_instance_v2.dbslave.*.access_ip_v4)}"
}
```

My main configuration then calls this module 

```
module "database" {
  source = "./modules/database"
  key_pair = "${var.key_pair}"
  subnet_id = "${var.subnet_id}"
  sshkey = "${var.sshkey}"
  ...
}
```

### Expected Behavior

`terraform output -module=database` should display some values.

### Actual Behavior

Nothing is displayed

```
$ terraform output -module=database

$
```

### Steps to Reproduce

Run `terraform apply`

```
$ terraform apply
module.database.openstack_compute_secgroup_v2.dbsecgroup: Refreshing state... (ID: 27977d8a-0a50-455a-b562-482f502XXX)
module.database.openstack_compute_instance_v2.dbslave: Refreshing state... (ID: 42f137c4-692d-4fac-9bae-a1d0ac51XXXX)
module.database.openstack_compute_instance_v2.dbmaster: Refreshing state... (ID: 73e95604-63bf-4efb-85e3-0a24695XXXX)

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

I see the following configuration in the `tfstate`:

```
    "modules": [
        {
            "path": [
                "root"
            ],
            "outputs": {},
            "resources": {}
        },
        {
            "path": [
                "root",
                "database"
            ],
            "outputs": {
                "database.master": {
                    "sensitive": false,
                    "type": "string",
                    "value": "1.2.3.4"
                },
                "database.slave": {
                    "sensitive": false,
                    "type": "string",
                    "value": "2.3.4.5"
                },
            },
```

But no output is displayed.

```
$ terraform output
The state file has no outputs defined. Define an output
in your configuration with the `output` directive and re-run
`terraform apply` for it to become available.
$ terraform output -module=database

$
```

### PR DESCRIPTION
**Pull request by jen20**
The behaviour whereby outputs for a particular nested module can be output was broken by the changes for lists and maps. This pull-request restores the previous behaviour by passing the module path into the `outputsAsString` function.

We also add a new test of this since the code path for indivdual output vs all outputs for a module has diverged.

Fixes #7840.

### CODE REVIEW

**Comment by jen20** [comment]
cc @phinze or @jbardin

File: terraform/state.go [hunk 1]
```diff
@@ -14,10 +14,9 @@ import (
 	"strings"
 
 	"github.com/hashicorp/go-version"
-	"github.com/satori/go.uuid"
-
 	"github.com/hashicorp/terraform/config"
 	"github.com/mitchellh/copystructure"
+	"github.com/satori/go.uuid"
```
Comment (jen20) [inline terraform/state.go]: This is just some tidying up in formatting that goimports picked up.

File: command/apply.go [hunk 2]
```diff
@@ -251,7 +251,7 @@ func (c *ApplyCommand) Run(args []string) int {
 	}
 
 	if !c.Destroy {
-		if outputs := outputsAsString(state, ctx.Module().Config().Outputs, true); outputs != "" {
+		if outputs := outputsAsString(state, []string{"root"}, ctx.Module().Config().Outputs, true); outputs != "" {
```
Comment (phinze) [inline command/apply.go]: Note for later: perhaps we should make `terraform.rootModulePath` an exported constant so we can reference from here.

**Comment by phinze** [comment]
LGTM

File: command/apply.go (hunk 2 above)
Comment (jen20) [inline command/apply.go]: Strong :+1: on that.

Comment (jen20) [inline command/apply.go]: Oh it is already. I'll update this commit soon.
