### PR TITLE
use `cty.DynamicVal` for expanded resources during validation

### LINKED ISSUE #30127: Terraform 1.1.0 lookup regression
After upgrading to terraform 1.1.0 from 1.0.11 following expression stopped working:
```
output "sg_id" {
  value = lookup(aws_security_group.lambda_default_sg, "default", { id = null })["id"]
}
```

### Expected Behavior
Plan runs fine

### Actual Behavior
```
Invalid value for "default" parameter: the default value must have the same type as the map elements.
```

### PR DESCRIPTION
**Pull request by jbardin**
Revert the evaluation change from #29862.

While returning a dynamic value for all expanded resources during validation is not optimal, trying to work around this using unknown maps and lists is causing other undesirable behaviors during evaluation.

Fixes #30127

### CODE REVIEW

**Comment by jbardin** [comment]
Going to add in a test specifically for 30171

File: internal/terraform/context_validate_test.go [hunk 1]
```diff
@@ -2031,3 +2031,50 @@ resource "test_object" "t" {
 		t.Fatal(diags.ErrWithWarnings())
 	}
 }
+
+func TestContext2Plan_lookupMismatchedObjectTypes(t *testing.T) {
+	p := new(MockProvider)
```
Comment (apparentlymart) [inline internal/terraform/context_validate_test.go:2036]: Given that we were all so surprised that this had ever worked before, I think it would help to include a comment here explaining _why_ the behavior described by this test is "correct", because I expect that in the far future we'll end up back here after seeing this test fail and have lost the context for what exactly this is testing, and thus might end up incorrectly concluding that the test is wrong.

**Review by apparentlymart — APPROVED** [review]

File: internal/terraform/context_validate_test.go (hunk 1 above)
Comment (jbardin) [reply internal/terraform/context_validate_test.go:2036]: Thanks, I meant to add that and will include it before merging!
