### PR TITLE
terraform: fail early if module validation fails

### LINKED ISSUE #1861: Unknown variable referenced error too late, unclear
Hi 
I have been reading the release notes for 0.5.0 trying to find an explanation for something a bit strange..
I am using the very same piece of code for 0.4.2 and 0.5.0
while on 0.4.2 seems to work well on 0.5.0 when I run plan terraform I am getting errors variable related such us:
* module.vpc_infrastructure: missing dependency: var.cidr-block-vpc-infrastructure
That is coming from this file: infrastructucture.tf
```
/* Infrastructure  Modules */
module "vpc_infrastructure" {
  source = "modules/network/vpc/infrastructure/"
  cidr-block-vpc-infrastructure = "${var.cidr-block-vpc-infrastructure}"
  region = "${var.region}"
}
```

And the variable has been defined on terraform.tfvars
```
/* cidr vpc infrastructure */
cidr-block-vpc-infrastructure = "50.10.0.0/16"
```
But it is ignored unless I update the variables.tf :
```
variable "cidr-block-infrastructure-backbone-1a" {
	default= "50.10.0.0/16"
}
```

Maybe this is expected all together, but a bit puzzled as on 0.4.2 it never reported those errors and I cannot find the piece of documentation which can explain all that..

Thanks!

### PR DESCRIPTION
**Pull request by mitchellh**
Fixes #1861 

This just bails earlier if we have module validation errors. There isn't a test for this because its mostly a UX change. All errors that are caught at this stage are also caught at the graph stage, but the errors are nicer UX earlier if we bail.

### CODE REVIEW

File: terraform/context_test.go [hunk 1]
```diff
@@ -3132,28 +3132,6 @@ func TestContext2Validate_targetedDestroy(t *testing.T) {
...
-	p.ValidateResourceFn = func(t string, c *ResourceConfig) ([]string, []error) {
-		computed = c.IsComputed("foo")
-		return nil, nil
-	}
-
-	c.Validate()
-	if !computed {
-		t.Fatal("should be computed")
-	}
-}
```
Comment (phinze) [inline terraform/context_test.go]: Why is this test going away?

**Comment by phinze** [comment]
One question, but seems reasonable generally.

File: terraform/context_test.go (hunk 1 above)
Comment (mitchellh) [inline terraform/context_test.go]: It was testing that validation didn't fail and that the validate resource function actually received a "computed" value in the case that a value wasn't specified. This happened prior to this commit, but not after. We were masking the error "variable 'foo' is required"
