### PR TITLE
internal: Fix lockfile constraint output for 1.2.*

### LINKED ISSUE #26631: Error: Invalid provider version constraints
### Terraform Version

```
Terraform v0.14.0-beta1
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.11"
    }
  }

  required_version = ">= 0.14"
}
```

### Debug Output

https://gist.github.com/danieladams456/2a62510f5646fb073647f9e367c68062

### Expected Behavior

terraform init should be able to be run twice.

### Actual Behavior

The second time terraform init runs, it errors. This seems to be due the required_providers using a single version string like "3.11" and it being saved in the lock file as "3.11.\*".

### Steps to Reproduce

1. `terraform init`
2. `terraform init`

### Additional Context
`.terraform.lock.hcl` contents:
```hcl
# This file is maintained automatically by "terraform init".
# Manual edits may be lost in future updates.

provider "registry.terraform.io/hashicorp/aws" {
  version     = "3.11.0"
  constraints = "3.11.*"
  hashes = [
    "h1:J+FDe23QpxhMKYDh9xGrr+9HcWIAkyodIZXvUvuxpDY=",
  ]
}
```
### References

#26524

### PR DESCRIPTION
**Pull request by alisdair**
If a configuration requires a partial provider version (with some parts unspecified), Terraform considers this as a constrained-to-zero version. For example, a version constraint of `1.2` will result in an attempt to install version `1.2.0`, even if `1.2.1` is available.

When writing the dependency locks file, we previously would write `1.2.*`, as this is the in-memory representation of `1.2`. This would then cause an error on re-reading the locks file, as this is not a valid constraint format.

Instead, we now explicitly convert the constraint to its zero-filled representation before writing the locks file. This ensures that it correctly round-trips.

Because this change is made in `getproviders.`VersionConstraintsString, it also affects the output of the providers sub-command.

Fixes #26631.

### CODE REVIEW

**Review by mildwonkey — APPROVED** [review]
This looks good to me! 

The reporter asked a good question in the attached issue (not a question that would hold up this PR): should terraform require full major.minor.patch version constraints when specifying an exact match w/ `=`? 

I'm ok with not requiring that as long as it's clearly documented that `= 2.0` is equivalent to ` = 2.0.0`, *especially* if `= 2.0.0` is what terraform displays in the UI, but it's worth thinking about.

File: internal/getproviders/types.go [hunk 1]
```diff
@@ -422,27 +422,24 @@ func VersionConstraintsString(spec VersionConstraints) string {
 			b.WriteString("??? ")
 		}
 
+		// The parser allows writing abbreviated versions (such as ~> 2) which
+		// end up being represented in memory with trailing unconstrained parts
```
Comment (mildwonkey) [inline internal/getproviders/types.go:426]: (dang it gh this is the 4th time I've written this comment PLEASE STICK THIS TIME)

I know this isn't a new comment, but I have a nitpicky request while you're in the area: reading this briefly (before my brain kicked in) lead me to expect that a constraint written as `~> 2.0` would be recorded as `2.0.0` (exact). It's silly, but can you clarify that comment? I don't know if my suggestion (below) is the right idea but something like it would have saved me a lot of time this morning 🙃

File: internal/getproviders/types.go [hunk 2]
```diff
@@ -422,27 +422,24 @@ func VersionConstraintsString(spec VersionConstraints) string {
...
+		// (for example ~> 2.*).  That's not really any different than writing
+		// the constrained-to-zero version (like 2.0) and so we'll prefer that
```
Comment (mildwonkey) [inline internal/getproviders/types.go:428]:
```suggestion
		// the constrained-to-zero version (like ~> 2.0) and so we'll prefer that
```

something _like_ this?

File: internal/getproviders/types.go (hunk 1 above)
Comment (alisdair) [reply internal/getproviders/types.go:426]: I think your suggestion below is correct, but in rereading the comment I also spent 10 minutes confused, so I think it's probably structurally unclear. I'll take another shot at it. Thanks for pointing this out!

Comment (alisdair) [reply internal/getproviders/types.go:426]: Here's another attempt. Is this any clearer to you?

Comment (mildwonkey) [reply internal/getproviders/types.go:426]: YES thank you!! That's fantastic!
