### PR TITLE
make remote state initial behavior the same as local state

### LINKED ISSUE #30670: S3 backend does not give stale plan file error until 3rd apply of same plan file.
First, let me show that everything works as designed using local backend mode.  Below is my TF config file that is specially crafted so that the creation of 1 resource will be successful, but the other one will fail.  In this sample, the IAM role will fail because I have placed a special tag on it which is restricted by the account SCP in AWS and my default profile does not have permissions to bypass that SCP.

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
  }
}

provider "aws" {
  profile = "default"
  region = "us-west-2"
}

data "aws_iam_policy_document" "MyRoleAssumePolicy" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      identifiers = ["ec2.amazonaws.com"]
      type = "Service"
    }
  }
}
resource "aws_security_group" "MySecurityGroup" {
  name = "ShawnTraining"
  description = "ShawnTraining"
  vpc_id = "vpc-XXXXXXXXXXX"
  egress {
    protocol = "-1"
    from_port = 0
    to_port = 0
    cidr_blocks = ["0.0.0.0/0"]
  }
}
resource "aws_iam_role" "MyRole" {
  name = "ShawnTraining"
  assume_role_policy = data.aws_iam_policy_document.MyRoleAssumePolicy.json
  tags = {
    protected-tag = "techops"
  }
}
```

I then run the following commands against a local backend:
1. terraform init
```
Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/aws versions matching "~> 3.0"...
- Installing hashicorp/aws v3.74.3...
- Installed hashicorp/aws v3.74.3 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```
2. terraform plan -out tf.plan
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_iam_role.MyRole will be created
  + resource "aws_iam_role" "MyRole" {
      + arn                   = (known after apply)
      + assume_role_policy    = jsonencode(
            {
              + Statement = [
                  + {
                      + Action    = "sts:AssumeRole"
                      + Effect    = "Allow"
                      + Principal = {
                          + Service = "ec2.amazonaws.com"
                        }
                      + Sid       = ""
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
      + create_date           = (known after apply)
      + force_detach_policies = false
      + id                    = (known after apply)
      + managed_policy_arns   = (known after apply)
      + max_session_duration  = 3600
      + name                  = "ShawnTraining"
      + name_prefix           = (known after apply)
      + path                  = "/"
      + tags                  = {
          + "protected-tag" = "techops"
        }
      + tags_all              = {
          + "protected-tag" = "techops"
        }
      + unique_id             = (known after apply)

      + inline_policy {
          + name   = (known after apply)
          + policy = (known after apply)
        }
    }

  # aws_security_group.MySecurityGroup will be created
  + resource "aws_security_group" "MySecurityGroup" {
      + arn                    = (known after apply)
      + description            = "ShawnTraining"
      + egress                 = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 0
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "-1"
              + security_groups  = []
              + self             = false
              + to_port          = 0
            },
        ]
      + id                     = (known after apply)
      + ingress                = (known after apply)
      + name                   = "ShawnTraining"
      + name_prefix            = (known after apply)
      + owner_id               = (known after apply)
      + revoke_rules_on_delete = false
      + tags_all               = (known after apply)
      + vpc_id                 = "vpc-XXXXXXXXXXX"
    }

Plan: 2 to add, 0 to change, 0 to destroy.

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Saved the plan to: tf.plan

To perform exactly these actions, run the following command to apply:
    terraform apply "tf.plan"
```
3. terraform apply tf.plan
```
aws_iam_role.MyRole: Creating...
aws_security_group.MySecurityGroup: Creating...
aws_security_group.MySecurityGroup: Creation complete after 4s [id=sg-053589fa520beddcc]
╷
│ Error: failed creating IAM Role (ShawnTraining): AccessDenied: User: arn:aws:sts::YYYYYYYYYY:assumed-role/ZZZZZZZZZZZ/shawn@company.com is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::YYYYYYYYYY:role/ShawnTraining with an explicit deny
│ 	status code: 403, request id: 945af9e3-498d-4ee7-9913-fa58e5ae7328
│ 
│   with aws_iam_role.MyRole,
│   on main.tf line 35, in resource "aws_iam_role" "MyRole":
│   35: resource "aws_iam_role" "MyRole" {
│ 
╵
```
4. terraform apply tf.plan
```
╷
│ Error: Saved plan is stale
│ 
│ The given plan file can no longer be applied because the state was changed by another operation after the plan was created.
╵
 ```

You can see that the second time I tried to apply the same plan file, TF correctly detected that the plan file was stale.  However, if I try the same thing using an S3 backend with DynamoDB, the plan file is NOT detected as stale and damages the state file in S3.

First, I will change my TF config file to hardcode S3 backend parameters like this (everything else is unchanged):
```
backend "s3" {
    role_arn = "arn:aws:iam::WWWWWWWWW:role/enr-terraform-state-manager"
    bucket = "enr-terraform-state"
    key = "ShawnTraining/tf4.tfstate"
    region = "us-west-2"
    dynamodb_table = "enr-terraform-state-lock"
  }
```

Now, I repeat the same commands with an S3 backend:
1. terraform init
```
Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding hashicorp/aws versions matching "~> 3.0"...
- Installing hashicorp/aws v3.74.3...
- Installed hashicorp/aws v3.74.3 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```
2. terraform plan -out tf.plan
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_iam_role.MyRole will be created
  + resource "aws_iam_role" "MyRole" {
      + arn                   = (known after apply)
      + assume_role_policy    = jsonencode(
            {
              + Statement = [
                  + {
                      + Action    = "sts:AssumeRole"
                      + Effect    = "Allow"
                      + Principal = {
                          + Service = "ec2.amazonaws.com"
                        }
                      + Sid       = ""
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
      + create_date           = (known after apply)
      + force_detach_policies = false
      + id                    = (known after apply)
      + managed_policy_arns   = (known after apply)
      + max_session_duration  = 3600
      + name                  = "ShawnTraining"
      + name_prefix           = (known after apply)
      + path                  = "/"
      + tags                  = {
          + "protected-tag" = "techops"
        }
      + tags_all              = {
          + "protected-tag" = "techops"
        }
      + unique_id             = (known after apply)

      + inline_policy {
          + name   = (known after apply)
          + policy = (known after apply)
        }
    }

  # aws_security_group.MySecurityGroup will be created
  + resource "aws_security_group" "MySecurityGroup" {
      + arn                    = (known after apply)
      + description            = "ShawnTraining"
      + egress                 = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 0
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "-1"
              + security_groups  = []
              + self             = false
              + to_port          = 0
            },
        ]
      + id                     = (known after apply)
      + ingress                = (known after apply)
      + name                   = "ShawnTraining"
      + name_prefix            = (known after apply)
      + owner_id               = (known after apply)
      + revoke_rules_on_delete = false
      + tags_all               = (known after apply)
      + vpc_id                 = "vpc-XXXXXXXXXXX"
    }

Plan: 2 to add, 0 to change, 0 to destroy.

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Saved the plan to: tf.plan

To perform exactly these actions, run the following command to apply:
    terraform apply "tf.plan"
Releasing state lock. This may take a few moments...
```
3. terraform apply tf.plan
```
Acquiring state lock. This may take a few moments...
aws_iam_role.MyRole: Creating...
aws_security_group.MySecurityGroup: Creating...
aws_security_group.MySecurityGroup: Creation complete after 5s [id=sg-02aed019198faf4ec]
╷
│ Error: failed creating IAM Role (ShawnTraining): AccessDenied: User: arn:aws:sts::YYYYYYYYYY:assumed-role/ZZZZZZZZZZZ/shawn@company.com is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::YYYYYYYYYY:role/ShawnTraining with an explicit deny
│ 	status code: 403, request id: 425ae5a6-3927-4e79-85d1-e0db0e5fdebe
│ 
│   with aws_iam_role.MyRole,
│   on main.tf line 42, in resource "aws_iam_role" "MyRole":
│   42: resource "aws_iam_role" "MyRole" {
│ 
╵
Releasing state lock. This may take a few moments...
```
4. terraform apply tf.plan
```
aws_iam_role.MyRole: Creating...
aws_security_group.MySecurityGroup: Creating...
╷
│ Error: error creating Security Group (ShawnTraining): InvalidGroup.Duplicate: The security group 'ShawnTraining' already exists for VPC 'vpc-XXXXXXXXXXX'
│ 	status code: 400, request id: dc43debe-84c7-4902-8f65-fd90cf677e26
│ 
│   with aws_security_group.MySecurityGroup,
│   on main.tf line 31, in resource "aws_security_group" "MySecurityGroup":
│   31: resource "aws_security_group" "MySecurityGroup" {
│ 
╵
╷
│ Error: failed creating IAM Role (ShawnTraining): AccessDenied: User: arn:aws:sts::YYYYYYYYYY:assumed-role/ZZZZZZZZZZZ/shawn@company.com is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::YYYYYYYYYY:role/ShawnTraining with an explicit deny
│ 	status code: 403, request id: 72cc28d8-4598-4123-b1f0-2da9df337111
│ 
│   with aws_iam_role.MyRole,
│   on main.tf line 42, in resource "aws_iam_role" "MyRole":
│   42: resource "aws_iam_role" "MyRole" {
│ 
╵
Releasing state lock. This may take a few moments...
```

Notice that on the second apply of the same plan file, no stale plan error was given and the apply tried to re-create the security group that was successfully created in the first apply.  But even worse, the re-creation fails AND corrupts the state file such that the security group is no longer in the state file and must be imported.
5. terraform apply tf.plan
```
Acquiring state lock. This may take a few moments...
Releasing state lock. This may take a few moments...
╷
│ Error: Saved plan is stale
│ 
│ The given plan file can no longer be applied because the state was changed by another operation after the plan was created.
╵
```

Notice on the 3rd attempt at applying the same plan file, TF finally shows the stale plan file error.

I think this is a serious problem since it corrupts the state file.

### PR DESCRIPTION
**Pull request by yardbirdsax**
This fixes #30670, which is due to how the remote state functionality previously had slightly different logic for the initial serial number of state. The local backend always generated initial state with a serial of `> 0`, whereas remote state would generate it with a serial of `0`. When combined with certain conditions (such as the one laid out in the referenced issue), this could result in Terraform over-writing remote state with stale state from a `plan` file and not throwing the expected `The given plan file can no longer be applied because the state was changed` error.

To support this change I also had to refactor the way in which the tests for the affected method were written, since previously the tests assumed one request per test case. I think I did this in a fairly idiomatic way that didn't depart too much from the rest of the test methods but I'm certainly open to suggestions on other ways to do so.

Fixes #30670

## Target Release

1.4.x
1.3-backport

### BUG FIXES
-  When using remote state and an initial `terraform apply` operation with a `plan` file specified partially succeeds, Terraform would allow the stale `plan` file to be used again and overwrite the remote state, due to a small difference in how remote state was initially created. Terraform now creates initial remote state in a manner consistent with local state, and will throw the expected `The given plan file can no longer be applied because the state was changed` error if a stale plan file is used again after the initial partially successful `apply` operation.

### CODE REVIEW

File: internal/states/remote/state.go [hunk 1]
```diff
@@ -175,13 +179,15 @@ func (s *State) PersistState(schemas *terraform.Schemas) error {
...
+		log.Printf("[DEBUG] states/remote: after refresh, state read serial is: %d; serial is: %d", s.readSerial, s.serial)
+		log.Printf("[DEBUG] states/remote: after refresh, state read lineage is: %s; lineage is: %s", s.readLineage, s.lineage)
 		if s.lineage == "" { // indicates that no state snapshot is present yet
 			lineage, err := uuid.GenerateUUID()
 			if err != nil {
 				return fmt.Errorf("failed to generate initial lineage: %v", err)
 			}
 			s.lineage = lineage
-			s.serial = 0
+			s.serial = 1
```
Comment (nmische) [inline internal/states/remote/state.go:190]: I might suggest changing this to match what is done in other places in the codebase:

```suggestion
			s.serial++
```

**Review by nmische — APPROVED** [review]
Looks like this could also be an issue for Terraform Cloud: 

https://github.com/hashicorp/terraform/blob/main/internal/cloud/state.go#L166

**Comment by yardbirdsax** [comment]
By the way, based on where the code I changed was, I think this would be a problem for all remote states, not just S3, though I can't verify that since I don't have any other cloud vendor's storage on which to test.

**Comment by jbardin** [comment]
Thanks @yardbirdsax! This is not unique to s3, but the fix will apply to all of the legacy remote states in the same manner. It does look like cloud is unique though as @nmische mentioned. We can follow up with a PR there too.

File: internal/states/remote/state.go (hunk 1 above)
Comment (jbardin) [reply internal/states/remote/state.go]: @brandonc, can you confirm if this would affect cloud at all, or does the server itself prevent this from being applied?

**Comment by yardbirdsax** [comment]
Thanks @jbardin ! Question: did I forget to do something to make sure this gets backported to the 1.3 version? I thought I put the right text in the description but I don’t see any related issues / PRs. Apologies in advance if my GitHub Fu is failing me.

**Comment by jbardin** [comment]
Thanks for mentioning that @yardbirdsax. This would of missed the last patch release, but due to some unforeseen circumstances we do still have one pending. Since it's such a small change I'm going to go ahead and backport it for v1.3 (you didn't miss anything, the automation is triggered by labels which are set by maintainers).

**Comment by yardbirdsax** [comment]
Awesome, thank you!

File: internal/states/remote/state.go (hunk 1 above)
Comment (brandonc) [reply internal/states/remote/state.go]: The Terraform Cloud platform will allow this to be applied, as long as it is incrementing. I duplicated the fix as https://github.com/hashicorp/terraform/pull/32647 and smoke tested it in Terraform Cloud. Thanks for the mention
