### PR TITLE
Change import message to 'prepared'

### LINKED ISSUE #20017: "Import completed!" message is wrong
### Terraform Version

```console
$ terraform -v
Terraform v0.11.11
```

### Terraform Configuration Files

```hcl
resource "aws_route" "test" {
  route_table_id = "${aws_route_table.test.id}"
  destination_cidr_block = "10.1.0.0/16"
  gateway_id = "${aws_internet_gateway.test.id}"
}
```

### Expected Behavior

During import, Terraform should report "Import prepared" (or something similar) after the resource importer `State()` function is complete.

To be extra clear, after both the `State()` and `Read()` functions complete successfully, a message announcing "Import complete!" could be given.

### Actual Behavior

During import, Terraform wrongly reports "Import complete!" when it is not usually complete.  

Terraform reports "Import complete!" after the resource importer `State()` function is complete. However, `State()` is often used to just set enough information so that `Read()` works, which is called immediately after. Usually during `State()`, information provided in the import command is put in the right places in the state, without ever checking anything on AWS (or presumably, other provider). That does not constitute the normal meaning of "import complete." As a result, it's easy to get the confusing and wrong "Import complete!" message below followed by a "non-existent resource" message.

```
aws_route.test: Importing from ID "rtb-0b8835dc7eb1e3168_12.22.48.96/0"...
aws_route.test: Import complete!
  Imported aws_route (ID: r-rtb-0b8835dc7eb1e3168715786107)
aws_route.test: Refreshing state... (ID: r-rtb-0b8835dc7eb1e3168715786107)

Error: aws_route.test (import id: rtb-0b8835dc7eb1e3168_12.22.48.96/0): 1 error(s) occurred:

* import aws_route.test result: r-rtb-0b8835dc7eb1e3168715786107: import aws_route.test (id: r-rtb-0b8835dc7eb1e3168715786107): Terraform detected a resource with this ID doesn't
exist. Please verify the ID is correct. You cannot import non-existent
resources using Terraform import.
```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`
3. `terraform state rm aws_route.test`
4. Delete the route using the AWS console
4. `terraform import -input=false aws_route.test rtb-0b8835dc7eb1e3168_12.22.48.96/0`

### References
- terraform-providers/terraform-provider-aws#6404
- terraform-providers/terraform-provider-aws#6944

### PR DESCRIPTION
**Pull request by YakDriver**
Fixes #20017 

Changes proposed:
* hook_ui: Change the "Import complete!" message to "Import prepared!" and then list resources as "prepared" instead of "imported".

### CODE REVIEW

File: command/hook_ui.go [hunk 1]
```diff
@@ -316,10 +316,10 @@ func (h *UiHook) PostImportState(addr addrs.AbsResourceInstance, imported []prov
 	h.once.Do(h.init)
 
 	h.ui.Output(h.Colorize.Color(fmt.Sprintf(
-		"[reset][bold][green]%s: Import complete!", addr)))
+		"[reset][bold][green]%s: Import prepared!", addr)))
 	for _, s := range imported {
 		h.ui.Output(h.Colorize.Color(fmt.Sprintf(
-			"[reset][green]  Imported %s",
+			"[reset][green]  Prepared %s",
```
Comment (mildwonkey) [inline command/hook_ui.go]:
```suggestion
			"[reset][green]  Prepared %s for import",
```

This is nitpicky, but what do you think?

**Comment by mildwonkey** [comment]
Hi @YakDriver , thanks for working on this! 

This is indeed a confusing message. It's meant to indicate that the item has been imported to the current state, pending successful refresh, but (as you already noted) that just isn't clear.  

I went back and forth for a bit on the message - `Import staged`? `Imported to state`? - but you had a good idea with `Import prepared`. I left one small nitpicky suggestion for the next message. Let me know what you think. 

I know it's been awhile since you submitted this PR. If you don't have the time or inclination to look at this again, that's ok! I can make that small change myself and merge this for you. 
Thanks again!

**Comment by YakDriver** [comment]
@mildwonkey I like it. As long as it clears up the confusion, I'm happy.

**Comment by mildwonkey** [comment]
Great, thank you @YakDriver ! 

The travis build did pass - it's still showing up as 'in progress', at least from my browser - so I will merge this now. 🎉
