### PR TITLE
provider/aws: Fix issue with updating VPC Security Group IDs for an Instance

### LINKED ISSUE #1611: modify/attach/detach secururity group on vpc instance
Currently terraform "forces new resource" (redeploys instance) in case of security group modification on instance which is deployed in VPC. But AWS VPC allows to modify security groups and Instance relationship  without downtime.

### PR DESCRIPTION
**Pull request by catsby**
Currently, we aren't correctly setting the ids, and are setting both
`security_groups` and `vpc_security_group_ids` in the state. As a result, we really only use
the former, but the latter never goes away in the state file :frowning: 

We also don't actually update the remote security groups in the `update` method.

This PR fixes both issues, correctly reading `security_groups` vs.
`vpc_security_group_ids` and allows users to update the latter without
destroying the Instance when in a VPC.

Should fix #1611

### CODE REVIEW

File: builtin/providers/aws/resource_aws_eip.go [hunk 1]
```diff
@@ -102,8 +102,8 @@ func resourceAwsEipRead(d *schema.ResourceData, meta interface{}) error {
 	domain := resourceAwsEipDomain(d)
 	id := d.Id()
 
-	assocIds := []*string{}
-	publicIps := []*string{}
+	var publicIps []*string
+	var assocIds []*string
```
Comment (catsby) [inline builtin/providers/aws/resource_aws_eip.go]: The test was failing to create the EIP because of this. While this fixes this particular acceptance test, #1598 may be a better solution long term

**Comment by radeksimko** [comment]
This fixes the issue for me :+1:

**Comment by pmoust** [comment]
Working fine for us as well.

**Comment by mzupan** [comment]
works great for me :+1:

**Comment by catsby** [comment]
rebased on master /cc @phinze

**Comment by phinze** [comment]
LGTM!
