### PR TITLE
lang/funcs: Add support for OpenSSH RSA key format

### LINKED ISSUE #24597: Terraform version: 0.12.21 crashed
[crash.log](https://github.com/hashicorp/terraform/files/4450993/crash.log)
TerraformCrash

### Terraform Version 
0.12.21

```
...
```

### Terraform Configuration Files

```hcl
...
```

### Actual Behavior
Terraform is getting crashed while doing terraform plan.

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

### LINKED ISSUE #24970: rsadecrypt fails using recent ssh-keygen DSA keys
### Terraform Version

```
Terraform v0.12.25
+ provider.aws v2.61.0
```

### Terraform Configuration Files

A [complete reproduction case](https://github.com/danieldreier/terraform-issue-reproductions/tree/master/24970) is available.

### Debug Output

https://raw.githubusercontent.com/danieldreier/terraform-issue-reproductions/master/24970/failure-output.log

### Expected Behavior

Windows AWS EC2 instances can automatically generate a password for the Administrator account and associate it with EC2 instance metadata using the get_password_data argument on the aws_instance resource. AWS encrypts the password with the rsa private key identified by the key_name argument on the aws_instance resource. The rsadecrypt function was added to terraform to support decrypting this value in PR #16647.

Note that all keys in this repository and generated passwords were generated for this exercise alone and are safe to be shared publicly. These are not confidential or used for anything else, and the infrastructure shown for this output has since been destroyed.

The rsadecrypt function should provide the plain-text representation of the password that was encrypted using the public key by AWS. When using the ssh-keygen command from Linux to generate this RSA key pair, this is successful. When using ssh-keygen from OS X 10.15.4, it is not successful.

### Actual Behavior

When using an rsa key pair generated by OS X `ssh-keygen`, terraform exits with the following error:
```
Error: Error in function call

  on example.tf line 130, in output "password_decrypted":
 130:   value=rsadecrypt(aws_instance.windows2019.password_data, file("${path.module}/${var.rsa_private_key_file}") )
    |----------------
    | aws_instance.windows2019.password_data is "I91Vapc4zdkxopkh4l8hNY5O1TwE5NMwCV+GvbycR4HLMRQoLn5TV8+fdrSbu4NyWlu1rKbAEjP0LO+y1nf49D/5hB3jXtLu2ZH+bHKIBeYH9ojnqwp3qCkOdUkrebx58MWK2n1+26JsibpVcjiVG5oNBT8t4h/aSwMREzw6mGiO6PPNDSFp3xQsBVh5H8ymCg8pD6b0nvu/7jwizE+tXS4BANYehhJgIwPR6VytZT693Oz+TlOsEjJZ6wBQZaULJkDyumOo3Xr/pIBcEqPGkDucZLipjcup1Mi3zyoSSLtiRGFQpqT9tIXSTf/0gPpgu9nM6TsmpdyABWoaA0ZMVbpCAf6puwkYQUwfXdyCnXvloCUdQQzY3a/EO/HK1mj4psldacqRNj85QHFWXA20Foj2Pcle5OvUZh+uKEL2gAIxHwfOXZC1xoONvymUIYkA3wtZK2pUpQgcWVYf4AggrEPsqGxwMGfybvO79XM7a10sn6JhADVlsja0vpOK9881"
    | path.module is "."
    | var.rsa_private_key_file is "id_rsa_from_osx"

Call to function "rsadecrypt" failed: asn1: structure error: tags don't match
(16 vs {class:1 tag:15 length:112 isCompound:true}) {optional:false
explicit:false application:false private:false defaultValue:<nil> tag:<nil>
stringType:0 timeType:0 set:false omitEmpty:false} pkcs1PrivateKey @2.
```

### Steps to Reproduce

See more detailed reproduction steps in the [linked github repository](https://github.com/danieldreier/terraform-issue-reproductions/tree/master/24970).

### Additional Context

This basically breaks Windows EC2 provisioning because terraform can no longer decrypt the admin password. If people feed that password into a provisioner, the whole provisioning flow is broken. I think that detecting this situation and providing a better error message that points people to the workaround (e.g. copy-pastable openssh / ssh-keygen command string for how to generate a usable key-pair) would be plausible if the root issue is too hard to solve.

### References

Similar errors have been reported in
https://github.com/concourse/concourse/issues/2592 which linked to https://github.com/golang/go/issues/18634

According to [their discussion forum](https://discuss.concourse-ci.org/t/worker-key-generated-on-macos-doesnt-work/911)

 * ssh-keygen(1): write OpenSSH format private keys by default
    instead of using OpenSSL's PEM format. The OpenSSH format,
    supported in OpenSSH releases since 2014 and described in the
    PROTOCOL.key file in the source distribution, offers substantially
    better protection against offline password guessing and supports
    key comments in private keys. If necessary, it is possible to write
    old PEM-style keys by adding "-m PEM" to ssh-keygen's arguments
    when generating or updating a key.

This has also come up in discuss:
https://discuss.hashicorp.com/t/how-to-rsadecrypt-and-get-password-data-from-aws-windows-server-instance/7474

### PR DESCRIPTION
**Pull request by alisdair**
Keys generated by recent versions of OpenSSH use a new OpenSSH PEM format which is incompatible with the `x509` package. We can work around this by using the `ParseRawPrivateKey` from `x/crypto/ssh` and type asserting that we get the expected RSA key type back.

- [`ParseRawPrivateKey` docs](https://godoc.org/golang.org/x/crypto/ssh#ParseRawPrivateKey)
- [`ParseRawPrivateKey` source](https://github.com/golang/crypto/blob/279210d13fedf5be6d476bad5df6a015042bb905/ssh/keys.go#L1120-L1145), where you can see that it delegates depending on key type
- [Code further down the path returning an `rsa.PrivateKey`](https://github.com/golang/crypto/blob/279210d13fedf5be6d476bad5df6a015042bb905/ssh/keys.go#L1329-L1365), which is what our `rsadecrypt` function needs to proceed

The new OpenSSH private key fixture was generated by re-encoding the existing private key fixture using this command on macOS:

```shellsession
$ ssh-keygen -p -N "" -f id_rsa_terraform
Your identification has been saved with the new passphrase.
```

Fixes #24970.

### CODE REVIEW

File: lang/funcs/crypto.go [hunk 1]
```diff
@@ -155,24 +154,18 @@ var RsaDecryptFunc = function.New(&function.Spec{
...
-			return cty.UnknownVal(cty.String), fmt.Errorf(
-				"failed to parse key: password protected keys are not supported. Please decrypt the key prior to use",
-			)
-		}
-
-		x509Key, err := x509.ParsePKCS1PrivateKey(block.Bytes)
+		rawKey, err := ssh.ParseRawPrivateKey([]byte(key))
 		if err != nil {
-			return cty.UnknownVal(cty.String), err
+			return cty.UnknownVal(cty.String), fmt.Errorf("failed to parse key: %s", err)
```
Comment (jbardin) [inline lang/funcs/crypto.go:159]: is the Errorf text needed here? Just wondering if we're going to get errors like `failed to parse key: fail to parse SSH key`

Comment (apparentlymart) [reply lang/funcs/crypto.go:159]: I had kinda hoped that the `encoding/asn1` package would produce machine-readable error values that we could use to present something more appropriate for the Terraform end-user audience, 'cause from what I see in #24970 these messages seem pretty poor, but sadly it looks like [`StructuralError`](https://pkg.go.dev/encoding/asn1?tab=doc#SyntaxError) and [`SyntaxError`](https://pkg.go.dev/encoding/asn1?tab=doc#SyntaxError) are both just wrappers around opaque strings formatted in the internals of the parser. :confounded: 

With that said, I reviewed [the parser code](https://github.com/golang/go/blob/go1.14.4/src/encoding/asn1/asn1.go#L1082) and it looks like this "tags don't match" error is a particularly ugly example but most of them are reasonably messages that suffer only from a total lack of useful context, like "base 128 integer too large". So the two forms this should end up producing are:

* `failed to parse key: asn1: structure error: tags don't match
(16 vs {class:1 tag:15 length:112 isCompound:true}) {optional:false
explicit:false application:false private:false defaultValue:<nil> tag:<nil>
stringType:0 timeType:0 set:false omitEmpty:false} pkcs1PrivateKey @2.`
* `failed to parse key: asn1: syntax error: invalid boolean`

I think the only way we could marginally improve these with the information we have is to recognize when the error type is either `asn1.SyntaxError` or asn1.StructuralError` and generate a different prefix (replacing `asn1: syntax error:`) that is more inline with our usual writing style, like:

* `invalid ASN1 data in the given private key: invalid boolean`
* `invalid ASN1 data in the given private key: tags don't match
(16 vs {class:1 tag:15 length:112 isCompound:true}) {optional:false
explicit:false application:false private:false defaultValue:<nil> tag:<nil>
stringType:0 timeType:0 set:false omitEmpty:false} pkcs1PrivateKey @2.`

(the second one isn't going to be nice _whatever_ we do to it, of course...)

A further embellishment, though very much _not necessary_, would be to use `function.NewArgErrorf` to associate this error explicitly with the second argument (argument index 1), and then HCL should indicate that argument's experession in particular as being the problematic part of the configuration.

Comment (alisdair) [reply lang/funcs/crypto.go]: Thanks for the suggestions!

I think it is important to process these errors rather than just pass them through, because the crypto errors are pretty obscure. Adding even basic error annotations was the first step to debugging this.

I've made the suggested changes and I think it's a big improvement:

```shellsession
velara:24970 $ tf apply -var-file=trunc.tfvars

Error: Invalid function argument

  on example.tf line 13, in output "password_decrypted":
  13:   value=rsadecrypt(var.password_data, file("${path.module}/${var.rsa_private_key_file}") )
    |----------------
    | path.module is "."
    | var.rsa_private_key_file is "id_rsa_trunc"

Invalid value for "privatekey" parameter: invalid ASN1 data in the given
private key: data truncated.
```
