### PR TITLE
provider/aws: Change to `aws_dynamodb_table` hash_key forces a new resource

### LINKED ISSUE #6825: Changing hash key on aws_dynamodb_table should recreate the table
Hi,
 
### Terraform Version
Terraform v0.6.16

### Affected Resource(s)
- aws_dynamodb_table

### Terraform Configuration Files

Original file:

```hcl
resource "aws_dynamodb_table" "oulumo-demo-user-table" {
    name = "Users"
    read_capacity = 10
    write_capacity = 10
    hash_key = "PhoneNumber"
    attribute {
        name = "PhoneNumber"
        type = "S"
    }
    attribute {
        name = "UserId"
        type = "S"
    }
    global_secondary_index {
        name = "UserIdIndex"
        hash_key = "UserId"
        write_capacity = 10
        read_capacity = 10
        projection_type = "ALL"
    }
}
```

Changed to:

```hcl
resource "aws_dynamodb_table" "oulumo-demo-user-table" {
    name = "Users"
    read_capacity = 10
    write_capacity = 10
    hash_key = "UserId"
    attribute {
        name = "PhoneNumber"
        type = "S"
    }
    attribute {
        name = "UserId"
        type = "S"
    }
    global_secondary_index {
        name = "PhoneNumberIndex"
        hash_key = "PhoneNumber"
        write_capacity = 10
        read_capacity = 10
        projection_type = "ALL"
    }
}
```

### Expected Behavior
The original table should be destroyed, and a new table created.

### Actual Behavior
Terraform tries to update the table, and AWS SDK generates this error message:

Hash key can only be specified at creation, you cannot modify it.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Nothing special with the account / setup.

### PR DESCRIPTION
**Pull request by stack72**
Fixes #6825

We had a line on the Update func that said:

```
Hash key can only be specified at creation, you cannot modify it.
```

The resource has now been changed to ForceNew on the hashkey

```
aws_dynamodb_table.demo-user-table: Refreshing state... (ID: Users)
aws_dynamodb_table.demo-user-table: Destroying...
aws_dynamodb_table.demo-user-table: Destruction complete
aws_dynamodb_table.demo-user-table: Creating...
aws_dynamodb_table.demo-user-table: Creation complete
```

### CODE REVIEW

File: builtin/providers/aws/resource_aws_dynamodb_table.go [hunk 1]
```diff
@@ -343,10 +344,6 @@ func resourceAwsDynamoDbTableUpdate(d *schema.ResourceData, meta interface{}) er
 		return fmt.Errorf("Local secondary indexes can only be built at creation, you cannot update them!")
 	}
 
-	if d.HasChange("hash_key") {
-		return fmt.Errorf("Hash key can only be specified at creation, you cannot modify it.")
-	}
-
 	if d.HasChange("range_key") {
 		return fmt.Errorf("Range key can only be specified at creation, you cannot modify it.")
```
Comment (jen20) [inline builtin/providers/aws/resource_aws_dynamodb_table.go]: We should probably apply the same fix here to `range_key` which I believe follows the same rule?

Comment (stack72) [inline builtin/providers/aws/resource_aws_dynamodb_table.go]: Nps :)

**Comment by stack72** [comment]
@jen20 this has been updated as expected :)
