### PR TITLE
Module depends_on

### LINKED ISSUE #10462: depends_on cannot be used in a module
Hi there,

### Terraform Version
0.8.0 rc1+

### Affected Resource(s)
module

### Terraform Configuration Files
```hcl
module "legacy_site" {
  source = "../../../../../modules/site"
  name = "foo-site"
  health_check_target = "TCP:443"
  azs = "${var.azs}"
  instance_count = "${var.instance_count}"
  vpc = "apps"
  region = "${var.region}"
  environment = "${var.environment}"
  run_list = "hs_site_foo"

  #rds_complete = "${module.rds.db_instance_id}"
  #elasticache_cache_complete = "${module.elasticache_cache.elasticache_id}"
  #elasticache_sessions_complete = "${module.elasticache_sessions.elasticache_id}"

  depends_on = [
  "module.rds",
  "module.elasticache_sessions"
  ]

}
```

### Debug Output
Error loading Terraform: module root: module legacy_site: depends_on is not a valid parameter
module root: module legacy_site: depends_on is not a valid parameter

### Expected Behavior
I am trying to use the new depends_on instead of the above outputs, so I create and provision my app once I know database and caches are built.

### Actual Behavior
Nothing as terraform errors out as above.

### Steps to Reproduce

1. `terraform apply`

### References
depends_on can reference modules. This allows a resource or output to depend on everything within a module. (#10076)

### LINKED ISSUE #17101: Module-aware explicit dependencies
Terraform currently allows the declaration of explicit inter-resource dependencies using `depends_on`:

```hcl
resource "example" "example1" {
}

resource "example" "example2" {
  depends_on = ["example.example1"]
}
```

The presence of the `depends_on` in the above example causes the graph builder to create a dependency edge from `example2` to `example1`, which ensures that `example1` is visited first during any graph traversal.

This mechanism does not generalize to other constructs within Terraform. In particular, it doesn't generalize to modules, since a module is not represented as a single node in the graph. Instead, each individual `variable` and `output` in a module is its own graph node, which allows us to optimize our parallelism by getting started on _some_ aspects of a module before all of the input variables are ready, and to begin processing resources that _depend_ on a module before all of its outputs are complete. Even though variables and outputs _are_ in the graph, we do not currently support referring to them in `depends_on`.

The following proposal describes a generalization of the `depends_on` mechanism to apply to both resources and modules, with the goal of satisfying the use-cases discussed in #10462, allowing explicit dependencies on module variables and outputs, along with a syntax that creates the _effect_ of an entire-module dependency.

---

## New addressing forms for `depends_on`

We currently allow references to managed and data resources in `depends_on`. To support dependencies with modules, we must extend this to support the following forms:

* `aws_instance.example` - managed resource dependency, as today
* `aws_instance.another_example[2]` - a particular instance of a managed resource with `count` set
* `data.template_file.example` - data resource dependency, as today
* `var.foo` - dependency on an input variable passed by a parent module
* `module.example.foo` - dependency on an output of a named child module
* `module.example` - dependency on an entire module

Our improved configuration language parser (which, at the time of writing, is in the process of being integrated into Terraform Core) allows us to improve the `depends_on` syntax through direct use of expressions, rather than requiring these references to be inside quoted strings:

```hcl
# DESIGN SKETCH: not yet implemented and may change before release

resource "example" "example2" {
  depends_on = [
    aws_instance.example,
    aws_instance.another_example[2]
    data.template_file.example,
    var.foo,
    module.example.foo,
    module.example,
  ]
}
```

This syntax will be used for the examples in the remainder of this proposal.

## Support `depends_on` as a `module` block argument

The above allows modules to be used as explicit dependencies, but we need to additionally support `depends_on` inside `module` blocks in order to allow _modules_ to have dependencies:

```hcl
# DESIGN SKETCH: not yet implemented and may change before release

module "example" {
  depends_on = [
    aws_instance.example,
  ]
}
```

## Depending on a Module Variable

At first glance, an explicit dependency on a `var.foo` expression feels a little strange: variables don't have externally-visible side-effects, so it's strange to want to depend on them without using their result.

However, allowing explicit dependencies on variables creates a mechanism for the author of a more-complex reusable module to create custom `depends_on`-like attributes that serve to block _subsets_ of the functionality of the module. For example:

```hcl
# DESIGN SKETCH: not yet implemented and may change before release

### in root module

module "database" {
}

module "app" {
  ami_id = "ami-1234"
  app_server_depends_on = [
    module.database,
  ]
}

### in module "app"

variable "app_server_depends_on" {
  default = []
}

resource "aws_security_group" "foo" {
  # Work on _this_ resource can begin immediately
  # ...
}


resource "aws_instance" "app_server" {
  ami = var.ami_id
  # ...

  # We can't create this resource until the caller tells us that it's
  # prepared some hidden dependencies.
  depends_on = [
    var.app_server_depends_on,
  ]
}
```

This makes it possible to create a re-usable module for deploying arbitrary applications (parameterized by an AMI to deploy, etc), which can immediately create supporting resources like the security group in this example, but defer creating the actual compute resources until some arbitrary, caller-defined dependencies have been dealt with. The caller knows that `ami-1234` expects to have a database available to it on boot, while the re-usable module has no direct knowledge of that database.

The actual _value_ of `app_server_depends_on` in the above example is not actually significant. Instead, we effectively pass the _dependencies_ of that expression through to the module by creating a transitive dependency relationship in the graph.

## Depending on a Whole Module

As noted above, modules are not represented directly by graph nodes today, so whole-module dependencies (either as dependencies or dependents) require some new graph-building functionality.

The most likely user intent for a dependency of the form `module.example` is to wait until _everything_ in the module has completed before continuing. This behavior would have a severe impact on Terraform's ability to achieve parallelism though, and so this proposal suggests a compromise for when `depends_on` references a whole module: treat this as an alias for depending on each of the module's outputs, but not on any resources or nested modules.

Terraform graph where a nested module called "example" has two resources, example1 and example2, where only example1 is a dependency of the module's outputs

The biggest consequence of this compromise is that in the above example `null_resource.example` will block until `module.example.null_resource.example2` is complete, but will not wait for `module.example.null_resource.example3` because none of the module's outputs depend on that resource.

This consequence gives a measure of flexibility and control for the module author, however: if the author knows that the module performs a time-consuming operation but that this operation does not block access to the objects that the caller will depend on then this can be expressed by making that operation _not_ be a dependency of the outputs. From the module _caller's_ perspective, the module can still be thought of as a black box, with the module author designing it such that all significant effects of the module are referenced in an output. In effect, the module author uses `output` blocks to define what it means for the module to be considered "complete".

The improved configuration language, whose integration is in progress as we write this, allows passing the result of an entire module as a value into another module:

```hcl
# DESIGN SKETCH: not yet implemented and may change before release

### root module
module "example1" {
}
module "example2" {
  example1 = module.example1
}

### module example1

output "id" {
  value = "placeholder-id"
}

### module example2

variable "example1" {
}

resource "null_resource" "example" {
  triggers = {
    example1_id = var.example1.id
  }
}

```

This new usage creates an _implicit_ dependency between `module.example2.var.example1` and all of the outputs of `module.example1`, since they must all be complete before the language runtime can construct the value of `module.example1` to assign. This implicit usage further reinforces the idea that only the outputs are dependencies in this case, because that is what is necessary to construct the object value returned by `module.example1`.

## Whole-module `depends_on`

Using `depends_on` in a `module` block will also limit parallelism, but the impact is less severe in this case because the effect is under the direct control of the _caller_ module, and so its author can make a tradeoff to decide at what point the limited parallelism hurts enough to warrant more precise dependency handling:

```hcl
# DESIGN SKETCH: not yet implemented and may change before release

### root module

variable "baz" {
}

resource "null_resource" "example1" {
  triggers = {
    example = "hello"
  }
}

module "example" {
  foo = var.baz

  depends_on = [
    null_resource.example1,
  ]
}

### module "example"

variable "foo" {
}

resource "null_resource.example2" {
  triggers = {
    foo = var.foo
  }
}

resource "null_resource.example3" {
}

module "example2" {
}

### module "example2"

resource "null_resource.example4" {
}
```

Dependencies _away_ from the module require the creation of a new "begin" graph node for the module that declares `depends_on`, which must then be a dependency of every resource in the module _and_ of any downstream modules. To reduce the number of graph edges, a "begin" node will be created for each of the downstream modules too, so that only one additional edge needs to be added _between_ the modules (to connect the "begin" nodes).

A "begin" graph node takes no action when visited during a walk and so just serves as an aggregation point to reduce the number of dependency edges. For a `module` block without `depends_on` the "begin" graph node can be safely optimized away, along with its incoming dependency edges, during graph construction.

## `depends_on` in other contexts

`depends_on` can be useful for any Terraform construct that causes externally-visible side-effects, as a means to influence the ordering of those side-effects.

Provider initialization also sometimes has side effects, such as reaching out to an external network service to begin a session or to validate credentials. `depends_on` could therefore also be useful in `provider` blocks, as described in #2430. However, providers are special in that they need to be instantiated in _all_ phases of Terraform's operation, and thus it is not always possible to force an ordering for provider initialization relative to resource creation as described in #4149. Implementation of `depends_on` for modules should not block on the implementation of "partial apply", but we should reserve the `depends_on` argument for `provider` blocks as part of implementing _this_ proposal to minimize the risk that a provider in the wild will introduce its own `depends_on` configuration argument that would then be in conflict.

`output`, `variable` and `locals` blocks do not have any externally-visible side-effects and so `depends_on` would not serve any useful purpose for these blocks; it is always safe to evaluate the corresponding graph nodes as soon as their implicit dependencies become ready.

`provisioner` blocks within managed resources are not currently represented as separate graph nodes, and so they are processed as part of a create action for their parent resource node.

### PR DESCRIPTION
**Pull request by jbardin**
Allow the use of `depends_on` for modules.

This PR stands on the existing work already done for module expansion, evaluation, and data source planning. See #24461, #24697, and #24904 for the majority of the work involved in making that happen. 

Now that modules can be ordered and referenced as a whole, and data sources will cleanly allow forced ordering  by `depends_on`; all that is left is to enable the feature in the config and add the graph connections for the `depends_on` references. 

Closes #10462
Closes #17101

### CODE REVIEW

File: terraform/context_apply_test.go [hunk 1]
```diff
@@ -11122,3 +11122,63 @@ resource "aws_instance" "cbd" {
...
+		t.Fatal(diags.ErrWithWarnings())
+	}
+
+	_, diags = ctx.Apply()
+	if diags.HasErrors() {
+		t.Fatal(diags.ErrWithWarnings())
+	}
+
+	// run the plan again to ensure that data sources are not going to be re-read
+	plan, diags := ctx.Plan()
```
Comment (alisdair) [inline terraform/context_apply_test.go:11174]: I might be missing something obvious, but I don't understand this comment. Why does re-planning after apply ensure that the data source isn't re-read?

Comment (jbardin) [reply terraform/context_apply_test.go:11174]: If the data source is read during plan (which is a new ability from #24904), it would show in the plan as a read operation. There should be nothing left to apply at this point, so anything in the plan should be NoOp.

Comment (alisdair) [reply terraform/context_apply_test.go:11174]: Ah, I see now, thanks!

**Comment by apparentlymart** [comment]
I've not delved deep into this yet because I don't have the necessary context loaded to think about the details, but I wanted to ask: could we make sure there's a test somewhere for the case where module `depends_on` _isn't_ being used and one of a module's variables depends on its outputs? I'd like to make sure that isn't broken (and stays unbroken, for the time being) for situations where users _aren't_ using any of these new features.

The sort of test case I have in mind would be...

root module:

```hcl
module "test" {
  source = "./test"

  a = module.test.b
}

output "c" {
  value = module.test.c
}
```

The `./test` module:

```hcl
variable "a" {}

resource "test" "test" {
}

output "b" {
  value = test.test.id
}

output "c" {
  value = var.a
}
```

I would expect the above to work and for the root module output `c` to be whatever `test.test.id` is in the child module. Based on an initial read of this code I expect this _should_ still work, because without `depends_on` set in the `module` block there should not be any additional dependency edges created that would make this be a cycle.

We have so many test fixtures in Terraform Core that I wouldn't be surprised if something like this was there somewhere already, but I'm not sure where it is if so. :confused:

**Comment by jbardin** [comment]
Good idea @apparentlymart! While I didn't expect that to be be effected by this PR, I want to make certain we have that test in the corpus.

**Comment by jbardin** [comment]
The docs change is minimal I think. I just have that in another PR since data sources also needed a `depends_on` update, and then Nick could also review the docs separately.

**Comment by ozbillwang** [comment]
I think this would be a big change (I mean a lot of codes need be updated), but not. 

That's amazing, thanks a lot.

**Comment by feliperfmarques** [comment]
Thanks a lot for this feature. Looking forward to this release.
