### PR TITLE
terraform: missing provider should add missing aliases [GH-2023]

### LINKED ISSUE #2023: Provider alias does not work properly inside module v(0.5.3)
Hey all. I have only tested this with the google provider
Terraform v0.5.3-dev (0d575b75c872aa887071aa46a0dc44dcbda97888)
I also tested with 0.5.1 with the same behaviour.
main.tf
```
module "test" {
  source = "./module"
}
```

./module/main.tf
```
provider "google" {
  alias = "eu"
  project = "staging"
  account_file = "google.json"
  region = "europe-west1"
}

resource "google_compute_address" "new_ip" {
  provider = "google.eu"
  name = "new_ip"
}
```
terraform plan produces:
```
Errors:

  * 1 error(s) occurred:

* module.test: provider google.eu couldn't be found
```

If I include the provider inside the main.tf file I get the same error.
If I include the provider in both main.tf and ./module/main.tf it works.

### PR DESCRIPTION
**Pull request by mitchellh**
Fixes #2023 

The missing provider transform should add provider aliases as well. This makes provider aliases work more easily in modules.

### CODE REVIEW

File: terraform/context_test.go [hunk 1]
```diff
@@ -697,43 +697,6 @@ func TestContext2Plan_preventDestroy_destroyPlan(t *testing.T) {
 	}
 }
 
-func TestContext2Plan_providerAliasMissing(t *testing.T) {
```
Comment (mitchellh) [inline terraform/context_test.go]: This whole test was testing the opposite of the behavior I added. It doesn't make a lot of sense to me that this should be an error, because it breaks modules completely. I think we just default it like every other provider type.

File: terraform/transform_provider.go [hunk 2]
```diff
@@ -146,15 +147,44 @@ type MissingProviderTransformer struct {
...
+
+			if _, ok := supported[ptype]; !ok {
+				// If we don't support the provider type, skip it.
+				// Validation later will catch this as an error.
+				continue
+			}
+
+			// Add our own missing provider node to the graph
+			m[p] = g.Add(&graphNodeMissingProvider{ProviderNameValue: p})
+		}
```
Comment (mitchellh) [inline terraform/transform_provider.go]: This was the key change. Before we would just blindly add every supported provider as a missing provider. But now we actually go through, find what providers we need, and add them each in turn.

Comment (phinze) [inline terraform/transform_provider.go]: +1 I like this more direct approach.

File: terraform/transform_provider.go [hunk 3]
```diff
@@ -146,15 +147,44 @@ type MissingProviderTransformer struct {
...
 
-		// Add our own missing provider node to the graph
-		g.Add(&graphNodeMissingProvider{ProviderNameValue: p})
+		for _, p := range pv.ProvidedBy() {
+			if _, ok := m[p]; ok {
+				// This provider already exists as a configure node
+				break
+			}
+
+			// If the provider has an alias in it, we just want the type
```
Comment (phinze) [inline terraform/transform_provider.go]: How do we know the provider has an alias in it here?

At first I was worried about what would happen if somebody did `provider = "aws.oh.whoops"`, but I think it's fine - the `graphNodeMissingProvider` will get added with a weird `ProviderNameValue` and fail later.

**Comment by phinze** [comment]
LGTM

File: terraform/transform_provider.go (hunk 3 above)
Comment (mitchellh) [inline terraform/transform_provider.go]: Yep, we just check for the "." and assume it exists because proper smeantic checks like that should happen earlier.
