### PR TITLE
Fix destroy-time handling of outputs and local values

### LINKED ISSUE #17158: Wrong parsing ot the destroy-time provisioner command, during a targeted destroy
### Terraform Version

```
Terraform v0.11.2                                  
+ provider.null v1.0.0    
```

### Terraform Configuration Files

```
locals {
  msg_creation = "I should be shown at creation-time"
  msg_destruction = "I should be shown at destruction-time"
}

resource "null_resource" "myresource" {
  provisioner "local-exec" {
    command = "echo ${local.msg_creation}"
  }
  provisioner "local-exec" {
    command = "echo ${local.msg_destruction}"
    when = "destroy"
  }
}
```

### Expected Behavior

Doing a targeted destroy of `myresource` should execute the destroy-time provisioner, and then remove the resource from the state.

### Actual Behavior

Invoking `terraform destroy --target null_resource.myresource --force` prints out a possibly faulty error message:
```
null_resource.myresource: Refreshing state... (ID: 95776629882402507)
null_resource.myresource: Destroying... (ID: 95776629882402507)
null_resource.myresource: Provisioning with 'local-exec'...

Error: Error applying plan:

1 error(s) occurred:

* null_resource.myresource (destroy): 1 error(s) occurred:

* local-exec provisioner command must be a non-empty string

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

It's worth noting that this error is not printed out when doing a targetless destroy, e.g. `terraform destroy --force`. Also, a targeted apply does not incur in any problems.

### Steps to Reproduce

Given the above config:
1. `terraform init`
2. `terraform apply --auto-approve`
3. `terraform destroy --target null_resource.myresource --force`

### Found workaround

The workaround i used to overcome this problem might be useful in identifying the cause: to make the above steps work, I added the variable that appears in the destroy-time command into the creation-time provisioner block, as a comment.

Thus, the following configuration ensures that the `terraform destroy --target null_resource.myresource --force` works as well (notice the commented variable, in the creation-time provisioner command):
```
locals {
  msg_creation = "I should be shown at creation-time"
  msg_destruction = "I should be shown at destruction-time"
}

resource "null_resource" "myresource" {
  provisioner "local-exec" {
    command = "echo ${local.msg_creation} #${local.msg_destruction}"
  }
  provisioner "local-exec" {
    command = "echo ${local.msg_destruction}"
    when = "destroy"
  }
}
```

### PR DESCRIPTION
**Pull request by jbardin**
Because destroy time provisioners are not evaluated until the destroy operation, and outputs and locals are "dynamic" in the sense that they can be evaluated on demand, we always need to evaluate them, even during destroy.

Since the destroy-time local and output nodes are no longer a
"destroy" operation, the order of evaluation need to be reversed. Take
the existing `DestroyValueReferenceTransformer` and change it to reverse
the outgoing edges, rather than in incoming edges. This makes it so that
any dependencies of a local or output node are destroyed after
evaluation.

Previously, outputs were removed during destroy from the same
"Applyable" node type that evaluates them. Now that we need to possibly
both evaluate and remove outputs during an apply, we add a new node -
`NodeDestroyableOutput`.

This new node is added to the graph by the `DestroyOutputTransformer`,
which makes the new destroy node depend on all descendants of the output
node.  This ensures that the output remains in the state as long as
everything which may interpolate the output still exists

Also, since outputs and local nodes are always evaluated, interpolation can fail
if they reference a resource form the configuration that isn't in the state. The new `PruneUnusedValuesTransformer` removes unused value nodes from the graph.

Throughout this PR, a number of unrelated tests went through failure, due to the attempted interpolation of "id" attributes which weren't in the state. Add a failsafe in the interpolation function to fallback on the `ID` field when the attribute no longer exists. We should plan in the future to only have a single location for a resource ID.

Fixes #17158, #17181, #16907, #16420, #14450, probably others

### CODE REVIEW

File: terraform/interpolate.go [hunk 1]
```diff
@@ -518,6 +518,16 @@ func (i *Interpolater) computeResourceVariable(
 		return &v, err
 	}
 
+	// special case for the "id" field which is usually also an attribute
+	if v.Field == "id" && r.Primary.ID != "" {
```
Comment (apparentlymart) [inline terraform/interpolate.go]: Is this something that can really happen in practice, or was this more just a result of us tending to be lazy about fully-constructing state in tests?

Not objecting to doing it to be safe in the mean time, but just curious as to what tripped this up and prompted you to add the branch here.

(The new provider protocols and state format no longer have this special `ID` field, as you know, so an end to this odd special-case is not too far in the future but of course we'll need to watch out during that change for situations like this were we're doing something special to keep the two aligned.)

File: terraform/node_local.go [hunk 2]
```diff
@@ -59,38 +59,8 @@ func (n *NodeLocal) References() []string {
...
-				Node: &EvalSequence{
-					Nodes: []EvalNode{
-						&EvalDeleteLocal{
-							Name: n.Config.Name,
-						},
-					},
-				},
-			},
-		},
+	return &EvalLocal{
```
Comment (apparentlymart) [inline terraform/node_local.go]: This is _much_ nicer!

File: terraform/node_output.go [hunk 3]
```diff
@@ -83,19 +83,65 @@ func (n *NodeApplyableOutput) EvalTree() EvalNode {
...
-					Name: n.Config.Name,
-				},
-			},
 		},
 	}
 }
+
+// NodeDestroyableOutput represents an output that is "destroybale":
+// its application will remove the output from the state.
+type NodeDestroyableOutput struct {
```
Comment (apparentlymart) [inline terraform/node_output.go]: We have a special behavior for outputs under `-target` that ensures that they stay in the graph as long as any dependency is present. Do you think we need to do the same for destroy here too?

My initial instinct is yes, so that if I run `terraform destroy -target=aws_instance.foo` we'd still visit an output whose expression is `"${aws_instance.foo.id}"` and remove it, though it's _tricky_ if the expression is instead `"${aws_instance.foo.id} ${aws_instance.bar.id}"`.

In that multi-dependency case, I suppose maybe it's _right_ that we'd remove it from state anyway, because the expression is no longer resolvable anyway (there would be an error if we tried to eval it). Not totally sure, though... :thinking: 

BTW, the `TargetDownstream` function implemented by `NodeApplyableOutput` is what triggers this special behavior, and so that's what we'd add here if we want to retain the destroy nodes too.

File: terraform/interpolate.go (hunk 1 above)
Comment (jbardin) [reply terraform/interpolate.go]: yeah, it's a destroy-time issue, and we do run into it quite often. I'm actually not sure what order of operations through helper/schema get us in this situation, but as you said it is hopefully going away so this would only be temporary. I added the check now because the extra local/output evaluations during destroy are much more likely to encounter the situation.

File: terraform/node_output.go (hunk 3 above)
Comment (jbardin) [reply terraform/node_output.go]: I _thought_ this was doing the right thing here, but now you have me questioning whether I understood the TargetDownstream code correctly. Let me run some tests to confirm here.

If we intend to remove all but the root module outputs from the state, it's kind of a moot point, since the targeted destroy is going to at least break the output temporarily until there's another apply to reify the missing resources for interpolation.

I think removing the root output is OK too. If a remote state is looking for it, it's probably better that it appear as missing and require fixing rather than using a known stale value.

Comment (jbardin) [reply terraform/node_output.go]: Descendants, Ancestors, Upstream, Downstream, (Up|Down|In|Out)Edges 🤕 

You're right, this was missed in some cases by targeting. `GraphNodeTargetDownstream` is an easy fix, since the dependency set of the destroy node is just the output and its ancestors.

**Comment by jbardin** [comment]
Well, the commit message tells you what the _result_ is, rather than what it's doing! It's removing the output, by _keeping_ the NodeDestroyableOutput in the graph ;)
