### PR TITLE
provider/aws: Fix issue in updating Route 53 records on refresh/read.

### LINKED ISSUE #1413: Dynamically updated Route53 records are not destroyed
I have a configuration in which I create a bunch of A records in route53 into pre-existing hosted zones (both public and private). These creation of these records is intended to be managed by Terraform, but they are dynamically updated during runtime (not by Terraform) to point to instances created by autoscaling groups as necessary.

This is all working great with the exception of destruction of these A records when tearing down with Terraform. Terraform reports that all the resources, including the A records, were destroyed successfully but the A records still exist in route53.

I suspect this is because the original placeholder IP address for the A records was changed outside of Terraform and that it is submitting a Route53 change-set to delete the record with the original IP address as the record value. Because Route53 finds no matches for the original values, it does nothing.

### PR DESCRIPTION
**Pull request by catsby**
Route 53 records were silently erroring out when saving the records returned
from AWS, because they weren't being presented as an array of strings like we
expected.

This PR Introduces `flattenResourceRecords` to `structure.go`, used to flatten `[]route53.ResourceRecord` into an array of strings and correctly update the local state of records. We also no longer silently ignore this error.

This basically fixes #1413, in such that the local state is updated, and subsequent applying of `destroy` will actually destroy the record.

### CODE REVIEW

File: builtin/providers/aws/resource_aws_route53_record.go [hunk 1]
```diff
@@ -184,7 +184,10 @@ func resourceAwsRoute53RecordRead(d *schema.ResourceData, meta interface{}) erro
 
 		found = true
 
-		d.Set("records", record.ResourceRecords)
+		err := d.Set("records", flattenResourceRecords(record.ResourceRecords))
+		if err != nil {
+			log.Printf("[DEBUG] Error setting records for: %s, error: %#v", en, err)
```
Comment (phinze) [inline builtin/providers/aws/resource_aws_route53_record.go]: Should we return this error instead of just logging it?

File: builtin/providers/aws/structure.go [hunk 2]
```diff
@@ -251,3 +252,11 @@ func flattenAttachment(a *ec2.NetworkInterfaceAttachment) map[string]interface{}
 	att["attachment_id"] = *a.AttachmentID
 	return att
 }
+
+func flattenResourceRecords(recs []route53.ResourceRecord) []string {
+	strs := make([]string, 0, len(recs))
+	for _, r := range recs {
+		strs = append(strs, *r.Value)
```
Comment (phinze) [inline builtin/providers/aws/structure.go]: Is r.Value ever a nil pointer? If not that's AOK just wanted to double check.

File: builtin/providers/aws/resource_aws_route53_record.go (hunk 1 above)
Comment (catsby) [inline builtin/providers/aws/resource_aws_route53_record.go]: Totally wasn't sure on what to do there. I'm cool with bubbling up the error

File: builtin/providers/aws/structure.go (hunk 2 above)
Comment (catsby) [inline builtin/providers/aws/structure.go]: no idea, so I'll sprinkle some safety on it

**Comment by willmcg** [comment]
I've run this change against my full configuration and can confirm that the modified DNS A records are now being correctly deleted during destroy.

Thanks!  You guys rock.

This pace of evolution and responsiveness to issues is why I chose Terraform.

**Comment by catsby** [comment]
I've broken an acceptance test with TXT records here, fixing...

**Comment by catsby** [comment]
Updated to fix regression with TXT records. @phinze take a gander when you get a minute

**Comment by mitchellh** [comment]
Route53 API still sad, but LGTM

**Comment by phinze** [comment]
:+1:
