### PR TITLE
terraform: flattening multi-level modules works

### LINKED ISSUE #1854: Error: "unknown variable accessed" when using module
Config:

```js
variable "instance_type" {
  default = "t2.micro"
}

variable "region" {
  default = "us-west-2"
}

module "ami" {
  source = "github.com/terraform-community-modules/tf_aws_ubuntu_ami/ebs"
  region = "${var.region}"
  distribution = "trusty"
  instance_type = "${var.instance_type}"
}

resource "aws_instance" "web" {
  ami = "${module.ami.ami_id}"
  instance_type = "${var.instance_type}"
}
```

Commands:

```
terraform get
terraform plan
```

Output:

```
Refreshing Terraform state prior to plan...

Error refreshing state: 2 error(s) occurred:

* 1:3: unknown variable accessed: var.architecture in:

${var.architecture}
* 1:3: unknown variable accessed: var.distribution in:

${var.distribution}
```

Debug log: https://gist.github.com/phinze/89f913540c40cb2656fc

### PR DESCRIPTION
**Pull request by mitchellh**
Fixes #1854 

Multiple nesting levels of modules were not being flattened properly. This adds a test for that and fixes it.

### CODE REVIEW

File: terraform/transform_flatten.go [hunk 1]
```diff
@@ -53,6 +53,12 @@ func (t *FlattenTransformer) Transform(g *Graph) error {
 
 		// Go through the subgraph and flatten all the nodes
 		for _, sv := range subgraph.Vertices() {
+			// If the vertex already has a subpath then we assume it has
+			// already been flattened. Ignore it.
+			if _, ok := sv.(GraphNodeSubPath); ok {
```
Comment (phinze) [inline terraform/transform_flatten.go]: I'm somewhat concerned that without something more directly expressive like `.(GraphNodeFlattened)` w/ `Flattened() bool` this would be easy to mess up elsewhere down the road.

But only somewhat. Not a dealbreaker, just food for thought.

**Comment by phinze** [comment]
LGTM - will re-test my example once this lands.

File: terraform/transform_flatten.go (hunk 1 above)
Comment (mitchellh) [inline terraform/transform_flatten.go]: Yeah, I thought of that too, but I didn't want to risk missing adding that interface to every flat node. I'd rather do this and then just refactor later to have EVERY node have a `Path` and do it without flattening at all.

Comment (phinze) [inline terraform/transform_flatten.go]: :ok_hand:
