### PR TITLE
internal/providercache: Fix bug when symlink fails

### LINKED ISSUE #25652: Terraform 0.13 fails to install provider from cache on Windows 7
### Terraform Version

```
Terraform v0.13.0-rc1
```

#### Official providers

```terraform
provider "aws" {}
```

#### Custom providers

```terraform
provider "custom" {}
```

### Debug Output

https://gist.github.com/cmbrad/c0e9bd1926657d23dbac244ffe66e31a

### Expected Behavior

Terraform successfully installs providers.

### Actual Behavior

Terraform fails to install providers and fails with an error message.

#### Cached official providers

1. Be running on Windows 7 (or some other OS with no ability to symlink)
2. `TF_PLUGIN_CACHE_DIR=my/cache/dir`
3. `terraform init`

#### Custom providers only

1. Be running on Windows 7 (or some other OS with no ability to symlink)
2. Install a local plugin to %APPDATA%/terraform.d/plugins/my-local-hostname.com/myorg/myplugin/1.0.0/windows_amd64/my-provider-v1.0.0_x4.exe
3. `terraform init`

### Additional Context

By the look of the code I think the the CopyDir arguments are flipped, ref: https://github.com/hashicorp/terraform/blob/master/internal/providercache/package_install.go#L172

Might be fixed by:
`err = copydir.CopyDir(absNew, absCurrent)` -> `err = copydir.CopyDir(absCurrent, absNew)`

### PR DESCRIPTION
**Pull request by alisdair**
When installing a provider which is already cached, we attempt to create a symlink from the install directory targeting the cache. If symlinking fails due to missing OS/filesystem support, we instead want to copy the cached provider.

The fallback code to do this would always fail, due to a missing target directory. This commit fixes that. I was unable to find a way to add automated tests around this, but I have manually verified the fix on Windows 8.1.

Fixes #25652

### Reproduction/verification

Steps to reproduce:

1. On a Windows 7 or 8 host, create a simple configuration:

```hcl
provider "random" {}
```

1. Run `terraform init` to download the random provider
1. Copy the `.terraform\plugins` folder to `%APPDATA%\terraform.d`
1. Remove the `.terraform` folder
1. Rerun `terraform init`

With 0.13.0-rc1:

With this commit:

### CODE REVIEW

File: internal/providercache/package_install.go [hunk 1]
```diff
@@ -157,7 +157,7 @@ func installFromLocalDir(ctx context.Context, meta getproviders.PackageMeta, tar
 
 	parentDir := filepath.Dir(absNew)
 	err = os.MkdirAll(parentDir, 0755)
-	if err != nil && os.IsExist(err) {
+	if err != nil {
 		return nil, fmt.Errorf("failed to create parent directories leading to %s: %s", targetDir, err)
```
Comment (alisdair) [inline internal/providercache/package_install.go:161]: This additional check didn't look right to me. There's no further checking of `err` below this, and I can't see any way for `MkdirAll` to fail with an `IsExist` error—if a directory exists at any step of the given path, it returns `nil`.
