### PR TITLE
backend/local: Handle interactive prompts for variables in UI layer

### LINKED ISSUE #21659: Error: Unassigned variable
Hi, I'm trying to run atlantis on AWS Fragate through https://github.com/terraform-aws-modules/terraform-aws-atlantis.

I've set up everything but am getting a wierd error. I am fairly sure that the variables are set through environment.

### Crash Output
```
running "/usr/local/bin/terraform plan -input=false -refresh -no-color -out \"/home/atlantis/.atlantis/repos/meshwatch/infrastructure/terraform-gsuite/1/default/default.tfplan\"" in "/home/atlantis/.atlantis/repos/meshwatch/infrastructure/terraform-gsuite/1/default": exit status 1

Error: Unassigned variable

The input variable "access_key" has not been assigned a value. This is a bug
in Terraform; please report it in a GitHub issue.


Error: Unassigned variable

The input variable "secret_key" has not been assigned a value. This is a bug
in Terraform; please report it in a GitHub issue.


Error: Unassigned variable

The input variable "region" has not been assigned a value. This is a bug in
Terraform; please report it in a GitHub issue.
```

### PR DESCRIPTION
**Pull request by apparentlymart**
During the 0.12 work we intended to move all of the variable value collection logic into the UI layer (command package and backend packages) and present them all together as a unified data structure to Terraform Core. However, we didn't quite succeed because the interactive prompts for unset required variables were still being handled _after_ calling into Terraform Core.

Here we complete that earlier work by moving the interactive prompts for variables out into the UI layer too, thus allowing us to handle final validation of the variables all together in one place and do so in the UI layer where we have the most context still available about where all of these values are coming from.

This allows us to fix a problem where previously disabling input with `-input=false` on the command line could cause Terraform Core to receive an incomplete set of variable values, and fail with a bad error message. (Fixes #21659)

---

This refactoring also exposed a few cases where tests were not correctly constructing a realistic invocation of Terraform but had been getting away with it before due to the missing validation and a lucky coincidence. Therefore this PR includes some fixes for tests that were valid situations incorrectly framed, and some removals of tests that were testing situations that are impossible in normal use because the caller is responsible for preventing them from arising.

There are a few new tests here but since the overall functionality is still the same as it was before, and we've just pushed the concerns about a bit here, our existing context tests, command tests, and end-to-end tests were already covering the affected behaviors here and continue to do so.

I have also manually verified the correct behavior of various commands against a local test configuration with various combinations of required and optional variables.

---

As a consequence of this refactoring, the scope of `terraform.Context.Input` is now reduced to only gathering provider configuration arguments. Ideally that too would move into the UI layer somehow in a future commit, but that's a problem for another day.

### CODE REVIEW

File: backend/local/backend_local.go [hunk 1]
```diff
@@ -136,14 +136,27 @@ func (b *Local) contextDirect(op *backend.Operation, opts terraform.ContextOpts)
...
+	if op.AllowUnsetVariables {
+		// Rather than prompting for input, we'll just stub out the required
+		// but unset variables with unknown values to represent that they are
+		// placeholders for values the user would need to provide for other
+		// operations.
+		rawVariables = b.stubUnsetRequiredVariables(op.Variables, config.Module.Variables)
+	} else {
+		// If interactive input is enabled, we might gather some more variable
+		// values through interactive prompts.
+		// TODO: Need to route the operation context through into here, so that
```
Comment (mildwonkey) [inline backend/local/backend_local.go]: Can you make a comment (here, not necessarily in the code) about why this TODO isn't being done now?

File: backend/local/backend_local.go [hunk 2]
```diff
@@ -245,6 +258,159 @@ func (b *Local) contextFromPlanFile(pf *planfile.Reader, opts terraform.ContextO
...
+	}
+	if len(needed) == 0 {
+		return existing
+	}
+
+	log.Printf("[DEBUG] backend/local: will prompt for input of unset required variables %s", needed)
+
+	// If we get here then we're planning to prompt for at least one additional
+	// variable's value.
+	sort.Strings(needed) // prompt in lexical order
```
Comment (mildwonkey) [inline backend/local/backend_local.go]: This is a question, not a suggestion, despite the phrasing: 

If `needed` wasn't sorted, what order would the variables show up in? If the variables are (at least per-fil) in the same order that they are in the configuration files it might make more sense to the user if the variables are presented in that order. I'm thinking of scenarios where one has a lot of related variables lumped together in each file and where the variables make more sense when thought of as a whole (as opposed to seeing them "split up" in lexical order).

File: backend/local/backend_local.go [hunk 3]
```diff
@@ -245,6 +258,159 @@ func (b *Local) contextFromPlanFile(pf *planfile.Reader, opts terraform.ContextO
...
+	Name     string
+	WantType cty.Type
+}
+
+var _ backend.UnparsedVariableValue = unparsedUnknownVariableValue{}
+
+func (v unparsedUnknownVariableValue) ParseVariableValue(mode configs.VariableParsingMode) (*terraform.InputValue, tfdiags.Diagnostics) {
+	return &terraform.InputValue{
+		Value:      cty.UnknownVal(v.WantType),
+		SourceType: terraform.ValueFromInput,
```
Comment (mildwonkey) [inline backend/local/backend_local.go]: Another just-a-question: I'm not familiar with the usage of `SourceType`. Is there value in a SourceType that indicates that this value was explicitly left unset vs. the given `terraform.ValueFromInput`?

File: terraform/context_validate_test.go [hunk 4]
```diff
@@ -87,35 +87,28 @@ func TestContext2Validate_varMapOverrideOld(t *testing.T) {
...
-				Value:      cty.StringVal("bar"),
-				SourceType: ValueFromCaller,
-			},
-		},
+		Variables: InputValues{},
 	})
-
-	diags := c.Validate()
 	if !diags.HasErrors() {
+		// Error should be: The input variable "provider_var" has not been assigned a value.
```
Comment (mildwonkey) [inline terraform/context_validate_test.go]: Thank you for adding these, I'll be sure to start doing the same!

File: backend/local/backend_local.go (hunk 1 above)
Comment (apparentlymart) [reply backend/local/backend_local.go]: I don't have any _grand_ reason for it... just wanted to keep the function signature changes to a minimum here in order to keep the diff minimal, and the context wasn't routed in before either so this hasn't made things any worse than they used to be.

File: backend/local/backend_local.go (hunk 2 above)
Comment (apparentlymart) [reply backend/local/backend_local.go]: The variable definitions and values both live in maps so the _default_ sort here would be pseudorandom.

In principle we could try to sort them by their source locations in order to recover the order in source code that you're thinking about here. So far the only precedent we've had for sorting things in lexical order is that we sort diagnostic messages that way in the hope of them appearing in an order that allows you to work through them one by one; I expect we could adapt similar logic here but we'd probably need to generalize some logic for actually sorting by the source locations so that it can be used from multiple locations.

I'm open to doing that, but I'd rather pursue it as a separate change, since my goal here was to retain the same user-facing behavior we had before and just move the logic to a different place in the code.

File: backend/local/backend_local.go (hunk 3 above)
Comment (apparentlymart) [reply backend/local/backend_local.go]: In this particular case the meaning I was trying to represent here was "this isn't known yet, but it will eventually be determined by user input" (as long as the user changes nothing else in the mean time, of course).

In practice we don't currently really make strong use of this `SourceType`. It's used to lightly adjust some error message phrasing so that the messages can say things like "...which you set on the command line", or "...which you set in foo.tf", etc. We could add a new source type that would mean something like "unknown source" to go with the "unknown value". Perhaps we'd use that to suppress certain error messages altogether, like we do with unknown values in HCL. :thinking:

File: terraform/context_validate_test.go (hunk 4 above)
Comment (apparentlymart) [reply terraform/context_validate_test.go]: Honestly, if I were writing these tests from scratch today I'd rather make the test code itself assert the error message, but I didn't want to mess _too_ much with existing tests here and distract from the main goal...

**Comment by apparentlymart** [comment]
After pondering @mildwonkey's questions/feedback for a little while, I'm going to go ahead and merge this in the interests of addressing the main issue at hand but will keep these other good ideas in mind for future work in this area, at which time we'll hopefully have time to consider the design implications more fully, as opposed to aiming for a minimal refactor to fix the bug.

**Comment by vroy** [comment]
This impacted `terraform import` in that all variables now have to be provided even for cases where they wouldn't have impact on the import. Would that be the intended behaviour moving forward?
