### PR TITLE
provider/aws: Set aws_alb security_groups computed

### LINKED ISSUE #8264: provider/aws: ALB gets recreated when no SG is defined
### Terraform Version

```
Terraform v0.7.1-dev (dd2740d4fec9d1846026301e0b527a55246ccf52)
```

### Affected Resource(s)

- `aws_alb`

### Terraform Configuration Files
```hcl
resource "aws_vpc" "main" {
  cidr_block = "10.10.0.0/16"
}

resource "aws_subnet" "first" {
  cidr_block = "10.10.1.0/24"
  vpc_id = "${aws_vpc.main.id}"
}

resource "aws_subnet" "second" {
  cidr_block = "10.10.2.0/24"
  vpc_id = "${aws_vpc.main.id}"
}

resource "aws_alb" "main" {
  name            = "test-alb-tf"
  subnets         = ["${aws_subnet.first.id}", "${aws_subnet.second.id}"]
}
```

### Expected Behavior

```
$ terraform plan
```

No diff.

### Actual Behavior

```
$ terraform plan
```
```
-/+ aws_alb.main
    dns_name:                   "test-alb-tf-319967521.us-west-2.elb.amazonaws.com" => "<computed>"
    enable_deletion_protection: "false" => "false"
    idle_timeout:               "60" => "60"
    internal:                   "false" => "<computed>"
    name:                       "test-alb-tf" => "test-alb-tf"
    security_groups.#:          "1" => "0" (forces new resource)
    security_groups.289196067:  "sg-81cbcae4" => ""
    subnets.#:                  "2" => "2"
    subnets.6620723:            "subnet-f9297b8d" => "subnet-f9297b8d"
    subnets.704553415:          "subnet-f5c3a873" => "subnet-f5c3a873"
    vpc_id:                     "vpc-fd351998" => "<computed>"
    zone_id:                    "Z1H1FL5HABSF5" => "<computed>"
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

### PR DESCRIPTION
**Pull request by jen20**
This commit fixes #8264 by making the `security_groups` attribute on `aws_alb` resources computed, allowing the default security group assigned by AWS to not generate perpetual plans forcing new resources.

Part of #8137.

### CODE REVIEW

**Comment by jen20** [comment]
cc @radeksimko

File: builtin/providers/aws/resource_aws_alb_test.go [hunk 1]
```diff
@@ -334,3 +368,69 @@ resource "aws_security_group" "alb_test" {
...
+  cidr_block              = "${element(var.subnets, count.index)}"
+  map_public_ip_on_launch = true
+  availability_zone       = "${element(data.aws_availability_zones.available.names, count.index)}"
+
+  tags {
+    TestName = "TestAccAWSALB_basic"
+  }
+}
+
+resource "aws_security_group" "alb_test" {
```
Comment (radeksimko) [inline builtin/providers/aws/resource_aws_alb_test.go]: Is there any reason why not leave the `aws_security_group` out completely from this config?

**Comment by radeksimko** [comment]
Except that single nitpick this LGTM. ALB acceptance tests passing 👌

File: builtin/providers/aws/resource_aws_alb_test.go (hunk 1 above)
Comment (jen20) [inline builtin/providers/aws/resource_aws_alb_test.go]: Yup good call, I'll go through and fix this up before merging.
