### PR TITLE
provisioner/file: don’t use `d.GetOk` in validation functions

### LINKED ISSUE #15177: 0.9.7 breaks provisioners using template_file with "Must provide one of 'content' or 'source'"
`terraform plan` fails when using a template_file in a file provisioner

### Terraform Version
`0.9.7`

### Affected Resource(s)
All

### Terraform Configuration Files
```hcl
data "template_file" "test" {
  template = "${file("${path.module}/test.tpl")}"
}

resource "test_resource" "test" {
  required = "${count.index}"
  required_map {
    key1 = "value1"
    key2 = "value2"
  }

  provisioner "file" {
    content = "${data.template_file.test.rendered}"
    destination = "foo"
  }
}
```

### Expected Behavior
Plan should succeed with no error.  here is a sample output when using terraform `0.9.6`
```
$GOPATH/bin/terraform_0.9.6 plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.template_file.test: Refreshing state...
The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed. Cyan entries are data sources to be read.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

+ test_resource.test
    computed_from_required:       "<computed>"
    computed_list.#:              "<computed>"
    computed_map.%:               "<computed>"
    computed_read_only:           "<computed>"
    computed_read_only_force_new: "<computed>"
    computed_set.#:               "<computed>"
    optional_computed_force_new:  "<computed>"
    optional_computed_map.%:      "<computed>"
    required:                     "0"
    required_map.%:               "2"
    required_map.key1:            "value1"
    required_map.key2:            "value2"


Plan: 1 to add, 0 to change, 0 to destroy.
```

### Actual Behavior
using 0.9.7...
```
terraform plan                  
1 error(s) occurred:

* test_resource.test: Must provide one of 'content' or 'source'
```

### Steps to Reproduce
1. `terraform plan`

### PR DESCRIPTION
**Pull request by svanharmelen**
It turns out that `d.GetOk` also returns `false` when the user _did_ actually supply a value for it in the config, but the value itself needs to be evaluated before it can be used.

@mitchellh I must admit this is a bit different then my perception was about how (and when) to use `d.GetOk`.

I was fully under the impression that it would only return `false` if a value was not set in the config by the user and in all other cases it would return `true`. Regardless whether the value needed any kind of interpolation or evaluation.

That way you could always safely use this function to determine if the value you retrieved was put there by the user or was written back to the state during the execution of a `Read()` function of a resource.

The docs seem to (in part) support my assumptions:

```
GetOk returns the data for the given key and whether or not the key has
been set to a non-zero value at some point.
```

So did I read/understand it's usage incorrectly? And if so, is there a way to determine if a value is set by a user or that it was written back by the resource?

Or did I understand it correctly and should the current behaviour of `d.GetOk` be considered a bug? Thx!

_EDIT:_ Fixes #15177

### CODE REVIEW

File: builtin/provisioners/file/resource_provisioner.go [hunk 1]
```diff
@@ -79,17 +79,11 @@ func applyFn(ctx context.Context) error {
 }
 
 func validateFn(d *schema.ResourceData) (ws []string, es []error) {
-	numSrc := 0
-	if _, ok := d.GetOk("source"); ok == true {
-		numSrc++
+	if d.Get("source").(string) == "" && d.Get("content").(string) == "" {
```
Comment (onorua) [inline builtin/provisioners/file/resource_provisioner.go]: this will not catch the situation when you have both source and content defined

Comment (svanharmelen) [inline builtin/provisioners/file/resource_provisioner.go]: That is not needed, as that will be catched by the `ConflictsWith` configs defined in the schema.

Comment (onorua) [inline builtin/provisioners/file/resource_provisioner.go]: What about tests? This functionality was broken for 2 releases since 0.9.6, and this is core functionality. Would be nice to catch this, so far I can see current tests are not catching the problem described in #15177

**Comment by svanharmelen** [comment]
Working on an improved version of this fix... Will update later this evening.

**Comment by svanharmelen** [comment]
@apparentlymart could you have a look at this one? I refactored it after the chat we had yesterday and I think the current solution is a very clean one that circumvents all the issues we talked about...

**Comment by svanharmelen** [comment]
Of course... Now were happy with the solution, I'll add some tests tomorrow before merging the PR. Thx!

**Comment by svanharmelen** [comment]
@apparentlymart added a test that fails with the reported error when not using this patch... Guess that wraps up this PR right?

File: builtin/provisioners/file/resource_provisioner.go (hunk 1 above)
Comment (svanharmelen) [inline builtin/provisioners/file/resource_provisioner.go]: Just added a test to the latest revision of this fix...

File: builtin/provisioners/file/resource_provisioner_test.go [hunk 2]
```diff
@@ -48,6 +48,21 @@ func TestResourceProvider_Validate_good_content(t *testing.T) {
 	}
 }
 
+func TestResourceProvider_Validate_good_unknown_variable_value(t *testing.T) {
+	c := testConfig(t, map[string]interface{}{
+		"content":     "74D93920-ED26-11E3-AC10-0800200C9A66",
```
Comment (apparentlymart) [inline builtin/provisioners/file/resource_provisioner_test.go]: I assume this is the "unknown variable value". If possible, it'd be preferable to use one of the global variables that contain this, so that in future when this stops being a magic string we'll be able to track down uses of it to update them.

It's available in a few places, though off the top of my head I'm not sure what's the most convenient to access from here. It's a global variable called `UnknownValue` or `UnknownVariableValue` in a few different packages.

**Comment by svanharmelen** [comment]
@apparentlymart that's actually a very good point... Thx! Updated the test so it uses the constant `config.UnknownVariableValue` instead 👍

**Comment by shantanugadgil** [comment]
Hi,
I was wondering if this fixes #15186 ?
I can't get to my test setup for a while, so thought would ask!

Regards,
Shantanu

**Comment by svanharmelen** [comment]
Yes, indeed. Thanks for the pointer, updated and closed the other issue as well.
