### PR TITLE
command: Taint should respect required_version

### LINKED ISSUE #23049: `terraform taint` Does Not Check Terraform Version
### Terraform Version
```
Terraform v0.12.8
+ provider.google v2.16.0
+ provider.null v2.1.2
+ provider.random v2.2.1
# and
Terraform v0.12.10
+ provider.google v2.16.0
+ provider.null v2.1.2
+ provider.random v2.2.1
```

### Terraform Configuration Files
<!--
Paste the relevant parts of your Terraform configuration between the ``` marks below.

For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file. For security, you can also encrypt the files using our GPG public key.
-->

```hcl
###################
# State Management #
###################

# manage state remotely with history in case something goes horribly wrong
terraform {                                                                                                                                                                                                           
  required_version = "0.12.8"
  backend "remote" {
      hostname = "app.terraform.io"
      organization = "..."
      workspaces {
        prefix = "..."
      }
  }
}
```

### Expected Behavior
When I run `terraform taint` with a version of terrafrom incompatible with my remote state settings, I should get an error like the below:

```
Error: Unsupported Terraform Core version

  on main.tf line 7, in terraform:
   7:   required_version = "0.12.8"

This configuration does not support Terraform version 0.12.10. To proceed,
either choose another supported Terraform version or update this version
constraint. Version constraints are normally set for good reason, so updating
the constraint may lead to other errors or unexpected behavior.
```

### Actual Behavior
The terraform version was ratcheted up to v0.12.10 in Terraform Cloud (with no way to revert as far I know).

```
Error: Error loading state: state snapshot was created by Terraform v0.12.10, which is newer than current v0.12.8; upgrade to Terraform v0.12.10 or greater to work with this state
```

### Steps to Reproduce
Run the below on a project that specifies v0.12.8 using terraform v0.12.10
`terraform0.12.10 taint $resource0.12.8`

### Additional Context
Terraform Cloud is being used to manage state remotely, but everything is being executed locally.

### LINKED ISSUE #26325: Terraform taint does not respect required_version
### Terraform Version

```
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/external v1.2.0
+ provider registry.terraform.io/hashicorp/google v3.39.0
+ provider registry.terraform.io/hashicorp/google-beta v3.39.0
+ provider registry.terraform.io/hashicorp/http v1.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.2
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v2.3.0
+ provider registry.terraform.io/hashicorp/template v2.1.2
+ provider registry.terraform.io/hashicorp/tls v2.2.0
+ provider registry.terraform.io/hashicorp/vault v2.14.0
```

### Terraform Configuration Files

```terraform
N/A
```

### Debug Output

N/A
### Crash Output

N/A
### Expected Behaviour

`terraform taint my.special.resource` should respect the `required_version` in `versions.tf` and not proceed if there is a mismatch, similar to `terraform apply`.
### Actual Behaviour

We have `required_version = "0.13.2"` set, but Terraform v0.13.3 happily tainted the state and set a new minimal version in the state.
### Steps to Reproduce

Run `terraform taint my.special.resource` with v0.13.3 on a state file from v0.13.2.
### Additional Context

We use Homebrew as a makeshift package manager due to inadequacies in macOS. It is easy to 'accidentally' upgrade packages with no easy way to roll back to an older version when the upgrade is discovered. Therefore we set a fixed Terraform version to prevent accidental upgrades of the state file.

Terraform was upgraded on my machine. `terraform taint` was able to taint my state file without issue. The subsequent `terraform apply` immediately failed because the Terraform version did not match the value in `required_version`. After downgrading, `terraform apply` failed again because the state file was set with a higher Terraform version.

### PR DESCRIPTION
**Pull request by alisdair**
Despite not requiring the configuration for any other reason, the taint subcommand should not execute if the required_version constraints cannot be met. Doing so can result in an undesirable state file upgrade.

Fixes #26325. Fixes #23049.

Question for reviewers: it feels to me like there ought to be a neater way of loading the config to check the constraints are met. Can you think of one? 🙏

### CODE REVIEW

**Review by jbardin — APPROVED** [review]

File: command/taint.go [hunk 1]
```diff
@@ -62,6 +64,34 @@ func (c *TaintCommand) Run(args []string) int {
 		return 1
 	}
 
+	// Load the config and check the core version requirements are satisfied
```
Comment (mildwonkey) [inline command/taint.go:67]: I'm not sure, but I'd be curious to see if the `earlyconfig` loader (examples in `init.go`) is sufficient and perhaps faster for this purpose.  `loadSingleModule` for e.g. will only load the root module:

https://github.com/hashicorp/terraform/blob/6d86cd46f7394e4d655a18fc2e977f1c670f668e/command/meta_config.go#L95-L97

Again, this might not actually be faster or better, but it might be worth looking at.

**Review by mildwonkey — APPROVED** [review]
I have no objections to this PR as-is, but I did leave a suggestion for alternative config loading that may or may not be useful.

File: command/taint.go (hunk 1 above)
Comment (alisdair) [reply command/taint.go:67]: Ah, I hadn't thought of that! Unfortunately I think we need to load and check the entire tree's version constraints. In particular, many public registry modules have fairly strict version requirements that we need to honour.
