### PR TITLE
command/format: Fix nested (JSON) object formatting

### LINKED ISSUE #19275: JSON-oriented diffs not working consistently
The new diff renderer for v0.12.0 includes a heuristic for detecting whether before and after strings are both JSON-formatted and showing a JSON structural diff.

...but the heuristic seems to not be good enough right now, since it's failing to produce diffs in some cases such as IAM policy JSON, while it works okay for simpler situations.

Structural diff of IAM policies is one of the main use-cases for this heuristic, so we should figure out what's going on here and ensure that this sort of JSON gets the structural diff treatment.

### PR DESCRIPTION
**Pull request by radeksimko**
Fixes #19275

----

I also realized (after fixing the original bug) that we render partially known strings, such as

```
  description = "Provider ${github_repository.aws.computed_field}"
```

as `(known after apply)`, which IMO deserves a completely separate issue.

### CODE REVIEW

File: command/format/diff.go [hunk 1]
```diff
@@ -742,20 +740,34 @@ func (p *blockBodyDiffPrinter) writeValueDiff(old, new cty.Value, indent int, pa
...
 			}
 			p.buf.WriteString("\n")
 
-			elemDiffs := ctySequenceDiff(old.AsValueSlice(), new.AsValueSlice())
-			for _, elemDiff := range elemDiffs {
-				p.buf.WriteString(strings.Repeat(" ", indent+2))
-				p.writeActionSymbol(elemDiff.Action)
-				p.writeValue(elemDiff.Value, elemDiff.Action, indent+4)
-				p.buf.WriteString(",\n")
+			if ty.IsTupleType() && ty.Length() > 0 && ty.TupleElementType(0).IsObjectType() {
```
Comment (radeksimko) [inline command/format/diff.go]: Here I just assumed that we'll never have tuples of multiple types, but I am not sure if it's a safe assumption at all. 🤔

Comment (apparentlymart) [reply command/format/diff.go]: Indeed it is _not_; the primary purpose of tuples is to allow separate types per element, and it's particularly relevant in a JSON context because cty tuple is the representation of a JSON array, and so users can write `["a", {}]` in a JSON argument which would become a `tuple([string, object({})]` value once parsed.

To get correct behavior here we may need to somehow combine the object-sequence behavior into `ctySequenceDiff`, and have it be the one to deal with any awkward single-element type changes.

**Comment by radeksimko** [comment]
@apparentlymart PTAL, I have abandoned the whole idea of comparing object similarity as the current implementation based on attribute existence was too simple and getting it right would be IMO hard. It was not in use anywhere anyway (practically dead code), so I assume deleting it cannot make things worse? 🤷‍♂️ 

I'm sure some more edge cases will come up over time, but this should render the most common cases correctly. 🤞 

Below are some real examples from the original issue.

### Before

screen shot 2019-01-23 at 11 51 13

screen shot 2019-01-23 at 13 35 18

### After

screen shot 2019-01-23 at 11 50 39

screen shot 2019-01-23 at 13 15 56
