### PR TITLE
Fix cloud integration's handling of TF_WORKSPACE environment variable

### LINKED ISSUE #33976: `terraform init`, `TF_WORKSPACE` errors after 1.6.0 release
### Terraform Version

```shell
Terraform v1.6.0
```

### Terraform Configuration Files

```terraform
terraform {
  cloud {
    organization = "XXXXX"
    workspaces {
      tags = [ "XXXXX" ]
    }
  }
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = ">= 4.28.0"
    }
  }
}
```

### Debug Output

The only thing in the stacktrace that looked somewhat relevant. It appears to be going to the "default" workspace when the TF_WORKSPACE environment variable defines something else
```
2023-10-04T19:00:18.825Z [TRACE] backend/local: state manager for workspace "default" will:
 - read initial snapshot from terraform.tfstate
 - write new snapshots to terraform.tfstate
 - create any backup at terraform.tfstate.backup
2023-10-04T19:00:18.825Z [TRACE] statemgr.Filesystem: reading initial snapshot from terraform.tfstate
2023-10-04T19:00:18.825Z [TRACE] statemgr.Filesystem: snapshot file has nil snapshot, but that's okay
2023-10-04T19:00:18.825Z [TRACE] statemgr.Filesystem: read nil snapshot
2023-10-04T19:00:18.825Z [TRACE] Meta.Backend: ignoring local "default" workspace because its state is empty
2023-10-04T19:00:18.825Z [TRACE] Meta.Backend: Terraform Cloud mode initialization type: ConfigChangeInPlace
2023-10-04T19:00:18.827Z [TRACE] ModuleInstaller: installing child modules for . into .terraform/modules
```

### Expected Behavior

Should have initialized successfully, as it was prior to the release of 1.6.0.

### Actual Behavior

│ Error: Invalid workspaces configuration
│ 
│   on main.tf line 5, in terraform:
│    5:   cloud ***
│ 
│ Only one of workspace "tags" or "name" is allowed.
│ 
│ The 'workspaces' block configures how Terraform CLI maps its workspaces for
│ this single
│ configuration to workspaces within a Terraform Cloud organization. Two
│ strategies are available:
│ 
│ tags - A set of tags used to select remote Terraform Cloud
│ workspaces to be used for this single
│ configuration. New workspaces will automatically be tagged with these tag
│ values. Generally, this
│ is the primary and recommended strategy to use.  This option conflicts with
│ "name".
│ 
│ name - The name of a single Terraform Cloud workspace to be
│ used with this configuration.
│ When configured, only the specified workspace can be used. This option
│ conflicts with "tags".

### Steps to Reproduce

NOTE: I can only reproduce this inside a git action runner, have not been able to replicate it with local commands
1. `terraform init`

### Additional Context

This issue appears to be common across all of our git actions, and it coincides with the release of version 1.6.0, which happened 1-2 hours ago at the time of writing this

### References

_No response_

### PR DESCRIPTION
**Pull request by nfagerlund**
Fixes #33976 

This bug was introduced in https://github.com/hashicorp/terraform/pull/33489 (adding `project` to the cloud config). Analyzing the flow of logic around config handling for the cloud backend took, a long time, which convinced me that a bug like this was honestly pretty inevitable — this code was too complex to safely edit. 

So, this PR refactors that whole zone to draw some sharper divisions of responsibility:

- `PrepareConfig` does almost nothing, as per the interface contract (which we were previously ignoring).
- Combining env vars with the received config block is now isolated in an immutable helper function, and the logic is now a bit more pedantic and obvious, hopefully making it harder to misunderstand in the future.
- `Configure` no longer delegates to the intensely side-effectful `setConfigurationFields` helper method to set fields on self; instead it just trades its cty config object for a dumb Go struct, sets a couple fields, and moves on. 

Notes for reviewers: 

- Probably easier to review this by-commit.
- LMK if you want these tests chopped down even further. I erred on the side of too much, since all the test cases already existed. 
- To test the behaviors interactively, you want to set TF_WORKSPACE with a variety of cloud block configs.
    - TF_WORKSPACE + name: Should error, with a newly added explanation instead of the old cryptic one ("workspaces not supported??")
    - TF_WORKSPACE + tags: Should work fine, and should select the active workspace from among the tagged ones.

## Target Release

1.6.1, as this bug was a disruptive regression. 

### BUG FIXES

- The `TF_WORKSPACE` environment variable once again works properly for selecting the active workspace when using the `cloud` block with workspace `tags`.

### CODE REVIEW

File: internal/cloud/backend_test.go [hunk 1]
```diff
@@ -138,7 +138,7 @@ func TestCloud_PrepareConfig(t *testing.T) {
 	}
 }
 
-func WithEnvVars(t *testing.T) {
+func TestCloud_configWithEnvVars(t *testing.T) {
```
Comment (brandonc) [inline internal/cloud/backend_test.go:141]: ❗

**Review by brandonc — APPROVED** [review]
Works great and nice refactor.

File: internal/cloud/backend_test.go (hunk 1 above)
Comment (nfagerlund) [reply internal/cloud/backend_test.go:141]: rite?
