### PR TITLE
provider/aws: Update state on `aws_elasticache_subnet_group` not found exception

### LINKED ISSUE #7062: refreshing aws_elasticache_subnet_group fails if resource does not exist
```
$ terraform -v
Terraform v0.6.16
```

```
Error refreshing state: 1 error(s) occurred:

* aws_elasticache_subnet_group.redis: CacheSubnetGroupNotFoundFault: Cache subnet group foo-bar not found.
	status code: 400, request id: d3329895-2d0a-11e6-855e-4b99d85a5fe7
```

I'm guessing it's just a matter of handling the failure case properly.  SQS had a similar issue at #6381

### PR DESCRIPTION
**Pull request by stack72**
Fixes #7062

make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSElasticacheSubnetGroup'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /vendor/)
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSElasticacheSubnetGroup -timeout 120m
=== RUN   TestAccAWSElasticacheSubnetGroup_basic
--- PASS: TestAccAWSElasticacheSubnetGroup_basic (44.62s)
=== RUN   TestAccAWSElasticacheSubnetGroup_update
--- PASS: TestAccAWSElasticacheSubnetGroup_update (73.74s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	118.379s

### CODE REVIEW

File: builtin/providers/aws/resource_aws_elasticache_subnet_group.go [hunk 1]
```diff
@@ -87,6 +87,11 @@ func resourceAwsElasticacheSubnetGroupRead(d *schema.ResourceData, meta interfac
 
 	res, err := conn.DescribeCacheSubnetGroups(req)
 	if err != nil {
+		if ec2err, ok := err.(awserr.Error); ok && ec2err.Code() == "CacheSubnetGroupNotFoundFault" {
+			// Update state to indicate the db subnet no longer exists.
```
Comment (catsby) [inline builtin/providers/aws/resource_aws_elasticache_subnet_group.go]: Can we log a `[WARN]` here that it was removed from state?

Comment (catsby) [inline builtin/providers/aws/resource_aws_elasticache_subnet_group.go]: Did so myself in 1624c7e27f542e1aacf597720943cb43703ac2ec !

**Comment by catsby** [comment]
Merged in c667b2d8cde5c577db9d36189c44efffe1f02697, thanks!
