### PR TITLE
validate integers when using protoV5

### LINKED ISSUE #21272: strconv.ParseInt panic when reading a float value into an `int`
### Terraform Version
```
2019/05/10 10:53:41 [INFO] Terraform version: 0.12.0 rc1
2019/05/10 10:53:41 [INFO] Go runtime version: go1.12.1
+ provider.google 2.7.0 (unreleased)
```

### Terraform Configuration Files
```hcl
resource "google_compute_backend_service" "go_clicks" {
  name          = "go-clicks"
  description   = "backend service for go-clicks from different clusters"
  health_checks = ["fake_self_link_for_github_issue"]

  load_balancing_scheme = "EXTERNAL"
  protocol = "HTTP"

  timeout_sec = 30.02

  backend {
    max_rate = 99999
    balancing_mode = "RATE"
  }
}
```

### Debug Output
https://gist.github.com/chrisst/1a500d9a40dbbaab2d1b540ea4a69a51

### Crash Output
https://gist.github.com/chrisst/a7100eb4dbe8ecf581c4157f03ebf6b1

### Expected Behavior
Terraform should throw a type validation error rather than panicking 

### Actual Behavior
panic: Error reading level config: strconv.ParseInt: parsing "30.02": invalid syntax

### Steps to Reproduce
1. Set a float value for a field defined as an integer
2. Terraform plan

### Additional Context
I confirmed this bug exists with Terraform 0.11 and a provider version running a pre 0.12 sdk as well (google-provider 2.4.1).

### References
May be related to https://github.com/hashicorp/terraform/issues/18121 however this doesn't require any migrations in order to repro. 
Could be the root cause of https://github.com/terraform-providers/terraform-provider-google/issues/3590

### PR DESCRIPTION
**Pull request by jbardin**
The new type system only has a Number type, but helper schema
differentiates between Int and Float values. Verify that a new config
value is an integer during Validate, because the existing WeakDecode
validation will decode a float value into an integer while the config
FieldReader will attempt to parse the float exactly.

Fixes #21272

### CODE REVIEW

File: helper/schema/schema.go [hunk 1]
```diff
@@ -1731,12 +1731,25 @@ func (m schemaMap) validatePrimitive(
...
+		switch {
+		case isProto5():
+			// We need to verify the type precisely, because WeakDecode will
+			// decode a float as an integer.
+
+			// the config shims only use int for integral number values
+			if v, ok := raw.(int); ok {
+				decoded = v
+			} else {
+				return nil, []error{fmt.Errorf("%s: expected int, got %[2]T(%[2]v)", k, raw)}
```
Comment (apparentlymart) [inline helper/schema/schema.go]: It's a shame that we have to handle this so late here, when we've already shimmed everything, because `cty` has a nicer error message for this situation, but I guess we can live for now and improve it in the future SDK.

With that said, we _could_ try to mimic `cty`'s error message style here right now, which is to say "must be a whole number" rather than "expected int" if the given value is a float. "int" and "float64" are Go types, not Terraform language types, so to include them in a user-facing error message is likely to cause confusion.

I also wondered here if we can be sure that a whole number from the configuration will always appear as an `int` here. Is there ever a case where a float with no fractional part would be used instead? It looks like the shim prefers to use int where possible:

https://github.com/hashicorp/terraform/blob/28b2383eacaefaa88dd67afdf1d3af28e21900c0/config/hcl2shim/values.go#L151-L162

...so seems fine, I guess.

Comment (jbardin) [reply helper/schema/schema.go]: Yes, I'd rather get this earlier, but I don't think we have any choice since the int/float differentiation is only in `helper/schema`.  I can see this being a common request for property validation in a new SDK too, so I don't know if we want to push this down into configschema somehow later on. 

Good idea on the error message, I'll change that before merging.
