### PR TITLE
store CreateBeforeDestroy even when not refreshing

### LINKED ISSUE #35218: Removing `create_before_destroy` and applying a replacement with `-refresh=false` will not destroy old resource
### Terraform Version

```shell
Terraform v1.8.3
on windows_amd64
+ provider registry.terraform.io/hashicorp/local v2.5.1
```

### Terraform Configuration Files

First `apply` Original Terraform:
```terraform
resource "local_file" "main" {
  content  = "test"
  filename = "foo.txt"

  lifecycle {
    create_before_destroy = true
  }
}
```

Then change to Updated Terraform and `apply -refresh=false`:
```terraform
resource "local_file" "main" {
  content  = "test"
  filename = "bar.txt"
}
```

### Debug Output

https://gist.github.com/michael-sterling/48f32d53123769faf17c05e06ed583be

### Expected Behavior

The plan for `apply -refresh=false` looks like this:

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # local_file.main must be replaced
-/+ resource "local_file" "main" {
      ~ content_base64sha256 = "n4bQgYhMfWWaL+qgxVrQFaO/TxsrC4Is0V1sFbDwCgg=" -> (known after apply)
      ~ content_base64sha512 = "7iaw3Ur350mqGo7jwQrpkj9hiYB3Lkc/iBml1JQODbJ6wYX4oOHV+E+IvIh/1nsUNzLDBMxfqa2Ob1f1ACio/w==" -> (known after apply)
      ~ content_md5          = "098f6bcd4621d373cade4e832627b4f6" -> (known after apply)
      ~ content_sha1         = "a94a8fe5ccb19ba61c4c0873d391e987982fbbd3" -> (known after apply)
      ~ content_sha256       = "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08" -> (known after apply)
      ~ content_sha512       = "ee26b0dd4af7e749aa1a8ee3c10ae9923f618980772e473f8819a5d4940e0db27ac185f8a0e1d5f84f88bc887fd67b143732c304cc5fa9ad8e6f57f50028a8ff" -> (known after apply)
      ~ filename             = "foo.txt" -> "bar.txt" # forces replacement
      ~ id                   = "a94a8fe5ccb19ba61c4c0873d391e987982fbbd3" -> (known after apply)
        # (3 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

I would expect `foo.txt` to be deleted as the plan states.

### Actual Behavior

Both `foo.txt` and `bar.txt` exist. `foo.txt` is no longer tracked in Terraform state.

The `apply` part of the `apply -refresh=false` output confirms it did not attempt to delete `foo.txt`:

```
local_file.main: Creating...
local_file.main: Creation complete after 0s [id=a94a8fe5ccb19ba61c4c0873d391e987982fbbd3]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

### Steps to Reproduce

1. Create a `main.tf` with "Original Terraform" above
2. `terraform init`
3. `terraform apply -auto-approve`
4. Update `main.tf` to the "Updated Terraform" above
5. `terraform apply -refresh=false -auto-approve`

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by jbardin**
The ordering for `CreateBeforeDestroy` is determined by the value stored in the resource instance state. If the destroy plan was created with `-refresh=false`, _and_ the configuration changed the value of `create_before_destroy`, then there was no chance for the state to be updated, and we now have a mismatch between the configuration and the state. This disagreement causes the plan to record the resource replacement as destroy-then-create, but later order the apply actions as create-before-destroy, and since the create is expected to be last, the destroy operation ends up showing a noop and is skipped.

The fix is relatively small, just ensure that we re-write the state when there is no refresh but there was a change in `CreateBeforeDestroy`.

The replacement ordering optimally should be decided entirely by the plan, and then we can rely on the planned changes to determine the CreateBeforeDestroy status without re-inspecting the config and state. This would require very careful auditing however, since not all nodes are represented exactly in the changes, and the way `CreateBeforeDestroy` propagates through the graph is extremely important for correctness and to prevent cycles.

Fixes #35218

### CODE REVIEW

File: internal/terraform/node_resource_plan_instance.go [hunk 1]
```diff
@@ -243,6 +242,16 @@ func (n *NodePlannableResourceInstance) managedResourceExecute(ctx EvalContext)
 		}
 	}
 
+	if n.skipRefresh && !importing && updatedCBD {
+		// CreateBeforeDestroy must be set correctly in the state which us used
```
Comment (kmoe) [inline internal/terraform/node_resource_plan_instance.go:246]:
```suggestion
		// CreateBeforeDestroy must be set correctly in the state which is used
```

**Review by kmoe — APPROVED** [review]
