### PR TITLE
command/format: include nested blocks in `terraform show` output

### LINKED ISSUE #19752: terraform show not showing nested fields in v0.12
### Terraform Version

```
Terraform v0.12.0-dev
+ provider.google (unversioned)
```

### Terraform Configuration Files

```hcl
data "google_compute_image" "my_image" {
  family  = "debian-9"
  project = "debian-cloud"
}

resource "google_compute_instance" "inst" {
	name = "asdf-012-testing"

  machine_type   = "n1-standard-1"
  boot_disk {
    initialize_params{
      image = "${data.google_compute_image.my_image.self_link}"
    }
  }

  network_interface {
    network = "default"
  }
}
```

### Debug Output

I don't think debug logs will be very useful in this case, but here's my terraform state (this is from a different run where i had imported the resource instead of creating it, but same idea. the nested fields are all there as expected): https://gist.github.com/danawillow/b874d89ad09baaa2d930c24f6e820ac3

### Expected Behavior

`terraform show` should have all fields including `boot_disk`, `network_interface`, and `scheduling`.

### Actual Behavior

It only shows top-level fields:
```
$ $GOPATH/bin/terraform show
# google_compute_instance.inst:
resource "google_compute_instance" "inst" {
    can_ip_forward = false
    cpu_platform = "Intel Sandy Bridge"
    deletion_protection = false
    id = "vm-instance-3fgz4w4gz1"
    instance_id = "6061998783150535787"
    label_fingerprint = "42WmSpB8rSM="
    machine_type = "f1-micro"
    metadata_fingerprint = "zxKvLKF-n4o="
    metadata_startup_script = ""
    min_cpu_platform = ""
    name = "vm-instance-3fgz4w4gz1"
    project = "graphite-test-danahoffman-tf"
    self_link = "https://www.googleapis.com/compute/v1/projects/graphite-test-danahoffman-tf/zones/us-central1-a/instances/vm-instance-3fgz4w4gz1"
    tags_fingerprint = "42WmSpB8rSM="
    zone = "us-central1-a"
}
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. `terraform show`

### Additional Context

Tried it at 0.12-alpha4 and at HEAD and got same thing at both.

### PR DESCRIPTION
**Pull request by mildwonkey**
fixes #19752

Here is a sample of the new output using the example state from #19752: https://gist.github.com/mildwonkey/e22885d1920d770ecf056b87c0369622

### CODE REVIEW

File: command/format/state_test.go [hunk 1]
```diff
@@ -101,6 +109,17 @@ func testProviderSchema() *terraform.ProviderSchema {
 					"foo":     {Type: cty.String, Optional: true},
 					"woozles": {Type: cty.String, Optional: true},
 				},
+				BlockTypes: map[string]*configschema.NestedBlock{
+					"nested_attr": {
```
Comment (apparentlymart) [inline command/format/state_test.go]: Since "attributes" is the _other_ field in `*configschema.Block`, this name may prove confusing for future maintainers; maybe we could just call it `nested`?
