### PR TITLE
provider/aws: Fix issue with tainted ASG groups failing to re-create

### LINKED ISSUE #1105: providers/aws: aws_autoscaling_group -/+ should wait till scaling group is removed before recreating
@catsby since `taint` command has been introduced I wanted to utilize it to iterate through some changes fast on our ASGs.

`Terraform v0.4.0-dev (23d90c0c02c10596eed79986e356b20bc6abb441)`

```
 ~/pph/pph-iac/peopleperhour ⮀ ⭠ master  ⮀ terraform taint aws_autoscaling_group.micro_staging
The resource aws_autoscaling_group.micro_staging in the module root has been marked as tainted!
 ~/pph/pph-iac/peopleperhour ⮀ ⭠ master ● ⮀ terraform plan -out /tmp/plan
<snipped>
-/+ aws_autoscaling_group.micro_staging
<snipped>
 ~/pph/pph-iac/peopleperhour ⮀ ⭠ master ● ⮀ terraform apply /tmp/plan
aws_autoscaling_group.micro_staging: Destroying...
aws_autoscaling_group.micro_staging: Creating... 
<snipped>
aws_autoscaling_group.micro_staging: Error: 1 error(s) occurred:

* Error creating Autoscaling Group: AutoScalingGroup by this name already exists - A group with the name micro_staging already exists and is pending delete.  Please wait until Autoscaling completes the deletion process before creating another group with the same name.
```
I 'd like TF to wait until the `aws_autoscaling_group` no longer exists before attempting to recreate it. It can take a while since instances need to be terminated first by the ASG scheduler.

### PR DESCRIPTION
**Pull request by catsby**
Auto Scaling groups can take a minute or two to fully delete even after being drained. In the case of recreating them (ex. a tainted ASG), the immediate re-create attempt will fail because the original still exists, and the new one violates a name constraint.

This PR fixes #1105 by waiting on the ASG to fully delete before returning from the `resourceAwsAutoscalingGroupDelete` function. The timeout is set at 5 minutes, but in practice it's usually less than 1 minute.

### CODE REVIEW

File: builtin/providers/aws/resource_aws_autoscaling_group.go [hunk 1]
```diff
@@ -287,7 +287,12 @@ func resourceAwsAutoscalingGroupDelete(d *schema.ResourceData, meta interface{})
 		return err
 	}
 
-	return nil
+	return resource.Retry(5*time.Minute, func() error {
+		if g, _ = getAwsAutoscalingGroup(d, meta); g != nil {
+			return fmt.Errorf("Auto Scaling Group still exists")
+		}
```
Comment (phinze) [inline builtin/providers/aws/resource_aws_autoscaling_group.go]: Should we check the error here and return a `RetryError` just so we're not waiting around 5m when the internet drops out?

Comment (phinze) [inline builtin/providers/aws/resource_aws_autoscaling_group.go]: We discussed this just now and it's :ok_hand: :shipit:

Comment (catsby) [inline builtin/providers/aws/resource_aws_autoscaling_group.go]: `getAwsAutoscalingGroup` only returns a non-nil `g` if it found the ASG, in which case we want to continue to pool

**Comment by pmoust** [comment]
:+1:
