### PR TITLE
command: use backend config from state when backend=false is used.

### LINKED ISSUE #16593: Terraform reinitialization fails with a conflicting backend configuration even when backend configuration is explicitly skipped
### Terraform Version
Terraform v0.10.8

### Terraform Configuration Files
```hcl
backend-init.tf:
terraform {
  backend "http" {
    address = "some_url"
    update_method = "PUT"
  }

example.tf:
variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "compartment_ocid" {}
variable "region" {}

terraform {
  backend "http" {
    address = "some_other_url"
    update_method = "PUT"
  }
}

provider "oci" {
  tenancy_ocid = "${var.tenancy_ocid}"
  user_ocid = "${var.user_ocid}"
  fingerprint = "${var.fingerprint}"
  private_key_path = "${var.private_key_path}"
  region = "${var.region}"
}

resource "oci_core_virtual_network" "vcn1" {
  cidr_block = "10.0.0.0/16"
  dns_label = "vnc1"
  compartment_id = "${var.compartment_ocid}"
  display_name = "vnc1"
}

}
```

### Debug Output
Backend reinitialization required. Please run "terraform init".
Reason: Backend configuration changed for "http"
....

### Expected Behavior
Terraform initialization succeeds and ignores the new backend configuration

### Actual Behavior
Terraform initialization fails

### Steps to Reproduce
1. Supply a config with a terraform backend configured.
2. Run terraform init to configure the backend.
3. Supply a full terraform config with a different backend configuration.
4. run terraform init -backend=false

### Important Factoids
The atypical piece is the two phase init of terraform and the changed backend configuration which should be ignored due to the -backend=false flag.

### PR DESCRIPTION
**Pull request by mildwonkey**
When a user runs `terraform init --backend=false`, terraform should
inspect the state for a previously-configured backend, and use that
backend, ignoring any backend config in the current configuration. If no
backend is configured or there is no state, return a local backend.

Fixes #16593

### CODE REVIEW

File: command/meta_backend.go [hunk 1]
```diff
@@ -562,6 +562,76 @@ func (m *Meta) backendFromConfig(opts *BackendOpts) (backend.Backend, tfdiags.Di
 	}
 }
 
+// backendFromState retunrs the initialized (not configured) backend directly
```
Comment (pselle) [inline command/meta_backend.go]: nit: typo in returns

File: command/meta_backend.go [hunk 2]
```diff
@@ -562,6 +562,76 @@ func (m *Meta) backendFromConfig(opts *BackendOpts) (backend.Backend, tfdiags.Di
...
+// from the state. This should be used only when a user runs `terraform init
+// -backend=false`. This function returns a local backend if there is no state
+// or no backend configured.
+func (m *Meta) backendFromState() (backend.Backend, tfdiags.Diagnostics) {
+	var diags tfdiags.Diagnostics
+	// Get the path to where we store a local cache of backend configuration
+	// if we're using a remote backend. This may not yet exist which means
+	// we haven't used a non-local backend before. That is okay.
+	statePath := filepath.Join(m.DataDir(), DefaultStateFilename)
```
Comment (pselle) [inline command/meta_backend.go]: Are there scenarios where this can fail before the `sMgr` creation?

Comment (mildwonkey) [reply command/meta_backend.go]: There isn't really anything to fail here; `m.DataDir` and `filepath.Join` both return strings and m.DataDir returns a default value if the data dir isn't set. 

If there was a an inaccurate result from either (not pointing to the actual state), the error would appear two lines down when terraform tries to refresh.

**Comment by mildwonkey** [comment]
I can add something specific to this function.

Basic usage is covered by `TestInit_getProvider`: https://github.com/hashicorp/terraform/blob/master/command/init_test.go#L768

**Comment by mildwonkey** [comment]
Thanks for the nudge, I added a test and found it an interesting learning experience!

File: command/meta_backend.go [hunk 3]
```diff
@@ -562,6 +562,76 @@ func (m *Meta) backendFromConfig(opts *BackendOpts) (backend.Backend, tfdiags.Di
...
+	}
+	s := sMgr.State()
+	if s == nil {
+		// no state, so return a local backend
+		log.Printf("[TRACE] Meta.Backend: backend has not previously been initialized in this working directory")
+		s = terraform.NewState()
+		return backendLocal.New(), diags
+	} else if s.Backend != nil {
+		log.Printf("[TRACE] Meta.Backend: working directory was previously initialized for %q backend", s.Backend.Type)
+	} else if s.Backend == nil {
```
Comment (pselle) [inline command/meta_backend.go]: Somewhat nit, but if you reversed the order of these last two `if`s, do you get to drop one? ex. `if x == nil {}` then the log line doesn't have to be wrapped in an `if`?

Comment (mildwonkey) [reply command/meta_backend.go]: Not quite, not without more rewriting: there are 3 `if`s there so the 'else' needs to be specific or it will relate to the first `if`. 

It's code I copied from elsewhere and could have spent more time polishing it, so let me go make that clearer, thank you!

Comment (pselle) [reply command/meta_backend.go]: Your next change is what I was thinking of! Nice fixup
