### PR TITLE
core: fix crash when computed nested map given in module block

### LINKED ISSUE #13297: Crash when passing nested hash to module containing resource reference
The magic combination seems to be:
1. A module that defines a variable, which is a nested hash (i.e. the variable is a hash, and contains keys whose value is also a hash)
2. An instance of that module, with a value inside the nested hash that refers to a resource's attribute

### Terraform Version
v0.9.2

### Affected Resource(s)
`aws_lambda_function` but this appears to be a bug in core, not resource-specific

### Terraform Configuration Files
main.tf:
```hcl
provider "aws" {
  region  = "us-east-1"
}

# Could be any other resource, doesn't seem to crash with a simple variable reference
resource "aws_s3_bucket" "example" {
  bucket = "my-example-bucket"
}

module "test_module" {
  source = "test_module"

  configuration = {
    environment_vars = {
      BUCKET = "${aws_s3_bucket.example.arn}"
    }
  }
}
```

test_module/main.tf:
```hcl
variable "configuration" {
  default = {
    environment_vars = {}
  }
}

resource "aws_lambda_function" "function" {
  filename      = "file.zip"
  function_name = "function"
  handler       = "handler.handler"
  role          = "arn:aws:iam::123456:role/function-role"
  runtime       = "nodejs4.3"

  environment {
    variables = "${var.configuration["environment_vars"]}"
  }
}
```

### Panic Output
https://gist.github.com/bsiegel/99f90ad9c7e4d4f10c590d21f37f98f8

### Expected Behavior
No crash

### Actual Behavior
Crash

### Steps to Reproduce
1. `terraform plan`

### PR DESCRIPTION
**Pull request by apparentlymart**
This crash resulted because the type switch checked for either of two types but the type assertion within it assumed only one of them.
    
A straightforward (if inelegant) fix is to simply duplicate the relevant case block and change the type assertion, thus allowing the types to match up in all cases.
    
This fixes #13297.

(Also includes a basic test for this eval type, since it entirely lacked one before.)

### CODE REVIEW

File: terraform/eval_variable.go [hunk 1]
```diff
@@ -114,7 +114,6 @@ type EvalVariableBlock struct {
 	VariableValues map[string]interface{}
 }
 
-// TODO: test
```
Comment (jbardin) [inline terraform/eval_variable.go]: I love seeing these go away

File: terraform/eval_variable.go [hunk 2]
```diff
@@ -175,14 +174,22 @@ func (n *EvalVariableBlock) setUnknownVariableValueForPath(path string) error {
 	var current interface{} = n.VariableValues[pathComponents[0]]
 	for i := 1; i < len(pathComponents); i++ {
 		switch current.(type) {
```
Comment (jbardin) [inline terraform/eval_variable.go]: We could define `switch tCurrent := current.(type) {` here, and get rid of the redundant assertions below.

Comment (apparentlymart) [inline terraform/eval_variable.go]: Oh yes, good point! I will update this before merging.
