### PR TITLE
provider/aws: `aws_s3_bucket` acceleration_status not available in china or us-gov

### LINKED ISSUE #7969: aws_s3_bucket UnsupportedArgument in v0.7
UnsupportedArgument Error when running terraform plan

### Terraform Version
- v0.7

### Affected Resource(s)
- aws_s3_bucket

### Terraform Configuration Files
```
resource "aws_s3_bucket" "registry_cn" {
  count  = "${signum(length(var.is_china))}"
  bucket = "${var.env}-elb-registry-logs"
  acl    = "log-delivery-write"

  policy = <<EOF
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Sid": "",
			"Effect": "Allow",
			"Principal": {
				"AWS": "arn:aws-cn:iam::638102146993:root"
			},
			"Action": "s3:PutObject",
			"Resource": "arn:aws-cn:s3:::${var.env}-elb-registry-logs/*"
		}
	]
}
EOF
  tags {
      Name  = "${var.env}_elb_registry_logs"
      Env   = "${var.env}"
  }
}
```
### Debug Output
```
2016/08/04 13:58:35 [DEBUG] plugin: terraform: aws-provider (internal) 2016/08/04 13:58:35 [DEBUG] [aws-sdk-go] DEBUG: Response s3/GetBucketAccelerateConfiguration Details:
2016/08/04 13:58:35 [DEBUG] plugin: terraform: ---[ RESPONSE ]--------------------------------------
2016/08/04 13:58:35 [DEBUG] plugin: terraform: HTTP/1.1 400 Bad Request
2016/08/04 13:58:35 [DEBUG] plugin: terraform: Connection: close
2016/08/04 13:58:35 [DEBUG] plugin: terraform: Transfer-Encoding: chunked
2016/08/04 13:58:35 [DEBUG] plugin: terraform: Content-Type: application/xml
2016/08/04 13:58:35 [DEBUG] plugin: terraform: Date: Thu, 04 Aug 2016 05:58:33 GMT
2016/08/04 13:58:35 [DEBUG] plugin: terraform: Server: AmazonS3
2016/08/04 13:58:35 [DEBUG] plugin: terraform: X-Amz-Id-2: AXAUTQtsgayqOE2fBBoHAyHx8R8EqNPByMXSWZ0MswGtX12MyFUAx/srbNa9gBnG69PZKgd0Fl4=
2016/08/04 13:58:35 [DEBUG] plugin: terraform: X-Amz-Request-Id: F74BA6AA0985B103
2016/08/04 13:58:35 [DEBUG] plugin: terraform:
2016/08/04 13:58:35 [DEBUG] plugin: terraform: 142
2016/08/04 13:58:35 [DEBUG] plugin: terraform: <?xml version="1.0" encoding="UTF-8"?>
2016/08/04 13:58:35 [DEBUG] plugin: terraform: <Error><Code>UnsupportedArgument</Code><Message>The request contained an unsupported argument.</Message><ArgumentName>accelerate</ArgumentName><RequestId>F74BA6AA0985B103</RequestId><HostId>AXAUTQtsgayqOE2fBBoHAyHx8R8EqNPByMXSWZ0MswGtX12MyFUAx/srbNa9gBnG69PZKgd0Fl4=</HostId></Error>
```

### Expected Behavior
The same configuration works on v0.6.16
### Actual Behavior
```
Error refreshing state: 1 error(s) occurred:

2016/08/04 13:58:52 [DEBUG] plugin: waiting for all plugin processes to complete...
* aws_s3_bucket.registry_cn: UnsupportedArgument: The request contained an unsupported argument.
        status code: 400, request id: F74BA6AA0985B103
```

### Steps to Reproduce
1. `terraform plan`

### PR DESCRIPTION
**Pull request by stack72**
Fixes #7969

`acceleration_status` is not available in China or US-Gov data centers.
Even querying for this will give the following:

```
Error refreshing state: 1 error(s) occurred:

2016/08/04 13:58:52 [DEBUG] plugin: waiting for all plugin processes to
complete...
* aws_s3_bucket.registry_cn: UnsupportedArgument: The request contained
* an unsupported argument.
        status code: 400, request id: F74BA6AA0985B103
```

We are going to stop any Read calls for acceleration status from these
data centers

```
% make testacc TEST=./builtin/providers/aws
% TESTARGS='-run=TestAccAWSS3Bucket_'                                  ✹
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSS3Bucket_
-timeout 120m
=== RUN   TestAccAWSS3Bucket_Notification
--- PASS: TestAccAWSS3Bucket_Notification (409.46s)
=== RUN   TestAccAWSS3Bucket_NotificationWithoutFilter
--- PASS: TestAccAWSS3Bucket_NotificationWithoutFilter (166.84s)
=== RUN   TestAccAWSS3Bucket_basic
--- PASS: TestAccAWSS3Bucket_basic (133.48s)
=== RUN   TestAccAWSS3Bucket_acceleration
--- PASS: TestAccAWSS3Bucket_acceleration (282.06s)
=== RUN   TestAccAWSS3Bucket_Policy
--- PASS: TestAccAWSS3Bucket_Policy (332.14s)
=== RUN   TestAccAWSS3Bucket_UpdateAcl
--- PASS: TestAccAWSS3Bucket_UpdateAcl (225.96s)
=== RUN   TestAccAWSS3Bucket_Website_Simple
--- PASS: TestAccAWSS3Bucket_Website_Simple (358.15s)
=== RUN   TestAccAWSS3Bucket_WebsiteRedirect
--- PASS: TestAccAWSS3Bucket_WebsiteRedirect (380.38s)
=== RUN   TestAccAWSS3Bucket_WebsiteRoutingRules
--- PASS: TestAccAWSS3Bucket_WebsiteRoutingRules (258.29s)
=== RUN   TestAccAWSS3Bucket_shouldFailNotFound
--- PASS: TestAccAWSS3Bucket_shouldFailNotFound (92.24s)
=== RUN   TestAccAWSS3Bucket_Versioning
--- PASS: TestAccAWSS3Bucket_Versioning (654.19s)
=== RUN   TestAccAWSS3Bucket_Cors
--- PASS: TestAccAWSS3Bucket_Cors (143.58s)
=== RUN   TestAccAWSS3Bucket_Logging
--- PASS: TestAccAWSS3Bucket_Logging (249.79s)
=== RUN   TestAccAWSS3Bucket_Lifecycle
--- PASS: TestAccAWSS3Bucket_Lifecycle (259.87s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/aws
3946.464s
```

Running these over a 4G tethering connection has been painful :)

### CODE REVIEW

File: builtin/providers/aws/resource_aws_s3_bucket.go [hunk 1]
```diff
@@ -538,15 +538,18 @@ func resourceAwsS3BucketRead(d *schema.ResourceData, meta interface{}) error {
...
 
-	//read the acceleration status
-	accelerate, err := s3conn.GetBucketAccelerateConfiguration(&s3.GetBucketAccelerateConfigurationInput{
-		Bucket: aws.String(d.Id()),
-	})
-	log.Printf("[DEBUG] S3 bucket: %s, read Acceleration: %v", d.Id(), accelerate)
-	if err != nil {
-		return err
+	s3HostedRegion := meta.(*AWSClient).region
+	if s3HostedRegion != "cn-north-1" && s3HostedRegion != "us-gov-west-1" {
```
Comment (radeksimko) [inline builtin/providers/aws/resource_aws_s3_bucket.go]: Hard-coding regions means that once AWS actually starts supporting this feature in `cn-north-1` & `us-gov-west-1`, we'll have to patch it again and users will have to wait for the next release :/

How about silently ignoring `UnsupportedArgument` errors instead? i.e. we'd still error out if _any other_ error comes from AWS API, but this error code seems to be unique enough that it shouldn't have any unintended consequences (like hiding actual errors).

Comment (kwilczynski) [inline builtin/providers/aws/resource_aws_s3_bucket.go]: @radeksimko something like this?

https://gist.github.com/kwilczynski/287639d36ce7bde585c351b7ce9f30f7

Comment (radeksimko) [inline builtin/providers/aws/resource_aws_s3_bucket.go]: @kwilczynski Pretty much, except I would still log full error message. I think we even have a helper function somewhere for matching these AWS errors.

Comment (kwilczynski) [inline builtin/providers/aws/resource_aws_s3_bucket.go]: @radeksimko yes, we have, and with it it would be not necessarily better, as per:

```
isAWSErr(err, "UnsupportedArgument", "The request contained an unsupported argument")
```

I mean, this is fine too, although very verbose. In this particular case accessing the "ArgumentName" would be a plus, but sadly this is not exposed via the error interface.

Comment (radeksimko) [inline builtin/providers/aws/resource_aws_s3_bucket.go]: I see what do you mean, the error message doesn't contain the name of unsupported argument - that's sad, true 😞 

It just depends on the level of reusability of that error code - the `isAWSErr` may potentially help us avoiding false positives/negatives when matching the error message. The question is do we want to ignore error messages we haven't seen yet in a context we didn't think about? IMO we don't because we don't know the exact effect of that. That's why more precise match _may_ be helpful.

The official API docs aren't very helpful in this area either. 😞  http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html#ErrorCodeList doesn't contain `UnsupportedArgument` at all. Instead it contains bunch of 400 Bad Request errors with the **exact same code** related to transfer acceleration, most of which would _probably_ come from `POST`/Create operations.

I don't have a strong opinion about this specific case (`UnsupportedArgument` / `aws_s3_bucket`) though, either way is fine with me.

**Comment by stack72** [comment]
the changes have been resolved thanks to @radeksimko and @kwilczynski :)
