### PR TITLE
core: fix "provider ... couldn't be found" bug

### LINKED ISSUE #2581: "provider template couldn't be found"
When moving to Terraform 0.6.0, terraform refresh now generates errors around my templates:

    * module.staging_member_service.module.mysql_db_server.template_file.userdata (destroy): provider template couldn't be found

My overall terraform code is pretty crazy, so I'm working on creating a smaller reproduction case which I'll attach when I figure out how to reproduce.

### PR DESCRIPTION
**Pull request by phinze**
The `CloseProviderTransformer` relies on the `ProvidedBy()` interface to
look up the proper dependency for the the graph nodes it adds. This
interface needs to yield the name of a provider, _AND_ for flattened
nodes it needs to yield the full path to a provider.

Destroy nodes did not implement this second part, which resulted in
"provider X couldn't be found" when both of these were true:

 * A module included a resource that dependend on a provider
 * The root did _NOT_ include a provider config

Implementing a proper ProvidedBy() on the flattened version of
destroy nodes solves the issue.

fixes #2581

### CODE REVIEW

**Comment by phinze** [comment]
Kicking to @mitchellh to cook up a covering test for me. :heart_decoration:

**Comment by mitchellh** [comment]
Got the test case in, coming in.

File: terraform/context_apply_test.go [hunk 1]
```diff
@@ -894,6 +894,43 @@ func TestContext2Apply_moduleProviderAliasTargets(t *testing.T) {
...
+
+	if _, err := ctx.Plan(); err != nil {
+		t.Fatalf("err: %s", err)
+	}
+
+	if _, err := ctx.Apply(); err != nil {
+		t.Fatalf("err: %s", err)
+	}
+}
+
```
Comment (phinze) [inline terraform/context_apply_test.go]: :+1:
