### PR TITLE
Always validate the graph

### LINKED ISSUE #30647: Terraform hangs due to missed cycle
### Terraform Version

```
Terraform v1.1.0-dev
on darwin_amd64
```

It's actually the latest `main` branch as of today, i.e. what will eventually become 1.2.0. The v1.1 branch is not affected.

### Terraform Configuration Files

```terraform
locals {
  nulls = toset(["alpha", "beta"])
}

resource "null_resource" "a" {
  for_each = local.nulls

  triggers = {
    b = null_resource.b[each.key].triggers.a
  }
}

resource "null_resource" "b" {
  for_each = null_resource.a

  triggers = {
    a = "a"
  }
}
```

### Debug Output

```
2022-03-10T16:46:33.179-0500 [TRACE] dag/walk: vertex "null_resource.a" is waiting for "null_resource.b"
2022-03-10T16:46:33.179-0500 [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/null\"] (close)"
2022-03-10T16:46:33.262-0500 [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/null\"] (close)" is waiting for "null_resource.a"
2022-03-10T16:46:33.262-0500 [TRACE] dag/walk: vertex "null_resource.b" is waiting for "null_resource.a"
2022-03-10T16:46:38.179-0500 [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/null\"] (close)"
```

### Expected Behavior

```
╷
│ Error: Cycle: null_resource.b, null_resource.a
│
│
╵
```

### Actual Behavior

Terraform hangs.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### PR DESCRIPTION
**Pull request by jbardin**
Complete the removal of the Validate option for graph building. There is
no case where we want to allow an invalid graph, as the primary reason
for validation is to ensure we have no cycles, and we can't walk a graph
with cycles. The only code which specifically relied on there being no
validation was a test to ensure the Validate flag prevented it.

Fixes #30647

### CODE REVIEW

File: internal/terraform/graph_builder.go [hunk 1]
```diff
@@ -21,8 +21,8 @@ type GraphBuilder interface {
 // series of transforms and (optionally) validates the graph is a valid
 // structure.
 type BasicGraphBuilder struct {
-	Steps    []GraphTransformer
-	Validate bool
+	Steps []GraphTransformer
+	//Validate bool
```
Comment (alisdair) [inline internal/terraform/graph_builder.go:25]: Perhaps delete instead of comment out?

**Review by alisdair — APPROVED** [review]
Thanks for fixing this!

File: internal/terraform/graph_builder.go (hunk 1 above)
Comment (jbardin) [reply internal/terraform/graph_builder.go:25]: thanks!
