### PR TITLE
Make config errors more important during init operations

### LINKED ISSUE #33622: Unset variable in backend.tf causes crash
### Terraform Version

```shell
Terraform v1.5.4
on windows_amd64
```

### Terraform Configuration Files

backend.tf

```terraform

terraform {
    backend "local" {
        path = ${some.var}
    }
}

```

### Debug Output

```
2023-08-02T20:56:57.949+1000 [INFO]  Terraform version: 1.5.4
2023-08-02T20:56:57.949+1000 [DEBUG] using github.com/hashicorp/go-tfe v1.26.0
2023-08-02T20:56:57.949+1000 [DEBUG] using github.com/hashicorp/hcl/v2 v2.16.2
2023-08-02T20:56:57.949+1000 [DEBUG] using github.com/hashicorp/terraform-svchost v0.1.0
2023-08-02T20:56:57.949+1000 [DEBUG] using github.com/zclconf/go-cty v1.12.2
2023-08-02T20:56:57.949+1000 [INFO]  Go runtime version: go1.20
2023-08-02T20:56:57.949+1000 [INFO]  CLI args: []string{"C:\\Users\\Adam\\OneDrive\\bin\\terraform.exe", "init"}
2023-08-02T20:56:57.950+1000 [TRACE] Stdout is a terminal of width 169
2023-08-02T20:56:57.950+1000 [TRACE] Stderr is a terminal of width 169
2023-08-02T20:56:57.950+1000 [TRACE] Stdin is a terminal
2023-08-02T20:56:57.951+1000 [DEBUG] Attempting to open CLI config file: C:\Users\Adam\AppData\Roaming\terraform.rc
2023-08-02T20:56:57.951+1000 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2023-08-02T20:56:57.952+1000 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2023-08-02T20:56:57.952+1000 [DEBUG] ignoring non-existing provider search directory C:\Users\Adam\AppData\Roaming\terraform.d\plugins
2023-08-02T20:56:57.952+1000 [DEBUG] ignoring non-existing provider search directory C:\Users\Adam\AppData\Roaming\HashiCorp\Terraform\plugins
2023-08-02T20:56:57.952+1000 [INFO]  CLI command args: []string{"init"}

Initializing the backend...
2023-08-02T20:56:57.953+1000 [TRACE] Meta.Backend: built configuration for "local" backend with hash value 3318668199
2023-08-02T20:56:57.953+1000 [TRACE] Meta.Backend: backend has not previously been initialized in this working directory
2023-08-02T20:56:57.953+1000 [DEBUG] New state was assigned lineage "4de671a5-29e2-0c30-a8fa-11fe76ef5067"
2023-08-02T20:56:57.953+1000 [TRACE] Meta.Backend: moving from default local state only to "local" backend
2023-08-02T20:56:57.953+1000 [DEBUG] checking for provisioner in "."
2023-08-02T20:56:57.954+1000 [DEBUG] checking for provisioner in "C:\\Users\\Adam\\OneDrive\\bin"
2023-08-02T20:56:57.954+1000 [TRACE] backend/local: state manager for workspace "default" will:
 - read initial snapshot from terraform.tfstate
 - write new snapshots to terraform.tfstate
 - create any backup at terraform.tfstate.backup
2023-08-02T20:56:57.954+1000 [TRACE] statemgr.Filesystem: reading initial snapshot from terraform.tfstate
2023-08-02T20:56:57.954+1000 [TRACE] statemgr.Filesystem: snapshot file has nil snapshot, but that's okay
2023-08-02T20:56:57.954+1000 [TRACE] statemgr.Filesystem: read nil snapshot
2023-08-02T20:56:57.954+1000 [TRACE] Meta.Backend: ignoring local "default" workspace because its state is empty

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

value is unknown
goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.20.0/x64/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /opt/hostedtoolcache/go/1.20.0/x64/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /home/runner/work/terraform/terraform/internal/logging/panic.go:58 +0x153
panic({0x224a640, 0x2ce6c30})
        /opt/hostedtoolcache/go/1.20.0/x64/src/runtime/panic.go:890 +0x263
github.com/zclconf/go-cty/cty.Value.AsString({{{0x2d10500?, 0xc00011e96d?}}, {0x22ff700?, 0x41c84a0?}})
        /home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.12.2/cty/value_ops.go:1265 +0x111
github.com/hashicorp/terraform/internal/backend/local.(*Local).PrepareConfig(0x2d105e0?, {{{0x2d105e0?, 0xc0009a2b80?}}, {0x232cd00?, 0xc0009b8b10?}})
        /home/runner/work/terraform/terraform/internal/backend/local/backend.go:134 +0xde
github.com/hashicorp/terraform/internal/command.(*Meta).backendInitFromConfig(0x0?, 0xc00030d9a0)
        /home/runner/work/terraform/terraform/internal/command/meta_backend.go:1391 +0x527
github.com/hashicorp/terraform/internal/command.(*Meta).backend_C_r_s(0xc0002fdc00, 0xc00030d9a0, 0xc5cedba7, 0xc00016d920, 0xc00082cee8)
        /home/runner/work/terraform/terraform/internal/command/meta_backend.go:984 +0x8d2
github.com/hashicorp/terraform/internal/command.(*Meta).backendFromConfig(0xc0002fdc00, 0xc00082cee8)
        /home/runner/work/terraform/terraform/internal/command/meta_backend.go:644 +0x14b3
github.com/hashicorp/terraform/internal/command.(*Meta).Backend(0xc0002fdc00, 0x0?)
        /home/runner/work/terraform/terraform/internal/command/meta_backend.go:104 +0x73
github.com/hashicorp/terraform/internal/command.(*InitCommand).initBackend(0xc0002fdc00, 0xc0009b60d0, {{0x271eb7d?, 0x273305e?}, 0xc00052bc08?})
        /home/runner/work/terraform/terraform/internal/command/init.go:469 +0x77b
github.com/hashicorp/terraform/internal/command.(*InitCommand).Run(0xc0002fdc00, {0xc0001183b0, 0x0, 0x0})
        /home/runner/work/terraform/terraform/internal/command/init.go:186 +0xf33
github.com/mitchellh/cli.(*CLI).Run(0xc00011bcc0)
        /home/runner/go/pkg/mod/github.com/mitchellh/cli@v1.1.5/cli.go:262 +0x5f8
main.realMain()
        /home/runner/work/terraform/terraform/main.go:318 +0x1749
main.main()
        /home/runner/work/terraform/terraform/main.go:61 +0x19
```

### Expected Behavior

Probably an error about variables not being supported in backend.tf, or an error about the variable not being set

### Actual Behavior

Crash, as seen above

### Steps to Reproduce

1. create backend.tf with the invalid variable
2. terraform init
3. crash

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by liamcervante**
This PR updates the backend initialisation logic so that if the value returned by parsing the configuration isn't wholly known it returns an error diagnostic instead of crashing. This happens because we try to delay returning diagnostics until we can validate the `required_versions` conditions.

This PR also tweaks the ordering of which diagnostics are returned first. Previously if the backend initialisation returned diagnostics those diagnostics would be reported instead of the config parsing diagnostics. I can see the logic in that, but there is no way to differentiate between there is an error in the backend initialisation and there was an error in the backend initialisation caused by an error in the configuration. Therefore, I think it's better to simply return the configuration errors as higher priority since in the end, both will have to be fixed anyway.

@radditude - you put together the logic I'm moving around here so would be glad to hear your thoughts on my reasoning!

Another solution could be to simply return all the early config diagnostics and the backend diagnostics together instead of either/or?

Fixes #33622 

## Target Release

1.5.5

### BUG FIXES 

 

-  init: Fix crash when using invalid configuration in `backend` blocks.

### CODE REVIEW

File: internal/command/init.go [hunk 1]
```diff
@@ -262,24 +262,22 @@ func (c *InitCommand) Run(args []string) int {
...
-			c.Ui.Error(strings.TrimSpace(errInitConfigError))
-			c.showDiagnostics(diags)
-			return 1
-		}
+	// We've passed the core version check, now we can show errors from the
+	// configuration and backend initialisation.
+
+	// Now, we can check the diagnostics from the early configuration.
+	diags = diags.Append(earlyConfDiags)
+	if earlyConfDiags.HasErrors() {
```
Comment (radditude) [inline internal/command/init.go:270]: Hmm, `earlyConfDiags` doesn't include errors from backend initialization, so if I have a config that looks like this:

```
terraform {
  backend "local" {
    bad_attribute = "is bad"
  }
}

bad_block {

}
```

I won't see anything about the backend problems until after I fix any other config errors. 

That doesn't seem like a terrible outcome, but I wonder if it might be just as well to return all these diags together and adjust `errInitConfigError` so that it makes sense for both config errors and backend errors - the exact wording of that error message used to be important because `terraform-exec` relied on it, but that matching was since [removed](https://github.com/hashicorp/terraform-exec/pull/352).

Comment (liamcervante) [reply internal/command/init.go:272]: Yep, sounds good! I've made it print both sets if either one fails and tweaked the wording a bit!

Comment (radditude) [reply internal/command/init.go:272]: Ah, actually, an important bit of context came back to me and I fear I gave you a bad suggestion 😅 `backDiags` includes config validation errors as well, so appending/returning both together means we'll show errors twice.

We could consider:

1. making `loadBackendConfig` _not_ also [validate the entire root module](https://github.com/hashicorp/terraform/blob/c9a7b7f082551da9ea2b18a326009573487d60d0/internal/command/meta_config.go#L130-L144) so `backDiags` actually contains what it says on the tin
2. going back to what you had originally in order to fix the crash and straighten out this initialization logic later

2 seems reasonable to me, unless you have other suggestions - sorry for the false flag!

Comment (liamcervante) [reply internal/command/init.go:272]: I'm more than happy to turn it back, but I don't think they will actually contain duplicate diagnostics. The HCL library itself caches the files it loads: https://github.com/hashicorp/hcl/blob/main/hclparse/parser.go#L56

So, the first time round it loads the partial file with the diagnostics, but on following reads it doesn't reproduce the diagnostics. It just returns the partial file directly with no diagnostics. The tests also don't show duplicate errors.

Either way, I'm more than happy to go back to the previous approach but I *think* it should be fine.

**Review by radditude — APPROVED** [review]
