### PR TITLE
Produce detailed diagnostic objects when test run assertions fail

### LINKED ISSUE #34428: Produce more detailed diagnostics from failing test conditions
### Terraform Version

```shell
v1.6
```

### Use Cases

The run condition expressions used in tests are going to primarily rely on equality for comparisons, and usually only between 2 values. When the values consist of complex types, the error diagnostics attempt to simplify the output by summarizing the references in the expression, like `is object with 4 attributes`, or `is tuple with 3 elements`. This summary doesn't usually help in the context of a test failure, since the types should be known, and the user is concerned with why the exact values in the expression aren't matching.

### Attempted Solutions

It is possible to break down the expression into multiple assertions, but it would be convenient to enable direct comparison of more complex objects.

### Proposal

Extend the diagnostic format for test failures, which can print complete values or even create smart diffs based on those values in the UI.

### References

#34425

### PR DESCRIPTION
**Pull request by dsa0x**
Fixes #34428

This PR tries to address some of the issues related to test assertion outputs

- The object references in the LHS and RHS expression condition of a run assertion will now be shown in full, instead of the compacted message that was being displayed.
- When a complex object has a marked (sensitive or ephemeral) value, the object will be show in full, with only the marked values redacted. e.g
```
  28:     condition = output.foo == var.foo[0]
    ├────────────────
    │ --- actual
    │ +++ expected
    │   {
    │     "field1": "value1",
    │ -   "field2": "value2",
    │ +   "field2": "different",
    │     "field3": "value3",
    │     "field4": "value4"
    │   }
```

- A diff representation for conditions (LHS (actual) - RHS (expected)) that are a result of binary operations, i.e `a == b`
- For objects of the different types, a statement is added to indicate the reason, because such objects may have the same visual json representation in the terminal. e.g {foo: null} vs {"foo": tonumber(null)}
- Tip: Please look through the tests in `test_test.go` file to see variaous output changes.

## Target Release

1.12

## CHANGELOG entry

- [x] This change is user-facing and I added a changelog entry.
- [ ] This change is not user-facing.

### CODE REVIEW

File: internal/command/test_test.go [hunk 1]
```diff
@@ -301,8 +303,11 @@ func TestTest_Runs(t *testing.T) {
 		},
 		"ephemeral_input_with_error": {
 			expectedOut: []string{"Error message refers to ephemeral values", "1 passed, 1 failed."},
-			expectedErr: []string{"Test assertion failed", "has an ephemeral value"},
-			code:        1,
+			expectedErr: []string{"Test assertion failed", "has an ephemeral value",
+				`│ ~diff: 
+    | - (ephemeral value)
```
Comment (dsa0x) [inline internal/command/test_test.go:308]: I'm contemplating if we would rather show the real underlying value for ephemeral and sensitive values, given that it's just in test outputs

File: internal/command/views/json/diagnostic.go [hunk 2]
```diff
@@ -416,6 +430,204 @@ func NewDiagnostic(diag tfdiags.Diagnostic, sources map[string][]byte) *Diagnost
...
+
+// diffBinaryFailedRunDiagnostic is used to diff the two values of a binary expression
+// in a failed run diagnostic. More often than not, run assert expressions are binary
+// expressions, i.e., `a == b`. If the values are of different types, we don't diff them.
+func diffBinaryFailedRunDiagnostic(ctx *hcl.EvalContext, expr *hclsyntax.BinaryOpExpr) DiagnosticExpressionValue {
+	// The expression has already been evaluated and failed, so we can ignore the diags here.
+	lhs, _ := expr.LHS.Value(ctx)
+	rhs, _ := expr.RHS.Value(ctx)
+
+	// The types do not match. We don't need to diff them?
```
Comment (dsa0x) [inline internal/command/views/json/diagnostic.go:465]: I don't think we need to display a diff when the types do not match. The diff may end up being unreadable, and there is little value in it, especially because we are already showing the full objects involved in the operation

Comment (dsa0x) [reply internal/command/views/json/diagnostic.go:465]: contrived example of a diff of distinct types

```
│ var.tr1 is [
            |   "foo",
            |   "bar"
            | ]
        
            │ var.tr2 is "foo"
            │ ~diff: 
            | - [
            | + "foo"
            | - "foo",
            | - "bar"
            | - ]
            | - 
```

Comment (dsa0x) [reply internal/command/views/json/diagnostic.go:465]: While we allow some comparison to pass in simple primitives (true == "true"), simply ignoring diff when types do not match seem sufficient

Comment (dsa0x) [reply internal/command/views/json/diagnostic.go:465]: another edge case is when we have objects of different types, but whose string representation is the same, e.g
```
{
  "iops" = tonumber(null)
  "size" = 60
}

// AND

{
  iops = null
  size = 60
}
```

The diff for this would indicate no visible difference. In that case, perhaps we should just tell that the values do not have the same type (while showing both objects with no visible difference.

Comment (dsa0x) [reply internal/command/views/json/diagnostic.go]: 626a9f4929

File: internal/command/test_test.go (hunk 1 above)
Comment (dsa0x) [reply internal/command/test_test.go]: Opted not to show marked values. Instead, we will expand the complex objects, and that provides better information to the user about the attributes that are marked. They may then decide to unmark them (e.g with `nonsensitive()`)

File: internal/command/views/json/diagnostic.go [hunk 3]
```diff
@@ -408,6 +412,12 @@ func NewDiagnostic(diag tfdiags.Diagnostic, sources map[string][]byte) *Diagnost
 					diagnostic.Snippet.FunctionCall = callInfo
 				}
 
+				// When the diagnostic is caused by a failed run whose assertion is a binary expression,
+				// we'll include a diff of the two values in the diagnostic snippet.
+				if expr, ok := fromExpr.Expression.(*hclsyntax.BinaryOpExpr); ok && tfdiags.DiagnosticCausedByTestFailure(diag) {
+					diagnostic.Snippet.Values = diffBinaryFailedRunDiagnostic(ctx, expr)
```
Comment (dsa0x) [inline internal/command/views/json/diagnostic.go:418]: Right now, this is a replacement, thus removing all existing snippets. It could be that users still want to see the individual traversals, instead of just the LHS and RHS values.

**Comment by wyardley** [comment]
This is great!

Only feedback from me is that having _both_ the LHS / RHS _and_ diff output could be verbose in some situations? I  have run into cases where diffs are hard to parse in test output, but one thought would be maybe to set it so that the diff only is shown unless a verbose or debug flag is passed?

One thing I also find really helpful in other test frameworks is when the diff part shows explicitly what's expected and what's actual? Even though it's usually `-` for expected and `+` for actual, sometimes it's still a helpful reminder.
Maybe something like
```diff
--- expected
+++ actual
-   "bar": "notbaz",
+   "bar": "baz",
-   "qux": "(sensitive value)",
+   "qux": "quux",
```
I find the `|` on the left a little distracting, but I realize it's probably the terraform standard for errors?

**Comment by dsa0x** [comment]
> Only feedback from me is that having _both_ the LHS / RHS _and_ diff output could be verbose in some situations? I have run into cases where diffs are hard to parse in test output, but one thought would be maybe to set it so that the diff only is shown unless a verbose or debug flag is passed?

Thanks for the feedback @wyardley!. I like the idea of the diff being in the verbose mode. I had planned to also move individual references (i.e var.foo[var.bar] are 2 references) into the verbose mode, and I'll move the diff as well.

> One thing I also find really helpful in other test frameworks is when the diff part shows explicitly what's expected and what's actual? Even though it's usually `-` for expected and `+` for actual, sometimes it's still a helpful reminder. Maybe something like
> 
> ```diff
> --- expected
> +++ actual
> -   "bar": "notbaz",
> +   "bar": "baz",
> -   "qux": "(sensitive value)",
> +   "qux": "quux",
> ```

That's great feedback. Thank you


> I find the `|` on the left a little distracting, but I realize it's probably the terraform standard for errors?

That's right. The format precedes this change, so I will leave it be.

File: internal/moduletest/graph/diagnostics.go [hunk 4]
```diff
@@ -0,0 +1,47 @@
...
+// populate the EvalContext and Expression fields of the diagnostic.
+
+type DiagnosticCausedByTestFailure bool
+
+var _ tfdiags.DiagnosticExtraCausedByTestFailure = DiagnosticCausedByTestFailure(true)
+var _ tfdiags.DiagnosticExtraBecauseEphemeral = DiagnosticCausedByTestFailure(true)
+var _ tfdiags.DiagnosticExtraBecauseSensitive = DiagnosticCausedByTestFailure(true)
+var _ tfdiags.DiagnosticExtraBecauseUnknown = DiagnosticCausedByTestFailure(true)
+
+func (e DiagnosticCausedByTestFailure) DiagnosticCausedByTestFailure() bool {
```
Comment (SarahFrench) [inline internal/moduletest/graph/diagnostics.go:33]: Just a heads up- when I was originally looking into marking test diagnostics as explicitly due to an assertion failure I discussed this implementation with Liam and a sticking point was naming. The pre-existing `DiagnosticCausedByEphemeral`, etc, makes it sound like the test failed _due to_ ephemerality but I think it's more accurate to say that there was an ephemeral in play when the diagnostic was raised.

In contrast, `DiagnosticCausedByTestFailure` is meant to convey a causal link between the test failure and the diagnostic.

There's nothing you need to change here, but I wanted to share that context!

File: internal/command/testdata/test/complex_condition/main.tftest.hcl [hunk 5]
```diff
@@ -0,0 +1,52 @@
...
+run "validate_complex_output" {
+  assert {
+    condition = output.complex == var.foo
+    error_message = "expected to fail"
+  }
+}
+
+run "validate_complex_output_sensitive" {
+  assert {
+    condition = output.complex == output.complex_sensitive
```
Comment (SarahFrench) [inline internal/command/testdata/test/complex_condition/main.tftest.hcl:42]: What would the output look like if the binary expression included nested expressions?
E.g. `(output.complex == output.complex_sensitive) == true`?

Would the output contain all the information, or summarise the left side expression?

**Review by SarahFrench — COMMENTED** [review]
Some small comments. I agree re: verbosity in the previous review but otherwise this PR looks good to me

File: internal/moduletest/graph/diagnostics.go (hunk 4 above)
Comment (dsa0x) [reply internal/moduletest/graph/diagnostics.go:33]: Thanks for that context!

> The pre-existing DiagnosticCausedByEphemeral, etc, makes it sound like the test failed due to ephemerality but I think it's more accurate to say that there was an ephemeral in play when the diagnostic was raised.

You're absolutely right. This definitely make more sense. The original code was more of a workaround.

Regarding the interface implementations, they aren't currently utilized for failed assertions in `internal/command/views/json/diagnostic.go` where diagnostics are displayed in output. I've already created a separate path specifically for handling failed assertion diagnostics there.

I've however left the interface implementations in place as a forward-looking measure. If a future code starts analyzing diagnostics differently without special handling for failed assertions, they'll be available to serve that purpose.

File: internal/command/testdata/test/complex_condition/main.tftest.hcl (hunk 5 above)
Comment (dsa0x) [reply internal/command/testdata/test/complex_condition/main.tftest.hcl:42]: Good question!. The LHS would still be `(output.complex == output.complex_sensitive)`, with it being a type of `ParenthesesExpr`. This is HCL implementation detail, but it feels like a good example to document. Therefore, in the diff, the LHS may simply be something like `true`. 

Nevertheless, in addition to the LHS/RHS and diff, we also display the individual references, e.g

```
  28:     condition = output.foo == var.foo[0]
    ├────────────────
...
    │ Diff:
...
    │ output.foo is {
    │     "bar": "notbaz",
    │     "qux": "quux"
    │   }
    │ var.foo[0] is {
    │     "bar": "baz",
    │     "qux": "quux"
    │   }
```

I intend to move this one to the verbose mode though, so we keep the default mode focused on just the LHS and RHS values.

**Comment by wyardley** [comment]
I didn't read the code too carefully, but how do the colors work? looks like there are colors applied, but mainly the same one? Do you have a screenshot of how the diff looks in a terminal?

**Comment by dsa0x** [comment]
Here is a screenshot example of the colorized output. It mimics similar style used in diffs for terraform operations

image

**Comment by wyardley** [comment]
Nice! This looks great. This is truly going to be so helpful when working on tests.

**Comment by wyardley** [comment]
Side note - I know it looks just like I posted above; but looking at it again, I’d more often expect it to work like a unified diff with the grouping like this. That might be complicated to do without using a third party lib, especially if you had a matching line in between.
But maybe:

```diff
--- expected
+++ actual
-   "bar": "notbaz",
-   "qux": "(sensitive value)",
+   "bar": "baz",
+   "qux": "quux",
```
and in the case where there’s a matching line in between, maybe like 
```diff
--- expected
+++ actual
-   "bar": "notbaz",
+   "bar": "baz",
     “matches”: “matches”,
-   "qux": "(sensitive value)",
+   "qux": "quux",
```

Not sure what the sorting behavior is like - I guess it depends how deep comparison of objects works? I think there’s still some complexity with comparison of objects without converting to JSON first.

**Comment by dsa0x** [comment]
> Side note - I know it looks just like I posted above; but looking at it again, I’d more often expect it to work like a unified diff with the grouping like this. That might be complicated to do without using a third party lib, especially if you had a matching line in between. But maybe:

Thanks. I found different options in existing testing libraries. I'll look into what's more ubiquitous and serves the user better. It does seem like go-based libraries have a similar approach to your suggestion.

> Of course, including some of the matching context like in that case might require some decision making in terms of how much overall context to show (like if you had 40 matching lines in between two non-matching ones). You could include a cut with 3-4 lines of matching context showing but again, maybe hard to implement.

I understand that. I think the output is definitely something we can continue to iterate and improve on 👍

**Review by SarahFrench — APPROVED** [review]
Looks good to me, and the test coverage is great
