### PR TITLE
provider/aws: Fix aws_route53_record alias perpetual diff

### LINKED ISSUE #9628: AWS::Route53 perpetually changing
Terraform v0.7.7
macOS El Capitan 10.11.6
Homebrew 1.0.8
### Terraform Configuration Files

``` hcl
resource "aws_elb" "client-api" {
    name = "${var.namespace}client-api-elb"
    internal = false

    security_groups = ["${aws_security_group.client-api-elb.id}"]
    subnets = ["${aws_subnet.us-west-2a-public.id}", "${aws_subnet.us-west-2b-public.id}"]


    listener {
        instance_port = 80
        instance_protocol = "http"
        lb_port = 80
        lb_protocol = "http"
    }

    listener {
        instance_port = 80
        instance_protocol = "http"
        lb_port = 443
        lb_protocol = "https"
        ssl_certificate_id = "${aws_iam_server_certificate.client-api.arn}"
    }

    health_check {
        healthy_threshold = 4
        unhealthy_threshold = 4
        timeout = 5
        target = "HTTP:80/health"
        interval = 10
    }

    cross_zone_load_balancing = true
    connection_draining = true
    connection_draining_timeout = 300

    tags {
        Name = "${var.environment}-client-api-elb"
        Environment = "${var.environment}"
        Role = "elb"
    }
}

resource "aws_route53_record" "api" {
    zone_id = "${aws_route53_zone.primary.id}"
    name = "api"
    type = "A"

    alias {
        name = "${aws_elb.client-api.dns_name}"
        zone_id = "${aws_elb.client-api.zone_id}"
        evaluate_target_health = true
    }
}
```
### Debug Output

N/A
### Expected Behavior

```
> tf plan
no changes...
```
### Actual Behavior

```
> tf plan
    alias.3026843650.evaluate_target_health: "true" => "false"
    alias.3026843650.name:                   "dualstack.alpha-client-api-elb-[aws_id].us-west-2.elb.amazonaws.com" => ""
    alias.3026843650.zone_id:                "Z1H1FL5HABSF5" => ""
    alias.912019456.evaluate_target_health:  "" => "true"
    alias.912019456.name:                    "" => "alpha-client-api-elb-[aws_id].us-west-2.elb.amazonaws.com"
    alias.912019456.zone_id:                 "" => "Z33MTJ483KN6FU"
```
### Steps to Reproduce

I'm not quite sure how to reproduce this. All I know is that there seems to be no change to the record but TF insists that there is. I suspect it has something to do with the `dualstack` prependation. (That's a word now)

Even after a `terraform apply`, these changes do not stick (it "completes successfully") because next time around it insists on changing them again, or at least trying to.

### PR DESCRIPTION
**Pull request by stack72**
Fixes #9628
Fixes #9298

When a route53_record alias is updated in the console, AWS prepends
`dualstack.` to the name. This is there incase IPV6 is wanted. It is
exactly the same without it as it is with it

In order to stop perpetual diffs, I introduced a normalizeFunc that will
that tke alias name and strip known issues:
- dualstack
- trailing dot

This normalize fun will continue to grow I'm sure

```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSRoute53Record_'                                         ✹
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/10/29 00:28:12 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSRoute53Record_ -timeout 120m
=== RUN   TestAccAWSRoute53Record_basic
--- PASS: TestAccAWSRoute53Record_basic (124.64s)
=== RUN   TestAccAWSRoute53Record_basic_fqdn
--- PASS: TestAccAWSRoute53Record_basic_fqdn (132.07s)
=== RUN   TestAccAWSRoute53Record_txtSupport
--- PASS: TestAccAWSRoute53Record_txtSupport (134.07s)
=== RUN   TestAccAWSRoute53Record_spfSupport
--- PASS: TestAccAWSRoute53Record_spfSupport (113.36s)
=== RUN   TestAccAWSRoute53Record_generatesSuffix
--- PASS: TestAccAWSRoute53Record_generatesSuffix (112.62s)
=== RUN   TestAccAWSRoute53Record_wildcard
--- PASS: TestAccAWSRoute53Record_wildcard (162.84s)
=== RUN   TestAccAWSRoute53Record_failover
--- PASS: TestAccAWSRoute53Record_failover (126.18s)
=== RUN   TestAccAWSRoute53Record_weighted_basic
--- PASS: TestAccAWSRoute53Record_weighted_basic (121.10s)
=== RUN   TestAccAWSRoute53Record_alias
--- PASS: TestAccAWSRoute53Record_alias (118.14s)
=== RUN   TestAccAWSRoute53Record_s3_alias
--- PASS: TestAccAWSRoute53Record_s3_alias (155.07s)
=== RUN   TestAccAWSRoute53Record_weighted_alias
--- PASS: TestAccAWSRoute53Record_weighted_alias (235.41s)
=== RUN   TestAccAWSRoute53Record_geolocation_basic
^[[C--- PASS: TestAccAWSRoute53Record_geolocation_basic (125.32s)
=== RUN   TestAccAWSRoute53Record_latency_basic
--- PASS: TestAccAWSRoute53Record_latency_basic (122.23s)
=== RUN   TestAccAWSRoute53Record_TypeChange
--- PASS: TestAccAWSRoute53Record_TypeChange (231.98s)
=== RUN   TestAccAWSRoute53Record_empty
--- PASS: TestAccAWSRoute53Record_empty (116.48s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/aws    2131.526s
```

Before this fix, I was getting the following by recreating the code in

```
~ aws_route53_record.alias
    alias.1563903989.evaluate_target_health: "true" => "false"
    alias.1563903989.name:                   "9828-recreation-106795730.us-west-2.elb.amazonaws.com." => ""
    alias.1563903989.zone_id:                "Z1H1FL5HABSF5" => ""
    alias.318754017.evaluate_target_health:  "" => "true"
    alias.318754017.name:                    "" => "9828-recreation-106795730.us-west-2.elb.amazonaws.com"
    alias.318754017.zone_id:                 "" => "Z1H1FL5HABSF5"

Plan: 0 to add, 1 to change, 0 to destroy.
```

After this fix:

```

No changes. Infrastructure is up-to-date. This means that Terraform
could not detect any differences between your configuration and
the real physical resources that exist. As a result, Terraform
doesn't need to do anything.
```

### CODE REVIEW

**Comment by catsby** [comment]
LGTM – are there any scenaiors that exist where an existing alias is not trigging a diff (no "dual stack"), but they may have a `.` suffix, in which upgrading after this will cause a diff? Long way of asking if we need a migration for this:

```diff
+	if strings.HasSuffix(input, ".") {
+		return input[0 : len(input)-1]
+	}
```

File: builtin/providers/aws/resource_aws_route53_record.go [hunk 1]
```diff
@@ -748,3 +749,16 @@ func nilString(s string) *string {
...
 }
+
+func normalizeAwsAliasName(alias interface{}) string {
+	input := alias.(string)
+	if strings.HasPrefix(input, "dualstack.") {
+		return strings.Replace(input, "dualstack.", "", -1)
+	}
+
+	if strings.HasSuffix(input, ".") {
+		return input[0 : len(input)-1]
```
Comment (catsby) [inline builtin/providers/aws/resource_aws_route53_record.go]: could either of these operations be replaced with `strings.TrimLeft` ? https://golang.org/pkg/strings/#TrimLeft ?

**Comment by stack72** [comment]
The . is something that was already in place for the read:

```
name := strings.TrimSuffix(*alias.DNSName, ".")
```

I just moved it into this function as to avoid multiple normalization operations

File: builtin/providers/aws/resource_aws_route53_record.go [hunk 2]
```diff
@@ -748,3 +749,16 @@ func nilString(s string) *string {
 	}
 	return aws.String(s)
 }
+
+func normalizeAwsAliasName(alias interface{}) string {
```
Comment (catsby) [inline builtin/providers/aws/resource_aws_route53_record.go]: will `alias` here ever _not_ be a string? All the invocations thus far are a `string` that I can see

File: builtin/providers/aws/resource_aws_route53_record.go (hunk 1 above)
Comment (catsby) [inline builtin/providers/aws/resource_aws_route53_record.go]: I think I meant  `TrimRight` :)

**Comment by stack72** [comment]
@catsby updated to TrimRight as tested it here :) https://play.golang.org/p/MX_RHqsbfb

File: builtin/providers/aws/resource_aws_route53_record.go [hunk 3]
```diff
@@ -732,7 +733,7 @@ func expandRecordName(name, zone string) string {
 func resourceAwsRoute53AliasRecordHash(v interface{}) int {
 	var buf bytes.Buffer
 	m := v.(map[string]interface{})
-	buf.WriteString(fmt.Sprintf("%s-", m["name"].(string)))
+	buf.WriteString(fmt.Sprintf("%s-", normalizeAwsAliasName(m["name"].(string))))
 	buf.WriteString(fmt.Sprintf("%s-", m["zone_id"].(string)))
```
Comment (apparentlymart) [inline builtin/providers/aws/resource_aws_route53_record.go]: Sorry for the late comment here @stack72... but when I've seen this class of error so far I've seen `zone_id` change too, as if Route53 uses a different zone for the `dualstack.` form of the hostname than for the regular form. You can see this e.g. in the example in the summary of #9628.

Do you think we need to do something additional here to catch that case, or is this fine because the non-prefixed hostname happens to resolve in the other zone too?

Comment (stack72) [inline builtin/providers/aws/resource_aws_route53_record.go]: TBH I haven't come across a zone change yet - that is a legit change IMO - I have only come across the issue where f we chose / edit an alias in the console, it adds `dualstack.` so we are guarding here against that.

I have no doubt that this normalize func will expand in the future though :)

**Comment by CpuID** [comment]
@stack72 still seeing this in 0.7.9 currently.

```
~ aws_route53_record.api-lb-e01
    alias.1991554031.evaluate_target_health: "" => "true"
    alias.1991554031.name:                   "" => "api-lb-e01-1049240735.us-east-1.elb.amazonaws.com"
    alias.1991554031.zone_id:                "" => "Z3DZXE0Q79N41H"
    alias.880662862.evaluate_target_health:  "true" => "false"
    alias.880662862.name:                    "api-lb-e01-1049240735.us-east-1.elb.amazonaws.com." => ""
    alias.880662862.zone_id:                 "Z35SXDOTRQ7X7K" => ""

$ terraform version
Terraform v0.7.9
```

When I try an apply, it passes and claims it applied but in the Route53 console looks like a no-op (still has the old Hosted Zone ID attached).

Also note there are valid use cases for setting the `dualstack.` prefix, which do not seem to be handled by the variable `${aws_elb.api-lb-e01.dns_name}` currently, would it be worth adding an extra property to the `aws_elb` resource of something like `.dualstack_dns_name`?

**Comment by CpuID** [comment]
https://github.com/hashicorp/terraform/issues/10004 is a duplicate of this issue, future correspondence there.
