### PR TITLE
provider/aws: Add Primary Endpoint Address attribute for `aws_elasticache_replication_group`

### LINKED ISSUE #8377: resource AWS_ELASTICACHE_REPLICATION_GROUP should at least output the primary endpoint address and its portt
### Terraform Version
Terraform v0.7.1

### Affected Resource(s)
- AWS_ELASTICACHE_REPLICATION_GROUP

### Terraform Configuration Files
n/a

### Debug Output
n/a

### Panic Output
n/a

### Expected Behavior
The resource should output the primary endpoint address and the service port as in 
`aws elasticache describe-replication-groups`

### Actual Behavior
The resource is only providing the the replication group id, which is not really informative.

### Steps to Reproduce
terraform apply

### Important Factoids
n/a

### References
n/a

### PR DESCRIPTION
**Pull request by stack72**
Fixes #8377

Now we can output the endpoint of the primary

```
resource "aws_elasticache_replication_group" "bar" {
    replication_group_id = "tf-11111"
    replication_group_description = "test description"
    node_type = "cache.m1.small"
    number_cache_clusters = 2
    port = 6379
    parameter_group_name = "default.redis2.8"
    apply_immediately = true
}

output "primary_endpoint_address" {
  value = "${aws_elasticache_replication_group.bar.primary_endpoint_address}"
}
```

This gives us:

```
% terraform apply
...................
aws_elasticache_replication_group.bar: Creation complete

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

primary_endpoint_address = tf-11111.d5jx4z.ng.0001.use1.cache.amazonaws.com
```

This was the addition of a computed field only so the basic test still works as expected:

```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSElasticacheReplicationGroup_basic'                        ✹
==> Checking that code complies with gofmt requirements...
/Users/stacko/Code/go/bin/stringer
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/08/22 17:11:13 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSElasticacheReplicationGroup_basic -timeout 120m
=== RUN   TestAccAWSElasticacheReplicationGroup_basic
--- PASS: TestAccAWSElasticacheReplicationGroup_basic (741.71s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	741.735s
```

### CODE REVIEW

File: builtin/providers/aws/resource_aws_elasticache_replication_group.go [hunk 1]
```diff
@@ -215,6 +220,8 @@ func resourceAwsElasticacheReplicationGroupRead(d *schema.ResourceData, meta int
 		d.Set("snapshot_window", c.SnapshotWindow)
 		d.Set("snapshot_retention_limit", c.SnapshotRetentionLimit)
 
+		d.Set("primary_endpoint_address", rgp.NodeGroups[0].PrimaryEndpoint.Address)
```
Comment (jen20) [inline builtin/providers/aws/resource_aws_elasticache_replication_group.go]: Is there any possibility of this being empty?

**Comment by jen20** [comment]
One question, otherwise LGTM

File: builtin/providers/aws/resource_aws_elasticache_replication_group.go (hunk 1 above)
Comment (stack72) [inline builtin/providers/aws/resource_aws_elasticache_replication_group.go]: As long as we have gotten into this block, we have passed a check to make sure that there is a NodeGroup available :) The first NodeGroup is the primary and we use that to populate all of the information above it

Comment (manuchadha) [reply builtin/providers/aws/resource_aws_elasticache_replication_group.go]: @stack72 @jen20  -How to get addresses for replica nodes?

**Comment by manuchadha** [comment]
@stack72 @jen20 -How to get addresses for replica nodes?

**Comment by jen20** [comment]
Presumably there is a secondary endpoint on the structure which you could expose. Development now goes on in the AWS provider repo, which is the appropriate place to log an issue (after searching for an existing one) for this.
