### PR TITLE
backend/azurerm: Dependency Update and Fixes

### LINKED ISSUE #20831: AzureRM backend support for AD auth (no need for keys)
### Current Terraform Version
0.11.13

### Use-cases
Authenticating to Azure Storage using the current credential

### Attempted Solutions
Storage Key works but doesn't offer granular control, stores the storage key in the state file, and changing keys can be difficult in a possible compromise.

### Proposal
MS has added support for adding AzureAD/AD users to roles like "storage blob data contributor" to that the proliferation of keys is not required.  Allow Terraform to use these credentials the same way the az cli does to access the storage account.

### LINKED ISSUE #26702: Crash during terraform plan
**Terraform version**
2020/10/26 18:53:06 [INFO] Terraform version: 0.13.5  
2020/10/26 18:53:06 [INFO] Go runtime version: go1.14.7
2020/10/26 18:53:06 [INFO] CLI args: []string{"C:\\microservice\\azure\\kubectl\\terraform.exe", "plan"}

**Issue**

When performing terraform plan with version 0.13.5 in azure initalizing list of redis services, terraform crashed.
Below is the stack

2020/10/26 18:53:24 [DEBUG] Building the Blob Client from an Access Token (using user credentials)
2020/10/26 18:53:24 [TRACE] vertex "data.terraform_remote_state.kv": visit complete
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x127a3f6]

goroutine 689 [running]:
github.com/hashicorp/terraform/backend/remote-state/azure.(*RemoteClient).Get(0xc00047e690, 0x17, 0x2756af2, 0x1b)
	/home/circleci/project/project/backend/remote-state/azure/client.go:42 +0x166
github.com/hashicorp/terraform/states/remote.(*State).refreshState(0xc0004c2540, 0x1b, 0xc00079b940)
	/home/circleci/project/project/states/remote/state.go:111 +0x3f
github.com/hashicorp/terraform/states/remote.(*State).RefreshState(0xc0004c2540, 0x0, 0x0)
	/home/circleci/project/project/states/remote/state.go:104 +0x73
github.com/hashicorp/terraform/builtin/providers/terraform.dataSourceRemoteStateRead(0x2d435a0, 0xc000330228, 0x235b460, 0xc0007da750, 0x14, 0xbfddd1521204c330, 0x35d4df391, 0xc0, 0xc001136000, 0xc00008e080, ...)
	/home/circleci/project/project/builtin/providers/terraform/data_source_state.go:121 +0xa2d
github.com/hashicorp/terraform/builtin/providers/terraform.(*Provider).ReadDataSource(0xc000982020, 0xc0002c2d80, 0x16, 0x2d435a0, 0xc000330228, 0x235b460, 0xc0007da750, 0x2d434e0, 0x4188680, 0x0, ...)
	/home/circleci/project/project/builtin/providers/terraform/provider.go:80 +0x21f
github.com/hashicorp/terraform/terraform.(*evalReadData).readDataSource(0xc00047e5a0, 0x2d86220, 0xc0018d4270, 0x2d435a0, 0xc000330228, 0x235b460, 0xc0007da750, 0x0, 0x0, 0x0, ...)
	/home/circleci/project/project/terraform/eval_read_data.go:112 +0xa18
github.com/hashicorp/terraform/terraform.(*evalReadDataRefresh).Eval(0xc00047e5a0, 0x2d86220, 0xc0018d4270, 0x1, 0x1, 0x0, 0x0)
	/home/circleci/project/project/terraform/eval_read_data.go:282 +0xf4e
github.com/hashicorp/terraform/terraform.EvalRaw(0x2cdb7a0, 0xc00047e5a0, 0x2d86220, 0xc0018d4270, 0x0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/eval.go:49 +0xce
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc000983800, 0x2d86220, 0xc0018d4270, 0x1, 0x1, 0x4, 0xc0011b6670)
	/home/circleci/project/project/terraform/eval_sequence.go:20 +0x104
github.com/hashicorp/terraform/terraform.EvalRaw(0x2cdb1e0, 0xc000983800, 0x2d86220, 0xc0018d4270, 0x2310940, 0x40156c4, 0x2270ee0, 0xc00094cc20)
	/home/circleci/project/project/terraform/eval.go:49 +0xce
github.com/hashicorp/terraform/terraform.Eval(0x2cdb1e0, 0xc000983800, 0x2d86220, 0xc0018d4270, 0xc000983800, 0x2cdb1e0, 0xc000983800, 0x0)
	/home/circleci/project/project/terraform/eval.go:35 +0x54
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x2661280, 0xc00011a0b0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/graph.go:73 +0xc7e
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc0004be720, 0x2661280, 0xc00011a0b0, 0xc0011b6600)
	/home/circleci/project/project/dag/walk.go:387 +0x35e
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/home/circleci/project/project/dag/walk.go:309 +0x11de

**Steps to reproduce**
One of the variable was undeclared and it lead to this crash

### LINKED ISSUE #27723: Panic/TF Crash with terraform_remote_state and Azure Variable Group
Experiencing a TF crash when passing variables with TF_VAR_x in an Azure DevOps variable group. Crash does not occur when including the TF_VARS_x variables directly in the pipeline. This is only happening with the teraform_remote_state provider

### Terraform Version

```
0.14.6
```

### Debug Output
https://gist.github.com/ryanfields-8451/e55985224e179a1d4ae262fed2e06d31 

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context
This is only happening when passing the remote statefile config parameters as environment variables in an Azure Devops variable group. If the environment variables are each declared in the pipeline rather than the group the pipeline is successful. 

### References
Similar to #27511

### LINKED ISSUE #27809: TERRAFORM CRASH
[crash.log](https://github.com/hashicorp/terraform/files/5998289/crash.log)

**_terraform version is:_**  v0.14.6

I initiated
**terraform plan**

**the response was:**
Acquiring state lock. This may take a few moments...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1f9a631]

goroutine 38 [running]:
github.com/hashicorp/terraform/backend/remote-state/azure.(*RemoteClient).Lock(0xc0003d6000, 0xc0001fa800, 0xc0003d6000, 0xd4bd800, 0xc0003d6000, 0x1)
	/home/circleci/project/project/backend/remote-state/azure/client.go:154 +0x291
github.com/hashicorp/terraform/states/remote.(*State).Lock(0xc00009aea0, 0xc0001fa800, 0x0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/states/remote/state.go:208 +0xbd
github.com/hashicorp/terraform/states/statemgr.LockWithContext(0x38e4260, 0xc00009af00, 0xd4bd7d8, 0xc00009aea0, 0xc0001fa800, 0xc0002c3a70, 0xc0002c3a60, 0x0, 0x106b5e1)
	/home/circleci/project/project/states/statemgr/locker.go:76 +0x82
github.com/hashicorp/terraform/command/clistate.(*locker).Lock.func1(0xc000350000, 0xc0002c3a50)
	/home/circleci/project/project/command/clistate/state.go:116 +0x5b
github.com/hashicorp/terraform/helper/slowmessage.Do.func1(0xc00009af60, 0xc00001eb40)
	/home/circleci/project/project/helper/slowmessage/slowmessage.go:20 +0x27
created by github.com/hashicorp/terraform/helper/slowmessage.Do
	/home/circleci/project/project/helper/slowmessage/slowmessage.go:19 +0x77

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

### PR DESCRIPTION
**Pull request by mbfrahry**
Fixes #27809
Fixes #27809 
Fixes #27723
Fixes #26702
Fixes #20831

### CODE REVIEW

File: backend/remote-state/azure/arm_client.go [hunk 1]
```diff
@@ -109,6 +121,8 @@ func buildArmClient(ctx context.Context, config BackendConfig) (*ArmClient, erro
 }
 
 func buildArmEnvironment(config BackendConfig) (*azure.Environment, error) {
+	// TODO: can we remove this?
+	// https://github.com/hashicorp/terraform/issues/27156
```
Comment (tombuildsstuff) [inline backend/remote-state/azure/arm_client.go:125]: outside of this PR since this is already unused, but we should dig into this separately

File: website/docs/language/settings/backends/azurerm.html.md [hunk 2]
```diff
@@ -11,7 +11,7 @@ description: |-
 
 **Kind: Standard (with state locking)**
 
-Stores the state as a Blob with the given Key within the Blob Container within [the Blob Storage Account](https://docs.microsoft.com/azure/storage/common/storage-introduction). This backend also supports state locking and consistency checking via native capabilities of Azure Blob Storage.
+Stores the state as a Blob with the given Key within the Blob Container within [the Blob Storage Account](https://docs.microsoft.com/en-us/azure/storage/common/storage-introduction). This backend also supports state locking and consistency checking via native capabilities of Azure Blob Storage.
```
Comment (tombuildsstuff) [inline website/docs/language/settings/backends/azurerm.html.md:14]: if we remove this it'll redirect to the users locale:

```suggestion
Stores the state as a Blob with the given Key within the Blob Container within [the Blob Storage Account](https://docs.microsoft.com/azure/storage/common/storage-introduction). This backend also supports state locking and consistency checking via native capabilities of Azure Blob Storage.
```

**Review by tombuildsstuff — APPROVED** [review]
a couple of minor comments but this otherwise LGTM 👍

File: website/docs/language/settings/backends/azurerm.html.md (hunk 2 above)
Comment (mbfrahry) [reply website/docs/language/settings/backends/azurerm.html.md:14]: This one breaks the website-test as a link that has permanently moved. I think we'll need to keep it this way

**Comment by hideout** [comment]
nice info.
