### PR TITLE
moved: error if not targeting a resource address

### LINKED ISSUE #35840: moved block does not trigger if using `locals` as input
### Terraform Version

```shell
Terraform v1.9.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/random v3.6.3
```

I also tested it with 1.7

### Terraform Configuration Files

```terraform
terraform {
    required_providers {
        random = {
        source = "hashicorp/random"
        }
    }
}

resource "random_password" "token" { # first run `terraform apply` with this named `token_old`
  length  = 32
  special = false
}


# this works
#moved {
#    from = random_password.token_old
#    to = random_password.token
#}

# this is the bug and causes a destroy and create
locals {
    old_token = "random_password.token_old"
}
moved {
    from = locals.old_token
    to = random_password.token
}

# this is not valid:
# A single static variable reference is required: only attribute access and
# │ indexing with constant keys. No calculations, function calls, template
# │ expressions, etc are allowed here.
# 
# moved {
#     from = "random_password.token_old"
#     to = "random_password.token"
# }
```

### Debug Output

```
terraform plan
random_password.token_old: Refreshing state... [id=none]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

  # random_password.token will be created
  + resource "random_password" "token" {
      + bcrypt_hash = (sensitive value)
      + id          = (known after apply)
      + length      = 32
      + lower       = true
      + min_lower   = 0
      + min_numeric = 0
      + min_special = 0
      + min_upper   = 0
      + number      = true
      + numeric     = true
      + result      = (sensitive value)
      + special     = false
      + upper       = true
    }

  # random_password.token_old will be destroyed
  # (because random_password.token_old is not in configuration)
  - resource "random_password" "token_old" {
      - bcrypt_hash = (sensitive value) -> null
      - id          = "none" -> null
      - length      = 32 -> null
      - lower       = true -> null
      - min_lower   = 0 -> null
      - min_numeric = 0 -> null
      - min_special = 0 -> null
      - min_upper   = 0 -> null
      - number      = true -> null
      - numeric     = true -> null
      - result      = (sensitive value) -> null
      - special     = false -> null
      - upper       = true -> null
    }

Plan: 1 to add, 0 to change, 1 to destroy.

```

### Expected Behavior

it should also move the resource like in the first, commented out, example:

```
moved {
    from = random_password.token_old
    to = random_password.token
}
```

```
terraform plan
random_password.token: Refreshing state... [id=none]

Terraform will perform the following actions:

  # random_password.token_old has moved to random_password.token
    resource "random_password" "token" {
        id          = "none"
        # (12 unchanged attributes hidden)
    }

Plan: 0 to add, 0 to change, 0 to destroy.

```

### Actual Behavior

the resource is not moved but destroyed and created

when using:
```
locals {
    old_token = "random_password.token_old"
}
moved {
    from = locals.old_token
    to = random_password.token
}
```

### Steps to Reproduce

- change example to be `resource "random_password" "token_old"` instead of `resource "random_password" "token"`
- `terraform init`
- `terraform apply`
- change example to be `resource "random_password" "token"` instead of `resource "random_password" "token_old"`
- `terraform plan`
- see the bug

### Additional Context

tested in CI/CD with version 1.7
tested on windows with 1.9

The Idea behind using locals is that I can use variables inside the names of the resources.
I needed this since I'm migrating away from a lib which dynamically created tf.json files and used env vars to name the resources.

### References

_No response_

### PR DESCRIPTION
**Pull request by liamcervante**
This PR updates the parsing of targets (such as within import and moved blocks) so that they respect the keywords reserved by the top level references within Terraform.

These keywords include things like `local`, `each`, `count`, `self`, and `terraform`. Previously it was possible to reference these from within `moved` as resource types without prefixing them with the normally required `resource.` identifier to differentiate between a resource with the type name `local` and just referencing a `local` variable.

I'm not backporting this change, as it is technically a breaking change though I doubt anyone will be affected. Anyone who uses a resource that is simple called `local` (or any other reserved keyword) would previously have been able to reference it directly from a `moved` block. This will start failing, and they must add in the `.resource` prefix to make things work again.

The purpose of this change is to protect users from trying to reference input or local variables, which currently makes Terraform just ignore the moved block. I don't think many (if any) providers have actually made resource types that match keywords so this should hopefully not breaking anything.

Fixes #35840 

## Target Release

1.10.x

### UPGRADE NOTES

 

-  `moved` blocks: Moved blocks now respect reserved keywords when parsing resource addresses. Configurations that reference resources with type names that match top level blocks and keywords will need to be updated to

### CODE REVIEW

**Review by DanielMSchmidt — APPROVED** [review]

File: internal/addrs/parse_target.go [hunk 1]
```diff
@@ -181,6 +181,15 @@ func parseResourceInstanceUnderModule(moduleAddr ModuleInstance, allowPartial bo
 		// Starting a resource address with "resource" is optional, so we'll
 		// just ignore it.
 		remain = remain[1:]
+	case "count", "each", "local", "module", "path", "self", "terraform", "var", "template", "lazy", "arg":
```
Comment (jbardin) [inline internal/addrs/parse_target.go:184]: You can target and move modules, which always require the `module` keyword.

File: website/docs/language/moved.mdx [hunk 2]
```diff
@@ -16,8 +16,8 @@ The `moved` block programmatically changes the address of a resource. Refer to [
 The following list outlines field hierarchy, language-specific data types, and requirements in the `moved` block. 
 
 - [`moved`](#moved): map
-  - [`from`](#moved): string
-  - [`to`](#moved): string
+  - [`from`](#moved): instance address
+  - [`to`](#moved): instance address
```
Comment (jbardin) [inline website/docs/language/moved.mdx:20]: Targets are often groups of instances, so I think just "reference" here would be the correct type for documentation purposes.

File: internal/addrs/parse_target.go (hunk 1 above)
Comment (liamcervante) [reply internal/addrs/parse_target.go:184]: This function is specifically for parsing resources under modules (as in the modules have already been parsed out). I think it's technically impossible to get here with `module` at the moment as nothing calls this function directly - but it would be an error for a resource address to start with `module`.

I can still take this out, but I think being safe in case anyone references this function directly in future is probably better?

Comment (jbardin) [reply internal/addrs/parse_target.go:184]: oh, then ignore me! 😆 I saw parseTarget under the collapsed code above and missed what this was actually checking.

File: website/docs/language/moved.mdx (hunk 2 above)
Comment (liamcervante) [reply website/docs/language/moved.mdx]: Done!
