### PR TITLE
lang: Fix non-string key panics in map function

### LINKED ISSUE #23043: panic on passing non-string key to map()
### Terraform Version

```
Terraform v0.12.10
+ provider.local v1.3.0
```

### Terraform Configuration Files

```hcl
locals {
	a = map(1, 1)
}
```

### Debug Output

https://gist.github.com/alxrem/16972d40bbfe8df2fbecac6720a9b5a8

### Crash Output

https://gist.github.com/alxrem/af55977e452fbd3c6be0c192c05bc3bd

### Expected Behavior

Error message from syntax parser.

### Actual Behavior

Panic

### Steps to Reproduce

```
cat <<EOF >bug.tf
locals {
	a = map(1, 1)
}
EOF
terraform init
terraform plan
```

### LINKED ISSUE #23346: Call to function "map" failed: panic in function implementation: not a string
### Terraform Version

```
Terraform v0.12.13
```

### Terraform Configuration Files

It is sufficient to run this in the Terraform console:

```hcl
map(null, 1)
```

### Crash Output

https://gist.github.com/sbrandtb/c126f844dafe304df379572ec21f1495

### Expected Behavior
Error message similar to [this](https://github.com/hashicorp/terraform/issues/21548#issuecomment-518361658)

### Actual Behavior
Crash.

### Steps to Reproduce

1. `terraform console`
1. `map(null, 1)`

### References

Similar: #21548

### PR DESCRIPTION
**Pull request by alisdair**
The map function assumed that the key arguments were strings, and would panic if they were not.

After this commit, calling `map(1, 2)` will result in a map `{"1" = 2}`, and calling `map(null, 1)` will result in a syntax error.

```
$ terraform console
> map(1, 2)
{
  "1" = 2
}
> map(null, 1)

>
Error: Error in function call

  on <console-input> line 1:
  (source code not available)

Call to function "map" failed: argument 1 is a null key.
```

Fixes #23346, fixes #23043

### CODE REVIEW

File: lang/funcs/collection.go [hunk 1]
```diff
@@ -346,12 +346,14 @@ var MapFunc = function.New(&function.Spec{
...
 
-			key := args[i].AsString()
-
-			err := gocty.FromCtyValue(args[i], &key)
+			keyVal, err := convert.Convert(args[i], cty.String)
 			if err != nil {
 				return cty.NilVal, err
 			}
+			if keyVal.IsNull() {
+				return cty.NilVal, fmt.Errorf("argument %d is a null key", i+1)
```
Comment (apparentlymart) [inline lang/funcs/collection.go]: Not super important here, but just wanted to point out that you can return the special error type [`ArgError`](https://pkg.go.dev/github.com/zclconf/go-cty@v1.3.1/cty/function?tab=doc#ArgError) from a function (e.g. using `NewArgErrorf` instead of `Errorf` here) to indicate that a specific argument is incorrect.

When using functions with HCL, HCL recognizes that error type and indicates the specific single argument as the problem, rather than the entire call.
