### PR TITLE
cli: Refactor show command & migrate to command arguments and views

### LINKED ISSUE #30195: `terraform show` fails with `different state lineage` error on `v1.1.1` if plan uses non-default state file
### Terraform Version

```
Terraform v1.1.1
on darwin_amd64
+ provider registry.terraform.io/kreuzwerker/docker v2.15.0
```

### Terraform Configuration Files

https://github.com/ansgarm/reproduction-cdktf-tf-1.1-issue/blob/main/main.tf.json

#### stdout / stderr
https://github.com/ansgarm/reproduction-cdktf-tf-1.1-issue/blob/main/full-log.txt

#### with `TF_LOG=trace`
https://github.com/ansgarm/reproduction-cdktf-tf-1.1-issue/blob/main/full-log-trace.txt

### Expected Behavior

Should not fail (works with Terraform `v1.0.7`)

### Actual Behavior

`terraform show test.plan` fails with
```
╷
│ Error: Saved plan does not match the given state
│
│ The given plan file can not be applied because it was created from a different state lineage.
╵
```

### Steps to Reproduce

See https://github.com/ansgarm/reproduction-cdktf-tf-1.1-issue

### Additional Context

The `cdk.tf.json` was generated by the CDK for Terraform and based on code from [this tutorial](https://learn.hashicorp.com/tutorials/terraform/cdktf-install?in=terraform/cdktf).

### References
- https://github.com/hashicorp/terraform-cdk/issues/1428

### PR DESCRIPTION
**Pull request by lafentres**
## Description 

This PR refactors the `show` command by:
1. Removing its dependence on a local backend and local run to load necessary data
1. Only loading the backend when we need it
1. Migrating it to use the command arguments and views packages
1. Removing the now unnecessary `DisablePlanFileStateLineageChecks` flag added in #30205  to fix #30195 

The goal of this PR is to make the show command significantly simpler and easier to understand, without changing existing functionality. 

See https://github.com/hashicorp/terraform/pull/30205#issuecomment-997113175 for more context

## Testing plan
main.tf used for relevant scenarios below
```
resource "null_resource" "test" {
  count = 1
}
```

Build this branch locally and compare the following basic scenarios to the most recent version of Terraform to make sure the command still functions the same:
1. Bad args (too many arguments, unsupported flags): 
   - `terraform show too many arguments`
      <details>
         <summary>Output</summary>
      
      ```
      # 15:56:53 # : ~/new-test $ terraform show too many arguments
      The show command expects at most two arguments.
       The path to a Terraform state or plan file, and optionally -json for json output.

      Usage: terraform [global options] show [options] [path]

        Reads and outputs a Terraform state or plan file in a human-readable
        form. If no path is specified, the current state will be shown.

      Options:

        -no-color           If specified, output won't contain any color.
        -json               If specified, output the Terraform plan or state in
                            a machine-readable form.
      # 16:00:51 # : ~/new-test $ $GOBIN/terraform show too many arguments
      ╷
      │ Error: Too many command line arguments
      │ 
      │ Expected at most one positional argument.
      ╵

      For more help on using this command, run:
        terraform show -help
      ```
      </details>
   - `terraform show -json too many arguments`
      <details>
         <summary>Output</summary>
      
      ```
      # 15:56:53 # : ~/new-test $ terraform show -json too many arguments
      The show command expects at most two arguments.
       The path to a Terraform state or plan file, and optionally -json for json output.

      Usage: terraform [global options] show [options] [path]

        Reads and outputs a Terraform state or plan file in a human-readable
        form. If no path is specified, the current state will be shown.

      Options:

        -no-color           If specified, output won't contain any color.
        -json               If specified, output the Terraform plan or state in
                            a machine-readable form.
      # 16:00:51 # : ~/new-test $ $GOBIN/terraform show -json too many arguments
      ╷
      │ Error: Too many command line arguments
      │ 
      │ Expected at most one positional argument.
      ╵

      For more help on using this command, run:
        terraform show -help
      ```
      </details>
1. No args, empty directory: 
   - `terraform show` in an empty directory
      <details>
         <summary>Output</summary>
      
      ```
      # 15:47:20 # : ~/new-test $ terraform show
      No state.
      # 15:47:30 # : ~/new-test $ $GOBIN/terraform show
      No state.
      ```
      </details>
   - `terraform show -json` in an empty directory
      <details>
         <summary>Output</summary>
      
      ```
      # 15:47:26 # : ~/new-test $ terraform show -json
      {"format_version":"1.0"}
      # 15:47:34 # : ~/new-test $ $GOBIN/terraform show -json
      {"format_version":"1.0"}
      ```
      </details>
1. No args, no statefile: 
   - `terraform show` in an directory where `terraform init` has been run
      <details>
         <summary>Output</summary>
      
      ```
      # 15:47:20 # : ~/new-test $ terraform show
      No state.
      # 15:47:30 # : ~/new-test $ $GOBIN/terraform show
      No state.
      ```
      </details>
   - `terraform show -json` in an directory where `terraform init` has been run
      <details>
         <summary>Output</summary>
      
      ```
      # 15:47:26 # : ~/new-test $ terraform show -json
      {"format_version":"1.0"}
      # 15:47:34 # : ~/new-test $ $GOBIN/terraform show -json
      {"format_version":"1.0"}
      ```
      </details>
1. No args, statefile exists: 
   - `terraform show` in a directory where you have a default `terraform.tfstate` statefile
      <details>
         <summary>Output</summary>
      
      ```
      # 16:02:44 # : ~/new-test $ terraform show
      # null_resource.test[0]:
      resource "null_resource" "test" {
          id = "5392993047991207106"
      }
      # 16:03:16 # : ~/new-test $ $GOBIN/terraform show
      # null_resource.test[0]:
      resource "null_resource" "test" {
          id = "5392993047991207106"
      }
      ```
      </details>
   - `terraform show -json` in a directory where you have a default `terraform.tfstate` statefile
      <details>
         <summary>Output</summary>
      
      ```
      # 16:04:08 # : ~/new-test $ terraform show -json | jq '.'
      {
        "format_version": "1.0",
        "terraform_version": "1.1.1",
        "values": {
          "root_module": {
            "resources": [
              {
                "address": "null_resource.test[0]",
                "mode": "managed",
                "type": "null_resource",
                "name": "test",
                "index": 0,
                "provider_name": "registry.terraform.io/hashicorp/null",
                "schema_version": 0,
                "values": {
                  "id": "5392993047991207106",
                  "triggers": null
                },
                "sensitive_values": {}
              }
            ]
          }
        }
      }
      # 16:04:28 # : ~/new-test $ $GOBIN/terraform show -json | jq '.'
      {
        "format_version": "1.0",
        "terraform_version": "1.1.1",
        "values": {
          "root_module": {
            "resources": [
              {
                "address": "null_resource.test[0]",
                "mode": "managed",
                "type": "null_resource",
                "name": "test",
                "index": 0,
                "provider_name": "registry.terraform.io/hashicorp/null",
                "schema_version": 0,
                "values": {
                  "id": "5392993047991207106",
                  "triggers": null
                },
                "sensitive_values": {}
              }
            ]
          }
        }
      }
      ```
      </details>
1. Statefile passed in as arg, statefile exists: 
   - `terraform show state.tfstate` & `terraform show -json state.tfstate` in a directory where you have a non-default `state.tfstate` statefile
      ```
      Output should look essentially like the previous scenario
      ```
1. Statefile passed in as arg, statefile does not exist: 
   - `terraform show state.tfstate` in a directory where you do not have a non-default `state.tfstate` statefile
      <details>
         <summary>Output</summary>
      
      ```
      # 16:06:49 # : ~/new-test $ terraform show state.tfstate
      Terraform couldn't read the given file as a state or plan file.
      The errors while attempting to read the file as each format are
      shown below.

      State read error: Error loading statefile: open state.tfstate: no such file or directory

      Plan read error: open state.tfstate: no such file or directory
      # 16:07:00 # : ~/new-test $ $GOBIN/terraform show state.tfstate
      ╷
      │ Error: Terraform couldn't read the given file as a state or plan file.
      │ The errors while attempting to read the file as each format are
      │ shown below.
      │ 
      │ State read error: Error loading statefile: open state.tfstate: no such file or directory
      │ 
      │ Plan read error: open state.tfstate: no such file or directory
      │ 
      │ 
      ╵
      ```
      </details>
   - `terraform show -json state.tfstate` in a directory where you do not have a non-default `state.tfstate` statefile
      <details>
         <summary>Output</summary>
      
      ```
      # 16:06:49 # : ~/new-test $ terraform show -json state.tfstate
      Terraform couldn't read the given file as a state or plan file.
      The errors while attempting to read the file as each format are
      shown below.

      State read error: Error loading statefile: open state.tfstate: no such file or directory

      Plan read error: open state.tfstate: no such file or directory
      # 16:07:00 # : ~/new-test $ $GOBIN/terraform show -json state.tfstate
      ╷
      │ Error: Terraform couldn't read the given file as a state or plan file.
      │ The errors while attempting to read the file as each format are
      │ shown below.
      │ 
      │ State read error: Error loading statefile: open state.tfstate: no such file or directory
      │ 
      │ Plan read error: open state.tfstate: no such file or directory
      │ 
      │ 
      ╵
      ```
      </details>
1. Plan file passed in as arg, plan file exists: 
   - `terraform show plan.tfplan` in a directory where you have a saved plan file `plan.tfplan`
      <details>
         <summary>Output</summary>
      
      ```
      # 16:13:50 # : ~/new-test $ terraform show plan.tfplan

      Terraform used the selected providers to generate the following execution plan.
      Resource actions are indicated with the following symbols:
        + create

      Terraform will perform the following actions:

        # null_resource.test[1] will be created
        + resource "null_resource" "test" {
            + id = (known after apply)
          }

      Plan: 1 to add, 0 to change, 0 to destroy.
      # 16:15:25 # : ~/new-test $ $GOBIN/terraform show plan.tfplan

      Terraform used the selected providers to generate the following execution plan.
      Resource actions are indicated with the following symbols:
        + create

      Terraform will perform the following actions:

        # null_resource.test[1] will be created
        + resource "null_resource" "test" {
            + id = (known after apply)
          }

      Plan: 1 to add, 0 to change, 0 to destroy.
      ```
      </details>
   - `terraform show -json plan.tfplan` in a directory where you have a saved plan file `plan.tfplan`
1. Plan file passed in as arg, plan file does not exist: 
   - `terraform show plan.tfplan` & `terraform show -json plan.tfplan` in a directory where you do not have a saved plan file `plan.tfplan`
      ```
      Output should look similar to the output in scenario #6
      ```
1. Plan file passed in as arg, plan file exists and has non-default state lineage:
   - Create a plan with non-default state lineage by running the following:
      `terraform init`
      `terraform apply -state test.tfstate -auto-approve`
      `terraform plan -state test.tfstate -out saved.tfplan`
   - Then run `terraform show saved.tfplan` & `terraform show -json saved.tfplan`
      ```
      Output should look similar to the output in scenario #7
      ```

Feel free to test any other scenarios you can think of. These are just some basic scenarios that have had bugs fixed recently or didn't previously have tests.

### CODE REVIEW

File: internal/command/views/show_test.go [hunk 1]
```diff
@@ -0,0 +1,184 @@
...
+			addrs.AbsProviderConfig{
+				Provider: addrs.NewDefaultProvider("test"),
+				Module:   addrs.RootModule,
+			},
+		)
+		// DeepCopy is used here to ensure our synthetic state matches exactly
+		// with a state that will have been copied during the command
+		// operation, and all fields have been copied correctly.
+	}).DeepCopy()
+}
```
Comment (lafentres) [inline internal/command/views/show_test.go:184]: I feel like there has got to be a cleaner, simpler way to get the data necessary for these tests in a way that makes sure the data is consistent but I'm not sure how to improve on this yet.

File: internal/command/show_test.go [hunk 2]
```diff
@@ -22,54 +21,111 @@ import (
...
-			Ui:               ui,
 			View:             view,
 		},
 	}
 
-	if code := c.Run([]string{}); code != 0 {
-		t.Fatalf("bad: \n%s", ui.OutputWriter.String())
+	// the statefile created by testStateFile is named state.tfstate
+	args := []string{
+		"state.tfstate",
```
Comment (alisdair) [inline internal/command/show_test.go:116]: Could we use `filepath.Base(statePath)` here instead of assuming the filename and leaving a comment?

File: internal/command/show.go [hunk 3]
```diff
@@ -24,243 +23,228 @@ type ShowCommand struct {
...
+	if planErr != nil {
+		stateFile, stateErr = getStateFromPath(path)
+		if stateErr != nil {
+			diags = diags.Append(fmt.Errorf(
+				"Terraform couldn't read the given file as a state or plan file.\n"+
+					"The errors while attempting to read the file as each format are\n"+
+					"shown below.\n\n"+
+					"State read error: %s\n\nPlan read error: %s",
+				stateErr,
+				planErr))
```
Comment (alisdair) [inline internal/command/show.go:181]: This err-as-diagnostic looks really awkward in the error output:

image

We could use a sourceless diagnostic here instead to improve the formatting a little. For example:

image

```go
			diags = diags.Append(tfdiags.Sourceless(
				tfdiags.Error,
				"Failed to read the given file as a state or plan file",
				fmt.Sprintf(
					"State read error: %s\n\nPlan read error: %s",
					stateErr,
					planErr,
				),
			))
```

File: internal/command/views/show_test.go (hunk 1 above)
Comment (alisdair) [reply internal/command/views/show_test.go:184]: This seems reasonable enough to me! Maybe my brain is broken from doing this exact sort of thing too many times.

**Review by alisdair — APPROVED** [review]
Looks great, thanks for doing this! 🎉 I have a couple of minor notes inline.

File: internal/command/show.go (hunk 3 above)
Comment (lafentres) [reply internal/command/show.go:181]: done!

File: internal/command/show_test.go (hunk 2 above)
Comment (lafentres) [reply internal/command/show_test.go:116]: done!
