### PR TITLE
dynamic set blocks produce inconsistent final plan

### LINKED ISSUE #22048: Error: Provider produced inconsistent final plan in 0.12.3
### Terraform Version

```
$ terraform version
Terraform v0.12.3
+ provider.aws v2.19.0
+ provider.template v2.1.2
```
### Debug Output
```
Error: Provider produced inconsistent final plan

When expanding the plan for aws_lb.nlb to include new values learned so far
during apply, provider "aws" produced an invalid new value for
.subnet_mapping: block set length changed from 1 to 2.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.*
```

### Expected Behavior

`aws_lb.nlb` resource should be created with list of `subnet_mapping` during first time `terraform apply` itself.

### Actual Behavior

`aws_lb.nlb` resource is getting created with list of `subnet_mapping` during second time `terraform apply` only and getting error output (shared in debug output) during first time apply.

### Steps to Reproduce

You can find a simple project to reproduce this bug here https://github.com/plar/terraform_dynamic_bug

### References

- Provider produced inconsistent final plan while dynamic block generation #21157

### PR DESCRIPTION
**Pull request by jbardin**
`AssertObjectCompatible` needs to detect possible dynamic `NestingSet` blocks, and ignore changes in set length. This check was already present in the `NestingList` case.

Fixes #22048

### CODE REVIEW

File: plans/objchange/compatible.go [hunk 1]
```diff
@@ -169,6 +169,14 @@ func assertObjectCompatible(schema *configschema.Block, planned, actual cty.Valu
 			})
 			errs = append(errs, setErrs...)
 
+			if maybeUnknownBlocks {
+				// When unknown blocks are present the final blocks may be
+				// at different indices than the planned blocks, so unfortunately
```
Comment (apparentlymart) [inline plans/objchange/compatible.go]: The sentiment of this comment is correct for both cases, but in the set case it's not really _indices_ that are the problem... maybe best to generalize this comment so it isn't confusing for a future reader who doesn't realize that this text was originally written for the list codepath.

Comment (jbardin) [reply plans/objchange/compatible.go]: oh yes, thanks. That was obviously a quick copy&paste ;)
