### PR TITLE
command/state_list.go: fix bug loading user-defined state

### LINKED ISSUE #19920: `-state=statefile` option is ignored when in workspace other than default
Terraform commands which support `-state=statefile` option is not working when in workspace other than default.

### Terraform Version

```
Terraform v0.11.11
```

### Terraform Configuration Files

```hcl
provider "aws" {
  access_key = "foo"
  secret_key = "bar"
  region  = "cn-north-1"
  version = "~> 1.34.0"
}

resource "aws_instance" "consumer_instance" {
}

```

### Debug Output

```
2019/01/04 16:33:13 [INFO] Terraform version: 0.11.11  ac4fff416318bf0915a0ab80e062a99ef3724334
2019/01/04 16:33:13 [INFO] Go runtime version: go1.11.1
2019/01/04 16:33:13 [INFO] CLI args: []string{"/usr/local/bin/terraform", "state", "list", "-state=terraform.tfstate.old"}
2019/01/04 16:33:13 [DEBUG] Attempting to open CLI config file: /Users/kelly/.terraformrc
2019/01/04 16:33:13 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/01/04 16:33:13 [INFO] CLI command args: []string{"state", "list", "-state=terraform.tfstate.old"}
2019/01/04 16:33:13 [DEBUG] command: loading backend config file: /Users/kelly/workspace/terraform
2019/01/04 16:33:13 [WARN] BackendOpts.Config not set, but config found
2019/01/04 16:33:13 [INFO] command: empty terraform config, returning nil
2019/01/04 16:33:13 [DEBUG] command: no data state file found for backend config
2019/01/04 16:33:13 [DEBUG] New state was assigned lineage "fc5ec0e1-93b1-d747-17a3-b2fa3cf493a8"
2019/01/04 16:33:13 [INFO] command: backend initialized: <nil>
2019/01/04 16:33:13 [DEBUG] checking for provider in "."
2019/01/04 16:33:13 [DEBUG] checking for provider in "/usr/local/bin"
2019/01/04 16:33:13 [DEBUG] checking for provider in ".terraform/plugins/darwin_amd64"
2019/01/04 16:33:13 [DEBUG] found provider "terraform-provider-alicloud_v1.25.0_x4"
2019/01/04 16:33:13 [DEBUG] found provider "terraform-provider-aws_v1.34.0_x4"
2019/01/04 16:33:13 [DEBUG] found valid plugin: "alicloud", "1.25.0", "/Users/kelly/workspace/terraform/.terraform/plugins/darwin_amd64/terraform-provider-alicloud_v1.25.0_x4"
2019/01/04 16:33:13 [DEBUG] found valid plugin: "aws", "1.34.0", "/Users/kelly/workspace/terraform/.terraform/plugins/darwin_amd64/terraform-provider-aws_v1.34.0_x4"
2019/01/04 16:33:13 [DEBUG] checking for provisioner in "."
2019/01/04 16:33:13 [DEBUG] checking for provisioner in "/usr/local/bin"
2019/01/04 16:33:13 [DEBUG] checking for provisioner in ".terraform/plugins/darwin_amd64"
2019/01/04 16:33:13 [INFO] command: backend <nil> is not enhanced, wrapping in local
2019/01/04 16:33:13 [DEBUG] plugin: waiting for all plugin processes to complete...

```

### Expected Behavior

Read state file specified in `-state` option.

### Actual Behavior

When in selected workspace other default like `foobar`, it keep trying to read file in ./terraform.tfstate.d/foobar/terraform.tfstate no matter `-state` option is supplied.

### Steps to Reproduce

```bash
$ terraform workspace select default
$ terraform state list -state=terraform.tfstate.old
aws_instance.consumer_instance

$ terraform workspace select foobar
$ terraform state list -state=terraform.tfstate.old
No state file was found!

State management commands require a state file. Run this command
in a directory where Terraform has been run or use the -state flag
to point the command to a specific state location.
```

### Additional Context

None

### References

None

### PR DESCRIPTION
**Pull request by mildwonkey**
If the user supplied a state path via the `-state` flag and terraform
was running in a workspace other than `default`, the state was not being
loaded properly. Fixes #19920

### CODE REVIEW

File: command/output.go [hunk 1]
```diff
@@ -77,7 +77,7 @@ func (c *OutputCommand) Run(args []string) int {
 	}
 
 	if err := stateStore.RefreshState(); err != nil {
-		c.Ui.Error(fmt.Sprintf("Failed to load state: %s", err))
+		c.Ui.Error(fmt.Sprintf("Failed to refresh state: %s", err))
```
Comment (apparentlymart) [inline command/output.go]: I think we need to be careful about this one because "refresh state" has a specific meaning in the user-facing model of making API calls to ensure that objects in the state match their remote counterparts, but here we're just retrieving the existing state from the state storage backend.

It's unfortunate that this internal API has a confusing name, but pushing that terminology collision out into the user-facing error message is likely to lead to misunderstandings, I think. "Load" or "read" are, I think, the best verbs for what `RefreshState` actually does.
