### PR TITLE
core: Use -state-out option when applying from a plan

### LINKED ISSUE #7264: Flag -state-out is ignored on terraform apply when plan file is used
### Terraform Version
Terraform v0.6.16

### Affected Resource(s)
- multiple resources

### Terraform Configuration Files
```hcl
resource "aws_instance" "kairosdb" {
  count                  = "${var.kairosdb_instance_count}"
  instance_type          = "${var.kairosdb_instance_type}"
  ami                    = "ami-d7a751b7"
  subnet_id              = "${element(split(",", var.private_subnets), count.index % 3)}"
  vpc_security_group_ids = ["${var.default_security_group}"]
  iam_instance_profile   = "Infra"

  tags {
    Name        = "${var.env}-kairosdb-${count.index}"
    Application = "kairosdb"
    Environment = "${var.env}"
    Groups      = "kairosdb"
  }
}

resource "aws_elb" "kairosdb" {
  name                        = "${var.env}-kairosdb-elb-0"
  subnets                     = ["${split(",", var.private_subnets)}"]
  instances                   = ["${aws_instance.kairosdb.*.id}"]
  internal                    = true
  cross_zone_load_balancing   = true
  idle_timeout                = 60
  connection_draining         = true
  connection_draining_timeout = 400

  listener {
    lb_port           = 80
    lb_protocol       = "http"
    instance_port     = 8080
    instance_protocol = "http"
  }

  health_check {
    healthy_threshold   = 10
    unhealthy_threshold = 2
    timeout             = 5
    target              = "HTTP:8080/"
    interval            = 30
  }

  tags {
    Name = "${var.env}-kairosdb-elb-0"
  }
}

output "dns_name" {
  value = "${aws_elb.kairosdb.dns_name}"
}
```

### Debug Output
https://gist.githubusercontent.com/jamesmaidment/ab3d0c19354c3424cf3e17bb39a4c71c/raw/dc88b2517930e590dddf1592defbf3c89ebd3b61/terraform.apply.log

### Expected Behavior
State file created

### Actual Behavior
No state file

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan -state=terraform.tfstate -out=terraform.tfplan -var-file=qa.tfvars service`
2. `terraform apply -state=terraform.tfstate -state-out=terraform-new.tfstate terraform.tfplan`

### PR DESCRIPTION
**Pull request by jbardin**
When working from an existing plan, we weren't setting the PathOut field
for a LocalState. This required adding an outPath argument to the
StateFromPlan function to avoid having to introspect the returned
state.State interface to find the appropriate field.

Fixes #7264

### CODE REVIEW

**Comment by jbardin** [comment]
test coming soon...

**Comment by jbardin** [comment]
Added a test.

This runs a plan from inside an Apply test to generate a new plan file. We could also just put the plan file in a test fixture, but I thought this way was less likely to get stale.

File: command/apply_test.go [hunk 1]
```diff
@@ -1326,6 +1326,60 @@ func TestApply_disableBackup(t *testing.T) {
...
 }
 
+// -state-out wasn't taking effect when a plan is supplied. GH-7264
+func TestApply_stateOutWithPlan(t *testing.T) {
+	p := testProvider()
+	ui := new(cli.MockUi)
+
+	tmpDir := testTempDir(t)
+	defer os.RemoveAll(tmpDir)
+	fmt.Println("tmpDir:", tmpDir)
```
Comment (phinze) [inline command/apply_test.go]: stray print here

**Comment by phinze** [comment]
Found a stray print inline, other than that this LGTM!
