### PR TITLE
terraform: Relax provider config ref constraints

### LINKED ISSUE #25407: Error when using local.variables in Provider block.
### Terraform Version

```
$ terraform version
Terraform v0.13.0-beta2
+ provider registry.terraform.io/hashicorp/aws v2.66.0

```

### Terraform Configuration Files

```hcl
locals {
  region = "eu-central-1"
  profile = "dev"
}

provider "aws" {
  profile = local.profile
  region  = local.region

  assume_role {
    role_arn     = "xxxxxx"
  }

}

resource "aws_s3_bucket" "tf-bucket" {
  acl    = "private"
  bucket = "dev-test-tf-0.13-beta"
  region = local.region
}
```

### Actual Behavior

Terraform reports the following when trying to import this simple bucket: 
```bash
Error: Invalid provider dependency for import

  on .../terraform/test/main.tf line 7, in provider "aws":
   7:   profile = local.profile

The configuration for provider["registry.terraform.io/hashicorp/aws"] depends
on local.profile. Providers used with import must either have literal
configuration or refer only to input variables.


Error: Invalid provider dependency for import

  on .../terraform/test/main.tf line 8, in provider "aws":
   8:   region  = local.region

The configuration for provider["registry.terraform.io/hashicorp/aws"] depends
on local.region. Providers used with import must either have literal
configuration or refer only to input variables.
```

### Expected Behavior

Meanwhile using terraform v0.12 in the same folder:
```bash
$terraform version
Terraform v0.12.26
+ provider.aws v2.66.0

$ terraform import aws_s3_bucket.tf-bucket dev-test-tf-0.13-beta
aws_s3_bucket.tf-bucket: Importing from ID "dev-test-tf-0.13-beta"...
aws_s3_bucket.tf-bucket: Import prepared!
  Prepared aws_s3_bucket for import
aws_s3_bucket.tf-bucket: Refreshing state... [id=dev-test-tf-0.13-beta]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

If this is not fixed it is a great deal breaker for migrating to v0.13 as it would require to destroy all our AWS resources. In our configuration the aws provider is created dynamically using locals that are terraform.workspace related. The solution to hard-code the provider's block is a leap back for terraform.

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform import aws_s3_bucket.tf-bucket dev-test-tf-0.13-beta`

### PR DESCRIPTION
**Pull request by alisdair**
When configuring providers, it is normally valid to refer to any value which is known at apply time. This can include resource instance attributes, variables, locals, and so on.

The import command has a simpler graph evaluation, which means that many of these values are unknown. We previously prevented this from happening by restricting provider configuration references to input variables (#22862), but this was more restrictive than is necessary.

This commit changes how we verify provider configuration for import.  We no longer inspect the configuration references during graph building, because this is too early to determine if these values will become known
or not.

Instead, when the provider is configured during evaluation, we check if the configuration value is wholly known. If not, we fail with a diagnostic error.

Includes a test case which verifies that providers can now be configured using locals as well as vars, and an updated test case which verifies that providers cannot be configured with references to resources.

Fixes #25407

### CODE REVIEW

File: terraform/evaltree_provider.go [hunk 1]
```diff
@@ -18,19 +18,6 @@ func ProviderEvalTree(n *NodeApplyableProvider, config *configs.Provider) EvalNo
...
-		Node: &EvalSequence{
-			Nodes: []EvalNode{
-				&EvalGetProvider{
-					Addr:   addr,
-					Output: &provider,
-				},
-			},
-		},
-	})
-
```
Comment (alisdair) [inline terraform/evaltree_provider.go:33]: I think this step was redundant with the "everything except validate" one a few lines below.

File: terraform/evaltree_provider.go [hunk 2]
```diff
@@ -48,7 +35,6 @@ func ProviderEvalTree(n *NodeApplyableProvider, config *configs.Provider) EvalNo
 		},
 	})
 
-	// Apply stuff
```
Comment (alisdair) [inline terraform/evaltree_provider.go:51]: This comment (and the one above) did not seem to mean anything. I'd happily add more comments here if I knew what to write…
