### PR TITLE
configs/configupgrade: do not panic over int value out of range

### LINKED ISSUE #23148: Terraform crash parsing a big integer during the upgrade to 0.12
### Terraform Version

```
v0.12.10
```

### Terraform Configuration Files

```hcl
variable "axis_high_watermark" {
  default = 17976931348623157000
}

variable "axis_low_watermark" {
  default  = -17976931348623157000
}

variable "axis_max_value" {
  default = 17976931348623157000
}

variable "axis_min_value" {
  default = -17976931348623157000
}
```

### Crash Output

```
2019/10/22 01:37:28 [INFO] Terraform version: 0.12.10  
2019/10/22 01:37:28 [INFO] Go runtime version: go1.12.9
2019/10/22 01:37:28 [INFO] CLI args: []string{"/usr/bin/terraform12", "0.12upgrade"}
2019/10/22 01:37:28 [DEBUG] Attempting to open CLI config file: /home/igor_mb/.terraformrc
2019/10/22 01:37:28 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/10/22 01:37:28 [INFO] CLI command args: []string{"0.12upgrade"}
2019/10/22 01:37:28 [DEBUG] command: asking for input: "Would you like to upgrade the module in the current directory?"
2019/10/22 01:37:29 [DEBUG] checking for provider in "."
2019/10/22 01:37:29 [DEBUG] checking for provider in "/usr/bin"
2019/10/22 01:37:29 [DEBUG] checking for provider in ".terraform/plugins/linux_amd64"
2019/10/22 01:37:29 [DEBUG] found provider "terraform-provider-signalfx_v4.9.1_x4"
2019/10/22 01:37:29 [DEBUG] found valid plugin: "signalfx", "4.9.1", "/home/igor_mb/workspace/terraform-sda/signalfx/dashboards/.terraform/plugins/linux_amd64/terraform-provider-signalfx_v4.9.1_x4"
2019/10/22 01:37:29 [DEBUG] checking for provisioner in "."
2019/10/22 01:37:29 [DEBUG] checking for provisioner in "/usr/bin"
2019/10/22 01:37:29 [DEBUG] checking for provisioner in ".terraform/plugins/linux_amd64"
2019/10/22 01:37:29 [TRACE] configupgrade: Analyzing "prvider.tf"
2019/10/22 01:37:29 [TRACE] configupgrade: Analyzing "variables.tf"
2019/10/22 01:37:29 [TRACE] configupgrade: Analyzing "dashboard-groups.tf"
2019/10/22 01:37:29 [TRACE] Resource block for signalfx_dashboard_group.dashboardgroup_sda requires provider "signalfx"
2019/10/22 01:37:29 [TRACE] configupgrade: Analyzing "dashboards-kafka.tf"
2019/10/22 01:37:29 [ERROR] Failed to parse "dashboards-kafka.tf": At 25:13: unexpected token while parsing list: IDENT
2019/10/22 01:37:29 [TRACE] configupgrade: Analyzing "provider.tf"
2019/10/22 01:37:29 [TRACE] Provider block requires provider "signalfx"
2019/10/22 01:37:30 [TRACE] Fetching schema from provider "signalfx"
2019-10-22T01:37:30.121+0300 [INFO]  plugin: configuring client automatic mTLS
2019-10-22T01:37:30.153+0300 [DEBUG] plugin: starting plugin: path=/home/igor_mb/workspace/terraform-sda/signalfx/dashboards/.terraform/plugins/linux_amd64/terraform-provider-signalfx_v4.9.1_x4 args=[/home/igor_mb/workspace/terraform-sda/signalfx/dashboards/.terraform/plugins/linux_amd64/terraform-provider-signalfx_v4.9.1_x4]
2019-10-22T01:37:30.153+0300 [DEBUG] plugin: plugin started: path=/home/igor_mb/workspace/terraform-sda/signalfx/dashboards/.terraform/plugins/linux_amd64/terraform-provider-signalfx_v4.9.1_x4 pid=8039
2019-10-22T01:37:30.153+0300 [DEBUG] plugin: waiting for RPC address: path=/home/igor_mb/workspace/terraform-sda/signalfx/dashboards/.terraform/plugins/linux_amd64/terraform-provider-signalfx_v4.9.1_x4
2019-10-22T01:37:30.160+0300 [INFO]  plugin.terraform-provider-signalfx_v4.9.1_x4: configuring server automatic mTLS: timestamp=2019-10-22T01:37:30.159+0300
2019-10-22T01:37:30.192+0300 [DEBUG] plugin.terraform-provider-signalfx_v4.9.1_x4: plugin address: address=/tmp/plugin914104273 network=unix timestamp=2019-10-22T01:37:30.192+0300
2019-10-22T01:37:30.192+0300 [DEBUG] plugin: using plugin: version=5
2019/10/22 01:37:30 [TRACE] GRPCProvider: GetSchema
2019/10/22 01:37:30 [TRACE] Fetching schema from provisioner "chef"
2019-10-22T01:37:30.257+0300 [DEBUG] plugin: starting plugin: path=/usr/bin/terraform12 args=[/usr/bin/terraform12, internal-plugin, provisioner, chef]
2019-10-22T01:37:30.257+0300 [DEBUG] plugin: plugin started: path=/usr/bin/terraform12 pid=8053
2019-10-22T01:37:30.257+0300 [DEBUG] plugin: waiting for RPC address: path=/usr/bin/terraform12
2019-10-22T01:37:30.267+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [INFO] Terraform version: 0.12.10  
2019-10-22T01:37:30.267+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [INFO] Go runtime version: go1.12.9
2019-10-22T01:37:30.267+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [INFO] CLI args: []string{"/usr/bin/terraform12", "internal-plugin", "provisioner", "chef"}
2019-10-22T01:37:30.267+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [DEBUG] Attempting to open CLI config file: /home/igor_mb/.terraformrc
2019-10-22T01:37:30.267+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019-10-22T01:37:30.267+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [INFO] CLI command args: []string{"internal-plugin", "provisioner", "chef"}
2019-10-22T01:37:30.268+0300 [DEBUG] plugin.terraform12: chef-provisioner (internal) 2019/10/22 01:37:30 [INFO] Starting provisioner plugin chef
2019-10-22T01:37:30.268+0300 [DEBUG] plugin.terraform12: plugin address: address=/tmp/plugin723792245 network=unix timestamp=2019-10-22T01:37:30.268+0300
2019-10-22T01:37:30.268+0300 [DEBUG] plugin: using plugin: version=5
2019/10/22 01:37:30 [TRACE] Fetching schema from provisioner "file"
2019-10-22T01:37:30.270+0300 [DEBUG] plugin: starting plugin: path=/usr/bin/terraform12 args=[/usr/bin/terraform12, internal-plugin, provisioner, file]
2019-10-22T01:37:30.270+0300 [DEBUG] plugin: plugin started: path=/usr/bin/terraform12 pid=8064
2019-10-22T01:37:30.270+0300 [DEBUG] plugin: waiting for RPC address: path=/usr/bin/terraform12
2019-10-22T01:37:30.279+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [INFO] Terraform version: 0.12.10  
2019-10-22T01:37:30.279+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [INFO] Go runtime version: go1.12.9
2019-10-22T01:37:30.279+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [INFO] CLI args: []string{"/usr/bin/terraform12", "internal-plugin", "provisioner", "file"}
2019-10-22T01:37:30.279+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [DEBUG] Attempting to open CLI config file: /home/igor_mb/.terraformrc
2019-10-22T01:37:30.279+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019-10-22T01:37:30.279+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [INFO] CLI command args: []string{"internal-plugin", "provisioner", "file"}
2019-10-22T01:37:30.279+0300 [DEBUG] plugin.terraform12: file-provisioner (internal) 2019/10/22 01:37:30 [INFO] Starting provisioner plugin file
2019-10-22T01:37:30.279+0300 [DEBUG] plugin.terraform12: plugin address: address=/tmp/plugin017219757 network=unix timestamp=2019-10-22T01:37:30.279+0300
2019-10-22T01:37:30.279+0300 [DEBUG] plugin: using plugin: version=5
2019/10/22 01:37:30 [TRACE] Fetching schema from provisioner "habitat"
2019-10-22T01:37:30.281+0300 [DEBUG] plugin: starting plugin: path=/usr/bin/terraform12 args=[/usr/bin/terraform12, internal-plugin, provisioner, habitat]
2019-10-22T01:37:30.282+0300 [DEBUG] plugin: plugin started: path=/usr/bin/terraform12 pid=8073
2019-10-22T01:37:30.282+0300 [DEBUG] plugin: waiting for RPC address: path=/usr/bin/terraform12
2019-10-22T01:37:30.291+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [INFO] Terraform version: 0.12.10  
2019-10-22T01:37:30.291+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [INFO] Go runtime version: go1.12.9
2019-10-22T01:37:30.291+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [INFO] CLI args: []string{"/usr/bin/terraform12", "internal-plugin", "provisioner", "habitat"}
2019-10-22T01:37:30.291+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [DEBUG] Attempting to open CLI config file: /home/igor_mb/.terraformrc
2019-10-22T01:37:30.291+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019-10-22T01:37:30.292+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [INFO] CLI command args: []string{"internal-plugin", "provisioner", "habitat"}
2019-10-22T01:37:30.292+0300 [DEBUG] plugin.terraform12: habitat-provisioner (internal) 2019/10/22 01:37:30 [INFO] Starting provisioner plugin habitat
2019-10-22T01:37:30.292+0300 [DEBUG] plugin.terraform12: plugin address: address=/tmp/plugin199394191 network=unix timestamp=2019-10-22T01:37:30.292+0300
2019-10-22T01:37:30.292+0300 [DEBUG] plugin: using plugin: version=5
2019/10/22 01:37:30 [TRACE] Fetching schema from provisioner "local-exec"
2019-10-22T01:37:30.293+0300 [DEBUG] plugin: starting plugin: path=/usr/bin/terraform12 args=[/usr/bin/terraform12, internal-plugin, provisioner, local-exec]
2019-10-22T01:37:30.293+0300 [DEBUG] plugin: plugin started: path=/usr/bin/terraform12 pid=8083
2019-10-22T01:37:30.293+0300 [DEBUG] plugin: waiting for RPC address: path=/usr/bin/terraform12
2019-10-22T01:37:30.303+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [INFO] Terraform version: 0.12.10  
2019-10-22T01:37:30.303+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [INFO] Go runtime version: go1.12.9
2019-10-22T01:37:30.303+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [INFO] CLI args: []string{"/usr/bin/terraform12", "internal-plugin", "provisioner", "local-exec"}
2019-10-22T01:37:30.303+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [DEBUG] Attempting to open CLI config file: /home/igor_mb/.terraformrc
2019-10-22T01:37:30.303+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019-10-22T01:37:30.303+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [INFO] CLI command args: []string{"internal-plugin", "provisioner", "local-exec"}
2019-10-22T01:37:30.303+0300 [DEBUG] plugin.terraform12: local-exec-provisioner (internal) 2019/10/22 01:37:30 [INFO] Starting provisioner plugin local-exec
2019-10-22T01:37:30.303+0300 [DEBUG] plugin.terraform12: plugin address: address=/tmp/plugin557087575 network=unix timestamp=2019-10-22T01:37:30.303+0300
2019-10-22T01:37:30.304+0300 [DEBUG] plugin: using plugin: version=5
2019/10/22 01:37:30 [TRACE] Fetching schema from provisioner "puppet"
2019-10-22T01:37:30.304+0300 [DEBUG] plugin: starting plugin: path=/usr/bin/terraform12 args=[/usr/bin/terraform12, internal-plugin, provisioner, puppet]
2019-10-22T01:37:30.305+0300 [DEBUG] plugin: plugin started: path=/usr/bin/terraform12 pid=8093
2019-10-22T01:37:30.305+0300 [DEBUG] plugin: waiting for RPC address: path=/usr/bin/terraform12
2019-10-22T01:37:30.314+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [INFO] Terraform version: 0.12.10  
2019-10-22T01:37:30.314+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [INFO] Go runtime version: go1.12.9
2019-10-22T01:37:30.314+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [INFO] CLI args: []string{"/usr/bin/terraform12", "internal-plugin", "provisioner", "puppet"}
2019-10-22T01:37:30.314+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [DEBUG] Attempting to open CLI config file: /home/igor_mb/.terraformrc
2019-10-22T01:37:30.314+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019-10-22T01:37:30.314+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [INFO] CLI command args: []string{"internal-plugin", "provisioner", "puppet"}
2019-10-22T01:37:30.314+0300 [DEBUG] plugin.terraform12: puppet-provisioner (internal) 2019/10/22 01:37:30 [INFO] Starting provisioner plugin puppet
2019-10-22T01:37:30.315+0300 [DEBUG] plugin.terraform12: plugin address: address=/tmp/plugin225005912 network=unix timestamp=2019-10-22T01:37:30.315+0300
2019-10-22T01:37:30.315+0300 [DEBUG] plugin: using plugin: version=5
2019/10/22 01:37:30 [TRACE] Fetching schema from provisioner "remote-exec"
2019-10-22T01:37:30.316+0300 [DEBUG] plugin: starting plugin: path=/usr/bin/terraform12 args=[/usr/bin/terraform12, internal-plugin, provisioner, remote-exec]
2019-10-22T01:37:30.316+0300 [DEBUG] plugin: plugin started: path=/usr/bin/terraform12 pid=8102
2019-10-22T01:37:30.316+0300 [DEBUG] plugin: waiting for RPC address: path=/usr/bin/terraform12
2019-10-22T01:37:30.326+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [INFO] Terraform version: 0.12.10  
2019-10-22T01:37:30.326+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [INFO] Go runtime version: go1.12.9
2019-10-22T01:37:30.326+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [INFO] CLI args: []string{"/usr/bin/terraform12", "internal-plugin", "provisioner", "remote-exec"}
2019-10-22T01:37:30.326+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [DEBUG] Attempting to open CLI config file: /home/igor_mb/.terraformrc
2019-10-22T01:37:30.326+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019-10-22T01:37:30.326+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [INFO] CLI command args: []string{"internal-plugin", "provisioner", "remote-exec"}
2019-10-22T01:37:30.326+0300 [DEBUG] plugin.terraform12: remote-exec-provisioner (internal) 2019/10/22 01:37:30 [INFO] Starting provisioner plugin remote-exec
2019-10-22T01:37:30.327+0300 [DEBUG] plugin.terraform12: plugin address: address=/tmp/plugin893230264 network=unix timestamp=2019-10-22T01:37:30.327+0300
2019-10-22T01:37:30.327+0300 [DEBUG] plugin: using plugin: version=5
2019/10/22 01:37:30 [TRACE] Fetching schema from provisioner "salt-masterless"
2019-10-22T01:37:30.328+0300 [DEBUG] plugin: starting plugin: path=/usr/bin/terraform12 args=[/usr/bin/terraform12, internal-plugin, provisioner, salt-masterless]
2019-10-22T01:37:30.328+0300 [DEBUG] plugin: plugin started: path=/usr/bin/terraform12 pid=8113
2019-10-22T01:37:30.328+0300 [DEBUG] plugin: waiting for RPC address: path=/usr/bin/terraform12
2019-10-22T01:37:30.338+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [INFO] Terraform version: 0.12.10  
2019-10-22T01:37:30.338+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [INFO] Go runtime version: go1.12.9
2019-10-22T01:37:30.338+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [INFO] CLI args: []string{"/usr/bin/terraform12", "internal-plugin", "provisioner", "salt-masterless"}
2019-10-22T01:37:30.338+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [DEBUG] Attempting to open CLI config file: /home/igor_mb/.terraformrc
2019-10-22T01:37:30.338+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019-10-22T01:37:30.339+0300 [DEBUG] plugin.terraform12: 2019/10/22 01:37:30 [INFO] CLI command args: []string{"internal-plugin", "provisioner", "salt-masterless"}
2019-10-22T01:37:30.339+0300 [DEBUG] plugin.terraform12: salt-masterless-provisioner (internal) 2019/10/22 01:37:30 [INFO] Starting provisioner plugin salt-masterless
2019-10-22T01:37:30.339+0300 [DEBUG] plugin.terraform12: plugin address: address=/tmp/plugin623708899 network=unix timestamp=2019-10-22T01:37:30.339+0300
2019-10-22T01:37:30.339+0300 [DEBUG] plugin: using plugin: version=5
2019/10/22 01:37:30 [TRACE] configupgrade: Working on "dashboard-groups.tf"
2019/10/22 01:37:30 [TRACE] configupgrade: Upgrading signalfx_dashboard_group.dashboardgroup_sda at dashboard-groups.tf:6,1-1
2019/10/22 01:37:30 [TRACE] configupgrade: Upgrading output.dashboardgroup_sda_id at dashboard-groups.tf:11,1-1
2019/10/22 01:37:30 [TRACE] configupgrade: Working on "dashboards-kafka.tf"
2019/10/22 01:37:30 [TRACE] configupgrade: Working on "provider.tf"
2019/10/22 01:37:30 [TRACE] configupgrade: Upgrading provider.signalfx at provider.tf:31,1-1
2019/10/22 01:37:30 [TRACE] configupgrade: Working on "prvider.tf"
2019/10/22 01:37:30 [TRACE] configupgrade: Working on "variables.tf"
2019/10/22 01:37:30 [TRACE] configupgrade: Upgrading var.axis_high_watermark at variables.tf:20,1-1
2019-10-22T01:37:30.342+0300 [DEBUG] plugin: plugin process exited: path=/home/igor_mb/workspace/terraform-sda/signalfx/dashboards/.terraform/plugins/linux_amd64/terraform-provider-signalfx_v4.9.1_x4 pid=8039
2019-10-22T01:37:30.342+0300 [DEBUG] plugin: plugin exited
2019-10-22T01:37:30.343+0300 [DEBUG] plugin: plugin process exited: path=/usr/bin/terraform12 pid=8102
2019-10-22T01:37:30.343+0300 [DEBUG] plugin: plugin exited
2019-10-22T01:37:30.344+0300 [DEBUG] plugin: plugin process exited: path=/usr/bin/terraform12 pid=8083
2019-10-22T01:37:30.344+0300 [DEBUG] plugin: plugin exited
2019-10-22T01:37:30.345+0300 [DEBUG] plugin: plugin process exited: path=/usr/bin/terraform12 pid=8053
2019-10-22T01:37:30.345+0300 [DEBUG] plugin: plugin exited
2019-10-22T01:37:30.346+0300 [DEBUG] plugin: plugin process exited: path=/usr/bin/terraform12 pid=8093
2019-10-22T01:37:30.346+0300 [DEBUG] plugin: plugin exited
2019-10-22T01:37:30.346+0300 [DEBUG] plugin: plugin process exited: path=/usr/bin/terraform12 pid=8113
2019-10-22T01:37:30.346+0300 [DEBUG] plugin: plugin exited
2019-10-22T01:37:30.348+0300 [DEBUG] plugin: plugin process exited: path=/usr/bin/terraform12 pid=8064
2019-10-22T01:37:30.348+0300 [DEBUG] plugin: plugin exited
2019-10-22T01:37:30.348+0300 [DEBUG] plugin: plugin process exited: path=/usr/bin/terraform12 pid=8073
2019-10-22T01:37:30.348+0300 [DEBUG] plugin: plugin exited
panic: strconv.ParseInt: parsing "17976931348623157000": value out of range

goroutine 1 [running]:
github.com/hashicorp/hcl/hcl/token.Token.Value(0x6, 0x0, 0x0, 0x43a, 0x15, 0xd, 0xc000426fe0, 0x14, 0x0, 0x0, ...)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/hashicorp/hcl@v0.0.0-20170504190234-a4b07c25de5f/hcl/token/token.go:138 +0x4f8
github.com/hashicorp/terraform/configs/configupgrade.upgradeExpr(0x1ce68e0, 0xc00002d900, 0xc0004401c2, 0xc, 0x0, 0xc0004da240, 0x0, 0x0, 0x0, 0xc0005e0028, ...)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/configs/configupgrade/upgrade_expr.go:41 +0x3e50
github.com/hashicorp/terraform/configs/configupgrade.upgradeExpr(0x1b62580, 0xc0004a5380, 0xc0004401c2, 0xc, 0x600, 0xc0004da240, 0xc00027aab0, 0x32bf87d, 0xc0005e0578, 0x77aca6, ...)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/configs/configupgrade/upgrade_expr.go:38 +0x59d8
github.com/hashicorp/terraform/configs/configupgrade.noInterpAttributeRule.func1(0x1b62580, 0xc0004a5380, 0x0, 0x430, 0x15, 0x3, 0xc00034c997, 0x7)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/configs/configupgrade/upgrade_body.go:43 +0x59
github.com/hashicorp/terraform/configs/configupgrade.attributeRule.func1(0xc00027a8d0, 0xc0004270e0, 0x17, 0xc0004a5320, 0xc0005e1548, 0x1, 0xc00034c997)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/configs/configupgrade/upgrade_body.go:252 +0x2b6
github.com/hashicorp/terraform/configs/configupgrade.upgradeBlockBody(0xc0004401c2, 0xc, 0xc0004270e0, 0x17, 0xc00027a8d0, 0xc00000ebb0, 0x1, 0x1, 0x0, 0x0, ...)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/configs/configupgrade/upgrade_native.go:469 +0xacc
github.com/hashicorp/terraform/configs/configupgrade.(*Upgrader).upgradeNativeSyntaxFile(0xc0005e1960, 0xc0004401c2, 0xc, 0xc000596000, 0x639, 0x839, 0xc0004da240, 0x1, 0x1, 0x5b9, ...)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/configs/configupgrade/upgrade_native.go:166 +0x35db
github.com/hashicorp/terraform/configs/configupgrade.(*Upgrader).Upgrade(0xc0005e1960, 0xc00043e3c0, 0x1e2114d, 0x1, 0xc000448150, 0x3, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/configs/configupgrade/upgrade.go:102 +0x49e
github.com/hashicorp/terraform/command.(*ZeroTwelveUpgradeCommand).Run(0xc0005444e0, 0xc00000c0b0, 0x0, 0x0, 0xc000479030)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/012_config_upgrade.go:159 +0x916
github.com/mitchellh/cli.(*CLI).Run(0xc0004297c0, 0xc0004297c0, 0xc00022fd90, 0x1)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x1f1
main.wrappedMain(0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:235 +0xb66
main.realMain(0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:100 +0xb4
main.main()
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:36 +0x3b
```
### Steps to Reproduce

1. `terraform init`
2. `terraform 0.12upgrade`

### PR DESCRIPTION
**Pull request by mildwonkey**
Terraform 0.12upgrade assumes that the configuration has passed 0.11
init, but did not explicitly check that the configuration was valid.
Certain issues would not get caught because the configuration was
syntactically valid. In this case, int or float values out of range
resulted in a panic.

Since running a 0.11 validate command is a breaking change, this PR
merely moves the `Value()` logic for ints and floats into configupgrade so
the error can be returned to the user, instead of causing a panic.

Fixes #23148

### CODE REVIEW

File: configs/configupgrade/upgrade_expr.go [hunk 1]
```diff
@@ -38,9 +38,9 @@ Value:
 		return upgradeExpr(tv.Token, filename, interp, an)
 
 	case hcl1token.Token:
-		litVal := tv.Value()
```
Comment (pselle) [inline configs/configupgrade/upgrade_expr.go]: It's unclear from the diff why this was moved to happen in the switch cases vs leaving it here?

Comment (mildwonkey) [reply configs/configupgrade/upgrade_expr.go]: `Value()`  panics if there is an error converting the token Text value to the indicated type (https://github.com/hashicorp/hcl/blob/master/hcl/token/token.go#L128). 

In normal terraform usage, some variation of `validate()` would have caught that the token literal value was too long and exited with an error before now. Since that's not happening in `0.12upgrade`, I moved the `Value()` call into the individual statements so that I could skip it altogether when the token is a number and instead directly convert the `Text` to int or float (or not, in the case of an error) without panicking.

Comment (pselle) [reply configs/configupgrade/upgrade_expr.go]: ahhhh thank you! TIL
