### PR TITLE
filter nulls when shimming a config

### LINKED ISSUE #20889: Terraform crash when creating list with empty remote data lookup.
### Terraform Version

```
Terraform v0.12.0-beta1
+ provider.aws v1.60.0-dev20190216h00-dev
```

### Terraform Configuration Files

```hcl
 [~/terraform.d/environments/stage1]$ cat ec2.tf 
module "bastion" {
  source      = "../../modules/ec2"
  vpc             = "${data.terraform_remote_state.vpc.outputs}"
  serverclass = "bastion"
  subnet_id       = module.subnet_service1.id
  instance_type = "t2.micro"
}

module "bastion2" {
  source      = "../../modules/ec2"
  vpc             = "${data.terraform_remote_state.vpc.outputs}"
  instance_name = "bastion2"
  subnet_id       = module.subnet_service1.id
  instance_type = "t2.micro"
}
```
```
[~/terraform.d/modules/ec2]$ cat main.tf 
data "aws_security_group" "common" {
  filter {
    name   = "tag:Name"
    values = ["sg_common"]
  }
}

data "aws_security_group" "serverclass" {
  filter {
    name   = "tag:serverclass"
    values = ["${var.serverclass}"]
  }
}

resource "aws_instance" "this" {
  ami                         = "${data.aws_ami.amazon-linux.id}"
  instance_type               = "${var.instance_type}"
  monitoring                  = true
  vpc_security_group_ids      = "${var.security_groups == true ? var.security_groups : [data.aws_security_group.common.id, data.aws_security_group.serverclass.id]}"
  subnet_id                   = "${var.subnet_id}"
  associate_public_ip_address = true

  tags = {
    Name        = "${var.instance_name}"
  }
}
```

```
[~/terraform.d/modules/ec2]$ cat variables.tf 
variable "aws_region" {
  description = "AWS region to deploy resource"
  default     = "us-east-1"
}

variable "vpc" {
  description = "Map of VPC details"
}

variable "subnet_id" {
  description = "Subnet to build the host"
  default     = ""
}

variable "security_groups" {
  type = "list"
  description = "SGs to attach to host"
  default = null
}

variable "instance_name" {
    description = "Name of ec2 instance"
    default = "noname"
}

variable "instance_type" {
    description = "EC2 instance type"
}

variable "serverclass" {
    description = "EC2 serverclass"
    default = null
}


data "aws_ami" "amazon-linux" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "owner-alias"
    values = ["amazon"]
  }

  filter {
    name   = "root-device-type"
    values = ["ebs"]
  }

  filter {
    name   = "name"
    values = ["amzn-ami-hvm*"]
  }
}
```

### Crash Output

https://gist.github.com/brandonstrohmeyer/52c2063e58ad0472c2ad5148b218cdd8
### Expected Behavior

Gave error that remote data source was empty and couldn't add to list

### Actual Behavior

Terraform crashed

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
### Additional Context

When creating an ec2 instance as referenced above, "serverclass" is used in a remote data lookup in the ec2/main.tf module. The output of this data lookup is then added to a list, and passed to the resource in order to bind security groups to the newly created EC2 instance. 

While testing to see what happens if that field is left blank in the module "bastion2", in the environments/stage1/ec2.tf  configuration file, terraform crashed.

### PR DESCRIPTION
**Pull request by jbardin**
Nulls can't exist in HCL, and the legacy sdk will panic when
encountering them. The map shim already did this, just copy the same
pattern in the list case.

Fixes #20889

### CODE REVIEW

File: config/hcl2shim/values_test.go [hunk 1]
```diff
@@ -232,6 +232,26 @@ func TestConfigValueFromHCL2Block(t *testing.T) {
 			&configschema.Block{},
 			nil,
 		},
+		// nulls should be filtered out of the config, since they couldn't exist
+		// in hcl.
+		{
+			cty.ObjectVal(map[string]cty.Value{
+				"list": cty.ListVal([]cty.Value{
+					cty.StringVal("ok"),
+					cty.NullVal(cty.String)}),
```
Comment (apparentlymart) [inline config/hcl2shim/values_test.go]: What if the null is in the middle of a list? :thinking: 

I suppose just dropping nulls in the middle (as if they didn't exist at all) could be reasonable behavior, but it feels a little surprising.

It's a shame `ConfigValueFromHCL2` doesn't work in terms of a schema where we could prefer to instead insert a reasonable zero value that the SDK _would_ accept... but in the absense of that, I guess this is fine since as you say there was no such thing as a null before anyway and so this is only a concern for newly-written configurations.

Comment (jbardin) [reply config/hcl2shim/values_test.go]: The referenced issue was because of a variable that defaulted to `null`. But yes, this should only apply to HCL2 config where you're inserting a `null` in a list somehow.

Comment (apparentlymart) [reply config/hcl2shim/values_test.go]: I guess one worry here is that because this "drop nulls" is a legacy SDK behavior, switching to a newer SDK without these shims wouldn't do it, and so it would be implicitly a breaking change for anyone who was relying on this implicit removal.

Having said that then, I wonder if instead we should prefer to solve this by returning an error message to the user saying that null values are not allowed (I imagine we'd need to do that as a post-shim validation step since the shims themselves don't return errors) and then users won't come to depend on this behavior and be upset when it doesn't behave the same in other future SDKs.

Comment (jbardin) [reply config/hcl2shim/values_test.go]: Yeah, I only followed the existing code here, which did the same for maps since there was no error to return. I'm going to leave this since it prevents panics for other callers, but I'm making a PR to catch these separately during validation.

Comment (apparentlymart) [reply config/hcl2shim/values_test.go]: Ignoring nulls in _maps_ seems okay because it's consistent with our usual rule that `null` is equivalent to unset, but "unset" isn't a reasonable concept for list elements (leaving something out is the same as re-setting everything after it, because the indices must of course be contiguous), so I think an error is the better behavior here to avoid unfortunate surprises.
