### PR TITLE
Check for nested computed values in all structural types when planning data sources

### LINKED ISSUE #36653: Data resource producing `<null>` instead of `<unknown>` for deferred plan w/ map nested attribute
### Terraform Version

```shell
Terraform v1.11.1
```

### Terraform Configuration Files

```terraform
resource "terraform_data" "force_deferral" {
  input = "hello"
}

data "examplecloud_thing" "test" {
  nested_map = {
    "key1" : {
      required_attr = terraform_data.force_deferral.output
      # computed_attr
    }
  }
  nested_obj = {
    required_attr = terraform_data.force_deferral.output
    # computed_attr
  }
}

output "test" {
  value = data.examplecloud_thing.test
}
```

#### Plugin Framework schema for reference
```go
resp.Schema = schema.Schema{
    Attributes: map[string]schema.Attribute{
        "nested_map": schema.MapNestedAttribute{
            Optional: true,
            NestedObject: schema.NestedAttributeObject{
                Attributes: map[string]schema.Attribute{
                    "required_attr": schema.StringAttribute{
                        Required: true,
                    },
                    "computed_attr": schema.StringAttribute{
                        Computed: true,
                    },
                },
            },
        },
        "nested_obj": schema.SingleNestedAttribute{
            Optional: true,
            Attributes: map[string]schema.Attribute{
                "required_attr": schema.StringAttribute{
                    Required: true,
                },
                "computed_attr": schema.StringAttribute{
                    Computed: true,
                },
            },
        },
    },
}
```

### Debug Output

```bash
# ... most of the log is not useful, but the one showing that the provider isn't involved in the read
2025-03-07T08:52:53.536-0500 [TRACE] planDataSource: data.examplecloud_thing.test configuration not fully known yet, so deferring to apply phase
```

Full gist if you're interested: https://gist.github.com/austinvalle/09ce975db66669fc13751e3da91d5036

### Expected Behavior

```sh
Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + test = {
      + nested_map = {
          + key1 = {
              + computed_attr = (known after apply) # <-------
              + required_attr = (known after apply)
            }
        }
      + nested_obj = {
          + computed_attr = (known after apply)
          + required_attr = (known after apply)
        }
    }
```

### Actual Behavior

When a data source is deferred to the apply phase, Terraform core creates a plan via [`PlannedDataResourceObject`](https://github.com/hashicorp/terraform/blob/9ac4b3a62b7295ae2060e24c8d04f5f7d149bf8d/internal/plans/objchange/objchange.go#L64) on the providers behalf. For computed attributes that are nested under a nested map type, it looks like Terraform is planning the config value (`<null>`) value instead of the prior value (`<unknown>` for deferred data resources).

I compared this behavior with a single (object) nested type with a computed attribute, which looks to be planning an `<unknown>` properly.

-----------

It looks like the `objchange` logic for nested map types is only using the prior map value (which is all unknowns for deferred data resources) when the map is known, which results in the `configVal` being taken for the computed attribute (`<null>`), rather than `<unknown>`
https://github.com/hashicorp/terraform/blob/9ac4b3a62b7295ae2060e24c8d04f5f7d149bf8d/internal/plans/objchange/objchange.go#L242-L246

```sh
Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + test = {
      + nested_map = {
          + key1 = {
              + computed_attr = null   # I'd expect this to be unknown
              + required_attr = (known after apply)
            }
        }
      + nested_obj = {
          + computed_attr = (known after apply)
          + required_attr = (known after apply)
        }
    }
```

### Steps to Reproduce

The provider shown isn't published, but you can build it from source if you need (or I can help debug further, just ping me on HC slack 😆)
https://github.com/austinvalle/terraform-provider-sandbox/tree/main

1. `terraform plan` (no init since it's from source/reattached)

### Additional Context

_No response_

### References

- **Original plugin framework issue:** https://github.com/hashicorp/terraform-plugin-framework/issues/1102
- **Provider specific issue:** https://github.com/marshallford/terraform-provider-ansible/issues/79

### Generative AI / LLM assisted development?

_No response_

### PR DESCRIPTION
**Pull request by jbardin**
While the proposed plan value for managed resource is only a suggestion for providers, deferred data sources must be completely planed by core, and hence set appropriate unknown values. We do this by creating an entirely unknown prior value to plan against, which will be used to fill in any `null` `computed` attributes when generating the proposed new value. There were a couple combinations of nested types where we need to specifically check for and handle unknown in the prior value to translate that "unknown-ness" to what would be an unknown value extracted from an unknown container.

Fixes #36653

### CODE REVIEW

File: internal/plans/objchange/objchange_test.go [hunk 1]
```diff
@@ -954,7 +954,7 @@ func TestProposedNew(t *testing.T) {
 					}),
 					"c": cty.ObjectVal(map[string]cty.Value{
 						"bar": cty.StringVal("bosh"),
-						"baz": cty.NullVal(cty.List(cty.String)),
```
Comment (dsa0x) [inline internal/plans/objchange/objchange_test.go:957]: Was this change part of the bug fix, or just correcting something else?. I see in the code that this change is part of the config object. Do we no longer represent config objects as `cty.NullVal(cty.List(cty.String))`?

Comment (dsa0x) [reply internal/plans/objchange/objchange_test.go:957]: Thanks!

**Comment by marshallford** [comment]
This fix hasn't made its way into 1.11.3 or the latest 1.12 alpha. Will this be backported to 1.11? If not, is it possible to include the change in the next alpha build (perhaps it is, just not the changelog item)?

**Comment by jbardin** [comment]
@marshallford, this doesn't qualify for a 1.11 patch release, but it has been merged into `main`. The changelog however won't be collated yet in the alpha builds (not sure if it should though, I'll have to check on the new changelog workflow)

Thanks!

**Comment by marshallford** [comment]
FYI the change is missing from the v1.12.0-beta1 changelog. Is that to be expected?
