### PR TITLE
Fix bug for force push for backends besides the remote backend

### LINKED ISSUE #25761: Terraform remote state push -force fails lineage check for S3 backend
# Terraform Version
`v0.12.29`

# Expected Behavior
The state should be pushed to the remote and forced over any existing state

# Actual Behavior
```
$ tf state push -force B.tfstate
Failed to write state: cannot import state with lineage "c65f30fe-24db-19f7-43c8-bd29fb644be5" over unrelated state with lineage "bfeaceb5-75f6-5a22-5068-bc488243b268"
```

# Steps to reproduce
I am using an s3 backend
```
terraform {
  backend "s3" {
    bucket = "my-terraform-state"
    region = "us-east-1"
  }
}
```
```
terraform workspace new A || terraform workspace select A
terraform apply -auto-approve
terraform state pull > A.state

terraform workspace new B || terraform workspace select B
terraform apply -auto-approve
terraform state pull > B.state

terraform workspace select A
terraform state push -force B.state
```

# References
#5663
#15674
#24916

### PR DESCRIPTION
**Pull request by pselle**
In refactoring the `state push -force` code when implementing force push for the Terraform remote backend, a bug was introduced that meant that backends that don't implement the `EnableForcePush` method would still have their state validated, despite having `-force` set.

This commit fixes that, and adds test coverage such that there is a separate mockRemoteClient that has this method implemented. I had trouble thinking of a way to simplify the tests that doesn't make it needlessly complicated. The tests fail without the change in state.go.

Closes #25761

I nominate this change to go to v0.13 as well, as it is a bug fix for existing versions worthy of cherry-picking.

### CODE REVIEW

File: states/remote/remote_test.go [hunk 1]
```diff
@@ -126,3 +116,54 @@ func (c *mockClient) appendLog(method string, content []byte) {
...
+
+// mockRemoteClient is like mockClient, but also implements
+// EnableForcePush, allowing testing for this behavior
+type mockRemoteClient struct {
+	current []byte
+	force   bool
+	log     []mockClientRequest
+}
+
+func (c *mockRemoteClient) Get() (*Payload, error) {
```
Comment (pselle) [inline states/remote/remote_test.go:128]: Not all these methods are used in the tests, so are extraneous for mockRemoteClient, however I've included them for completeness if/when this client might be re-used for tests covering other differentiation with the remote backend.

File: states/remote/state_test.go [hunk 2]
```diff
@@ -302,6 +302,168 @@ func TestWriteStateForMigration(t *testing.T) {
 		},
 	}
 
+	testCases := []migrationTestCase{
```
Comment (pselle) [inline states/remote/state_test.go:305]: The diff implies this is the new section, however, it is the previous set of test cases with the EnableForcePush-specific code removed. The test `TestWriteStateForMigrationWithForcePushClient` is the new test.

File: states/remote/remote_test.go [hunk 3]
```diff
@@ -126,3 +116,54 @@ func (c *mockClient) appendLog(method string, content []byte) {
...
 	c.log = append(c.log, mockClientRequest{method, contentVal})
 }
+
+// mockRemoteClient is like mockClient, but also implements
+// EnableForcePush, allowing testing for this behavior
+type mockRemoteClient struct {
+	current []byte
+	force   bool
+	log     []mockClientRequest
+}
```
Comment (alisdair) [inline states/remote/remote_test.go:126]: I was a bit confused by the name of this type, thinking "why isn't the `mockClient` also remote?" But is it "remote" as in "enhanced remote backend"?

Would naming the type something like `mockForceableClient` make sense to you? If my understanding of what's happening here is correct I think that would've been less confusing to me.

File: states/remote/state_test.go [hunk 4]
```diff
@@ -387,7 +539,7 @@ func TestWriteStateForMigration(t *testing.T) {
 
 	// Our client is a mockClient which has a log we
```
Comment (alisdair) [inline states/remote/state_test.go:540]: Should this be updated to `mockRemoteClient`?

**Review by alisdair — APPROVED** [review]
👏 Good catch in the force logic, that was subtle! Thanks for making the test changes easy to follow.

File: states/remote/remote_test.go (hunk 3 above)
Comment (pselle) [reply states/remote/remote_test.go:126]: OO yes I like that. I'll adopt that suggestion. I meant remote as in "like the remote backend" and agree that it's a bit too confusing as-is

File: states/remote/remote_test.go (hunk 1 above)
Comment (mildwonkey) [reply states/remote/remote_test.go:128]: Since these are both (nominally) mock remote clients, what do you think about naming your new one something like `mockRemoteClientForcePusher` or `mockClientForcePusher` (`ClientForcePusher` being the interface it implements)? 

I genuinely don't know if this would make it more or less confusing, so absolutely feel free to disregard this.

File: states/remote/remote_test.go (hunk 3 above)
Comment (pselle) [reply states/remote/remote_test.go:126]: Adopted @mildwonkey's suggestion :)
