### PR TITLE
init always prompts for migration with most remote backend configurations

### LINKED ISSUE #21189: `init -reconfigure` required after upgrading to 0.12 with remote backend
After upgrading my (0.11.13) configuration using 0.12upgrade, `terraform` reported an error with a message that I needed to run `init` again. `init` then errored out with a message that `init -reconfigure` was required. 
This could be a more precise message - it would have been nice to know from the start why `init` was required (and it is notable that this step was not required with the local backend, including one using remote state), and also that `init -reconfigure` was required.
Failing that, we should make a note in the upgrade guide.

```
$ terraform version
Terraform v0.12.0-beta2
+ provider.random v2.1.2
```

configuration:
```hcl
terraform {
  backend "remote" { [redacted] }
}

resource "random_pet" "my_pets" {
  count = 2
}
```

Output after running 0.12upgrade (which made no changes to the configuration above):

```
$ terraform plan
Backend reinitialization required. Please run "terraform init".
Reason: Backend configuration changed for "remote"

The "backend" is the interface that Terraform uses to store state,
perform operations, etc. If this message is showing up, it means that the
Terraform configuration you're using is using a custom configuration for
the Terraform backend.

Changes to backend configurations require reinitialization. This allows
Terraform to setup the new configuration, copy existing state, etc. This is
only done during "terraform init". Please run that command now then try again.

If the change reason above is incorrect, please verify your configuration
hasn't changed and try again. At this point, no changes to your existing
configuration or state have been made.


Error: Initialization required. Please see the error message above.

$ terraform init

Initializing the backend...
Backend configuration changed!

Terraform has detected that the configuration specified for the backend
has changed. Terraform will now check for existing state in the backends.



Error: Failed to decode current backend config

The backend configuration created by the most recent run of "terraform init"
could not be decoded: missing expected {. The configuration may have been
initialized by an earlier version that used an incompatible configuration
structure. Run "terraform init -reconfigure" to force re-initialization of the
backend.

```

### PR DESCRIPTION
**Pull request by jbardin**
This was the same outcome, caused by 2 different issues.
The first was that `init` is supposed to be idempotent, and calling init with no `-backend-config` flags should accept the stored config if the hash matches.
Second was that when the config did need to be compared, the saved result had already been pre-processed by `PrepareConfig` and was no longer identical to the given config.

Fixes #21189

### CODE REVIEW

File: command/init_test.go [hunk 1]
```diff
@@ -410,6 +411,97 @@ func TestInit_backendConfigKV(t *testing.T) {
...
+	ui = new(cli.MockUi)
+	c = &InitCommand{
+		Meta: Meta{
+			testingOverrides: metaOverridesForProvider(testProvider()),
+			Ui:               ui,
+		},
+	}
+
+	// a second init should require no changes, nor should it change the backend.
+	args = []string{"-input=false"}
```
Comment (apparentlymart) [inline command/init_test.go]: This makes sense, but it makes me wonder then what is the correct way to express "Discard all previously-set `-backend-config` settings"?

Could that be done by setting `-backend-config` to a path to a file containing nothing at all? Or setting `-backend-config` explicitly to the empty string? [Our instructions on the website](https://www.terraform.io/docs/commands/init.html#backend-initialization) don't discuss how you're supposed to express that.

Comment (jbardin) [reply command/init_test.go]: That's a good question! We've never ever really had a way to do that.
I think `-reconfigure` should be able to take care of that (though it doesn't currently), meaning that `-reconfigure` with no `-backend-config` will use _only_ the config file.
