### PR TITLE
configgen: escape any invalid HCL syntax in map keys

### LINKED ISSUE #35752: terraform plan -generate-config-out fails for map nested objects with keys with spaces
### Terraform Version

```shell
Terraform v1.9.5
on darwin_amd64
```

### Terraform Configuration Files

```terraform
provider "example" {
}

import {
  to = example_example.myExample
  id = "str"
}
```

### Debug Output

https://gist.github.com/henryrecker-pingidentity/ae09eb59b71a2d0c02526018760dd254

### Expected Behavior

HCL should be generated with the expected values

### Actual Behavior

Error, no HCL is generated: 
```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Missing key/value separator
│
│   on generated_resources.tf line 2:
│   (source code not available)
│
│ Expected an equals sign ("=") to mark the beginning of the attribute value. If you intended to given an
│ attribute name containing periods or spaces, write the name in quotes to create a string literal.
╵
```

### Steps to Reproduce

`terraform plan -generate-config-out=generated_resources.tf` with a provider schema that has a MapNestedAttribute with a key that includes spaces.

A simple provider that reproduces this issue can be found here: https://github.com/henryrecker-pingidentity/terraform-provider-example/tree/GenerateConfigBug

Relevant provider code, note the "Use Case" name with the space.
```
func (r *exampleResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Example resource.",
		Attributes: map[string]schema.Attribute{
			"string_val": schema.StringAttribute{
				Description: "Optional string attribute",
				Optional:    true,
			},
			"map_val": schema.MapNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"values": schema.SetAttribute{
							ElementType: types.StringType,
							Optional:    true,
							Description: "A Set of values",
						},
					},
				},
				Optional:    true,
				Description: "Extended Properties allows to store additional information for IdP/SP Connections. The names of these extended properties should be defined in /extendedProperties.",
			},
		},
	}
}

// Metadata returns the resource type name.
func (r *exampleResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_example"
}

func (r *exampleResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	plan := exampleResourceModel{
		StringVal: types.StringValue("str"),
		MapVal: types.MapValueMust(types.ObjectType{
			AttrTypes: map[string]attr.Type{
				"values": types.SetType{
					ElemType: types.StringType,
				},
			}}, map[string]attr.Value{
			"Use Case": types.ObjectValueMust(map[string]attr.Type{
				"values": types.SetType{
					ElemType: types.StringType,
				},
			}, map[string]attr.Value{
				"values": types.SetValueMust(types.StringType, []attr.Value{
					types.StringValue("CIAM"),
				}),
			}),
		}),
	}
	diags := resp.State.Set(ctx, plan)
	resp.Diagnostics.Append(diags...)
}

func (r *exampleResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	plan := exampleResourceModel{
		StringVal: types.StringValue("str"),
		MapVal: types.MapValueMust(types.ObjectType{
			AttrTypes: map[string]attr.Type{
				"values": types.SetType{
					ElemType: types.StringType,
				},
			}}, map[string]attr.Value{
			"Use Case": types.ObjectValueMust(map[string]attr.Type{
				"values": types.SetType{
					ElemType: types.StringType,
				},
			}, map[string]attr.Value{
				"values": types.SetValueMust(types.StringType, []attr.Value{
					types.StringValue("CIAM"),
				}),
			}),
		}),
	}
	diags := resp.State.Set(ctx, plan)
	resp.Diagnostics.Append(diags...)
}

// Update updates the resource and sets the updated Terraform state on success.
func (r *exampleResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	plan := exampleResourceModel{
		StringVal: types.StringValue("str"),
		MapVal: types.MapValueMust(types.ObjectType{
			AttrTypes: map[string]attr.Type{
				"values": types.SetType{
					ElemType: types.StringType,
				},
			}}, map[string]attr.Value{
			"Use Case": types.ObjectValueMust(map[string]attr.Type{
				"values": types.SetType{
					ElemType: types.StringType,
				},
			}, map[string]attr.Value{
				"values": types.SetValueMust(types.StringType, []attr.Value{
					types.StringValue("CIAM"),
				}),
			}),
		}),
	}
	diags := resp.State.Set(ctx, plan)
	resp.Diagnostics.Append(diags...)
}

// No backend so no logic needed
func (r *exampleResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
}

func (r *exampleResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("string_val"), req, resp)
}
```

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by liamcervante**
This PR updates the config generation so that any invalid HCL syntax in generated map keys is escaped and not just whitespace.

Fixes #35752 

## Target Release

1.9.x

### BUG FIXES

 

-  config generation: Escape all invalid syntax in generate map keys with quotes.

### CODE REVIEW

File: internal/genconfig/generate_config.go [hunk 1]
```diff
@@ -592,7 +593,7 @@ func ctyCollectionValues(val cty.Value) []cty.Value {
 func hclEscapeString(str string) string {
 	// TODO: Replace this with more complete HCL logic instead of the simple
```
Comment (DanielMSchmidt) [inline internal/genconfig/generate_config.go:594]: Isn't this done now?

**Review by DanielMSchmidt — APPROVED** [review]

File: internal/genconfig/generate_config.go (hunk 1 above)
Comment (liamcervante) [reply internal/genconfig/generate_config.go:594]: see Martin's comment here for a more thorough explanation of what I'd consider to be done: https://github.com/hashicorp/terraform/pull/35754#issuecomment-2372449103

Basically, it's not the detection that this TODO is talking about but the escaping itself - it's not always enough to just wrap it in quotes.

Comment (DanielMSchmidt) [reply internal/genconfig/generate_config.go:594]: Ah ok 👍
