### PR TITLE
Make sure a failed destroy is marked as tainted

### LINKED ISSUE #22011: Failure to destroy tainted resources will untaint them
If a resource is tainted, and a `terraform apply` is run and attempts to destroy the tainted resource but fails, the resource will continue to exist but will no longer be marked as tainted. I really hope this is a bug and not intended behavior, because it allows infrastructure to be put into a broken state, with Terraform believing it has correctly provisioned resources, despite never successfully doing so.

I have three minimal examples that demonstrate this behavior. Two use the AWS provider, and one uses the MySQL provider. Because two different providers are affected, and it concerns the tainted flag itself, I believe it is likely an issue in core functionality.

Here is my `terraform -version` output:
```
> terraform version                   
Terraform v0.12.2
+ provider.aws v2.18.0

> terraform version                   
Terraform v0.12.2
+ provider.mysql v1.6.0
```

### Example 1

This example shows how the issue can be used to create an AWS EC2 Autoscaling group, have it fail to start successfully, but after repeated applies have Terraform store it in the state fail as untainted, just like after a successful start of the autoscaling group, despite it being broken. Here is the terraform config:

```
provider "aws" {
  profile = "default"
  region  = "us-east-1"
}

resource "aws_launch_template" "x" {
  name_prefix   = "bug_terraform_test"
  image_id      = "ami-0c6b1d09930fac512"
  instance_type = "t3.small"
}

data "aws_vpc" "default" {
  default = true
}

data "aws_subnet_ids" "x" {
  vpc_id = data.aws_vpc.default.id
}

resource "aws_autoscaling_group" "without_create_before_destroy" {
  name_prefix = "bug_terraform_test"
  max_size    = 1
  min_size    = 1

  vpc_zone_identifier = data.aws_subnet_ids.x.ids

  wait_for_capacity_timeout = "1m"
  timeouts {
    delete = "1m"
  }

  launch_template {
    id = aws_launch_template.x.id
    version = aws_launch_template.x.latest_version
  }

  initial_lifecycle_hook {
    name                 = "startup"
    default_result       = "ABANDON"
    heartbeat_timeout    = 10 * 60 # 10 minutes
    lifecycle_transition = "autoscaling:EC2_INSTANCE_LAUNCHING"
  }
}
```

This creates an autoscaling group with a lifecycle hook that will never be satisfied, and so no instances will ever reach the ready state.

1. The first time you run `terraform apply` with this file, it will create the autoscaling group, the autoscaling group will fail to reach required capacity before the ` wait_for_capacity_timeout`, and terraform will mark it as tainted.
2. The second time you run `terraform apply`, Terraform will plan to destroy the tainted autoscaling group and create a new one. Unfortunately, the broken lifecycle hook also prevents destruction, so it will fail.
3. The third time you run `terraform apply` exposes the bug. The behavior I expected was a repeat of the second run, where it will attempt to destroy the tainted autoscaling group and recreated it. However, when the second run failed it marked the tainted autoscaling group as untainted. As a result, the third `terraform apply` completes without changing any resources.

We've put Terraform in a state where it believes it has successfully applied the template, but the autoscaling group it created never passed the initial check for capacity.

### Example 2

This demonstrates the issue again, but using AWS security groups. First, apply this config:

```
provider "aws" {
  profile = "default"
  region  = "us-east-1"
}

resource "aws_security_group" "x" {
  name        = "bug_terraform_test"
  description = "For testing terraform bug"

  timeouts {
    delete = "1m"
  }
}
```

Then, in another directory, apply this config:

```
provider "aws" {
  profile = "default"
  region  = "us-east-1"
}

data "aws_security_group" "group1" {
  name = "bug_terraform_test"
}

resource "aws_security_group" "x" {
  name        = "bug_terraform_test_2"
  description = "For testing terraform bug"

  ingress {
    from_port   = 10
    to_port     = 10
    protocol    = "tcp"

    security_groups = [data.aws_security_group.group1.id]
  }
}
```

Then return to the first directory. Run `terraform taint aws_security_group.x` to taint the security group, then `terraform apply`. Because the second config created a dependency on the original security group, it cannot be deleted, so `terraform` will fail. Then run `terraform apply` again. Expected behavior would be that the security group would still be tainted and terraform would reattempt to recreate it. However, the tainted flag has been lost, and so `terraform` completes without making any changes.

### Example 3

This demonstrates the issue using the MySQL provider. You will need a MySQL DB setup and the root user password. Edit the root password into this config and apply:

```
provider "mysql" {
  endpoint = "localhost"
  username = "root"
  password = "ROOT_PASSWORD_HERE"
}

resource "mysql_user" "broken_admin" {
  user               = "broken_admin"
  plaintext_password = "password"
}

resource "mysql_grant" "x" {
  user       = "broken_admin"
  database   = "mysql"
  privileges = ["SELECT"]
}

resource "mysql_user" "x" {
  user               = "bug_test"
  plaintext_password = "password"
}
```

Then, edit the provider block:
```
provider "mysql" {
  endpoint = "localhost"
  username = "broken_admin"
  password = "password"
}
```

We can now run `terraform apply` again to confirm that our broken_admin user has access and no changes are needed. Now do `terraform taint mysql_user.x` followed by `terraform apply`. Terraform will attempt to destroy and recreate the bug_test user, but the broken_admin doesn't have the right permissions so it will fail. Then do `terraform apply` again. Expected behavior is that it will once again attempt to destroy and recreate the bug_test user. However, the tainted flag is no longer set, so it completes without making any changes.

Apologies if this is a duplicate or expected behavior.

### PR DESCRIPTION
**Pull request by jbardin**
If there are errors while deleting an instance, mark the instance as
tainted. This ensures the instance remains queued for deletion, as it
may have been tainted in the first place.

Fixes #22011

### CODE REVIEW

**Comment by apparentlymart** [comment]
:thinking: I remember when we were in the 0.12 prerelease phase we found we'd inadvertently made a failed destroy lead to a taint and that caused problems for folks because sometimes providers require applying a change first before destroy can work, such as setting the name of a backup object or a flag to enable a particular kind of destroy, but forcing the thing to be tainted caused them to get stuck in a situation where Terraform would just keep trying to destroy the thing, unless they figure out how to `terraform untaint ...` the object in order to apply the change.

I think in order to avoid recreating that situation we'd need to do something a little more subtle here: can we instead arrange for Terraform to _leave_ the object tainted if it already was but not to taint it if it wasn't already?

**Comment by jbardin** [comment]
Thanks, I hadn't seen that "workflow" before, but we don't want to break a provider that expects that right now. We will have to wait for the ability to have providers communicate some level of status to refine this further. 

I switched this to restore just `ObjectTainted` on errors.

File: terraform/context_apply_test.go [hunk 1]
```diff
@@ -10862,3 +10862,138 @@ func TestContext2Apply_destroyDataCycle(t *testing.T) {
...
+
+	_, diags := ctx.Plan()
+	diags.HasErrors()
+	if diags.HasErrors() {
+		t.Fatalf("diags: %s", diags.Err())
+	}
+
+	state, diags = ctx.Apply()
+	if !diags.HasErrors() {
+		t.Fatal("expecetd error")
```
Comment (apparentlymart) [inline terraform/context_apply_test.go]:
```suggestion
		t.Fatal("expected error")
```

File: terraform/context_apply_test.go [hunk 2]
```diff
@@ -10862,3 +10862,138 @@ func TestContext2Apply_destroyDataCycle(t *testing.T) {
...
+		Mode: addrs.ManagedResourceMode,
+		Type: "test_instance",
+		Name: "a",
+	}.Instance(addrs.NoKey))
+
+	if a.Current.Status != states.ObjectTainted {
+		t.Fatal("test_instance.a should be tainted")
+	}
+
+	// b should be ready with one deposed instance
```
Comment (apparentlymart) [inline terraform/context_apply_test.go]: It took me a few reads through here to understand _why_ there should be a deposed instance for b. I think it'd be helpful to be explicit in this comment that we're expecting a deposed instance because b is create_before_destroy and we arranged for the create to succeed but the subsequent destroy to fail. That _is_ redundant once you absorb the details of the mock config and the mock above, but I found it hard to piece these different contributing parts together without a clear prompt here.

File: terraform/eval_apply.go [hunk 3]
```diff
@@ -378,40 +386,39 @@ type EvalMaybeTainted struct {
...
 func (n *EvalMaybeTainted) Eval(ctx EvalContext) (interface{}, error) {
+	if n.State == nil || n.Change == nil || n.Error == nil {
+		return nil, nil
+	}
+
 	state := *n.State
 	change := *n.Change
 	err := *n.Error
 
+	// nothing to do if everythig went as planned
```
Comment (apparentlymart) [inline terraform/eval_apply.go]:
```suggestion
	// nothing to do if everything went as planned
```
