### PR TITLE
Evaluate data sources in plan when necessary

### LINKED ISSUE #11806: `depends_on` always triggers data source read
Hi there,

### Terraform Version
Terraform v0.8.4

### Affected Resource(s)
- data.template_file

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
data "template_file" "hello" {
    template = "template"
    depends_on = ["null_resource.hello"]
}

resource "null_resource" "hello" {}
```

### Debug Output
https://gist.github.com/queeno/f198c93760f7c60e5102e7fd5873ad1f

### Expected Behavior
`terraform plan` shouldn't re-read the data source.

### Actual Behavior
`terraform plan` re-reads the data source.

```
❯ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.

null_resource.hello: Refreshing state... (ID: 3983604783330107355)

The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed. Cyan entries are data sources to be read.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

<= data.template_file.hello
    rendered: "<computed>"
    template: "template"


Plan: 0 to add, 0 to change, 0 to destroy.
```

### Steps to Reproduce
`terraform plan`

### Important Factoids
When using `depends_on` in `template_file`, `terraform plan` always seems to re-read the data source. If the data source is used by an instance's `user-data`, terraform plans to change the instance's user-data. `terraform apply`, however, doesn't produce any change.

If `depends_on` is not used, then the data source is not re-read.

### LINKED ISSUE #17173: Data source external with dependencies is being evaluated early
### Terraform Version
```
Terraform v0.11.2
+ provider.external v1.0.0
+ provider.null v1.0.0
```

### Terraform Configuration Files
These are defined inside a module called `consul`.
```hcl
module "A" {
  source       = "./region"
  region       = "RegionA"
  environment  = "${var.environment}"
  project-name = "${var.project-name}"
  number-of-servers = "${var.number-of-servers}"
}

module "T" {
  source       = "./region"
  region       = "RegionT"
  environment  = "${var.environment}"
  project-name = "${var.project-name}"
  number-of-servers = "${var.number-of-servers}"
}

locals {
  both-regions-server-ips   = "${concat(module.A.server-ips, module.T.server-ips)}"
  both-regions-server-fqdns = "${concat(module.A.server-fqdns, module.T.server-fqdns)}"
}

resource "null_resource" "provision-both-clusters" {
  count = "${var.number-of-servers * 2}" # * 2 Because we have RegionA and RegionT

  connection {
    host = "${element(local.both-regions-server-ips, count.index)}"

    user        = "${var.ssh-username}"
    private_key = "${file(".${local.keypair}.pem")}"
  }

  provisioner "chef" {
    # Omitted for clarity
  }
}

data "external" "vault-tokens" {
  depends_on = ["null_resource.provision-both-clusters"]
  
  program = ["${path.module}/create-vault-tokens.sh"]

  query = {
    consulAddress = "https://${element(module.tagus.server-ips, 0)}:8500"
    masterToken   = "${var.master-token}"
  }
}

output "vault-backend-token" {
  value     = "${data.external.vault-tokens.result.backend-token}"
  sensitive = true
}

output "vault-consul-auth-backend-token" {
  value     = "${data.external.vault-tokens.result.consul-auth-backend-token}"
  sensitive = true
}
```
### Expected Behavior
The output variables values should only be computed after `provision-both-clusters` in ran.

### Actual Behavior
```
Error: Error running plan: 2 error(s) occurred:

* module.consul.output.vault-consul-auth-backend-token: Resource 'data.external.vault-tokens' does not have attribute 'result.consul-auth-backend-token' for variable 'data.external.vault-tokens.result.consul-auth-backend-token'
* module.consul.output.vault-backend-token: Resource 'data.external.vault-tokens' does not have attribute 'result.backend-token' for variable 'data.external.vault-tokens.result.backend-token'
```

The same behavior happens even if I define `vault-tokens` to be:

```hcl
data "external" "vault-tokens" {
  program = ["${path.module}/create-vault-tokens.sh"]

  query = {
    consulAddress = "https://${element(module.tagus.server-ips, 0)}:8500"
    masterToken   = "${var.master-token}"
    dummy = "${null_resource.provision-both-clusters.count}"
  }
}
```

Like described in #10603

If I remove the output variables Terraform resolves the graph correctly and only runs the `vault-tokens` after the null_resource.

If I set a `depends_on = ["null_resource.provision-both-clusters"]` on both output variables I still get the error.

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

### PR DESCRIPTION
**Pull request by jbardin**
In order to support `depends_on` in for modules, it first needs to be supported on data sources that may be contained within modules. In order to do that, we need to be able to evaluate data sources during plan. 

This does not provide a way to fully plan data source changes, as they may still only be read during refresh when possible. While this is a step towards implementing #17034, it does not yet fully merge the refresh and plan walks. The new handling of `depends_on` here will still be relevant for that change, and the refactoring of the eval nodes will make the code easier to update. 

We start by removing the existing `depends_on` half-measures, and make it so that data sources can detect if they really have a `depends_on` dependency that effects their update.  `GraphNodeAttachDependsOn` give us a method for adding all transitive resource dependencies found through `depends_on` references, so that data sources can determine if they can be read during plan. This will be done by inspecting the changes of all dependency resources, and delaying read until apply if any changes are planned.

The next step is to evaluate data sources during plan. The existing logic in the `EvalReadData` monolith wasn't maintainable, so that gets broken up into separate eval nodes for each phase, since the desired logic is subtly different in each case. 

What we end up with is the following logic for data sources:

#### Refresh
 - If the config is not wholly known, or there are any `depends_on` references _and_ the data source has never been read, it is defered to planning. The state status is set to `ObjectPlanned`, and it is removed from the state forcing a refresh during plan or apply.
 - Otherwise if the config is known, the data source is refreshed as usual and saved to state.
#### Plan
 - If the config is not wholly known, or there are changes in any transitive `depends_on` resources, we generate a change with `plans.Read`, and defer reading until apply. The proposed change, which will contain unknown values, is stored in `change.After`.
 - If the state value is nil (which may indicate it being deferred from refresh), or the config causes a change in the prior value, we read the data source and plan the change. The change is stored as a `plans.Read` to indicate that it only needs to be updated in state during apply.
#### Apply
 - Apply the stated `plans.Read` change for the data source. If the planned `After` value is not wholly-known, the config is re-evaluated and the data source is read into state. If the `After` value is wholly-known, it indicates the data source was read during plan, and the value is saved directly to state without reading the data source again.

Fixes #11806
Fixes #17173

### CODE REVIEW

File: terraform/eval_read_data_apply.go [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+
+	if err := ctx.Hook(func(h Hook) (HookAction, error) {
+		return h.PreApply(absAddr, states.CurrentGen, planned.Action, planned.Before, planned.After)
+	}); err != nil {
+		return nil, err
+	}
+
+	// we have a change and it is complete, which means we read the data
+	// source during plan and only need to store it in state.
+	if planned.Action == plans.Update {
```
Comment (apparentlymart) [inline terraform/eval_read_data_apply.go:49]: Overloading the meaning of `Update` here makes me nervous. :confused: I can't identify a specific reason why right now, but this meaning of "update" seems different enough to at least cause some confusion in future maintenance.

Part of me wants to suggest adding a new verb here like "Commit" to represent just writing something to the state without any other side-effect, but at the same time that's also a pretty big change in our data model that I wouldn't want to rush into without some more design thought first. :confounded: 

Given that we're planning to merge plan and refresh into a single step later anyway, and at that point we should no longer need to distinguish these two cases (because the updated data will be in the "prior state" already), is there room for a temporary slightly-more-tricky solution here, such as checking whether the "before" object in the plan contains unknown values? I'm not pretending that this is any easier to understand than overloading `Update`, but I'm hoping it'd be a more _localized_ temporary hack that would be easier to mark with cautionary comments in one spot and easier to find and remove later when we are ready to do the full refresh/plan merger.... :thinking: 

(By "localized" here I mean that it would hopefully be less visible to other subsystems like our plan renderer, JSON plan output, etc, and just confined to the logic in this package. :crossed_fingers: I'm particularly worried about it being visible in the JSON plan output, because Sentinel policies can then create an additional compatibility constraint for us to clean it up later.)

File: terraform/node_resource_destroy.go [hunk 2]
```diff
@@ -237,19 +237,14 @@ func (n *NodeDestroyResourceInstance) EvalTree() EvalNode {
 				// Make sure we handle data sources properly.
 				&EvalIf{
 					If: func(ctx EvalContext) (bool, error) {
-						return addr.Resource.Resource.Mode == addrs.DataResourceMode, nil
+						if addr.Resource.Resource.Mode == addrs.DataResourceMode {
+							// deleting a data source is simply removing the state
+							state = nil
```
Comment (apparentlymart) [inline terraform/node_resource_destroy.go:242]: :confused: having the `If` arm of this `EvalIf` contain a side-effect makes me a little nervous, because I've seen logic before that tries to pre-evaluate and "optimize" `EvalSequence` by resolving some of the higher-order `EvalNode` implementations early. Are you sure this is safe?

(Out of caution I'd kinda rather just have a silly `evalSetStateToNil` to put in the `Else` just to avoid introducing a new pattern into the mix here; I'm not _super_ set on it because we're hoping to phase out the `EvalNode` concept in future anyway, but I think keeping things consistent will make that later work easier to think about and plan.)

File: terraform/transform_reference.go [hunk 3]
```diff
@@ -45,6 +43,22 @@ type GraphNodeAttachDependencies interface {
...
+// to be further delayed until apply.
+// We can only use an addrs.ConfigResource address here, because modules are
+// not yet expended in the graph. While this will cause some extra data
+// resources to show in the plan when their depends_on references may be in
+// unrelated module instances, the fact that it only happens when there are any
+// resource updates pending means we can still avoid the problem of the
+// "perpetual diff"
+type GraphNodeAttachDependsOn interface {
+	GraphNodeConfigResource
+	AttachDependsOn([]addrs.ConfigResource)
```
Comment (apparentlymart) [inline terraform/transform_reference.go:58]: Given that "depends on" already has a meaning in our language, might we name this something like `AttachResourceDependencies` instead, to make it a bit clearer that it's getting something _derived from_ `depends_on` rather than getting `depends_on` itself?

File: terraform/transform_reference.go [hunk 4]
```diff
@@ -106,18 +120,81 @@ func (t *ReferenceTransformer) Transform(g *Graph) error {
...
+	for _, v := range vertices {
+		depender, ok := v.(GraphNodeAttachDependsOn)
+		if !ok {
+			continue
+		}
+		selfAddr := depender.ResourceAddr()
+
+		// Only data need to attach depends_on, so they can determine if they
+		// are eligible to be read during plan.
+		if selfAddr.Resource.Mode != addrs.DataResourceMode {
```
Comment (apparentlymart) [inline terraform/transform_reference.go:162]: Would it _hurt_ to just do this unconditionally for every implementer of `GraphNodeAttachDependsOn`? It feels a little confusing to me that this is named as if it's a generic mechanism but then has this suprising restriction hidden in it, and my intuition from reading the rest of this PR is that other resource modes would just accept it and ignore it. :thinking:

File: plans/changes.go [hunk 5]
```diff
@@ -52,6 +52,22 @@ func (c *Changes) ResourceInstance(addr addrs.AbsResourceInstance) *ResourceInst
 	}
 
 	return nil
+
+}
+
+// ConfigResourceInstances returns the planned change for the current objects
+// of the resource instances of the given address, if any. Returns nil if no
+// changes are planned.
+func (c *Changes) ConfigResourceInstances(addr addrs.ConfigResource) []*ResourceInstanceChangeSrc {
```
[the remark this answers is not in the document]
Comment (jbardin) [reply plans/changes.go:61]: This was only to sort of follow the other names, but anything to make is more clear for other readers is fine with me.

File: terraform/context_plan_test.go [hunk 6]
```diff
@@ -4992,8 +4993,10 @@ func TestContext2Plan_createBeforeDestroy_depends_datasource(t *testing.T) {
 		}
 	}
 	p.ReadDataSourceFn = func(req providers.ReadDataSourceRequest) providers.ReadDataSourceResponse {
+		cfg := req.Config.AsValueMap()
```
[the remark this answers is not in the document]
Comment (jbardin) [reply terraform/context_plan_test.go:4996]: Yes, we will need to call this out. I'm sure we'll find someone why relies on using stale data sources, but since we want to eventually move this completely into planning, it's something we need to deal with.

File: terraform/eval_read_data.go [hunk 7]
```diff
@@ -34,208 +33,83 @@ type EvalReadData struct {
...
 	if validateResp.Diagnostics.HasErrors() {
-		return nil, validateResp.Diagnostics.InConfigBody(n.Config.Config).Err()
+		return newVal, validateResp.Diagnostics.InConfigBody(config.Config)
 	}
 
 	// If we get down here then our configuration is complete and we're read
 	// to actually call the provider to read the data.
 	log.Printf("[TRACE] EvalReadData: %s configuration is complete, so reading from provider", absAddr)
 
-	err := ctx.Hook(func(h Hook) (HookAction, error) {
```
[the remark this answers is not in the document]
Comment (jbardin) [reply terraform/eval_read_data.go:220]: I'll double check that, since the code was split into 3 different types.

File: terraform/eval_read_data.go [hunk 8]
```diff
@@ -285,152 +160,126 @@ func (n *EvalReadData) Eval(ctx EvalContext) (interface{}, error) {
...
-	Provider       *providers.Interface
-	ProviderAddr   addrs.AbsProviderConfig
-	ProviderMeta   *configs.ProviderMeta
-	ProviderSchema **ProviderSchema
-	Output         **states.ResourceInstanceObject
-	Config         *configs.Resource
-	Change         **plans.ResourceInstanceChange
+// EvalReadDataRefresh is an EvalNode implementation that handled the data
+// resource lifecycle during refresh
+type EvalReadDataRefresh struct {
```
[the remark this answers is not in the document]
Comment (jbardin) [reply terraform/eval_read_data.go:191]: Also sounds good to me, not sure why I didn't do that to these, since I have been de-exporting other new types

File: terraform/eval_read_data_apply.go (hunk 1 above)
Comment (jbardin) [reply terraform/eval_read_data_apply.go:49]: I went around and around on this a bit, and for some reason the idea that "updating" a data source meant updating its state is what fell out as the simplest use case. I did leave that open for changing however; but if you think about a data source as a resource which only has a plan, the apply step simply becomes saving the planned value.

I'm also leaning towards keeping the concepts of data resources and manages resources as closely aligned as possible (i.e. `ReadDataSource` is just a special form of `PlanResourceChange` that returns all values). This is another reason I like this idea of data source diffs showing up as planned changes. Having data sources be silently read only sometimes, and have planned changes at other times, definitely leads to some of the confusion around their behavior. 

Sentinel making use of this without our intention to support it is a good point though, so I think we just need to decide if this is a good method to stick with. If the goal is to eventually have data source changes show up in the plan (which there is a lot of demand for, though it could be done in other ways), and `Update` is an acceptable verb for the situation, I think this is a good step forward. If we're unsure about the final use case, we should change the verb to something new, and hide the change from the json output for now.

File: terraform/node_resource_destroy.go (hunk 2 above)
Comment (jbardin) [reply terraform/node_resource_destroy.go:242]: Yeah, I can change this back. It should be safe, but there's no reason to not just use `EvalWriteState` for consistency.

File: terraform/transform_reference.go (hunk 3 above)
Comment (jbardin) [reply terraform/transform_reference.go:58]: We already have something like that for _actual_ dependencies though, which is why I ended up on this sort of awkward name. I do want this to be clear that it is derived from `depends_on` in some way, and not the result of normal dependencies with visible changes, but am open to a better name.

File: terraform/transform_reference.go (hunk 4 above)
Comment (jbardin) [reply terraform/transform_reference.go:162]: No, it wouldn't hurt. I did try to document in each location that these mechanisms only apply to data source, so I didn't want to attach them to managed resources and have something start using them from another code path (an occurrence which is unfortunately all too common)

File: terraform/eval_read_data_apply.go (hunk 1 above)
Comment (jbardin) [reply terraform/eval_read_data_apply.go]: The refactoring here actually left the data source plan handling in the perfect place to handle this transparently. The `change.After` value can now be used directly to determine whether apply needs to read the data source or not. 

This alleviates us from designing any new plan features for data sources at the moment.

File: terraform/transform_reference.go (hunk 3 above)
Comment (apparentlymart) [reply terraform/transform_reference.go:58]: Since this is specifically about _resource dependencies_ rather than arbitrary dependencies, I'd suggest `AttachResourceDependencies` as a subtle (admittedly) way to differentiate this.

File: terraform/transform_reference.go (hunk 4 above)
Comment (apparentlymart) [reply terraform/transform_reference.go:162]: Fair enough! Perhaps we could ram that point home in a crude way by naming the interface `GraphNodeDataResourceAttachDependencies`, leaving no doubt at all that someone should think twice before using it for something other than a data resource, even if they don't read the comments.

(For similar reasons, I might also call this transformer `AttachDataResourceDependenciesTransformer`, so it's easy to see scanning the graph builder instantiation that this is something specifically for data resources.)

File: terraform/context_plan_test.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (apparentlymart) [reply terraform/context_plan_test.go:4996]: Having had some time away to reflect on this a bit more, I'm feeling like this half-way position where we read data resources during refresh _and_ during plan is likely to be confusing, because it will still be subject to the usual quirks/bugs where data sources get resolved against the "wrong" values (the ones in the prior state, rather than the ones in the config) but it will also no longer be disableable with `-refresh=false` and so the user model here is kinda odd.

I realize I'm taking a different posture here than my initial reaction to this changeset, but out of curiosity: do you have a sense of the size of the delta from this PR to having data sources not update during refresh at all? I was previously feeling nervous about squeezing that in so late before 0.13, but the effect of _this_ change feels potentially heavy too and so now I'm wondering if we shouldn't just go all-in on the new behavior and get some more benefit to justify the risk. What do you think? :thinking: 

(I'm also now considering that this would be released at the same time as an initial iteration of #15419, which wasn't true when we originally discussed this, and so that capability could help mitigate the fact that `terraform refresh` would no longer work to get data sources updated because folks could use `terraform apply` with no other changes to get there instead.)

[the remark this answers is not in the document]
Comment (jbardin) [reply terraform/context_plan_test.go:4996]: The benefit with this PR is that while refresh can be using "old" values for data source config, plan will check again if the data source needs to be read, and update the data source there if needed. While overall it is still not optimal, it should reduce the confusing instances to only those where either the evaluation fails entirely (which is the same situation we have now requiring `-refresh=false`), or when providers require a change in the data source via a dependency (which again we have today).

Overall there shouldn't be much more work to _remove_ data source reevaluation from a separate refresh cycle, but that's not what we need in the end. The bulk of the remaining work is removing the separate refresh cycle entirely, which requires the merging of the refresh and plan walks for all resources at once, which did not look trivial (I only briefly ventured down that path). I also toyed with both not having data sources refresh, and having data sources refresh from state, but that always fails with the cases around using data sources for provider configuration, especially when the data source is involved in authentication.

[the remark this answers is not in the document]
Comment (apparentlymart) [reply terraform/context_plan_test.go:4996]: Hmm indeed... the abuse of data sources for issuing credentials is definitely a wrench in the works here. Reading data sources twice during a plan is not great for that situation either, because it will presumably then issue _two_ sets of credentials, though that's better than it failing altogether.

This particular data source misuse is going to be problematic for #15419 too (`terraform plan` will never succeed without generating a new plan to be applied) so I expect we're going to need to address it somehow either way... :confounded:

[the remark this answers is not in the document]
Comment (jbardin) [reply terraform/context_plan_test.go:4996]: The good news is that the plan-time read is conditional, so it only get's issued twice if the configuration has visible changes (or if the data is doing something incorrectly, which also isn't out of the question with the relaxed legacy API constraints).
