### PR TITLE
terraform: Compare locks and provider requirements

### LINKED ISSUE #26565: Pinned required_providers version ignored by terraform plan
When changing the pinned version of a required provider, `terraform plan` happily ignores it.

### Terraform Version

```
Terraform v0.13.4
```

### Expected Behavior

`terraform plan` fails and tells me to run `terraform init` to update the provider.

### Actual Behavior

A plan is happily produced from invalid code.

### Steps to Reproduce

1. Create a directory and put a similar config in a `main.tf` file:
```terraform
terraform {
  required_version = "0.13.4"
  required_providers {
    github = {
      source  = "hashicorp/github"
      version = "3.0.0"
    }
  }
}

provider "github" {
  token        = var.github_token
  organization = "hashicorp"
}

resource "github_branch_protection" "terraform-master" {
  repository = "terraform"
  branch     = "master"
}

variable "github_token" {
  type = string
}
```
2. run `terraform init`
3. run `terraform plan -var "github_token=$GITHUB_TOKEN"`
4. see a nice plan
5. update the configuration file to bump the github provider version to `3.1.0`
6. run `terraform plan -var "github_token=$GITHUB_TOKEN"`
7. see a nice plan
8. run `terraform init`
10. run `terraform plan -var "github_token=$GITHUB_TOKEN"`
11. see 4 errors being reported instead of a nice plan

### PR DESCRIPTION
**Pull request by alisdair**
When building a context, we read the dependency locks and ensure that the provider requirements from the configuration can be satisfied. If the configured requirements change such that the locks need to be updated, we explain this and recommend running "terraform init".

This check is ignored for any providers which are locally marked as in development. This includes unmanaged providers and those listed in the provider installation `dev_overrides` block.

Fixes #26565.

### Screenshot

diags

### CODE REVIEW

**Comment by alisdair** [comment]
There's a failing e2e test:

```
=== FAIL: command TestPlan_init_required (0.00s)
    plan_test.go:879: wrong error message in output: 
        Error: Provider requirements cannot be satisfied by locked dependencies
        
        The following required providers are not installed:
        
        - registry.terraform.io/hashicorp/test ()
        
        Please run "terraform init".
```

I'm not sure if this is a test that needs to be updated or if we need to somehow cope with this use case.

**Comment by alisdair** [comment]
The above comment was a misread of test output. I'll investigate these test failures and re-request review if I can address them.

File: command/meta.go [hunk 1]
```diff
@@ -421,6 +421,21 @@ func (m *Meta) contextOpts() (*terraform.ContextOpts, error) {
 		}
 		opts.Providers = providerFactories
 		opts.Provisioners = m.provisionerFactories()
+
+		// If any dev overrides or unmanaged providers are in place, we cannot
+		// verify the locks as we have incomplete version information
+		if len(m.UnmanagedProviders) == 0 && len(m.ProviderDevOverrides) == 0 {
```
[the remark this answers is not in the document]
Comment (pselle) [reply command/meta.go:427]: If these settings (at all) mean this check doesn't happen, we should update docs in those areas (.. if there are docs areas?) to warn that this check won't happen if any unmanaged providers are present, or providerdevoverrides.

[the remark this answers is not in the document]
Comment (pselle) [reply command/meta.go:427]: And to your suggestions request ... you mention you'd like to filter. What about adding a method on `Locks` to allow this filtering? Since we have `addrs.Provider` in `UnmanagedProvider` or `ProviderDevOverrides`, could you use a new method to create a new `Locks` with those values filtered out?

[the remark this answers is not in the document]
Comment (alisdair) [reply command/meta.go:427]: Unfortunately filtering development providers out of the locks won't work. The logic in context requires that there is an entry in the locks which satisfies the version constraints in the config.

To allow development providers to work while still verifying other providers, I think we'd need to pass a slice of providers to ignore through to the context, and then skip them like we do for builtin providers. There might be a cleaner way to do it, but I can't see one.

I guess in retrospect it's probably worth trying to do that, if only because it means I don't have to try to explain this weird edge case in the docs 🙃

[the remark this answers is not in the document]
Comment (alisdair) [reply command/meta.go]: Done!

File: command/meta.go [hunk 2]
```diff
@@ -421,6 +421,28 @@ func (m *Meta) contextOpts() (*terraform.ContextOpts, error) {
...
+		lockedDependencies, diags := m.lockedDependencies()
+
+		// If the locks file is invalid, we should fail early rather than
+		// ignore it. A missing locks file will return no error.
+		if diags.HasErrors() {
+			return nil, diags.Err()
+		}
+		opts.LockedDependencies = lockedDependencies
+
+		// If any unmanaged providers or dev overrides are enabled, they must
```
Comment (pselle) [inline command/meta.go:436]: 👍

File: terraform/context_test.go [hunk 3]
```diff
@@ -117,6 +119,134 @@ func TestNewContextRequiredVersion(t *testing.T) {
...
+			LockFile: locksBeepGreaterThanOne,
+		},
+		"no locks given": {
+			Config: configBeepGreaterThanOne,
+		},
+		"builtin provider with empty locks": {
+			Config:   configBuiltin,
+			LockFile: `# This file is maintained automatically by "terraform init".`,
+		},
+		"development provider with empty locks": {
```
Comment (pselle) [inline terraform/context_test.go:180]: Another test case to add could be where there's a managed provider and a development provider? (to ensure that the managed provider is still checked)

Comment (alisdair) [reply terraform/context_test.go:216]: Done, thanks. That's also a more realistic test case, I think.

File: terraform/context_test.go [hunk 4]
```diff
@@ -117,6 +119,171 @@ func TestNewContextRequiredVersion(t *testing.T) {
...
+}
+`
+	configBeepBoop := `
+terraform {
+  required_providers {
+    beep = {
+      source  = "example.com/foo/beep"
+      version = "< 1.0.0" # different from locks
+    }
+	boop = {
```
Comment (pselle) [inline terraform/context_test.go:168]: Extremely trivial, but spacing for readability (tabs/spaces issue?)

File: terraform/context_test.go (hunk 3 above)
Comment (pselle) [reply terraform/context_test.go:216]: One more request for the path where there would be an error for the managed? That is, boop doesn't match, and the error only mentions boop and not beep. (excellent test names)

**Review by pselle — APPROVED** [review]
Two more comments but non-blocking/merge when addressed if you choose to: a readability/whitespace in the tests, and a request for another test case.
