### PR TITLE
backend/gcs Rework Service Account Impersonation

### LINKED ISSUE #28139: backend/gcs: Service Account Impersonation doesn't work if the original identity is another service account.
I implemented service account impersonation a while back in https://github.com/hashicorp/terraform/pull/26700 and it works correctly if the original identity is a google user.

However, it doesn't work properly when you are using a Google Service Account as the original identity.

There is a bug present in how `cloud.google.com/go/storage`(modern/new client) handles ClientOptions supplied to a client but works correctly in `google.golang.org/api/storage/v1` (legacy/autogen client)

Terraform Core uses the new client but TPG uses the legacy client.

PoC:

```
// Modern client in Terraform Core at backend/remote-state/gcs/backend.go

package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"time"

	"cloud.google.com/go/storage"
	"google.golang.org/api/option"
)

func main() {
	ctx := context.Background()

	// Sets your Google Cloud Platform project ID.
	projectID := os.Getenv("GOOGLE_PROJECT")

	// Creates a client.
	client, err := storage.NewClient(ctx, option.ImpersonateCredentials(os.Getenv("GOOGLE_IMPERSONATE_SERVICE_ACCOUNT")))
	if err != nil {
		log.Fatalf("Failed to create client: %v", err)
	}

	// Sets the name for the new bucket.
	bucketName := "foo" // Intentional, expected API response is 409 not 403 from failed impersonation

	// Creates a Bucket instance.
	bucket := client.Bucket(bucketName)

	// Creates the new bucket.
	ctx, cancel := context.WithTimeout(ctx, time.Second*10)
	defer cancel()
	if err := bucket.Create(ctx, projectID, nil); err != nil {
		log.Fatalf("Failed to create bucket: %v", err)
	}

	fmt.Printf("Bucket %v created.\n", bucketName)

}
```

```
 REDACTED  MCW0CDP3YY  ~  Desktop  Git  tpg-2252  $  go run main.go 
2021/03/18 15:47:14 Failed to create bucket: Post "https://storage.googleapis.com/storage/v1/b?alt=json&prettyPrint=false&project=mgcp-1192365-landing-zone": impersonate: status code 403: {
  "error": {
    "code": 403,
    "message": "Request had insufficient authentication scopes.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "ACCESS_TOKEN_SCOPE_INSUFFICIENT",
        "domain": "googleapis.com",
        "metadata": {
          "method": "google.iam.credentials.v1.IAMCredentials.GenerateAccessToken",
          "service": "iamcredentials.googleapis.com"
        }
      }
    ]
  }
}
exit status 1
```

```
// Legacy/Autogen Client used in TPG
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"time"

	"google.golang.org/api/option"
	"google.golang.org/api/storage/v1"
)

func main() {
	ctx := context.Background()

	// Sets your Google Cloud Platform project ID.
	projectID := os.Getenv("GOOGLE_PROJECT")

	// Creates a client.
	client, err := storage.NewService(ctx, option.ImpersonateCredentials(os.Getenv("GOOGLE_IMPERSONATE_SERVICE_ACCOUNT")))
	if err != nil {
		log.Fatalf("Failed to create client: %v", err)
	}

	// Creates a Bucket instance.
	sb := &storage.Bucket{
		Name:     "potato", // Expected Response is 409 and not 403 from failed impersonation
		Location: "us",
	}
	// Creates the new bucket.
	ctx, cancel := context.WithTimeout(ctx, time.Second*10)
	defer cancel()

	if _, err := client.Buckets.Insert(projectID, sb).Do(); err != nil {
		log.Fatalf("Failed to create bucket: %v", err)
	}

	fmt.Printf("Bucket %v created.\n", sb.Name)
}
```

```
 REDACTED  MCW0CDP3YY  ~  Desktop  Git  tpg-2252  $  go run main.go 
2021/03/18 16:32:11 Failed to create bucket: googleapi: Error 409: Sorry, that name is not available. Please try a different one., conflict
exit status 1
```

Terraform Logs:

```
 REDACTED  MCW0CDP3YY  ~  Desktop  Git  REDACTED-Landing-Zone  terraform   initial_build  8✎  3+  $   TF_LOG=debug terraform init
2021/03/18 16:43:11 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
2021/03/18 16:43:11 [INFO] Terraform version: 0.14.7  
2021/03/18 16:43:11 [INFO] Go runtime version: go1.15.6
2021/03/18 16:43:11 [INFO] CLI args: []string{"/usr/local/Cellar/tfenv/2.0.0/versions/0.14.7/terraform", "init"}
2021/03/18 16:43:11 [DEBUG] Attempting to open CLI config file: /Users/REDACTED/.terraformrc
2021/03/18 16:43:11 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2021/03/18 16:43:11 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2021/03/18 16:43:11 [DEBUG] ignoring non-existing provider search directory /Users/REDACTED/.terraform.d/plugins
2021/03/18 16:43:11 [DEBUG] ignoring non-existing provider search directory /Users/REDACTED/Library/Application Support/io.terraform/plugins
2021/03/18 16:43:11 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2021/03/18 16:43:11 [INFO] CLI command args: []string{"init"}
2021/03/18 16:43:11 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----

Initializing the backend...

Error: Failed to get existing workspaces: querying Cloud Storage failed: Get "https://storage.googleapis.com/storage/v1/b/REDACTED-tfstate/o?alt=json&delimiter=%2F&pageToken=&prefix=landing-zone%2F&prettyPrint=false&projection=full&versions=false": impersonate: status code 403: {
  "error": {
    "code": 403,
    "message": "Request had insufficient authentication scopes.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "ACCESS_TOKEN_SCOPE_INSUFFICIENT",
        "domain": "googleapis.com",
        "metadata": {
          "method": "google.iam.credentials.v1.IAMCredentials.GenerateAccessToken",
          "service": "iamcredentials.googleapis.com"
        }
      }
    ]
  }
}

```

@rileykarson @slevenick How do should we deal with this? Resolve it upstream at https://github.com/googleapis/google-cloud-go or shall I rewrite the gcs backend to use the legacy client?

We also need to bump golang.org/x/oauth2 to a newer version to resolve this https://github.com/hashicorp/terraform-provider-google/issues/8671 in Terraform Core.

### PR DESCRIPTION
**Pull request by upodroid**
Fixes #28139﻿

Changelog notes:

```
* backend/gcs: Fixed a bug where service account impersonation didn't work if the original identity was another service account. ([#28139﻿](https://github.com/hashicorp/terraform/issues/28139﻿))

* backend/gcs: Terraform Core now supports [Workload Identity Federation](https://cloud.google.com/iam/docs/workload-identity-federation). The federated json credentials must be loaded through the `GOOGLE_APPLICATION_CREDENTIALS` environment variable. This is also available in the Google Provider in versions newer than v3.61
```

### CODE REVIEW

**Comment by upodroid** [comment]
@rileykarson There is a fun snag with the impersonate library, it will only allow ADCs to impersonate ie `option.WithCredentialsJSON` doesn't work at all.

```
=== CONT  TestBackendWithPrefix
    backend_test.go:146: storage.NewClient() failed: dialing: multiple credential options provided
--- FAIL: TestBackendWithPrefix (0.20s)
=== CONT  TestRemoteClient
    backend_test.go:57: storage.NewClient() failed: dialing: multiple credential options provided
--- FAIL: TestRemoteClient (0.22s)
```
https://github.com/googleapis/google-api-go-client/blob/v0.44.0-impersonate-preview/impersonate/impersonate.go#L62

I recommend getting rid of supplying credentials and access tokens.  https://github.com/hashicorp/terraform-provider-google/issues/7332
Other than that, it works nicely

```
 REDACTED  MCW0CDP3YY  ~  Desktop  Git  terraform   gcs-imp-v2  1✎  $   go test -v ./backend/remote-state/gcs/ 
=== RUN   TestStateFile
=== PAUSE TestStateFile
=== RUN   TestRemoteClient
=== PAUSE TestRemoteClient
=== RUN   TestRemoteClientWithEncryption
=== PAUSE TestRemoteClientWithEncryption
=== RUN   TestRemoteLocks
=== PAUSE TestRemoteLocks
=== RUN   TestBackend
=== PAUSE TestBackend
=== RUN   TestBackendWithPrefix
=== PAUSE TestBackendWithPrefix
=== RUN   TestBackendWithEncryption
=== PAUSE TestBackendWithEncryption
=== CONT  TestStateFile
=== CONT  TestBackendWithEncryption
=== CONT  TestRemoteClient
=== CONT  TestRemoteLocks
=== CONT  TestBackendWithPrefix
=== CONT  TestBackendWithEncryption
    backend_test.go:159: TestBackendConfig on *gcs.Backend with configs.synthBody{Filename:"<TestWrapConfig>", Values:map[string]cty.Value{"bucket":cty.StringVal("tf-1673674efa3ada38-testbackendwithencryption"), "encryption_key":cty.StringVal("yRyCOikXi1ZDNE0xN3yiFsJjg7LGimoLrGFcLZgQoVk="), "prefix":cty.StringVal("")}}
=== CONT  TestRemoteLocks
    backend_test.go:96: TestBackendConfig on *gcs.Backend with configs.synthBody{Filename:"<TestWrapConfig>", Values:map[string]cty.Value{"bucket":cty.StringVal("tf-1673674efa3b91d0-testremotelocks"), "encryption_key":cty.StringVal(""), "prefix":cty.StringVal("")}}
=== CONT  TestRemoteClient
    backend_test.go:57: TestBackendConfig on *gcs.Backend with configs.synthBody{Filename:"<TestWrapConfig>", Values:map[string]cty.Value{"bucket":cty.StringVal("tf-1673674efa3ade20-testremoteclient"), "encryption_key":cty.StringVal(""), "prefix":cty.StringVal("")}}
=== CONT  TestRemoteClientWithEncryption
=== CONT  TestBackendWithPrefix
    backend_test.go:146: TestBackendConfig on *gcs.Backend with configs.synthBody{Filename:"<TestWrapConfig>", Values:map[string]cty.Value{"bucket":cty.StringVal("tf-1673674efa3d2428-testbackendwithprefix"), "encryption_key":cty.StringVal(""), "prefix":cty.StringVal("test/prefix")}}
=== CONT  TestRemoteClientWithEncryption
    backend_test.go:76: TestBackendConfig on *gcs.Backend with configs.synthBody{Filename:"<TestWrapConfig>", Values:map[string]cty.Value{"bucket":cty.StringVal("tf-1673674efa3fe730-testremoteclientwithencryption"), "encryption_key":cty.StringVal("yRyCOikXi1ZDNE0xN3yiFsJjg7LGimoLrGFcLZgQoVk="), "prefix":cty.StringVal("")}}
--- PASS: TestStateFile (0.00s)
=== CONT  TestBackend
    backend_test.go:130: TestBackendConfig on *gcs.Backend with configs.synthBody{Filename:"<TestWrapConfig>", Values:map[string]cty.Value{"bucket":cty.StringVal("tf-1673674efa41cf78-testbackend"), "encryption_key":cty.StringVal(""), "prefix":cty.StringVal("")}}
=== CONT  TestBackendWithPrefix
    backend_test.go:149: TestBackendConfig on *gcs.Backend with configs.synthBody{Filename:"<TestWrapConfig>", Values:map[string]cty.Value{"bucket":cty.StringVal("tf-1673674efa3d2428-testbackendwithprefix"), "encryption_key":cty.StringVal(""), "prefix":cty.StringVal("test/prefix/")}}
=== CONT  TestBackend
    backend_test.go:133: TestBackendConfig on *gcs.Backend with configs.synthBody{Filename:"<TestWrapConfig>", Values:map[string]cty.Value{"bucket":cty.StringVal("tf-1673674efa41cf78-testbackend"), "encryption_key":cty.StringVal(""), "prefix":cty.StringVal("")}}
=== CONT  TestBackendWithEncryption
    backend_test.go:162: TestBackendConfig on *gcs.Backend with configs.synthBody{Filename:"<TestWrapConfig>", Values:map[string]cty.Value{"bucket":cty.StringVal("tf-1673674efa3ada38-testbackendwithencryption"), "encryption_key":cty.StringVal("yRyCOikXi1ZDNE0xN3yiFsJjg7LGimoLrGFcLZgQoVk="), "prefix":cty.StringVal("")}}
--- PASS: TestRemoteClientWithEncryption (4.83s)
--- PASS: TestRemoteClient (5.12s)
--- PASS: TestRemoteLocks (5.38s)
=== CONT  TestBackendWithPrefix
    testing.go:299: TestBackend: testing state locking for *gcs.Backend
=== CONT  TestBackend
    testing.go:299: TestBackend: testing state locking for *gcs.Backend
=== CONT  TestBackendWithEncryption
    testing.go:299: TestBackend: testing state locking for *gcs.Backend
--- PASS: TestBackendWithPrefix (15.99s)
=== CONT  TestBackend
    testing.go:299: TestBackend: testing state locking for *gcs.Backend
--- PASS: TestBackendWithEncryption (17.55s)
--- PASS: TestBackend (24.18s)
PASS
ok      github.com/hashicorp/terraform/backend/remote-state/gcs 24.506s
 REDACTED  MCW0CDP3YY  ~  Desktop  Git  terraform   gcs-imp-v2  1✎  $   env | grep GOO
GOOGLE_REGION=us-central1
GOOGLE_APPLICATION_CREDENTIALS=/Users/REDACTED/Downloads/REDACTED-f92a047fcc9c.json
GOOGLE_IMPERSONATE_SERVICE_ACCOUNT=terraform@REDACTED.iam.gserviceaccount.com
GOOGLE_ZONE=us-central1-a
GOOGLE_PROJECT=mgcp-1192365-landing-zone
GOOGLE_USE_DEFAULT_CREDENTIALS=true
```

**Comment by upodroid** [comment]
Ignore last comment.

This is ready now.

Tested the following env combinations:

```
 REDACTED  MCW0CDP3YY  ~  Desktop  Git  terraform   gcs-imp-v2  1✎  $   env | grep GOO
GOOGLE_REGION=us-central1
GOOGLE_BACKEND_CREDENTIALS=/Users/maha4472/Downloads/REDACTED-f92a047fcc9c.json
GOOGLE_IMPERSONATE_SERVICE_ACCOUNT=terraform@REDACTED.gserviceaccount.com
GOOGLE_ZONE=us-central1-a
GOOGLE_PROJECT=REDACTED
GOOGLE_USE_DEFAULT_CREDENTIALS=true
```

```
 REDACTED  MCW0CDP3YY  ~  Desktop  Git  terraform   gcs-imp-v2  1✎  $   env | grep GOO
GOOGLE_REGION=us-central1
GOOGLE_APPLICATION_CREDENTIALS=/Users/REDACTED/Downloads/REDACTED-f92a047fcc9c.json
GOOGLE_IMPERSONATE_SERVICE_ACCOUNT=terraform@REDACTED.iam.gserviceaccount.com
GOOGLE_ZONE=us-central1-a
GOOGLE_PROJECT=mgcp-1192365-landing-zone
GOOGLE_USE_DEFAULT_CREDENTIALS=true
```

```
 REDACTED  MCW0CDP3YY  ~  Desktop  Git  terraform   gcs-imp-v2  $   env | grep GOO
GOOGLE_REGION=us-central1
GOOGLE_ZONE=us-central1-a
GOOGLE_PROJECT=REDACTED
GOOGLE_USE_DEFAULT_CREDENTIALS=true
```

They all work correctly.

File: backend/remote-state/gcs/backend.go [hunk 1]
```diff
@@ -162,22 +147,22 @@ func (b *Backend) configure(ctx context.Context) error {
...
+		ts, err := impersonate.CredentialsTokenSource(ctx, impersonate.CredentialsConfig{
+			TargetPrincipal: ServiceAccount,
+			Scopes:          []string{storage.ScopeReadWrite},
+		}, credOptions...)
+
+		if err != nil {
+			return err
+		}
+
+		opts = append(opts, option.WithTokenSource(ts))
```
Comment (rileykarson) [inline backend/remote-state/gcs/backend.go:165]: Won't two `CredentialsConfig` options get added when there are delegates? How is that handled, and can we link to documentation if so?

File: backend/remote-state/gcs/backend.go [hunk 2]
```diff
@@ -162,22 +147,22 @@ func (b *Backend) configure(ctx context.Context) error {
 			return fmt.Errorf("Error parsing credentials '%s': %s", contents, err)
 		}
 
-		conf := jwt.Config{
```
Comment (rileykarson) [inline backend/remote-state/gcs/backend.go:165]: Why is removing this safe, exactly? I'm not 100% read up on auth details right now, so I could be missing something obvious here 🙂

Comment (upodroid) [reply backend/remote-state/gcs/backend.go:165]: It was building the http client directly from the JWT of the service account which isn't great and `option.WithCredentialsJSON()` is simpler to use.

On a second look, I could have reused the `option.WithHTTPClient(conf.Client(ctx))` but I would prefer to avoid interacting with http.client unless it is necessary.

File: backend/remote-state/gcs/backend.go (hunk 1 above)
Comment (upodroid) [reply backend/remote-state/gcs/backend.go]: That is wrong. I have fixed it now.

**Review by rileykarson — APPROVED** [review]
These changes seem reasonable to me from a GCP perspective.

**Comment by upodroid** [comment]
@alisdair Can I get this reviewed and merged?

Also if I wanted to remove fields from the gcs backend schema, it is easier to do it before the mythical v1 release? The fields are mentioned here https://github.com/hashicorp/terraform-provider-google/issues/7332

**Comment by alisdair** [comment]
@upodroid Thanks for your work on this. A few notes pre-review:

- The tests are failing—I'm not sure what's causing that. Can you look into it?
- Why are there changes to the `mock_proto` files?
- Removing fields from the backend would be a breaking change, and I'm not sure when we'd want to do that. Removing them before 1.0 isn't completely essential—with the deprecation process they could always be removed in a later 1.x release.

**Comment by upodroid** [comment]
The CI run from 39bfa6f mentioned that those files needs to be generated

https://app.circleci.com/pipelines/github/hashicorp/terraform/5714/workflows/96fb8cfc-79e3-416f-b785-04c8c618f744/jobs/38342

**Comment by rileykarson** [comment]
> Also if I wanted to remove fields from the gcs backend schema, it is easier to do it before the mythical v1 release? The fields are mentioned here hashicorp/terraform-provider-google#7332

FWIW, we haven't committed to doing so in the provider at this point- we've added it to the `4.0.0` backlog for discussion in a few months.

**Comment by mildwonkey** [comment]
I ran `go generate ./...` locally, and it did not touch those mock_proto files - can you revert those changes and rebase against main? I don't know why it would have added periods on the end of those sentences 🤷‍♀️

**Comment by upodroid** [comment]
@mildwonkey current head of this repo is reproducing the error.

When I upgraded the google.golang.org/api to v0.44.0-impersonate-preview, it also upgraded mock to v1.5.

Forcing mock down to v1.4.4 downgrades the google library too, whcih doesn't help me.

```
 REDACTED  MCW0CDP3YY  ~  Desktop  Git  terraform   gcs-imp-v2  3✎  $   go get github.com/golang/mock@v1.4.4
 REDACTED  MCW0CDP3YY  ~  Desktop  Git  terraform   gcs-imp-v2  2✎  $   git diff
diff --git a/go.mod b/go.mod
index dffc9bc4a..cf5207c0f 100644
--- a/go.mod
+++ b/go.mod
@@ -35,9 +35,10 @@ require (
        github.com/dylanmei/winrmtest v0.0.0-20190225150635-99b7fe2fddf1
        github.com/go-test/deep v1.0.3
        github.com/gofrs/uuid v3.3.0+incompatible // indirect
-       github.com/golang/mock v1.5.0
+       github.com/golang/mock v1.4.4
        github.com/golang/protobuf v1.4.3
        github.com/google/go-cmp v0.5.5
+       github.com/google/pprof v0.0.0-20210226084205-cbba55b83ad5 // indirect
        github.com/google/uuid v1.2.0
        github.com/gophercloud/gophercloud v0.10.1-0.20200424014253-c3bfe50899e5
        github.com/gophercloud/utils v0.0.0-20200423144003-7c72efc7435d
@@ -128,7 +129,8 @@ require (
        golang.org/x/term v0.0.0-20201210144234-2321bbc49cbf
        golang.org/x/text v0.3.5
        golang.org/x/tools v0.1.0
-       google.golang.org/api v0.44.0-impersonate-preview
+       google.golang.org/api v0.41.0
+       google.golang.org/genproto v0.0.0-20210319143718-93e7006c17a6 // indirect
        google.golang.org/grpc v1.36.0
        google.golang.org/protobuf v1.25.0
        gopkg.in/ini.v1 v1.42.0 // indirect
diff --git a/go.sum b/go.sum
index ecbecc4a9..4bf70b122 100644
--- a/go.sum
+++ b/go.sum
@@ -912,6 +912,8 @@ google.golang.org/api v0.35.0/go.mod h1:/XrVsuzM0rZmrsbjJutiuftIzeuTQcEeaYcSk/mQ
 google.golang.org/api v0.36.0/go.mod h1:+z5ficQTmoYpPn8LCUNVpK5I7hwkpjbcgqA7I34qYtE=
 google.golang.org/api v0.40.0/go.mod h1:fYKFpnQN0DsDSKRVRcQSDQNtqWPfM9i+zNPxepjRCQ8=
 google.golang.org/api v0.41.0/go.mod h1:RkxM5lITDfTzmyKFPt+wGrCJbVfniCr2ool8kTBzRTU=
+google.golang.org/api v0.42.0/go.mod h1:+Oj4s6ch2SEGtPjGqfUfZonBH0GjQH89gTeKKAEGZKI=
+google.golang.org/api v0.43.0/go.mod h1:nQsDGjRXMo4lvh5hP0TKqF244gqhGcr/YSIykhUk/94=
 google.golang.org/api v0.44.0-impersonate-preview h1:/7twr+Es8HH6URUkpfcnn6mCadE7NCYmogHzBXNQZh4=
 google.golang.org/api v0.44.0-impersonate-preview/go.mod h1:nQsDGjRXMo4lvh5hP0TKqF244gqhGcr/YSIykhUk/94=
 google.golang.org/appengine v1.1.0/go.mod h1:EbEs0AVv82hx2wNQdGPgUI5lhzA/G0D9YwlJXL52JkM=
(END)
```

**Comment by upodroid** [comment]
I think we are good to go.

**Comment by upodroid** [comment]
Bump 😄

**Review by alisdair — APPROVED** [review]

**Comment by alisdair** [comment]
Thanks for your patience on this, @upodroid!

**Comment by flightlesstux** [comment]
> These changes LGTM to me from a GCP perspective.

+1 @rileykarson
