### PR TITLE
cli: Fix rendering of long integers

### LINKED ISSUE #27438: Unexpected Exponent Formatting in Printing Output
### Terraform Version

```
$ terraform --version
Terraform v0.14.4
```

### Terraform Configuration Files

```terraform
locals {
  example_value = 12345678
}

output "example_value" {
  value = local.example_value
}
```

### Expected Behavior

```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

example_value = 12345678
```

### Actual Behavior

```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

example_value = 1.2345678e+07
```

### Steps to Reproduce

```sh
$ terraform --version
Terraform v0.14.4
$ mkdir mwe
$ cat << HCL > mwe/main.tf
locals {
  example_value = 12345678
}

output "example_value" {
  value = local.example_value
}
HCL
$ terraform -chdir=mwe apply -auto-approve

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

example_value = 1.2345678e+07

```

### PR DESCRIPTION
**Pull request by alisdair**
Recent changes to the human-readable rendering of outputs and console values led to long integer values being presented in scientific notation (e.g. 1.2345678e+07). While technically correct, this is an unusual way to present integer values.

This commit checks if a number value is an integer, and if so renders it as a sequence of digits instead (e.g. 12345678).

Fixes #27438.

### CODE REVIEW

File: repl/format.go [hunk 1]
```diff
@@ -52,6 +52,9 @@ func FormatValue(v cty.Value, indent int) string {
 			return strconv.Quote(v.AsString())
 		case cty.Number:
 			bf := v.AsBigFloat()
+			if bf.IsInt() {
+				return bf.String()
+			}
```
Comment (apparentlymart) [inline repl/format.go:57]: I guess the result is probably the same for integers in the end anyway, but I think elsewhere we've used the `f` formatting mode which _never_ uses scientific notation. It feels weird to me to use scientific notation in Terraform since we're not typically _doing science_, but I guess it'll probably produce a better result for very small fractional numbers... :thinking: maybe we should (separately from this PR) do a survey of how we've been formatting numbers to strings for the UI elsewhere and decide what our "standard" ought to be.

**Review by apparentlymart — APPROVED** [review]

File: repl/format.go (hunk 1 above)
Comment (alisdair) [reply repl/format.go]: Thanks! After a quick look, I can only find `bf.Text('f', -1)` as the other way we display numbers in Terraform: https://github.com/hashicorp/terraform/blob/5132abf6386830420797c739fb535f5f5b0b424f/command/format/diff.go#L720-L722

That's certainly clearer than my original branching approach, so I've updated the commit to use that. No more scientific notation!

I can't find any test cases that don't work well with this. Even very large integer values print correctly:

```shellsession
$ echo 12345678901234567890123456789012345678901234567890 | terraform console
12345678901234567890123456789012345678901234567890
```

**Review by apparentlymart — APPROVED** [review]
