### PR TITLE
provider/aws: Validate `aws_iam_policy_attachment` Name parameter to stop being empty

### LINKED ISSUE #8368: aws: if "aws_iam_policy_attachment" has a blank name, state is empty
Following the format below but its clear from looking at the source that we need to do a validation func that the name is non-empty since we use it as the ID in the state. If it is blank then helper/schema doesn't store anything for it!

### Terraform Version

0.7.1

### Affected Resource(s)

- aws_iam_policy_attachment

### Terraform Configuration Files

```hcl
resource "aws_iam_policy_attachment" "attach_admin" {
    name = ""

    groups = [
      "asdf"
    ]

    policy_arn = "arn:aws:iam::aws:policy/AdministratorAccess"
}
```

### Expected Behavior

It creates the IAM policy attachment and stores it in the state.

### Actual Behavior

It **does** crate the IAM policy attachment **but** it doesn't store it in the state, resulting in `terraform apply` constantly creating the attachment.

### Steps to Reproduce

1. `terraform apply`
1. `terraform apply` again

### PR DESCRIPTION
**Pull request by stack72**
Fixes #8368

```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSPolicyAttachment_'
==> Checking that code complies with gofmt requirements...
/Users/stacko/Code/go/bin/stringer
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/08/24 11:46:01 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v
-run=TestAccAWSPolicyAttachment_ -timeout 120m
=== RUN   TestAccAWSPolicyAttachment_basic
--- PASS: TestAccAWSPolicyAttachment_basic (44.67s)
=== RUN   TestAccAWSPolicyAttachment_paginatedEntities
--- PASS: TestAccAWSPolicyAttachment_paginatedEntities (161.68s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/aws    206.379s
```

### CODE REVIEW

File: builtin/providers/aws/resource_aws_iam_policy_attachment.go [hunk 1]
```diff
@@ -25,6 +25,14 @@ func resourceAwsIamPolicyAttachment() *schema.Resource {
 				Type:     schema.TypeString,
 				Required: true,
 				ForceNew: true,
+				ValidateFunc: func(v interface{}, k string) (ws []string, errors []error) {
+					value := v.(string)
+					if value == "" {
```
Comment (mitchellh) [inline builtin/providers/aws/resource_aws_iam_policy_attachment.go]: nitpick if you want, you can just do `if v.(string) == ""`

**Comment by mitchellh** [comment]
LGTM! One nitpick but otherwise good to go.
