### PR TITLE
command/meta_backend: Allow the remote backend to have no workspaces [again]

### LINKED ISSUE #30129: Unable to init using remote backend and Terraform v1.1.0
Terraform v1.1.0 will not initialize using a remote backend if there is no existing workspaces.

### Terraform Version
```
Terraform v1.1.0
on darwin_amd64
```

### Terraform Configuration Files
```terraform
terraform {
  backend "remote" {
    organization = "xxxx"

    workspaces {
      prefix = "hello-"
    }
  }
}
```

### Debug Output
```
$ terraform init

Initializing the backend...
╷
│ Error: No existing workspaces.
│ 
│ Use the "terraform workspace" command to create and select a new workspace.
│ If the backend already contains existing workspaces, you may need to update
│ the backend configuration.
│ 
│ 
╵

$ terraform workspace new hello
╷
│ Error: Backend initialization required, please run "terraform init"
│ 
│ Reason: Initial configuration of the requested backend "remote"
│ 
│ The "backend" is the interface that Terraform uses to store state,
│ perform operations, etc. If this message is showing up, it means that the
│ Terraform configuration you're using is using a custom configuration for
│ the Terraform backend.
│ 
│ Changes to backend configurations require reinitialization. This allows
│ Terraform to set up the new configuration, copy existing state, etc. Please run
│ "terraform init" with either the "-reconfigure" or "-migrate-state" flags to
│ use the current configuration.
│ 
│ If the change reason above is incorrect, please verify your configuration
│ hasn't changed and try again. At this point, no changes to your existing
│ configuration or state have been made.
╵

```
https://gist.github.com/dflook/b43b0c303f3d8940eeab5dcafa1f7faa

### Expected Behavior
Terraform should have initialized such that I can create a workspace

### Steps to Reproduce
1. `terraform init`

### Additional Context
These commands are run by CI typically with `-input=false`, but that doesn't seem to make a difference.
Some workspaces are created for the duration of a build, some are created for the duration of a PR.

The error message appears with terraform <v1.1.0 but the backend would be successfully configured, so it could be easily ignored and a workspace created.

### PR DESCRIPTION
**Pull request by chrisarcand**
Closes #30129

A regression introduced in d72a413ef833d4882fcb15d7436fba4a35d53741 (https://github.com/hashicorp/terraform/pull/29945)

The comment explains, but TLDR: The remote backend actually *depended* on being able to write it's backend state even though an 'error' occurred (no workspaces). This is expected behavior for the remote backend: 

image

With the improvements made in the changes mentioned above, an error now means that the backend config should _not_ be written to disk......except in this particular situation, sadly.

---

There are no tests for this, I know; we don't really have any sort of test harness for initializing this backend (all backend tests like this just use the local backend).

### CODE REVIEW

File: internal/command/meta_backend.go [hunk 1]
```diff
@@ -1025,11 +1025,24 @@ func (m *Meta) backend_C_r_s(c *configs.Backend, cHash int, sMgr *clistate.Local
...
-	// Verify that selected workspace exist. Otherwise prompt user to create one
+	// Verify that selected workspace exists in the backend.
 	if opts.Init && b != nil {
-		if err := m.selectWorkspace(b); err != nil {
+		err := m.selectWorkspace(b)
+		if err != nil {
 			diags = diags.Append(err)
-			return nil, diags
+
+			// HACK: A compatibility oddity with the 'remote' backend.
```
Comment (alisdair) [inline internal/command/meta_backend.go:1034]: We're just starting to establish a convention of explicitly using `FIXME` to mark technical debt, and that seems fairly appropriate here instead of `HACK`, if you wouldn't mind changing it 🙏

**Review by alisdair — COMMENTED** [review]
If I'm reading this correctly, any error on selecting a workspace with the `remote` backend will now result in not just writing the backend state (the point of this PR) but also a "success" UI output. If that's true, and doesn't match 1.0 behaviour, it seems like it'd be best to avoid it if possible. Can you confirm either way?

**Comment by chrisarcand** [comment]
>  Can you confirm either way?

Good call double checking this, but it is indeed retaining a lovely UX:  ✅ ❌   👍🏻

CleanShot 2021-12-14 at 09 46 46@2x

CleanShot 2021-12-14 at 09 47 37@2x

**Review by alisdair — APPROVED** [review]
🎉

**Comment by uturunku1** [comment]
@chrisarcand So, it sounds like is not possible to run the cmd "terraform workspace new some-new-name" without writing the backend state first, right? Because I think it would have been nice to match a similar behavior to what we see with "cloud" (meaning, we error first, then we offer the user to either input a workspace name or, in the case of remote backend, we offer to enter the `workspace` cmd, and  only then we finally write the state. But this is probably just a very naive approach I picture without understanding well the `workspace` cmd requirements.
I have smoke tested this change and it seems to work as well as before 1.1, so I approve these changes.

**Comment by chrisarcand** [comment]
> Because I think it would have been nice to match a similar behavior to what we see with "cloud" 

That is true, but is arguably a breaking change from the original existing behavior intentionally written: That no workspaces is ultimately a successful initialization that you should then follow up with by creating a new workspace explicitly, not requiring a workspace to initialize. 

It's sort of weird behavior (which is why it was changed, in the Cloud integration!), but a behavior that wasn't intended to be changed and is now retained here 👍🏻
