### PR TITLE
lang/funcs: lookup() can work with maps of lists, maps and objects

### LINKED ISSUE #22267: Weird behavior when using the lookup function in terraform 0.12.x
# Description of the issue

I am trying to use the [`lookup` function](https://www.terraform.io/docs/configuration/functions/lookup.html) with a `variable`, which fails. At the same time, using the function on a `local` with similar characteristics succeeds. The error message given seems to imply different semantics than what is described in the documentation

# Terraform version

`0.12.2` and `0.12.5`

# Minimal example

## Files to reproduce the issue

`terraform.tfvars`:
```hcl
test_elem1 = {
  "instance-01" = {
    name = "foo"
  }
}
```

`main.tf`
```hcl
variable "test_elem1" {
  type = "map"
}
locals {
  test_elem1 = var.test_elem1
  test_elem2 = {"instance-01" = {"name" = "bar"}}
}
```

## Commands to reproduce the issue
```zsh
sme@ada: ~/tmp/terraform_lookup_bug > terraform_0_12_2 init

Initializing the backend...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
sme@ada: ~/tmp/terraform_lookup_bug > terraform_0_12_2 console
> local.test_elem1
{
  "instance-01" = {
    "name" = "foo"
  }
}
> local.test_elem2
{
  "instance-01" = {
    "name" = "bar"
  }
}
> lookup(local.test_elem1, "instance-01")

>  
Error: Error in function call

  on <console-input> line 1:
  (source code not available)
    |----------------
    | local.test_elem1 is map of object with 1 element

Call to function "lookup" failed: lookup() can only be used with flat lists.

> lookup(local.test_elem2, "instance-01")
{
  "name" = "bar"
}
>  
```

## Expected output
I was expecting the lookup on the variable to behave in the same way as the lookup on the local.

As an aside (and as mentioned in the top of this issue), I am puzzled by the error message coming from terraform: `lookup() can only be used with flat lists.`, which to me differs in explanation to that of the [documentation](https://www.terraform.io/docs/configuration/functions/lookup.html): 

> `lookup` retrieves the value of a single element from a map, given its key

### PR DESCRIPTION
**Pull request by mildwonkey**
lookup() can already handle arbitrary objects of (whatever) and should
handle maps of (whatever) similarly.

[The documentation](https://www.terraform.io/docs/configuration/functions/lookup.html) does _not_ mention any limitation to the types returned, which was inconsistent with the error message when a map of objects, lists or maps was used.

Fixes #22267

### CODE REVIEW

File: lang/funcs/collection.go [hunk 1]
```diff
@@ -660,6 +660,12 @@ var LookupFunc = function.New(&function.Spec{
 			}
 			return cty.DynamicPseudoType, function.NewArgErrorf(0, "the given object has no attribute %q", key)
 		case ty.IsMapType():
+			if len(args) == 3 {
+				_, err = convert.Convert(args[2], ty.ElementType())
+				if err != nil {
+					return cty.NilType, function.NewArgErrorf(0, "the default value and map elements must have the same type")
```
Comment (apparentlymart) [inline lang/funcs/collection.go]: The `0` here indicates that the problem is with the zeroth argument; perhaps it would be clearer to indicate `2` so that Terraform will indicate the default value as the subject of the error when it prints out diagnostics, as a subtle additional indication that it's probably the default value that ought to change to match the map, rather than the other way around.

File: lang/funcs/collection.go [hunk 2]
```diff
@@ -695,8 +701,10 @@ var LookupFunc = function.New(&function.Spec{
 					return cty.NumberVal(v.AsBigFloat()), nil
 				case ty.Equals(cty.Bool):
 					return cty.BoolVal(v.True()), nil
+				case ty.IsObjectType() || ty.IsListType() || ty.IsMapType():
+					return v, nil
 				default:
-					return cty.NilVal, errors.New("lookup() can only be used with maps of primitive types")
+					return cty.NilVal, fmt.Errorf("lookup() cannot be used with type %s", ty.FriendlyName())
```
Comment (apparentlymart) [inline lang/funcs/collection.go]: This `switch` statement seems to ultimately just be a bunch of no-ops: if it's a string then convert it to a string, if it's a number convert it to a number, etc.

I'm wondering if we could just replace this whole thing with `return mapVar.Index(cty.StringVal(lookupKey)), nil` and thus be completely type agnostic, just like the language's built-in index operator. Do you remember what we put this here for originally? Perhaps it was just inherited from the 0.11 implementation of `lookup`? :thinking:

File: lang/funcs/collection_test.go [hunk 3]
```diff
@@ -1469,6 +1469,22 @@ func TestLookup(t *testing.T) {
...
+		}),
+	})
+	mapOfObjects := cty.ObjectVal(map[string]cty.Value{
+		"foo": cty.MapVal(map[string]cty.Value{
+			"a": cty.StringVal("bar"),
+		}),
+		"baz": cty.MapVal(map[string]cty.Value{
+			"b": cty.StringVal("bat"),
+		}),
+	})
```
Comment (apparentlymart) [inline lang/funcs/collection_test.go]: For completeness, maybe we could also test a map of tuples here... map of tuples doesn't really arise much in real use, but it can arise in principle, such as if we write `tomap({"a": []})`, which would have type `map(tuple([]))`.

File: lang/funcs/collection_test.go [hunk 4]
```diff
@@ -1469,6 +1469,22 @@ func TestLookup(t *testing.T) {
...
 	})
+	mapOfMaps := cty.MapVal(map[string]cty.Value{
+		"foo": cty.MapVal(map[string]cty.Value{
+			"a": cty.StringVal("bar"),
+		}),
+		"baz": cty.MapVal(map[string]cty.Value{
+			"b": cty.StringVal("bat"),
+		}),
+	})
+	mapOfObjects := cty.ObjectVal(map[string]cty.Value{
```
Comment (apparentlymart) [inline lang/funcs/collection_test.go]: This seems to be an "object of maps", rather than the other way around.

**Comment by apparentlymart** [comment]
Looking good, thanks! I left some minor notes inline.

File: lang/funcs/collection.go (hunk 2 above)
Comment (mildwonkey) [reply lang/funcs/collection.go]: That's beautiful! And no, I have no recollection of why this was done this way. I implemented your suggestion and the tests continue to pass, so hooray for simplification!

File: lang/funcs/collection_test.go (hunk 4 above)
Comment (mildwonkey) [reply lang/funcs/collection_test.go]: Ah, I noticed that too, but forgot to fix it. I bet I wrote that in the first place 🙃
