### PR TITLE
command: "terraform show" to render plans like "terraform plan"

### LINKED ISSUE #23106: terraform show on v0.12 only display resource addresses
### Terraform Version

```
0.12.10
```

### Terraform Configuration Files
```hcl
provider "aws" {
  region = "eu-west-1"
  version = "2.32.0"
}


resource "aws_s3_bucket" "bucket" {
  bucket = "test"

  tags = {
    test = "test"
  }
}
```

### Expected Behavior
`terraform show` should display the full plan, the exact same output as the `terraform plan`
```
Terraform will perform the following actions:

  # aws_s3_bucket.bucket will be created
  + resource "aws_s3_bucket" "bucket" {
      + acceleration_status         = (known after apply)
      + acl                         = "private"
      + arn                         = (known after apply)
      + bucket                      = "test"
      + bucket_domain_name          = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = false
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + tags                        = {
          + "test" = "test"
        }
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)

      + versioning {
          + enabled    = (known after apply)
          + mfa_delete = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

### Actual Behavior
`terraform show` only outputs the resource name, which is not very useful
```
  + aws_s3_bucket.bucket
```

> it works perfectly on 0.11 and I always had this issue with 0.12 (any of the versions) 

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. `$HOME/terraform_0.12.10 init`
2. `$HOME/terraform_0.12.10 plan -out test.plan`
3. `$HOME/terraform_0.12.10 show  test.plan`

### References
- #21864

### PR DESCRIPTION
**Pull request by apparentlymart**
During the Terraform 0.12 work we briefly had a partial update of the old Terraform 0.11 (and prior) diff renderer that could work with the new plan structure, but could produce only partial results.

We switched to the new plan implementation prior to release, but the `terraform show` command was left calling into the old partial implementation, and thus produced incomplete results when rendering a saved plan.

Here we instead use the plan rendering logic from the `terraform plan` command, making the output of both identical.

This fixes #23106.

---

Unfortunately, due to the current backend architecture that logic lives inside the `backend/local`, and it contains some business logic around state and schema wrangling that would make it inappropriate to move wholesale into the `command/format` package. To allow for a low-risk fix to the `terraform show` output, here we avoid some more severe refactoring by just exporting the rendering functionality in a way that allows the `terraform show` command to call into it.

In future we'd like to move all of the code that actually writes to the output into the `command` package so that the roles of these components are better segregated, but that is too big a change to block fixing this issue.

---

This also left lots of dead code in `command/format` for the old and mostly-broken plan renderer. In order to reduce naming confusion in the `command/format` package I've removed `plan.go` entirely after removing the one function that was still used from there (`DiffActionSymbol`) into `diff.go`.

### CODE REVIEW

File: backend/local/backend_plan.go [hunk 1]
```diff
@@ -190,6 +193,21 @@ func (b *Local) opPlan(
...
+}
+
+// RenderPlan renders the given plan to the given UI.
+//
+// This is exported only so that the "terraform show" command can re-use it.
+// Ideally it would be somewhere outside of this backend code so that both
+// can call into it, but we're leaving it here for now in order to avoid
+// disruptive refactoring.
+//
+// If you find yourself wanting to call this function from a third callsite,
```
Comment (pselle) [inline backend/local/backend_plan.go]: I love this comment

**Comment by remipichon** [comment]
Thank you ! That was quick, hats off to you.
