### PR TITLE
provider/openstack: Rename provider to loadbalancer_provider

### LINKED ISSUE #12237: openstack_lb_loadbalancer_v2: "provider" attribute fails validation because of namespace collision with "Provider"
```
resource "openstack_lb_loadbalancer_v2" "hero_edge" {
  region        = "${var.region}"
  vip_subnet_id = "${var.vip_subnet_id}"
  provider      = "a10networks_ext"
}
```

Upon attempting to plan:
```
» terraform plan xx-98
2 error(s) occurred:

* module web: provider alias must be defined by the module or a parent: a10networks_ext
```

Obviously, this isn't referring to the `provider` attribute listed here:
https://www.terraform.io/docs/providers/openstack/r/lb_loadbalancer_v2.html

And instead is referring to the Provider during validation:
https://github.com/hashicorp/terraform/blob/f2c16b7ba2b01b233623097e479825efe1ead3c8/config/module/validate_provider_alias.go#L69-L71

### Terraform Version
Terraform v0.8.7

### Affected Resource
- openstack_lb_loadbalancer_v2

### Terraform Configuration Files
```
resource "openstack_lb_loadbalancer_v2" "hero_edge" {
  region        = "${var.region}"
  vip_subnet_id = "${var.vip_subnet_id}"
  provider      = "a10networks_ext"
}
```

### Debug Output
https://gist.github.com/rcreasey/f79c160cd14a3c1f5110567efb4070d1

### Expected Behavior
This "provider" attribute should be applied to the resource and not validated as a "Provider" alias.

### Actual Behavior
What actually happened?

### Steps to Reproduce
1. Define a `openstack_lb_loadbalancer_v2` resource and specify the `provider` attribute.
2. Attempt to run `terraform plan`

### Important Factoids
This seems to be a failure in the validation code of Terraform, and not related to any specific Openstack API.

### PR DESCRIPTION
**Pull request by jtopjian**
This commit renames provider to loadbalancer_provider in the
openstack_lb_loadbalancer_v2 resource.

It also changes security_group_ids to Computed so default
security groups are added to the state correctly.

Fixes #12237

### CODE REVIEW

File: builtin/providers/openstack/resource_openstack_lb_loadbalancer_v2.go [hunk 1]
```diff
@@ -75,7 +75,7 @@ func resourceLoadBalancerV2() *schema.Resource {
 				ForceNew: true,
 			},
 
-			"provider": &schema.Schema{
+			"loadbalancer_provider": &schema.Schema{
```
Comment (jtopjian) [inline builtin/providers/openstack/resource_openstack_lb_loadbalancer_v2.go]: @stack72 I can definitely do a deprecation thing here.

Just curious, though: would `provider` have worked during any previous release? Was it only recent that the error reported in #12237 would happen? If so, that would definitely help my sanity :)

File: builtin/providers/openstack/resource_openstack_lb_loadbalancer_v2.go [hunk 2]
```diff
@@ -100,6 +108,11 @@ func resourceLoadBalancerV2Create(d *schema.ResourceData, meta interface{}) erro
 		return fmt.Errorf("Error creating OpenStack networking client: %s", err)
 	}
 
+	var lbProvider string
+	if v, ok := d.GetOk("loadbalancer_provider"); ok {
+		lbProvider = v.(string)
+	}
+
```
Comment (jtopjian) [inline builtin/providers/openstack/resource_openstack_lb_loadbalancer_v2.go]: @stack72 I couldn't decide on leaving this part as-is or adding the following:

```go
if v, ok := d.GetOk("provider"); ok && lbProvider != "" {
        lbProvider = v.(string)
}
```

The above would set `lbProvider` if `provider` was set and the new preferred `loadbalancer_provider` wasn't set. However, since having an argument of `provider will error out anyway, is it worth adding the above block of code in?

**Comment by rcreasey** [comment]
FYI, I've validated this actually correctly sets the `openstack_lb_loadbalancer_v2` provider attribute against an actual OpenStack Neutron API.
