### PR TITLE
Consider security groups with source security groups when hashing

### LINKED ISSUE #2294: AWS Provider in 0.5.3- Can not tie multiple aws_security_group_rule to one security group
Again, I just love Terraform.. I sing its praises to everyone I meet!
The second issue I found deals again with `aws_security_group_rule`. I can not get one security group to attach multiple rules (which point to other security groups) without throwing errors on subsequent `apply`s.

# File structure and contents
## tree
```
$ tree
.
├── main.tf
└── terraform.tfvars
0 directories, 2 files
```
## main.tf
```
variable "access_key" {}
variable "region" {}
variable "secret_key" {}

provider "aws" {
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
  region     = "${var.region}"
}
resource "aws_vpc" "vpc" {
  cidr_block           = "172.16.0.0/16"
  enable_dns_hostnames = true
  enable_dns_support   = true
  tags {
    Name = "asgr2-vpc"
  }
}

resource "aws_security_group" "nat" {
  description = "nat security group"
  name        = "asgr2-nat"
  vpc_id      = "${aws_vpc.vpc.id}"
  tags {
    Name = "asgr2-nat"
  }
}
resource "aws_security_group" "admin" {
  description = "admin security group"
  name        = "asgr2-admin"
  vpc_id      = "${aws_vpc.vpc.id}"
  tags {
    Name = "asgr2-admin"
  }
}
resource "aws_security_group" "bastion" {
  description = "bastion security group"
  name        = "asgr2-bastion"
  vpc_id      = "${aws_vpc.vpc.id}"
  tags {
    Name = "asgr2-bastion"
  }
}

resource "aws_security_group_rule" "admin_ingress_nat" {
  from_port                = 0
  protocol                 = "-1"
  security_group_id        = "${aws_security_group.admin.id}"
  source_security_group_id = "${aws_security_group.nat.id}"
  to_port                  = 0
  type                     = "ingress"
}
resource "aws_security_group_rule" "admin_ingress_bastion" {
  from_port                = 0
  protocol                 = "-1"
  security_group_id        = "${aws_security_group.admin.id}"
  source_security_group_id = "${aws_security_group.bastion.id}"
  to_port                  = 0
  type                     = "ingress"
}
```
## terraform.tfvars
```
access_key = "<actual_access_key_here>"
region = "us-west-2"
secret_key = "<actual_secret_key_here>"
```

# Terraform version
Tested with both:
```
$ terraform --version
Terraform v0.5.3
```
```
$ terraform --version
Terraform v0.6.0-dev (2b9318651236807c29add41a9119c92f59bf58ba)
```

# Problem
I have had a number of issues getting security groups to reference each other, this one in particular I can't seem to get around. First I create three security groups, `nat`, `admin`, `bastion`. Second I allow all traffic from `nat` to `admin`. Third, allow all traffic from `bastion` to `admin`. This applies correctly on the first Terraform apply, but all other subsequent applies do not work properly.

### Plan
```
$ terraform plan
Refreshing Terraform state prior to plan...


The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

+ aws_security_group.admin
    description: "" => "admin security group"
    egress.#:    "" => "<computed>"
    ingress.#:   "" => "<computed>"
    name:        "" => "asgr2-admin"
    owner_id:    "" => "<computed>"
    tags.#:      "" => "1"
    tags.Name:   "" => "asgr2-admin"
    vpc_id:      "" => "${aws_vpc.vpc.id}"

+ aws_security_group.bastion
    description: "" => "bastion security group"
    egress.#:    "" => "<computed>"
    ingress.#:   "" => "<computed>"
    name:        "" => "asgr2-bastion"
    owner_id:    "" => "<computed>"
    tags.#:      "" => "1"
    tags.Name:   "" => "asgr2-bastion"
    vpc_id:      "" => "${aws_vpc.vpc.id}"

+ aws_security_group.nat
    description: "" => "nat security group"
    egress.#:    "" => "<computed>"
    ingress.#:   "" => "<computed>"
    name:        "" => "asgr2-nat"
    owner_id:    "" => "<computed>"
    tags.#:      "" => "1"
    tags.Name:   "" => "asgr2-nat"
    vpc_id:      "" => "${aws_vpc.vpc.id}"

+ aws_security_group_rule.admin_ingress_bastion
    from_port:                "" => "0"
    protocol:                 "" => "-1"
    security_group_id:        "" => "${aws_security_group.admin.id}"
    self:                     "" => "0"
    source_security_group_id: "" => "${aws_security_group.bastion.id}"
    to_port:                  "" => "0"
    type:                     "" => "ingress"

+ aws_security_group_rule.admin_ingress_nat
    from_port:                "" => "0"
    protocol:                 "" => "-1"
    security_group_id:        "" => "${aws_security_group.admin.id}"
    self:                     "" => "0"
    source_security_group_id: "" => "${aws_security_group.nat.id}"
    to_port:                  "" => "0"
    type:                     "" => "ingress"

+ aws_vpc.vpc
    cidr_block:                "" => "172.16.0.0/16"
    default_network_acl_id:    "" => "<computed>"
    default_security_group_id: "" => "<computed>"
    dhcp_options_id:           "" => "<computed>"
    enable_dns_hostnames:      "" => "1"
    enable_dns_support:        "" => "1"
    main_route_table_id:       "" => "<computed>"
    tags.#:                    "" => "1"
    tags.Name:                 "" => "asgr2-vpc"
```
### Apply
```
$ terraform apply
aws_vpc.vpc: Creating...
  cidr_block:                "" => "172.16.0.0/16"
  default_network_acl_id:    "" => "<computed>"
  default_security_group_id: "" => "<computed>"
  dhcp_options_id:           "" => "<computed>"
  enable_dns_hostnames:      "" => "1"
  enable_dns_support:        "" => "1"
  main_route_table_id:       "" => "<computed>"
  tags.#:                    "" => "1"
  tags.Name:                 "" => "asgr2-vpc"
aws_vpc.vpc: Creation complete
aws_security_group.bastion: Creating...
  description: "" => "bastion security group"
  egress.#:    "" => "<computed>"
  ingress.#:   "" => "<computed>"
  name:        "" => "asgr2-bastion"
  owner_id:    "" => "<computed>"
  tags.#:      "" => "1"
  tags.Name:   "" => "asgr2-bastion"
  vpc_id:      "" => "vpc-9eef65fb"
aws_security_group.nat: Creating...
  description: "" => "nat security group"
  egress.#:    "" => "<computed>"
  ingress.#:   "" => "<computed>"
  name:        "" => "asgr2-nat"
  owner_id:    "" => "<computed>"
  tags.#:      "" => "1"
  tags.Name:   "" => "asgr2-nat"
  vpc_id:      "" => "vpc-9eef65fb"
aws_security_group.admin: Creating...
  description: "" => "admin security group"
  egress.#:    "" => "<computed>"
  ingress.#:   "" => "<computed>"
  name:        "" => "asgr2-admin"
  owner_id:    "" => "<computed>"
  tags.#:      "" => "1"
  tags.Name:   "" => "asgr2-admin"
  vpc_id:      "" => "vpc-9eef65fb"
aws_security_group.bastion: Creation complete
aws_security_group.nat: Creation complete
aws_security_group.admin: Creation complete
aws_security_group_rule.admin_ingress_bastion: Creating...
  from_port:                "" => "0"
  protocol:                 "" => "-1"
  security_group_id:        "" => "sg-49ed032d"
  self:                     "" => "0"
  source_security_group_id: "" => "sg-4fed032b"
  to_port:                  "" => "0"
  type:                     "" => "ingress"
aws_security_group_rule.admin_ingress_nat: Creating...
  from_port:                "" => "0"
  protocol:                 "" => "-1"
  security_group_id:        "" => "sg-49ed032d"
  self:                     "" => "0"
  source_security_group_id: "" => "sg-48ed032c"
  to_port:                  "" => "0"
  type:                     "" => "ingress"
aws_security_group_rule.admin_ingress_bastion: Creation complete
aws_security_group_rule.admin_ingress_nat: Creation complete

Apply complete! Resources: 6 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate
```
### Statefile, after first apply
```
{
    "version": 1,
    "serial": 1,
    "modules": [
        {
            "path": [
                "root"
            ],
            "outputs": {},
            "resources": {
                "aws_security_group.admin": {
                    "type": "aws_security_group",
                    "depends_on": [
                        "aws_vpc.vpc"
                    ],
                    "primary": {
                        "id": "sg-49ed032d",
                        "attributes": {
                            "description": "admin security group",
                            "egress.#": "0",
                            "id": "sg-49ed032d",
                            "ingress.#": "0",
                            "name": "asgr2-admin",
                            "owner_id": "317085423413",
                            "tags.#": "1",
                            "tags.Name": "asgr2-admin",
                            "vpc_id": "vpc-9eef65fb"
                        }
                    }
                },
                "aws_security_group.bastion": {
                    "type": "aws_security_group",
                    "depends_on": [
                        "aws_vpc.vpc"
                    ],
                    "primary": {
                        "id": "sg-4fed032b",
                        "attributes": {
                            "description": "bastion security group",
                            "egress.#": "0",
                            "id": "sg-4fed032b",
                            "ingress.#": "0",
                            "name": "asgr2-bastion",
                            "owner_id": "317085423413",
                            "tags.#": "1",
                            "tags.Name": "asgr2-bastion",
                            "vpc_id": "vpc-9eef65fb"
                        }
                    }
                },
                "aws_security_group.nat": {
                    "type": "aws_security_group",
                    "depends_on": [
                        "aws_vpc.vpc"
                    ],
                    "primary": {
                        "id": "sg-48ed032c",
                        "attributes": {
                            "description": "nat security group",
                            "egress.#": "0",
                            "id": "sg-48ed032c",
                            "ingress.#": "0",
                            "name": "asgr2-nat",
                            "owner_id": "317085423413",
                            "tags.#": "1",
                            "tags.Name": "asgr2-nat",
                            "vpc_id": "vpc-9eef65fb"
                        }
                    }
                },
                "aws_security_group_rule.admin_ingress_bastion": {
                    "type": "aws_security_group_rule",
                    "depends_on": [
                        "aws_security_group.admin",
                        "aws_security_group.bastion"
                    ],
                    "primary": {
                        "id": "sg-4235098228",
                        "attributes": {
                            "cidr_blocks.#": "0",
                            "from_port": "0",
                            "id": "sg-4235098228",
                            "protocol": "-1",
                            "security_group_id": "sg-49ed032d",
                            "self": "false",
                            "source_security_group_id": "sg-4fed032b",
                            "to_port": "0",
                            "type": "ingress"
                        }
                    }
                },
                "aws_security_group_rule.admin_ingress_nat": {
                    "type": "aws_security_group_rule",
                    "depends_on": [
                        "aws_security_group.admin",
                        "aws_security_group.nat"
                    ],
                    "primary": {
                        "id": "sg-4235098228",
                        "attributes": {
                            "cidr_blocks.#": "0",
                            "from_port": "0",
                            "id": "sg-4235098228",
                            "protocol": "-1",
                            "security_group_id": "sg-49ed032d",
                            "self": "false",
                            "source_security_group_id": "sg-4fed032b",
                            "to_port": "0",
                            "type": "ingress"
                        }
                    }
                },
                "aws_vpc.vpc": {
                    "type": "aws_vpc",
                    "primary": {
                        "id": "vpc-9eef65fb",
                        "attributes": {
                            "cidr_block": "172.16.0.0/16",
                            "default_network_acl_id": "acl-4edc4c2b",
                            "default_security_group_id": "sg-4ded0329",
                            "dhcp_options_id": "dopt-05080167",
                            "enable_dns_hostnames": "true",
                            "enable_dns_support": "true",
                            "id": "vpc-9eef65fb",
                            "main_route_table_id": "rtb-0e19876b",
                            "tags.#": "1",
                            "tags.Name": "asgr2-vpc"
                        }
                    }
                }
            }
        }
    ]
}
```
Note that the `source_security_group_id` for `aws_security_group_rule.admin_ingress_bastion` AND `aws_security_group_rule.admin_ingress_nat` both say the same id (`sg-4fed032b`), which is incorrect. 
The one relating to `bastion` should say `sg-4fed032b` and the one relating to `nat` should say `sg-48ed032c`.
However, the rule was successfully applied. Screenshot from the AWS console directly after the first apply.
screen shot 2015-06-09 at 3 22 07 pm

### Apply, with no changes
```
$ terraform apply
aws_vpc.vpc: Refreshing state... (ID: vpc-9eef65fb)
aws_security_group.bastion: Refreshing state... (ID: sg-4fed032b)
aws_security_group.nat: Refreshing state... (ID: sg-48ed032c)
aws_security_group.admin: Refreshing state... (ID: sg-49ed032d)
aws_security_group_rule.admin_ingress_nat: Refreshing state... (ID: sg-4235098228)
aws_security_group_rule.admin_ingress_bastion: Refreshing state... (ID: sg-4235098228)
aws_security_group_rule.admin_ingress_nat: Destroying...
aws_security_group_rule.admin_ingress_nat: Destruction complete
aws_security_group_rule.admin_ingress_nat: Creating...
  from_port:                "" => "0"
  protocol:                 "" => "-1"
  security_group_id:        "" => "sg-49ed032d"
  self:                     "" => "0"
  source_security_group_id: "" => "sg-48ed032c"
  to_port:                  "" => "0"
  type:                     "" => "ingress"
aws_security_group_rule.admin_ingress_nat: Error: 1 error(s) occurred:

* Error authorizing security group rules rules: InvalidPermission.Duplicate: the specified rule "peer: sg-48ed032c, ALL, ALLOW" already exists
	status code: 400, request id: []
Error applying plan:

1 error(s) occurred:

* 1 error(s) occurred:

* 1 error(s) occurred:

* Error authorizing security group rules rules: InvalidPermission.Duplicate: the specified rule "peer: sg-48ed032c, ALL, ALLOW" already exists
	status code: 400, request id: []

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```
### Statefile diff, after failed apply
```diff
--- terraform.tfstate.backup Tue Jun  9 15:23:41 2015
+++ terraform.tfstate Tue Jun  9 15:23:41 2015
@@ -1,6 +1,6 @@
 {
     "version": 1,
-    "serial": 1,
+    "serial": 2,
     "modules": [
         {
             "path": [
@@ -89,27 +89,6 @@
                         }
                     }
                 },
-                "aws_security_group_rule.admin_ingress_nat": {
-                    "type": "aws_security_group_rule",
-                    "depends_on": [
-                        "aws_security_group.admin",
-                        "aws_security_group.nat"
-                    ],
-                    "primary": {
-                        "id": "sg-4235098228",
-                        "attributes": {
-                            "cidr_blocks.#": "0",
-                            "from_port": "0",
-                            "id": "sg-4235098228",
-                            "protocol": "-1",
-                            "security_group_id": "sg-49ed032d",
-                            "self": "false",
-                            "source_security_group_id": "sg-4fed032b",
-                            "to_port": "0",
-                            "type": "ingress"
-                        }
-                    }
-                },
                 "aws_vpc.vpc": {
                     "type": "aws_vpc",
                     "primary": {
```

I hope that wasn't TMI!
This might or might not relate to the other issue I just reported, #2291.

### PR DESCRIPTION
**Pull request by catsby**
Supersedes #2318
Fixes #2294

**Original message:**

Previously they would conflict you had multiple security group rules
with the same ingress or egress ports but different source security
groups because only the CIDR blocks were considered (which are empty
when using source security groups).

**Updates:**

- updated to include schema migration (from clint@ctshryock.com)

**Remediation:** If you encounter an error regarding duplicate rules, you will need to identify and manually remove the offending/missing security group rules from the Security Group, and re-plan and apply with Terraform.

### CODE REVIEW

**Comment by catsby** [comment]
This will clean up #2294. It will migrate people when possible, but there may still exist scenarios (like in 2294) where some manual cleanup will be necessary. The reason being that in the config given there, there are 2 rules created, but without considering the source group id in the hash, the state file will mistakenly have the same source id for both rules (clearly not the correct case).

**Comment by catsby** [comment]
cc @phinze for some review

**Comment by catsby** [comment]
> The reason being that in the config given there, there are 2 rules created, but without considering the source group id in the hash, the state file will mistakenly have the same source id for both rules (clearly not the correct case).

I should add this; remotely (on AWS) the rules are created correctly. They're simply stored locally in the state file incorrectly. This PR will migrate most cases ( I believe ) and prevent that in the future. 

Users with these conflicts can hit "Duplicate" errors. Manual clean up is needed, unless we swallow that error in the `create` method for the rule... but that seemed unsafe

File: builtin/providers/aws/resource_aws_security_group_rule.go [hunk 1]
```diff
@@ -263,15 +267,32 @@ func findResourceSecurityGroup(conn *ec2.EC2, id string) (*ec2.SecurityGroup, er
...
+func (b byUserIDAndGroup) Swap(i, j int) { b[i], b[j] = b[j], b[i] }
+func (b byUserIDAndGroup) Less(i, j int) bool {
+	if b[i].GroupID != nil && b[j].GroupID != nil {
+		return *b[i].GroupID < *b[j].GroupID
+	}
+	if b[i].GroupName != nil && b[j].GroupName != nil {
+		return *b[i].GroupName < *b[j].GroupName
+	}
+
+	panic("mismatched security group rules, may be a terraform bug")
```
Comment (phinze) [inline builtin/providers/aws/resource_aws_security_group_rule.go]: Can a user get to this panic by specifying a config improperly? Or are we protected by earlier validations from that?

File: builtin/providers/aws/resource_aws_security_group_rule.go [hunk 2]
```diff
@@ -263,15 +267,32 @@ func findResourceSecurityGroup(conn *ec2.EC2, id string) (*ec2.SecurityGroup, er
 	return resp.SecurityGroups[0], nil
 }
 
+// byUserIDAndGroup implements sort.Interface for []*ec2.UserIDGroupPairs based on
+// UserID and then the GroupID or GroupName field (only one should be set).
```
Comment (phinze) [inline builtin/providers/aws/resource_aws_security_group_rule.go]: This comment references UserID but the impl does not.

File: builtin/providers/aws/resource_aws_security_group_rule.go (hunk 1 above)
Comment (catsby) [inline builtin/providers/aws/resource_aws_security_group_rule.go]: I believe we're protected, but I'm honestly not 100% sure. @jszwedko wrote that part, and I meant to ask you @phinze about it. The `panic` makes me uneasy, but I'm not sure what's the consequences of omitting it are. Is there a more sane "default" fall through behavior?

File: builtin/providers/aws/resource_aws_security_group_rule.go (hunk 2 above)
Comment (catsby) [inline builtin/providers/aws/resource_aws_security_group_rule.go]: ah, I removed `UserID` since we don't set it (we ignore it completely) . I changed the method name and docs in 640836e

File: builtin/providers/aws/resource_aws_security_group_rule.go (hunk 1 above)
Comment (phinze) [inline builtin/providers/aws/resource_aws_security_group_rule.go]: Yeah let's just return false here, which will just sort last anything that's wonky looking, allowing later code to fail in a likely more meaningful way.

**Comment by zxjinn** [comment]
@catsby after running unmodified code I posted in #2294 against this branch, I still get the same error on the second apply :frowning: 
```
$ ~/code/go/bin/terraform --version
Terraform v0.6.0-dev (640836ee58d9d3e92a75f7c6e27953eb16e2f911)
```

**Comment by zxjinn** [comment]
@catsby Sorry false alarm! I forgot to update the symlink to point to  `~/code/go/bin/terraform`, I was still using the latest release when I ran that. :clap: thank you very much!

File: builtin/providers/aws/resource_aws_security_group_rule.go (hunk 1 above)
Comment (jszwedko) [inline builtin/providers/aws/resource_aws_security_group_rule.go]: I'd worry that just returning false might mask an error (though theoretically that line should never be hit). If we don't want to panic, I'd suggest at least sorting the bad data in a deterministic way (otherwise you could end up in a semi-permadiff situation).

Comment (jszwedko) [inline builtin/providers/aws/resource_aws_security_group_rule.go]: As a user of terraform, I'd personally prefer that it blow up than silently swallow this sort of error.

Comment (mitchellh) [inline builtin/providers/aws/resource_aws_security_group_rule.go]: One thing to keep in mind (a positive thing) is that Terraform _will_ recover panics that pop out of resource calls (as long as they're not from a goroutine _within_ that resource call) and still handle cleanup and partial state.

**Comment by catsby** [comment]
Thanks for checking it out @zxjinn , much appreciated. Sorry for the mess :smile:

File: builtin/providers/aws/resource_aws_security_group_rule.go [hunk 3]
```diff
@@ -122,18 +121,28 @@ func resourceAwsSecurityGroupRuleCreate(d *schema.ResourceData, meta interface{}
...
 		return fmt.Errorf("Security Group Rule must be type 'ingress' or type 'egress'")
 	}
 
+	if autherr != nil {
+		if awsErr, ok := autherr.(awserr.Error); ok {
+			if awsErr.Code() == "InvalidPermission.Duplicate" {
+				return fmt.Errorf(`[WARN] A duplicate Security Group rule was found. This may be 
+a side effect of a now-fixed Terraform issue causing two security groups with 
+identical attributes but different source_security_group_ids to overwrite each 
+other in the state. See https://github.com/hashicorp/teraform/pull/2376 for more
```
Comment (phinze) [inline builtin/providers/aws/resource_aws_security_group_rule.go]: s/teraform/terraform/ - probably my typo from earlier :stuck_out_tongue:

Comment (catsby) [inline builtin/providers/aws/resource_aws_security_group_rule.go]: IT'S ALL YOUR FAULT

**Comment by phinze** [comment]
LGTM

**Comment by jszwedko** [comment]
:clap: thanks @catsby !

**Comment by marshallpierce** [comment]
I'm on terraform 0.6.0 and I'm seeing the error warning me about this issue. This happens the first time I apply my infrastructure. Looks like this was merged before 0.6.0, so am I perhaps seeing a different issue?

**Comment by jtchoi** [comment]
We have two rules referencing the same port and security group, but differing protocols.  I believe in this case there should not be a duplicate but terraform 0.6.1 treats them as separate

**Comment by JeanMertz** [comment]
Just had this happen to me as well, using the latest Terraform stable version at this moment.

I already deleted all things manually, so don't have a log right now, but definitely saw this with  ~5 security group resources – which don't have a cidr block – during my run.

**Comment by samprakos** [comment]
This happens to me still with the latest build (v0.6.4-dev).

**Comment by jszwedko** [comment]
@SamClinckspoor can you post some example configuration reproducing?

**Comment by SamClinckspoor** [comment]
@jszwedko wrong person :wink:

**Comment by jszwedko** [comment]
Oops! @samprakos ^^

**Comment by samprakos** [comment]
I don't believe I'd be able to reproduce it on demand...I fixed the 18 errors by manually deleting the rules from aws and re-running Terraform plan/apply.  It's almost as though the security group ids in aws all of a sudden didn't align with the ones in the tfstate file.

**Comment by jszwedko** [comment]
@samprakos that is probably different from this issue then.

**Comment by catsby** [comment]
I recently opened https://github.com/hashicorp/terraform/pull/3019 to do further refactoring of Security Group rules. If you're interested in trying it out, I would recommend a test setup, as there's a schema migration and I don't know how easy that would be to roll back.

**Comment by dgarlitt** [comment]
Is there a work-around for this issue in the meantime? I get the "duplicate Security Group rule" error when trying to apply the following resources:

```go
resource "aws_security_group_rule" "all-master-to-master" {
  type = "ingress"
  security_group_id = "${aws_security_group.masters-k8s.id}"
  self = true
  from_port = 0
  to_port = 0
  protocol = "-1"
}

resource "aws_security_group_rule" "all-master-to-node" {
  type = "ingress"
  security_group_id = "${aws_security_group.nodes-k8s.id}"
  source_security_group_id = "${aws_security_group.masters-k8s.id}"
  from_port = 0
  to_port = 0
  protocol = "-1"
}
```

**Comment by gtmtech** [comment]
Still getting this on terraform 0.7.5 >.<

**Comment by gtmtech** [comment]
Ah I tracked it down - in my case I was rewiring two aws_subnets, subnet A, and subnet B, and swapping their CIDR blocks. On some terraform apply's it would say it couldnt create the subnet because the CIDR already existed (one bug - terraform isnt intelligent enough to handle this situation) - on another run it complained:

```
* aws_security_group_rule.egress8080loadbalancer: [WARN] A duplicate Security Group rule was found on (sg-9d5c8ffb). This may be
a side effect of a now-fixed Terraform issue causing two security groups with
identical attributes but different source_security_group_ids to overwrite each
other in the state. See https://github.com/hashicorp/terraform/pull/2376 for more
information and instructions for recovery. Error message: the specified rule "peer: 10.128.10.0/24, TCP, from port: 8080, to port: 8080, ALLOW" already exists
* aws_security_group_rule.ingress8080loadbalancer: [WARN] A duplicate Security Group rule was found on (sg-67439001). This may be
a side effect of a now-fixed Terraform issue causing two security groups with
identical attributes but different source_security_group_ids to overwrite each
other in the state. See https://github.com/hashicorp/terraform/pull/2376 for more
information and instructions for recovery. Error message: the specified rule "peer: 10.128.10.0/24, TCP, from port: 8080, to port: 8080, ALLOW" already exists
```

Which would be the case because the subnets are swapping around and order is important. 

In such cases like these the only appropriate thing would be to delete all subnets first, and all SG first and then recreate. Its more advanced logic than terraform currently has, but this would cater for this suite of problems

**Comment by shailendersingh2** [comment]
I am facing same error where i already have SG with specific CIDR block but when my terrafrom aplly command  gives same duplicate error and quits during terraform apply. I can't delete existing rule because it was already present and PRD data communication is happening and i need functionality to just ignore if it is already present and i used lifecycle {ignore_changed = "subnetname"} that not helped me so why it can't just ignore if security group CIDR already present.

**Comment by genevievelesperance** [comment]
Is there a way to migrate from inline security group rules to `aws_security_group_rule` resources? We want the same rules but external from the security group so that we can conditionally create new rules for a particular source security group.

**Comment by korfuri** [comment]
I think I was confused in my response above, and that's not possible.
You may be able to do something like: (1) back up your state (2) Write down the security group's ID and `terraform state rm` it (3) change your config to use non-inline rules (4) `terraform import` your security group again. The rules will be imported as their own resources, with arbitrary paths. (5) `terraform state mv` each rule into its proper location.

**Comment by maliaoreta** [comment]
YES that worked!!!
Thank you so much!!! Especially for such a quick response!

Have a good one!

**Comment by alkalinecoffee** [comment]
We're seeing this issue (`Terraform v0.11.7`, `provider.aws v1.29.0`) when modifying a security group rule with new IP ranges.  The security group config has no in-line rules--all rules are defined in `aws_security_group_rule` resources.

We've commented out all of our `aws_security_group_rule` resources, applied (so the security group has no rules attached), removed the security group from state, re-imported, uncommented and re-applied all of the rules.  This works fine, until we need to add a new rule, which results in the duplicate error.

Steps to reproduce (let's call the security group `infra`)...

1. Clear out existing rules from security group and state:
  - Comment out rules in config
  - `tf apply` (security group now has no rules)
  - `tf state list`
  - `tf state show sg-123456`
2. Remove the SG from state and re-add:
  - `tf state rm module.ci.aws_security_group.infra`
  - `tf import tf module.ci.aws_security_group.infra sg-123456`
3. Inspect state of resource to ensure rules are empty
  - `tf state show module.ci.aws_security_group.infra`
4. Re-add security groups removed from Step 1
  - Uncomment security group rules in config
  - `tf apply`
5. Add a new IP range to one of the rules and `tf apply` ... which results in failure
```

**Comment by alkalinecoffee** [comment]
Following up on the message above...

We had the following lifecycle in our security group rule configs:

```
lifecycle {
  create_before_destroy = true
}
```

It seems obvious now, but removing this lifecycle config avoids the duplicate warning.

We initially had this lifecycle policy in place as we ran into an issue where a bad `terraform apply` left our security groups in a bad state which resulted in blocked traffic.  But it seems that overall, having this policy in place is inherently incompatible with the strict duplication rules applied to security group rules.

I'm not sure what the resolution is here, or if this issue belongs in this thread or a new one should be opened.  We want to continue using the lifecycle for the reason above, but it also prevents us from easily managing our SG rules.

**Comment by ndp-stc** [comment]
Using terraform 0.11.8 and 0.11.10, both give me this error. I am not using create_before_destroy. All rules are separate (not inline) resources.

This seems to occur for me every time I use TF to push a change to any security group rule.

I also attempted to use timestamp() in rule descriptions; hoping that this would force attributes to be unique for each application of each rule - but it still reports this error. Which means that the description attribute is NOT part of the hash. 

I tried deleting all security group rules, (both manually, and using terraform apply) - and that did not fix this problem.

I tried using terraform state rm for the security group rule resources in state - but that didn't fix the problem, because terraform will no longer update those rules, so the state will never get refreshed with the rule state.  `terraform state list | grep aws_security_group_rule ` returns nothing after a re-apply.

The text of the error message makes no sense, because when it's applying to a "source security group id" - it then says that the duplicate rule is for a cidr range, not a source id. (you can not specify a source security group id, when you're specifying a cidr range).

The only eventual workaround was to delete all of the existing rules by hand in aws console, then re-apply the new terraform rules. (though I suppose this could probably be automated with aws cli).

**Comment by neechbear** [comment]
@ndp-stc's suggestion above seemed to be a viable workaround for me, but I needed to tweak the method very slightly. Maybe the taint syntax changed slightly or my nested modules complicate issues, .. not sure?

This seemed to give me all the terraform commands I needed to fix my problem:

```
while read -r addr
do
  if [[ "$addr" == "module."** ]]
  then
    module="${addr%.*.*}"
    addr="${addr#$module.}"
    echo terraform taint -module="${module//module./}" "$addr"
  else
    echo terraform taint "$addr"
  fi
done < <(terraform state list | grep "aws_security_group_rule")
```

**Comment by StubbsPKS** [comment]
Even following the workaround by @neechbear didn't help me with this issue. I was able to successfully taint everything, but upon apply TF just gave me the same error again.
