### PR TITLE
consul: Fix several problems w/ consul_keys update

### LINKED ISSUE #774: Terraform does not update consul values in consul
I have a module that declares a few consul values (it receives the values as input parameters)
I ran terraform and it created the keys and and values in consul.
If i change an input parameter that is mapped to a consul value and run terraform again, it will not update the value in consul.

### LINKED ISSUE #1866: tf 0.5.0 :: Resource "template_file" instance :: "diffs didn't match during apply" bug
I'm being told by Terraform that I should report a bug. Details below.

```
$ terraform --version
Terraform v0.5.0

$ consul --version
Consul v0.5.0
Consul Protocol: 2 (Understands back to: 1)

$ terraform apply
template_file.deployment: Creating...
  filename:                      "" => "deployment.json"
  rendered:                      "" => "<computed>"
  vars.#:                        "0" => "2"
  vars.application_name:         "" => "bootstrap"
  vars.deployment_configuration: "" => "default"
template_file.deployment: Creation complete
consul_keys.application_service: Creating...
  datacenter:            "" => "<computed>"
  key.#:                 "" => "1"
  key.449824328.default: "" => ""
  key.449824328.delete:  "" => "0"
  key.449824328.name:    "" => "deployment"
  key.449824328.path:    "" => "node/deployment"
  key.449824328.value:   "" => "{\n    \"application_name\": \"bootstrap\",\n    \"deployment_configuration\": \"default\"\n}\n"
  var.#:                 "" => "<computed>"
consul_keys.application_service: Creation complete

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate

$ terraform apply
template_file.deployment: Refreshing state... (ID: 8cca96a9cc6f7174f1a2)
consul_keys.application_service: Refreshing state... (ID: consul)
template_file.deployment: Creating...
  filename:                      "" => "deployment.json"
  rendered:                      "" => "<computed>"
  vars.#:                        "0" => "2"
  vars.application_name:         "" => "bootstrap"
  vars.deployment_configuration: "" => "default"
template_file.deployment: Creation complete
Error applying plan:

1 error(s) occurred:

* 1 error(s) occurred:

* consul_keys.application_service: diffs didn't match during apply. This is a bug with Terraform and should be reported.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

$cat application_service.tf 
variable "application_name" {
    default = "bootstrap"
}

variable "deployment_configuration" {
    default = "default"
}

# add node's configuration to consul
resource "template_file" "deployment" {
    filename = "deployment.json"
    vars {
       application_name = "${var.application_name}"
       deployment_configuration = "${var.deployment_configuration}"
    }
}

resource "consul_keys" "application_service" {

    key {
        name = "deployment"
        path = "node/deployment"
        value = "${template_file.deployment.rendered}"
    }
}
```

### LINKED ISSUE #3023: `consul_keys` intermittently returns a Terraform error on `terraform apply`
I've been received this error message lately:

```
Error applying plan:

2 error(s) occurred:

* consul_keys.dashboard_keys: diffs didn't match during apply. This is a bug with Terraform and should be reported.
* consul_keys.scribe_keys: diffs didn't match during apply. This is a bug with Terraform and should be reported.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

EDIT: ~~The odd part is it seems that the consul_keys are being updated properly.~~  The reproducing criteria seems to be having consul_key values that depend on another resource (say an aws_instance dns name) and the resource needs to be recreated, therefore the consul_keys need to be refreshed.

EDIT:  Spoke too soon.  The consul_keys did not change correctly.

Hope this helps.

### PR DESCRIPTION
**Pull request by phinze**
Implementation notes:

 * The hash implementation was not considering key value, causing "diffs
   did not match" errors when a value was updated. Switching to default
   HashResource implementation fixes this
 * Using HashResource as a default exposed a bug in helper/schema that
   needed to be fixed so the Set function is picked up properly during
   Read
 * Stop writing back values into the `key` attribute; it triggers extra
   diffs when `default` is used. Computed values all just go into `var`.
 * Includes a state migration to prevent unnecessary diffs based on
   "key" attribute hashcodes changing.

In the tests:

 * Switch from leaning on the public demo Consul instance to requiring a
   CONSUL_HTTP_ADDR variable be set pointing to a `consul agent -dev`
   instance to be used only for testing.
 * Add a test that exposes the updating issues and covers the fixes

Fixes #774
Fixes #1866
Fixes #3023

### CODE REVIEW

File: helper/schema/field_writer_map.go [hunk 1]
```diff
@@ -277,7 +277,7 @@ func (w *MapFieldWriter) setSet(
 		// not the `value` directly is because this forces all types
 		// to become []interface{} (generic) instead of []string, which
 		// most hash functions are expecting.
-		s := &Set{F: schema.Set}
```
Comment (apparentlymart) [inline helper/schema/field_writer_map.go]: Oh my... this must've been lurking here since I did the refactoring that added `schema.ZeroValue` months ago. Sorry about that!

Curious to see if this will fix weird quirky behavior with *other* resources that use the default hash implementation. I know a few times I've seen "diffs don't match" errors that I then failed to reproduce, and it seems plausible that this would be the cause for at least some of them...

**Comment by apparentlymart** [comment]
This LGTM!

Presumably changing the set hash function is going to cause Terraform to see all of the set items as changed, which will cause some extra diff noise but otherwise not do anything bad I think.

Not setting the `value` in the `keys` blocks also seems like a minor breaking change, but I can confirm that at least for my part I've never depended on that being set since it's always been more convenient to use `var.whatever`.

File: helper/schema/field_writer_map.go (hunk 1 above)
Comment (phinze) [inline helper/schema/field_writer_map.go]: No worries! I think this may be the first TypeSet using the default implementation that gets written, since the behavior I saw was a nil reference panic, and we definitely would have noticed that elsewhere.

**Comment by phinze** [comment]
Thanks for the review, @apparentlymart! Did another pass on the code and ended up deciding to set back `datacenter` since it can be interpreted from the provider, so it can be used as a reference field.

> Presumably changing the set hash function is going to cause Terraform to see all of the set items as changed, which will cause some extra diff noise but otherwise not do anything bad I think.

Good point. The proper thing to do here would be a state migration. I'll look into that.

> Not setting the value in the keys blocks also seems like a minor breaking change

Yeah, I think you're right about it being a breaking change. The prior behavior was extra diffs when using default, though, so it's basically a `fix`. I'll call this out in the CHANGELOG when this gets merged so it's clear.

**Comment by phinze** [comment]
Okay I followed up with a state migration so the only BC-notable change is that "value" will no longer be updated.

@apparentlymart PTAL when you have the chance
@mitchellh would appreciate eyes on the state migration function - after floundering a bit trying to manually munge `map[string]string`s, i ended up using the field reader/writers which worked out pretty okay

**Comment by mitchellh** [comment]
LGTM!

**Comment by apparentlymart** [comment]
Belated LGTM :grinning:
