### PR TITLE
provider/digitalocean: prevent new resources when using ID's of image…

### LINKED ISSUE #12255: DigitalOcean infinite apply loop (forces new resource)
Hi there,

### Terraform Version
v0.8.7

### Affected Resource(s)
- digitalocean_droplet

### Terraform Configuration Files
```hcl
resource digitalocean_droplet stage_server {
  image = "22995881" //ubuntu 16.04 with docker 1.13.1
  name = "test"
  region = "nyc1"
  size = "512mb"
}
```

### Expected Behavior
After a successful `terraform apply`, running `terraform plan` should show
```
Plan: 0 to add, 0 to change, 0 to destroy.
```

### Actual Behavior
It shows
```
Plan: 1 to add, 0 to change, 1 to destroy.
```

### Steps to Reproduce
1. `terraform apply`
2. `terraform plan`

### Possible solution
I think I found where it can be fixed ([See code](https://github.com/hashicorp/terraform/blob/master/builtin/providers/digitalocean/resource_digitalocean_droplet.go#L253-L257))
What happens is that digitalocean_droplet.**image** accepts an **id** or **slug** ([See in docs](https://www.terraform.io/docs/providers/do/r/droplet.html#image))... the specific image I am using offers both options

As the code a mentioned above prefers **slug** over **id**, terraform saves the state container image "ubuntu-16.04"... when running `terraform plan` it displays

image

Despite of just have created the resource, terraform thinks it needs to be updated

**PS: Simply inverting the if code, to prefer ids over slugs won't solve the problem**

### PR DESCRIPTION
**Pull request by roidelapluie**
…s with slugs

When you specify the ID of an image that has a slug, terraform would
store its slug to the state, hence it would always recreate the image.

This commit fixes it by storing the image as an ID when it is specified
by and ID by the user, ignoring the slug.

Closes #12751.
Fixes #12255.

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by roidelapluie** [comment]
ACCEPTANCE TESTS WITH TESTS ONLY (test_droplet.go)
```
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/04/23 18:04:19 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/digitalocean -v -run=TestAccDigitalOceanDroplet_WithID -timeout 120m
=== RUN   TestAccDigitalOceanDroplet_WithID
--- FAIL: TestAccDigitalOceanDroplet_WithID (38.42s)
        testing.go:280: Step 0 error: After applying this step, the plan was not empty:

                DIFF:

                DESTROY/CREATE: digitalocean_droplet.foobar
                  disk:                 "20" => "<computed>"
                  image:                "centos-7-x64" => "22995941" (forces new resource)
                  ipv4_address:         "45.55.154.238" => "<computed>"
                  ipv4_address_private: "" => "<computed>"
                  ipv6_address:         "" => "<computed>"
                  ipv6_address_private: "" => "<computed>"
                  locked:               "false" => "<computed>"
                  name:                 "foo-4889334322092258525" => "foo-4889334322092258525"
                  price_hourly:         "0.00744" => "<computed>"
                  price_monthly:        "5" => "<computed>"
                  region:               "nyc3" => "nyc3"
                  resize_disk:          "true" => "true"
                  size:                 "512mb" => "512mb"
                  status:               "active" => "<computed>"
                  user_data:            "foobar" => "foobar"
                  vcpus:                "1" => "<computed>"

                STATE:

                digitalocean_droplet.foobar:
                  ID = 46676585
                  disk = 20
                  image = centos-7-x64
                  ipv4_address = 45.55.154.238
                  locked = false
                  name = foo-4889334322092258525
                  price_hourly = 0.00744
                  price_monthly = 5
                  region = nyc3
                  resize_disk = true
                  size = 512mb
                  status = active
                  tags.# = 0
                  user_data = foobar
                  vcpus = 1
FAIL
exit status 1
FAIL    github.com/hashicorp/terraform/builtin/providers/digitalocean   38.429s
make: *** [Makefile:49: testacc] Error 1
```



ACCEPTANCE TESTS WITH ALL CHANGES (droplet_test.go + droplet.go)

```
make testacc TEST=./builtin/providers/digitalocean TESTARGS='-run=TestAccDigitalOceanDroplet_WithID'  
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/04/23 18:02:16 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/digitalocean -v -run=TestAccDigitalOceanDroplet_WithID -timeout 120m
=== RUN   TestAccDigitalOceanDroplet_WithID
--- PASS: TestAccDigitalOceanDroplet_WithID (50.56s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/digitalocean   50.564s
```


I also ran the basic test:

```
make testacc TEST=./builtin/providers/digitalocean TESTARGS='-run=TestAccDigitalOceanDroplet_Basic'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/04/23 18:16:05 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/digitalocean -v -run=TestAccDigitalOceanDroplet_Basic -timeout 120m
=== RUN   TestAccDigitalOceanDroplet_Basic
--- PASS: TestAccDigitalOceanDroplet_Basic (49.30s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/digitalocean   49.308s
```

**Comment by roidelapluie** [comment]
There might be a problem when switching from a snapshot to a distro

**Comment by roidelapluie** [comment]
fixed.

**Comment by roidelapluie** [comment]
current status: ready for review & merge

File: builtin/providers/digitalocean/resource_digitalocean_droplet_test.go [hunk 1]
```diff
@@ -46,6 +46,31 @@ func TestAccDigitalOceanDroplet_Basic(t *testing.T) {
...
+				Config: testAccCheckDigitalOceanDropletConfig_withID(centosID, rInt),
+				Check: resource.ComposeTestCheckFunc(
+					testAccCheckDigitalOceanDropletExists("digitalocean_droplet.foobar", &droplet),
+				),
+				Destroy: false,
+			},
+			{
+				Config:   testAccCheckDigitalOceanDropletConfig_withID(centosID, rInt),
+				PlanOnly: true,
+			},
```
Comment (radeksimko) [inline builtin/providers/digitalocean/resource_digitalocean_droplet_test.go]: We actually refresh the state as part of every test step, so this is not necessary - would you mind removing the second step + `Destroy: false`?

**Comment by roidelapluie** [comment]
done

**Comment by radeksimko** [comment]
@roidelapluie thanks for sending the other PR, would you mind modifying this PR/test too and resolving conflicts?

Thanks

**Comment by roidelapluie** [comment]
done
