### PR TITLE
missing args assignment after parsing flags

### LINKED ISSUE #12423: New terraform env list command not working
Hi there,

### Terraform Version
```
% terraform version
Terraform v0.9.0-dev (452f47ce8c4a4eb24d7e188287bdd73be67915d5+CHANGES)
```

### Affected Resource(s)

```
% terraform env list .
Too many command line arguments. Configuration path expected.
% terraform env list
Too many command line arguments. Configuration path expected.
% terraform env list --help
Usage: terraform env list [DIR]

  List Terraform environments.
```

the env new subcommand seems to work

### PR DESCRIPTION
**Pull request by jbardin**
`env list` was missing the args re-assignment after parsing the flags.
This is only a problem if the variables are automatically populated
as arguments from a tfvars file.

Fixes #12423

### CODE REVIEW

File: command/env_command_test.go [hunk 1]
```diff
@@ -64,6 +64,16 @@ func TestEnv_createAndList(t *testing.T) {
...
 
+	// make sure a vars file doesn't interfere
+	err := ioutil.WriteFile(
+		DefaultVarsFilename,
+		[]byte(`foo = "bar"`),
+		0644,
+	)
+	if err != nil {
+		t.Fatal(err)
+	}
```
Comment (mitchellh) [inline command/env_command_test.go]: I'd prefer doing a `testChdir` here and changing to a temp dir. Easier/cleaner to guarantee a clean environment that way.

Comment (jbardin) [inline command/env_command_test.go]: I'm confused, this test does use `testChdir` and `os.RemoveAll` to clean up

Comment (mitchellh) [inline command/env_command_test.go]: Oh whoops I misread the test comment thinking you were writing a blank vars file. Looks good!
