### PR TITLE
command: Fix state mv for only resource in module

### LINKED ISSUE #25520: terraform state mv panic
### Terraform Version

```
Terraform v0.12.24
+ provider.archive v1.3.0
+ provider.aws v2.69.0
+ provider.cloudflare v2.6.0
+ provider.local v1.4.0
+ provider.template v2.1.2
```

Updated to the current major version without success:

```
Terraform v0.12.28
+ provider.archive v1.3.0
+ provider.aws v2.69.0
+ provider.cloudflare v2.6.0
+ provider.local v1.4.0
+ provider.template v2.1.2
```

### Terraform Configuration Files
[crash.log](https://github.com/hashicorp/terraform/files/4891851/crash.log)

### Steps to Reproduce

I first moved a map of zones to a non existent resource:

```
terraform state mv 'cloudflare_zone.zones' 'module.cloudflare.cloudflare_zone.zones'
```

Then I tried to correct the mistake I made and terraform panics.

```
terraform state mv 'module.cloudflare.cloudflare_zone.zones' 'module.cloudflare.cloudflare_zone.this'
```

### PR DESCRIPTION
**Pull request by alisdair**
When moving a resource block with multiple instances to a new address within the same module, we need to ensure that the target module is present as late as possible. Otherwise, deleting the resource from the original address triggers pruning, and the module is removed just before we try to add the resource to it, which causes a crash.

Includes regression test which panics without this code change.

Fixes #25520

### CODE REVIEW

File: command/state_mv.go [hunk 1]
```diff
@@ -223,7 +220,7 @@ func (c *StateMvCommand) Run(args []string) int {
 
 				// Update the address before adding it to the state.
 				rs.Addr = addrTo
-				stateTo.Module(addrTo.Module).Resources[addrTo.Resource.String()] = rs
+				stateTo.EnsureModule(addrTo.Module).Resources[addrTo.Resource.String()] = rs
```
Comment (mildwonkey) [inline command/state_mv.go:223]: I like that this also clears up a bit of redundancy (more like unnecessary code) since EnsureModule is safe to run in place of Module (here, that is)!
