### PR TITLE
Unmark values before showing in JSON

### LINKED ISSUE #26737: terraform show -json not displaying sensitive values
### Terraform Version

```
v0.14.0
```

### Terraform Configuration Files

```terraform
variable "cat" {
  default   = "cat"
  sensitive = true
}

resource "random_pet" "bar" {
  prefix = var.cat
}

```

### Expected Behavior

Since `show -json` explicitly asks to show the value, we should show it.
```
{"format_version":"0.1","terraform_version":"0.14.0","values":{"outputs":{"out":{"sensitive":true,"value":"cat"}},"root_module":{"resources":[{"address":"random_pet.bar","mode":"managed","type":"random_pet","name":"bar","provider_name":"registry.terraform.io/hashicorp/random","schema_version":0,"values":{"id":"cat-quick-sunbird","keepers":null,"length":2,"prefix":"cat","separator":"-"}}]}}}
```

### Actual Behavior

```

{"format_version":"0.1","terraform_version":"0.14.0","values":{"root_module":{"resources":[{"address":"random_pet.bar","mode":"managed","type":"random_pet","name":"bar","provider_name":"registry.terraform.io/hashicorp/random","schema_version":0,"values":{"id":"cat-quick-sunbird","keepers":null,"length":2,"prefix":null,"separator":"-"}}]}}}

```

### Steps to Reproduce

1. terraform apply
2. terraform show

### PR DESCRIPTION
**Pull request by pselle**
This prevents "sensitive" values from unintentionally showing as nil when running terraform show -json. Also adjusts the signature of a function to remove an unused argument.

Closes #26737

### CODE REVIEW

File: command/jsonstate/state.go [hunk 1]
```diff
@@ -100,7 +99,10 @@ type resource struct {
 // resource, whose structure depends on the resource type schema.
 type attributeValues map[string]interface{}
 
-func marshalAttributeValues(value cty.Value, schema *configschema.Block) attributeValues {
+func marshalAttributeValues(value cty.Value) attributeValues {
```
Comment (alisdair) [inline command/jsonstate/state.go:102]: I appreciate this incidental clean-up! 🙏

**Review by alisdair — APPROVED** [review]
Looks good to me!
