### PR TITLE
core: build a test apply graph during plan

### LINKED ISSUE #30407: Terraform graph does not produce cycles while apply does
### Terraform Version

```
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/google v4.7.0
+ provider registry.terraform.io/hashicorp/google-beta v4.7.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/innovationnorway/git v0.1.3
+ provider registry.terraform.io/kreuzwerker/docker v2.15.0
+ provider registry.terraform.io/terraform-providers/docker v2.7.2
```

### Terraform Configuration Files

https://gist.github.com/AndreasBergmeier6176/e8adeaa87a54841e64e27bf2393570ec/c617710775bbcbf951ff0f537ed55ed0730419eb

### Debug Output

https://gist.github.com/AndreasBergmeier6176/e8adeaa87a54841e64e27bf2393570ec/575b19cf89a98dae85c1596dc248c5e60c91c708

### Expected Behavior

If there really is a cycle, `terraform graph -type=apply -draw-cycles` should display it.

### Actual Behavior

`terraform apply` complains:

> Error: Cycle: module.c.google_compute_instance_template.pull (destroy deposed 83fe0757),
module.o.google_compute_instance_template.integration_test,
<...>

`terraform graph -type=apply -draw-cycles | grep red` finds no edge.

See https://gist.github.com/AndreasBergmeier6176/e8adeaa87a54841e64e27bf2393570ec/91b48e52dc6d95dd801e857986015b1e396e8103

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

and

1. `terraform init`
2. `terraform graph -type=apply -draw-cycles`

### PR DESCRIPTION
**Pull request by jbardin**
The plan graph does not contain all the information necessary to detect
cycles which may happen when building the apply graph. Once we have more
information from the plan we can build the complete apply graph with all
individual instances to verify that the apply can begin without errors.

This gives better feedback for users, allowing them to detect more problems
when running `plan` which would otherwise not be detected until `apply`.

Closes #30407

### CODE REVIEW

File: internal/terraform/context_plan2_test.go [hunk 1]
```diff
@@ -2964,6 +2964,58 @@ output "a" {
...
+			addrs.NewDefaultProvider("test"): testProviderFuncFixed(p),
+		},
+	})
+
+	_, diags := ctx.Plan(m, state, &PlanOpts{
+		Mode: plans.NormalMode,
+	})
+	if !diags.HasErrors() {
+		t.Fatal("cycle error not detected")
+	}
```
Comment (apparentlymart) [inline internal/terraform/context_plan2_test.go:3016]: Should we also check here that one of the errors has a summary that starts with "Cycle"?

I don't really like sniffing error message text like that, but this test is exercising basically the whole of Terraform Core so seems likely that this test would end up eventually hitting some other sort of error that's unrelated to what it's trying to test for and thus masking the test for the problem it was originally aimed at.

**Review by apparentlymart — APPROVED** [review]
Nice!

An inline question about test robustness, but otherwise this looks great... nice and simple.

File: internal/terraform/context_plan2_test.go (hunk 1 above)
Comment (jbardin) [reply internal/terraform/context_plan2_test.go:3016]: yeah, that seems reasonable for testing purposes 👍
