### PR TITLE
fix windows locks

### LINKED ISSUE #12012: terraform init fails on windows (v0.9.0-beta1)
### Terraform Version
    Terraform v0.9.0-beta1 (4e96da57eef7b1bfd6e2752839e897f932752656)

### Terraform Configuration Files
```hcl
terraform {
    backend "local" {
        path = "terraform.tfstate"
    }
}
````

### Debug Output
(pasting here as it's tiny)
````
2017/02/16 16:21:36 [INFO] Terraform version: 0.9.0 beta1 4e96da57eef7b1bfd6e2752839e897f932752656
2017/02/16 16:21:36 [INFO] CLI args: []string{"C:\\temp\\tt\\terraform.exe", "init"}
2017/02/16 16:21:36 [DEBUG] Attempting to open CLI config file: C:\Users\erikb\AppData\Roaming\terraform.rc
2017/02/16 16:21:36 [INFO] CLI command args: []string{"init"}
2017/02/16 16:21:36 [DEBUG] command: loading backend config file: C:\temp\tt
Initializing the backend...
2017/02/16 16:21:36 [DEBUG] command: no data state file found for backend config
2017/02/16 16:21:36 [DEBUG] New state was assigned lineage "726d6303-d03f-4261-af9a-184a0bd9c739"
2017/02/16 16:21:36 [DEBUG] New state was assigned lineage "722c6d27-a0d0-488d-a8f6-c7ade089aaa1"
2017/02/16 16:21:36 [TRACE] Preserving existing state lineage "722c6d27-a0d0-488d-a8f6-c7ade089aaa1"

Error saving the backend configuration: Failed to write state: write C:\temp\tt\.terraform\terraform.tfstate: The process cannot access the file because another process has locked a portion of the file.

Terraform saves the complete backend configuration in a local file for
configuring the backend on future operations. This cannot be disabled. Errors
are usually due to simple file permission errors. Please look at the error
above, resolve it, and try again.

2017/02/16 16:21:36 [DEBUG] plugin: waiting for all plugin processes to complete...
````

### Expected Behavior
Terraform should have initialized the remote backend.

### Actual Behavior
Terraform can't initialize the backend, as it thinks the file is locked.

### Steps to Reproduce
1. `terraform init`

### Important Factoids
Tried on Windows 10, Windows Server 2012R2 (both domain joined) and a fresh Windows Server 2016 in AWS. Same result.
Using Bash on Ubuntu on Windows it doesn't throw the error.

### PR DESCRIPTION
**Pull request by jbardin**
Don't create a second windows handle for the lock file.
Fixes #12012

### CODE REVIEW

File: state/local_lock_windows.go [hunk 1]
```diff
@@ -75,16 +41,8 @@ func (s *LocalState) lock() error {
...
-
-	handle, ok := lockedFiles[s.stateFileOut]
-	if !ok {
-		// we allow multiple Unlock calls
-		return nil
-	}
-	delete(lockedFiles, s.stateFileOut)
-	return syscall.Close(handle)
+	// the file is closed in Unlock
+	return nil
```
Comment (mitchellh) [inline state/local_lock_windows.go]: What does this mean? We are unlocked automatically on file close? When does that happen?

Comment (jbardin) [inline state/local_lock_windows.go]: Oh yes, file is unocked when the associated handle is closed. This happens automatically when Close is called in the main Unlock method.

Comment (mitchellh) [inline state/local_lock_windows.go]: Gotcha. Looks great!
