### PR TITLE
provider/azurerm: Locking around Network Security Group / Subnets

### LINKED ISSUE #7986: Status=429 Code="RetryableError" Message="A retryable error occured."
I think this might be related with this issue https://github.com/hashicorp/terraform/issues/7153 I'm open it to provide more information about it and to keep separate from that issue.
### Terraform Version

Terraform v0.7.0
### Affected Resource(s)
- azurerm_subnet
### Terraform Configuration Files

[link](https://gist.github.com/zot24/f6186a1c96ebca2780cf64968efddb89)
### Debug Output

[link](https://gist.github.com/zot24/5973e55c59779a3d286e7c09eac1a651)
### Standard Output

```
Error applying plan:

1 error(s) occurred:

* azurerm_subnet.mod: network.SubnetsClient#CreateOrUpdate: Failure responding to request: StatusCode=429 -- Original Error: autorest/azure: Service returned an error. Status=429 Code="RetryableError" Message="A retryable error occured." Details=[{"code":"ReferencedResourceNotProvisioned","message":"Cannot proceed with operation because resource /subscriptions/614e4618-7e10-4847-be48-a61acdbadff1/resourceGroups/testm1_resource_group_1/providers/Microsoft.Network/networkSecurityGroups/testm1_network_security_group_1 used by resource /subscriptions/614e4618-7e10-4847-be48-a61acdbadff1/resourceGroups/testm1_resource_group_1/providers/Microsoft.Network/virtualNetworks/testm1_virtual_network_1/subnets/testm1_subnet_1 is not in Succeeded state. Resource is in Updating state and the last operation that updated/is updating the resource is PutSecurityRuleOperation."}]
```
### Azure Error

```
    "properties": {
        "statusCode": "429",
        "serviceRequestId": "fa3f97c4-3118-4a93-b625-6a0948b5d9f4",
        "statusMessage": "{\"error\":{\"code\":\"RetryableError\",\"message\":\"A retryable error occured.\",\"details\":[{\"code\":\"ReferencedResourceNotProvisioned\",\"message\":\"Cannot proceed with operation because resource /subscriptions/614e4618-7e10-4847-be48-a61acdbadff1/resourceGroups/testm1_resource_group_1/providers/Microsoft.Network/networkSecurityGroups/testm1_network_security_group_1 used by resource /subscriptions/614e4618-7e10-4847-be48-a61acdbadff1/resourceGroups/testm1_resource_group_1/providers/Microsoft.Network/virtualNetworks/testm1_virtual_network_1/subnets/testm1_subnet_1 is not in Succeeded state. Resource is in Updating state and the last operation that updated/is updating the resource is PutSecurityRuleOperation.\"}]}}"
    },
    "resourceGroupName": "testm1_resource_group_1",
    "resourceId": "/subscriptions/614e4618-7e10-4847-be48-a61acdbadff1/resourceGroups/testm1_resource_group_1/providers/Microsoft.Network/virtualNetworks/testm1_virtual_network_1/subnets/testm1_subnet_1",
    "resourceProviderName": {
        "localizedValue": "Microsoft.Network",
        "value": "Microsoft.Network"
    },
```

### PR DESCRIPTION
**Pull request by tombuildsstuff**
Currently there's a bug regarding Network Security Groups, where trying to create a Subnet / Virtual Network / Network Security Rule ([as in this example](https://gist.github.com/tombuildsstuff/a007598ece744015497fc77cbae24e6e) / #7986) would fail.

This PR fixes that, by only allowing a single modification to NSG's at once.

```
$ envchain azurerm make testacc TEST=./builtin/providers/azurerm/ TESTARGS='-run=TestAccAzureRMVirtualNetwork_'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/04/13 16:34:19 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/azurerm/ -v -run=TestAccAzureRMVirtualNetwork_ -timeout 120m
=== RUN   TestAccAzureRMVirtualNetwork_importBasic
--- PASS: TestAccAzureRMVirtualNetwork_importBasic (88.11s)
=== RUN   TestAccAzureRMVirtualNetwork_basic
--- PASS: TestAccAzureRMVirtualNetwork_basic (97.94s)
=== RUN   TestAccAzureRMVirtualNetwork_disappears
--- PASS: TestAccAzureRMVirtualNetwork_disappears (99.59s)
=== RUN   TestAccAzureRMVirtualNetwork_withTags
--- PASS: TestAccAzureRMVirtualNetwork_withTags (124.40s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/azurerm	410.070s
```

```
$ envchain azurerm make testacc TEST=./builtin/providers/azurerm/ TESTARGS='-run=TestAccAzureRMSubnet'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/04/13 16:43:09 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/azurerm/ -v -run=TestAccAzureRMSubnet -timeout 120m
=== RUN   TestAccAzureRMSubnet_importBasic
--- PASS: TestAccAzureRMSubnet_importBasic (134.67s)
=== RUN   TestAccAzureRMSubnet_basic
--- PASS: TestAccAzureRMSubnet_basic (115.68s)
=== RUN   TestAccAzureRMSubnet_disappears
--- PASS: TestAccAzureRMSubnet_disappears (116.02s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/azurerm	366.400s
```

```
$ envchain azurerm make testacc TEST=./builtin/providers/azurerm/ TESTARGS='-run=TestAccAzureRMNetworkSec'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/04/13 16:52:35 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/azurerm/ -v -run=TestAccAzureRMNetworkSec -timeout 120m
=== RUN   TestAccAzureRMNetworkSecurityGroup_importBasic
--- PASS: TestAccAzureRMNetworkSecurityGroup_importBasic (130.12s)
=== RUN   TestAccAzureRMNetworkSecurityRule_importBasic
--- PASS: TestAccAzureRMNetworkSecurityRule_importBasic (152.71s)
=== RUN   TestAccAzureRMNetworkSecurityGroup_basic
--- PASS: TestAccAzureRMNetworkSecurityGroup_basic (99.37s)
=== RUN   TestAccAzureRMNetworkSecurityGroup_disappears
--- PASS: TestAccAzureRMNetworkSecurityGroup_disappears (96.89s)
=== RUN   TestAccAzureRMNetworkSecurityGroup_withTags
--- PASS: TestAccAzureRMNetworkSecurityGroup_withTags (109.85s)
=== RUN   TestAccAzureRMNetworkSecurityGroup_addingExtraRules
--- PASS: TestAccAzureRMNetworkSecurityGroup_addingExtraRules (128.04s)
=== RUN   TestAccAzureRMNetworkSecurityRule_basic
--- PASS: TestAccAzureRMNetworkSecurityRule_basic (141.60s)
=== RUN   TestAccAzureRMNetworkSecurityRule_disappears
--- PASS: TestAccAzureRMNetworkSecurityRule_disappears (144.02s)
=== RUN   TestAccAzureRMNetworkSecurityRule_addingRules
--- PASS: TestAccAzureRMNetworkSecurityRule_addingRules (207.60s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/azurerm	1210.223s
```

Fixes #7986

### CODE REVIEW

File: builtin/providers/azurerm/resource_arm_virtual_network.go [hunk 1]
```diff
@@ -245,3 +268,37 @@ func resourceAzureSubnetHash(v interface{}) int {
...
 	return hashcode.String(subnet)
 }
+
+func expandAzureRmVirtualNetworkVirtualNetworkSecurityGroupNames(d *schema.ResourceData) ([]string, error) {
+	nsgNames := make([]string, 0)
+
+	if v, ok := d.GetOk("subnet"); ok {
+		subnets := v.(*schema.Set).List()
+		for _, subnet := range subnets {
+			subnet := subnet.(map[string]interface{})
```
Comment (grubernaut) [inline builtin/providers/azurerm/resource_arm_virtual_network.go]: Can we catch any errors from the interface cast here, and return?

Comment (tombuildsstuff) [inline builtin/providers/azurerm/resource_arm_virtual_network.go]: done :)

**Comment by tombuildsstuff** [comment]
Tests still pass - agreed to merge this with @grubernaut 👍
