### PR TITLE
cliconfig: more err detail when provider_installation has invalid provider source

### LINKED ISSUE #32716: Invalid dev override error message is hard to understand
### Terraform Version

```shell
Terraform v1.3.6
on darwin_amd64
```

### Terraform Configuration Files

No Terraform configuration files are necessary. But a `.terraformrc` file in the home directory is necessary. The only part that's important is that the address ends with `terraform-provider-<something>`. E.g.:
```HCL
provider_installation {
  dev_overrides {
      "registry.terraform.io/joneshf/terraform-provider-foo" = ""
  }
}
```

### Debug Output

https://gist.github.com/joneshf/f8446ee061ce3572e12de28bcdddfa0c

### Expected Behavior

The error displayed should include the [original diagnostic information with the suggestion for what the address should be](https://github.com/hashicorp/terraform-registry-address/blob/a459db791fcb28a1b93d9b7e0a46b5f1db027fa9/provider.go#L277).

### Actual Behavior

The error throws away the original diagnostic information in exchange for [a terser detail](https://github.com/hashicorp/terraform/blob/b8f3f802f591e5ff0523bfb8c2e06c9e62f56bfd/internal/command/cliconfig/provider_installation.go#L249).

### Steps to Reproduce

1. `terraform plan`

### Additional Context

I'm developing my first Terraform provider. I followed [the tutorial](https://developer.hashicorp.com/terraform/tutorials/providers-plugin-framework), and everything went fine. I then tried to start a new provider under my username and things have been going less than ideal. In particular, the `.terraformrc` file I included ends with `terraform-provider-<something>`. According to [a comment](https://github.com/hashicorp/terraform-registry-address/blob/a459db791fcb28a1b93d9b7e0a46b5f1db027fa9/provider.go#L250-L258), this is a mistake on my part. That's fine, I'm still learning this framework. The [useful diagnostic message it provides](https://github.com/hashicorp/terraform-registry-address/blob/a459db791fcb28a1b93d9b7e0a46b5f1db027fa9/provider.go#L277) is unfortunately discarded and instead a [cryptic diagnostic is returned instead](https://github.com/hashicorp/terraform/blob/b8f3f802f591e5ff0523bfb8c2e06c9e62f56bfd/internal/command/cliconfig/provider_installation.go#L249).

It would be great if the diagnostic that provides a solution to my error were propagated to me, instead of being lost.

My terraform version is a little out of date, but these diagnostics are on the trunk branches of the appropriate repos. So I don't think an update would fix anything.

### References

_No response_

### PR DESCRIPTION
**Pull request by kmoe**
Fixes #32716.

Error output beforehand:
```
$   terraform plan
There are some problems with the CLI configuration:
╷
│ Error: Invalid provider installation dev overrides
│
│ The entry "registry.terraform.io/joneshf/terraform-provider-foo" in 1:1 is
│ not a valid provider source string.
╵

As a result of the above problems, Terraform may not behave as intended.
```

Error output afterward:
```
$  terraform plan
There are some problems with the CLI configuration:
╷
│ Error: Invalid provider installation dev overrides
│
│ The entry "registry.terraform.io/joneshf/terraform-provider-foo" in 1:1 is
│ not a valid provider source string.
│ Invalid provider type: Provider source "joneshf/terraform-provider-foo" has
│ a type with the prefix "terraform-provider-", which isn't valid. Although
│ that prefix is often used in the names of version control repositories for
│ Terraform providers, provider source strings should not include it.
│
│ Did you mean "joneshf/foo"?
╵

As a result of the above problems, Terraform may not behave as intended.
```

I believe this is a valid use of the error message from `ParseProviderSourceString`, as cliconfig is parsing a hand-written provider source string. This should be the "user error" case in https://github.com/hashicorp/terraform-registry-address/blob/a459db791fcb28a1b93d9b7e0a46b5f1db027fa9/provider.go#L263.

### CODE REVIEW

File: internal/command/cliconfig/provider_installation.go [hunk 1]
```diff
@@ -246,7 +246,7 @@ func decodeProviderInstallationFromConfig(hclFile *hclast.File) ([]*ProviderInst
 						diags = diags.Append(tfdiags.Sourceless(
 							tfdiags.Error,
 							"Invalid provider installation dev overrides",
-							fmt.Sprintf("The entry %q in %s is not a valid provider source string.", rawAddr, block.Pos()),
+							fmt.Sprintf("The entry %q in %s is not a valid provider source string.\n%s", rawAddr, block.Pos(), moreDiags.Err().Error()),
```
Comment (alisdair) [inline internal/command/cliconfig/provider_installation.go:249]: Based on the example in the PR description, I think this might look better with two newlines before the interpolated error. For example:

```
╷
│ Error: Invalid provider installation dev overrides
│
│ The entry "registry.terraform.io/joneshf/terraform-provider-foo" in 1:1 is
│ not a valid provider source string.
│
│ Invalid provider type: Provider source "joneshf/terraform-provider-foo" has
│ a type with the prefix "terraform-provider-", which isn't valid. Although
│ that prefix is often used in the names of version control repositories for
│ Terraform providers, provider source strings should not include it.
│
│ Did you mean "joneshf/foo"?
╵
```

**Review by alisdair — APPROVED** [review]
👍 with a non-blocking suggestion inline
