### PR TITLE
command/format: Fix rendering of force-new updates

### LINKED ISSUE #19145: When rendering a plan to replace a resource, "requires replacement" annotation is missing from attribute(s) that caused it
### Terraform Version

```
Terraform v0.12.0-alpha1
```

### Expected Behavior

```
  # aws_subnet.all[1] must be replaced
-/+ resource "aws_subnet" "all" {
        arn                             = "arn:aws:ec2:us-west-2:187483:subnet/subnet-033387463333346df"
        assign_ipv6_address_on_creation = false
        availability_zone               = "us-west-2b"
      ~ cidr_block                      = "10.1.16.0/21" -> "10.1.32.0/21" (requires replacement)
        id                              = "subnet-033387463333346df"
        map_public_ip_on_launch         = false
        tags                            = {
            "Name" = "us-west-2b main subnet"
        }
        vpc_id                          = "vpc-0f70dddd013333379"
    }
```

When describing a plan to replace a particular instance due to a change that cannot be applied in-place, Terraform should annotate the specific changes that required that with "(requires replacement)", as shown for `cidr_block` in the output above.

### Actual Behavior
In v0.12-alpha1, these extra annotations are not consistently shown.

### Additional Context
In version of Terraform prior to v0.12, this used different terminology "forces new resource". Despite the terminology change, this is still the same mechanism and has the same behavior.

### PR DESCRIPTION
**Pull request by radeksimko**
~Depends on #19608 (I can rebase after that PR is merged)~

Fixes #19145

## Before

screen shot 2018-12-11 at 14 30 28

## After

screen shot 2018-12-11 at 14 29 05

### CODE REVIEW

File: command/format/diff_test.go [hunk 1]
```diff
@@ -935,6 +1273,118 @@ func TestResourceChange_nestedSet(t *testing.T) {
...
+				"ami": cty.StringVal("ami-AFTER"),
+				"root_block_device": cty.SetVal([]cty.Value{
+					cty.ObjectVal(map[string]cty.Value{
+						"volume_type": cty.StringVal("different"),
+					}),
+				}),
+			}),
+			RequiredReplace: cty.NewPathSet(cty.Path{
+				cty.GetAttrStep{Name: "root_block_device"},
+				cty.IndexStep{Key: cty.NumberIntVal(0)},
```
Comment (apparentlymart) [inline command/format/diff_test.go]: Since `root_block_device` is defined as a set, this is not a realistic path for it... there isn't any way to draw a path through a set (since they don't have keys) and so in "real life" the set as a whole is what would be here, with all of the separate block adds/removes marked as "forces replacement" in the output then.

This test _does_ make sense for a block of `NestingList`, though.

File: command/format/diff_test.go [hunk 2]
```diff
@@ -935,6 +1273,118 @@ func TestResourceChange_nestedSet(t *testing.T) {
...
+						Block: configschema.Block{
+							Attributes: map[string]*configschema.Attribute{
+								"volume_type": {
+									Type:     cty.String,
+									Optional: true,
+									Computed: true,
+								},
+							},
+						},
+						Nesting: 2,
```
Comment (apparentlymart) [inline command/format/diff_test.go]: It'd be easier to read to write this instead as `Nesting: configschema.NestingSet`.

**Comment by apparentlymart** [comment]
Oh, by the way: this fixes #19145.
