### PR TITLE
don't allow leading slashes in s3 remote state key

### LINKED ISSUE #15645: S3 backend doesn't like a key starting in `/` (slash)
### Terraform Version

```
$ terraform -v
Terraform v0.9.11
```

### Terraform Configuration Files

`backend.tf`:

```
terraform {
        backend "s3" {
                bucket         = "wombles-whacky-whatsit"
                key            = "/"
                region         = "ap-southeast-2"
                dynamodb_table = "wombles-whacky-whatsit"
        }
}
```

`terraform.tfvars`:

```
access_key = "blahblahblah"
secret_key = "s00pers3kr1t"
```

### Debug Output

Yeeeeeeeah... not so keen on putting that up publicly.  It's chock full of all sorts of stuff that I'm not qualified to determine the sensitivity of.  The *important* looking bit, though, with a bit of light redaction is probably this:

```
2017/07/27 21:30:24 [INFO] command: backend initialized: *s3.Backend
2017/07/27 21:30:24 [INFO] command: backend *s3.Backend is not enhanced, wrapping in local
2017/07/27 21:30:24 [DEBUG] [aws-sdk-go] DEBUG: Request s3/ListObjects Details:
---[ REQUEST POST-SIGN ]-----------------------------
GET /?prefix=env%3A%2F HTTP/1.1                    
Host: wombles-whacky-whatsit.s3-ap-southeast-2.amazonaws.com
User-Agent: aws-sdk-go/1.8.34 (go1.8; linux; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.9.11
Authorization: AWS4-HMAC-SHA256 Credential=NOPENOPENOPE
                                                   
                                                   
-----------------------------------------------------
2017/07/27 21:30:25 [DEBUG] [aws-sdk-go] DEBUG: Response s3/ListObjects Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK                                    
Connection: close                                  
Transfer-Encoding: chunked                         
Content-Type: application/xml                      
Date: Thu, 27 Jul 2017 11:30:26 GMT                
Server: AmazonS3                                   
X-Amz-Bucket-Region: ap-southeast-2                
                                                   
                                                   
-----------------------------------------------------
2017/07/27 21:30:25 [DEBUG] [aws-sdk-go] <?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>wombles-whacky-whatsit</Name><Prefix>env:/</Prefix><Marker></Marker><MaxKeys>1000</MaxKeys><IsTruncated>false</IsTruncated><Contents><Key>env:/dev-mpalmer/</Key><LastModified>2017-07-27T11:27:46.000Z</LastModified><ETag>&quot;71a8b43123aab3dca9d5d97dc39607da&quot;</ETag><Size>282</Size><Owner><ID>ce2152ddf2f621fbbbb5215370cfad1d83326d1b5d25c0955786134160086e35</ID><DisplayName>team+blizzard</DisplayName></Owner><StorageClass>STANDARD</StorageClass></Contents></ListBucketResult>
  default                                          
                                                   
2017/07/27 21:30:25 [DEBUG] plugin: waiting for all plugin processes to complete...
```

That shows the important bit, I think: exactly what files are in place.

### Expected Behavior

There should have been a `dev-mpalmer` line in the environment list.

### Actual Behavior

There was not a `dev-mpalmer` line in the environment list.

### Steps to Reproduce

1. Create a regular-looking S3 bucket.
1. Create a regular-looking DynamoDB table (I keep the cost down by turning off auto-scaling and setting the read/write capacity to 1, but I'd be... moderately surprised... if that were the cause)
1. `terraform init -backend-config terraform.tfvars`
1. `terraform env new dev-mpalmer`
1. `terraform env list`

### Important Factoids

The access/secret key are from an IAM user which has Administrators privilege, and which was the same IAM user that created the bucket and DynamoDB table, so I don't *think* permissions are an issue.

If I replace `"/"` in the backend config's `key` line with something that doesn't start with a `/`, such as, say, `lolrus`, everything works just peachy.

I have observed the same behaviour with a `key` value that isn't *just* `"/"` (such as `"/something/funny"`), so it doesn't appear to be something that is unique to `"/"`.

### PR DESCRIPTION
**Pull request by jbardin**
S3 accepts objects with a leading slash and strips them off. This works
fine except in our workspace hierarchy, which then can no longer find
suffixes matching the full key name.

Fixes #15645

### CODE REVIEW

File: backend/remote-state/s3/backend.go [hunk 1]
```diff
@@ -25,6 +27,14 @@ func New() backend.Backend {
 				Type:        schema.TypeString,
 				Required:    true,
 				Description: "The path to the state file inside the bucket",
+				ValidateFunc: func(v interface{}, s string) ([]string, []error) {
+					// s3 will strip leading slashes from an object, so while this will
+					// technically be accepted by s3, it will break our workspace hierarchy.
+					if strings.HasPrefix(v.(string), "/") {
+						return nil, []error{fmt.Errorf("key cannot contain a leading '/'")}
```
Comment (apparentlymart) [inline backend/remote-state/s3/backend.go]: This is totally a nit, but "contain a leading slash" reads funny to me since I guess I don't think of a prefix as being "contained".

Suggest instead: `"key must not start with '/'"`

Comment (jbardin) [inline backend/remote-state/s3/backend.go]: thanks, much better!
