### PR TITLE
check for cancellation before apply confirmation

### LINKED ISSUE #30918: crtl-c shows "graceful" shutdown message, then long pause, then terraform still destroys resources
### Terraform Version
v1.1.7

### Screenshot of destruction:
josh_ip-10-20-11-55__

### Expected Behavior
not destroyed resources

### Actual Behavior
resources destroyed.  site down. 💥 

### Steps to Reproduce
Press ctrl-c - see graceful message.  wait.

### Additional Context
As noted in the screenshot there was a long pause after the Graceful shutdown message showed up to when it continued on and destroyed resources. That is, it had plenty of time to think about doing things and still didn't shutdown.

Counterintuitively, I'm pretty sure if I **held** ctrl-c down and sent the process 10s or 100s of kill signals it would've died "ungracefully" and the resource would not have been destroyed.  This would've been a much better scenario.

### PR DESCRIPTION
**Pull request by jbardin**
When executing an apply with no plan, it's possible for a cancellation
to arrive during the final batch of provider operations, resulting in no
errors in the plan. The run context was next checked during the
confirmation for apply, but in the case of -auto-approve that
confirmation is skipped, resulting in the canceled plan being applied.

Make sure we directly check for cancellation before confirming the plan.

Fixes #30918

### CODE REVIEW

File: internal/backend/local/backend_apply_test.go [hunk 1]
```diff
@@ -351,3 +351,36 @@ func applyFixtureSchema() *terraform.ProviderSchema {
...
+		if !strings.Contains(output.Stderr(), "execution halted") {
+			t.Fatal("expected 'execution halted', got:\n", output.All())
+		}
+	}()
+
+	ctx, cancel := context.WithCancel(context.Background())
+	testHookStopPlanApply = cancel
+	defer func() {
+		testHookStopPlanApply = nil
+	}()
```
Comment (alisdair) [inline internal/backend/local/backend_apply_test.go:374]: Is there any chance of this leaking into another parallel test and causing a mid-process cancel?

**Review by alisdair — APPROVED** [review]
Fix makes sense to me, one question/worry about the test inline (which might be nothing).
