### PR TITLE
command/format: improve "source" of error messages regarding missing arguments

### LINKED ISSUE #20829: connection block diagnostics report resource as source
If the `diagnostic.Format` function gets an `*hcl.Diagnostic` for a missing required value in a connection block, the empty code snippet is turned into the resource block, rather than the connection block.

A missing `host` field show:

```
Error: Missing required argument

  on main.tf line 1, in resource "null_resource" "foo":
   1: resource "null_resource" "foo" {

The argument "host" is required, but no definition was found.
```

While the actual diagnostic `Source()` is:

```
&tfdiags.SourceRange{
    Filename:"main.tf",
    Start:tfdiags.SourcePos{Line:9, Column:6, Byte:171},
    End:tfdiags.SourcePos{Line:9, Column:6, Byte:171},
}
```

### PR DESCRIPTION
**Pull request by mildwonkey**
Fixes #20829

HCL2 was originally returning the end of the block as the location for missing attributes. On it's own this wasn't terribly helpful, and terraform ended up looking up the start of the block for error messages. An unintended side effect of this was that attributes missing from nested blocks returned unclear error messages  pointed to the top-level resource, not the nested block.

HCL2 has been updated to return the _start_ of the block, which leads to more precise error messages:

```
Error: Missing required argument

  on connection.tf line 5, in resource "null_resource" "foo":
   5:   connection {

The argument "host" is required, but no definition was found.


Error: Missing required argument

  on connection.tf line 11, in resource "random_id" "id":
  11: resource "random_id" "id" {

The argument "byte_length" is required, but no definition was found.
```

### CODE REVIEW

File: command/format/diagnostic.go [hunk 1]
```diff
@@ -180,12 +177,6 @@ func Diagnostic(diag tfdiags.Diagnostic, sources map[string][]byte, color *color
 	return buf.String()
 }
 
-// sourceCodeContextStr attempts to find a user-friendly description of
```
Comment (pselle) [inline command/format/diagnostic.go]: Is this deleted because it's referring to a function that's not here anymore?

File: go.mod [hunk 2]
```diff
@@ -60,7 +60,7 @@ require (
 	github.com/hashicorp/go-version v1.1.0
 	github.com/hashicorp/golang-lru v0.5.0 // indirect
 	github.com/hashicorp/hcl v0.0.0-20170504190234-a4b07c25de5f
-	github.com/hashicorp/hcl2 v0.0.0-20190327223817-3fb4ed0d9260
```
Comment (pselle) [inline go.mod]: Do these changes need to go into this PR?

File: go.sum [hunk 3]
```diff
@@ -202,6 +202,8 @@ github.com/hashicorp/hcl v0.0.0-20170504190234-a4b07c25de5f/go.mod h1:oZtUIOe8dh
 github.com/hashicorp/hcl2 v0.0.0-20181208003705-670926858200/go.mod h1:ShfpTh661oAaxo7VcNxg0zcZW6jvMa7Moy2oFx7e5dE=
 github.com/hashicorp/hcl2 v0.0.0-20190327223817-3fb4ed0d9260 h1:C3vhYEXk8ihs+Xvq093axRyYhfLERrZ6Uv5tfRw9yvw=
 github.com/hashicorp/hcl2 v0.0.0-20190327223817-3fb4ed0d9260/go.mod h1:HtEzazM5AZ9fviNEof8QZB4T1Vz9UhHrGhnMPzl//Ek=
+github.com/hashicorp/hcl2 v0.0.0-20190402200843-8b450a7d58f9 h1:zCITwiA0cog6aYr/a/McDHKtgsEpYxXvTIgugv5iu8o=
```
Comment (pselle) [inline go.sum]: Does this change need to go in this PR?

File: vendor/modules.txt [hunk 4]
```diff
@@ -307,7 +307,7 @@ github.com/hashicorp/hcl/hcl/scanner
 github.com/hashicorp/hcl/hcl/strconv
 github.com/hashicorp/hcl/json/scanner
 github.com/hashicorp/hcl/json/token
-# github.com/hashicorp/hcl2 v0.0.0-20190327223817-3fb4ed0d9260
+# github.com/hashicorp/hcl2 v0.0.0-20190402200843-8b450a7d58f9
```
Comment (pselle) [inline vendor/modules.txt]: Does this change need to be in this PR?

File: command/format/diagnostic.go (hunk 1 above)
Comment (mildwonkey) [reply command/format/diagnostic.go]: Yes. The function was renamed and the behavior changed in an earlier merge, so I just removed the comment. I would've updated the comment but I wasn't sure how to properly describe the new behavior :(

**Comment by mildwonkey** [comment]
Ah ha! Tests did break, whoops, I'll fix those (I only checked the `command` pkg, my mistake 🙃 )

File: command/format/diagnostic.go [hunk 5]
```diff
@@ -100,18 +101,14 @@ func Diagnostic(diag tfdiags.Diagnostic, sources map[string][]byte, color *color
...
-						&buf, color.Color("%4d: %s[underline]%s[reset]%s\n"),
-						lineRange.Start.Line,
-						before, highlighted, after,
-					)
-				}
+				before := beforeRange.SliceBytes(src)
+				highlighted := highlightedRange.SliceBytes(src)
+				after := afterRange.SliceBytes(src)
+				fmt.Fprintf(
+					&buf, color.Color("%4d: %s[underline]%s[reset]%s\n"),
```
Comment (apparentlymart) [inline command/format/diagnostic.go]: I guess this works without the `if highlightedRange.Empty()` test because in that case everything will be in `before` and both `highlighted` and `after` are empty? I think perhaps when I originally wrote this I was trying to avoid printing out an underline escape code immediately followed by a reset escape code, but that doesn't really matter in practice and I agree this way seems more straightforward.

File: command/format/diagnostic.go (hunk 1 above)
Comment (apparentlymart) [reply command/format/diagnostic.go]: This does indeed seem kinda weird... from the description of `sourceCodeContextStr` it seems like it was the former home of what is now [`hcled.ContextString`](https://godoc.org/github.com/hashicorp/hcl2/hcled#ContextString), the function that figures out what top-level block a given offset is inside so we can include that in the error messages. It looks like this `parseRange` function was what remained after we factored out the main work into that `hcled.ContextString` function; the work now is just to go from raw source code and a range into suitable arguments to pass to `hcled.ContextString`. `parseRange` feels like an odd name for that, but I don't have a better one... :thinking:

File: command/format/diagnostic.go (hunk 5 above)
Comment (mildwonkey) [reply command/format/diagnostic.go]: The `highlightedRange.Empty()` check is still in this function, it was moved back to its original location:

https://github.com/hashicorp/terraform/blob/d472568d0e5714693025088169e3f4dccbc3131b/command/format/diagnostic.go#L69-L72

I'll admit I didn't look too closely at the rest of the logic - if something looks off to you I can take a closer look.

Comment (apparentlymart) [reply command/format/diagnostic.go]: Ahh, right... I forgot that there's the fixup step above where it turns zero-length highlights into one-byte highlights so that there's always _something_ to underline. :+1:
