### PR TITLE
Fix remote backend multi workspace state migration

### LINKED ISSUE #28858: Error looking up workspace with multiple environments when prefix contains a digit/number
### Terraform Version

* 0.14.11
* 0.15.4

### Terraform Configuration Files

```terraform
terraform {
  required_version = ">= 0.14.11, < 0.15.0"

  backend "remote" {
    hostname = "app.terraform.io"
    organization = "myorg"
    workspaces {
      prefix = "cp-10-dns-"
    }
  }

}
```

### Debug Output

```
$ terraform init
Initializing modules...

Initializing the backend...
Backend configuration changed!

Terraform has detected that the configuration specified for the backend
has changed. Terraform will now check for existing state in the backends.



Error: Error looking up workspace

Workspace read failed: invalid value for workspace
```

### Expected Behavior

Migrate the local state per workspace to the corresponding TFC workspace, with the namespace name following this scheme:

`${NAMESPACE}-${MODULE_INDEX}-${MODULE_NAME}-${ENVIRONMENT}`

Example:
```
cp-10-dns-dev
cp-15-network-prod
cp-20-eks-staging
```

### Actual Behavior

Following the official docs (https://www.terraform.io/docs/cloud/migrate/workspaces.html) to migrate current local workspaces (dev, staging, prod) to TFC using the recommended `workspaces.prefix` scheme, I get an error, when the TFC workspace name contains an digit. 
Even if digits are allowed character (https://www.terraform.io/docs/cloud/workspaces/naming.html).

Removing the digit from the TFC workspace name seems to solves this issue.

In addition, when using `worspaces.name` with the exact string works.

### Steps to Reproduce

1. Fork this repo https://github.com/hashicorp/tfc-guide-example
2. Login to TFC
3. Create 3 workspaces as VCS and name them using this scheme: `cp-42-tfc-guide-example-${environment}`
4. Clone the repo locally
5. Update the backend remote configuration with prefix
6.  perform `terraform init` to sync state

```
terraform {
  backend "remote" {
    hostname = "app.terraform.io"
    organization = "my-org"

    workspaces {
      prefix = "cp-42-tfc-guide-example-"
    }
  }
}
```

### References

- #28092

### PR DESCRIPTION
**Pull request by alisdair**
Two changes, both addressing the same underlying issue:

- Fix faulty state migration version check when using multiple workspaces

    When migrating multiple local workspaces to a remote backend target using the `prefix` argument, we need to perform the version check against all existing workspaces returned by the `Workspaces` method. Failing to do so will result in a version check error.

- Add `-ignore-remote-version` flag for init as a fallback

    When performing state migration to a remote backend target, Terraform may fail due to mismatched remote and local Terraform versions. Here we add the `-ignore-remote-version` flag to allow users to ignore this version check when necessary.

Unfortunately neither of these are easily unit tested. I've manually verified that this fixes #28858 when testing against my reproduction.

### CODE REVIEW

File: internal/command/meta_backend_migrate.go [hunk 1]
```diff
@@ -57,7 +57,7 @@ func (m *Meta) backendMigrateState(opts *backendMigrateOpts) error {
 			errMigrateLoadStates), opts.OneType, err)
 	}
 
-	_, err = opts.Two.Workspaces()
+	twoWorkspaces, err := opts.Two.Workspaces()
```
Comment (radditude) [inline internal/command/meta_backend_migrate.go:60]: A very small naming nit: I was momentarily confused by this variable name because my brain tried to parse `two` as the number of workspaces 😆 would it be weird to call this `backendTwoWorkspaces` instead? I realize that doesn't match the naming convention of the other variables in this file, though.

**Review by radditude — APPROVED** [review]
My manual testing looks good! I'm going to list my test steps here just because this was a slightly convoluted repro and I want to confirm that I didn't miss anything:

- created two local workspaces named `one` and `two`
- ran `terraform apply` for each so they had state
- created two TFC workspaces named `test-one` and `test-two` with Terraform versions set to 0.13.7
- added remote backend configuration that looked like:

```
backend "remote" {
	organization = "my-org"
	
	workspaces {
		prefix = "test-"
	}
}
```

- ran `terraform init`, which failed as expected due to the mismatched versions
- ran `terraform init -ignore-remote-version`, which succeeded and state was successfully migrated to the two TFC workspaces

File: internal/command/meta_backend_migrate.go (hunk 1 above)
Comment (alisdair) [reply internal/command/meta_backend_migrate.go:60]: I agree that this variable naming is confusing, but as you noted the rest of the function (and the entire file) has this pattern established, and I don't want to change _everything else_ so I intend to leave it as-is 😑

**Comment by alisdair** [comment]
Thank you for the very thorough manual testing, @radditude! 🙌
