### PR TITLE
core: fix bug detecting deeply nested module orphans

### LINKED ISSUE #3114: Nested Module Bug
It appears as though there's a bug with nested modules. I've detailed the steps to reproduce and the errors that I'm seeing in https://github.com/meylor/terraform-nested-module-bug/blob/master/README.md

### PR DESCRIPTION
**Pull request by phinze**
Context:

As part of building up a Plan, Terraform needs to detect "orphaned"
resources--resources which are present in the state but not in the
config. This happens when config for those resources is removed by the
user, making it Terraform's responsibility to destroy them.

Both state and config are organized by Module into a logical tree, so
the process of finding orphans involves checking for orphaned Resources
in the current module and for orphaned Modules, which themselves will
have all their Resources marked as orphans.

Bug:

In #3114 a problem was exposed where, given a module tree that looked
like this:

```
root
 |
 +-- parent (empty, except for sub-modules)
       |
       +-- child1 (1 resource)
       |
       +-- child2 (1 resource)
```

If `parent` was removed, a bunch of error messages would occur during
the plan. The root cause of this was duplicate orphans appearing for the
resources in child1 and child2.

Fix:

This turned out to be a bug in orphaned module detection. When looking
for deeply nested orphaned modules, root.parent was getting added twice
as an orphaned module to the graph.

Here, we add an additional check to prevent a double add, which
addresses this scenario properly.

Fixes #3114 (the Provisioner side of it was fixed in #4877)

### CODE REVIEW

**Comment by phinze** [comment]
Relevant prior work on deeply nested orphans here: #2786

**Comment by phinze** [comment]
ping @mitchellh, @jen20 for review here :eyes:

File: terraform/state.go [hunk 1]
```diff
@@ -151,8 +151,22 @@ func (s *State) ModuleOrphans(path []string, c *config.Config) [][]string {
...
 		}
 
+		orphanPath := m.Path[:len(path)+1]
+
+		// Don't double-add if we've already added this orphan (which can happen if
+		// there are multiple nested sub-modules that get orphaned together).
+		alreadyAdded := false
+		for _, o := range orphans {
+			if reflect.DeepEqual(o, orphanPath) {
+				alreadyAdded = true
```
Comment (mitchellh) [inline terraform/state.go]: Not going to probably matter but you can break after this line safely.

**Comment by mitchellh** [comment]
One comment, otherwise LGTM

**Comment by phinze** [comment]
Added the `break` - will merge once Travis gives the ole' green
