### PR TITLE
handle empty containers in ProposedNew NestedTypes

### LINKED ISSUE #29576: `terraform plan` reports "planned for absence but config wants existence" when provider returns empty Set
### Terraform Version

```console
% terraform version
Terraform v1.0.6
on darwin_amd64
```

### Description

A protocol v6 resource type declares (using `terraform-plugin-framework`) an attribute `tags` of type:

```go
"tags": {
	Attributes: types.SetNestedAttributes(
		map[string]tfsdk.Attribute{
			"key": {
				Type:        types.StringType,
				Required:    true,
			},
			"value": {
				Type:     types.StringType,
				Required: true,
			},
		},
	),
	Optional: true,
},
```

My configuration has no `tags` defined:

```terraform
resource "cloud_service_thing" "test" {}
```

On `terraform refresh` the underlying cloud provider API, and hence the provider, returns an empty array for `tags`:

```
2021-09-14T10:08:48.938-0400 [WARN]  Provider "registry.terraform.io/hashicorp/cloud" produced an unexpected new value for cloud_service_thing.test during refresh.
      - .tags: was null, but now cty.SetValEmpty(cty.Object(map[string]cty.Type{"key":cty.String, "value":cty.String}))
```

and Terraform correctly shows a diff:

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # cloud_service_thing.test will be updated in-place
  ~ resource "cloud_service_thing" "test" {
        id                  = "606d124b-cfcc-40cb-b4b5-f37bf5d70c85"
      - tags                = [
        ]
        # (8 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

I change my configuration to try and suppress the diff and match the cloud provider API's result:

```terraform
resource "cloud_service_thing" "test" {
  tags = []
}
```

On `terraform refresh` I now get an error:

```
2021-09-14T10:11:34.877-0400 [WARN]  Provider "registry.terraform.io/hashicorp/cloud" produced an unexpected new value for cloud_service_thing.test during refresh.
      - .tags: was null, but now cty.SetValEmpty(cty.Object(map[string]cty.Type{"key":cty.String, "value":cty.String}))
2021-09-14T10:11:34.899-0400 [INFO]  backend/local: plan operation completed
╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/hashicorp/cloud" planned an invalid value for cloud_service_thing.test.tags: planned for absence but config wants existence.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

I would expect Terraform to show no diff when both the configuration specifies an empty set and the provider/underlying cloud provider API returns an empty set.

### PR DESCRIPTION
**Pull request by jbardin**
Empty containers of NestedTypes were not handled in ProposedNew, causing plans to be submitted with null values where there was configuration present.

Fixes #29576

### CODE REVIEW

File: internal/plans/objchange/objchange.go [hunk 1]
```diff
@@ -345,8 +347,10 @@ func proposedNewNestedType(schema *configschema.Object, prior, config cty.Value)
 			} else {
 				newV = cty.ListVal(newVals)
 			}
-		} else {
-			newV = cty.NullVal(schema.ImpliedType())
+		case config.IsNull():
+			newV = cty.NullVal(config.Type())
+		default:
+			newV = cty.ListValEmpty(config.Type().ElementType())
```
Comment (apparentlymart) [inline internal/plans/objchange/objchange.go:353]: It looks like these two cases could be safely simplified down to just one like this:

```go
default:
    newV = config
```

...since right now both of those paths seem to just be constructing a new value equivalent to the one we're already holding, right?

(Similar question for the other variants of this below.)

**Review by apparentlymart — APPROVED** [review]
This makes sense to me... I guess we inherited this from the codepath which handles blocks where we needed to preserve the rigid invarants the SDK expected for those, but that sort of mangling isn't correct for attributes.

The realization that this was likely the extra processing we had to do to make blocks work then led to the question I left inline, though if the answer to that is "no" (that is, if there's a reason to reconstruct new values rather than just preserve the existing ones) then I'm happy to keep it how you wrote it, though I'd love to know more about what that reason is for my own edification! :grinning:

File: internal/plans/objchange/objchange.go (hunk 1 above)
Comment (jbardin) [reply internal/plans/objchange/objchange.go:353]: 🤦‍♂️Thank you, that is a correct simplification. I was repeating a pattern used elsewhere when creating collections based on other constraints, but it’s unnecessary here since we have a value already.
