### PR TITLE
Fix panics due to missing graph edges on empty modules or invalid refs

### LINKED ISSUE #34976: It happened crash after upgrade the version to 1.8.0
### Terraform Version

```shell
1.8.0
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

panic: no expansion has been registered for module.cert_lb
goroutine 19550 [running]:
runtime/debug.Stack()
	/Users/runner/hostedtoolcache/go/1.22.1/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/Users/runner/work/terraform/terraform/internal/logging/panic.go:84 +0x18b
panic({0x7213d00?, 0xc00592bef0?})
	/Users/runner/hostedtoolcache/go/1.22.1/x64/src/runtime/panic.go:770 +0x132
github.com/hashicorp/terraform/internal/instances.(*Expander).ExpandAbsModuleCall(0x734ed40?, {{0x0, 0x0, 0x0}, {{}, {0xc00013c8d0, 0x7}}})
	/Users/runner/work/terraform/terraform/internal/instances/expander.go:171 +0x265
github.com/hashicorp/terraform/internal/terraform.(*evaluationStateData).GetModule(0xc00159d560, {{}, {0xc00013c8d0?, 0x4a5f547?}}, {{0xc00072a970, 0xf}, {0x3b, 0x1e, 0x892}, {0x3b, ...}})
	/Users/runner/work/terraform/terraform/internal/terraform/evaluate.go:398 +0x788
github.com/hashicorp/terraform/internal/lang.(*Scope).evalContext(0xc00159d5f0, {0xc00aa8d320, 0x5, 0x5}, {0x0, 0x0})
	/Users/runner/work/terraform/terraform/internal/lang/eval.go:381 +0x1112
github.com/hashicorp/terraform/internal/lang.(*Scope).EvalContext(...)
	/Users/runner/work/terraform/terraform/internal/lang/eval.go:245
github.com/hashicorp/terraform/internal/lang.(*Scope).EvalBlock(0xc00159d5f0, {0x78fb640, 0xc002ac4730}, 0xc004d29980)
	/Users/runner/work/terraform/terraform/internal/lang/eval.go:58 +0xc5
github.com/hashicorp/terraform/internal/terraform.(*BuiltinEvalContext).EvaluateBlock(0x1?, {0x78fb8d0, 0xc00123edc0}, 0xc004d29980, {0x0?, 0x0?}, {{{{0x0, 0x0}}, {0x0, 0x0}}, ...})
	/Users/runner/work/terraform/terraform/internal/terraform/eval_context_builtin.go:315 +0x145
github.com/hashicorp/terraform/internal/terraform.(*NodeAbstractResourceInstance).plan(0xc005e24248, {0x791b128, 0xc000e2ec30}, 0x0, 0x0, 0x0, {0x0, 0x0, 0x0?})
	/Users/runner/work/terraform/terraform/internal/terraform/node_resource_abstract_instance.go:808 +0xb8b
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).managedResourceExecute(0xc005dd7340, {0x791b128, 0xc000e2ec30})
	/Users/runner/work/terraform/terraform/internal/terraform/node_resource_plan_instance.go:250 +0x1395
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).Execute(0x18?, {0x791b128?, 0xc000e2ec30?}, 0x0?)
	/Users/runner/work/terraform/terraform/internal/terraform/node_resource_plan_instance.go:75 +0x8a
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc003821cc0, {0x791b128, 0xc000e2ec30}, {0x554ec930, 0xc005dd7340})
	/Users/runner/work/terraform/terraform/internal/terraform/graph_walk_context.go:153 +0xbb
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x7880a60, 0xc005dd7340})
	/Users/runner/work/terraform/terraform/internal/terraform/graph.go:112 +0x62a
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc005d896e0, {0x7880a60, 0xc005dd7340}, 0xc00579f1c0)
	/Users/runner/work/terraform/terraform/internal/dag/walk.go:384 +0x2d7
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update in goroutine 15667
	/Users/runner/work/terraform/terraform/internal/dag/walk.go:307 +0xff3
```

### Expected Behavior

Nothing should have happened.

### Actual Behavior

It happened crash

### Steps to Reproduce

terraform plan

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by liamcervante**
This PR fixes two crashes within Terraform v1.8.0. In both cases a module expansion was being missed, and then crashing when something tried to reference the missed module.

The first occurs when referencing an output that doesn't exist within the `try()` function. In this case the executing node was not getting connected to the module expansion node because the output node to connect doesn't exist. Now, the `transform_reference` transformer will unfold module call output references into simple module call references if the target node for a module call output does not exist.

The second occurs when referencing a module block directly (ie. not a module output), on a module that has no changes during the apply. The module expansion node was being removed as it had no direct references (as no changes from within the module). Now, the module expansion node implements the referenceable interface, and we'll connect nodes that reference the module directly both to the expansion node and the closer node. This will ensure the expansion of a module happens before anything that references it is processed.

Fixes #34976 

## Target Release

1.8.1

### BUG FIXES

 

- Fix crash in `terraform plan` when referencing a module output that does not exist within the `try(...)` function.
- Fix crash in `terraform apply` when referencing a module with no planned changes.

### CODE REVIEW

File: internal/terraform/node_module_expand.go [hunk 1]
```diff
@@ -98,7 +107,7 @@ func (n *nodeExpandModule) DependsOn() []*addrs.Reference {
 
 // GraphNodeReferenceOutside
 func (n *nodeExpandModule) ReferenceOutside() (selfPath, referencePath addrs.Module) {
-	return n.Addr, n.Addr.Parent()
+	return n.Addr.Parent(), n.Addr.Parent()
```
Comment (jbardin) [inline internal/terraform/node_module_expand.go:110]: OK, this is starting to make more sense. The original graph shape was structured around the variables and outputs, so only `referencePath` was really being used to connect `for_each` references. There was no real reference directly to a module until expansion was introduced, and even then it relied on the output objects for coordination. I think we may have a bug open somewhere about a module with no outputs not being referencable which this might also fix.

**Review by jbardin — APPROVED** [review]

**Comment by favoretti** [comment]
@jbardin I think this introduced a regression. We started getting cycle errors, where 1.8.0 didn't have them in statements where we actually use `try()` to verify whether a particular part of module output exists or not :) Is this intentional?

**Comment by jbardin** [comment]
Thanks @favoretti, I thought there was a parallel discussion about testing this against a self-referencing module for cycles, but maybe I was mistaken. I do see now how this will create a cycle in that situation though, so I'll take a closer look.

Thanks!

**Comment by jbardin** [comment]
In case someone gets to this before I do, it's a little more subtle that just a self-referencing module. If you have a module which has outputs which can be tied back to it's own inputs it still works, unless you have a reference that resolves to the entire module somehow:

```
module a {
  source = "./mod"
  first = "input"
  second = local.intermediate
}

locals {
  intermediate = try(module.a.maybe, "oops")
}
```

I can't think of any examples where this pattern would have worked without `try`, a direct reference to `module.a` would have produces a cycle previously too, and invalid outputs would have given `Error: Unsupported attribute` without `try` to catch the error. I'm not sure yet if it's possible to resolve this unique use of `try`, given that it previously it would have only worked out with the correct values by chance when there was no edge to resolve the evaluation order.

**Comment by favoretti** [comment]
@jbardin Thanks for looking into this. Let us try and untangle the loop to verify that the scenario you poste above does represent what we've been accidentally abusing and get back to you on that.
