### PR TITLE
command: Fix stale lock when exiting early

### LINKED ISSUE #23318: Missing provider failure case leaves s3 lock in place
```
Terraform v0.12.13
+ provider.aws v2.34.0
+ provider.google v2.18.1
+ provider.template v2.1.2
+ provider.vault v2.2.0
```

### Terraform Configuration Files
Attempt to use a Google Cloud resource without a relevant provider being declared

### Expected Behavior
Lock should be removed in event of failure case.

### Actual Behavior
Error on `terraform import` (correct)
```
Error: provider.google-beta: no suitable version installed
  version requirements: "(any version)"
  versions installed: none
```

And next operation:
```
Error: Error locking state: Error acquiring the state lock: ConditionalCheckFailedException: The conditional request failed
	status code: 400, request id: SL3JPK86NVLJITHD2I5E6D9PHJVV4KQNSO5AEMVJF66Q9ASUAAJG
Lock Info:
  ID:        53b7efb8-a7a7-a0c3-f55f-73aee25c8472
  Path:      [redacted].tfstate
  Operation: OperationTypeInvalid
  Who:       joe@Joes-MacBook-Pro.local
  Version:   0.12.13
  Created:   2019-11-08 10:55:32.551892 +0000 UTC
  Info:
```

Lock never gets releases after the import failure.

### Steps to Reproduce
1. Create a state stored in s3
2. Create a new google resource, without a appropriate provider
3. Run (in my case `terraform import` on the google resource.

### PR DESCRIPTION
**Pull request by alisdair**
If an error occurs on creating the context for console or import, we would fail to unlock the state. Fix this by unlocking slightly earlier. Affects console and import commands.

Fixes #23318.

Also, while I was making these changes:

- Remove the no-op unlock from the graph command, which followed the same code pattern. graph never actually acquires a lock, so rather than applying the same fix, I thought it best to remove the code.
- Remove a now-unused test fixture which was almost reusable for this change, but not quite.

### CODE REVIEW

File: command/import.go [hunk 1]
```diff
@@ -203,20 +203,20 @@ func (c *ImportCommand) Run(args []string) int {
 
 	// Get the context
 	ctx, state, ctxDiags := local.Context(opReq)
-	diags = diags.Append(ctxDiags)
-	if ctxDiags.HasErrors() {
-		c.showDiagnostics(diags)
-		return 1
-	}
 
-	// Make sure to unlock the state
```
Comment (pselle) [inline command/import.go]: I don't think this comment needs to be deleted!
