### PR TITLE
provider/aws - CloudFront custom_error_response fixes for missing

### LINKED ISSUE #6324: AWS aws_cloudfront_distribution custom_error_response error
Hi,

Started using the Cloudfront distribution (AWS) resource and hit a problem.
When defining `custom_error_response` block and leaving `response_code` and `response_page_path` (both optional attributes) undefined i get an error like:
```
...
aws_cloudfront_distribution.cf: Modifying...
  custom_error_response.#:                               "0" => "1"
  custom_error_response.860345937.error_caching_min_ttl: "" => "30"
  custom_error_response.860345937.error_code:            "" => "404"
  custom_error_response.860345937.response_code:         "" => ""
  custom_error_response.860345937.response_page_path:    "" => ""
Error applying plan:

1 error(s) occurred:

* aws_cloudfront_distribution.cf: IllegalUpdate: Your request must specify both ResponsePagePath and ResponseCode together or both should be empty.
	status code: 400, request id: c08f70b1-0ad0-11e6-8cec-59ec2c8f45a1

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

The code block in question inside the resource looks like:
```
custom_error_response {
    error_caching_min_ttl = 30
    error_code            = 404
    # response_code
    # response_page_path
  }
```

Haven't found any way of bypassing this yet except providing these 2 values...
But as it is not mandatory i would rather not. Hope there is  a solution.

My example is when i am trying to add the `custom_error_response` to an existing CloudFront resource.
Same error appears on a resource that is being created when the two values are omitted.

Kristjan

### PR DESCRIPTION
**Pull request by jrnt30**
- Omit custom_error_response response_* fields when not explicitly set via config for
SDK call
- Adding a test case to ensure that the response_error gets converted
to an empty string properly, versus "0". (Thanks @vancluever)

Fixes #6324

### CODE REVIEW

**Comment by stack72** [comment]
@jrnt30 what issue dies this fix? I don't believe the linked one is correct :)

**Comment by jrnt30** [comment]
@stack72 Sorry about that, updated.

**Comment by stack72** [comment]
Nps :) Just want to make sure we link it back to the right bug

File: builtin/providers/aws/cloudfront_distribution_configuration_structure.go [hunk 1]
```diff
@@ -719,12 +719,15 @@ func expandCustomErrorResponse(m map[string]interface{}) *cloudfront.CustomError
 	if v, ok := m["error_caching_min_ttl"]; ok {
 		er.ErrorCachingMinTTL = aws.Int64(int64(v.(int)))
 	}
-	if v, ok := m["response_code"]; ok {
+	if v, ok := m["response_code"]; ok && v.(int) != 0 {
 		er.ResponseCode = aws.String(strconv.Itoa(v.(int)))
+	} else {
+		er.ResponseCode = aws.String("")
```
Comment (stack72) [inline builtin/providers/aws/cloudfront_distribution_configuration_structure.go]: Do we actually want to send an empty string here or just omit it from the request completely?

Comment (jrnt30) [inline builtin/providers/aws/cloudfront_distribution_configuration_structure.go]: We do.  If the element is missing AWS will error out unless they are present (and in our case empty).

Comment (vancluever) [inline builtin/providers/aws/cloudfront_distribution_configuration_structure.go]: @stack72, as @jrnt30 mentioned, this is actually necessary, because the attribute is `TypeInt`, but the API and SDK expect `string`. There's a breakdown in the conversion between @jrnt30 in the referenced issue.

The reasoning for keeping `response_code` as a `TypeInt` is three-fold: 
 * It's the HTTP response code that needs to be sent back (and hence can only be int)
 * It's that way in CloudFormation (which is what I was using as my reference implementation as much as possible)
 * `cloudfront.CustomErrorResponse.ErrorCode` (the incoming error code) is `*int64`, so it's kind of odd that this would be a `*string`.

As such, we have to set this to `""`, as the zero value of `int`, `0`, converts to `"0"` with `strconv.Itoa()`, versus an empty string.

Comment (stack72) [inline builtin/providers/aws/cloudfront_distribution_configuration_structure.go]: Got it! Just had to check :)

**Comment by stack72** [comment]
Currently running the tests on this (they take a long time!) - will post the results when they are done

**Comment by vancluever** [comment]
@stack72 yeah, if you are testing manually, you can set `TF_TEST_CLOUDFRONT_RETAIN=1` to get thru the tests faster, if you don't mind deleting the disabled distributions afterwards :)

**Comment by stack72** [comment]
@jrnt30 / @vancluever 

Just a FYI, as the tests were running I just saw this error:

```
ake testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSCloudFrontDistribution' 2>~/tf.log
==> Checking that code complies with gofmt requirements...
/Users/stacko/Code/go/bin/stringer
go generate $(go list ./... | grep -v /vendor/)
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSCloudFrontDistribution -timeout 120m
=== RUN   TestAccAWSCloudFrontDistribution_S3Origin
--- PASS: TestAccAWSCloudFrontDistribution_S3Origin (896.46s)
=== RUN   TestAccAWSCloudFrontDistribution_customOrigin
--- PASS: TestAccAWSCloudFrontDistribution_customOrigin (792.49s)
=== RUN   TestAccAWSCloudFrontDistribution_multiOrigin
--- PASS: TestAccAWSCloudFrontDistribution_multiOrigin (1909.30s)
=== RUN   TestAccAWSCloudFrontDistribution_noOptionalItemsConfig
--- FAIL: TestAccAWSCloudFrontDistribution_noOptionalItemsConfig (881.96s)
	testing.go:172: Step 0 error: Check failed: Check 1/1 error: Not found: aws_cloudfront_distribution.no_optional_items
```

The last few are still running but at least 1 fails

**Comment by jrnt30** [comment]
Thank you...There will be another, somehow I reversed the names when
merging for the two test case resources.

**Comment by jrnt30** [comment]
`
***********
BEFORE: 
***********

17:48 $ TF_TEST_CLOUDFRONT_RETAIN=1 TF_ACC=1 envhcain personal  make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSCloudFrontDistribution' 2>tf.log
==> Checking that code complies with gofmt requirements...
/Users/justinn/Development/go/bin/stringer
go generate $(go list ./... | grep -v /vendor/)
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSCloudFrontDistribution -timeout 120m
=== RUN   TestAccAWSCloudFrontDistribution_S3Origin
--- PASS: TestAccAWSCloudFrontDistribution_S3Origin (12.33s)
=== RUN   TestAccAWSCloudFrontDistribution_customOrigin
--- PASS: TestAccAWSCloudFrontDistribution_customOrigin (4.31s)
=== RUN   TestAccAWSCloudFrontDistribution_multiOrigin
--- PASS: TestAccAWSCloudFrontDistribution_multiOrigin (12.97s)
=== RUN   TestAccAWSCloudFrontDistribution_noOptionalItemsConfig
--- FAIL: TestAccAWSCloudFrontDistribution_noOptionalItemsConfig (3.77s)
  testing.go:172: Step 0 error: Check failed: Check 1/1 error: Not found: aws_cloudfront_distribution.no_optional_items
=== RUN   TestAccAWSCloudFrontDistribution_noCustomErrorResponseConfig
--- FAIL: TestAccAWSCloudFrontDistribution_noCustomErrorResponseConfig (4.00s)
  testing.go:172: Step 0 error: Check failed: Check 1/1 error: Not found: aws_cloudfront_distribution.no_custom_error_responses
FAIL
exit status 1
FAIL  github.com/hashicorp/terraform/builtin/providers/aws  37.408s

***********
AFTER:
***********

17:42 $ TF_TEST_CLOUDFRONT_RETAIN=1 TF_ACC=1 envhcain personal  make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSCloudFrontDistribution' 2>tf.log
==> Checking that code complies with gofmt requirements...
/Users/justinn/Development/go/bin/stringer
go generate $(go list ./... | grep -v /vendor/)
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSCloudFrontDistribution -timeout 120m
=== RUN   TestAccAWSCloudFrontDistribution_S3Origin
--- PASS: TestAccAWSCloudFrontDistribution_S3Origin (12.35s)
=== RUN   TestAccAWSCloudFrontDistribution_customOrigin
--- PASS: TestAccAWSCloudFrontDistribution_customOrigin (4.07s)
=== RUN   TestAccAWSCloudFrontDistribution_multiOrigin
--- PASS: TestAccAWSCloudFrontDistribution_multiOrigin (11.38s)
=== RUN   TestAccAWSCloudFrontDistribution_noOptionalItemsConfig
--- PASS: TestAccAWSCloudFrontDistribution_noOptionalItemsConfig (3.92s)
=== RUN   TestAccAWSCloudFrontDistribution_noCustomErrorResponseConfig
--- PASS: TestAccAWSCloudFrontDistribution_noCustomErrorResponseConfig (5.05s)
PASS
ok    github.com/hashicorp/terraform/builtin/providers/aws  36.800s
`

**Comment by stack72** [comment]
@jrnt30 

thanks so much for fixing this up! This LGTM now :)

Paul
