### PR TITLE
Resource for_each

### LINKED ISSUE #17179: for_each attribute for creating multiple resources based on a map
Hi,

We are missing a better support for loops which would be based on keys, not on indexes.

Below is an example of the problem we currently have and would like Terraform to address:

* We have a list of Azure NSG (Network Security Group) rules defined in a hash. E.g.
```
locals {
  rules = {
    rdp_from_onprem = {
      priority         = 100
      protocol         = "TCP"
      destination_port = "3389"
      source_address   = "10.0.0.0/8"
    }

    winrm_from_onprem = {
      priority         = 110
      destination_port = "5985-5986"
      source_address   = "10.0.0.0/8"
    }

    dynatrace_security_gateway = {
      priority         = 120
      destination_port = "9999"
    }
  }
}
```

* This allows us to keep the Terraform resource definition DRY and use a loop to create all the rules:
```
resource "azurerm_network_security_rule" "allow-in" {
  count                       = "${length(keys(local.rules))}"
  name                        = "allow-${element(keys(local.rules), count.index)}-in"
  direction                   = "Inbound"
  access                      = "Allow"
  priority                    = "${lookup(local.rules[element(keys(local.rules), count.index)], "priority")}"
  protocol                    = "${lookup(local.rules[element(keys(local.rules), count.index)], "protocol", "*")}"
  source_port_range           = "*"
  destination_port_range      = "${lookup(local.rules[element(keys(local.rules), count.index)], "destination_port", "*")}"
  source_address_prefix       = "${lookup(local.rules[element(keys(local.rules), count.index)], "source_address", "*")}"
  destination_address_prefix  = "${lookup(local.rules[element(keys(local.rules), count.index)], "destination_address", "*")}"
  resource_group_name         = "${azurerm_resource_group.resource_group.name}"
  network_security_group_name = "${azurerm_network_security_group.nsg.name}"
}
```

* So far, so good. However since the resources and their state are uniquely identified by the index and not by their name, we can't simply change the rules later.
  * We can add new rules only at the end of the hash.
  * We can remove rules only at the end of the hash.
  * We can modify the rules, as long as their position in the hash doesn't change.
  * **But we can never remove any other rule or change their position in the hash.** This seems to be very restrictive and basically means we had to stop using this approach and define all individual rules as individual _azurerm_network_security_rule_ resources.

As you can guess, if we e.g. remove the first item from the hash, Terraform would not see that as a removal of the first resource (index 0), but rather removal of the last resource (index 2) and a related unexpected change of all the other resources (old index 1 becomes new index 0, old index 2 becomes new index 1).

**Unfortunately this can also cause Azure provider to fail**, because it may get into a conflict where an actual resource (old index 1) still exists in Azure, but Terraform now tries to modify the actual resource (old index 0) to have the same properties, but that is not possible (e.g. NSG _priority_ and _port_ have to be unique).

I've shown an example with 3 rules, but in reality we can have 50 rules and the tf file is 5x longer and more difficult to manage with individual resources compared to using a hash.

We would like to use hashes in Terraform in such a way that a position of an element inside a hash doesn't matter. That's why many other languages provide two ways of looping - by index (e.g. ```for i=0; i<list.length;i++```) and by key (```foreach key in list```).

I'm sure that smart guys like you can figure out how to make this work in Terraform.

Thanks

### PR DESCRIPTION
**Pull request by pselle**
Allow instances to be created according to a map or a set of strings. Closes #17179

```
locals {
  little_map = {
    a = 1
    b = 2
  }
}
resource "random_pet" "server" {
  for_each = little_map
}

locals {
  lil_strings = list("x", "y")
}
resource "random_pet" "server" {
  for_each = toset(lil_strings)
}
```

Things that won't work:
- null
- lists (that are a list and not a set)
- random types (string, number, w/e)
- sets that aren't of type string

### CODE REVIEW

File: terraform/node_resource_plan.go [hunk 1]
```diff
@@ -77,6 +78,12 @@ func (n *NodePlannableResource) DynamicExpand(ctx EvalContext) (*Graph, error) {
 		return nil, diags.Err()
 	}
 
+	forEachMap, forEachDiags := evaluateResourceForEachExpression(n.Config.ForEach, ctx)
+	if forEachDiags.HasErrors() {
+		fmt.Println("hit the hasErrors block")
```
Comment (pselle) [inline terraform/node_resource_plan.go]: This remains a question for me -- I added a bit that checks this earlier (at eval_validate), and thus diags get exposed to the user, but I still am confused as to why these diags don't get exposed to the user. Having it does prevent a panic though.

File: terraform/eval_for_each.go [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+
+import (
+	"fmt"
+
+	"github.com/hashicorp/hcl2/hcl"
+	"github.com/hashicorp/terraform/tfdiags"
+	"github.com/zclconf/go-cty/cty"
+)
+
+// evaluateResourceCountExpression interprets a "for_each" argument on a resource.
```
Comment (mildwonkey) [inline terraform/eval_for_each.go]: copy-pasta :) 
```suggestion
// evaluateResourceForEachExpression interprets a "for_each" argument on a resource.
```

File: website/docs/configuration/resources.html.md [hunk 3]
```diff
@@ -299,6 +300,52 @@ intended. The practice of generating multiple instances from lists should
 be used sparingly, and with due care given to what will happen if the list is
 changed later.
 
+### `for_each`: Multiple Resource Instances Defined By a Map
```
Comment (mildwonkey) [inline website/docs/configuration/resources.html.md]: `for_each` should be able to work with a list or a map (even if it doesn't now, it should before we merge this)

**Comment by mildwonkey** [comment]
This is great!

`count` doesn't work with `null`, though I personally expected it to work, and I suspect we'll consider adding that in the future (in my mind, `null` count means: leave out the `count` expression altogether, but others might expect it to be equivalent to `0` - the ambiguity may explain why we don't allow null, and instead have the user write a conditional).  

I _think_ lists and sets (other than strings) should be supported before this gets released; I'm not as sure about how to implement sets (we'd either need to convert them to lists so we have an index, or have users use the `tolist()` function) but we should at least think about it. Lists and sets should have unified types (so no set of `["1", 2, true]`)

I'm also curious about the errors that aren't being surfaced to the user - I wouldn't mind spending some time looking into that!

File: terraform/eval_for_each.go (hunk 2 above)
Comment (pselle) [reply terraform/eval_for_each.go]: 🙈 ha, thank you!!

File: website/docs/configuration/resources.html.md (hunk 3 above)
Comment (pselle) [reply website/docs/configuration/resources.html.md]: Will discuss this in chat :)

Comment (mildwonkey) [reply website/docs/configuration/resources.html.md]: I hereby revoke my comment! MAPS!!!

File: website/docs/configuration/resources.html.md [hunk 4]
```diff
@@ -299,6 +300,52 @@ intended. The practice of generating multiple instances from lists should
...
+  ami           = "ami-a1b2c3d4"
+  instance_type = "t2.micro"
+  subnet_id     = each.key # note, each.key and each.value will be the same on a set
+
+  tags {
+    Name = "Server ${each.key}"
+  }
+}
+```
+
```
Comment (pselle) [inline website/docs/configuration/resources.html.md]: A wise addition here would be to expand a little on what's happening to create the instances (and how they are keyed) which should help in making it clear why we don't allow `list` inputs to `for_each`, or sets of values other than `string`

Comment (wyardley) [reply website/docs/configuration/resources.html.md]: Will the actual resource names be `aws_instance.server.foo` (where foo is the key in the current iteration), or `aws_instance.server[0]`?

Comment (mildwonkey) [reply website/docs/configuration/resources.html.md]: Hi @wyardley, good question!

Resources created with for_each are created from a map or set, not a list, and cannot be indexed with `[0]`. They will be referenced by name, such as the `aws_instance.server.foo` example shown here.

File: terraform/eval_for_each.go [hunk 5]
```diff
@@ -0,0 +1,64 @@
...
+			Summary:  "Invalid for_each argument",
+			Detail:   fmt.Sprintf(`The "for_each" argument must be a map, or set of strings.`),
+			Subject:  expr.Range().Ptr(),
+		})
+		return nil, diags
+	}
+
+	if forEachVal.Type().IsSetType() {
+		// QUESTION: Can I get one elem out of the set to check this, or do I need
+		// to do the whole iterator business. This only looks at the first item before it returns
```
Comment (apparentlymart) [inline terraform/eval_for_each.go]: `Set` is a collection type kind, so all elements are required to have the same type, and that element type is part of the set type.

So you can write this as something like:

```go
if forEachVal.Type().IsSetType() {
    if forEachVal.Type().ElementType() != cty.String {
        // (error message)
    }
    return forEachVal.AsValueMap(), nil
}
```

File: terraform/node_resource_plan.go (hunk 1 above)
Comment (apparentlymart) [reply terraform/node_resource_plan.go]: Hmm, that _is_ interesting... I think that suggests a bug in how the graph walk deals with `DynamicExpand` where it's not handling returned diagnostics properly, and we've probably not been seeing it just because other codepaths happen to catch all the same errors.

However, I went to find the caller of this and found that at least _that_ call seems to be dealing with it okay:

https://github.com/hashicorp/terraform/blob/86e6481cc661b2ba694d353aab6d11838c066c7c/terraform/graph.go#L103-L107

So if this is a bug then it must be somewhere further up the call stack, I guess.

File: terraform/node_resource_plan_instance.go [hunk 6]
```diff
@@ -34,25 +34,18 @@ var (
...
-	stateId := NewLegacyResourceInstanceAddress(addr).stateId()
-
-	// Determine the dependencies for the state.
-	stateDeps := n.StateReferences()
-
 	// Eval info is different depending on what kind of resource this is
 	switch addr.Resource.Resource.Mode {
 	case addrs.ManagedResourceMode:
-		return n.evalTreeManagedResource(addr, stateId, stateDeps)
+		return n.evalTreeManagedResource(addr)
```
Comment (apparentlymart) [inline terraform/node_resource_plan_instance.go]: Nice to see that these old state-specific address forms are finally gone here! :tada:

File: terraform/eval_for_each.go [hunk 7]
```diff
@@ -0,0 +1,64 @@
...
+	"github.com/hashicorp/terraform/tfdiags"
+	"github.com/zclconf/go-cty/cty"
+)
+
+// evaluateResourceForEachExpression interprets a "for_each" argument on a resource.
+//
+// Returns a cty.Value map, and diagnostics if necessary
+func evaluateResourceForEachExpression(expr hcl.Expression, ctx EvalContext) (forEach map[string]cty.Value, diags tfdiags.Diagnostics) {
+	if expr == nil {
+		return nil, nil
```
Comment (apparentlymart) [inline terraform/eval_for_each.go]: It looks like this is using `nil` to signal that `for_each` isn't set, vs. an empty map to signal that `for_each` is set to an expression that returned an empty map.

That does seem okay to me, but the usual idiom/convention in Go is for a `nil` map and an empty map to be considered equivalent, so I think worth noting that specifically in the doc comment so that the reader can see that we're making a distinction that wouldn't normally be significant.

File: terraform/eval_for_each.go (hunk 5 above)
Comment (pselle) [reply terraform/eval_for_each.go]: Perfect, thank you!

File: terraform/eval_for_each.go (hunk 7 above)
Comment (pselle) [reply terraform/eval_for_each.go]: I've noted in the doc comment how this using nil -- since `count` evaluation is using `-1` as its "special value" I believe it makes sense to do that here as well.

File: terraform/node_resource_plan.go (hunk 1 above)
Comment (pselle) [reply terraform/node_resource_plan.go]: Ok, that's sounding like "not something to deal with here" --- thanks for the additional context, I'm curious when we'll see this show up again 🤔 Not sure how to word an issue to open, but maybe we'll remember this in the future 🤷‍♀

File: terraform/eval_for_each.go (hunk 7 above)
Comment (apparentlymart) [reply terraform/eval_for_each.go]: LGTM!

File: website/docs/configuration/resources.html.md (hunk 4 above)
Comment (pselle) [reply website/docs/configuration/resources.html.md]: I've added another paragraph to this page (in this changeset) that hopefully makes this clearer!

**Comment by Skaronator** [comment]
How are the resources managed in the state file? Is it still a array like with count or do we get the actual keys in the state file?

File: website/docs/configuration/resources.html.md (hunk 4 above)
Comment (pselle) [reply website/docs/configuration/resources.html.md]: Correction: They'll be referenced by key using indexing syntax: `aws_instance.server["foo"]`. I'll be updating the docs to reflect this appropriately.

**Comment by pselle** [comment]
@Skaronator Here's a statefile showing instances created with `for_each`. https://gist.github.com/pselle/140c5f21c96b66f417796ed6ca000c1d, they are identified with the `index_key` inside the `instances` array of the given resource. This is the configuration that generated this:

```
locals {
  little_map = {
    a = 1
    b = 2
  }
}
resource "random_pet" "with_for_each" {
  for_each = local.little_map
}

resource "random_pet" "with_count" {
  count = 2
}

resource "random_pet" "no_iterator" {}
```

**Comment by Skaronator** [comment]
@pselle Ah thats great! So _b_ wouldn't get recreated when I remove _a_ from the map. (Since its now on Index 0 instead of 1)

File: configs/resource.go [hunk 8]
```diff
@@ -111,13 +111,15 @@ func decodeResourceBlock(block *hcl.Block) (*Resource, hcl.Diagnostics) {
...
-			Severity: hcl.DiagError,
-			Summary:  "Reserved argument name in resource block",
-			Detail:   fmt.Sprintf("The name %q is reserved for use in a future version of Terraform.", attr.Name),
-			Subject:  &attr.NameRange,
-		})
+		// Cannot have count and for_each on the same resource block
+		if r.Count != nil {
+			diags = append(diags, &hcl.Diagnostic{
+				Severity: hcl.DiagError,
+				Summary:  "Invalid config, cannot use count and for_each in same block",
```
Comment (apparentlymart) [inline configs/resource.go]: The sentence fragment here made me trip over reading this sentence a bit. :confounded: 

Most of our "modern" error messages try to start with a concise statement of the broad problem as the summary and then elaborate more in the detail. Since this is a situation where it's the combination of two things that is invalid rather than one thing, the usual "Invalid <whatever it is>" summary won't work here, but maybe something like this?

```
Error: Invalid combination of "count" and "for_each"

  <source snippet>

The "count" and "for_each" meta-arguments are mutually-exclusive, because each one chooses
a different identifier type for the resource instances.
```

(This term "meta-arguments" has always felt a little weird to me, but that's what it's called throughout the documentation and so hopefully using that terminology in the error message will help users find further documentation about these features if they are unsure how to proceed.)

**Comment by apparentlymart** [comment]
Sorry I didn't catch this on the previous review, but it only just occurred to me while I was staring some similar code...

I think the `References` implementation of `NodeAbstractResource` must also be extended to include references from the `for_each` expression, similarly to how it includes references in the `count` expression:

https://github.com/hashicorp/terraform/blob/1a89165705d3577468e96cb4fbde9a357ab70b16/terraform/node_resource_abstract.go#L188-L189

Without this, Terraform wouldn't notice that a particular object is referenced in the `for_each` expression and thus create the dependency edge needed to ensure that we wait until all of the data is available before evaluating it.

I'm sorry if I missed something somewhere else in this diff that's catching that.

This sort of thing unfortunately tends to be quite awkward to test, because without it what we have is a race condition and thus not a deterministic test failure. We have two existing strategies for testing this:

* In `graph_builder_plan_test.go` we test the plan graph builder with some contrived inputs and check that the resulting graph has the expected shape. This is a good way to get a deterministic test, but these tests tend to be pretty sensitive to changes elsewhere because they run the whole plan graph builder (rather than just the reference-analysis code) and thus any other changes to the graph building logic tends to change the outcomes.
* In `context_plan_test.go` (and other context tests) we have a few cases where we use a mocked provider for one of the resources that intentionally has a short delay in the `PlanResourceChange` implementation, thus making it very likely that any race condition would be detected. This is nice because it can more directly test for the behavior we're looking for, but it's not so nice that it forces an artificial slowdown in the test and _still_ isn't truly deterministic (if, e.g., something else on the system interferes and creates delays).

**Comment by pselle** [comment]
@apparentlymart Very good note -- I'll do some digging to check on this/make sure it works/fix it if it doesn't.

**Comment by apparentlymart** [comment]
Looking at this again with fresh eyes, I remember there is a third testing strategy out there:

* There's at least one test (which I encountered in 0.12 test update work) where it uses one of the [`sync`](https://godoc.org/sync) package's primitives to _force_ one resource to hang until after another one is processed. That's similar to the timer-based trick I mentioned before but without the risk of other days causing the test result to wobble. That approach does have the significant drawback that one of its failure modes is to deadlock the test run altogether, which is what had happened when I encountered that test. So... I dunno if I would add more tests like that, but I suppose it's an option if nothing else seems practical.

**Comment by i870495** [comment]
Hi,

Are we really able to use for_each inside resource. I am using terraform 12.4 but cannot use for_each to create multiple azure network interfaces.

Error : 
rror: Reserved argument name in resource block

  on main.tf line 81, in resource "azurerm_network_interface" "vm_instance_nic":
  81:   for_each            = local.testmap

The name "for_each" is reserved for use in a future version of Terraform.


Thanks,
Balu Rajendran

**Comment by Skaronator** [comment]
@i870495 This feature hasn't been merged yet nor has it been released.

**Comment by i870495** [comment]
@Skaronator - Thank you !!!

**Comment by pselle** [comment]
@apparentlymart Re: references

The following is a simple example demonstrating referencing another resource in the expression passed to `for_each` -- I was able to see this working without issue

```
resource "random_pet" "with_for_each" {
  for_each =  {
    cool_pet = random_pet.no_iterator.id
  }
  separator = each.value
}

resource "random_pet" "no_iterator" {}
```

I've added a reference in the testdata used by Context2Plan; I'd be interested in more info on how to introspect there, reading some of the other tests, it's not very clear how to introspect (as when I started using `checkVals`, I started getting some values that seemed to be bleeding in from another test's schema definition).

I could of course add to the abstract node ref but without proof that it's necessary, I'm not inclined to do so.

**Comment by apparentlymart** [comment]
If the dependency is not present, Terraform will think it can work on both of those resource blocks concurrently, so it would be undefined which order they would resolve in. With resources that resolve essentially instantly, it's quite possible for them to complete in the right order just by accident, unfortunately.

One way to verify this without writing any further code would be to `terraform plan` that test configuration with `TF_LOG=trace` set and watch the logs about graph construction... the last graph construction in the log (building the plan graph) should include something like this:

```
2019/07/15 10:15:33 [TRACE] Completed graph transform *terraform.TransitiveReductionTransformer with new graph:
meta.count-boundary (EachMode fixup) - *terraform.NodeCountBoundary
  random_pet.with_for_each - *terraform.NodePlannableResource
provider.random - *terraform.NodeApplyableProvider
provider.random (close) - *terraform.graphNodeCloseProvider
  random_pet.with_for_each - *terraform.NodePlannableResource
random_pet.no_iterator - *terraform.NodePlannableResource
  provider.random - *terraform.NodeApplyableProvider
random_pet.with_for_each - *terraform.NodePlannableResource
  random_pet.no_iterator - *terraform.NodePlannableResource
root - terraform.graphNodeRoot
  meta.count-boundary (EachMode fixup) - *terraform.NodeCountBoundary
  provider.random (close) - *terraform.graphNodeCloseProvider
------
2019/07/15 10:15:33 [DEBUG] Starting graph walk: walkPlan
```

The important part of this is the dependencies for `random_pet.with_for_each`:

```
random_pet.with_for_each - *terraform.NodePlannableResource
  random_pet.no_iterator - *terraform.NodePlannableResource
```

This shows that (in the quick example configuration I wrote using `count` on my local tree) `random_pet.with_for_each` depends on `random_pet.no_iterator`, which is what I'd expect. I'd expect to see the same sort of thing with `for_each` in your example, if Terraform is correctly finding the dependency here.

(You will likely see multiple `TransitiveReductionTransformer` references like this in the logs. The one just before `Starting graph walk: walkPlan` is the main one to look at here, because planning is the phase where we'll expand out the `for_each` expression and thus the one where this dependency is needed.)

File: website/docs/configuration/resources.html.md [hunk 9]
```diff
@@ -143,7 +143,8 @@ Terraform CLI defines the following meta-arguments, which can be used with
 any resource type to change the behavior of resources:
 
 - [`depends_on`, for specifying hidden dependencies][inpage-depend]
-- [`count`, for creating multiple resource instances][inpage-count]
+- [`count`, for creating multiple resource instances according to a count][inpage-count]
+- [`for_each`, to create multiple instances according to a map][inpage-for_each]
```
[the remark this answers is not in the document]
Comment (pselle) [reply website/docs/configuration/resources.html.md]: Made some updates to elevate that a bit more!

**Comment by pselle** [comment]
For PR visibility: added the change (and a test) to make sure edges created by references are caught.

**Comment by halberom** [comment]
Testing of the sync_hdfs is currently failing with

```
Traceback (most recent call last):
  File "/usr/local/bin/ipa_tools_sync_hdfs", line 10, in <module>
    sys.exit(sync_hdfs())
  File "/usr/local/lib/python2.7/dist-packages/Cli/ipa_sync_hdfs.py", line 66, in sync_hdfs
    ldap_user_list = ldap.list_ldap_users(basedn, args.hostname)
  File "/usr/local/lib/python2.7/dist-packages/ModuleApi/JSUtilities/SimpleLdap.py", line 26, in list_ldap_users
    result = self.execute_command(cmd, options)
  File "/usr/local/lib/python2.7/dist-packages/ModuleApi/JSUtilities/KerberisedCommand.py", line 28, in execute_command
    raise ModuleException("Exception in {} module: '{}' - '{}'".format(cls.__name__, stdout, stderr))
ModuleApi.ModuleException.ModuleException: {"source": {"line": 28, "method": "execute_command", "file": "/usr/local/lib/python2.7/dist-packages/ModuleApi/JSUtilities/KerberisedCommand.py"}, "message": "Exception in SimpleLdap module: '' - 'Inappropriate authentication (48)\nAdditional information: Anonymous access is not allowed.\n'", "code": 400, "type": "ModuleException"}
```

Quoting Tim

> anonymous auth was removed after pen test results, with implementation being late last year, so i suspect that this has never run successfully in prod due to the arg parse issue. It may be a case of adding a flag to the ldap commands to let them use the kerberos token, although i guess that is what the kerberos command wrapper is supposed to do.  It may also be the case that you need to provide a bind dn for ldap connection and the kerberos is already taken care of.

**Comment by bentterp** [comment]
TL;DR: I think that empty maps should be handled by doing nothing, instead of throwing errors.

```
Error: Invalid for_each argument

  on ../../../../IaC/aztfmod_nwk/subnets.tf line 133, in resource "azurerm_network_security_group" "nsgs":
 133:   for_each = local.subnetmap

The "for_each" argument must be a map, or set of strings.

```
I didn't understand how that can be because the variable is defined like this:
```
locals{
  subnetmap = merge(
      { for subnet in var.subnets_byname: subnet => cidrsubnet(var.vnet_cidr, local.subnetaddbits, index(var.subnets_byname,subnet)) },
      { for subnet in var.subnets_bybits: subnet.name => cidrsubnet(var.vnet_cidr, subnet.bits, subnet.net) },
      { for subnet in var.subnets_bycidr: subnet.name => subnet.cidr }
  )
}

```
And I thought that merge() could only produce a map as output.....

.... turns out the map is empty:
```
$ terraform output local_subnetmap
{}
$
```

Of course I need to test with a map containing items also, but this was actually a good point even if un-intended.

**Comment by bentterp** [comment]
```
$ terraform output local_subnetmap
{
  "back" = "10.141.0.32/27"
  "front" = "10.141.0.0/27"
}
$
```

Same result  😰

**Comment by bentterp** [comment]
When I replace the ```for_each = local.subnetmap``` with
```
  for_each = {
  "back" = "10.141.0.32/27"
  "front" = "10.141.0.0/27"
}
```
then it seems to work better.

Is this intentional? for_each becomes much less useful if we can't use variables and have to hard-code everything.

**Comment by pselle** [comment]
> TL;DR: I think that empty maps should be handled by doing nothing, instead of throwing errors.

They indeed should!

And no, it is definitely not intentional -- you should be able to reference variables. In your comment, the line `for_each = local.subnetmap` should be `for_each = local.local_subnetmap` based on what you've named the variable, and an empty map works then.

> I've also tried with var.subnetmap instead and passing that into the module. Same result

I am curious about this case, if you've got some examples!

Thank you for testing, and in general, something this makes me think is that the type error would be more useful if it tells you the type you attempted to pass to it, so I'll look into that.

**Comment by bentterp** [comment]
I'll share some more of the code from the office tomorrow, bedtime soon
over here.
Can't write the Go code but happy if I can help by testing.

**Comment by tmccombs** [comment]
I got a panic while trying to run, I'll see if I can get a minimal reproduction:
```
panic: value is not known

goroutine 136 [running]:
github.com/zclconf/go-cty/cty.Value.LengthInt(0x2223820, 0xc00045fb30, 0x1aaac60, 0x3325a20, 0x1)
        /home/thayne/dev/terraform/vendor/github.com/zclconf/go-cty/cty/value_ops.go:871 +0x271
github.com/hashicorp/terraform/terraform.evaluateResourceForEachExpression(0x2222520, 0xc00067c480, 0x2255460, 0xc0009731e0, 0x7f4bb1365460, 0x0, 0x0, 0x0)
        /home/thayne/dev/terraform/terraform/eval_for_each.go:60 +0x504
github.com/hashicorp/terraform/terraform.(*EvalValidateResource).Eval(0xc0005b83c0, 0x2255460, 0xc0009731e0, 0x2, 0x2, 0x0, 0x0)
        /home/thayne/dev/terraform/terraform/eval_validate.go:380 +0x1b52
github.com/hashicorp/terraform/terraform.EvalRaw(0x21e1cc0, 0xc0005b83c0, 0x2255460, 0xc0009731e0, 0x0, 0x0, 0x0, 0x0)
        /home/thayne/dev/terraform/terraform/eval.go:57 +0x131
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc0005161a0, 0x2255460, 0xc0009731e0, 0x2, 0x2, 0xedc345, 0x21e1cc0)
        /home/thayne/dev/terraform/terraform/eval_sequence.go:20 +0xfd
github.com/hashicorp/terraform/terraform.EvalRaw(0x21e1c20, 0xc0005161a0, 0x2255460, 0xc0009731e0, 0x1a82420, 0x31db405, 0x19ef3e0, 0xc000a8a1f0)
        /home/thayne/dev/terraform/terraform/eval.go:57 +0x131
github.com/hashicorp/terraform/terraform.Eval(0x21e1c20, 0xc0005161a0, 0x2255460, 0xc0009731e0, 0xc0005161a0, 0x21e1c20, 0xc0005161a0, 0x0)
        /home/thayne/dev/terraform/terraform/eval.go:35 +0x4d
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x1ce1480, 0xc00043a0c0, 0x0, 0x0, 0x0)
        /home/thayne/dev/terraform/terraform/graph.go:90 +0xf40
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc00059ef00, 0x1ce1480, 0xc00043a0c0, 0xc0005b6400)
        /home/thayne/dev/terraform/dag/walk.go:392 +0x353
created by github.com/hashicorp/terraform/dag.(*Walker).Update
        /home/thayne/dev/terraform/dag/walk.go:314 +0xa9b

```

**Comment by tmccombs** [comment]
Here's an example that causes that error:

```
variable "names" {
  type = set(string)
}

resource "local_file" "test" {
  for_each = var.names

  content = "This is file ${each.key}"
  filename = "${path.module}/${each.key}.txt"
}
```

If you change the for_each line to use `toset(var.names)`, then it doesn't panic but I get the somewhat unhelpful error:

```
The given "for_each" argument value is unsuitable: "for_each" supports maps
and sets of strings, but you have provided a set containing type dynamic.
```

Changing the var type to `map(string)` and passing in a map also results in a panic.

**Comment by tmccombs** [comment]
If I use a local instead of a variable, I don't run into this problem.

**Comment by tmccombs** [comment]
Also, as far as the API goes, I wonder if it would make sense to implicitly convert lists to sets for the for_each argument. According to the documentation for `toset`:

> Explicit type conversions are rarely necessary in Terraform because it will convert types automatically where required. Use the explicit type conversion functions only to normalize types returned in module outputs.

So it seems a little unusual that it is necessary for `for_each`

**Comment by wyardley** [comment]
> Also, as far as the API goes, I wonder if it would make sense to implicitly convert lists to sets for the for_each argument

I had the same thought... unless it's too magical, that is probably the best behavior. However, because sets are unordered and lists could contain duplicates, are there cases where auto-converting to a set would cause unpredictable or undesirable behavior? Maybe that's why you have to explicitly convert to a set?

I know this is the wrong venue, but I really wish the original pseudo-code (where the for-each construct is an iterator _outside_ the resource) had been chosen. Is the idea that that is just too programming-y for a DSL, or is it because of technical constraints.

File: terraform/eval_for_each.go [hunk 10]
```diff
@@ -0,0 +1,65 @@
...
+				Summary:  "Invalid for_each set argument",
+				Detail:   fmt.Sprintf(`The given "for_each" argument value is unsuitable: "for_each" supports maps and sets of strings, but you have provided a set containing type %s.`, forEachVal.Type().ElementType().FriendlyName()),
+				Subject:  expr.Range().Ptr(),
+			})
+			return nil, diags
+		}
+	}
+
+	// If the map is empty ({}), return an empty map, because cty will return nil when representing {} AsValueMap
+	if forEachVal.LengthInt() == 0 {
```
Comment (tmccombs) [inline terraform/eval_for_each.go]: If you change this to 
```
if !forEachVal.IsKnown() || forEachVal.LengthInt() == 0 {
```
then it fixes the panic I saw. I don't completely understand what is going on, but I think it might evaluate it first without the injected variables, and then later evaluates it with the variables. (Maybe it is better to have a seperate branch to handle the unknown case?)

**Comment by bentterp** [comment]
Rebuilt from the bc2cb39 commit.

```
 133:   for_each = local.subnetmap

The given "for_each" argument value is unsuitable: the "for_each" argument
must be a map, or set of strings, and you have provided a value of type
dynamic.
```

Now we've narrowed it down a bit. Yes, it's a dynamic value but I'd still argue that it is indeed a map.

It doesn't make any difference if the map is a local variable or a "real" variable declared as an empty map  and called with ``` { "back" = "10.141.0.32/27", "front" = "10.141.0.0/27"  }``` as value to the module parameter.

I've even tried making it the default value in the module and not passing a value when calling the module, same error.

**Comment by bentterp** [comment]
> In your comment, the line `for_each = local.subnetmap` should be `for_each = local.local_subnetmap` based on what you've named the variable, and an empty map works then.

No that's just the name of the output in main config:
```

output "local_subnetmap" {
  value = module.nwk.subnetmap
}
```
Inside the module:
```
locals {
  subnetmap = merge(
    { for subnet in var.subnets_byname: subnet => cidrsubnet(var.vnet_cidr, local.subnetaddbits, index(var.subnets_byname,subnet)) },
    { for subnet in var.subnets_bybits: subnet.name => cidrsubnet(var.vnet_cidr, subnet.bits, subnet.net) },
    { for subnet in var.subnets_bycidr: subnet.name => subnet.cidr }
  )
}

output "subnetmap" {
  value = local.subnetmap
}
```

**Comment by bentterp** [comment]
I've made a minimal setup now where I reproduce the issue outside our corporate Terraform modules.

https://github.com/bentterp/tfbughunt

Bring your own Azure subscription and do export ARM_SUBSCRIPTION_ID=#################

The config where the module has a hardcoded local variable works as intended. The two other present the dynamic issue of having the map in a variable, both inside a module and without module usage

Interestingly, when I just declare the vaiable with a default value which is a map, I get the dynamic type error message, but if I explicitly typecast the variable then I get a crash instead, probably the same as @tmccombs encountered.

**Comment by tmccombs** [comment]
using vars directly now works.  However, if I use a variable in a local and then use that local, I get the following error:

> The given "for_each" argument value is unsuitable: the "for_each" argument
must be a map, or set of strings, and you have provided a value of type
dynamic.

Sample config:

```

variable "names" {
  type = set(string)
}

locals {
  files = {for name in var.names: name => "This is file ${name}"}
}

resource "local_file" "test" {
  for_each = tomap(local.files)

  content = each.value
  filename = "${path.module}/${each.key}.txt"

}
```

I wonder if this might be a bug in the type determination for terraform.

**Comment by tmccombs** [comment]
Ok, I think what is happening  is, when the type check is run, the type is DynamicPseudoType for the local, because we don't have the values for the variable yet. In the count evaluation, that is fine, because converting a DynamicPseudoType assumes that it will be the right type when it is provided (and then later fails if it isn't). But since the for_each eval doesn't use a conversion with a wanted type, it fails. I'm not sure what the best way to fix that is.

**Comment by bentterp** [comment]
Weird, because this config works now:
```
variable "mymap" {
  type = map
  default = { myrg1: "My Resource Group 1", myrg2: "My Resource Group 2"}
}
locals {
  mylocalmap = var.mymap
}
resource "azurerm_resource_group" "myrg" {
  for_each = local.mylocalmap
  name     = each.key
  location = "westeurope"
  tags = merge({"Description" = each.value})
}
```

What I've noticed is that I need to explicitly typecast the mymap variable, else I get the dynamic type error message. Yesterday, explicit typecasting caused a panic but with today's commits it gives the intended result.

**Comment by bentterp** [comment]
Very good testcase by @tmccombs :+1:
```
fbte61@SEA37LT16653:/c/Data/tfbughunt/for_each/localfiles$ $GOPATH/bin/terraform plan

Error: Invalid for_each argument

  on main.tf line 11, in resource "local_file" "test":
  11:   for_each = tomap(local.files)

The given "for_each" argument value is unsuitable: the "for_each" argument
must be a map, or set of strings, and you have provided a value of type
dynamic.

fbte61@SEA37LT16653:/c/Data/tfbughunt/for_each/localfiles$ cat main.tf
variable "names" {
#  type = set(string)
  default = [ "Peter", "Paul" ]
}

locals {
  files = {for name in var.names: name => "This is ${name}'s file"}
}

resource "local_file" "test" {
  for_each = tomap(local.files)

  content = each.value
  filename = "${path.root}/${lower(each.key)}.txt"

}
fbte61@SEA37LT16653:/c/Data/tfbughunt/for_each/localfiles$
```
If ```count``` is evaluating in a different manner and that works for most of us - Lord knows, I've gotten with doing things with count that should not have been done ;-) - then maybe the same type of evaluation could be used for ```for_each```?
It seems bizarre to be told that the output from the ```tomap()``` function is not of type ```map```

(bughunt repo updated, in case anybody feels like using it)

**Comment by tmccombs** [comment]
I think this fixes the dynamic type problem:

```
diff --git a/terraform/eval_for_each.go b/terraform/eval_for_each.go
index f9f4a46a8..980650c4d 100644
--- a/terraform/eval_for_each.go
+++ b/terraform/eval_for_each.go
@@ -24,6 +24,10 @@ func evaluateResourceForEachExpression(expr hcl.Expression, ctx EvalContext) (fo
 		return nil, diags
 	}
 
+	if forEachVal.Type() == cty.DynamicPseudoType {
+		return nil, diags
+	}
+
 	if forEachVal.IsNull() {
 		diags = diags.Append(&hcl.Diagnostic{
 			Severity: hcl.DiagError,
```

**Comment by bentterp** [comment]
Rebuilt against db6a6c4.
The configuration panics if the type is not obvious.
But that can be worked around with tomap() or toset()
```
variable "names" {
  type = set(string)
  default = [ "Peter", "Paul" ]
}

locals {
  files = {for name in var.names: name => "This is ${name}'s file"}
}
resource "local_file" "varfilestest" {
  for_each = var.names
  content = each.value
  filename = "${path.root}/${lower(each.key)}.txt"
}
resource "local_file" "localfilestest" {
  for_each = tomap(local.files)
  content = each.value
  filename = "${path.root}/${lower(each.key)}.txt"
}
```
Even though local.files is clearly a map, I still need to wrap it in tomap().

But as long as the documentation is clear about this, then I personally think that it's good enough.

**Comment by bentterp** [comment]
Crashlog here in case anybody feels like looking at it
https://gist.github.com/bentterp/93d90a9ff27380aa766d209c7b5bcc43

**Comment by bentterp** [comment]
Just tested a more complex map:
```
variable "complex" {
  type = map
  default = { Peter : { age : 35 , town : "Portsmouth"}, Paul: {age : 29 , town : "London"}}
}
resource "local_file" "complex" {
  for_each = var.complex
  filename = "${path.root}/${lower(each.key)}_complex.txt"
  content = <<-EOF
  ${each.key} is ${each.value.age} years old and live in ${each.value["town"]}.
  EOF
}
```

And it worked beautifully:
```
$ cat peter_complex.txt
Peter is 35 years old and live in Portsmouth.
$
```

**Comment by bentterp** [comment]
Using a map as parameter when calling a module also works as intended now:
```
$ cat main.tf
module "foreach" {
  source = "../modules/for_each_var"
  mymap = { myrg1: "My Resource Group 1", myrg2: "My Resource Group 2"}
}
$ cat ../modules/for_each_var/main.tf
variable "mymap" {
  type = map
}
resource "azurerm_resource_group" "myrg" {
  for_each = var.mymap
  name     = each.key
  location = "westeurope"
  tags = merge({"Description" = each.value})
}
$
```

**Comment by tmccombs** [comment]
> But as long as the documentation is clear about this, then I personally think that it's good enough.

We probably want to avoid panics. A helpful error message would be better.

**Comment by pselle** [comment]
@tmccombs Ben's example worked for me/works for me now, am I missing a case listed here that's still failing? 

(also, agree error > panic)

**Comment by tmccombs** [comment]
huh, Ben's example works fine for me too.

Also, as a status update, with the current code, for_each is working great for me. I can't wait for this to get merged.

**Comment by pselle** [comment]
@tmccombs Thanks for the update, and thanks to both you and @bentterp for testing out this feature! This has been so so helpful!

File: terraform/eval_for_each.go [hunk 11]
```diff
@@ -0,0 +1,73 @@
...
+	}
+
+	forEachVal, forEachDiags := ctx.EvaluateExpr(expr, cty.DynamicPseudoType, nil)
+	diags = diags.Append(forEachDiags)
+	if diags.HasErrors() {
+		return nil, diags
+	}
+
+	// No-op for dynamic types, so that these pass validation, but are then populated at apply
+	if forEachVal.Type() == cty.DynamicPseudoType {
```
Comment (apparentlymart) [inline terraform/eval_for_each.go]: When I was playing around with the latest `for_each` implementation I accidentally triggered a funny case where I got the following error in a situation where I _had_ `for_each` set:

```
Error: Reference to "each" in context without for_each

  on ../../main.tf line 113, in resource "dns_ns_record_set" "this":
 113:   nameservers = each.value.records

The "each" object can be used only in "resource" blocks, and only when the
for_each" argument is set.
```

After digging around a little, I suspect the block I attached this comment to is what led there... I managed to get into a situation where the `for_each` value was `cty.DynamicVal` by using a computed resource attribute as part of my `for_each` expression, which this codepath then treated as if it was not set at all.

In the equivalent situation for `count` we return a different error here:

```
Error: Invalid count argument

  on simple.tf line 73, in resource "null_resource" "foo":
  73:   count = uuid()

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```

We have #4149 tracking the idea of permitting unknown values in `count` (along with a potential solution), so I wonder if we should follow suit for `for_each` here and make this be a similar error for now (including the guidance about using `-target`), and then plan to treat `for_each` the same way as `count` when we design a final solution for #4149 in the future.

I lucked out here in that I created a situation where `cty.DynamicVal` was the result, but when working with resource attributes that are unknown during plan it's also possible that we'll see things like `cty.UnknownVal(cty.Set(cty.String))` here, if e.g. an AWS `availability_zones` set attribute can't be populated until apply, so to cover that I'd recommend using `!forEachVal.IsKnown()` for this case, which _includes_ `cty.DynamicVal` because it is equivalent to `cty.UnknownVal(cty.DynamicPseudoType)`, but also covers unknown values with known types.

**Comment by tmccombs** [comment]
I've made a branch at https://github.com/tmccombs/terraform/tree/resource_for_each which adds support for using for_each for data sources as well. I think it will also fix the error message for https://github.com/hashicorp/terraform/pull/21922#discussion_r307065377, although I haven't tested that.

**Comment by tmccombs** [comment]
Unfortunately `resource_name.name[*].attribute` doesn't work. However, that is a limitation of HCL, because it only supports splat for lists, tuples, and sets, not maps. As a workaround you can use `values(resource_name.name)[*].attribute`

**Comment by pselle** [comment]
@tmccombs Great changeset! You figured out what I hadn't as yet -- the bits of count that hadn't yet been paralleled in `for_each` (the Known situations). It made sense to me so I cherry-picked it here, if you'd like this to go in. I'll also need to update the docs over here (after you confirm you're good with bringing your commit into this PR): https://www.terraform.io/docs/configuration/data-sources.html to reference this functionality, or can cherry-pick a commit for that if you like.

**Comment by tmccombs** [comment]
Yes, please include my changes in this PR, I've signed the CLA. And thanks for catching the panic and extra file I left in there. If you want to update the data-source documentation, that would be great.

**Comment by defo89** [comment]
Apologize if it was clarified before but is it planned to add `for_each` expression support for modules (https://github.com/hashicorp/terraform/issues/17519#issuecomment-371882932) in this PR as well? Thank you!

**Comment by pselle** [comment]
@defo89 It was not asked before, so your question is welcome! No, that is not planned (to add `for_each` for modules in this PR). As soon as I add docs for data sources, this will be merged and will go out in the next release of Terraform.

**Comment by brikis98** [comment]
Very excited to see this merged!

Two questions: 

1. With `count`, you could not reference the output of a resource. Does `for_each` have the same limitation?
1. Is there any reason to use `count` now? Given all the issues it has with removing items from the middle of a list, would it always be safer to use `for_each`? Or are there cases where `count` is still preferred?

**Comment by Skaronator** [comment]
@brikis98 
1. You can actually reference the output of a resource that uses a count. The resource is stored as an array and you can return the whole array of a attribute by doing this:
```
output "nat_ips" {
  value = aws_instance.nat.*.private_ip
}
```
And then you can select with `[0]` or `element(aws_instance.nat.*.private_ip, 0)` the first element.

2. `for_each` seems to be the preferred way since it doesn't need to recreate everything when you remove a element in the middle but there are probably some cases where count should good enough.

**Comment by tmccombs** [comment]
> With count, you could not reference the output of a resource. Does for_each have the same limitation?

I'm not sure what you mean. with count you can access the computed attributes of a resource like `resource_type.name[idx].attribute`. The same method works for for_each, but with a string key instead of a number key.

> Is there any reason to use count now?

The one reason I can think of is where you actually want to create n copies of a resource, with almost identical config.

**Comment by brikis98** [comment]
Ah, whoops, my first question was a bit ambiguous. What I meant is that the `count` parameter itself cannot contain a reference to the output of some other resource output. E.g.:

```hcl
resource "random_integer" "num_instances" {
  min = 1
  max = 3
}

resource "aws_instance" "example_3" {
  # This is not allowed
  count         = random_integer.num_instances.result
  ami           = "ami-0c55b159cbfafe1f0"
  instance_type = "t2.micro"
}
```

The example above will fail as I'm trying to reference a computed output in a `count` parameter, which is not allowed. Will that fail with the new `for_each` as well?

**Comment by Skaronator** [comment]
When you apply the `random_integer` resource fist then it would go through.
`terraform apply -target=random_integer.num_instances`

Not the best workaround but it works.

**Comment by mejedi** [comment]
This is exactly the feature I was looking for! What a coincidence that it got merged just now :)

Unfortunately it fails if `self` is used within a resource spawned with `for_each`:

```
variable "do_token" {}
variable "private_key" {}
variable "ssh_fingerprint" {}
provider "digitalocean" { token = var.do_token }

variable "compute_cluster" {
  default = [1,2,3,4,5] # makes it possible to destroy specific instances when scaling down
}

resource "digitalocean_droplet" "compute" {
  for_each = zipmap(var.compute_cluster, var.compute_cluster)

  image = "ubuntu-18-04-x64"
  name = "compute-${each.key}"
  region = "ams3"
  size = "s-1vcpu-1gb"
  ssh_keys = [ var.ssh_fingerprint ]

  connection {
    host = self.ipv4_address
    user = "root"
    type = "ssh"
    private_key = file(var.private_key)
  }

  provisioner "remote-exec" {
    inline = []
  }
}
```
```
on app.tf line 133, in resource "digitalocean_droplet" "compute":
 133:     host = self.ipv4_address

Because digitalocean_droplet.compute has "for_each" set, its attributes must
be accessed on specific instances.

For example, to correlate with indices of a referring resource, use:
    digitalocean_droplet.compute[each.key]
```

Implementing the suggestion, I get a different error:
```
Error: Reference to "each" in context without for_each

  on app.tf line 132, in resource "digitalocean_droplet" "compute":
 132:     host = digitalocean_droplet.compute[each.key].ipv4_address

The "each" object can be used only in "resource" blocks, and only when the
"for_each" argument is set.
```

Declaring the map inline, i.e.
```
resource "digitalocean_droplet" "compute" {
  for_each = { 1 = 1 }
```
results in a slightly different error:
```
Error: Missing resource instance key

  on app.tf line 132, in resource "digitalocean_droplet" "compute":
 132:     host = self.ipv4_address

Because digitalocean_droplet.compute has "for_each" set, its attributes must
be accessed on specific instances.

For example, to correlate with indices of a referring resource, use:
    digitalocean_droplet.compute[each.key]
```

Any suggestions highly appreciated.

**Comment by tmccombs** [comment]
Does self work with a resource with count?

**Comment by mejedi** [comment]
@tmccombs
> Does self work with a resource with count?

Yes it does! AFAIK ‘self’ is the only option if it is necessary to use (current) resource properties in resource definition. If you attempt ‘resource[count.index]’ instead, a circular dependency is reported, since terraform is unable to figure out that only the current resource is being referenced, not the whole set.

**Comment by tmccombs** [comment]
Sounds like a bug to me. The logic for self is probably just missing the
foreach support.

**Comment by tmccombs** [comment]
I think this should fix it: https://github.com/hashicorp/terraform/pull/22230

**Comment by mejedi** [comment]
@tmccombs Thank you for awesome work, `self` now works like a charm!

Unfortunately, I am hitting further issues. I will give a brief summary below. Later I will provide a minimal terraform file to reproduce.

```
variable "compute_cluster" {
  type = list
  default = [
    "compute-1",
    "compute-2",
    "compute-3",
    "compute-4",
    "compute-5"
  ]
  description = "The list of compute nodes to deploy"
}
resource "digitalocean_droplet" "compute" {
  for_each = zipmap(var.compute_cluster, var.compute_cluster)
  ...
}
resource "null_resource" "update_compute_cluster_users" {
  triggers = {
    compute_cluster_ips = join(" ", values(digitalocean_droplet.compute).*.ipv4_address)
  }
  ...
}
```
I tried deploying new compute nodes, and it works. However if I remove one, say `compute-2`, a sane-looking plan is produced but later terraform says the plan is inconsistent and fails. Relevant excerpt from the plan:
```
  # null_resource.update_compute_cluster_users (deposed object 4a995044) will be destroyed
  - resource "null_resource" "update_compute_cluster_users" {
      - id       = "1618624293842542071" -> null
      - triggers = {
          - "compute_cluster_ips" = "10.133.250.194 10.133.250.42 10.133.250.36 10.133.251.208 10.133.250.119"
        } -> null
    }

  # null_resource.update_compute_cluster_users will be created
  + resource "null_resource" "update_compute_cluster_users" {
      + id       = (known after apply)
      + triggers = {
          + "compute_cluster_ips" = "10.133.250.194 10.133.250.36 10.133.251.208 10.133.250.119"
        }
    }
```
Error message:
```
Error: Provider produced inconsistent final plan

When expanding the plan for null_resource.update_compute_cluster_users to
include new values learned so far during apply, provider "null" produced an
invalid new value for .triggers["compute_cluster_ips"]: was
cty.StringVal("10.133.250.194 10.133.250.36 10.133.251.208 10.133.250.119"),
but now cty.StringVal("10.133.250.194 10.133.250.42 10.133.250.36
10.133.251.208 10.133.250.119").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```
Used to work with `count`.

**Comment by mejedi** [comment]
A minimal terraform file to reproduce the issue with inconsistent plan:
```
variable "list" {
  default = [1, 2, 3, 4, 5]
}
resource "local_file" "file" {
  for_each = zipmap(var.list, var.list)
  filename = "/tmp/${each.key}"
}
resource "null_resource" "null" {
  lifecycle {
    create_before_destroy = true
  }
  triggers = {
    files = join(" ", values(local_file.file)[*].filename)
  }
}
```
To reproduce: `terraform apply`, remove an element from list, `terraform apply` again.

If I remove `lifecycle` section, there's no error.

**Comment by teamterraform** [comment]
Hi @mejedi, thanks for the feedback! Can you please open a new issue with this reproduction case? It's easy to miss comments on closed issues and merged PRs. Thank you.

**Comment by sleterrier** [comment]
> 2. Is there any reason to use `count` now? Given all the issues it has with removing items from the middle of a list, would it always be safer to use `for_each`? Or are there cases where `count` is still preferred?

While I tend to agree that everyone would prefer _for_each_ over _count_ so items can be removed from the middle of a map without triggering a massive destroy/create storm, I wonder how to achieve the conditional case of _count_ in a _for_each_ resource? Here is a simple example:

- Give the following variables:
`variable members {
  default = [ 
    "me@example.com",
    "you@example.com",
  ]
}
variable roles {
  default = [ 
    "roles/resourcemanager.folderAdmin",
    "roles/resourcemanager.folderIamAdmin",
  ]
}
variable folder_id {
  default = "project-1234"
}`

- This would allow to only trigger the resource creation if a folder_id is specified:
`resource "google_folder_iam_binding" "binding" {
  count       = "${length(var.folder_id) > 0 ? length(var.roles) : 0}"
  folder       = var.folder_id
  members = var.members
  role          = element(var.roles, count.index)
}`

- But I do not see a way to achieve a conditional on length(var.folder_id) with for_each:

`locals {
  bindings = {
    for role in var.roles:
    role => var.members
  }
}

resource "google_folder_iam_binding" "binding" {
    for_each = local.bindings

    folder      = var.folder_id
    members = each.value
    role          = each.key
  }
}`

Am I missing something here?

**Comment by brikis98** [comment]
Question: what is the equivalent of `count.index` if using `for_each` on a resource?

**Comment by ilyasotkov** [comment]
@brikis98 I was wondering the same, found the answer here: https://github.com/hashicorp/terraform/issues/21533#issuecomment-497958190

**Comment by brikis98** [comment]
@ilyasotkov Got it, thanks!
