### PR TITLE
command/show: fix issue with show and aliased provider

### LINKED ISSUE #21462: `terraform show` missing schema for provider
### Terraform Version

```
$ terraform --version
Terraform v0.12.0
+ provider.aws v2.12.0
```

### Terraform Configuration Files

Most likely only part of configuration should be enough
```hcl
terraform {
  required_version = "~> 0.12.0"
}

provider "aws" {
  version             = "~> 2.12.0"
  allowed_account_ids = ["XXX"]
}

provider "aws" {
  alias               = "us-east-1"
  region              = "us-east-1"
  allowed_account_ids = [var.region_table["us-east-1"]["account_id"]]

  assume_role {
    role_arn = "arn:aws:iam::${var.region_table["us-east-1"]["account_id"]}:role/${var.assume_role_name}"
  }
}

module "vpc_us-east-1" {
  source = "./vpc"

  providers = {
    aws = aws.us-east-1
  }

  cidr_prefix  = var.region_table["us-east-1"]["cidr_prefix"]
  cidr_netmask = var.vpc_cidr_netmask
}
```

### Expected Behavior

`terraform show` should print resources in proper manner

### Actual Behavior

```
$ terraform show
# module.vpc_us-east-1.aws_default_route_table.rt: 
# missing schema for provider "aws.us-east-1"

# module.vpc_us-east-1.aws_route_table_association.subnets_rt[2]: 
# missing schema for provider "aws.us-east-1"

# module.vpc_us-east-1.aws_route_table_association.subnets_rt[3]: 
# missing schema for provider "aws.us-east-1"

(...)
```

### Steps to Reproduce

Assuming we already have resources.
1. `terraform init`
2. `terraform show`

### Additional Context

I'm rewriting my 0.11 terraform files to 0.12 and my CI step for `terraform show` stopped working and now only shows `missing schema for provider`.

I fail to find any information regarding that in docs so I call for some kind of bug or something is wrong with my code here - not sure.

### PR DESCRIPTION
**Pull request by mildwonkey**
The formatter in `command/format/state.go`, when formatting a resource
with an aliased provider, was looking for a schema with the alias (ie,
test.foo), but the schemas are only listed by provider type (test).
Update the state formatter to lookup schemas by provider type only.

Some of the show tests (and a couple others) were not properly cleaning
up the created tmpdirs, so I fixed those. Also, the show tests are using
a statefile named `state.tfstate`, but were not passing that path to the
show command, so we were getting some false positives (a `show` command
that returns `no state` exits 0).

Fixes #21462

### CODE REVIEW

File: command/show_test.go [hunk 1]
```diff
@@ -51,16 +54,73 @@ func TestShow_noArgs(t *testing.T) {
...
+				Dependencies: []addrs.AbsResource{},
+				DependsOn:    []addrs.Referenceable{},
+			},
+			addrs.RootModuleInstance.ProviderConfigAliased("test", "alias"),
+		)
+	})
+
+	statePath := testStateFile(t, testState)
+	stateDir := filepath.Dir(statePath)
+	// defer os.RemoveAll(stateDir)
```
Comment (jbardin) [inline command/show_test.go]: Is this supposed to be commented out?

Comment (mildwonkey) [reply command/show_test.go]: It mostly certainly is not, thank you!
