### PR TITLE
provider/aws: SNS Topic State Refreshing correctly

### LINKED ISSUE #4888: Fails to refresh state SNS subscription deletions
I had some weird issues with SNS topic subscriptions not registering properly unless managed from the UI, so I deleted those at some point and now TF is freaking out. I tried tainting, removing them from config, refreshing state, but the errors won't go away:

```
* aws_sns_topic_subscription.checker: NotFound: Subscription does not exist
	status code: 404, request id: b8ca0c27-1a62-57b3-8b96-43038a0ead86
```

Shouldn't terraform just detect that it's gone and create it? I'm not sure if this is a bug or just a UX issue. I swear I've deleted things plenty in the past and have TF bring it back up.

### PR DESCRIPTION
**Pull request by stack72**
Fixes #4888

Provider/aws - SNS Topics deleted from the UI were causing Terraform to throw an error:

* aws_sns_topic_subscription.checker: NotFound: Subscription does not
* exist
    status code: 404, request id: b8ca0c27-1a62-57b3-8b96-43038a0ead86

Terraform wasn't refreshing the state when the topic gave a 404

### CODE REVIEW

File: builtin/providers/aws/resource_aws_sns_topic.go [hunk 1]
```diff
@@ -163,6 +165,12 @@ func resourceAwsSnsTopicRead(d *schema.ResourceData, meta interface{}) error {
 	})
 
 	if err != nil {
+		if ec2err, ok := err.(awserr.RequestFailure); ok && ec2err.StatusCode() == http.StatusNotFound {
```
Comment (radeksimko) [inline builtin/providers/aws/resource_aws_sns_topic.go]: Usually (at least from what I've seen elsewhere in the codebase) we check `ec2err.Code()` (which in this case would be `NotFound`) which would help you avoiding that extra import of `net/http`.

Also (but that's really a nitpick), this is a generic AWS error, has nothing to do with EC2. I know this pattern is sprinkled throughout the codebase with EC2 in the name which makes me think we should probably rename all of those variables.

Comment (stack72) [inline builtin/providers/aws/resource_aws_sns_topic.go]: Makes sense @radeksimko - will fix and re-push first thing

**Comment by stack72** [comment]
@radeksimko ok, this was a pretty simple change to make - just repushed it

**Comment by radeksimko** [comment]
LGTM, feel free to merge once Travis turns to green.

**Comment by radeksimko** [comment]
Also after merging don't forget to update the Changelog.md, we typically do this manually via github web interface (to avoid conflicts). :wink:
