### PR TITLE
plan renderer: render unknown nested blocks properly

### LINKED ISSUE #35556: TERRAFORM CRASH when importing google_composer_environment resource
### Terraform Version

```shell
Terraform v1.9.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v5.25.0
+ provider registry.terraform.io/hashicorp/google-beta v5.25.0

Your version of Terraform is out of date! The latest version
is 1.9.3. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

```terraform
module "composer" {
  source = "terraform-google-modules/composer/google//modules/create_environment_v2"

  project_id               = var.project
  region                   = var.region
  network_project_id       = var.network_vpc_project
  network                  = var.network_vpc_name
  subnetwork               = var.subnetwork_vpc_name
  composer_service_account = var.service_account
  environment_size         = var.environment_size
  airflow_config_overrides = local.airflow_config_overrides

  composer_env_name = var.composer_name
  image_version     = local.image_version
  pypi_packages     = local.pypi_packages

  scheduler  = local.scheduler
  web_server = local.webserver
  worker     = local.worker

  labels = {
    "owner" = local.owner_name,
    "env"   = var.env_name
  }

  env_variables = var.env_variables
}

import {
  id = "projects/${local.project}/locations/${var.region}/environments/composer-prod"
  to = module.composer.google_composer_environment.composer_env
}
```

### Debug Output

https://gist.github.com/jlenuffgsoi/7f7c8960d2cbf6959d1b47cea6ced2ef

### Expected Behavior

The resource should be imported successfully.

### Actual Behavior

Terraform crashes when importing google_composer_environment resource :
``` 
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### Steps to Reproduce

terraform init
terraform plan

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by liamcervante**
This PR updates the rendering logic so that it properly renders the contents of a nested block that is becoming unknown. Previously, we'd only render a single item for the whole nested block. Now we should a single item being created that is unknown, and all existing entries being marked as deleted.

In addition, this change fixes a crash that would occur when nested blocks were becoming unknown and contained attributes that were forcing the resource to be replaced. We weren't properly accounting for the nested indices within the replacement list, and now since we are properly computing the diffs we are.

Fixes #35556 

## Target Release

v1.9.7

### BUG FIXES

- Plan renderer: Fix crash that occurs when attempting to render unknown nested blocks that contain attributes forcing replacement.
- Plan renderer: Render complete changes within unknown nested blocks.

### CODE REVIEW

File: internal/command/jsonformat/plan_test.go [hunk 1]
```diff
@@ -3467,6 +3467,113 @@ func TestResourceChange_nestedList(t *testing.T) {
...
+  ~ resource "test_instance" "example" {
+      ~ ami   = "ami-BEFORE" -> "ami-AFTER"
+        id    = "i-02ae66f368e8518a9"
+        # (1 unchanged attribute hidden)
+
+      ~ root_block_device {
+          + ami   = (known after apply)
+          + disks = (known after apply)
+          + id    = (known after apply)
+        } -> (known after apply)
```
Comment (liamcervante) [inline internal/command/jsonformat/plan_test.go:3521]: This is probably incorrect - we're not revealing the fact there were 2 entries in the list block before.

File: internal/command/jsonformat/plan_test.go [hunk 2]
```diff
@@ -3467,6 +3467,113 @@ func TestResourceChange_nestedList(t *testing.T) {
...
+					}),
+				}),
+				"root_block_device": cty.UnknownVal(cty.List(cty.Object(map[string]cty.Type{
+					"volume_type": cty.String,
+					"new_field":   cty.String,
+				}))),
+			}),
+			RequiredReplace: cty.NewPathSet(
+				cty.GetAttrPath("root_block_device").IndexInt(0).GetAttr("volume_type"),
+				cty.GetAttrPath("root_block_device").IndexInt(1).GetAttr("volume_type"),
```
Comment (liamcervante) [inline internal/command/jsonformat/plan_test.go:3563]: This test crashes at the moment because of this. It's because the renderer assumes the unknown block is just a single block type.

**Review by kmoe — APPROVED** [review]
needs backport label?
