### PR TITLE
command/jsonstate: properly marshal deposed resources

### LINKED ISSUE #22642: crash when "terraform show -json" is executed
### Terraform Version

```
0.12.7
```

### Terraform Configuration Files

```hcl
...
```

### Crash Output

https://gist.github.com/ashayshub/8d1d9eb43d3475e915e41d5a1bb5b758

### Expected Behavior

`terraform show -json` should show the JSON output of the resources and output

### Actual Behavior

`terraform show -json` resulted in panic and ended up crashing.

### Steps to Reproduce

1.` AWS_PROFILE=someWorkingProfile terraform init`
2. `AWS_PROFILE=someWorkingProfile terraform refresh  -target=module.someWorkingModule  -var-file=tfVarFileName`
3. `AWS_PROFILE=someWorkingProfile terraform show -json`
 
### Additional Context

In two of the terraform module outputs I am computing map and then using the root module outputs to show these maps
module outputs
```
 output "app-git-sha"{
     value = {
        "xxxx_xxxx_git_sha" = data.aws_autoscaling_group.xxxx-xxxx-asg.tags["GitSHA"],
        "xxxx_xxxx2_git_sha" = data.aws_autoscaling_group.xxxx-xxxx-asg.tags["GitSHA"],
     }
 }
```
root module output
```
output "platform-xxxx-app-git-sha" {
    value = module.platform-xxxx.app-git-sha
}
```
I am unable to see the output of these modules in root module. But I am not sure if this is related with terraform show json crash.

### PR DESCRIPTION
**Pull request by mildwonkey**
This PR addresses 2 issues: `show -json` would crash if there was not a
`Current` `states.ResourceInstance` for a given resource, and `deposed`
resource instances were not shown at all.

Fixes #22642

### CODE REVIEW

File: command/jsonstate/state.go [hunk 1]
```diff
@@ -266,39 +269,78 @@ func marshalResources(resources map[string]*states.Resource, schemas *terraform.
...
+
+				if riObj.Status == states.ObjectTainted {
+					current.Tainted = true
+				}
+				ret = append(ret, current)
 			}
 
-			if riObj.Status == states.ObjectTainted {
-				resource.Tainted = true
+			if ri.Deposed != nil {
```
Comment (jbardin) [inline command/jsonstate/state.go]: You don't the `if` here if you're going to rage over the map to reduce indentation.

Comment (mildwonkey) [reply command/jsonstate/state.go]: 🤦‍♀ thank you, great catch! That was leftover from an earlier implementation. Erp.
