### PR TITLE
core: Fix sensitive value/attribute conflict

### LINKED ISSUE #28244: Panic in Terraform 0.15.0-beta2 with sensitive attributes/arguments
### Terraform Version

```
Terraform v0.15.0-beta2
on darwin_amd64
```

### Terraform Configuration Files

[From the AWS provider tests](https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_glue_crawler_test.go#L1988):

```terraform
provider "aws" {
  region = "us-east-1"
}

data "aws_partition" "current" {}

resource "aws_iam_role" "test" {
  name               = "tf-acc-test-12345"
  assume_role_policy = data.aws_iam_policy_document.assume.json
}

data "aws_iam_policy_document" "assume" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["glue.amazonaws.com"]
    }
  }
}

data "aws_iam_policy" "AWSGlueServiceRole" {
  arn = "arn:${data.aws_partition.current.partition}:iam::aws:policy/service-role/AWSGlueServiceRole"
}

resource "aws_iam_role_policy_attachment" "test-AWSGlueServiceRole" {
  policy_arn = data.aws_iam_policy.AWSGlueServiceRole.arn
  role       = aws_iam_role.test.name
}

resource "aws_iam_role_policy" "LakeFormationDataAccess" {
  role = aws_iam_role.test.name

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "LakeFormationDataAccess",
      "Effect": "Allow",
      "Action": [
        "lakeformation:GetDataAccess"
      ],
      "Resource": "*"
    }
  ]
}
EOF
}

data "aws_availability_zones" "available" {
  state = "available"

  filter {
    name   = "opt-in-status"
    values = ["opt-in-not-required"]
  }
}

resource "aws_vpc" "test" {
  cidr_block = "10.0.0.0/16"

  tags = {
    Name = "terraform-testacc-glue-connection-base"
  }
}

resource "aws_security_group" "test" {
  name   = "tf-acc-test-12345s"
  vpc_id = aws_vpc.test.id

  ingress {
    from_port = 1
    protocol  = "tcp"
    self      = true
    to_port   = 65535
  }
}

resource "aws_subnet" "test" {
  count = 2

  availability_zone = data.aws_availability_zones.available.names[count.index]
  cidr_block        = "10.0.${count.index}.0/24"
  vpc_id            = aws_vpc.test.id

  tags = {
    Name = "terraform-testacc-glue-connection-base"
  }
}

resource "aws_glue_catalog_database" "test" {
  name = "tf-acc-test-12345s"
}

resource "aws_glue_connection" "test" {
  connection_properties = {
    JDBC_ENFORCE_SSL = false
  }

  connection_type = "NETWORK"

  name = "tf-acc-test-12345s"

  physical_connection_requirements {
    availability_zone      = aws_subnet.test[0].availability_zone
    security_group_id_list = [aws_security_group.test.id]
    subnet_id              = aws_subnet.test[0].id
  }
}

resource "aws_glue_crawler" "test" {
  depends_on = [aws_iam_role_policy_attachment.test-AWSGlueServiceRole]

  database_name = aws_glue_catalog_database.test.name
  name          = "tf-acc-test-12345s"
  role          = aws_iam_role.test.name

  s3_target {
    connection_name = aws_glue_connection.test.name
    path            = "s3://bucket1"
  }
}
```

### Crash Output

```
        panic: value is marked, so must be unmarked first
        
        goroutine 156 [running]:
        github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
        	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.1/cty/marks.go:123
        github.com/zclconf/go-cty/cty.Value.LengthInt(0x2c020f0, 0xc0005a97c0, 0x24bce60, 0xc001345ef0, 0x2c02001)
        	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.1/cty/value_ops.go:1045 +0x4f
        github.com/zclconf/go-cty/cty.transform(0xc0005a9970, 0x1, 0x1, 0x2c020f0, 0xc0005a97c0, 0x24bce60, 0xc001345ef0, 0x2bcbb48, 0xc001345f20, 0xc001345ef0, ...)
        	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.1/cty/walk.go:175 +0x8f9
        github.com/zclconf/go-cty/cty.transform(0x0, 0x0, 0x0, 0x2c02128, 0xc0005a9940, 0x23cfa00, 0xc001e2e120, 0x2bcbb48, 0xc001345f20, 0x1, ...)
        	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.1/cty/walk.go:209 +0x10ed
        github.com/zclconf/go-cty/cty.TransformWithTransformer(...)
        	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.1/cty/walk.go:125
        github.com/zclconf/go-cty/cty.Value.MarkWithPaths(0x2c02128, 0xc0005a9940, 0x23cfa00, 0xc001e2e120, 0x0, 0x0, 0x0, 0x23cfa00, 0xc001e2e120, 0x0, ...)
        	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.1/cty/marks.go:215 +0xc5
        github.com/hashicorp/terraform/terraform.(*evaluationStateData).GetResource(0xc000598cf0, 0x4d, 0xc000054618, 0x13, 0xc0000588c8, 0x4, 0xc00013e6a8, 0x18, 0x76, 0x17, ...)
        	/home/circleci/project/project/terraform/evaluate.go:765 +0xab4
        github.com/hashicorp/terraform/lang.(*Scope).evalContext(0xc0005e6b90, 0xc001345e48, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x30)
        	/home/circleci/project/project/lang/eval.go:360 +0x206d
        github.com/hashicorp/terraform/lang.(*Scope).EvalContext(...)
        	/home/circleci/project/project/lang/eval.go:238
        github.com/hashicorp/terraform/lang.(*Scope).EvalBlock(0xc0005e6b90, 0x2c00bb8, 0xc001ebb200, 0xc0010bc720, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
        	/home/circleci/project/project/lang/eval.go:51 +0xf3
        github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).EvaluateBlock(0xc002541520, 0x2c00e58, 0xc001ebb200, 0xc0010bc720, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        	/home/circleci/project/project/terraform/eval_context_builtin.go:273 +0x1ad
        github.com/hashicorp/terraform/terraform.(*NodeAbstractResourceInstance).plan(0xc0002996c0, 0x2c37770, 0xc002541520, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        	/home/circleci/project/project/terraform/node_resource_abstract_instance.go:585 +0x3d5
        github.com/hashicorp/terraform/terraform.(*NodePlannableResourceInstance).managedResourceExecute(0xc0023c7e20, 0x2c37770, 0xc002541520, 0xc000000001, 0xc000061578, 0xc002753c80)
        	/home/circleci/project/project/terraform/node_resource_plan_instance.go:145 +0x4f4
        github.com/hashicorp/terraform/terraform.(*NodePlannableResourceInstance).Execute(0xc0023c7e20, 0x2c37770, 0xc002541520, 0xc000132002, 0xc002753d18, 0x40bb05, 0x2418a80)
        	/home/circleci/project/project/terraform/node_resource_plan_instance.go:41 +0xb3
        github.com/hashicorp/terraform/terraform.(*ContextGraphWalker).Execute(0xc0002a2480, 0x2c37770, 0xc002541520, 0x7fc548f50110, 0xc0023c7e20, 0x0, 0x0, 0x0)
        	/home/circleci/project/project/terraform/graph_walk_context.go:127 +0xbf
        github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x2745d00, 0xc0023c7e20, 0x0, 0x0, 0x0)
        	/home/circleci/project/project/terraform/graph.go:59 +0xba2
        github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc0007d5f20, 0x2745d00, 0xc0023c7e20, 0xc000985b00)
        	/home/circleci/project/project/dag/walk.go:381 +0x288
        created by github.com/hashicorp/terraform/dag.(*Walker).Update
        	/home/circleci/project/project/dag/walk.go:304 +0x1246
```

### Expected Behavior

Terraform works

### Actual Behavior

Terraform does not work!!!

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

This results in a crash.

### Additional Context

Reported in the AWS provider.

### References

https://github.com/hashicorp/terraform-provider-aws/issues/18485

### PR DESCRIPTION
**Pull request by alisdair**
When applying sensitivity marks to resources, we previously would first mark any provider-denoted sensitive attributes, then apply the set of planned-change sensitive value marks. This would cause a panic if a provider marked an iterable value as sensitive, because it is invalid to call `MarkWithPaths` against a marked iterable value.

Instead, we now merge the marks from the provider schema and the planned change into a single set, and apply them with one call. The included test panics without this change.

Fixes #28244. See also https://github.com/hashicorp/terraform-provider-aws/issues/18485.

### CODE REVIEW

File: terraform/evaluate.go [hunk 1]
```diff
@@ -758,11 +758,12 @@ func (d *evaluationStateData) GetResource(addr addrs.Resource, rng tfdiags.Sourc
 			}
 
 			// If our provider schema contains sensitive values, mark those as sensitive
+			afterMarks := change.AfterValMarks
 			if schema.ContainsSensitive() {
-				val = markProviderSensitiveAttributes(schema, val)
+				afterMarks = append(afterMarks, getValMarks(schema, val, nil)...)
```
Comment (pselle) [inline terraform/evaluate.go:763]: Is it possible to get rid of the `markProviderSensitiveAttributes` then? (a quick read of this file suggested its only a wrapper around this `getValMarks` (which could perhaps be more descriptively named) method?)

Comment (jbardin) [inline terraform/evaluate.go:763]: There's 1 remaining call to `markProviderSensitiveAttributes` a little further down. Do we need to do the same thing there too?

Comment (jbardin) [reply terraform/evaluate.go:763]: Oh, nm, I missed that `val` was being re-assigned there

**Review by jbardin — APPROVED** [review]
