### PR TITLE
filter unknowns from simple lists and maps in sdk

### LINKED ISSUE #21419: TF 0.12 - TypeMap validation function gets placeholder values from variables
### Terraform Version
```
Terraform v0.12.0
+ provider.kubernetes v1.7.0
```

### Terraform Configuration Files

```hcl
variable "quota_pods" {
  default = 5
}
variable "quota_memory_request" {
  default = "4Gi"
}

resource "kubernetes_resource_quota" "resource" {
  metadata {
    name = "quota"
  }

  spec {
    hard = {
      pods              = var.quota_pods
      "requests.memory" = var.quota_memory_request

      #   pods = 5
      #   "requests.memory" = "4Gi"
    }
  }
}
```

### Debug Output

https://gist.github.com/alexsomesan/2fe40bfee0f0a07d2d036ba1a2ee6f52

### Crash Output

N/A

### Expected Behavior

Planning should execute successfully and display the plan output.

### Actual Behavior

Validation errors are shown that indicate the contents of the values in the `hard` map are not the ones passed in through the corresponding variables.
Further digging reveals that all the map's values are in fact the same UUID string.

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### Additional Context

When the same values are passed in as literals directly in the map block, the plan executes as expected and the plan output displays the correct values.
To reproduce, uncomment the two commented lines containing literals and comment out the existing ones.

### References

https://github.com/terraform-providers/terraform-provider-kubernetes/issues/452

### PR DESCRIPTION
**Pull request by jbardin**
While there was already a check in the sdk to filter unknowns from
validation, it missed the case where those were in simple lists and maps.

Fixes #21419

### CODE REVIEW

File: helper/schema/schema.go [hunk 1]
```diff
@@ -1365,11 +1365,26 @@ func (m schemaMap) validate(
...
-		return nil, nil
+	// If the value is unknown then we can't validate it yet.
+	// In particular, this avoids spurious type errors where downstream
+	// validation code sees UnknownVariableValue as being just a string.
+	switch raw := raw.(type) {
+	case string:
+		if raw == config.UnknownVariableValue {
+			return nil, nil
+		}
+	case []interface{}:
```
Comment (apparentlymart) [inline helper/schema/schema.go]: Would this also trip up on a list of lists where the second level contains unknowns? I don't know that any provider has ever actually done that, but I think the schema would allow it. :thinking: 

I kinda remember seeing a helper function somewhere to recursively visit all of a data structure looking for `config.UnknownVariableValue`, which in our new world in Terraform Core was of course replaced by `cty`'s `IsWhollyKnown`. I wonder if we still have that old-school helper around somewhere to use here. HIL is the most likely place I'd expect to find it, since it would've needed it for its special behavior of flattening a collection containing unknowns down into a single unknown.

Comment (jbardin) [reply helper/schema/schema.go]: Yeah, I forgot that helper/schema accepts nested types in places, so just made the filter recursive.

There is a similar check already (probably multiple, and `UnknownAsNull` in cty), but the schema needs to have a value for required fields in order to validate, so we have to filter them later.
