### PR TITLE
provider/aws: Support Policy DiffSuppression in `aws_kms_key` policy

### LINKED ISSUE #7495: aws_iam_policy_document data source diff with single element arrays
### Terraform Version
Terraform v0.7.0-rc2 (46a0709bba004d8b6e0eedad411270b3ae135a9e)

### Affected Resource(s)
- aws_iam_policy_document

### Terraform Configuration Files
```hcl
data "aws_iam_policy_document" "key_store_kms" {
  statement {
    actions = [
      "kms:*"
    ]
    resources = [
      "*"
    ]
    effect = "Allow"
    principals {
      type = "AWS"
      identifiers = ["arn:aws:iam::0958430598340:root"]
    }
  }
}

resource "aws_kms_key" "key_store" {
  description = "Protects secrets stored in S3"
  policy = "${data.aws_iam_policy_document.key_store_kms.json}"
}
```

### Expected Behavior
The policy shouldn't be marked to be modified in the plan phase. All the arguments that received a [] with only one element, should be rendered as a string.

### Actual Behavior
The policy is marked to be modified every time I run terraform plan and apply. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
1. `terraform apply`
1. `terraform plan`

### References
- [GH-1234](https://github.com/hashicorp/terraform/pull/6881#issuecomment-222390832)
The is a mention about the problem but it's hidden in a merge PR.
> There needs to be some logic to ensure that array items like Actions get converted to strings instead of []strings if there is only one element (this was one of the things that was causing recurring diffs in unchanged policies). So those elements probably need to be interface{} and then handled accordingly.

### PR DESCRIPTION
**Pull request by stack72**
Fixes #7495

```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSKmsKey_policy'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/09/06 10:44:20 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSKmsKey_policy
-timeout 120m
=== RUN   TestAccAWSKmsKey_importBasic
--- PASS: TestAccAWSKmsKey_importBasic (166.19s)
=== RUN   TestAccAWSKmsKey_basic
--- PASS: TestAccAWSKmsKey_basic (215.33s)
=== RUN   TestAccAWSKmsKey_policy
--- PASS: TestAccAWSKmsKey_policy (116.81s)
=== RUN   TestAccAWSKmsKey_isEnabled
--- PASS: TestAccAWSKmsKey_isEnabled (1008.31s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/aws
1689.957s
```

### CODE REVIEW

File: builtin/providers/aws/resource_aws_kms_key_test.go [hunk 1]
```diff
@@ -74,6 +95,42 @@ func TestAccAWSKmsKey_isEnabled(t *testing.T) {
 	})
 }
 
+func testAccCheckAWKmsKeyHasPolicy(name string, expectedPolicyText string) resource.TestCheckFunc {
```
Comment (radeksimko) [inline builtin/providers/aws/resource_aws_kms_key_test.go]: Typo here... `AWKms` => `AWSKms` 😜

**Comment by radeksimko** [comment]
Except that typo this LGTM.

**Comment by stack72** [comment]
Good spot @radeksimko :) Just pushed an update - will merge when green
