### PR TITLE
backend/local: create local state file if backend write fails

### LINKED ISSUE #14298: State file is not saved locally when uploading to remote backend fails
Terraform does not save a state file locally when uploading to the remote backend fails. In my case I was creating 104 resources on AWS and after 1 hour of working and completion, suddenly, terraform failed to upload the resulting state file to S3 with 403 error to the bucket (with no reason, I didn't have the access problems) but important here, it left me without a state file at all - no local copy unfortunately. So basically, I have got a ton of orphaned AWS resources.

### Terraform Version
v0.9.3, v0.9.4

### Affected Resource(s)
Uploading a state file to the remote backend S3

### Expected Behavior
From https://www.terraform.io/docs/backends/state.html#state-storage 
```
In the case of an error persisting the state to the backend, Terraform will write
the state locally. This is to prevent data loss. If this happens the end user must 
manually push the state to the remote backend once the error is resolved.
```

### Actual Behavior
Data loss, you are left with the orphaned resources :(

### Steps to Reproduce
Here `my-bucket` should be a real bucket.
```
$ cat 1.tf
terraform {
  backend "s3" {
    bucket  = "my-bucket"
    key     = "roman/roman.tfstate"
    region  = "us-west-2"
    encrypt = true
  }
}

resource "random_id" "random_password" {
  byte_length = 1

  provisioner "local-exec" {
    command = "sleep 30"
  }
}
$ terraform init -backend=true -get=true
$ terraform plan
...

+ random_id.mysql_password
    b64:         "<computed>"
    b64_std:     "<computed>"
    b64_url:     "<computed>"
    byte_length: "1"
    dec:         "<computed>"
    hex:         "<computed>"


Plan: 1 to add, 0 to change, 0 to destroy.
```

Now run the below command and while it is sleeping on provisioning you will have 30s to quickly edit your /etc/hosts and add a line like this `1.2.3.4 my-bucket.s3-us-west-2.amazonaws.com` to repoint DNS to something fake and have the upload to remote backend to fail:
```
$ terraform apply
random_id.mysql_password: Creating...
  b64:         "" => "<computed>"
  b64_std:     "" => "<computed>"
  b64_url:     "" => "<computed>"
  byte_length: "" => "1"
  dec:         "" => "<computed>"
  hex:         "" => "<computed>"
random_id.mysql_password: Provisioning with 'local-exec'...
random_id.mysql_password (local-exec): Executing: /bin/sh -c "sleep 30"
random_id.mysql_password: Still creating... (10s elapsed)
random_id.mysql_password: Creation complete (ID: Sg)
Failed to save state: Failed to upload state: RequestError: send request failed
caused by: Put https://my-bucket.s3-us-west-2.amazonaws.com/roman/roman.tfstate: x509: certificate is valid for *.domain.com, not my-bucket.s3-us-west-2.amazonaws.com
```

No matter what the error is, it could be 403, 404 or in my case certificate problems. Terraform only saves a current state file to `terraform.tfstate.backup` locally which is a state file before resource creation, but after they are created and upload fails - nothing is saved neither to the current folder or to .terraform/ and you get a data loss.

Thanks, please let me know if you need any further information.

### PR DESCRIPTION
**Pull request by apparentlymart**
In the state system we have the idea of a local backup, which is actually still present and used when the local backend is active, but is no longer used when a remote backend is active.

This is problematic when an apply runs for long enough that someone's time-limited AWS STS credentials expire and then Terraform fails and can't persist state to S3.

To reduce the risk of lost state, here we add some extra fallback code for the local apply operation in particular. If either state writing or state persisting fail then we attempt to write the state to a special backup file `errored.tfstate`, and produce an error message that guides the user on how to retry uploading this state.

In the unlikely event that we can't write to local disk either (e.g. permissions problems) we take a last-ditch attempt to dump the JSON onto stdout and advise the user to manually copy it into a file for import. If even that doesn't work for some reason, we assume a critical Terraform bug (JSON-serialization problem with states?) and bail out with an apologetic error message.

This new behavior is added to the apply operation, rather than simply making the existing local backup system work for remote backends again, because doing it at the apply layer means we can give better feedback to the user and more easily have the additional fallback of printing to stdout.

This is implemented for the apply operation in particular because this is the one operation where new objects are created in real APIs that we don't want to lose track of. For other operations it's less bad to just generate a simple error message and have the user retry, since no new objects will have been created.

This fixes #14298. @phinze, I think this would also address part of what you apparently ran into earlier today where you needed to abort a Terraform process with expired STS credentials without losing state.

### CODE REVIEW

**Comment by apparentlymart** [comment]
Note for the future: one thing we will need to contend with here is situations where Terraform is running in automation, such as Terraform Enterprise. Such systems may want to have special handling for this situation, to ensure that the `errored.tfstate` file gets captured somewhere that the user can get it and possibly even to prevent further applies until a human indicates that the situation has been resolved. Not directly in the scope of this issue, but will need to deal with this eventually.

File: backend/local/backend_apply.go [hunk 1]
```diff
@@ -186,6 +188,41 @@ func (b *Local) opApply(
...
+	if writeErr != nil {
+		b.CLI.Error(fmt.Sprintf(
+			"Also failed to create local state file for recovery: %s\n\n", writeErr,
+		))
+		// To avoid leaving the user with no state at all, our last resort
+		// is to print the JSON state out onto the terminal. This is an awful
+		// UX, so we should definitely avoid doing this if at all possible,
+		// but at least the user has _some_ path to recover if we end up
+		// here for some reason.
+		jsonState, jsonErr := json.MarshalIndent(applyState, "", "  ")
```
Comment (mitchellh) [inline backend/local/backend_apply.go]: Could you use `terraform.WriteState` to a bytes.Buffer here instead? Its possible that JSON encoding directly may not produce the correct state.

Comment (apparentlymart) [inline backend/local/backend_apply.go]: :+1: makes sense! I'd forgotten about that function.

**Comment by jbardin** [comment]
I wonder if we eventually should try to handle this better directly with BackupState? While this doesn't replace the current use for BackupState, since the user may want the previous rather than an intermediate state, maybe BackupState should record all writes in versioned files, or at least the original and the latest write?

On a related note, I've been trying to come up with a nice way to prevent users from aborting a run and then starting new run before recovering the state (after ignoring the UI warning of course), and losing the state (e.g. `terraform apply`; Ctrl+C - Ctrl+C; `terraform apply`; "where did everything go?").  I wanted to avoid leaving a new backup from every command, but may archiving all states in a tar.gz in the .terraform directory would work, since they compress very well.

**Comment by apparentlymart** [comment]
This is now updated based on the feedback.

To me this feels different than `BackupState`. The existing backup mechanism is, as you said, primarily concerned with helping users undo state changes they made that they wish they didn't, not with helping users recover from errors.

_This_ situation is rather unique to the apply action. All other state-modifying commands don't benefit from this, because they don't make any new resources that Terraform needs to start tracking. I'd rather give users a straightforward error if, for example, `terraform state rm` fails, having them just try the operation again rather than suggesting they should try to recover by `terraform state push`.
