### PR TITLE
Fixes for maps in shims

### LINKED ISSUE #21070: 0.12 Missing TypeSet in state and attribute still present
Updating Terraform SDK to 0.12 beta 2 make two acceptance tests break.

### Terraform version

```
github.com/hashicorp/terraform v0.12.0-beta2
```

### Expected behavior

All tests pass, as they did with Terraform 0.11

### Actual behavior

Two tests fail:

```
=== RUN   TestAccConsulKeys_basic
--- FAIL: TestAccConsulKeys_basic (0.15s)
    testing.go:568: Step 1 error: Check failed: Check 4/4 error: Attribute 'remove_one' still present: map[string]string{"datacenter":"dc1", "id":"consul", "key.#":"2", "key.33137035.default":"true", "key.33137035.delete":"false", "key.33137035.flags":"0", "key.33137035.name":"enabled", "key.33137035.path":"test/enabled", "key.33137035.value":"", "key.4021585958.default":"", "key.4021585958.delete":"true", "key.4021585958.flags":"64", "key.4021585958.name":"set", "key.4021585958.path":"test/set", "key.4021585958.value":"acceptanceUpdated", "var.%":"3", "var.enabled":"true", "var.remove_one":"hello", "var.set":"acceptanceUpdated"}
=== RUN   TestAccConsulPreparedQuery_basic
--- FAIL: TestAccConsulPreparedQuery_basic (0.12s)
    testing.go:568: Step 2 error: Check failed: Check 4/7 error: Attribute 'tags.#' not found: map[string]string{"dns.#":"0", "failover.#":"0", "id":"1bc7b66a-1112-9fcf-ae4b-f29f35a530ba", "name":"baz", "near":"", "only_passing":"false", "service":"memcached", "session":"", "stored_token":"", "template.#":"0"}
```

### Steps to reproduce

Get the provider updated with the 0.12 SDK at https://github.com/terraform-providers/terraform-provider-consul/tree/terraform-0.12 and run the acceptance tests:

```
$ consul agent -dev -config-file ./consul_test.hcl
$ export CONSUL_HTTP_ADDR=http://localhost:8500
$ export CONSUL_HTTP_TOKEN=master-token
$ make testacc TEST_ARGS="-count=1"
```

### PR DESCRIPTION
**Pull request by jbardin**
Make sure values removed from a map during apply are not copied into the
new map when the plan didn't correctly mark a computed map as unknown.

Fixes #21070 as far as core is concerned. The provider will need a couple updates as well.

### CODE REVIEW

File: helper/plugin/grpc_provider.go [hunk 1]
```diff
@@ -1108,16 +1108,13 @@ func stripSchema(s *schema.Schema) *schema.Schema {
 // however it sees fit. This however means that a CustomizeDiffFunction may not
 // be able to change a null to an empty value or vice versa, but that should be
 // very uncommon nor was it reliable before 0.12 either.
-func normalizeNullValues(dst, src cty.Value, preferDst bool) cty.Value {
+func normalizeNullValues(dst, src cty.Value, apply bool) cty.Value {
```
Comment (pselle) [inline helper/plugin/grpc_provider.go]: I appreciate the name change here, it helps in the understanding.
