### PR TITLE
initwd: cache registry responses for module versions and download URL

### LINKED ISSUE #23544: Terraform init does not cache the location of a specific module version from the Terraform Registry
### Terraform Version

```
Terraform v0.12.17
```

### Terraform Configuration Files
```hcl
module "security-group-reg-1" {
  source  = "terraform-aws-modules/security-group/aws"
  version = "3.2.0"
  name = "sg-1"
  vpc_id = aws_vpc.state-vpc.id
}

module "security-group-reg-2" {
  source  = "terraform-aws-modules/security-group/aws"
  version = "3.2.0"
  name = "sg-2"
  vpc_id = aws_vpc.state-vpc.id
}

module "security-group-reg-3" {
  source  = "terraform-aws-modules/security-group/aws"
  version = "3.2.0"
  name = "sg-3"
  vpc_id = aws_vpc.state-vpc.id
}

module "security-group-git-1" {
  source  = "github.com/terraform-aws-modules/terraform-aws-security-group.git"
  name = "sg-4"
  vpc_id = aws_vpc.state-vpc.id
}

module "security-group-git-2" {
  source  = "github.com/terraform-aws-modules/terraform-aws-security-group.git"
  name = "sg-5"
  vpc_id = aws_vpc.state-vpc.id
}

module "security-group-git-3" {
  source  = "github.com/terraform-aws-modules/terraform-aws-security-group.git"
  name = "sg-6"
  vpc_id = aws_vpc.state-vpc.id
}
```

### Debug Output

https://gist.github.com/pkolyvas/6e80adbabe0569773880d1357194e8c4

### Expected Behavior
Terraform should have fetched a single copy of the module from the Terraform Module Registry and a single copy of the module from GitHub.

### Actual Behavior
Terraform fetched three copies of the module from the Terraform Module Registry and a single copy of the module from GitHub.

### Steps to Reproduce
1. Use multiple instances of the same module from the Terraform Module Registry in a given `.tf` config.
2. `terraform init`

### Additional context

On very large configurations/plans, repeatedly downloading the same, large, modules can dramatically affect performance.

### PR DESCRIPTION
**Pull request by mildwonkey**
Closes #23544

Suggestions for tests that specifically exercise this feature appreciated - the ideas I had felt more complicated (and fragile) than was worthwhile so I'd love to hear better ones. 

Some relevant trace output (using the example from #23544 ):

```
2019/12/19 11:16:04 [DEBUG] Module installer: security-group-reg-1 installed at .terraform/modules/security-group-reg-1/terraform-aws-modules-terraform-aws-security-group-57856b3
2019/12/19 11:16:04 [DEBUG] Module installer: begin security-group-reg-2
2019/12/19 11:16:05 [TRACE] ModuleInstaller: security-group-reg-2 is not yet installed
2019/12/19 11:16:05 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/security-group-reg-2 prior to install of security-group-reg-2
- security-group-reg-1 in .terraform/modules/security-group-reg-1/terraform-aws-modules-terraform-aws-security-group-57856b3
2019/12/19 11:16:05 [TRACE] ModuleInstaller: security-group-reg-2 is a registry module at terraform-aws-modules/security-group/aws
2019/12/19 11:16:05 [TRACE] security-group-reg-2 using already found available versions of terraform-aws-modules/security-group/aws at registry.terraform.io
2019/12/19 11:16:05 [TRACE] security-group-reg-2 using previously-found download URL for terraform-aws-modules/security-group/aws 3.2.0
```

### CODE REVIEW

**Comment by mildwonkey** [comment]
That's a good idea! I found a simpler - and admittedly less in-depth - test for now; currently the hooks only track download and install and I did not want to refactor to add API calls right now. But I'm open to disagreement!

File: internal/initwd/module_install.go [hunk 1]
```diff
@@ -405,15 +427,23 @@ func (i *ModuleInstaller) installRegistryModule(req *earlyconfig.ModuleRequest,
...
-		diags = diags.Append(tfdiags.Sourceless(
-			tfdiags.Error,
-			"Invalid response from remote module registry",
-			fmt.Sprintf("The remote registry at %s failed to return a download URL for %s %s.", hostname, addr, latestMatch),
-		))
-		return nil, nil, diags
+	var dlAddr string
+
+	// check if we've already looked up the module download URL
+	if dlAddr, exists = i.moduleVersionsUrl[moduleVersion{module: addr.String(), version: latestMatch.String()}]; exists {
```
Comment (apparentlymart) [inline internal/initwd/module_install.go]: This bit made me double-take a little because I didn't grok initially that this is using the `dlAddr` declared above, and was instead expecting it to be more like the similar branching above where the condition is only deciding whether to populate the map, not also writing to the result variable.

This is totally subjective, so no worries if you disagree, but I might be more inclined to write it this way:

```go
moduleAddr := moduleVersion{module: addr.String(), version: latestMatch.String()}

if _, exists := i.moduleVersionsUrl[moduleAddr]; !exists {
    // do all the fetching logic, and then populate the cache map:
    i.moduleVersionsUrl[moduleAddr] = ...
}

// now dlAddr can be declared and assigned in the same place, regardless
// of whether we'd had it cached.
dlAddr := i.moduleVersionsUrl[moduleAddr]
```

File: internal/initwd/module_install.go [hunk 2]
```diff
@@ -14,18 +14,32 @@ import (
...
+	"github.com/hashicorp/terraform/registry/response"
 	"github.com/hashicorp/terraform/tfdiags"
 )
 
 type ModuleInstaller struct {
 	modsDir string
 	reg     *registry.Client
+
+	// The keys in moduleVersions are resolved and trimmed registry source
+	// addresses and the values are the download URLs.
```
[the remark this answers is not in the document]
Comment (mildwonkey) [reply internal/initwd/module_install.go]: ah yes, that comment did not get updated as I refined the code - thanks, I'll clear those both up!

File: internal/initwd/module_install.go (hunk 1 above)
Comment (mildwonkey) [reply internal/initwd/module_install.go]: Looks great to me, thank you! I just pushed an update.
