### PR TITLE
plan rendering: fix truncation of very large numbers

### LINKED ISSUE #34686: distinct function rounding large integers
### Terraform Version

```shell
Terraform v1.6.2
```

### Terraform Configuration Files

```terraform

locals {
  ids = [
    9223372036854773256,
    9223372036854773263,
    9223372036854773263,
    9223372036854773266
  ]
  sorted = sort(local.ids)
  unique = distinct(local.ids)
}

output "sorted" {
  value = local.sorted
}

output "unique" {
  value = local.unique
}

```

### Debug Output

```
Changes to Outputs:
  + sorted = [
      + "9223372036854773256",
      + "9223372036854773263",
      + "9223372036854773263",
      + "9223372036854773266",
    ]
  + unique = [
      + 9223372036854774000,
      + 9223372036854774000,
      + 9223372036854774000,
    ]
```

### Expected Behavior

the distinct function should output full values just like sort does

### Actual Behavior

distinct is rounding the values to `9223372036854774000`

### Steps to Reproduce

just do a TF plan on the sample provided

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by liamcervante**
When unmarshalling the JSON plan, the renderer now uses `json.Number` to represent numbers instead of `float64`.  This means that very large numbers (> 2^63) will no longer be truncated down to 2^63.

Fixes #34686

## Target Release

1.7.4 or whatever the next 1.7 release is.

### BUG FIXES

 

-  plan renderer: Numbers larger than 2^63 will now be accurately rendered.

### CODE REVIEW

File: internal/command/jsonformat/jsondiff/types.go [hunk 1]
```diff
@@ -16,11 +19,11 @@ const (
...
 
-func GetType(json interface{}) Type {
-	switch json.(type) {
+func GetType(value interface{}) Type {
+	switch value.(type) {
 	case []interface{}:
 		return Array
-	case float64:
+	case json.Number:
 		return Number
```
Comment (Yantrio) [inline internal/command/jsonformat/jsondiff/types.go:27]: I think it may be a good idea to maintain the `float64` case here just incase we didn't catch everything.
