### PR TITLE
provider/aws: aws_db_option_group flattenOptions failing due to missing values

### LINKED ISSUE #8332: Crash while attempting to import a database option group
[crash.txt](https://github.com/hashicorp/terraform/files/427896/crash.txt)

### PR DESCRIPTION
**Pull request by stack72**
Fixes #8332

Not all option_group parameters have values. For example, when you
enable the MariaDB option_group, some of the settings have empty values
(see screenshot)

This PR adds a safety net on reading those values back to the statefile

```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSDBOptionGroup_'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/09/26 13:55:21 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v
-run=TestAccAWSDBOptionGroup_ -timeout 120m
=== RUN   TestAccAWSDBOptionGroup_importBasic
--- PASS: TestAccAWSDBOptionGroup_importBasic (20.12s)
=== RUN   TestAccAWSDBOptionGroup_basic
--- PASS: TestAccAWSDBOptionGroup_basic (18.45s)
=== RUN   TestAccAWSDBOptionGroup_basicDestroyWithInstance
--- PASS: TestAccAWSDBOptionGroup_basicDestroyWithInstance (597.90s)
=== RUN   TestAccAWSDBOptionGroup_OptionSettings
--- PASS: TestAccAWSDBOptionGroup_OptionSettings (33.27s)
=== RUN   TestAccAWSDBOptionGroup_sqlServerOptionsUpdate
--- PASS: TestAccAWSDBOptionGroup_sqlServerOptionsUpdate (33.39s)
=== RUN   TestAccAWSDBOptionGroup_multipleOptions
--- PASS: TestAccAWSDBOptionGroup_multipleOptions (19.87s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/aws    723.037s
```

screen shot 2016-09-26 at 13 56 19

### CODE REVIEW

File: builtin/providers/aws/structure.go [hunk 1]
```diff
@@ -622,12 +623,19 @@ func flattenOptions(list []*rds.Option) []map[string]interface{} {
...
 			}
 			if i.OptionSettings != nil {
+				spew.Sdump("Options HERE %s", i.OptionSettings)
 				settings := make([]map[string]interface{}, 0, len(i.OptionSettings))
 				for _, j := range i.OptionSettings {
-					settings = append(settings, map[string]interface{}{
-						"name":  *j.Name,
-						"value": *j.Value,
-					})
+					spew.Sdump("Option HERE %s", j)
```
Comment (catsby) [inline builtin/providers/aws/structure.go]: looks like some extra debugging things here. In general it's OK to use `spew` in our tests, but we kind of made a decision to not include it in another files (so it won't ship with the Terraform binary as a dependency) .

_Turns out_ spew is in some files, but I'll remove those 😆

Comment (stack72) [inline builtin/providers/aws/structure.go]: And that is the perfect reason why we send PRs for review :) Removed now so will merge on green
