### PR TITLE
internal/initwd: follow local module path symlink

### LINKED ISSUE #21060: 0.12 beta2 init fails when use of multiple symlinks
### Terraform Version

```
Terraform v0.12.0-beta2
```

### Terraform Configuration Files
https://github.com/dblooman/terraform-bug

In this repo, `cd staging/services/demo_service` and `terraform init`

### Debug Output
```bash
2019/04/19 15:28:23 [INFO] Terraform version: 0.12.0 beta2 
2019/04/19 15:28:23 [INFO] Go runtime version: go1.11.5
2019/04/19 15:28:23 [INFO] CLI args: []string{"/usr/local/bin/terraform2", "init"}
2019/04/19 15:28:23 [DEBUG] Attempting to open CLI config file: /Users/dblooman/.terraformrc
2019/04/19 15:28:23 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/04/19 15:28:23 [INFO] CLI command args: []string{"init"}
2019/04/19 15:28:23 [TRACE] ModuleInstaller: installing child modules for . into .terraform/modules
Initializing modules...
2019/04/19 15:28:23 [DEBUG] Module installer: begin testing
2019/04/19 15:28:23 [TRACE] ModuleInstaller: Module installer: testing <nil> already installed in ../modules/demo
2019/04/19 15:28:23 [DEBUG] Module installer: begin testing.ami
2019/04/19 15:28:23 [TRACE] ModuleInstaller: testing.ami has local path "../../aws_example"
2019/04/19 15:28:23 [TRACE] ModuleInstaller: testing.ami uses directory from parent: ../aws_example
2019/04/19 15:28:23 [DEBUG] Module installer: testing.ami installed at ../aws_example
2019/04/19 15:28:23 [TRACE] modsdir: writing modules manifest to .terraform/modules/modules.json
- testing.ami in ../aws_example

Error: Failed to read module directory

Module directory ../aws_example does not exist or cannot be read.


Error: Failed to read module directory

Module directory ../aws_example does not exist or cannot be read.

```

### Expected Behavior
I should be able to terraform init and get modules as with current latest stable terraform

### Actual Behavior
Terraform doesn't init, fails to find module

### Steps to Reproduce
clonse https://github.com/dblooman/terraform-bug

In this repo, `cd staging/services/demo_service` and `terraform init`

### PR DESCRIPTION
**Pull request by mildwonkey**
Fixes #21060

While a previous commit fixed a problem when the local module directory
contained a symlink, it did not account for the possibility that the
entire directory was a symlink.

I fully admit that the error phrasing is awkward and I enthusiastically welcome suggestions for improvement.

### CODE REVIEW

File: internal/initwd/module_install.go [hunk 1]
```diff
@@ -245,6 +245,17 @@ func (i *ModuleInstaller) installLocalModule(req *earlyconfig.ModuleRequest, key
 	// filesystem at all because the parent already wrote
 	// the files we need, and so we just load up what's already here.
 	newDir := filepath.Join(parentRecord.Dir, req.SourceAddr)
+
+	// it is possible that the local directory is a symlink
+	newDir, err := filepath.EvalSymlinks(newDir)
+	if err != nil {
+		diags = diags.Append(tfdiags.Sourceless(
+			tfdiags.Error,
+			"Unreadable module directory",
```
Comment (pselle) [inline internal/initwd/module_install.go]: To describe what's happening here, it's "Unable to evaluate directory symlink" perhaps? That's redundant with the "Unable" detail, but I like symlink in the main error

File: internal/initwd/module_install_test.go [hunk 2]
```diff
@@ -111,6 +111,67 @@ func TestModuleInstaller_error(t *testing.T) {
 	}
 }
 
+func TestModuleInstaller_symlink(t *testing.T) {
```
Comment (pselle) [inline internal/initwd/module_install_test.go]: Is there a test in this func covering a bad symlink? If not, perhaps let's?

File: internal/initwd/module_install_test.go [hunk 3]
```diff
@@ -111,6 +111,67 @@ func TestModuleInstaller_error(t *testing.T) {
...
+		{
+			Name:        "Install",
+			ModuleAddr:  "child_a.child_b",
+			PackageAddr: "",
+			LocalPath:   "child_a/child_b",
+		},
+	}
+
+	if assertResultDeepEqual(t, hooks.Calls, wantCalls) {
+		return
```
Comment (pselle) [inline internal/initwd/module_install_test.go]: What's happening here? If the calls and the desired calls are equal, we return, but then we don't get to the further asserts?

File: internal/initwd/module_install_test.go (hunk 2 above)
Comment (mildwonkey) [reply internal/initwd/module_install_test.go]: It's not explicitly covered here, but there are tests that handle other error situations already so I considered that to be sufficient. I could certainly add another test.

File: internal/initwd/module_install_test.go (hunk 3 above)
Comment (mildwonkey) [reply internal/initwd/module_install_test.go]: No, the opposite. If they don't match it will return an error

File: internal/initwd/module_install.go (hunk 1 above)
Comment (mildwonkey) [reply internal/initwd/module_install.go]: That's a much better phrasing - I'm going to use it for the detail, though, not the summary. 
My intent was to keep the summary for this error the same as the one below, since they are similar situations.

Now that I look at this again I'm also going to move this bit of code below the preceding `log` output; the `[TRACE]` info is relevant!

File: internal/initwd/module_install_test.go (hunk 2 above)
Comment (pselle) [reply internal/initwd/module_install_test.go]: It probably is sufficient, but I wouldn't mind a pointer so I can go read those to see how they look in practice :)

Comment (mildwonkey) [reply internal/initwd/module_install_test.go]: Sure, the test right before this one checks for an expected error:
https://github.com/hashicorp/terraform/blob/35a01283d66451fd3f4ce93957acb33f95a1d41c/internal/initwd/module_install_test.go#L96-L112

File: internal/initwd/module_install_test.go (hunk 3 above)
Comment (pselle) [reply internal/initwd/module_install_test.go]: Oh, perfect, thanks, I didn't think to look at the implementation of the `assert`, agree on the intuitive-ness
