### PR TITLE
Apply optimizations for handling of condition checks

### LINKED ISSUE #32060: Significant performance degradation with Terraform 1.3.x and local state
### Terraform Version

```shell
Terraform v1.3.3
```

### Terraform Configuration Files

https://github.com/danischm/tf-perf-test

### Debug Output

```
2022-10-21T13:06:59.469+0200 [TRACE] statemgr.Filesystem: have already backed up original terraform.tfstate to terraform.tfstate.backup on a previous write
2022-10-21T13:06:59.567+0200 [TRACE] statemgr.Filesystem: state has changed since last snapshot, so incrementing serial to 29
2022-10-21T13:06:59.567+0200 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2022-10-21T13:06:59.639+0200 [TRACE] vertex "null_resource.test3": visit complete
2022-10-21T13:06:59.640+0200 [TRACE] statemgr.Filesystem: have already backed up original terraform.tfstate to terraform.tfstate.backup on a previous write
2022-10-21T13:06:59.737+0200 [TRACE] statemgr.Filesystem: state has changed since last snapshot, so incrementing serial to 30
2022-10-21T13:06:59.738+0200 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2022-10-21T13:06:59.804+0200 [TRACE] vertex "null_resource.test0": visit complete
2022-10-21T13:06:59.805+0200 [TRACE] statemgr.Filesystem: have already backed up original terraform.tfstate to terraform.tfstate.backup on a previous write
2022-10-21T13:06:59.900+0200 [TRACE] statemgr.Filesystem: state has changed since last snapshot, so incrementing serial to 31
2022-10-21T13:06:59.900+0200 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2022-10-21T13:06:59.968+0200 [TRACE] vertex "null_resource.test6": visit complete
```

### Expected Behavior

The second `terraform apply` should be completed in less than a second (using the provided configuration) with no changes to the local state file. This is the observed behavior with TF <1.3.0.

### Actual Behavior

With TF 1.3.0+ we can see that the local state file is rewritten once per every resource in the configuration even though there are no changes. This is also visible in the local state file where `serial` gets incremented by the number of resources. Compared to TF <1.3.0 where the second no-op `terraform apply` takes less than a second, with TF 1.3.0+ the second `terraform apply` takes 3+ minutes to complete. Increasing the number of resources and/or the size of the state file worsens the issue.

### Steps to Reproduce

1. `terraform apply -auto-approve -refresh=false`
2. `terraform apply -auto-approve -refresh=false`

### Additional Context

A git bisect has revealed the following 'bad' commit: https://github.com/hashicorp/terraform/commit/72dd14ca5c023d32bed64ac887275fbd9d3569a9

### References

_No response_

### LINKED ISSUE #32071: v1.3 `apply` performance regressions with large numbers of instances
### Terraform Version

```shell
1.3.2
```

### Terraform Configuration Files

Judging by which parts of our estate have been impacted, I suspect this is going to require a fairly large input array and collection of resources to iterate, in order to exhaust the machine from which Terraform is invoked of most available resources. A minimal example should be capable of detailing the material differences I've noted below. If a bit of feedback could be provided on this change in behaviour between non-breaking versions it would help direct the replication for me to provide.

### Debug Output

Terraform 1.3.2 DEBUG output

```
2022-10-24T13:09:46.304+0100 [DEBUG] no planned changes, skipping apply graph check

[0m[1m[32mNo changes.[0m[1m Your infrastructure matches the configuration.[0m

[0mTerraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.
2022-10-24T13:09:46.856+0100 [INFO]  backend/local: apply calling Apply
2022-10-24T13:09:46.856+0100 [DEBUG] Building and walking apply graph for NormalMode plan
2022-10-24T13:09:58.977+0100 [DEBUG] ProviderTransformer: "module.product_attachment[\"somename\"].aws_servicecatalog_constraint.launch[\"NAT-103\"]" (*terraform.NodeApplyableResourceInstance) needs provider["registry.terraform.io/hashicorp/aws"]
2022-10-24T13:09:58.977+0100 [DEBUG] ProviderTransformer: "module.product_attachment[\"somename\"].aws_servicecatalog_constraint.notification_constraint[\"NAT-110\"]" (*terraform.NodeApplyableResourceInstance) needs provider["registry.terraform.io/hashicorp/aws"]
2022-10-24T13:09:58.977+0100 [DEBUG] ProviderTransformer: "module.product_attachment[\"somename\"].aws_servicecatalog_product_portfolio_association.product_attachment[\"NAT-028\"]" (*terraform.NodeApplyableResourceInstance) needs provider["registry.terraform.io/hashicorp/aws"]
```

Terraform 1.2.6 DEBUG output

```
2022-10-24T13:36:27.310+0100 [DEBUG] no planned changes, skipping apply graph check

[0m[1m[32mNo changes.[0m[1m Your infrastructure matches the configuration.[0m

[0mTerraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.
2022-10-24T13:36:27.826+0100 [INFO]  backend/local: apply calling Apply
2022-10-24T13:36:27.826+0100 [DEBUG] Building and walking apply graph for NormalMode plan
2022-10-24T13:36:27.946+0100 [DEBUG] ProviderTransformer: "module.common_tag_associations.aws_servicecatalog_tag_option_resource_association.this (expand)" (*terraform.nodeExpandApplyableResource) needs provider["registry.terraform.io/hashicorp/aws"]
2022-10-24T13:36:27.946+0100 [DEBUG] ProviderTransformer: "module.servie_catalog_cnb_products.aws_s3_bucket_object.products (expand)" (*terraform.nodeExpandApplyableResource) needs provider["registry.terraform.io/hashicorp/aws"]
2022-10-24T13:36:27.946+0100 [DEBUG] ProviderTransformer: "module.nat_product_attachment.aws_servicecatalog_constraint.template (expand)" (*terraform.nodeExpandApplyableResource) needs provider["registry.terraform.io/hashicorp/aws"]
2022-10-24T13:36:27.946+0100 [DEBUG] ProviderTransformer: "aws_servicecatalog_tag_option.cnb (expand)" (*terraform.nodeExpandApplyableResource) needs provider["registry.terraform.io/hashicorp/aws"]
2022-10-24T13:36:27.946+0100 [DEBUG] ProviderTransformer: "module.cnb_product_attachment.aws_servicecatalog_constraint.notification_constraint (expand)" (*terraform.nodeExpandApplyableResource) needs provider["registry.terraform.io/hashicorp/aws"]
2022-10-24T13:36:27.946+0100 [DEBUG] ProviderTransformer: "module.product_attachment.aws_servicecatalog_product_portfolio_association.product_attachment (expand)" (*terraform.nodeExpandApplyableResource) needs provider["registry.terraform.io/hashicorp/aws"]
2022-10-24T13:36:27.946+0100 [DEBUG] ProviderTransformer: "module.product_attachment.aws_servicecatalog_constraint.notification_constraint (expand)" (*terraform.nodeExpandApplyableResource) needs provider["registry.terraform.io/hashicorp/aws"]
2022-10-24T13:36:27.946+0100 [DEBUG] ProviderTransformer: "module.cnb_product_attachment.aws_servicecatalog_constraint.template (expand)" (*terraform.nodeExpandApplyableResource) needs provider["registry.terraform.io/hashicorp/aws"]
2022-10-24T13:36:27.946+0100 [DEBUG] ProviderTransformer: "data.aws_region.current (expand)" (*terraform.nodeExpandApplyableResource) needs provider["registry.terraform.io/hashicorp/aws"]
2022-10-24T13:36:27.946+0100 [DEBUG] ProviderTransformer: "module.nat_product_attachment.aws_servicecatalog_constraint.notification_constraint (expand)" (*terraform.nodeExpandApplyableResource) needs provider["registry.terraform.io/hashicorp/aws"]
2022-10-24T13:36:27.946+0100 [DEBUG] ProviderTransformer: "module.nat_product_attachment.aws_servicecatalog_constraint.launch (expand)" (*terraform.nodeExpandApplyableResource) needs provider["registry.terraform.io/hashicorp/aws"]
2022-10-24T13:36:27.946+0100 [DEBUG] ProviderTransformer: "module.product_attachment.aws_servicecatalog_constraint.launch (expand)" (*terraform.nodeExpandApplyableResource) needs provider["registry.terraform.io/hashicorp/aws"]
2022-10-24T13:36:27.946+0100 [DEBUG] ProviderTransformer: "module.cnb_product_attachment.aws_servicecatalog_constraint.launch (expand)" (*terraform.nodeExpandApplyableResource) needs provider["registry.terraform.io/hashicorp/aws"]
2022-10-24T13:36:27.946+0100 [DEBUG] ProviderTransformer: "aws_s3_bucket_object.products (expand)" (*terraform.nodeExpandApplyableResource) needs provider["registry.terraform.io/hashicorp/aws"]
2022-10-24T13:36:27.946+0100 [DEBUG] ProviderTransformer: "module.product_attachment.aws_servicecatalog_constraint.template (expand)" (*terraform.nodeExpandApplyableResource) needs provider["registry.terraform.io/hashicorp/aws"]
```

### Expected Behavior

Apply should complete in similar time frame to seen in version 1.2.6.

### Actual Behavior

Apply seem to hang, TF_LOG output suggests may exhaust machine resources. DEBUG output suggest the material difference is in `*terraform.NodeApplyableResourceInstance` (1.3.2, see debug statement suggesting this is per array element, and fails or hangs or is so resource demanding that success is unlikely), vs `*terraform.nodeExpandApplyableResource` (1.2.6, see debug statement suggesting this is per resource type, and succeeds in reasonable time frame).

### Steps to Reproduce

terraform apply

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by jbardin**
The handling of conditions during apply can have adverse affects on very large configs, due to the handling of all existing instances even when there are no changes. With extremely large configurations, the execution time can go from a few minutes to many hours only for minor changes.

The first step is to ensure empty `CheckResults` in the state are normalized to prevent the state from being re-written when there are no semantic differences. Empty and nil slices are not handled consistently overall, but we will use an empty slice in the state zero value to match the other top-level structures.

Next we can skip adding NoOp changes to the apply graph when there are no conditions at all to evaluate from the configuration. The nodes themselves can have significant processing overhead when assembling the graph, especially for steps like recalculating individual instance dependencies.

Finally we need to avoid re-planning each instance and re-writing the state for every NoOp change during apply. The whole process has gotten more convoluted with the addition of condition checks, as preconditions are done during the `NodeAbstractResourceInstance.plan` method, but postconditions are handled outside of the abstract instance in the `NodeApplyableResourceInstance.managedResourceExecute` method, and repetition data needs to be shared between all these. I pulled the repetition data out of `apply` to simplify the early return in the short-term, but there is definitely some more refactoring to be done in this area.

Fixes #32060
Fixes #32071

### CODE REVIEW

File: internal/terraform/node_resource_abstract_instance.go [hunk 1]
```diff
@@ -2059,44 +2066,38 @@ func (n *NodeAbstractResourceInstance) evalDestroyProvisionerConfig(ctx EvalCont
...
-// returned as an error and nil diags are returned.
+// send a nil config. The keyData information can be empty if the config is
+// nil, since it is only used to evaluate the configuration.
 func (n *NodeAbstractResourceInstance) apply(
 	ctx EvalContext,
 	state *states.ResourceInstanceObject,
 	change *plans.ResourceInstanceChange,
 	applyConfig *configs.Resource,
-	createBeforeDestroy bool) (*states.ResourceInstanceObject, instances.RepetitionData, tfdiags.Diagnostics) {
+	keyData instances.RepetitionData,
```
Comment (apparentlymart) [inline internal/terraform/node_resource_abstract_instance.go:2076]: Technically anything which has access to the `EvalContext` can get the "repetition data" like this:

```go
    exp := ctx.InstanceExpander()
    keyData := exp.GetResourceInstanceRepetitionData(n.Addr())
```

In the original design for this "instance expander" thing it was intended to act as the source of record for all of this expansion-related information specifically so that we wouldn't need to explicitly pass all of this contextual data around.

I do feel in two minds about it because it feels like a violation of [Law of Demeter](https://en.wikipedia.org/wiki/Law_of_Demeter), but we already widely use `ctx` as a big bag of shared "global" context, including in this very function where it uses `ctx` to do various other things that aren't strictly this function's business to do.

File: internal/terraform/transform_diff.go [hunk 2]
```diff
@@ -69,7 +93,7 @@ func (t *DiffTransformer) Transform(g *Graph) error {
 			// run any condition checks associated with the object, to
 			// make sure that they still hold when considering the
 			// results of other changes.
-			update = true
+			update = t.hasConfigConditions(addr)
```
Comment (apparentlymart) [inline internal/terraform/transform_diff.go:96]: I feel weird about making the DiffTransformer specifically aware of the preconditions in the config; this feels like some action at a distance that's likely to trip us up under future maintenance just has how not having no-op actions in the graph caused us to ship a subtly broken postconditions feature in the first place. :confounded: 

This very direct approach does seem reasonable as a small, surgical fix for backporting into the v1.3 branch, but I wonder if there's a different way we could arrange this in the v1.4 branch (soon after this is merged) so that this will hopefully be less of a maintenance hazard.

---

One starting idea, though I've not thought deeply about it yet:

* Add yet another optional interface that graph nodes can implement:

    ```hcl
    type GraphNodeDuringApply interface {
        HasApplyTimeActions() bool
    }
    ```
* In a new transformer after we've done all the ones that insert new nodes, prune from the graph any node which implements this interface and `HasApplyTimeActions()` returns `false`.
* If even inserting them in the first place is problematic then we could optionally optimize this by having `DiffTransformer` pre-check for the interface itself and not even insert the node in the first place. But my hope is that this wouldn't be necessary because we could do the pruning early enough that it's done by the time we get into all of the expensive transformers that do edge analysis.

Then this "are there any conditions?" logic could live in `GraphNodeApplyableResourceInstance` (and similar), closer to the `Execute` function that it's acting as a gate for. It would presumably return `false` unless the action is something other than `NoOp` _or_ there's at least one condition to check.

Since I'm explicitly not suggesting we do this refactoring as a blocker for this PR, happy to discuss this more in a more appropriate place after this is merged. :grinning:

**Review by apparentlymart — APPROVED** [review]
This makes sense to me as a tactical fix for the v1.3 series. Thanks for digging into this!

I left some notes inline about things that are more architectural, so I expect we'll ignore them for the purposes of merging this PR but I'd like to consider them for follow-up improvements in the v1.4 branch to hopefully have a couple less potential hazards for future maintenance.

File: internal/terraform/node_resource_abstract_instance.go (hunk 1 above)
Comment (jbardin) [reply internal/terraform/node_resource_abstract_instance.go:2076]: Yes, I left this as close to the current code as possible. I did forget that the rep data was directly available though, because the existing apply code already re-evaluated it anyway. Switching out that code however runs into a no `expansion has been registered` panic, so I think there's something else going on here too.

File: internal/terraform/transform_diff.go (hunk 2 above)
Comment (jbardin) [reply internal/terraform/transform_diff.go:96]: I tried a few different approaches here, and settled on this config reference only meant as a stop-gap. I think since we do store the plan check results, the results of those could be included in the "diff" that we're handling here. I was running into problems with inconsistent handling of the results however, because those have separate codepaths from normal changes, and this turned out to be a safer and more reliable failsafe for now.  Since unknown checks from planning also would indicate "HasApplyTimeActions", it may be worth seeing if we can incorporate the checks more closely with the plan object so they are always in sync.

File: internal/terraform/node_resource_abstract_instance.go (hunk 1 above)
Comment (apparentlymart) [reply internal/terraform/node_resource_abstract_instance.go:2076]: Hmm yes I suppose the fact that we've been passing it around through arguments meant that there was not previously any need to actually register it at the source of record. Unfortunate but not unexpected.

Hopefully in a future change we can find a suitable central point to evaluate this just once and register it in the expander, so it's clearer exactly whose responsibility it is to evaluate the `for_each` or `count` expressions.

**Comment by jbardin** [comment]
The earlier branches were no longer needed for this patch, so I rebased this on main in order to merge it for the release.
