### PR TITLE
provider/aws: Error when unable to find a Root Block Device name

### LINKED ISSUE #2633: device_name now required on root_block_device of AWS_LAUNCH_CONFIGURATION
Pre 0.6.0 I had the following in terraform

```
resource "aws_launch_configuration" "service_launch_configuration" {
    name = "${var.service_name}-1.0.1-lc"
    image_id = "${var.service_ami}"
    instance_type = "m3.medium"
    iam_instance_profile = ""
    key_name = "ami-key-pair"
    security_groups = ["${aws_vpc.env_vpc.default_security_group_id}"]
    associate_public_ip_address = true

    root_block_device {
        volume_type = "gp2"
        volume_size = "64"
    }
}

```

Now in 0.6.0 I get the following error:
```
* Error creating launch configuration: InvalidParameter: 1 validation errors:
- missing required parameter: BlockDeviceMappings[0].DeviceName
```

The docs at https://terraform.io/docs/providers/aws/r/launch_configuration.html don't indicate this as a new requirement?

### PR DESCRIPTION
**Pull request by catsby**
Fixes #2633 by returning an error if we can't find a Root Block Device 

With a config like this (using an ami that is Instance backed):

```javascript
provider "aws" {
    region = "us-west-2"
}
resource "aws_launch_configuration" "foobar" {
    name = "root_ami_thing"
    image_id = "ami-3fd3e90f"
    instance_type = "t2.micro"
    key_name = "packerkeything"

    root_block_device {
        volume_type = "gp2"
        volume_size = "64"
    }
}

resource "aws_autoscaling_group" "bar" {
  availability_zones = ["us-west-2a"]
  name = "foobar3-terraform-test"
  max_size = 2
  min_size = 0
  health_check_grace_period = 300
  health_check_type = "ELB"
  desired_capacity = 2
  force_delete = true
  termination_policies = ["OldestInstance"]
  launch_configuration = "${aws_launch_configuration.foobar.name}"
}
```

Now produces error: 

```
Error applying plan:

1 error(s) occurred:

* [WARN] Error finding Root Device Name for AMI (ami-3fd3e90f)
```

Instead of the error shown in #2633

### CODE REVIEW

**Comment by catsby** [comment]
cc @phinze to double check that erring there is reasonable

File: builtin/providers/aws/resource_aws_instance.go [hunk 1]
```diff
@@ -760,6 +760,10 @@ func fetchRootDeviceName(ami string, conn *ec2.EC2) (*string, error) {
 		rootDeviceName = image.BlockDeviceMappings[0].DeviceName
 	}
 
+	if rootDeviceName == nil {
+		return nil, fmt.Errorf("[WARN] Error finding Root Device Name for AMI (%s)", ami)
```
Comment (phinze) [inline builtin/providers/aws/resource_aws_instance.go]: In the linked issue the problem was a bad AMI ID, which means we would have hit the early nil return up on L735.

We specifically added that "no error when AMI not found" thingy in https://github.com/hashicorp/terraform/pull/1250 to fix unrecoverable error states because it was being hit in `Read`.

So we need to figure out how we can maintain the "allow users to correct bad AMIs" while still getting a specific error message when they specify one.

**Comment by phinze** [comment]
Commented inline - I think we'll need to dig into this.

File: builtin/providers/aws/resource_aws_instance.go (hunk 1 above)
Comment (catsby) [inline builtin/providers/aws/resource_aws_instance.go]: > In the linked issue the problem was a bad AMI ID, which means we would have hit the early nil return up on L735.

Let's sync up to discuss. The issue I was debugging (and the only way I could repo the source issue) did not trigger L735; there was an image, but there was no root device matching in the lines above this. I couldn't use an AMI that didn't exist; TF returned an error before this point. I'll double check though...

Comment (catsby) [inline builtin/providers/aws/resource_aws_instance.go]: For example, when I use a bad AMI in this context (Launch Configuration):

```
* InvalidAMIID.Malformed: Invalid id: "ami-nopenope"
	status code: 400, request id: []
```

Comment (catsby) [inline builtin/providers/aws/resource_aws_instance.go]: @phinze did you see my updates here? Hopefully they made sense, let's sync up and see what we need to do

Comment (phinze) [inline builtin/providers/aws/resource_aws_instance.go]: @catsby ah okay. so if we can verify that these steps still work:

 * create ami
 * create instance from AMI
 * delete ami
 * terraform refresh should not error

If that still is the case, then we're good to go.

Comment (catsby) [inline builtin/providers/aws/resource_aws_instance.go]: > terraform refresh should not error

It does not _error_... but a Launch Configuration will show a `-/+` , since the AMI no longer exists ...

**Comment by catsby** [comment]
Pulling this in

**Comment by ikalinin** [comment]
This change makes it impossible to use instance-store backed Amazon Linux images since they don't have a root device name on them. Please consider rolling this change back and finding another solution for #2633.

**Comment by catsby** [comment]
Hey @ikalinin – sorry for the trouble here! Do you have an example configuration for me to test out? I think we can avoid this error by checking the `image.RootDeviceType` and only throwing an error if is of type `ebs`, but I'm not entirely sure what the behavior should be for instance-store backed AMIs. Can you help me get this right? 

I was able to reproduce the error using AMI `ami-961bfaa5`, an Ubuntu Trusty in the us-west-2 region.
