### PR TITLE
Decode change values with marks

### LINKED ISSUE #28671: Always changing plan with sensitive values
If a submodule has a sensitive output that is not marked explicitly sensitive, using it in a resource will make it always changing.

### Terraform Version
```
0.15.3
```

### Terraform Configuration Files
Root module
```terraform
module "submodule" {
  source = "./submodule"
}

resource "null_resource" "foo" {
  triggers = {
    foo = module.submodule.foo
  }
}
```
Submodule
```terraform
output "foo" {
  value     = sensitive("foo")
}
```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`
3. `terraform apply`

At this point I would expect a noop plan but it's actually
```
Terraform will perform the following actions:

  # null_resource.foo will be updated in-place
  ~ resource "null_resource" "foo" {
        id       = "2229254378513900712"
      ~ triggers = {
          # Warning: this attribute value will be marked as sensitive and will
          # not display in UI output after applying this change
          ~ "foo" = (sensitive)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

If I mark the `foo` output `sensitive` the update loop is resolved.

### PR DESCRIPTION
**Pull request by jbardin**
When decoding change values, the stored marks should be applied to the decoded value, as this is the direct inverse of the `Encode` operation. The missing marks were not noticed in most cases because they would be correctly re-evaluated on demand, however some cases like module output values can rely on the change source alone, resulting in the marks being lost during apply.

Many call sites which were aware that the marks were missing would manually apply the marks after decoding. After removing the duplicate marking and verifying tests, `Decode` call sites were again statically located and checked for mark handling. Any locations found that were relying on the _absence_ of marks now must manually strip the marks before processing the values.

Fixes #28671

### CODE REVIEW

**Comment by NestorRV** [comment]
Is this going to be released within 2.59.0? @jbardin

File: command/jsonplan/plan.go [hunk 1]
```diff
@@ -212,10 +212,15 @@ func (p *plan) marshalResourceChanges(changes *plans.Changes, schemas *terraform
 		if err != nil {
 			return err
 		}
+		// We drop the marks from the change, as decoding is only an
+		// intermediate step to re-encode the values as json
+		changeV.Before, _ = changeV.Before.UnmarkDeep()
+		changeV.After, _ = changeV.After.UnmarkDeep()
```
Comment (alisdair) [inline command/jsonplan/plan.go:218]: Rather than mutating the struct, it might be clearer to bind the results of the `UnmarkDeep` calls to locals inside the `if changeV.[Before|After]` != cty.NilVal` blocks below. Those are already messily referring back to the change source to retrieve the marks.

One other worry here is that I think calling `UnmarkDeep` on `cty.NilVal` might crash. I'm not completely sure that this is the case, but moving the unmarking inside the if blocks feels safer.

(Same thought for the other changes in this package.)

**Review by alisdair — COMMENTED** [review]
This definitely feels clearer to me. One suggestion/abstract worry inline. Will test locally then ✅

**Review by alisdair — APPROVED** [review]
Verified that all my `sensitive` manual test cases continue to work as expected!

File: command/jsonplan/plan.go (hunk 1 above)
Comment (jbardin) [reply command/jsonplan/plan.go:218]: I verified that `UnmarkDeep` in a noop with a nil val, and opted to overwrite the fields here to leave the rest of the code as unchanged as possible. 

I also don't particularly like mutating the value, but since the `changeV` values have no way of leaking out from this package, I went with the smaller change.
