### PR TITLE
Instance state only destroys

### LINKED ISSUE #14548: Cycle error on module output/input when input used in destroy provisioner
It seems this issue i'm running into should have been fixed by 1835/1855.  However, I am still getting a cycle when I have two modules, one with an output that the other is taking as an input.   The only thing that I can tell differentiates me from 1835/1855 is that the input is used in a destroy provisioner.

Given:
main.tf

```
module "a_module" {
  source = "./a_module"
}
module "b_module" {
  source = "./b_module"
  a_id = "${module.a_module.a_output}"
}
```
a_module/main.tf

```
resource "null_resource" "a" {
}
output "a_output" {
  value = "${null_resource.a.id}"
}
```

b_module/main.tf

```
variable "a_id" {}
resource "null_resource" "b" {
  provisioner "local-exec" {
    command = "echo ${var.a_id}"
  }
  provisioner "local-exec" {
    when = "destroy" 
    command = "echo ${var.a_id}"
  }
}
```
Apply works

```
>terraform apply
module.a_module.null_resource.a: Creating...
module.a_module.null_resource.a: Creation complete (ID: 7834569308481174192)
module.b_module.null_resource.b: Creating...
module.b_module.null_resource.b: Provisioning with 'local-exec'...
module.b_module.null_resource.b (local-exec): Executing: cmd /C "echo 7834569308481174192"
module.b_module.null_resource.b (local-exec): 7834569308481174192
module.b_module.null_resource.b: Creation complete (ID: 6375952926384638186)

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path:
```
Destroy calls Cycle!  
```
>terraform destroy
Do you really want to destroy?
  Terraform will delete all your managed infrastructure.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

null_resource.a: Refreshing state... (ID: 7834569308481174192)
null_resource.b: Refreshing state... (ID: 6375952926384638186)
Error applying plan:

1 error(s) occurred:

* Cycle: module.a_module.null_resource.a (destroy), module.a_module.output.a_output, module.b_module.var.a_id, module.b_module.null_resource.b (destroy)

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```
Could the destroy graph just destroy the one with destroy provisioners first?

### LINKED ISSUE #16237: cycle reported when using resource attribute interpolation in local-exec destroy provisioner
I have a relatively simple configuration that contains an `aws_instance` with a `local-exec` provisioner with `when=destroy` to cleanly shut down services and unmount an EBS Volume (that's attached via userdata). The provisioner command includes an interpolation of the aws_instance's ``public_ip`` attribute. However, an apply that replaces the instance (i.e. a user-data change) reports a cycle. The cycle disappears if I remove the provisioner or remove the interpolation from the command.

For... reasons... my use case isn't really a candidate for a remote-exec destroy provisioner.

### Terraform Version

0.10.6

### Terraform Configuration Files

https://github.com/jantman/tf-vol-attachment-cycle

### Debug Output

See https://github.com/jantman/tf-vol-attachment-cycle

* [with provisioner](https://github.com/jantman/tf-vol-attachment-cycle/blob/master/with_local_exec.txt) (failure)
* [without provisioner](https://github.com/jantman/tf-vol-attachment-cycle/blob/master/without_local_exec.txt) (success)
* [without interpolation](https://github.com/jantman/tf-vol-attachment-cycle/blob/master/without_interpolation.txt) (success)

### Expected Behavior

One of:

1. (preferred) When userdata changes, terraform should replace the `aws_instance` as planned, without a "phantom" cycle. This is a __destroy__ provisioner, so it should know the instance's _current_ attributes (just like a connection block would).
2. (less bad than current) Terraform __plan__ fails with an error along the lines of "Resource attribute interpolations are not permitted in provisioners for that resource".

### Actual Behavior

```
Error applying plan:

1 error(s) occurred:

* Cycle: aws_instance.ecs-instance (destroy), aws_instance.ecs-instance
```

### Steps to Reproduce

1. ``git clone https://github.com/jantman/tf-vol-attachment-cycle.git``
2. Export AWS credentials and ``AWS_REGION``.
3. ``SUBNET_ID=<subnet-XXX> ./run.sh``

### LINKED ISSUE #17944: Circular dependency when provisioner for destroy references array member for AWS
To resolve problem with disk attachment on AWS (disk attachement cannot be destroyed when disk is mounted on OS level) I created following code:

```hcl
resource "aws_volume_attachment" "attachement_myservice" {
  count			=	"${length(var.network_myservice_subnet_ids)}"
  device_name   = "/dev/xvdg"
  volume_id     =   "${element(aws_ebs_volume.ebs_myservice.*.id, count.index)}"
  instance_id   =   "${element(aws_instance.myservice.*.id, count.index)}"

  provisioner "local-exec" {
    command = "aws ec2 stop-instances --instance-ids ${element(aws_instance.myservice.*.id, count.index)} --region ${var.region} && sleep 30"
    when = "destroy"
  }
}
```

When trying to rebuild instances (because AMI instances depend on) terraform reports circular dependency for this code. Experiment shows that the problem is with shell command - when reference `${element(aws_instance.myservice.*.id, count.index)}` is replaced with something different terraform works like a charm (production solution for me is to use AWS CLI to first find instance IDs and then use them to stop instances).

Most probably root cause is wrong interpretation of interpolation of array member when building graph for rebuild.

Problem doesn't exist when `terraform destroy` is executed - only on `terraform apply` which is expected to re-build instances.
 

### Terraform Version

```
terraform -v
Terraform v0.11.3

Your version of Terraform is out of date! The latest version
is 0.11.7. You can update by downloading from www.terraform.io/downloads.html

```

### Terraform Configuration Files

```hcl
...
```

### LINKED ISSUE #18026: terraform destroy tries to evaluate outputs that can refer to non existing resources
### Terraform Version

0.11.7

### Terraform Configuration Files

during apply:

```hcl
resource "null_resource" "a" {
}

output "foo" {
  value = "${list(null_resource.a.id)}"
}
```

during destroy:

```hcl
resource "null_resource" "a" {
}

resource "null_resource" "b" {
}

output "foo" {
  value = "${list(null_resource.a.id, null_resource.b.id)}"
}
```

### Debug Output
https://gist.github.com/mildred/af89828e68b53f996e3132f1eed26229

### Output

```
$ terraform-0.11.7 destroy
null_resource.a: Refreshing state... (ID: 4128732092189392605)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  - null_resource.a


Plan: 0 to add, 0 to change, 1 to destroy.

Do you really want to destroy?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes


Error: Error applying plan:

1 error(s) occurred:

* output.foo: Resource 'null_resource.b' does not have attribute 'id' for variable 'null_resource.b.id'

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

```

### Expected Behavior

No error should have happened. Terraform should detect that null_resource.b was never created and whouldn't try to access it. Anyway, it doesn't need to generate outputs on destroy.

### Actual Behavior

Terraform tries to evaluate the output referring to a non existing resource and fails on it.

### Steps to Reproduce

- Write to `example.tf` the first version of the file
- `terraform init`
- `terraform apply`
- Write to `example.tf` the second version of the file
- `terraform destroy`

### Additional Context
This is an error that initially happened with an AWS resource but could be reproduced with null_resource.

### LINKED ISSUE #18088: Faulty resource circular dependency detection
### Terraform Version

```
Terraform v0.11.7
+ provider.aws v1.18.0
+ provider.external v1.0.0
+ provider.null v1.0.0
+ provider.random v1.2.0
+ provider.template v1.0.0
```
### Terraform Configuration Files

```hcl
resource "null_resource" "tag_vpc" {
  depends_on = ["module.base_servers"]

  triggers {
    random_bs_number = "${uuid()}"
  }

  provisioner "local-exec" {
    command = "aws ec2 create-tags ..."
  }
}
```

And In base_servers there is a haproxy module with ASG deployment.

### Debug Output

```
* Cycle: module.location_deployment.module.base_servers.module.haproxy.random_id.unique_suffix (destroy), module.location_deployment.module.base_servers.module.haproxy.aws_launch_configuration.haproxy_lc (destroy), module.location_deployment.module.base_servers.module.haproxy.aws_autoscaling_group.haproxy_asg (destroy), module.location_deployment.null_resource.tag_vpc
```

### Expected Behavior
Replace the launch config and the ASG with the new AMI and tag the VPC once finished. ASG and LC have the create_before_destroy=true specified according to the docs: https://www.terraform.io/docs/providers/aws/r/launch_configuration.html

### Actual Behavior
ERROR: Terraform claims there is a circular dependency, which there is not.

### Additional Context

I have a VPC tagging post-processing resource that is trying to tag the VPC with a version and set a state of deployment to be finished instead of in progress.... Now this all works well right up to the point when an update needs to be made to one of the autoscaling groups that have lifecycle{create_before_destroy=true} set. Right around then terraform seems to lose its marbles and it claims that my vpc tagging seems to be conflicting with the asg replacement, which it shouldn't and it wouldn't but Terraform seems to insist this is the case:

### LINKED ISSUE #18356: terraform error on destroy when evaluating output referring to uncreated resource
### Terraform Version
v0.11.7

### Terraform Configuration Files

```hcl
variable "cluster_size" {
}

resource "aws_instance" "coreos" {
  count = "${var.cluster_size}"
  ...
  // for some reason this resource will fail to be created
  ...
  lifecycle {
    create_before_destroy = true
  }
}

// Don't look at the strange things there, that's not the point of the bug:

resource "random_pet" "cluster_size" {
  keepers {
    token = "${var.cluster_size}"
  }
}
resource "random_pet" "memory" {
  keepers {
    token = "${element(aws_instance.coreos.*.id, 0)}"
  }
  length = "${var.cluster_size}"
  prefix = "${random_pet.cluster_size.id}"
  lifecycle {
    ignore_changes = ["prefix", "length"]
  }
}

output "consul_bootstrap_expect" {
  value = "${(random_pet.memory.length == var.cluster_size && random_pet.memory.prefix == random_pet.cluster_size.id) ? "-bootstrap-expect=${random_pet.memory.length}" : ""}"
}

```

### Output

terraform plan && terraform apply was executed, the aws_instance failed to create (for some obscure AWS reason):

```
[vision-heat-redhold][f71065b2-9743-4331-9c9e-7bbb62491365] 2018/06/26 18:25:20 * aws_instance.coreos.1: Error waiting for instance (i-05c95dfbead0dc9f0) to become ready: Failed to reach target state. Reason: Server.InternalError: Internal error on launch
```

At that point the tfstate contains random_pet.cluster_size, **does not contain random_pet.memory** and does not contains output.consul_bootstrap_expect

Then we executed terraform refresh because of bug *terraform shows too much items in outputs when reducing the count of a create_before_destroy resource* #16473

At that point the tfstate contains random_pet.cluster_size, **does not contain random_pet.memory** and **contains output.consul_bootstrap_expect** which is illogical because the output needs the random_pet.cluster_size to evaluate. So one cannot exist without the other...

Then we run terraform plan -destroy and terraform apply to execute the destruction of all resources. The apply fails with:

```
* output.consul_bootstrap_expect: Resource 'random_pet.memory' does not have attribute 'length' for variable 'random_pet.memory.length'
```

which is normal because random_pet.memory does not exists in tfstate (but the output does)

### Expected Behavior

destruction should work correctly

### Actual Behavior

destruction failed because it tried to evaluate an output with non existing resource. This is perhaps a more problematic instance of *terraform destroy tries to evaluate outputs that can refer to non existing resources* #18026

### Steps to Reproduce
difficult to tell because it triggers only when terraform apply fails for the first time and stops before all resources are created

### Additional Context
all run in automated processes

### References

- *terraform shows too much items in outputs when reducing the count of a create_before_destroy resource* #16473
- *terraform destroy tries to evaluate outputs that can refer to non existing resources* #18026

### LINKED ISSUE #21610: Propagation of create_before_destroy = true
### Terraform Version
```
Terraform v0.12.0
+ provider.random v2.1.2
+ provider.tls v2.0.1
```

### Terraform Configuration Files
```hcl
resource "random_integer" "bits" {
  min = 2048
  max = 4096
}
resource "tls_private_key" "terraform" {
  algorithm = "RSA"
  rsa_bits = random_integer.bits.result
  lifecycle {
    create_before_destroy = true
  }
}

```

### Expected Behavior
Only the `tls_private_key` should be created before destroy.

### Actual Behavior
Both resources will create the replacement first then destroy the old instance.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`
3. `terraform taint random_integer.bits`
4. `terraform taint tls_private_key.terraform`
5. `terraform plan`

### Additional Context
Output from terraform plan (simplified):
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+/- create replacement and then destroy

Terraform will perform the following actions:

  # random_integer.bits is tainted, so must be replaced
+/- resource "random_integer" "bits" {
      ~ id     = "3232" -> (known after apply)
        max    = 4096
        min    = 2048
      ~ result = 3232 -> (known after apply)
    }

  # tls_private_key.terraform is tainted, so must be replaced
+/- resource "tls_private_key" "terraform" {
        algorithm                  = "RSA"
        ecdsa_curve                = "P224"
      ~ id                         = "3ff51c9479f37e8906fd4bda0c07cce5bccbc57a" -> (known after apply)
      ~ private_key_pem            = "<ommited for simplicity>" -> (known after apply)
      ~ public_key_fingerprint_md5 = "85:40:0e:0c:06:c1:dd:c5:58:e2:2a:14:00:67:d7:1b" -> (known after apply)
      ~ public_key_openssh         = "<ommited for simplicity>" -> (known after apply)
      ~ public_key_pem             = "<ommited for simplicity>" -> (known after apply)
      ~ rsa_bits                   = 3232 -> (known after apply)
    }

Plan: 2 to add, 0 to change, 2 to destroy.

```
Setting a lifecycle with `create_before_destroy = false` for `random_integer` has no effect.

Seems like the `create_before_destroy = true` is being propagated via the graph. I don't know if it is a bug or an undocumented feature (I hope its a bug). Even if it is a feature "overriding" the `create_before_destroy` on `random_integer` should work.

The terraform configuration given is just an example chosen for its simplicity. The problem will also arise with other resources.

### LINKED ISSUE #23196: Provisioner when destroy cycle
### Terraform Version

```
terraform -v
Terraform v0.12.12
+ provider.null v2.1.2
```

### Terraform Configuration Files

Module 1:
```hcl
variable A {
    type = map(string)
}

resource "null_resource" "A" {
    for_each = var.A
    triggers = {
        v=each.value
    }
    provisioner "local-exec" {
        command = "echo Create Resource ${each.key}-${each.value} "
    } 
}

output "Object" {
  value = [for k,v in null_resource.A:
      {
          key   = k
          value = var.A[k]
          AID   = v.id
      }
  ]
}
```
Module 2:
```hcl
variable "A" {
  type = list(object({
      key   = string
      value = string
      AID   = string
    }))
}

variable "Count_configs" {type = number}

resource "null_resource" "Config" {
  count = var.Count_configs
  triggers = {
    v = var.A[count.index].value
  } 
  provisioner "local-exec" {
    command = "echo Configure ${var.A[count.index].key}-${var.A[count.index].value} "
  }

  provisioner "local-exec" {
    when = "destroy"
    command = "echo Destroy config ${var.A[count.index].key}-${var.A[count.index].value} "
  }
}
```
Module 3:
```hcl
variable A {
    type = map(string)
    default = {
        Key1 = "V1"
        Key2 = "V2"
        Key3 = "V3"
    }
}

module "Resources" {
  source = "../module1"
  A      = var.A
}

module "Configs" {
  source        = "../module2"
  Count_configs = length(var.A)
  A             = module.Resources.Object
}
```

v1.tfvars
```hcl
A = {
    Key1 = "V10"
    Key2 = "V20"
    Key3 = "V30"
}
```

### Crash Output

https://gist.github.com/eddytrex/d2be154d5172b9053dcb2c7ba62c3037

### Expected Behavior

In the second apply it should: destroy the the null_resource.Config resource with the previous values, destroy the null_resource.A with the previous values, recreate null_resource.A and lastly recreate null_resource.Config

### Actual Behavior

```bash
module.Resources.null_resource.A["Key3"]: Refreshing state... [id=3417427815421531061]
module.Resources.null_resource.A["Key1"]: Refreshing state... [id=148907161230582130]
module.Resources.null_resource.A["Key2"]: Refreshing state... [id=1963858428133357225]
module.Configs.null_resource.Config[0]: Refreshing state... [id=3303131520289021751]
module.Configs.null_resource.Config[2]: Refreshing state... [id=1900602850461495067]
module.Configs.null_resource.Config[1]: Refreshing state... [id=6212963663486443828]

Error: Cycle: module.Resources.null_resource.A["Key1"], module.Resources.null_resource.A["Key2"], module.Resources.null_resource.A["Key2"] (destroy), module.Configs.null_resource.Config[0] (destroy), module.Configs.null_resource.Config[2] (destroy), module.Resources.null_resource.A["Key1"] (destroy), module.Resources.null_resource.A["Key3"], module.Resources.output.Object, module.Configs.var.A, module.Configs.null_resource.Config[1] (destroy), module.Resources.null_resource.A["Key3"] (destroy)
```

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply -auto-approve module3`
3.  `terraform apply -var-file="v1.tfvars" -auto-approve module3`

### Additional Context

If you remove  the provisioner in the module2.null_resource.Config:
``` hcl
provisioner "local-exec" {
    when = "destroy"
    command = "echo Destroy config ${var.A[count.index].key}-${var.A[count.index].value} "
  }
```
it works, also if  you add 
```hcl
  lifecycle {
    create_before_destroy = true
  }
```
But it does not execute the: `echo Destroy config ${var.A[count.index].key}-${var.A[count.index].value
  }`

I don't know if is possible to run `echo Destroy config ${var.A[count.index].key}-${var.A[count.index].value
  }` with the previous values  because there are not in the state file (maybe it should render the command when apply).
 
Thanks.

### LINKED ISSUE #23365: Outputs are evaluated before resource updates which can cause unnecessary errors
### Terraform Version
```
Terraform v0.12.14
```

### Terraform Configuration Files
```hcl
variable "my_list" {
  default = [
    "foo",
    "bar",
  ]
}

resource "random_uuid" "example" {
  count = length(var.my_list)
}

output "example" {
  value = zipmap(var.my_list, random_uuid.example.*.id)
}
```

### Expected Behavior
Given the above config, I run `terraform apply`.
Everything should run successfully and my outputs should be as expected.
Then I decide I no longer need `bar` so I remove it from `my_list` and run `terraform apply`.
I'd expect this to work.

### Actual Behavior
I get the following error:
```
Error: Error in function call

  on example.tf line 12, in output "example":
  12:   value = zipmap(var.my_list, random_uuid.example.*.id)
    |----------------
    | random_uuid.example is tuple with 2 elements
    | var.my_list is tuple with 1 element

Call to function "zipmap" failed: number of keys (1) does not match number of
values (2).
```

### Steps to Reproduce
1. create config as above
2. `terraform init`
3. `terraform apply`
4. remove `bar` from `my_list`
5. `terraform apply` 

### Additional Context
I can understand why it's failing - zipmap requires that the 2 lists are of equal length and the removal of `bar` from the list means this is no longer true on the second apply however I'd expect the output to be evaluated AFTER the resource updates.

I'd expect the following order of events:
1. evaluate `var.my_list` (length has changed from 2 to 1)
2. evaluate `random_uuid.example` and `count = length(var.my_list)` (count has changed from 2 to 1)
3. remove resource `random_uuid.example[1]` due to the changed count
4. evaluate `output.example` where `var.my_list` now has a length of 1 and `random_uuid.example.*.id ` also now has a length of 1.

I assume there's some validation happening before the resource is updated and the new `var.my_list.length` is being compared against the old `random_uuid.example.length`

### LINKED ISSUE #23875: Applying a plan to `-destroy` fails, while destroy succeeds
### Terraform Version
Tested on both 0.12.18 and 0.12.19
```
➜ terraform version
Terraform v0.12.19
```

### Terraform Configuration Files
Can be found on the [sample repo](https://github.com/env0/terraform-destroy-bug) along with the [steps to reproduce](#Steps-to-Reproduce)

### Expected Behavior
Running either: 
```
terraform plan -destroy -out=destroy.tf-plan
...
terraform apply destroy.tf-plan
```
or
```
terraform destroy [-auto-approve]
```
should destroy the resources

### Actual Behavior
Running the latter succeeds in destroying the resources, while the former reports an error:  
```
Error: Cycle: module.cluster.output.host, module.cluster.output.password, module.cluster.output.cluster_ca_certificate, provider.kubernetes, module.kubernetes.kubernetes_storage_class.ssd (destroy), module.cluster.google_container_cluster.cluster (destroy)
```

### Steps to Reproduce
1. Place a `credentials.json` with your google account.
2. Create a project in your google account `env0project` (or set your project as `var.gcp_project`)
3. `➜ terraform init`
    <details><summary>(output)</summary>
    <p>
      
      ```      
    Initializing modules...
    - cluster in modules/cluster
    - kubernetes in modules/kubernetes

    Initializing the backend...

    Initializing provider plugins...
    - Checking for available provider plugins...
    - Downloading plugin for provider "google" (hashicorp/google) 3.3.0...
    - Downloading plugin for provider "google-beta" (terraform-providers/google-beta) 3.3.0...
    - Downloading plugin for provider "kubernetes" (hashicorp/kubernetes) 1.9.0...
    - Downloading plugin for provider "null" (hashicorp/null) 2.1.2...
    - Downloading plugin for provider "random" (hashicorp/random) 2.2.1...
    - Downloading plugin for provider "external" (hashicorp/external) 1.2.0...
    - Downloading plugin for provider "tls" (hashicorp/tls) 2.1.1...

    Terraform has been successfully initialized!
      
      ```
      
  </p>
  </details>
  
4. `➜ terraform apply`

    <details><summary>(output)</summary>
    <p>
      
      ```      
    module.cluster.data.google_container_engine_versions.valid_gke_versions: Refreshing state...

    An execution plan has been generated and is shown below.
    Resource actions are indicated with the following symbols:
    + create

    Terraform will perform the following actions:

    # module.cluster.google_compute_address.gke-outgoing-address[0] will be created
    + resource "google_compute_address" "gke-outgoing-address" {
        + address            = (known after apply)
        + address_type       = "EXTERNAL"
        + creation_timestamp = (known after apply)
        + id                 = (known after apply)
        + name               = "default-gke-outgoing-nat-address-0"
        + network_tier       = (known after apply)
        + project            = (known after apply)
        + purpose            = (known after apply)
        + region             = "us-east1"
        + self_link          = (known after apply)
        + subnetwork         = (known after apply)
        + users              = (known after apply)
        }

    # module.cluster.google_compute_address.gke-outgoing-address[1] will be created
    + resource "google_compute_address" "gke-outgoing-address" {
        + address            = (known after apply)
        + address_type       = "EXTERNAL"
        + creation_timestamp = (known after apply)
        + id                 = (known after apply)
        + name               = "default-gke-outgoing-nat-address-1"
        + network_tier       = (known after apply)
        + project            = (known after apply)
        + purpose            = (known after apply)
        + region             = "us-east1"
        + self_link          = (known after apply)
        + subnetwork         = (known after apply)
        + users              = (known after apply)
        }

    # module.cluster.google_compute_global_address.external-ip will be created
    + resource "google_compute_global_address" "external-ip" {
        + address            = (known after apply)
        + creation_timestamp = (known after apply)
        + id                 = (known after apply)
        + name               = "default-backend-ip"
        + project            = (known after apply)
        + self_link          = (known after apply)
        }

    # module.cluster.google_compute_network.network will be created
    + resource "google_compute_network" "network" {
        + auto_create_subnetworks         = true
        + delete_default_routes_on_create = false
        + gateway_ipv4                    = (known after apply)
        + id                              = (known after apply)
        + ipv4_range                      = (known after apply)
        + name                            = "default-vpc"
        + project                         = (known after apply)
        + routing_mode                    = (known after apply)
        + self_link                       = (known after apply)
        }

    # module.cluster.google_compute_router.gke-outgoing-router will be created
    + resource "google_compute_router" "gke-outgoing-router" {
        + creation_timestamp = (known after apply)
        + id                 = (known after apply)
        + name               = "default-gke-outgoing-router"
        + network            = (known after apply)
        + project            = (known after apply)
        + region             = "us-east1"
        + self_link          = (known after apply)
        }

    # module.cluster.google_compute_router_nat.gke-outgoing-nat will be created
    + resource "google_compute_router_nat" "gke-outgoing-nat" {
        + icmp_idle_timeout_sec              = 30
        + id                                 = (known after apply)
        + min_ports_per_vm                   = 16384
        + name                               = "default-gke-outgoing-nat"
        + nat_ip_allocate_option             = "MANUAL_ONLY"
        + nat_ips                            = (known after apply)
        + project                            = (known after apply)
        + region                             = "us-east1"
        + router                             = "default-gke-outgoing-router"
        + source_subnetwork_ip_ranges_to_nat = "LIST_OF_SUBNETWORKS"
        + tcp_established_idle_timeout_sec   = 1200
        + tcp_transitory_idle_timeout_sec    = 30
        + udp_idle_timeout_sec               = 30

        + log_config {
            + enable = true
            + filter = "ALL"
            }

        + subnetwork {
            + name                     = "https://www.googleapis.com/compute/v1/projects/env0project/regions/us-east1/subnetworks/default-vpc"
            + secondary_ip_range_names = []
            + source_ip_ranges_to_nat  = [
                + "ALL_IP_RANGES",
                ]
            }
        }

    # module.cluster.google_container_cluster.cluster will be created
    + resource "google_container_cluster" "cluster" {
        + cluster_ipv4_cidr           = (known after apply)
        + default_max_pods_per_node   = (known after apply)
        + enable_binary_authorization = (known after apply)
        + enable_kubernetes_alpha     = false
        + enable_legacy_abac          = false
        + enable_tpu                  = (known after apply)
        + endpoint                    = (known after apply)
        + id                          = (known after apply)
        + initial_node_count          = 1
        + instance_group_urls         = (known after apply)
        + location                    = "us-east1-b"
        + logging_service             = "logging.googleapis.com/kubernetes"
        + master_version              = (known after apply)
        + min_master_version          = "1.14.10-gke.0"
        + monitoring_service          = "monitoring.googleapis.com/kubernetes"
        + name                        = "default-cluster"
        + network                     = (known after apply)
        + node_locations              = (known after apply)
        + node_version                = (known after apply)
        + project                     = (known after apply)
        + remove_default_node_pool    = true
        + resource_labels             = {
            + "workspace" = "default"
            }
        + services_ipv4_cidr          = (known after apply)
        + subnetwork                  = (known after apply)

        + addons_config {
            + horizontal_pod_autoscaling {
                + disabled = (known after apply)
                }

            + http_load_balancing {
                + disabled = (known after apply)
                }

            + kubernetes_dashboard {
                + disabled = (known after apply)
                }

            + network_policy_config {
                + disabled = (known after apply)
                }
            }

        + authenticator_groups_config {
            + security_group = (known after apply)
            }

        + cluster_autoscaling {
            + enabled = (known after apply)

            + auto_provisioning_defaults {
                + oauth_scopes    = (known after apply)
                + service_account = (known after apply)
                }

            + resource_limits {
                + maximum       = (known after apply)
                + minimum       = (known after apply)
                + resource_type = (known after apply)
                }
            }

        + ip_allocation_policy {
            + cluster_ipv4_cidr_block       = (known after apply)
            + cluster_secondary_range_name  = (known after apply)
            + create_subnetwork             = (known after apply)
            + node_ipv4_cidr_block          = (known after apply)
            + services_ipv4_cidr_block      = (known after apply)
            + services_secondary_range_name = (known after apply)
            + subnetwork_name               = (known after apply)
            + use_ip_aliases                = (known after apply)
            }

        + master_auth {
            + client_certificate     = (known after apply)
            + client_key             = (sensitive value)
            + cluster_ca_certificate = (known after apply)
            + password               = (sensitive value)
            + username               = "admin"

            + client_certificate_config {
                + issue_client_certificate = false
                }
            }

        + master_authorized_networks_config {
            + cidr_blocks {
                + cidr_block   = "0.0.0.0/0"
                + display_name = "allow-all"
                }
            }

        + network_policy {
            + enabled  = (known after apply)
            + provider = (known after apply)
            }

        + node_config {
            + disk_size_gb      = (known after apply)
            + disk_type         = (known after apply)
            + guest_accelerator = (known after apply)
            + image_type        = (known after apply)
            + labels            = (known after apply)
            + local_ssd_count   = (known after apply)
            + machine_type      = (known after apply)
            + metadata          = (known after apply)
            + min_cpu_platform  = (known after apply)
            + oauth_scopes      = (known after apply)
            + preemptible       = (known after apply)
            + service_account   = (known after apply)
            + tags              = (known after apply)
            + taint             = (known after apply)

            + sandbox_config {
                + sandbox_type = (known after apply)
                }

            + shielded_instance_config {
                + enable_integrity_monitoring = (known after apply)
                + enable_secure_boot          = (known after apply)
                }

            + workload_metadata_config {
                + node_metadata = (known after apply)
                }
            }

        + node_pool {
            + initial_node_count  = (known after apply)
            + instance_group_urls = (known after apply)
            + max_pods_per_node   = (known after apply)
            + name                = (known after apply)
            + name_prefix         = (known after apply)
            + node_count          = (known after apply)
            + version             = (known after apply)

            + autoscaling {
                + max_node_count = (known after apply)
                + min_node_count = (known after apply)
                }

            + management {
                + auto_repair  = (known after apply)
                + auto_upgrade = (known after apply)
                }

            + node_config {
                + disk_size_gb      = (known after apply)
                + disk_type         = (known after apply)
                + guest_accelerator = (known after apply)
                + image_type        = (known after apply)
                + labels            = (known after apply)
                + local_ssd_count   = (known after apply)
                + machine_type      = (known after apply)
                + metadata          = (known after apply)
                + min_cpu_platform  = (known after apply)
                + oauth_scopes      = (known after apply)
                + preemptible       = (known after apply)
                + service_account   = (known after apply)
                + tags              = (known after apply)
                + taint             = (known after apply)

                + sandbox_config {
                    + sandbox_type = (known after apply)
                    }

                + shielded_instance_config {
                    + enable_integrity_monitoring = (known after apply)
                    + enable_secure_boot          = (known after apply)
                    }

                + workload_metadata_config {
                    + node_metadata = (known after apply)
                    }
                }
            }

        + private_cluster_config {
            + enable_private_nodes   = true
            + master_ipv4_cidr_block = "172.16.0.0/28"
            + private_endpoint       = (known after apply)
            + public_endpoint        = (known after apply)
            }
        }

    # module.cluster.google_container_node_pool.node_pool will be created
    + resource "google_container_node_pool" "node_pool" {
        + cluster             = "default-cluster"
        + id                  = (known after apply)
        + initial_node_count  = 1
        + instance_group_urls = (known after apply)
        + location            = (known after apply)
        + max_pods_per_node   = (known after apply)
        + name                = "default-node-pool"
        + name_prefix         = (known after apply)
        + node_count          = (known after apply)
        + project             = (known after apply)
        + version             = "1.14.7-gke.10"

        + autoscaling {
            + max_node_count = 2
            + min_node_count = 1
            }

        + management {
            + auto_repair  = true
            + auto_upgrade = false
            }

        + node_config {
            + disk_size_gb      = (known after apply)
            + disk_type         = (known after apply)
            + guest_accelerator = (known after apply)
            + image_type        = (known after apply)
            + labels            = {
                + "workspace" = "default"
                }
            + local_ssd_count   = (known after apply)
            + machine_type      = "n1-highcpu-8"
            + metadata          = {
                + "disable-legacy-endpoints" = "true"
                }
            + min_cpu_platform  = "Intel Haswell"
            + oauth_scopes      = [
                + "https://www.googleapis.com/auth/compute",
                + "https://www.googleapis.com/auth/devstorage.read_only",
                + "https://www.googleapis.com/auth/logging.write",
                + "https://www.googleapis.com/auth/monitoring",
                ]
            + preemptible       = false
            + service_account   = (known after apply)
            + taint             = (known after apply)

            + shielded_instance_config {
                + enable_integrity_monitoring = (known after apply)
                + enable_secure_boot          = (known after apply)
                }
            }
        }

    # module.cluster.random_string.cluster_password will be created
    + resource "random_string" "cluster_password" {
        + id          = (known after apply)
        + length      = 50
        + lower       = true
        + min_lower   = 0
        + min_numeric = 0
        + min_special = 0
        + min_upper   = 0
        + number      = true
        + result      = (known after apply)
        + special     = true
        + upper       = true
        }

    # module.kubernetes.kubernetes_storage_class.ssd will be created
    + resource "kubernetes_storage_class" "ssd" {
        + allow_volume_expansion = true
        + id                     = (known after apply)
        + parameters             = {
            + "type" = "pd-ssd"
            }
        + reclaim_policy         = "Delete"
        + storage_provisioner    = "kubernetes.io/gce-pd"
        + volume_binding_mode    = "Immediate"

        + metadata {
            + generation       = (known after apply)
            + name             = "ssd"
            + resource_version = (known after apply)
            + self_link        = (known after apply)
            + uid              = (known after apply)
            }
        }

    Plan: 10 to add, 0 to change, 0 to destroy.

    Do you want to perform these actions?
    Terraform will perform the actions described above.
    Only 'yes' will be accepted to approve.

    Enter a value: yes
      
      ```
      
  </p>
  </details>
  
5. `➜ terraform plan -destroy -out=destroy.tf-plan`

    <details><summary>(output)</summary>
    <p>
      
      ```              
    Refreshing Terraform state in-memory prior to plan...
    The refreshed state will be used to calculate this plan, but will not be
    persisted to local or remote state storage.

    module.cluster.random_string.cluster_password: Refreshing state... [id=YJww(=l+yo)-F0BW-(cF{I(-(##MmU8N*U3$zk_f_HCA01}G3?]
    module.cluster.google_compute_global_address.external-ip: Refreshing state... [id=projects/env0project/global/addresses/default-backend-ip]
    module.cluster.google_compute_network.network: Refreshing state... [id=projects/env0project/global/networks/default-vpc]
    module.cluster.data.google_container_engine_versions.valid_gke_versions: Refreshing state...
    module.cluster.google_compute_address.gke-outgoing-address[1]: Refreshing state... [id=projects/env0project/regions/us-east1/addresses/default-gke-outgoing-nat-address-1]
    module.cluster.google_compute_address.gke-outgoing-address[0]: Refreshing state... [id=projects/env0project/regions/us-east1/addresses/default-gke-outgoing-nat-address-0]
    module.cluster.google_compute_router.gke-outgoing-router: Refreshing state... [id=projects/env0project/regions/us-east1/routers/default-gke-outgoing-router]
    module.cluster.google_container_cluster.cluster: Refreshing state... [id=projects/env0project/locations/us-east1-b/clusters/default-cluster]
    module.cluster.google_compute_router_nat.gke-outgoing-nat: Refreshing state... [id=env0project/us-east1/default-gke-outgoing-router/default-gke-outgoing-nat]
    module.cluster.google_container_node_pool.node_pool: Refreshing state... [id=projects/env0project/locations/us-east1-b/clusters/default-cluster/nodePools/default-node-pool]
    module.kubernetes.kubernetes_storage_class.ssd: Refreshing state... [id=ssd]

    ------------------------------------------------------------------------

    An execution plan has been generated and is shown below.
    Resource actions are indicated with the following symbols:
    - destroy

    Terraform will perform the following actions:

    # module.cluster.google_compute_address.gke-outgoing-address[0] will be destroyed
    - resource "google_compute_address" "gke-outgoing-address" {
        - address            = "35.231.97.206" -> null
        - address_type       = "EXTERNAL" -> null
        - creation_timestamp = "2020-01-16T08:11:18.565-08:00" -> null
        - id                 = "projects/env0project/regions/us-east1/addresses/default-gke-outgoing-nat-address-0" -> null
        - name               = "default-gke-outgoing-nat-address-0" -> null
        - network_tier       = "PREMIUM" -> null
        - project            = "env0project" -> null
        - region             = "us-east1" -> null
        - self_link          = "https://www.googleapis.com/compute/v1/projects/env0project/regions/us-east1/addresses/default-gke-outgoing-nat-address-0" -> null
        - users              = [
            - "https://www.googleapis.com/compute/v1/projects/env0project/regions/us-east1/routers/default-gke-outgoing-router",
            ] -> null
        }

    # module.cluster.google_compute_address.gke-outgoing-address[1] will be destroyed
    - resource "google_compute_address" "gke-outgoing-address" {
        - address            = "35.237.142.252" -> null
        - address_type       = "EXTERNAL" -> null
        - creation_timestamp = "2020-01-16T08:11:18.685-08:00" -> null
        - id                 = "projects/env0project/regions/us-east1/addresses/default-gke-outgoing-nat-address-1" -> null
        - name               = "default-gke-outgoing-nat-address-1" -> null
        - network_tier       = "PREMIUM" -> null
        - project            = "env0project" -> null
        - region             = "us-east1" -> null
        - self_link          = "https://www.googleapis.com/compute/v1/projects/env0project/regions/us-east1/addresses/default-gke-outgoing-nat-address-1" -> null
        - users              = [
            - "https://www.googleapis.com/compute/v1/projects/env0project/regions/us-east1/routers/default-gke-outgoing-router",
            ] -> null
        }

    # module.cluster.google_compute_global_address.external-ip will be destroyed
    - resource "google_compute_global_address" "external-ip" {
        - address            = "34.107.146.15" -> null
        - address_type       = "EXTERNAL" -> null
        - creation_timestamp = "2020-01-16T08:11:18.515-08:00" -> null
        - id                 = "projects/env0project/global/addresses/default-backend-ip" -> null
        - name               = "default-backend-ip" -> null
        - prefix_length      = 0 -> null
        - project            = "env0project" -> null
        - self_link          = "https://www.googleapis.com/compute/v1/projects/env0project/global/addresses/default-backend-ip" -> null
        }

    # module.cluster.google_compute_network.network will be destroyed
    - resource "google_compute_network" "network" {
        - auto_create_subnetworks         = true -> null
        - delete_default_routes_on_create = false -> null
        - id                              = "projects/env0project/global/networks/default-vpc" -> null
        - name                            = "default-vpc" -> null
        - project                         = "env0project" -> null
        - routing_mode                    = "REGIONAL" -> null
        - self_link                       = "https://www.googleapis.com/compute/v1/projects/env0project/global/networks/default-vpc" -> null
        }

    # module.cluster.google_compute_router.gke-outgoing-router will be destroyed
    - resource "google_compute_router" "gke-outgoing-router" {
        - creation_timestamp = "2020-01-16T08:12:17.665-08:00" -> null
        - id                 = "projects/env0project/regions/us-east1/routers/default-gke-outgoing-router" -> null
        - name               = "default-gke-outgoing-router" -> null
        - network            = "https://www.googleapis.com/compute/v1/projects/env0project/global/networks/default-vpc" -> null
        - project            = "env0project" -> null
        - region             = "us-east1" -> null
        - self_link          = "https://www.googleapis.com/compute/v1/projects/env0project/regions/us-east1/routers/default-gke-outgoing-router" -> null
        }

    # module.cluster.google_compute_router_nat.gke-outgoing-nat will be destroyed
    - resource "google_compute_router_nat" "gke-outgoing-nat" {
        - icmp_idle_timeout_sec              = 30 -> null
        - id                                 = "env0project/us-east1/default-gke-outgoing-router/default-gke-outgoing-nat" -> null
        - min_ports_per_vm                   = 16384 -> null
        - name                               = "default-gke-outgoing-nat" -> null
        - nat_ip_allocate_option             = "MANUAL_ONLY" -> null
        - nat_ips                            = [
            - "https://www.googleapis.com/compute/v1/projects/env0project/regions/us-east1/addresses/default-gke-outgoing-nat-address-0",
            - "https://www.googleapis.com/compute/v1/projects/env0project/regions/us-east1/addresses/default-gke-outgoing-nat-address-1",
            ] -> null
        - project                            = "env0project" -> null
        - region                             = "us-east1" -> null
        - router                             = "default-gke-outgoing-router" -> null
        - source_subnetwork_ip_ranges_to_nat = "LIST_OF_SUBNETWORKS" -> null
        - tcp_established_idle_timeout_sec   = 1200 -> null
        - tcp_transitory_idle_timeout_sec    = 30 -> null
        - udp_idle_timeout_sec               = 30 -> null

        - log_config {
            - enable = true -> null
            - filter = "ALL" -> null
            }

        - subnetwork {
            - name                     = "https://www.googleapis.com/compute/v1/projects/env0project/regions/us-east1/subnetworks/default-vpc" -> null
            - secondary_ip_range_names = [] -> null
            - source_ip_ranges_to_nat  = [
                - "ALL_IP_RANGES",
                ] -> null
            }
        }

    # module.cluster.google_container_cluster.cluster will be destroyed
    - resource "google_container_cluster" "cluster" {
        - cluster_ipv4_cidr         = "10.8.0.0/14" -> null
        - default_max_pods_per_node = 110 -> null
        - enable_kubernetes_alpha   = false -> null
        - enable_legacy_abac        = false -> null
        - endpoint                  = "104.196.137.78" -> null
        - id                        = "projects/env0project/locations/us-east1-b/clusters/default-cluster" -> null
        - initial_node_count        = 1 -> null
        - instance_group_urls       = [
            - "https://www.googleapis.com/compute/v1/projects/env0project/zones/us-east1-b/instanceGroups/gke-default-cluster-default-node-pool-c0a170c4-grp",
            ] -> null
        - location                  = "us-east1-b" -> null
        - logging_service           = "logging.googleapis.com/kubernetes" -> null
        - master_version            = "1.14.10-gke.0" -> null
        - min_master_version        = "1.14.10-gke.0" -> null
        - monitoring_service        = "monitoring.googleapis.com/kubernetes" -> null
        - name                      = "default-cluster" -> null
        - network                   = "projects/env0project/global/networks/default-vpc" -> null
        - node_locations            = [] -> null
        - node_version              = "1.14.7-gke.10" -> null
        - project                   = "env0project" -> null
        - remove_default_node_pool  = true -> null
        - resource_labels           = {
            - "workspace" = "default"
            } -> null
        - services_ipv4_cidr        = "10.72.0.0/20" -> null
        - subnetwork                = "projects/env0project/regions/us-east1/subnetworks/default-vpc" -> null

        - addons_config {

            - network_policy_config {
                - disabled = true -> null
                }
            }

        - cluster_autoscaling {
            - enabled = false -> null
            }

        - ip_allocation_policy {
            - cluster_ipv4_cidr_block       = "10.8.0.0/14" -> null
            - cluster_secondary_range_name  = "gke-default-cluster-pods-baaf834f" -> null
            - create_subnetwork             = false -> null
            - services_ipv4_cidr_block      = "10.72.0.0/20" -> null
            - services_secondary_range_name = "gke-default-cluster-services-baaf834f" -> null
            - use_ip_aliases                = false -> null
            }

        - master_auth {
            - cluster_ca_certificate = "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURERENDQWZTZ0F3SUJBZ0lSQUpNM1cxNkRpUExKMGZrdXVocUQzQ1l3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa01qSTNZV0prTlRJdFlUWXpaaTAwWW1FeExUa3dZemd0TnpBeE1qZzNObUkwWkRNdwpNQjRYRFRJd01ERXhOakUxTVRJeE9Gb1hEVEkxTURFeE5ERTJNVEl4T0Zvd0x6RXRNQ3NHQTFVRUF4TWtNakkzCllXSmtOVEl0WVRZelppMDBZbUV4TFRrd1l6Z3ROekF4TWpnM05tSTBaRE13TUlJQklqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBeW9wbFQ0dmFpV1NuQXhBRng1NlZ5WXRoTlIvUVZsNVRhNU9sNWdtRQovQmhoRXRuNm1MOXhsMFcxaGJaUlNyK1grZnRzR2FUQmNwRk9iWHNvVmk0TDJJY2hwUStyYVdoZXF1dmpTNS9FCkN5bGU2Qmk2czZ1QXVoeU9wcFByaVNXYlBYa1NDTEx0VHc4aTdMZGZtMHprVnU2djErdGRmdkRPbFNIVVFsVGsKKzNXbHovNmsrcEluaUdNTXFmbFZJUHR3QXJhejRNUGhjcTludUpKMGtsSHo5UlNmMU51TXJYUFhLalo2LzRwNwpuSkNHR3ZydDJ6STRDYWRJQjhCU2I3ZTNsbVNOMU12WEcyQ3M2RUQ3SG55MW1JVHcvTDFSRCtSVDE2S1NrZXo2ClRCQ0VIdjdLekIzNG1sbTRmcUprSVNQbTVyZGZMaS83cDNFd3ZRaVlaLzZkQXdJREFRQUJveU13SVRBT0JnTlYKSFE4QkFmOEVCQU1DQWdRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQQpIVW9Qa0NlSlRQcDNXeDJVcGFqU3h5RDFhMk03aXNIVTJPWmVtaDU5M1hTekJOeFVHSEE5MHlSd0kvRE5HTmVMCm1rdlJLb2xRc3p1UkdFR1JmeWkwdWlXYjlmYURTNFlxY3NZbGxJZ3ZOMytpb28rblE0R0FVaXJOYUVxWTZJLzkKcWlQV2J0dVNLQVl1b2Eva0JqSDA4djNUNXM0NHh4SkM2dWhlTzNsRzFZSk9qaVRzM2JwNnVOUllHME0xSktSMQo0MitQcksxOURNVGpidlI0eWI3bklxdkhpQ2xySnF6VUF3V1l3RlNpOUNtNS9VSWxuY0xHeUxtTkttUkVDY1dDCmN6TjRoNTBaTnlneUFiazVuaFpKaGcyRmRWeDdSdksrZ1M5ajQ2U1Q3VjlabjVmMXZOeDVZMkZIVFhnSys3NXoKMDF1VmNlNy9RdkdoU1hmUUlNbS9pZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K" -> null
            - password               = (sensitive value)
            - username               = "admin" -> null

            - client_certificate_config {
                - issue_client_certificate = false -> null
                }
            }

        - master_authorized_networks_config {
            - cidr_blocks {
                - cidr_block   = "0.0.0.0/0" -> null
                - display_name = "allow-all" -> null
                }
            }

        - network_policy {
            - enabled  = false -> null
            - provider = "PROVIDER_UNSPECIFIED" -> null
            }

        - node_config {
            - disk_size_gb      = 100 -> null
            - disk_type         = "pd-standard" -> null
            - guest_accelerator = [] -> null
            - image_type        = "COS" -> null
            - labels            = {
                - "workspace" = "default"
                } -> null
            - local_ssd_count   = 0 -> null
            - machine_type      = "n1-highcpu-8" -> null
            - metadata          = {
                - "disable-legacy-endpoints" = "true"
                } -> null
            - min_cpu_platform  = "Intel Haswell" -> null
            - oauth_scopes      = [
                - "https://www.googleapis.com/auth/compute",
                - "https://www.googleapis.com/auth/devstorage.read_only",
                - "https://www.googleapis.com/auth/logging.write",
                - "https://www.googleapis.com/auth/monitoring",
                ] -> null
            - preemptible       = false -> null
            - service_account   = "default" -> null
            - tags              = [] -> null
            - taint             = [] -> null

            - shielded_instance_config {
                - enable_integrity_monitoring = true -> null
                - enable_secure_boot          = false -> null
                }
            }

        - node_pool {
            - initial_node_count  = 1 -> null
            - instance_group_urls = [
                - "https://www.googleapis.com/compute/v1/projects/env0project/zones/us-east1-b/instanceGroupManagers/gke-default-cluster-default-node-pool-c0a170c4-grp",
                ] -> null
            - max_pods_per_node   = 110 -> null
            - name                = "default-node-pool" -> null
            - node_count          = 1 -> null
            - version             = "1.14.7-gke.10" -> null

            - autoscaling {
                - max_node_count = 2 -> null
                - min_node_count = 1 -> null
                }

            - management {
                - auto_repair  = true -> null
                - auto_upgrade = false -> null
                }

            - node_config {
                - disk_size_gb      = 100 -> null
                - disk_type         = "pd-standard" -> null
                - guest_accelerator = [] -> null
                - image_type        = "COS" -> null
                - labels            = {
                    - "workspace" = "default"
                    } -> null
                - local_ssd_count   = 0 -> null
                - machine_type      = "n1-highcpu-8" -> null
                - metadata          = {
                    - "disable-legacy-endpoints" = "true"
                    } -> null
                - min_cpu_platform  = "Intel Haswell" -> null
                - oauth_scopes      = [
                    - "https://www.googleapis.com/auth/compute",
                    - "https://www.googleapis.com/auth/devstorage.read_only",
                    - "https://www.googleapis.com/auth/logging.write",
                    - "https://www.googleapis.com/auth/monitoring",
                    ] -> null
                - preemptible       = false -> null
                - service_account   = "default" -> null
                - tags              = [] -> null
                - taint             = [] -> null

                - shielded_instance_config {
                    - enable_integrity_monitoring = true -> null
                    - enable_secure_boot          = false -> null
                    }
                }
            }

        - private_cluster_config {
            - enable_private_endpoint = false -> null
            - enable_private_nodes    = true -> null
            - master_ipv4_cidr_block  = "172.16.0.0/28" -> null
            - private_endpoint        = "172.16.0.2" -> null
            - public_endpoint         = "104.196.137.78" -> null
            }
        }

    # module.cluster.google_container_node_pool.node_pool will be destroyed
    - resource "google_container_node_pool" "node_pool" {
        - cluster             = "default-cluster" -> null
        - id                  = "projects/env0project/locations/us-east1-b/clusters/default-cluster/nodePools/default-node-pool" -> null
        - initial_node_count  = 1 -> null
        - instance_group_urls = [
            - "https://www.googleapis.com/compute/v1/projects/env0project/zones/us-east1-b/instanceGroupManagers/gke-default-cluster-default-node-pool-c0a170c4-grp",
            ] -> null
        - location            = "us-east1-b" -> null
        - max_pods_per_node   = 110 -> null
        - name                = "default-node-pool" -> null
        - node_count          = 1 -> null
        - project             = "env0project" -> null
        - version             = "1.14.7-gke.10" -> null

        - autoscaling {
            - max_node_count = 2 -> null
            - min_node_count = 1 -> null
            }

        - management {
            - auto_repair  = true -> null
            - auto_upgrade = false -> null
            }

        - node_config {
            - disk_size_gb      = 100 -> null
            - disk_type         = "pd-standard" -> null
            - guest_accelerator = [] -> null
            - image_type        = "COS" -> null
            - labels            = {
                - "workspace" = "default"
                } -> null
            - local_ssd_count   = 0 -> null
            - machine_type      = "n1-highcpu-8" -> null
            - metadata          = {
                - "disable-legacy-endpoints" = "true"
                } -> null
            - min_cpu_platform  = "Intel Haswell" -> null
            - oauth_scopes      = [
                - "https://www.googleapis.com/auth/compute",
                - "https://www.googleapis.com/auth/devstorage.read_only",
                - "https://www.googleapis.com/auth/logging.write",
                - "https://www.googleapis.com/auth/monitoring",
                ] -> null
            - preemptible       = false -> null
            - service_account   = "default" -> null
            - tags              = [] -> null
            - taint             = [] -> null

            - shielded_instance_config {
                - enable_integrity_monitoring = true -> null
                - enable_secure_boot          = false -> null
                }
            }
        }

    # module.cluster.random_string.cluster_password will be destroyed
    - resource "random_string" "cluster_password" {
        - id          = "YJww(=l+yo)-F0BW-(cF{I(-(##MmU8N*U3$zk_f_HCA01}G3?" -> null
        - length      = 50 -> null
        - lower       = true -> null
        - min_lower   = 0 -> null
        - min_numeric = 0 -> null
        - min_special = 0 -> null
        - min_upper   = 0 -> null
        - number      = true -> null
        - result      = "YJww(=l+yo)-F0BW-(cF{I(-(##MmU8N*U3$zk_f_HCA01}G3?" -> null
        - special     = true -> null
        - upper       = true -> null
        }

    # module.kubernetes.kubernetes_storage_class.ssd will be destroyed
    - resource "kubernetes_storage_class" "ssd" {
        - allow_volume_expansion = true -> null
        - id                     = "ssd" -> null
        - parameters             = {
            - "type" = "pd-ssd"
            } -> null
        - reclaim_policy         = "Delete" -> null
        - storage_provisioner    = "kubernetes.io/gce-pd" -> null
        - volume_binding_mode    = "Immediate" -> null

        - metadata {
            - annotations      = {} -> null
            - generation       = 0 -> null
            - labels           = {} -> null
            - name             = "ssd" -> null
            - resource_version = "1353" -> null
            - self_link        = "/apis/storage.k8s.io/v1/storageclasses/ssd" -> null
            - uid              = "1284f3ae-387c-11ea-8da6-4201ac100003" -> null
            }
        }

    Plan: 0 to add, 0 to change, 10 to destroy.

    ------------------------------------------------------------------------

    This plan was saved to: destroy.tf-plan

    To perform exactly these actions, run the following command to apply:
        terraform apply "destroy.tf-plan"
      
      ```
      
  </p>
  </details>
  
6. Trying to apply the plan will fail, claiming there are cycles which aren't clear to me:  
    `➜ terraform apply destroy.tf-plan`
    <details><summary>(output)</summary>
    <p>
      
      ```              
    Error: Cycle: module.cluster.output.host, module.cluster.output.password, module.cluster.output.cluster_ca_certificate, provider.kubernetes, module.kubernetes.kubernetes_storage_class.ssd (destroy), module.cluster.google_container_cluster.cluster (destroy)
      
      ```
      
  </p>
  </details>

  
7. What's worse, trying to destroy rather than applying the destruction plan works:  
    `➜ terraform destroy`
    <details><summary>(output)</summary>
    <p>
      
      ```              
    module.cluster.random_string.cluster_password: Refreshing state... [id=BhsaSh(H#!bnB}-CX6bifs($CIRaEn{Ml]3O+W[P{@c*PVitX2]
    module.cluster.google_compute_network.network: Refreshing state... [id=projects/env0project/global/networks/default-vpc]
    module.cluster.google_compute_address.gke-outgoing-address[0]: Refreshing state... [id=projects/env0project/regions/us-east1/addresses/default-gke-outgoing-nat-address-0]
    module.cluster.google_compute_address.gke-outgoing-address[1]: Refreshing state... [id=projects/env0project/regions/us-east1/addresses/default-gke-outgoing-nat-address-1]
    module.cluster.data.google_container_engine_versions.valid_gke_versions: Refreshing state...
    module.cluster.google_compute_global_address.external-ip: Refreshing state... [id=projects/env0project/global/addresses/default-backend-ip]
    module.cluster.google_compute_router.gke-outgoing-router: Refreshing state... [id=projects/env0project/regions/us-east1/routers/default-gke-outgoing-router]
    module.cluster.google_container_cluster.cluster: Refreshing state... [id=projects/env0project/locations/us-east1-b/clusters/default-cluster]
    module.cluster.google_compute_router_nat.gke-outgoing-nat: Refreshing state... [id=env0project/us-east1/default-gke-outgoing-router/default-gke-outgoing-nat]
    module.cluster.google_container_node_pool.node_pool: Refreshing state... [id=projects/env0project/locations/us-east1-b/clusters/default-cluster/nodePools/default-node-pool]
    module.kubernetes.kubernetes_storage_class.ssd: Refreshing state... [id=ssd]

    An execution plan has been generated and is shown below.
    Resource actions are indicated with the following symbols:
    - destroy

    Terraform will perform the following actions:

    # module.cluster.google_compute_address.gke-outgoing-address[0] will be destroyed
    - resource "google_compute_address" "gke-outgoing-address" {
        - address            = "35.231.97.206" -> null
        - address_type       = "EXTERNAL" -> null
        - creation_timestamp = "2020-01-16T06:43:11.220-08:00" -> null
        - id                 = "projects/env0project/regions/us-east1/addresses/default-gke-outgoing-nat-address-0" -> null
        - name               = "default-gke-outgoing-nat-address-0" -> null
        - network_tier       = "PREMIUM" -> null
        - project            = "env0project" -> null
        - region             = "us-east1" -> null
        - self_link          = "https://www.googleapis.com/compute/v1/projects/env0project/regions/us-east1/addresses/default-gke-outgoing-nat-address-0" -> null
        - users              = [
            - "https://www.googleapis.com/compute/v1/projects/env0project/regions/us-east1/routers/default-gke-outgoing-router",
            ] -> null
        }

    # module.cluster.google_compute_address.gke-outgoing-address[1] will be destroyed
    - resource "google_compute_address" "gke-outgoing-address" {
        - address            = "35.237.142.252" -> null
        - address_type       = "EXTERNAL" -> null
        - creation_timestamp = "2020-01-16T06:43:11.339-08:00" -> null
        - id                 = "projects/env0project/regions/us-east1/addresses/default-gke-outgoing-nat-address-1" -> null
        - name               = "default-gke-outgoing-nat-address-1" -> null
        - network_tier       = "PREMIUM" -> null
        - project            = "env0project" -> null
        - region             = "us-east1" -> null
        - self_link          = "https://www.googleapis.com/compute/v1/projects/env0project/regions/us-east1/addresses/default-gke-outgoing-nat-address-1" -> null
        - users              = [
            - "https://www.googleapis.com/compute/v1/projects/env0project/regions/us-east1/routers/default-gke-outgoing-router",
            ] -> null
        }

    # module.cluster.google_compute_global_address.external-ip will be destroyed
    - resource "google_compute_global_address" "external-ip" {
        - address            = "34.107.146.15" -> null
        - address_type       = "EXTERNAL" -> null
        - creation_timestamp = "2020-01-16T06:43:11.081-08:00" -> null
        - id                 = "projects/env0project/global/addresses/default-backend-ip" -> null
        - name               = "default-backend-ip" -> null
        - prefix_length      = 0 -> null
        - project            = "env0project" -> null
        - self_link          = "https://www.googleapis.com/compute/v1/projects/env0project/global/addresses/default-backend-ip" -> null
        }

    # module.cluster.google_compute_network.network will be destroyed
    - resource "google_compute_network" "network" {
        - auto_create_subnetworks         = true -> null
        - delete_default_routes_on_create = false -> null
        - id                              = "projects/env0project/global/networks/default-vpc" -> null
        - name                            = "default-vpc" -> null
        - project                         = "env0project" -> null
        - routing_mode                    = "REGIONAL" -> null
        - self_link                       = "https://www.googleapis.com/compute/v1/projects/env0project/global/networks/default-vpc" -> null
        }

    # module.cluster.google_compute_router.gke-outgoing-router will be destroyed
    - resource "google_compute_router" "gke-outgoing-router" {
        - creation_timestamp = "2020-01-16T06:43:59.995-08:00" -> null
        - id                 = "projects/env0project/regions/us-east1/routers/default-gke-outgoing-router" -> null
        - name               = "default-gke-outgoing-router" -> null
        - network            = "https://www.googleapis.com/compute/v1/projects/env0project/global/networks/default-vpc" -> null
        - project            = "env0project" -> null
        - region             = "us-east1" -> null
        - self_link          = "https://www.googleapis.com/compute/v1/projects/env0project/regions/us-east1/routers/default-gke-outgoing-router" -> null
        }

    # module.cluster.google_compute_router_nat.gke-outgoing-nat will be destroyed
    - resource "google_compute_router_nat" "gke-outgoing-nat" {
        - icmp_idle_timeout_sec              = 30 -> null
        - id                                 = "env0project/us-east1/default-gke-outgoing-router/default-gke-outgoing-nat" -> null
        - min_ports_per_vm                   = 16384 -> null
        - name                               = "default-gke-outgoing-nat" -> null
        - nat_ip_allocate_option             = "MANUAL_ONLY" -> null
        - nat_ips                            = [
            - "https://www.googleapis.com/compute/v1/projects/env0project/regions/us-east1/addresses/default-gke-outgoing-nat-address-0",
            - "https://www.googleapis.com/compute/v1/projects/env0project/regions/us-east1/addresses/default-gke-outgoing-nat-address-1",
            ] -> null
        - project                            = "env0project" -> null
        - region                             = "us-east1" -> null
        - router                             = "default-gke-outgoing-router" -> null
        - source_subnetwork_ip_ranges_to_nat = "LIST_OF_SUBNETWORKS" -> null
        - tcp_established_idle_timeout_sec   = 1200 -> null
        - tcp_transitory_idle_timeout_sec    = 30 -> null
        - udp_idle_timeout_sec               = 30 -> null

        - log_config {
            - enable = true -> null
            - filter = "ALL" -> null
            }

        - subnetwork {
            - name                     = "https://www.googleapis.com/compute/v1/projects/env0project/regions/us-east1/subnetworks/default-vpc" -> null
            - secondary_ip_range_names = [] -> null
            - source_ip_ranges_to_nat  = [
                - "ALL_IP_RANGES",
                ] -> null
            }
        }

    # module.cluster.google_container_cluster.cluster will be destroyed
    - resource "google_container_cluster" "cluster" {
        - cluster_ipv4_cidr         = "10.8.0.0/14" -> null
        - default_max_pods_per_node = 110 -> null
        - enable_kubernetes_alpha   = false -> null
        - enable_legacy_abac        = false -> null
        - endpoint                  = "35.196.124.50" -> null
        - id                        = "projects/env0project/locations/us-east1-b/clusters/default-cluster" -> null
        - initial_node_count        = 1 -> null
        - instance_group_urls       = [
            - "https://www.googleapis.com/compute/v1/projects/env0project/zones/us-east1-b/instanceGroups/gke-default-cluster-default-node-pool-67368eb2-grp",
            ] -> null
        - location                  = "us-east1-b" -> null
        - logging_service           = "logging.googleapis.com/kubernetes" -> null
        - master_version            = "1.14.10-gke.0" -> null
        - min_master_version        = "1.14.10-gke.0" -> null
        - monitoring_service        = "monitoring.googleapis.com/kubernetes" -> null
        - name                      = "default-cluster" -> null
        - network                   = "projects/env0project/global/networks/default-vpc" -> null
        - node_locations            = [] -> null
        - node_version              = "1.14.7-gke.10" -> null
        - project                   = "env0project" -> null
        - remove_default_node_pool  = true -> null
        - resource_labels           = {
            - "workspace" = "default"
            } -> null
        - services_ipv4_cidr        = "10.72.0.0/20" -> null
        - subnetwork                = "projects/env0project/regions/us-east1/subnetworks/default-vpc" -> null

        - addons_config {

            - network_policy_config {
                - disabled = true -> null
                }
            }

        - cluster_autoscaling {
            - enabled = false -> null
            }

        - ip_allocation_policy {
            - cluster_ipv4_cidr_block       = "10.8.0.0/14" -> null
            - cluster_secondary_range_name  = "gke-default-cluster-pods-d72e3347" -> null
            - create_subnetwork             = false -> null
            - services_ipv4_cidr_block      = "10.72.0.0/20" -> null
            - services_secondary_range_name = "gke-default-cluster-services-d72e3347" -> null
            - use_ip_aliases                = false -> null
            }

        - master_auth {
            - cluster_ca_certificate = "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDekNDQWZPZ0F3SUJBZ0lRYmlVbUh3WGdsNTJ3ZEsvUjc3cDVVakFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlRek5tSmpNR1k1T0MwMll6SmxMVFExWkRVdFlqSTRNeTFsWkRjMFpqRTRaV1psTnpjdwpIaGNOTWpBd01URTJNVE0wTXpVNVdoY05NalV3TVRFME1UUTBNelU1V2pBdk1TMHdLd1lEVlFRREV5UXpObUpqCk1HWTVPQzAyWXpKbExUUTFaRFV0WWpJNE15MWxaRGMwWmpFNFpXWmxOemN3Z2dFaU1BMEdDU3FHU0liM0RRRUIKQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNraUpVTlZONmxnNy9HN3Q1R005WjIwd1VzclA0dXc4eGxleWlXTXdhKwpCUFdjWVFKNlVyQW1KeXlWVXZlZVBkZlY5Tk5KMkd2Q0FiUEVucG9KK1cvbGpGcEhyUXBtdnhQVU9Ta1hrNVdXCnZYcTZJblA1aWN5Nkd0VEVPbFdjYkdhdkhuTVZVTnJoVCtya1l6RHNFV1lhcEh5a002eFRzbnZMbFhZekZQVGUKS3hWanArZHVZN3RtQ2NaOXVqbTFRalFKdTdXTzdxTVViaUJXWWtPcTRRUWhoLzJ0NUQzNGxpTjRPZEhsVSszTwpSY1JPM2wyOXprQ0VVT1JwV1NLcTYzMERHM2twbkx5dThiaW4rNVhtUW0wbHo4MDdKRGJSbUFEUXNtMlpvSy8xCmxyS0lwQkVSMVZDTzd3aS9NQW5QWGFsZDB0R0o0MS9HdVBBTDM1Um4zTFJCQWdNQkFBR2pJekFoTUE0R0ExVWQKRHdFQi93UUVBd0lDQkRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCcQpoRTNyTW1SL2NER1YrWUVYeGs3MlY5N0VKdlUyaVVVNFZaVGhVM0J5MVZPVEY4UXdKSldkd09JZE55UklJVStaCm9VMHpocm93L0I2RnI5NG4zc3c5RDlFZld0dkp0WHhVY2JvaWhGLzRqdzJ6YlNleERsMU5HeU5RL0YvaFd4YzcKd1Vzc1JrVzNqbmg0UkpOS0YzTk1FcnhmVjg5MEVkZEFyTWFxTUJXVHFTcVVuMFFNQXB3OG1qNTVWSHhMVC9YSApyMHhETy8yYytXa0FIbk82bi81QWdRN1NwNUloYUxpdmlsdG9yMEprUnVoalNPL2o3ZHR5R2Zqb3hQbDlmamNWCksxQ2gxV3RIU3IxazB4djB1ZzAzUTVoNTUwdCtpNFU1aTJMRFhhYjlZMHdQOC80SEYwVVlldFVYWkNpems3WGcKbS93VnU0SG9idHc3dE16VDdOVnQKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=" -> null
            - password               = (sensitive value)
            - username               = "admin" -> null

            - client_certificate_config {
                - issue_client_certificate = false -> null
                }
            }

        - master_authorized_networks_config {
            - cidr_blocks {
                - cidr_block   = "0.0.0.0/0" -> null
                - display_name = "allow-all" -> null
                }
            }

        - network_policy {
            - enabled  = false -> null
            - provider = "PROVIDER_UNSPECIFIED" -> null
            }

        - node_config {
            - disk_size_gb      = 100 -> null
            - disk_type         = "pd-standard" -> null
            - guest_accelerator = [] -> null
            - image_type        = "COS" -> null
            - labels            = {
                - "workspace" = "default"
                } -> null
            - local_ssd_count   = 0 -> null
            - machine_type      = "n1-highcpu-8" -> null
            - metadata          = {
                - "disable-legacy-endpoints" = "true"
                } -> null
            - min_cpu_platform  = "Intel Haswell" -> null
            - oauth_scopes      = [
                - "https://www.googleapis.com/auth/compute",
                - "https://www.googleapis.com/auth/devstorage.read_only",
                - "https://www.googleapis.com/auth/logging.write",
                - "https://www.googleapis.com/auth/monitoring",
                ] -> null
            - preemptible       = false -> null
            - service_account   = "default" -> null
            - tags              = [] -> null
            - taint             = [] -> null

            - shielded_instance_config {
                - enable_integrity_monitoring = true -> null
                - enable_secure_boot          = false -> null
                }
            }

        - node_pool {
            - initial_node_count  = 1 -> null
            - instance_group_urls = [
                - "https://www.googleapis.com/compute/v1/projects/env0project/zones/us-east1-b/instanceGroupManagers/gke-default-cluster-default-node-pool-67368eb2-grp",
                ] -> null
            - max_pods_per_node   = 110 -> null
            - name                = "default-node-pool" -> null
            - node_count          = 1 -> null
            - version             = "1.14.7-gke.10" -> null

            - autoscaling {
                - max_node_count = 2 -> null
                - min_node_count = 1 -> null
                }

            - management {
                - auto_repair  = true -> null
                - auto_upgrade = false -> null
                }

            - node_config {
                - disk_size_gb      = 100 -> null
                - disk_type         = "pd-standard" -> null
                - guest_accelerator = [] -> null
                - image_type        = "COS" -> null
                - labels            = {
                    - "workspace" = "default"
                    } -> null
                - local_ssd_count   = 0 -> null
                - machine_type      = "n1-highcpu-8" -> null
                - metadata          = {
                    - "disable-legacy-endpoints" = "true"
                    } -> null
                - min_cpu_platform  = "Intel Haswell" -> null
                - oauth_scopes      = [
                    - "https://www.googleapis.com/auth/compute",
                    - "https://www.googleapis.com/auth/devstorage.read_only",
                    - "https://www.googleapis.com/auth/logging.write",
                    - "https://www.googleapis.com/auth/monitoring",
                    ] -> null
                - preemptible       = false -> null
                - service_account   = "default" -> null
                - tags              = [] -> null
                - taint             = [] -> null

                - shielded_instance_config {
                    - enable_integrity_monitoring = true -> null
                    - enable_secure_boot          = false -> null
                    }
                }
            }

        - private_cluster_config {
            - enable_private_endpoint = false -> null
            - enable_private_nodes    = true -> null
            - master_ipv4_cidr_block  = "172.16.0.0/28" -> null
            - private_endpoint        = "172.16.0.2" -> null
            - public_endpoint         = "35.196.124.50" -> null
            }
        }

    # module.cluster.google_container_node_pool.node_pool will be destroyed
    - resource "google_container_node_pool" "node_pool" {
        - cluster             = "default-cluster" -> null
        - id                  = "projects/env0project/locations/us-east1-b/clusters/default-cluster/nodePools/default-node-pool" -> null
        - initial_node_count  = 1 -> null
        - instance_group_urls = [
            - "https://www.googleapis.com/compute/v1/projects/env0project/zones/us-east1-b/instanceGroupManagers/gke-default-cluster-default-node-pool-67368eb2-grp",
            ] -> null
        - location            = "us-east1-b" -> null
        - max_pods_per_node   = 110 -> null
        - name                = "default-node-pool" -> null
        - node_count          = 1 -> null
        - project             = "env0project" -> null
        - version             = "1.14.7-gke.10" -> null

        - autoscaling {
            - max_node_count = 2 -> null
            - min_node_count = 1 -> null
            }

        - management {
            - auto_repair  = true -> null
            - auto_upgrade = false -> null
            }

        - node_config {
            - disk_size_gb      = 100 -> null
            - disk_type         = "pd-standard" -> null
            - guest_accelerator = [] -> null
            - image_type        = "COS" -> null
            - labels            = {
                - "workspace" = "default"
                } -> null
            - local_ssd_count   = 0 -> null
            - machine_type      = "n1-highcpu-8" -> null
            - metadata          = {
                - "disable-legacy-endpoints" = "true"
                } -> null
            - min_cpu_platform  = "Intel Haswell" -> null
            - oauth_scopes      = [
                - "https://www.googleapis.com/auth/compute",
                - "https://www.googleapis.com/auth/devstorage.read_only",
                - "https://www.googleapis.com/auth/logging.write",
                - "https://www.googleapis.com/auth/monitoring",
                ] -> null
            - preemptible       = false -> null
            - service_account   = "default" -> null
            - tags              = [] -> null
            - taint             = [] -> null

            - shielded_instance_config {
                - enable_integrity_monitoring = true -> null
                - enable_secure_boot          = false -> null
                }
            }
        }

    # module.cluster.random_string.cluster_password will be destroyed
    - resource "random_string" "cluster_password" {
        - id          = "BhsaSh(H#!bnB}-CX6bifs($CIRaEn{Ml]3O+W[P{@c*PVitX2" -> null
        - length      = 50 -> null
        - lower       = true -> null
        - min_lower   = 0 -> null
        - min_numeric = 0 -> null
        - min_special = 0 -> null
        - min_upper   = 0 -> null
        - number      = true -> null
        - result      = "BhsaSh(H#!bnB}-CX6bifs($CIRaEn{Ml]3O+W[P{@c*PVitX2" -> null
        - special     = true -> null
        - upper       = true -> null
        }

    # module.kubernetes.kubernetes_storage_class.ssd will be destroyed
    - resource "kubernetes_storage_class" "ssd" {
        - allow_volume_expansion = true -> null
        - id                     = "ssd" -> null
        - parameters             = {
            - "type" = "pd-ssd"
            } -> null
        - reclaim_policy         = "Delete" -> null
        - storage_provisioner    = "kubernetes.io/gce-pd" -> null
        - volume_binding_mode    = "Immediate" -> null

        - metadata {
            - annotations      = {} -> null
            - generation       = 0 -> null
            - labels           = {} -> null
            - name             = "ssd" -> null
            - resource_version = "894" -> null
            - self_link        = "/apis/storage.k8s.io/v1/storageclasses/ssd" -> null
            - uid              = "6cc51038-386f-11ea-9648-4201ac100003" -> null
            }
        }

    Plan: 0 to add, 0 to change, 10 to destroy.

    Do you really want to destroy all resources?
    Terraform will destroy all your managed infrastructure, as shown above.
    There is no undo. Only 'yes' will be accepted to confirm.

    Enter a value: yes

    ...

    Destroy complete! Resources: 10 destroyed.
      
      ```
      
  </p>
  </details>

### LINKED ISSUE #23957: null_resource and templatefile using with deposed elements raise cycle error
### Terraform Version

```
Terraform v0.12.20
```

### Terraform Configuration Files

```hcl
resource "digitalocean_droplet" "test" {
  count  = 5
  image  = 57114112
  name   = "test-${format("%03d", count.index + 1)}"
  region = "ams3"
  private_networking = true
  monitoring = true
  size       = "s-2vcpu-2gb"
  tags       = ["test"]

  lifecycle {
    create_before_destroy = true
  }

  connection {
    host        = self.ipv4_address
    type        = "ssh"
    user        = "developer"
    private_key = file(pathexpand(var.private_key_path))
    certificate = file(pathexpand(var.certificate_key_path))
  }
}

resource "digitalocean_droplet" "haproxy_test" {
  count  = 1
  image  = 57065468
  name   = "haproxy-test-${format("%03d", count.index + 1)}"
  region = "ams3"
  private_networking = true
  monitoring         = true
  size = "s-2vcpu-2gb"
  tags = ["haproxy-test"]

  lifecycle {
    create_before_destroy = true
  }

  connection {
    host        = self.ipv4_address
    type        = "ssh"
    user        = "developer"
    private_key = file(pathexpand(var.private_key_path))
    certificate = file(pathexpand(var.certificate_key_path))
  }
}

resource "null_resource" "haproxy_test_config" {
  count = 1

  triggers = {
    droplets = templatefile("${path.module}/templates/haproxy/test.tpl", {droplets = digitalocean_droplet.test})
    haproxy  = digitalocean_droplet.haproxy_test[count.index].id
  }

  lifecycle {
    create_before_destroy = true
  }

  connection {
    host        = digitalocean_droplet.haproxy_test[count.index].ipv4_address
    user        = "developer"
    private_key = file(pathexpand(var.private_key_path))
    certificate = file(pathexpand(var.certificate_key_path))
  }

  provisioner "file" {
    content     = templatefile("${path.module}/templates/haproxy/test.tpl", {droplets = digitalocean_droplet.test})
    destination = "/tmp/haproxy"
  }

  provisioner "remote-exec" {
    inline = [
      "sudo cp /tmp/haproxy /etc/haproxy/haproxy.cfg",
      "sudo systemctl reload haproxy",
    ]
  }
}
```

**test.tpl**:
```
backend torg
    mode http
    http-check expect status 200
    option httpchk GET /health-check
    balance roundrobin
    %{ for test in droplets ~}
server ${test.name} ${test.ipv4_address_private}:8080 check fall 3 rise 2
    %{ endfor }
```

### Debug Output

https://gist.github.com/okgolove/2a126205e8bf92871c5dbc1cbdccd069

### Expected Behavior

**test** droplet has been destroyed, null_resource has been reprovisioned

### Actual Behavior

```
Error: Cycle: null_resource.haproxy_test_config[0], null_resource.haproxy_test_config[0] (destroy deposed bca85ac3), digitalocean_droplet.test[2] (destroy)
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. Reduce **test's** count to 4
4. `terraform apply`

### PR DESCRIPTION
**Pull request by jbardin**
This PR completes the implementation of resource destruction only using the resource's state (configuration is still required for providers).  By making sure destroy provisioners cannot reference other resources (more info in #23559), there is no need to connect resources to other values during destroy, preventing numerous cycle issues. 

This also completes the implementation of storing the destroy references in the state (more info in #23252). The `NodeAbstractResourceInstance.References` implementation can now be simplified because there will be no more `depends_on` references from the state during destroy. This also means we no longer need to search again for destroy dependencies during apply, since we stored them already, removing an extra graph-building and traversal step.

Finally we greatly simplify the `CBDEdgeTransformer`, because we now know that the resource destroy nodes can only depend on other resource destroy nodes and can easily reverse the required `GraphNodeCreator` edges. 

Closes #14548
Closes #16237
Closes #17944
Closes #18026
Closes #18088
Closes #18356
Closes #21610
Closes #23196
Closes #23365
Closes #23365
Closes #23875
Closes #23957

### CODE REVIEW

File: command/apply_destroy_test.go [hunk 1]
```diff
@@ -195,7 +195,7 @@ func TestApply_destroyTargeted(t *testing.T) {
 				Mode: addrs.ManagedResourceMode,
 				Type: "test_instance",
 				Name: "foo",
-			}.Instance(addrs.NoKey).Absolute(addrs.RootModuleInstance),
+			}.Instance(addrs.IntKey(0)).Absolute(addrs.RootModuleInstance),
```
Comment (pselle) [inline command/apply_destroy_test.go]: Should this change in this test? Seems suspicious.

File: configs/provisioner.go [hunk 2]
```diff
@@ -147,8 +147,8 @@ func onlySelfRefs(body hcl.Body) hcl.Diagnostics {
 
 			if !valid {
 				diags = append(diags, &hcl.Diagnostic{
-					Severity: hcl.DiagWarning,
-					Summary:  "External references from destroy provisioners are deprecated",
+					Severity: hcl.DiagError,
```
Comment (pselle) [inline configs/provisioner.go]: 🚀

File: terraform/node_resource_abstract.go [hunk 3]
```diff
@@ -241,46 +240,6 @@ func (n *NodeAbstractResourceInstance) References() []*addrs.Reference {
 		return n.NodeAbstractResource.References()
 	}
 
-	// FIXME: remove once the deprecated DependsOn values have been removed from state
```
Comment (pselle) [inline terraform/node_resource_abstract.go]: RAD

File: configs/parser_config_test.go [hunk 4]
```diff
@@ -224,3 +224,62 @@ func TestParserLoadConfigFileWarning(t *testing.T) {
 		})
 	}
 }
+
+// TestParseLoadConfigFileError is a test that verifies files from
+// testdata/warning-files produce particular warnings.
```
Comment (apparentlymart) [inline configs/parser_config_test.go]:
```suggestion
// testdata/error-files produce particular errors.
```

File: configs/parser_config_test.go [hunk 5]
```diff
@@ -224,3 +224,62 @@ func TestParserLoadConfigFileWarning(t *testing.T) {
...
+//
+// This test does not verify that reading these files produces the correct
+// file element contents in spite of those warnings. More detailed assertions
```
Comment (apparentlymart) [inline configs/parser_config_test.go]:
```suggestion
// file element contents in spite of those errors. More detailed assertions
```

File: configs/parser_config_test.go [hunk 6]
```diff
@@ -224,3 +224,62 @@ func TestParserLoadConfigFileWarning(t *testing.T) {
...
+		name := info.Name()
+		t.Run(name, func(t *testing.T) {
+			src, err := ioutil.ReadFile(filepath.Join("testdata/error-files", name))
+			if err != nil {
+				t.Fatal(err)
+			}
+
+			// First we'll scan the file to see what warnings are expected.
+			// That's declared inside the files themselves by using the
+			// string "WARNING: " somewhere on each line that is expected
```
Comment (apparentlymart) [inline configs/parser_config_test.go]:
```suggestion
			// string "ERROR: " somewhere on each line that is expected
```

File: terraform/context_apply_test.go [hunk 7]
```diff
@@ -290,35 +290,26 @@ func TestContext2Apply_resourceDependsOnModuleStateOnly(t *testing.T) {
...
-					"aws_instance.child": &ResourceState{
-						Type: "aws_instance",
-						Primary: &InstanceState{
-							ID: "child",
-						},
-						Provider: "provider.aws",
-					},
-				},
-			},
+	state := states.NewState()
```
Comment (apparentlymart) [inline terraform/context_apply_test.go]: Yay for removing uses of `MustShimLegacyState`!

File: terraform/transform_destroy_cbd.go [hunk 8]
```diff
@@ -134,25 +134,16 @@ type CBDEdgeTransformer struct {
 	// obtain schema information from providers and provisioners so we can
 	// properly resolve implicit dependencies.
 	Schemas *Schemas
-
-	// If the operation is a simple destroy, no transformation is done.
-	Destroy bool
```
Comment (apparentlymart) [inline terraform/transform_destroy_cbd.go]: This was the only remaining thing that was different between `terraform plan -destroy` and `terraform destroy`, right? If so, awesome!

File: terraform/graph_builder_apply.go [hunk 9]
```diff
@@ -168,20 +168,10 @@ func (b *ApplyGraphBuilder) Steps() []GraphTransformer {
...
-		// interpolations don't fail during destroy.
 		// Create a destroy node for outputs to remove them from the state.
-		GraphTransformIf(
-			func() bool { return b.Destroy },
-			GraphTransformMulti(
-				&DestroyValueReferenceTransformer{},
-				&DestroyOutputTransformer{},
-			),
-		),
+		&DestroyOutputTransformer{Destroy: b.Destroy},
```
Comment (apparentlymart) [inline terraform/graph_builder_apply.go]: Oh, I guess _this_ is still a difference between `terraform plan -destroy` and `terraform destroy`. _One day...._

**Comment by okgolove** [comment]
When will it be included in release?
