### PR TITLE
core: Add list() interpolation function

### LINKED ISSUE #7460: Allow creating list in interpolations
### Terraform Version

Terraform v0.7.0-rc2 (46a0709bba004d8b6e0eedad411270b3ae135a9e)

### Affected Resource(s)

Interpolations

### Terraform Configuration Files
N/A
### Debug Output
N/A
### Panic Output
N/A
### Expected Behavior

I have some variables that I'd like to pass into a resource.  Sometimes, some of those variables can be empty string, so I'd like to be able to use compact.  However, I don't have those variables in a list format, so cannot use compact.  It would be nice if there was a varag list() for creating the list so that I could pass it into compact.

I can do something like:

    value = "${compact(split(",", format("%s,%s", var.var1, var.var2)))}"

So the capability is there, but would be much nicer if I could do:

    value = "${compact(list(var.var1, var.var2))}"

### Actual Behavior
N/A
### Steps to Reproduce
N/A
### Important Factoids
N/A
### References
N/A

### PR DESCRIPTION
**Pull request by jen20**
The list() interpolation function provides a way to add support for list literals to HIL without having to invent new syntax for it and modify the HIL parser.

It presents as a function, thus:

    - list() -> []
    - list("a") -> ["a"]
    - list("a", "b") -> ["a", "b"]

Thanks to @wr0ngway for the idea of this approach, fixes #7460.

Assuming this is the route we wish to follow, we should make it work with types other than strings - the initial quick implementation is to get a feel for using a function rather than syntax.

cc @phinze, @mitchellh, @jbardin

### CODE REVIEW

**Comment by phinze** [comment]
Direction looks good. +1 for this as a stop-gap solution until we can parse non-primitives directly in HIL.

**Comment by jen20** [comment]
I've cleaned this up:

- added a test to verify behaviour if a non-string is passed
- removed the type checking code (which would never be hit) in favour of letting the type checker do its work
- fixed formatting issues

I'll remove the WIP now - cc @phinze.

**Comment by phinze** [comment]
LGTM for strings. Agreed we should make it work for lists and maps as well.

**Comment by jbardin** [comment]
Expanded the list interpolation to accept lists and maps, and the concat function to accept lists of lists and lists of maps. 

This now also fixes #7146

File: config/interpolate_funcs.go [hunk 1]
```diff
@@ -218,44 +258,52 @@ func interpolationFuncCoalesce() ast.Function {
...
-
-				// Otherwise variables
-				if argument, ok := arg.([]ast.Variable); ok {
-					for _, element := range argument {
-						t := element.Type
-						switch t {
+				switch arg := arg.(type) {
+				case string:
+					// we also allow bare strings for backwards compatibility
+					outputList = append(outputList, ast.Variable{Type: ast.TypeString, Value: arg})
```
Comment (phinze) [inline config/interpolate_funcs.go]: Let's nuke the BC here. I believe we've already gone talking about this case like it's gone! 😀

File: config/interpolate_funcs_test.go [hunk 2]
```diff
@@ -5,13 +5,114 @@ import (
...
+				Value: map[string]ast.Variable{
+					"key2": {
+						Type:  ast.TypeString,
+						Value: "baz",
+					},
+				},
+			},
+		},
+	})
+}
```
Comment (phinze) [inline config/interpolate_funcs_test.go]: 👏

File: config/interpolate_funcs.go [hunk 3]
```diff
@@ -218,44 +258,52 @@ func interpolationFuncCoalesce() ast.Function {
...
 				}
+			}
 
-				return nil, fmt.Errorf("arguments to concat() must be a string or list of strings")
+			// we don't support heterogeneous types, so make sure all types match the first
+			if len(outputList) > 0 {
+				firstType := outputList[0].Type
+				for _, v := range outputList[1:] {
+					if v.Type != firstType {
+						return nil, fmt.Errorf("unexpected type %s in list of type %s", v.Type, firstType)
```
Comment (phinze) [inline config/interpolate_funcs.go]: I believe "printable" is a thing for types to make them more error string friendly.

**Comment by phinze** [comment]
Nice work @jbardin!! A few inline nits, but this looks super solid overall.

File: config/interpolate_funcs.go (hunk 3 above)
Comment (jbardin) [inline config/interpolate_funcs.go]: I wasn't sure, because we also stringer-ify them.  The Printable() output is all lower case, but there's no grammar-correct way to remove the stutter from that output (not that this is much better :shrug:)

Comment (phinze) [inline config/interpolate_funcs.go]: Ah gotchya - yeah I was really just making sure we are treating this as a user-facing error message and making sure it's reasonably decipherable from out front. I'll defer to whatever you think works best here. 👍

**Comment by jbardin** [comment]
Used Printable, since it will usually make a better user-facing error.
Squashed the minor changes.

**Comment by phinze** [comment]
LGTM
