### PR TITLE
configs/configupgrade: preserve in-line comments for lists

### LINKED ISSUE #21155: terraform 0.12upgrade in v0.12 beta 2 strips comments from list items
### Terraform Version

```
Terraform v0.12.0-beta2
```

### Terraform Configuration Files

Given a v0.11 config file "variables.tf"
```hcl
variable "security_group_source_sgs" {
  type        = "list"
  description = "Permitted sources of traffic for this Aurora cluster by security group ID."

  default = [
    "sg-00000000000000000", # Traffic from resource a
    "sg-11111111111111111", # Traffic from resource b
    "sg-22222222222222222", # Traffic from resource c
  ]
}
```

### Debug Output

N/A

### Crash Output

N/A

### Expected Behavior

`terraform 0.12upgrade` retains comments following individual list items as it does for other attributes:

```hcl
variable "security_group_source_sgs" {
  type        = list(string)
  description = "Permitted sources of traffic for this Aurora cluster by security group ID."

  default = [
    "sg-00000000000000000", # Traffic from resource a
    "sg-11111111111111111", # Traffic from resource b
    "sg-22222222222222222", # Traffic from resource c
  ]
}
```

### Actual Behavior

`terraform 0.12upgrade` strips/removes the comments after each individual list item:

```hcl
variable "security_group_source_sgs" {
  type        = list(string)
  description = "Permitted sources of traffic for this Aurora cluster by security group ID."

  default = [
    "sg-00000000000000000",
    "sg-11111111111111111",
    "sg-22222222222222222",
  ]
}
```

This impairs human readability and understanding of what each individual list item means. In our example, if we wanted to remove default access from "resource b", we now have to return to the AWS console and figure out what each security group is.

### Steps to Reproduce

1. `terraform 0.12upgrade`

### Additional Context

This only appears to occur for individual items in a list; other comments after key/value attributes are formatted with a single leading space.

### References

None

### PR DESCRIPTION
**Pull request by mildwonkey**
The configupgrade tool was not writing `LineComments` for lists. Now it
is!

Fixes #21155

### CODE REVIEW

File: configs/configupgrade/upgrade_expr.go [hunk 1]
```diff
@@ -168,10 +168,19 @@ Value:
...
-			if multiline {
-				buf.WriteString(",\n")
-			} else if i < len(tv.List)-1 {
-				buf.WriteString(", ")
+			if lit, ok := node.(*hcl1ast.LiteralType); ok && lit.LineComment != nil {
+				for _, comment := range lit.LineComment.List {
+					buf.WriteString(", " + comment.Text)
+				}
+				if multiline {
+					buf.WriteString("\n")
```
Comment (apparentlymart) [inline configs/configupgrade/upgrade_expr.go]: I think this is missing a comma+space? :thinking:

Comment (apparentlymart) [reply configs/configupgrade/upgrade_expr.go]: Oh sorry, I just re-read and I understand better on the second read. :confounded:

Comment (apparentlymart) [reply configs/configupgrade/upgrade_expr.go]: I think what confused me here is that this doesn't seem to have any behavior for if `multiline` is `false`.

By how the parser works I think it's impossible to have line comments in single-line mode, so in practice that probably doesn't really matter, but perhaps it would be clearer to remove the `if multiline` condition altogether here and just always print the newline.

If a list item is a string but has no comment at all, would this logic lose its trailing comma, or am I missing something that deals with that? I think in that case `lit.LineComment.List` woudl be empty, so we'd print no commas at all.

```hcl
list = [
  "foo",
  "bar",
]
```

Comment (mildwonkey) [reply configs/configupgrade/upgrade_expr.go]: I added a test to validate the behavior for a string list item with no comment, and it passed - that's captured in the `else` statement a few lines below (in this case: `else there are no comments`). I'll push that test (and removing the redundant `if multiline` - I had _thought_ it was redundant but didn't trust myself). Thanks!

Comment (apparentlymart) [reply configs/configupgrade/upgrade_expr.go]: Ahh, what I missed was the `&& lit.LineComment != nil` on the first branch above. The "if (type assertion)" lead-in caused me to gloss over the rest as a "stock phrase" `if lit, ok := node.(*hcl1ast.LiteralType); ok {` and not spot that extra condition on the end.

Makes sense now! Thanks for adding the extra test.
