### PR TITLE
Limit backend block validation in the `validate` command to just backend type

### LINKED ISSUE #38466: `terraform validate` now fails valid partial backend configurations
### Terraform Version

```shell
1.15.0
```

### Terraform Configuration Files

```terraform
terraform {
  backend "azurerm" {}
}
```

### Debug Output

N/A

### Expected Behavior

`terraform validate` should succeed after `terraform init` has successfully initialized a partial backend using `-backend-config`.

A partial backend block should not be treated as invalid source configuration when the missing backend arguments are intentionally supplied during initialization.

More broadly, `terraform validate` should remain deployment-context agnostic: it should validate the root module's source configuration, not require backend coordinates for a particular run environment.

If backend required-argument validation is useful, it should be opt-in or gated behind a separate flag. Making it the default is a breaking change for documented partial-backend usage, where those values are intentionally supplied during `terraform init`.

### Actual Behavior

With 1.15.0, `terraform init` succeeds, but `terraform validate` now fails with:

```text
Error: Missing required argument

  on main.tf line 2, in terraform:
   2:   backend "azurerm" {}

The argument "storage_account_name" is required, but no definition was found.

Error: Missing required argument
The argument "container_name" is required, but no definition was found.

Error: Missing required argument
The argument "key" is required, but no definition was found.
```

### Steps to Reproduce

```bash
terraform init -reconfigure \
  -backend-config="storage_account_name=..." \
  -backend-config="container_name=..." \
  -backend-config="key=..."

terraform validate
```

### Additional Context

Terraform 1.15.0 changed `terraform validate` to validate backend blocks, including required backend arguments. This breaks a very common and documented CI/CD pattern: keeping backend configuration partial in source and supplying the environment-specific values during `terraform init`.

Example:

```hcl
terraform {
  backend "azurerm" {}
}
```

CI then runs:

```bash
terraform init -reconfigure \
  -backend-config="storage_account_name=..." \
  -backend-config="container_name=..." \
  -backend-config="key=..."

terraform validate
terraform plan
```

With 1.15.0, `terraform init` succeeds, but `terraform validate` now fails with:

```text
Error: Missing required argument

  on main.tf line 2, in terraform:
   2:   backend "azurerm" {}

The argument "storage_account_name" is required, but no definition was found.

Error: Missing required argument
The argument "container_name" is required, but no definition was found.

Error: Missing required argument
The argument "key" is required, but no definition was found.
```

This treats an intentionally partial backend block as invalid source, even though partial backend configuration is a supported Terraform pattern and the missing values are supplied during initialization.

The problem is that `validate` is now conflating two separate concerns:

- module/configuration integrity
- deployment/run context completeness

`terraform validate` should validate whether the configuration is structurally coherent as source. It should not require deployment-specific backend coordinates that are intentionally injected by automation at init time.

`terraform plan` is already the correct command for validating a configuration in a specific run context, with the initialized backend, variables, providers, generated files, and state available.

This change is especially painful because many CI/CD pipelines do:

```bash
terraform init ...
terraform validate
terraform plan
```

and many also install `latest` Terraform. Those pipelines began failing immediately when 1.15.0 was released, despite no change to their Terraform source.

Can `terraform validate` preserve support for partial backend configuration, or provide a mode/flag that validates backend type/schema without requiring init-supplied backend arguments?

### References

#38021 

### Generative AI / LLM assisted development?

N/A

### PR DESCRIPTION
**Pull request by SarahFrench**
Fixes https://github.com/hashicorp/terraform/issues/38466

This was an oversight on my part in the original PR 😅 

We're going with a partial revert to address that issue when using partial configuration. I think continuing to include validation of backend type is valid, while re-enabling use of configurations that are expected to be used alongside `-backend-config`.

## Target Release

1.15.1

## Rollback Plan

- [x] If a change needs to be reverted, we will roll out an update to the code within 7 days.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

## CHANGELOG entry

- [x] This change is user-facing and I added a changelog entry.
- [ ] This change is not user-facing.

### CODE REVIEW

File: internal/command/validate.go [hunk 1]
```diff
@@ -120,11 +114,8 @@ func (c *ValidateCommand) validate(dir string) tfdiags.Diagnostics {
 
 	// Validation of backend block, if present
 	// Backend blocks live outside the Terraform graph so we have to do this separately.
-	switch {
-	case cfg.Module.Backend != nil:
-		diags = diags.Append(c.validateBackend(cfg.Module.Backend))
-	case cfg.Module.StateStore != nil:
-		diags = diags.Append(c.validateStateStore(cfg.Module.StateStore))
```
Comment (radeksimko) [inline internal/command/validate.go:127]: I'd argue that for `state_store` blocks it wouldn't be a breaking change to do the validation. Perhaps not super convenient but at least it wouldn't come as a surprise, so I'd be still inclined to keep that one.

Comment (SarahFrench) [reply internal/command/validate.go:127]: State stores are planned to still support the -backend-config flag though, so the bug report is equally valid for users of backend or state_store blocks. It's just that few to no people are using state_stores currently.

**Review by DanielMSchmidt — APPROVED** [review]
Partially reverting makes sense to me 👍
