### PR TITLE
Don't open a new file descriptor for a locked state.

### LINKED ISSUE #17620: v0.11.4 plans resource creation where resources already exist and are listed in tfstate.
### Terraform Version
v0.11.4 broken.
v0.11.3 working.

### Terraform Configuration Files
But also reproducible with other resources.

```hcl
variable "region" {
  default = "eu-west-2"
}

provider "aws" {
  region = "${var.region}"
}

resource "aws_sns_topic" "user_updates" {
  name = "user-updates-topic"
}
```

### Debug Output
https://gist.github.com/OliverCole/e06b2fd1e458d8b183ff81bf85d1ea59

### Expected Behavior
`No changes. Infrastructure is up-to-date.`

### Actual Behavior
`Plan: 1 to add, 0 to change, 0 to destroy.`

### Steps to Reproduce
```
λ terraform.0.11.3.exe apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + aws_sns_topic.user_updates
      id:     <computed>
      arn:    <computed>
      name:   "user-updates-topic"
      policy: <computed>


Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_sns_topic.user_updates: Creating...
  arn:    "" => "<computed>"
  name:   "" => "user-updates-topic"
  policy: "" => "<computed>"
aws_sns_topic.user_updates: Creation complete after 0s (ID: arn:aws:sns:eu-west-2:[redacted]:user-updates-topic)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

λ terraform.0.11.3.exe plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

aws_sns_topic.user_updates: Refreshing state... (ID: arn:aws:sns:eu-west-2:[redacted]:user-updates-topic)

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

λ terraform.0.11.4.exe plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + aws_sns_topic.user_updates
      id:     <computed>
      arn:    <computed>
      name:   "user-updates-topic"
      policy: <computed>


Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

# Just prove my version numbers are correct
λ terraform.0.11.4.exe --version
Terraform v0.11.4
+ provider.aws v1.11.0

λ terraform.0.11.3.exe --version
Terraform v0.11.3
+ provider.aws v1.11.0

Your version of Terraform is out of date! The latest version
is 0.11.4. You can update by downloading from www.terraform.io/downloads.html
```

### Additional Context
N/A

### PR DESCRIPTION
**Pull request by jbardin**
Only open a new file descriptor for RefreshState if we haven't written a
state, and don't have the correct state open already. This prevents
windows from failing to refresh a locked state.

This also surfaces initial state read errors, which were previously assumed to be because of an empty state. On windows, this could mask the error return when file access is denied.

Fixes #17620

### CODE REVIEW

File: terraform/state.go [hunk 1]
```diff
@@ -1876,11 +1877,19 @@ var ErrNoState = errors.New("no state")
...
+		return nil, ErrNoState
+	}
+
 	buf := bufio.NewReader(src)
+
 	if _, err := buf.Peek(1); err != nil {
-		// the error is either io.EOF or "invalid argument", and both are from
-		// an empty state.
-		return nil, ErrNoState
+		if err == io.EOF {
```
Comment (apparentlymart) [inline terraform/state.go]: The removed comment here talks about both `io.EOF` and "invalid argument". Is the "invalid argument" case taken care of by the nil check above, or taken care of some other way here?

Comment (jbardin) [reply terraform/state.go]: oh yes, "invalid argument" is only expected when we have a nil `*os.File`. At one point that was ok to use for `ReadState` to indicate the absence of state. I'd like to not have that at all, but that takes some more serious auditing to make sure we don't have any more code paths passing it in.

**Comment by jbardin** [comment]
FTR, All state tests passing when run directly on a Windows host.
