### PR TITLE
core: module targeting

### LINKED ISSUE #1434: "-target" doesn't work with modules
I'm not sure if this is a bug or a feature, but `-target` does not work with modules. See below:

**`sample.tf`**:
```ruby
variable "aws_region" {
  default = "eu-west-1"
  description = "AWS Region"
}

provider "aws" {
  access_key = ""
  secret_key = ""
  region = "${var.aws_region}"
}

module "vpc" {
  source = "github.com/terraform-community-modules/tf_aws_vpc"

  aws_access_key = ""
  aws_secret_key = ""
  aws_region = "${var.aws_region}"
  environment_name = "dev"
  cidr_block = "10.10.0.0/16"
  mytag = ""
}
```

```
$ terraform plan
```
```
Refreshing Terraform state prior to plan...


The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

+ module.vpc
    1 resource(s)
```

```
$ terraform plan -target=module.vpc
```
```
Refreshing Terraform state prior to plan...


No changes. Infrastructure is up-to-date. This means that Terraform
could not detect any differences between your configuration and
the real physical resources that exist. As a result, Terraform
doesn't need to do anything.
```

### PR DESCRIPTION
**Pull request by phinze**
Adds the ability to target resources within modules, like:

module.mymod.aws_instance.foo

And the ability to target all resources inside a module, like:

module.mymod

Closes #1434

### CODE REVIEW

File: terraform/graph_config_node_resource.go [hunk 1]
```diff
@@ -174,7 +176,7 @@ func (n *GraphNodeConfigResource) DynamicExpand(ctx EvalContext) (*Graph, error)
 // GraphNodeAddressable impl.
 func (n *GraphNodeConfigResource) ResourceAddress() *ResourceAddress {
 	return &ResourceAddress{
-		// Indicates no specific index; will match on other three fields
+		Path:         n.Path[1:],
```
Comment (phinze) [inline terraform/graph_config_node_resource.go]: Decided that it's the Addressable Node's responsibility to strip off "root" as a prefix to their module path, rather than the Resource Address's responsibility to _prepend_ `"root"` to the module path of every parsed address.

File: terraform/resource_address.go [hunk 2]
```diff
@@ -76,10 +116,10 @@ func tokenizeResourceAddress(s string) (map[string]string, error) {
...
 	// string "aws_instance.web.tainted[1]"
 	re := regexp.MustCompile(`\A` +
-		// "aws_instance"
-		`(?P<type>[^.]+)\.` +
-		// "web"
-		`(?P<name>[^.[]+)` +
+		// "module.foo.module.bar" (optional)
+		`(?P<path>(?:module\.[^.]+\.?)*)` +
+		// "aws_instance.web" (optional when module path specified)
+		`(?:(?P<type>[^.]+)\.(?P<name>[^.[]+))?` +
```
Comment (phinze) [inline terraform/resource_address.go]: This regexp is getting a little absurd. I must learn the ways of the parser.

Comment (mitchellh) [inline terraform/resource_address.go]: Haha no problem I can show you sometime :)

**Comment by mitchellh** [comment]
LGTM!

**Comment by jszwedko** [comment]
:clap:

**Comment by ryanking** [comment]
Trying to make use of this in 0.6.0 and it appears to not be working. Does it skip modules where none of the resources have been created?

I have a module called "corp" which has no resource created in it.

When I run this:

```$ terraform plan -module-depth=2```

I get:
```
[...]
+ module.corp.vpc.aws_vpc.vpc
[...]
Plan: 11 to add, 10 to change, 0 to destroy.
```

But with this:
```
$ terraform plan -module-depth=2 -target=module.corp
```
I get:
```
[...]
module.corp.aws_vpc.corp: Refreshing state... (ID: vpc-80d801e5)

No changes. Infrastructure is up-to-date. This means that Terraform
could not detect any differences between your configuration and
the real physical resources that exist. As a result, Terraform
doesn't need to do anything.
```

**Comment by maxenglander** [comment]
Same issue as @ryanking on 0.6.4-dev.

This works:
```
$ terraform plan
Refreshing Terraform state prior to plan...

The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

+ module.dc1.api
    7 resource(s)
+ module.dc0.bastion
    8 resource(s)
+ module.dc1.zk
    8 resource(s)
+ module.dc0.rds
    8 resource(s)
+ module.dc0.zk
    8 resource(s)
+ module.dc0.api
    7 resource(s)
+ module.dc1.consul
    6 resource(s)
+ module.dc1.bastion
    8 resource(s)
+ module.dc1.rds
    8 resource(s)
+ module.dc0.consul
    6 resource(s)
+ module.dc1.netsec
    10 resource(s)
+ module.dc0.netsec
    10 resource(s)
```

This doesn't:
```
$ terraform plan -target=module.dc0 terraform
Refreshing Terraform state prior to plan...


No changes. Infrastructure is up-to-date. This means that Terraform
could not detect any differences between your configuration and
the real physical resources that exist. As a result, Terraform
doesn't need to do anything.
```

**Comment by cloudify** [comment]
Same issue here, I can confirm that this happens only when none of the module's resources have been created yet.

**Comment by jmccarty3** [comment]
Just hit this as well when adding a new module and only targeting it.

**Comment by apparentlymart** [comment]
I'm not sure from the examples given if this is the same issue, but I noted an issue where nested modules don't target in the way I initially expected.

Given the following module tree:

* root
  * foo
    * bar
    * baz

I initially expected that targeting `module.foo` would target all of the resources in `bar` and `baz`, but it appears that in fact it targets only the resources directly in `foo`. In my case there was actually nothing in `foo` *except* the declarations of `bar` and `baz`, so the `-target` plan appeared to do nothing, just like what is seen in the other examples above.

I suspect that this is at least what's going on for @maxenglander, since his `dc0` module seems to have various sub-modules within.

The workaround for me was to target `bar` and `baz` explicitly by writing out their full names. This was easy (if annoying) in my case because I had relatively few nested modules, but it'd be more intuitive/consistent if targeting a module would also implicitly target all of its descendant modules, thus working on an entire sub-tree of the module heirarchy.

(FWIW, the above description of the problem is based on observation and reasoning rather than actually digging into the code. I did dig into the patch on this PR quickly and noted that there doesn't seem to be a test for the grandchild-module case, but wasn't able to quickly gather enough context about the change to know for sure that the cause I've identified above is true... but certainly this is the behavior I've observed, and the workaround I used to move past it.)

**Comment by phinze** [comment]
Hey folks, I believe targeting of new modules should be working properly in the latest version of Terraform. If you're still seeing trouble on the latest version, would you mind reporting these as new issues with repro steps? 

@apparentlymart that report looks like it could be filed as a fresh issue as well.

I'll keep an eye out for new issues on this front. :+1:

**Comment by tamsky** [comment]
@apparentlymart  
> The workaround for me was to target bar and baz explicitly by writing out their full names. 

I'm not understanding how you're accomplishing the task from your description.

Would you mind providing an example of your workaround in action?

**Comment by tamsky** [comment]
Is the only way to discover the correct `-target` path when modules include other modules is to use TF_LOG and grovel the output?  (This is how I discovered it myself.)

Perhaps there should be a command similar to `show`, but which shows all `targets`?

The resource name below is not very intuitive or easily discoverable:

Using @apparentlymart's root/foo/{bar,baz} layout above, and assuming the `bar` module includes the `baz` module:
```
module "baz" {
   source = "../baz"
}
```
this becomes the target name:
   `-target=module.bar.module.baz`

**Comment by apparentlymart** [comment]
@tamsky for the module tree in my example, the following would only apply resources in the module "foo", and not in modules "foo.bar" and "foo.baz":

```
terraform plan ... -target="module.foo"
```

So to apply the whole subtree under "foo" it's necessary to list out all of the descendant modules explicitly:

```
terraform plan ... -target="module.foo" -target="module.foo.module.bar" -target="module.foo.module.baz"
```

**Comment by soupdiver** [comment]
I'm still hitting this issue
Using Terraform `10.8`

I'm using https://github.com/terraform-community-modules/tf_aws_vpc and only want to target that module during plan.

How I use the module
```
module "vpc" {
  source = "github.com/terraform-community-modules/tf_aws_vpc"

  name = "${var.environment}"
...
```

I have to specify `-target=module.vpc.aws_vpc.mod` to get this working but I would expect that `-target=module.vpc` is enough and includes _all_ resources defined by the module

**Comment by tamsky** [comment]
@soupdiver I would file a bug.  

Based on the description of the feature in this (merged) PR:

> Adds ... 
> And the ability to target all resources inside a module, like:
> module.mymod

as well as reviewing the bug: (-target does not source child modules #5190)
-- you can reasonably guess that you've found a bug if you need to use
`-target=module.vpc.aws_vpc.mod`
and can't simply use:
`-target=module.vpc`
