### PR TITLE
check for nil state in s3 client Get

### LINKED ISSUE #14927: backend/s3: crash in s3.Get
terraform v0.9.6

terraform apply  - 

 main.tf in attached ZIP.

has worked before, but I got confused about an S3 backend. Did a destroy on everything, then started again. Crashes every time, even after reboot.

OS X 10.12.5. iTerm2. All AWS in eu-west-2 (London)

[Archive.zip](https://github.com/hashicorp/terraform/files/1038447/Archive.zip)

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_instance
- dnsimple_record

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
terraform.tfstate attached

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
`crash.log`. in zip file

### Expected Behavior
What should have happened?
should create a simple ASG & ELB, from a book.

### Actual Behavior
Crash every time

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
All very standard, following book 'terraform up and running'

### PR DESCRIPTION
**Pull request by jbardin**
The S3 client can return (nil, nil) when the remote state doesn't exit.
The caused a nil pointer dereference when checking the payload.MD5
against the expected value.

This can happen if the remote state was manually removed, but the digest
entry was left in the DynamoDB table.

Fixes #14927

### CODE REVIEW

File: backend/remote-state/s3/client_test.go [hunk 1]
```diff
@@ -263,8 +263,8 @@ func TestRemoteClient_stateChecksum(t *testing.T) {
 		t.Fatal(err)
 	}
 
-	// put the old state in place of the new, without updating the checksum
-	if err := client2.Put(oldState.Bytes()); err != nil {
+	// put an empty state in place to check for panics dring get
```
Comment (apparentlymart) [inline backend/remote-state/s3/client_test.go]: `dring`
