### PR TITLE
cli: Improve error for invalid -target flags

### LINKED ISSUE #26786: Trying to plan or apply with an incorrect `-target` has no error message
### Terraform Version

```
Terraform v0.13.5
```

### Terraform Configuration Files

```terraform
resource "null_resource" "test" {}
```

### Debug Output

```
TF_LOG=trace terraform apply -target asdf
2020/11/02 10:24:04 [INFO] Terraform version: 0.13.5  
2020/11/02 10:24:04 [INFO] Go runtime version: go1.14.10
2020/11/02 10:24:04 [INFO] CLI args: []string{"/usr/local/bin/terraform", "apply", "-target", "asdf"}
2020/11/02 10:24:04 [DEBUG] Attempting to open CLI config file: /Users/<username>/.terraformrc
2020/11/02 10:24:04 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/11/02 10:24:04 [DEBUG] checking for credentials in "/Users/<username>/.terraform.d/plugins"
2020/11/02 10:24:04 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2020/11/02 10:24:04 [DEBUG] will search for provider plugins in /Users/<username>/.terraform.d/plugins
2020/11/02 10:24:04 [TRACE] getproviders.SearchLocalDirectory: /Users/<username>/.terraform.d/plugins is a symlink to /Users/w107566/.terraform.d/plugins
2020/11/02 10:24:04 [DEBUG] ignoring non-existing provider search directory /Users/<username>/Library/Application Support/io.terraform/plugins
2020/11/02 10:24:04 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2020/11/02 10:24:04 [INFO] CLI command args: []string{"apply", "-target", "asdf"}
Usage: terraform apply [options] [DIR-OR-PLAN]

  Builds or changes infrastructure according to Terraform configuration
  files in DIR.

  By default, apply scans the current directory for the configuration
  and applies the changes appropriately. However, a path to another
  configuration or an execution plan can be provided. Execution plans can be
  used to only execute a pre-determined set of actions.

Options:

  -auto-approve          Skip interactive approval of plan before applying.

  -backup=path           Path to backup the existing state file before
                         modifying. Defaults to the "-state-out" path with
                         ".backup" extension. Set to "-" to disable backup.

  -compact-warnings      If Terraform produces any warnings that are not
                         accompanied by errors, show them in a more compact
                         form that includes only the summary messages.

  -lock=true             Lock the state file when locking is supported.

  -lock-timeout=0s       Duration to retry a state lock.

  -input=true            Ask for input for variables if not directly set.

  -no-color              If specified, output won't contain any color.

  -parallelism=n         Limit the number of parallel resource operations.
                         Defaults to 10.

  -refresh=true          Update state prior to checking for differences. This
                         has no effect if a plan file is given to apply.

  -state=path            Path to read and save state (unless state-out
                         is specified). Defaults to "terraform.tfstate".

  -state-out=path        Path to write state to that is different than
                         "-state". This can be used to preserve the old
                         state.

  -target=resource       Resource to target. Operation will be limited to this
                         resource and its dependencies. This flag can be used
                         multiple times.

  -var 'foo=bar'         Set a variable in the Terraform configuration. This
                         flag can be set multiple times.

  -var-file=foo          Set variables in the Terraform configuration from
                         a file. If "terraform.tfvars" or any ".auto.tfvars"
                         files are present, they will be automatically loaded.
```

### Crash Output

N/A

### Expected Behavior

An error message should be displayed explaining why the apply failed. Such as:

> Target resource "asdf" [ could not be resolved | does not exist | is invalid | etc ] 

### Actual Behavior

Help output is displayed, with no explanation as to why.

### Steps to Reproduce

1. echo 'resource "null_resource" "test" {}' > main.tf
1. terraform init
1. terraform apply -target asdf
1. Observe help output with no explanation of why the given arguments are invalid
1. terraform apply -target null_resource.test
1. `terraform apply` is successful

### Additional Context

This behavior is confusing and leads to poor user experience. The user cannot be sure if they gave the wrong target, or if they made some sort of syntactical error elsewhere in the command arguments.

### PR DESCRIPTION
**Pull request by alisdair**
Errors encountered when parsing flags for apply, plan, and refresh were being suppressed. This resulted in a generic usage error when using an invalid `-target` flag.

This commit makes several changes to address this. First, these commands now output the flag parse error before exiting, leaving at least some hint about the error. You can verify this manually with something like:

    terraform apply -invalid-flag

We also change how target attributes are parsed, moving the responsibility from the flags instance to the command. This allows us to customize the diagnostic output to be more user friendly. The diagnostics now look like:

example

Finally, we add test coverage for both parsing of target flags, and at the command level for successful use of resource targeting. These tests focus on the UI output (via the change summary and refresh logs), as the functionality of targeting is covered by the context tests in the terraform package.

Fixes #26786

### CODE REVIEW

File: command/apply_destroy_test.go [hunk 1]
```diff
@@ -358,7 +358,10 @@ func TestApply_destroyPath(t *testing.T) {
 	}
 }
 
-func TestApply_destroyTargeted(t *testing.T) {
+// Config with multiple resources with dependencies, targeting destroy of a
```
Comment (pselle) [inline command/apply_destroy_test.go:361]: I love test comments
