### PR TITLE
don't send an invalid config to a provisioner

### LINKED ISSUE #22700: destroy provisioner fails to evaluate orphaned for_each instance
### Terraform Version
```
Terraform v0.12.7
```

### Terraform Configuration Files

```hcl
resource "null_resource" "default" {
  for_each = {delete-me = "first", delete-me-as-well = "second"}

  provisioner "local-exec" {
    when = create
    command = <<-EOF
      echo "Creating ${each.key}=${each.value}"
    EOF
  }

  provisioner "local-exec" {
    when = destroy
    command = <<-EOF
      echo "Deleting ${each.key}=${each.value}"
    EOF
  }
}
```

### Crash Output

https://gist.github.com/autero1/06743847a4b1deefcbd1b42e506574b8

### Expected Behavior

`terraform` removes single `null_resource`

### Actual Behavior

`terraform` crashes

### Steps to Reproduce

Using the provided configuration:

1. `terraform init`
2. `terraform apply`
3. Remove single entry from the `for_each` map, for example `delete-me-as-well = "second"`
4. `terraform apply`

--> crash

### Additional Context

If you just `apply` and `destroy` without changing the `for_each` map, `terraform` destroys the resources correctly. If you add entries, `terraform` adds those correctly, but on every re-`apply`, `terraform` crashes if you've removed entries.

### PR DESCRIPTION
**Pull request by jbardin**
The config diagnostics weren't checked before sending to the
provisioner, and may have contained invalid values.

This also adds an interesting case of `for_each` with `when = "destroy"`, which currently will fail if the each value is referenced in the provisioner.

This fixes the crash in #22700, but does not fix the root cause of the unknown for_each values.

### CODE REVIEW

File: terraform/context_apply_test.go [hunk 1]
```diff
@@ -2018,6 +2018,72 @@ aws_instance.foo:
...
+
+	if _, diags := ctx.Plan(); diags.HasErrors() {
+		t.Fatalf("plan errors: %s", diags.Err())
+	}
+
+	_, diags := ctx.Apply()
+	if diags == nil {
+		t.Fatal("should error")
+	}
+	if !strings.Contains(diags.Err().Error(), `Reference to "each" in context without for_each`) {
```
Comment (apparentlymart) [inline terraform/context_apply_test.go]: Do you think there's a way we can give a more specific error here? The wording of the error this seems to be returning talks about adding `for_each` to the resource block, which is not going to help in this case.

I guess it's tough though because this error is emerging out of `EvaluateBlock`; improving the error message is probably the same level of effort as making `for_each` work here at all, so maybe we just live with this for the moment to get rid of the crasher and try to make `for_each` work here soon afterwards. :thinking:

Comment (jbardin) [reply terraform/context_apply_test.go]: Yes, that was my intent here. I didn't an easy to to improve the error, but since we want this to work in the long run catching any configuration errors should suffice for now.
