### PR TITLE
remove extra backend migration prompts

### LINKED ISSUE #16922: Input prompt loop on init when no tty
### Terraform Version

```
0.11.0
```

### Terraform Configuration Files

1. main.tf v1

```hcl
terraform {
  backend "s3" {
    bucket = "test1"
    key    = "terraform_state"
  }
}
```

2. main.tf v2

```hcl
terraform {
  backend "s3" {
    bucket = "test2"
    key    = "terraform_state"
  }
}
```

### Debug Output

```
Initializing the backend...
Backend configuration changed!

Terraform has detected that the configuration specified for the backend
has changed. Terraform will now reconfigure for this backend. If you didn't
intend to reconfigure your backend please undo any changes to the "backend"
section in your Terraform configuration.


Do you want to copy the state from "s3"?
  Would you like to copy the state from your prior backend "s3" to the
  newly configured "s3" backend? If you're reconfiguring the same backend,
  answering "yes" or "no" shouldn't make a difference. Please answer exactly
  "yes" or "no".

  Enter a value:
Do you want to copy the state from "s3"?
  Would you like to copy the state from your prior backend "s3" to the
  newly configured "s3" backend? If you're reconfiguring the same backend,
  answering "yes" or "no" shouldn't make a difference. Please answer exactly
  "yes" or "no".

[..repeated infitnitely..]
```

### Crash Output

n/a

### Expected Behavior

Terraform should detect there is no tty allocated and only show the message once then exit.

I know specifying the `-input=false` arg would prevent this but it still seems like incorrect behaviour to me.

### Actual Behavior

Looped infinitely repeating the above message

### Steps to Reproduce

1. Create v1 of file `main.tf` provided above
2. Run `terraform init` from docker (with no tty) like so:

```sh
docker run --rm \
--env AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
--env AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION \
--env AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
--volume "$(pwd):/terraform" \
--workdir /terraform \
--entrypoint sh \
hashicorp/terraform:0.11.0 \
-c "terraform init"
```

You should see the below output (the bucket not existing doesn't matter):

```
Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
Error loading state: BucketRegionError: incorrect region, the bucket is not in 'eu-west-1' region
	status code: 301, request id: , host id:
```

3. Alter `main.tf` to v2 provided above and run the above docker command again

### Important Factoids

Running in docker with no tty

### References

n/a

### PR DESCRIPTION
**Pull request by jbardin**
The duplicate prompts can be confusing when the user confirms that a
migration should happen and we immediately prompt a second time for the
same thing with slightly different wording. The extra hand-holding that
this provides for legacy remote states is less critical now, since it's
been 2 major release cycles since those were removed.

Only check for input twice in the meta.confirm method. This prevents an
errant newline from aborting the run while allowing Terraform to exit if
there is no input available. We don't just check for a tty, since we
still rely on being able to pipe input in for testing.

Remove the redundant confirmation loops in the migration code, and only
use the confirm method.

fixes #16922

### CODE REVIEW

File: command/meta_backend.go [hunk 1]
```diff
@@ -1638,27 +1554,16 @@ Plan Serial:    %[1]d
...
-newly configured %q backend? If you're reconfiguring the same backend,
-answering "yes" or "no" shouldn't make a difference. Please answer exactly
-"yes" or "no".
-`
-
-const inputBackendMigrateLegacy = `
-Terraform can copy the existing state in your legacy remote state
-backend to your newly configured backend. Please answer "yes" or "no".
+const outputBackendMigrateChange = `
+Terraform detected the backend type changed from %q to %q.
```
Comment (apparentlymart) [inline command/meta_backend.go]: I think "Terraform detected _that_ the..." would be clearer here. On first read my mental parser was confused by trying to read it as "Terraform detected the backend type".
