### PR TITLE
provider/aws: Updating CloudFront distribution to correct LoggingConfig

### LINKED ISSUE #6390: Failed CloudFront logging_config change stored to state and not refreshed
I had an existing `aws_cloudfront_distribution` resource without `logging_config` configuration.
The when adding a new `aws_s3_bucket` and a referencing `logging_config` block, the Bucket was created but not ready when Terraform tried to configure it for the CloudFront distribution:

```
aws_s3_bucket.logs: Creating...
  acl:              "" => "private"
  arn:              "" => "<computed>"
  bucket:           "" => "foo-logs"
  force_destroy:    "" => "0"
  hosted_zone_id:   "" => "<computed>"
  region:           "" => "<computed>"
  website_domain:   "" => "<computed>"
  website_endpoint: "" => "<computed>"
aws_s3_bucket.logs: Creation complete
aws_cloudfront_distribution.app: Modifying...
  logging_config.#:                          "0" => "1"
  logging_config.1955940039.bucket:          "" => "foo-logs"
  logging_config.1955940039.include_cookies: "" => "0"
  logging_config.1955940039.prefix:          "" => "cloudfront"
Error applying plan:

1 error(s) occurred:

* aws_cloudfront_distribution.app: InvalidArgument: The parameter Logging Bucket does not refer to a valid S3 bucket.
        status code: 400, request id: <xxx>

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

This is a familiar case with AWS and it's caching, but the issue is that Terraform anyway **stored the new but failed configuration to the state file** and does not see any changes in the future `plan` or `apply` calls. So it does not refresh the state from AWS.

### PR DESCRIPTION
**Pull request by jrnt30**
- Addresses the issue when local state file has logging_config populated and the user
  disables the configuration via the UI (or in this case an
  application of the TF config).  This will now properly set the
  logging_config during the read operation and identify the state as
  diverging

Fixes #6390

### CODE REVIEW

File: builtin/providers/aws/cloudfront_distribution_configuration_structure.go [hunk 1]
```diff
@@ -124,12 +124,16 @@ func flattenDistributionConfig(d *schema.ResourceData, distributionConfig *cloud
...
 		}
 	}
+
 	if distributionConfig.Logging != nil && *distributionConfig.Logging.Enabled {
 		err = d.Set("logging_config", flattenLoggingConfig(distributionConfig.Logging))
-		if err != nil {
-			return err
-		}
+	} else {
+		err = d.Set("logging_config", []interface{}{})
```
Comment (vancluever) [inline builtin/providers/aws/cloudfront_distribution_configuration_structure.go]: Hey @jrnt30, I think right here, you'd want to do the following instead:

```
err = d.Set("logging_config", schema.NewSet(loggingConfigHash, []interface{}{}))
```

The idea here being that even though it's an empty set you still probably want to pass a `*schema.Set` and the correct hash function.

**Comment by catsby** [comment]
Excellent, thanks!
