### PR TITLE
Disallow provider configuration in expanding modules

### LINKED ISSUE #24851: Terraform 0.13 Dev - variables are not recognized in provider block when use count.
### Terraform Version

```
Terraform v0.13.0-dev
+ provider registry.terraform.io/hashicorp/aws v2.59.0
```

### Terraform Configuration Files

```hcl
./modules/test/main.tf
variable "region" {}

provider "aws" {
  version = "~> 2.59.0"
  region  = var.region
  alias   = "this"
}

data "aws_region" "current" {
  provider = aws.this
}
```

```hcl
./main.tf
locals {
  secondary_clusters = [
    {
      region        = "us-east-2"
      replicas      = 3
      instance_size = "db4.large"
    },
    {
      region        = "us-east-1"
      replicas      = 5
      instance_size = "db4.large"
    },
    {
      region        = "us-west-2"
      replicas      = 12
      instance_size = "db4.large"
    }
  ]

}

module "test" {
  count  = length(local.secondary_clusters)
  source = "./modules/test"
  region = local.secondary_clusters[count.index].region
}
```

### Debug Output

https://gist.github.com/marinsalinas/8dea55ed182bc9b6991739bf27c5c7a6

### Expected Behavior

Initialize provider by region.

### Actual Behavior

The region variable is not recognized in the provider block when use count.

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

### Additional Context
We are waiting for this feature on Terraform since we need to create RDS regional clusters dynamically by a list of regions provided.

### References

- https://github.com/hashicorp/terraform/issues/17519

### PR DESCRIPTION
**Pull request by pselle**
Expanding modules cannot have providers configured in them as this can cause issues with removal of the module. This PR updates the `moduleWalkerLoad` method in the `configload` package, where we have information about the caller (where the `count` or `for_each` is declared) and the module being loaded (which may have 0 or more provider configurations in it).

*Edited* Updated error message (changes to `for_each` when referring to `for_each`):

```
Error: Module does not support count

  on main.tf line 15, in module "child":
  15:   count = 1

Module "child" cannot be used with count because it contains a nested provider
configuration for "aws", at child/main.tf:2,10-15.

This module can be made compatible with count by changing it to receive all of
its provider configurations from the calling module, by using the "providers"
argument in the calling module block.
```

Closes #24851

### CODE REVIEW

File: configs/configload/loader_load.go [hunk 1]
```diff
@@ -17,7 +17,7 @@ import (
 // in spite of the errors.
 //
 // LoadConfig performs the basic syntax and uniqueness validations that are
-// required to process the individual modules, and also detects
+// required to process the individual modules
```
Comment (pselle) [inline configs/configload/loader_load.go:20]: I found this mysterious hanging comment, so I removed it.

File: configs/configload/loader_load.go [hunk 2]
```diff
@@ -31,8 +31,7 @@ func (l *Loader) LoadConfig(rootDir string) (*configs.Config, hcl.Diagnostics) {
 }
 
 // moduleWalkerLoad is a configs.ModuleWalkerFunc for loading modules that
-// are presumed to have already been installed. A different function
-// (moduleWalkerInstall) is used for installation.
+// are presumed to have already been installed.
```
Comment (pselle) [inline configs/configload/loader_load.go:34]: I updated this comment because `moduleWalkerInstall` does not exist.

File: configs/configload/loader_load_test.go [hunk 3]
```diff
@@ -75,8 +76,51 @@ func TestLoaderLoadConfig_addVersion(t *testing.T) {
 		t.Fatalf("success; want error")
 	}
 	got := diags.Error()
-	want := "Module requirements have changed"
-	if strings.Contains(got, want) {
+	want := "Module version requirements have changed"
+	if !strings.Contains(got, want) {
```
Comment (pselle) [inline configs/configload/loader_load_test.go:80]: This test was silently wrong! Thanks Kristin for helping figure this out.

**Comment by apparentlymart** [comment]
I'm focusing on the error message presentation here because I've not been following closely with the work that led here and so I think it's better for others to dig in to the details...

I'm thinking about the situations where a user is likely to encounter the first message you mentioned in your comment. I tend to assume that a given module is called more than it is written, and so I'm thinking about this from the perspective of the person writing the calling module. I think for _that_ person the way to understand the situation is "This module does not support count/for_each", with the presence of the provider being the explanation for why. That makes me think of an error similar to this example:

```
Error: Module does not support for_each

  on modules.tf line 4, in module "example":
   4:   for_each = var.whatever

Module "example" cannot be used with for_each because it contains
a nested provider configuration for "aws", at child/main.tf:2.

This module can be made compatible with for_each by changing it
to receive all of its provider configurations from the calling module,
either via implicit inheritance or via explicit passing using the
"providers" argument in the calling module block.
```

What I'm going for in the above is that in the common situation where the module is written by a different person than the caller, the most immediate action they can take in response to this is to remove the `for_each` argument and work with the module a different way. They might separately open a request to the module author to report the limitation, and so the message secondarily contains some guidance for that person on what they can change in their module to make it `for_each`-compatible.

In some cases the caller and the callee might be authored by the same person and even in the same codebase, so in that happy path the person reading this error message would in theory be able to go and change the module to make it `for_each` compatible immediately, but doing so is likely to be a breaking change for the module in question and so have more overhead than finding a different approach that doesn't use `for_each`.

What do you think? This is subjective for sure, and I can also see the argument that this new framing feels less direct from the perspective of the person who is empowered to refactor the child module.

**Comment by pselle** [comment]
@apparentlymart This is very interesting! I was wondering about 

- How to handle/communicate around users using modules they didn't write
- But still communicate helpful information to help users understand why, or how they could overcome the issue.

And this suggestion serves both of those! Thank you!
