### PR TITLE
Destroy provisioner each.key

### LINKED ISSUE #24139: Cannot destroy for_each null_resource with destroy provisioner within a module
### Terraform Version

```
Terraform v0.12.20
+ provider.null v2.1.2
```

### Terraform Configuration Files

./tftest/module.tf
```hcl
variable "database_roles" {
  type = map
}

resource "null_resource" "role" {
  for_each = var.database_roles

  provisioner "local-exec" {
    command = <<-EOT
    echo "Create role ${each.value} on ${each.key}"
    EOT
  }

  provisioner "local-exec" {
    when    = destroy
    command = <<-EOT
    echo "Deleted role on ${each.key}"
    EOT
  }
}
```

test.tf
```hcl
module "test" {
  source = "./tftest"
  database_roles = {
    # Sales = "user"
    Audit = "admin"
  }
}
```

### Debug Output

https://gist.github.com/tlanghals-uturn/7bde0e4ac6577768ec6428921409cce3

### Expected Behavior

module.test.null_resource.role["Sales"] should be destroyed

### Actual Behavior

Error: Invalid for_each argument: The "for_each" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the -target argument to first apply only the resources that the for_each depends on.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3.  Remove or comment out one item from the database_roles map
2. `terraform apply`

### Additional Context

This same code works without issue if you run the module code directly so it's explicitly related to the fact it's being called via module.

We have a number of modules using this syntax which all worked without issue in v12.18, once upgraded to v12.20 we can no longer destroy such resources.

### PR DESCRIPTION
**Pull request by jbardin**
Destroy provisioners have access to the `each.key` value, but they cannot access it by evaluating the `for_each` expressions and must extract it from the instance address.

Fixes #24139

### CODE REVIEW

File: terraform/eval_apply.go [hunk 1]
```diff
@@ -561,9 +561,22 @@ func (n *EvalApplyProvisioners) apply(ctx EvalContext, provs []*configs.Provisio
...
 
-		forEach, forEachDiags := evaluateResourceForEachExpression(n.ResourceConfig.ForEach, ctx)
-		diags = diags.Append(forEachDiags)
-		keyData := EvalDataForInstanceKey(instanceAddr.Key, forEach)
+		var keyData InstanceKeyEvalData
+		switch {
+		case n.When == configs.ProvisionerWhenDestroy:
+			// if this is a destroy provisioner, we can only know the Key value
+			// itself, which is contained in the address
+			switch key := instanceAddr.Key.(type) {
```
Comment (apparentlymart) [inline terraform/eval_apply.go]: To keep this more within the `cty` realm, maybe it would be good to add an `InstanceKey.Value` method that encapsulates the conversion to a suitable `cty.Value`. Then we could use it both here and in `EvalDataForInstanceKey` and thus avoid these two functionally-equivalent-but-different codepaths? :thinking: 

I'd ideally also like to somehow encapsulate the rule that a string key goes in `EachKey` but an int key goes in `CountIndex` in a single place too, but I'm not sure what's a good way to do that. One idea that comes to mind is to just call `EvalDataForInstanceKey` with a nil map, thus letting `EachValue` end up getting populated as `cty.NilVal`, but that feels like relying on implementation details than a properly-designed API. :confounded:

Comment (jbardin) [reply terraform/eval_apply.go]: Yes, I forgot to actually look at the `EvalDataForInstanceKey` function, as it wasn't doing what I though it was. 

As for the second part, that's what we already do, so I don't see any harm in continuing that at the moment.

Comment (jbardin) [reply terraform/eval_apply.go]: I liked the InstanceKey.Value idea, and implemented that, along with cleaning up `EvalDataForInstanceKey`. I think it looks a bit cleaner, short of revamping how we handle the InstanceKey data in general.

File: terraform/eval_apply.go [hunk 2]
```diff
@@ -561,8 +561,15 @@ func (n *EvalApplyProvisioners) apply(ctx EvalContext, provs []*configs.Provisio
 		provisioner := ctx.Provisioner(prov.Type)
 		schema := ctx.ProvisionerSchema(prov.Type)
 
-		forEach, forEachDiags := evaluateResourceForEachExpression(n.ResourceConfig.ForEach, ctx)
-		diags = diags.Append(forEachDiags)
+		var forEach map[string]cty.Value
+
+		// We can't evaluate the for_each expression during a destroy
```
Comment (apparentlymart) [inline terraform/eval_apply.go]: The logic here seems fine, but I feel like I want the commentary around this to be a little clearer about the intent because right now this use of `forEach` without populating it first has the pattern of a common bug I look for in code review. Perhaps we could add a couple extra comments to help be more explicit for future-us who don't remember about this PR...

For the `EvalKeyForInstanceKey` call below, perhaps:

```go
// For a destroy-time provisioner forEach is intentionally nil here, which
// EvalDataForInstanceKey responds to by not populating EachValue
// in its result. That's okay because each.value is prohibited for
// destroy-time provisioners.
```

...and then in the docstring for `EvalDataForInstanceKey` itself, perhaps:

```go
// EvalDataForInstanceKey constructs a suitable InstanceKeyEvalData for
// evaluating in a context that has the given instance key.
//
// The forEachMap argument can be nil when preparing for evaluation
// in a context where each.value is prohibited, such as a destroy-time
// provisioner. In that case, the returned EachValue will always be
// cty.NilVal.
```

Comment (jbardin) [reply terraform/eval_apply.go]: Those are great! added verbatim.
