### PR TITLE
Command state mv: Error when backup or backup-out options are used without the state option on non-local backends

### LINKED ISSUE #27908: terraform state mv not creating backups
### Terraform Version
0.14.6 - WINDOWS

### Expected Behavior
backup file should be created

### Actual Behavior
no backup file is created

### Steps to Reproduce
0. on windows
1. using s3 remote state - might not be relevant, but is my current configuration
2. `terraform state mv -backup="test.backup"  -state-out="test/terraform.tfstate" aws_iam_role.test aws_iam_role.test`
OR
`terraform state mv -state-out="test/terraform.tfstate" aws_iam_role.test aws_iam_role.test`

### Additional Context
Using an s3 backend (might not be relevant, but is my current configuration).  When specifying a `-backup`, no backup file is created when executing a `state mv`.  When not specifying `-backup`, no backup file is created when executing a `state mv`

### PR DESCRIPTION
**Pull request by lafentres**
## Description

While [the documentation for the `state mv` command says](https://www.terraform.io/docs/cli/commands/state/mv.html#usage) that `-state`, `-state-out`, `-backup`, and `-backup-out` are only supported on the local backend, Terraform will accept these options and ignore the backup options silently when used with a non-local backend. This can put users into a state where they think they have backed up their state when modifying it but they actually haven't. This PR changes the `state mv` command to error when the `-backup` or `-backup-out` options are used without the `-state` option on non-local backends. 
Closes #27908

There were a few different options I explored while trying to figure out what behavior made the most sense here:
1. Don't allow the use of the options `-state`, `-state-out`, `-backup`, and `-backup-out` with configurations using a non-local backend.
   - This is simple, straightforward, and matches exactly what is currently in the documentation.
   - However, it is possible that there are workflows where users might pull remote state down locally to make modifications, some that may involve supported Terraform commands and some that might be manual. To do this, they would use the `-state` option to point to their local copy of state. You could argue that they could do the `state mv` work before pulling the state down for other modifications but this seems like an arbitrary and inconvenient ordering to me.
1. Don't allow the use of the options `-backup` and `-backup-out` with configurations using a non-local backend.
   - This is straightforward but like the previous solution doesn't address the use case of modifying remote state locally. 
1. Don't allow the use of the options `-backup` and `-backup-out` with configurations using a non-local backend unless the `-state` option has been specified
   - This is definitely not as simple and straightforward as previous solutions but it supports modifying remote state locally while also still erroring when users use the backup options incorrectly. 
   - This also means eventually updating the documentation to reflect the fact that you can actually use the state options with a configuration that uses a non-local backend (doing so essentially overrides your backend and uses the local state file). The documentation will also need to be updated to explain that backup options can be used with configurations using a non-local backend but only if you use the state options to override your backend. 

There are other commands that are likely to have the same problem. They will be addressed in later PRs, likely in a similar manner:
1. `apply`
2. `import`
3. `refresh`
4. `taint`
5. `untaint`
6. `state replace-provider`
7. `state rm`

## Testing plan

You can use whatever configs you like for testing the `state mv` command against local and non-local backends. I've provided the simple configs I used below.
#### Example configs to use for testing:
1. Local backend
   ```terraform
   resource "random_id" "random_local" {
     keepers = {
       uuid = uuid()
     }
     byte_length = 11
   }

   output "random" {
     value = random_id.random_local.hex
   }
   ```
1. Non-local backend: Consul (feel free to use whatever non-local backend you like)
   ```terraform
   terraform {
     backend "consul" {
       path    = "state-mv-test"
     }
   }

   resource "random_id" "random_remote" {
     keepers = {
       uuid = uuid()
     }
     byte_length = 11
   }

   output "random" {
     value = random_id.random_remote.hex
   }
   ```

#### Local backend:
The basic idea for this section is that everything should continue to work the way it always has in previous Terraform versions, regardless of which option combinations you use or if you use an implicit or explicit local backend. 
1. Run `terraform state mv -backup=fancy-local.backup random_id.random_local random_id.random_local1`. 
   This should behave the same way as in previous Terraform versions, resulting in an error that looks like this:
   ```
   │ Error: Backend initialization required, please run "terraform init"
   │ 
   │ Reason: Initial configuration of the requested backend "local"
   │ 
   │ The "backend" is the interface that Terraform uses to store state,
   ...
   │ hasn't changed and try again. At this point, no changes to your existing
   │ configuration or state have been made.
   ```
1. Run `terraform init` 
   and then `terraform state mv -backup=fancy-local.backup random_id.random_local random_id.random_local1`. 
   This should behave the same way as in previous Terraform versions, resulting in an error that looks like this:
   ```
   No state file was found!

   State management commands require a state file. Run this command
   in a directory where Terraform has been run or use the -state flag
   to point the command to a specific state location.
   ```
1. Run `terraform apply` 
   and then `terraform state mv -backup=fancy-local.backup random_id.random_local random_id.random_local1`. 
   This should behave the same way as in previous Terraform versions, succeeding and resulting in a backup file called `fancy-local.backup` being created and the resource being renamed in your `terraform.tfstate` file
1. Try various combinations of `-state`, `-state-out`, `-backup`, and `-backup-out`. These should all behave the same way they have in previous versions of Terraform. 

#### Non-local backend:
1. Run `terraform state mv -backup=fancy-remote.backup random_id.random_remote random_id.random_remote1`. 
   This should behave the same way as in previous Terraform versions, resulting in an error that looks like this:
   ```
   │ Error: Backend initialization required, please run "terraform init"
   │ 
   │ Reason: Initial configuration of the requested backend "consul"
   │ 
   │ The "backend" is the interface that Terraform uses to store state,
   ...
   │ hasn't changed and try again. At this point, no changes to your existing
   │ configuration or state have been made.
   ```
1. Run `terraform init` 
   and then `terraform state mv -backup=fancy-remote.backup random_id.random_remote random_id.random_remote1`. 
   This should throw the new error that looks like this:
   ```
   │ Error: Invalid command line options: -backup
   │ 
   │ Command line options -backup and -backup-out are legacy options that operate on a local state file only. You must specify a local state file with the
   │ -state option or switch to the local backend.
   ```
1. Try running the same command with the `-backup-out` option and with the `-backup` and `-backup-out` options together. You should see the same error, with the first line changing to indicate which options you've used. 
1. Run `terraform apply` 
   and then `terraform state mv -backup=fancy-remote.backup random_id.random_remote random_id.random_remote1`. 
   You should see the same error as before and nothing should change in your remote state.
   ```
   │ Error: Invalid command line option: -backup
   │ 
   │ Command line options -backup and -backup-out are legacy options that operate on a local state file only. You must specify a local state file with the
   │ -state option or switch to the local backend.
   ```
1. Try running the same command with the `-backup-out` option and with the `-backup` and `-backup-out` options together. You should see the same error, with the first line changing to indicate which options you've used. 
1. Create a local copy of your remote state by running `terraform state pull > terraform-local-copy.tfstate`
1. Run the same command as before but with with the state option specified this time
   `terraform state mv -state=terraform-local-copy.tfstate -backup=fancy-remote.backup random_id.random_remote random_id.random_remote1`. 
   This should succeed and you should see a `fancy-remote.backup` file created and you should see your resource name updated in `terraform-local-copy.tfstate`. Nothing should change in your remote state. 
1. Try various combinations of `-state`, `-state-out`, `-backup`, and `-backup-out`. These should all work as expected as long as the state option has been specified.

#### Local build of section of updated docs:
Screen Shot 2021-11-05 at 3 38 04 PM

### CODE REVIEW

File: internal/command/state_mv.go [hunk 1]
```diff
@@ -42,6 +43,43 @@ func (c *StateMvCommand) Run(args []string) int {
...
+
+		// If currentBackend is nil and diags didn't have errors,
+		// this means we have an implicit local backend
+		_, isLocalBackend := currentBackend.(backend.Local)
+		if currentBackend != nil && !isLocalBackend {
+			diags = diags.Append(
+				tfdiags.Sourceless(
+					tfdiags.Error,
+					fmt.Sprintf("Invalid command-line flags: %s", strings.Join(setLegacyLocalBackendFlags[:], ", ")),
+					"Command-line flags -backup and -backup-out are legacy options that operate on a local state file only. You must specify a local state file with the -state flag or switch to the local backend.",
```
Comment (apparentlymart) [inline internal/command/state_mv.go:75]: We've been taking a "fix it while you're in the area" approach to gradually moving all of our user-facing language to talk about "command line _options_" rather than "flags", because we'd been historically pretty inconsistent about it. Could you tweak this message to use that noun instead? (Then it'll be more consistent with [the documentation](https://www.terraform.io/docs/cli/commands/state/mv.html).

(The internal symbols are less important because we're using a package called `flag` anyway, so it's pretty hard to get away from that terminology in the code itself! :grinning: )

**Review by apparentlymart — APPROVED** [review]
This looks good to me! I like the compromise of effectively treating the `-state=...` option here as a single-command forcing of using the local backend (conceptually, if not in implementation), since that's a nice way to get a bit of extra functionality out of what would otherwise have been a mostly-useless legacy mode.

I left a little nit inline about terminology. It's definitely a work-in-progress so we're not fully consistent on it yet, but it'd be nice to make this new message start off using the current terminology.

File: internal/command/state_mv.go (hunk 1 above)
Comment (lafentres) [reply internal/command/state_mv.go]: Thank you! This is very helpful. It wasn't clear to me which to use so this is perfect. I've updated all of my changes to use `option` instead of `flag` :]
