### PR TITLE
Validate duplicate provider local names in `required_providers`

### LINKED ISSUE #31196: Error: Invalid provider configuration
Hello,

I found a bug. It works sometimes and sometimes it doesn't work

Error is:
```
╷
│ Error: Invalid provider configuration
│
│ Provider "registry.terraform.io/hashicorp/aws" requires explicit configuration. Add a provider block to the root module and configure the provider's required arguments as described in the provider
│ documentation.
│
╵
╷
│ Error: Invalid provider configuration
│
│ Provider "registry.terraform.io/hashicorp/aws" requires explicit configuration. Add a provider block to the root module and configure the provider's required arguments as described in the provider
│ documentation.
│
╵
╷
│ Error: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: operation error STS: GetCallerIdentity, https response error StatusCode: 403, RequestID: 90c2bb3d-57fa-4343-8432-6547c9f428f6, api error InvalidClientTokenId: The security token included in the request is invalid.
│
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on <empty> line 0:
│   (source code not available)
│
╵
╷
│ Error: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: operation error STS: GetCallerIdentity, https response error StatusCode: 403, RequestID: 89839117-a84e-4ce7-ab1a-ef99a1b21466, api error InvalidClientTokenId: The security token included in the request is invalid.
│
│   with provider["registry.terraform.io/hashicorp/aws"].shared,
│   on <empty> line 0:
│   (source code not available)
│
╵
```

### Terraform Version

```
Terraform v1.2.2
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.17.1
```

### Terraform Configuration Files

```terraform
terraform {
  backend "s3" {
    bucket         = "tf-state-eu-west-3"
    key            = "management/terraform.tfstate"
    region         = "eu-west-3"
    profile        = "shared"
    dynamodb_table = "management-tflock"
  }
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }
    shared = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }
  }
}

provider "aws" {
  region = "eu-west-3"
  profile = "management"
}

provider "aws" {
  alias  = "shared"
  region = "eu-west-3"
  profile = "shared"
}
```

```terraform
locals {
  directory_service_password = jsondecode(data.aws_secretsmanager_secret_version.this.secret_string).aws_directory_service_directory
}

data "aws_secretsmanager_secret" "this" {
  name = "terraform/shared-services/infrastructure"
  provider = aws.shared
}

data "aws_secretsmanager_secret_version" "this" {
  secret_id = data.aws_secretsmanager_secret.this.id
  provider = aws.shared
}
```

### Expected Behavior

terraform plan should always work

### Actual Behavior

Often terraform plan does not work

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
3. if it works, retry `terraform plan`

### PR DESCRIPTION
**Pull request by jbardin**
Adding multiple local names for the same provider type in `required_providers` was not prevented, which can lead to ambiguous behavior in Terraform. Providers are always located via the provider's fully qualified name (even using the full name as a map key in many places), so duplicate local names cannot be differentiated. This can lead terraform to non-deterministically configure the incorrect provider in some cases.

Because it is currently possible that a configuration with providers which themselves do not need explicit configuration may have been working with duplicates, we cannot turn these into errors. Adding multiple entries for the same provider now results in a warning like so:

```
│ Warning: Duplicate required provider
...
│
│ Provider hashicorp/null with the local name "dupe" was previously required as "null". A provider
│ can only be required once within required_providers.
```

We can also check for the situation where a user required a provider by a name different from the default, but attempted to configure that provider via the default local name. This can help prevent the case where a provider configuration may apparently not always be taking effect within a module. The warning here is worded slightly differently:

```
│ Warning: Duplicate required provider
...
│
│ Provider hashicorp/null with the local name "dupe" was implicitly required via a configuration
│ block as "null". Make sure the provider configuration block name matches the name used in
│ required_providers.
```

fixes #31196

### CODE REVIEW

**Review by apparentlymart — COMMENTED** [review]
This seems like a nice improvement to me that should give some better feedback about a situation that was already invalid but checked and reported in a confusing way.

I do have a few questions about the overall impact of this change:
* Were you able to verify that there weren't any situations before where someone might have been able to "get away with" declaring multiple provider local names in this way _without_ hitting some sort of error?

    I cannot imagine any case that should've worked, because declaring two providers with different local names and then configuring against them both means exactly the same thing as declaring two provider configurations with the same local name and alias. But given that this was unambiguous, I do wonder if there's a possibility that something might have crept through that could be arguably covered by the v1.0 compatibility promises. :grimacing: 
* How does this interact with the various _implied_ provider requirements Terraform infers for backward compatibility? For example:

    ```hcl
    terraform {
      required_providers {
        notaws = {
          source = "hashicorp/aws"
        }
      }
    }

    provider "notaws" {
      # ...
    }


    provider "aws" {
      # ...
    }
    ```

    I _think_ your `TestProviderConfigTransformer_duplicateLocalName` test is asserting that this is _allowed_, but that seems counter-intuitive to me since it seems like it's still effectively declaring the `hashicorp/aws` provider under two local names, with one of them just being implied by our back-compat rules rather than written out explicitly by the user.

    Might we need an additional rule in `ProviderConfigTransformer` to treat the above as invalid, or does that already get taken care of by some logic I can't see clearly in this diff?

**Comment by jbardin** [comment]
Hmm, actually that test example came from my first iteration where this was warning, but I found that because there were multiple points where providers were located only by their full name, you couldn't configure them without possibly running into errors. But now I see the problem here, it's technically possible to have a completely working configuration if you're not configuring the provider at all (or maybe not even using the provider!). There would be no reason to write such a config in the first place, but maybe a module could end up there through some refactoring? 🤔 

I think I'm going to loosen this back up to a warning to be on the safe side.

File: internal/configs/provider_validation.go [hunk 1]
```diff
@@ -82,7 +82,54 @@ func validateProviderConfigs(parentCall *ModuleCall, cfg *Config, noProviderConf
...
+					),
+					Subject: &req.DeclRange,
+				})
+			} else if req.Type.IsDefault() {
+				// Now check for possible implied duplicates, where a provider
+				// block uses a default namespaced provider, but that provider
+				// was required via a different name.
+				impliedLocalName := req.Type.Type
+				// We have to search through the configs for a match, since the keys contains any aliases.
+				for _, pc := range mod.ProviderConfigs {
```
[the remark this answers is not in the document]
Comment (jbardin) [reply internal/configs/provider_validation.go:115]: While it does work out that the implied provider based on the resource prefix will just get hooked up to the correct provider, even if it has a different local name, perhaps it's best to warn about that case too? I didn't delve into that here because it doesn't cause any known issues, and it's not as straightforward as dealing with the provider configs alone.

[the remark this answers is not in the document]
Comment (apparentlymart) [reply internal/configs/provider_validation.go:115]: I agree that it seems a little unclear what we should do here... I do like the consistency of treating a provider dependency implied by a resource the same way as a provider dependency implied by a provider configuration, since it seems like both of those things are a common source of confusion for folks anyway. But if it is particularly gnarly to do it then I would agree probably not worth it.

I have some memory of a function somewhere which takes something describing a provider and encapsulates the logic for deciding which provider configuration it ought to belong to, which if we could find it might allow all of these situations together as one rule (a `provider = aws.foo` can _also_ imply a dependency on `hashicorp/aws` if there isn't already an `aws` in scope), but if we'd end up having to duplicate all of the logic for detecting implicit provider requirements in here then I'd say that's probably too high a cost for just a little consistency. (Unfortunately I don't remember where this function is, assuming I'm not misremembering it existing in the first place, but maybe you have seen it on your travels while working on this... :thinking:)

[the remark this answers is not in the document]
Comment (jbardin) [reply internal/configs/provider_validation.go:115]: Checking this final case wasn't that bad, we've already collected the `required_providers` local names, so we just need to iterate over the resources looking for implied providers which aren't in that set.

The newest commit adds a diagnostic like:

```
│ Warning: Duplicate required provider
...
│ Provider "null" was implicitly required via resource "null_resource.a", but listed in
│ required_providers as "nope". Either the local name in required_providers must match the resource
│ name, or the "nope" provider must be assigned within the resource block.
```

File: internal/configs/provider_validation.go [hunk 2]
```diff
@@ -95,6 +142,44 @@ func validateProviderConfigs(parentCall *ModuleCall, cfg *Config, noProviderConf
...
+			// Now make sure we don't have the same provider required under a
+			// different name.
+			for prevLocalName, addr := range localNames {
+				if addr.Equals(defAddr) {
+					diags = append(diags, &hcl.Diagnostic{
+						Severity: hcl.DiagWarning,
+						Summary:  "Duplicate required provider",
+						Detail: fmt.Sprintf(
+							"Provider %q was implicitly required via resource %q, but listed in required_providers as %q. Either the local name in required_providers must match the resource name, or the %q provider must be assigned within the resource block.",
+							localName, r.Addr(), prevLocalName, prevLocalName,
```
Comment (apparentlymart) [inline internal/configs/provider_validation.go:172]: Subjectively, I think it'd help a little to make that first `%q` be `defAddr` instead of just `localName`, even though _we_ know that it'll always just be `hashicorp/` followed by the `localName` anyway, just to add a little nudge here for those who aren't yet aware of this implied dependency mechanism and might benefit from us linking it with what they can see in the `terraform init` and `terraform providers` output.

Probably we'll refine this message some more once we see what sorts of questions people ask about it, since it's hard to guess right now what a typical recipient of this message might know or not know, so otherwise I think this is a fine place to start!

File: internal/configs/provider_validation.go [hunk 3]
```diff
@@ -95,6 +142,44 @@ func validateProviderConfigs(parentCall *ModuleCall, cfg *Config, noProviderConf
...
 
+	checkImpliedProviderNames := func(resourceConfigs map[string]*Resource) {
+		// Now that we have all the provider configs and requirements validated,
+		// check for any resources which use an implied localname which doesn't
+		// match that of required_providers
+		for _, r := range resourceConfigs {
+			// We're looking for resources with no specific provider reference
+			if r.ProviderConfigRef != nil {
+				continue
+			}
```
Comment (apparentlymart) [inline internal/configs/provider_validation.go:153]: Aren't we _also_ looking for resources that explicitly specify a provider local name that wasn't declared?

```hcl
  provider = aws.foo
```

I believe (though I haven't tested) that if we encounter the above without there being an `aws` in `required_providers` then we treat it as an implied requirement for `hashicorp/aws`, just as we would if it were not set at all but the type name begins with "aws".

[`Resource.ProviderConfigAddr`](https://github.com/hashicorp/terraform/blob/9db277af427d18af078cd07915733d04e14daf71/internal/configs/resource.go#L72-L90) seems to be the definition of which local name a particular resource is associated with, and so maybe we can use that here and then take the `LocalName` field of the result as the local name to use below.

File: internal/configs/provider_validation.go [hunk 4]
```diff
@@ -95,6 +142,44 @@ func validateProviderConfigs(parentCall *ModuleCall, cfg *Config, noProviderConf
...
+
+			localName := r.Addr().ImpliedProvider()
+			if _, ok := localNames[localName]; ok {
+				// OK, this was listed directly in the required_providers
+				continue
+			}
+
+			defAddr := addrs.NewDefaultProvider(localName)
```
Comment (apparentlymart) [inline internal/configs/provider_validation.go:161]: I think this could instead be a call to [`Module.ImpliedProviderForUnqualifiedType`](https://github.com/hashicorp/terraform/blob/f266d1ee82d1fa4d882c146cc131fec4bef753cf/internal/configs/module.go#L573-L577), which I believe aims to encapsulate the logic for "what is the fallback to use if this doesn't match an explicit provider requirement?".

That _does_ also consult the required providers for the module, and so calling it directly wouldn't allow distinguishing between a reference to an explicit declaration vs. a backward-compatibility fallback. So maybe then the better answer would be to skip over that layer and go directly to `addrs.ImpliedProviderForUnqualifiedType`, which at least deals with the special case that `terraform` means `terraform.io/builtin/terraform` rather than `hashicorp/terraform`. Or maybe we could change the signature of `Module.ImpliedProviderForUnqualifiedType` to return an additional result that signals explicitly whether this was taken from an explicit `required_providers` declaration or just a compatibility fallback, in the interests of keeping all of the logic using mostly the same codepaths. :thinking: 

Generally I'd encourage leaning on these existing methods as much as they make sense, because they are there to encapsulate all of the little oddities that arose in the process of developing the provider source scheme, and so if we skip over them and try to reimplement their logic out here it's likely that we'll miss some edge case that we've forgotten about in the meantime and make this not behave consistently with the logic elsewhere.

**Review by apparentlymart — COMMENTED** [review]
Sorry... more noodling here as I dug into the new logic you wrote. Each time I read new code in this PR it reminds me of things I'd forgotten about the provider resolution logic, and so I'm sorry I'm kinda just dribbling context slowly over the course of many round-trips. :confounded:

File: internal/configs/provider_validation.go (hunk 4 above)
Comment (apparentlymart) [reply internal/configs/provider_validation.go:161]: I don't remember us making any special effort to treat `source = "terraform.io/builtin/terraform"` as invalid, so as far as I know you _can_ include it there if you really want to give it a local name other than `terraform`, though of course that would be a pretty bizarre thing to do.

Comment (jbardin) [reply internal/configs/provider_validation.go:161]: oh yeah, you can, not sure why I thought we disallowed that 🤔

File: internal/configs/provider_validation.go (hunk 2 above)
Comment (jbardin) [reply internal/configs/provider_validation.go:172]: I actually had that at first, but changed it as I cut the message down for brevity ;) THat's a fair point though, and will put it back.

**Review by apparentlymart — APPROVED** [review]
This looks good to me! Thanks for indulging me on my gradual trip through reloading the context about how all of this works in order to actually review it. :roll_eyes:
