### PR TITLE
validate provider_meta contains no interpolations

### LINKED ISSUE #28061: Error: value must be known when using GKE module, google_service_account resource
### Terraform Version

```
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/google v3.59.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.3
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Terraform Configuration Files

```terraform
provider "google" {
  project = "wesearch-prod"
  region  = "us-west1"
}

data "google_client_config" "default" {}

# module to create gke cluster
module "gke" {
  source = "terraform-google-modules/kubernetes-engine/google//modules/private-cluster"

  project_id               = "wesearch-prod"
  name                     = "test-jt-cluster"
  regional                 = true
  region                   = "us-west1"
  zones                    = ["us-west1-a"]
  network                  = "wesearch-prod-vpc"
  subnetwork               = "wesearch-prod-gke"
  ip_range_pods            = "gke-gke-cluster-1-pods-test"
  ip_range_services        = "gke-test-gke-cluster-1-services"
  create_service_account   = true
  enable_private_nodes     = true
  remove_default_node_pool = true
  kubernetes_version       = "1.18.16-gke.300"

  node_pools = [
    {
      name         = "nodepool-with-min-config"
      min_count    = 1
      max_count    = 2
      disk_size_gb = 50
      disk_type    = "pd-standard"
      image_type   = "COS"
      machine_type = "n1-standard-1"
      auto_repair  = true
      auto_upgrade = true
      preemptible  = false
    },
  ]
}
```

### Debug Output

https://gist.github.com/justinturpin/062e6bb65aa02b27dc95a4cdf92dce2a

### Expected Behavior
Either no error, or a helpful message with context about what value was expected.

### Actual Behavior
When trying to use the GKE private cluster module "terraform-google-modules/kubernetes-engine/google//modules/private-cluster", Terraform gives a "Error: value must be known" error with no context on trying to create the google_service_account.

### Steps to Reproduce
Use full Terraform configuration above in a GCP environment, run `terraform init` and `terraform apply`.

### Additional Context
This can be reproduced using just Terraform, no wrapper script. Running in Pop Os (Ubuntu 20.10).

### PR DESCRIPTION
**Pull request by jbardin**
The `provider_meta` specification does not allow interpolation, but we were not preventing it in the configuration. The `provider_meta` block does not have a defined lifecycle during evaluation, and cannot be correctly ordered to ensure any references have been evaluated. Since `provider_meta` must be an entirely static map, we can validate this early on while loading the configuration. 

Preventing interpolations could be a breaking change for existing modules that were successfully using this undefined behavior, but as demonstrated in #28061 success is not deterministic between releases.

Resolves #28061

### CODE REVIEW

File: configs/provider_meta.go [hunk 1]
```diff
@@ -13,8 +13,20 @@ type ProviderMeta struct {
 }
 
 func decodeProviderMetaBlock(block *hcl.Block) (*ProviderMeta, hcl.Diagnostics) {
+	// provider_meta must be a static map. We can verify this by attempting to
+	// evaluate the values.
+	attrs, diags := block.Body.JustAttributes()
+	if diags.HasErrors() {
+		return nil, diags
```
Comment (pselle) [inline configs/provider_meta.go:20]: What diags are returned here? Does it help the user know how to fix their problem?

Comment (jbardin) [reply configs/provider_meta.go:20]: It's an `hcl.Diagnostics`, so will contain the source reference. This shouldn't be seen by endusers, as its use needs to be coordinated with the provider itself (and is currently only used by Google). Validating will allow the module developers to catch the problem before publishing the module.

**Review by mildwonkey — APPROVED** [review]

**Review by paddycarver — APPROVED** [review]
