### PR TITLE
command/init: omit a warning if -backend-config is used with no backend

### LINKED ISSUE #21023: No warning when backend config is not being used
I just spent an hour debugging why Terraform wanted to create resources that already exist. I eventually discovered it was because I omitted this by mistake:

```terraform
terraform {
  backend "s3" {}
}
```

### Terraform Version

```
Terraform v0.11.11
```

### Terraform Configuration Files

N/A

### Expected Behavior

The `terraform init` was called with backend configuration enabled, so I expect it to either fail - or at least very clearly warn me - when it does not end up using said configuration.

Also, why do I even need to add that source code snippet? Seems redundant if I have initialised a backend configuration on the command line.

### Actual Behavior

It silently fails to use the backend configuration.

### PR DESCRIPTION
**Pull request by mildwonkey**
Terraform would silently accept - and swallow - `-backend-config` on the
CLI when there was no `backend` block. Since it is mostly expected to
override existing backend configuration, ~it is reasonable that terraform
should return an error if there is no backend configuration to
override.~ EDIT: on second thought, let's print a warning! 

If the user intended to override the default (local) backend
configuration, they can first add a `backend` block to the `terraform` block to silence the warning:

```hcl
terraform {
  backend "local" {}
}
```
Fixes #21023

### CODE REVIEW

File: command/init.go [hunk 1]
```diff
@@ -438,6 +438,27 @@ func (c *InitCommand) initBackend(root *configs.Module, extraConfig rawFlags) (b
 		if overrideDiags.HasErrors() {
 			return nil, true, diags
 		}
+	} else {
+		// If the user supplied a -backend-config on the CLI but no backend
+		// block was found in the configuration, return an error.
+		if !extraConfig.Empty() {
+			diags = diags.Append(&hcl.Diagnostic{
+				Severity: hcl.DiagError,
+				Summary:  "missing backend block",
```
Comment (pselle) [inline command/init.go]: Aren't summaries usually capitalized?

Comment (mildwonkey) [reply command/init.go]: good catch, thanks

**Comment by mildwonkey** [comment]
After mulling over this for awhile I had second thoughts about an error vs. warning, so have a warning instead! An error could have been a breaking change; we can always choose to update this warning to an error _eventually_ (preferably with an interim step where the warning specifies when it will become an error).
