### PR TITLE
command/format: minor adjustments to plan rendering

### LINKED ISSUE #8713: terraform import command fails when there are several nested levels on the resource address
### Description

The terraform import command fails with an error message when you try to import a resource the was created from a module that has several nested levels.
### Terraform Version

Terraform v0.7.3
### Affected Resource(s)

AWS. Any resource created from a module with several nested subdirectories.
### Expected Behavior

The terraform import command works fine and finally import the resource no matters how many levels it has.
### Actual Behavior

The terraform import command fails when the resource address has several nested levels.
### Steps to Reproduce
1. `terraform get`
2. `terraform plan`
3. Here We get several resources that we has created previously trough amazon console and We want to add them to the tfstate.
4. `terraform import module.network.vpc.aws_vpc.vpc vpc-vpcxxxxid`
5. Terraform informs us that there's an "unexpected value for instance type field" due several nested levels on the resource address.
### Details

Our main project structure is like this:

```
/
  modules
    - network
        - network.tf
        - private_subnet
            public_subnet.tf
        - public_subnet
            public_subnet.tf
        - vpc
            vpc.tf
    - rds
    - redshift
    - ...
  dev
    network.tf
```

The call to the modules occurs in this order:

from dev/network.tf:

```
        module "network" {
          source          = "../modules/network"
          ...
```

from modules/network/network.tf

```
        module "vpc" {
          source   = "./vpc"
          ...
```

from modules/network/vpc/vpc.tf

```
        resource "aws_vpc" "vpc" {
          cidr_block           = "${var.vpc_cidr}"
          ...
```

If We are inside dev directory and We execute a terraform import command We get this error message:

hostname:dev julian$ terraform import module.network.vpc.aws_vpc.vpc vpc-vpcxxxxid
Error importing: failed to parse resource address 'module.network.vpc.aws_vpc.vpc': Unexpected value for InstanceType field: "vpc"
hostname:dev julian$

And the import fails.
### Workaround

We import the resource address with this command:
terraform import module.network.aws_vpc.vpc vpc-xxxxid

After this the resource is imported and We manually change the resource in the tfstate editing the file. If We move the resource with the command "terraform state mv source.address destination.address" We get an error too.

### LINKED ISSUE #15350: Stop colouring a destruction of a resource in green
terraform 0.8.7

An idea, not a bug per se, but still...:

terraform handily outputs the removal of a resource in red, the change of a resource in yellow, and the creation of a resource in green. 

However where the change consists of a re-creation of a resource (destroy then create), it uses green. As this is actually a destructive action, it should either be in red, or something like purple. 

Its too easy to assume that a terraform plan isnt being destructive because its all green, when in fact its blown away half your infrastructure and data you can never get back.

### PR DESCRIPTION
**Pull request by apparentlymart**
This change makes various minor adjustments to the rendering of plans in the output of `terraform plan`:
    
- Resources are identified using the standard resource address syntax, rather than exposing the legacy internal representation used in the module diff resource keys. This fixes #8713.
    
- Subjectively, having square brackets in the addresses made it look more visually "off" when the same name but with different indices were shown together with differing-length "symbols", so the symbols are now all padded and right-aligned to three characters for consistent layout across all operations.
    
- The `-/+` action is now more visually distinct, using several different colors to help communicate what it will do and including a more obvious `(new resource required)` marker to help draw attention to this not being just an update diff. This fixes #15350.
    
- The resources are now sorted in a manner that sorts index `[10]` after index `[9]`, rather than after index `[1]` as we did before. This makes it easier to scan the list and avoids the common confusion where it seems that there are only 10 items when in fact there are 11-20 items with all the tens hiding further up in the list.

Certainly there are many more significant changes that could be made in this area, but this is just intended to be a small, low-risk change to deal with some minor annoyances.

---

Here's a screenshot, though it's made to look more weird by the strange mismatching saturation levels I apparently have configured in my terminal:

tf-diff-tweaks

These are all just regular primary VT100 colors in practice.

### CODE REVIEW

File: terraform/resource_address.go [hunk 1]
```diff
@@ -329,6 +329,58 @@ func (addr *ResourceAddress) Equals(raw interface{}) bool {
...
+// numeric sort for indices, thus causing index 10 to sort after
+// index 9, rather than after index 1.
+func (addr *ResourceAddress) Less(other *ResourceAddress) bool {
+
+	switch {
+
+	case len(addr.Path) < len(other.Path):
+		return true
+
+	case !reflect.DeepEqual(addr.Path, other.Path):
```
Comment (jbardin) [inline terraform/resource_address.go]: I don't think it is right now, but is it possible for indexes to end up in a path? Might they be if we can add `count` support to modules? 

This is probably fine for now, I'm only mentioning it because I think I've fixed "lexically sorted numbers" 2 or 3 times in the past couple releases.

Comment (apparentlymart) [inline terraform/resource_address.go]: Indeed in future this may get more complex, but I expect that at that point we rewrite all of this `ResourceAddress` code, since we will have hit the limit of what can be represented by the current model.
