### PR TITLE
provider/google: ignore expanded v collapsed policies in diff

### LINKED ISSUE #11763: providers/google: equivalent IAM policies are treated as different
### Terraform Version
0.8.5, 0.8.6, master

### Affected Resource(s)
* google_project_iam_policy

### Terraform Configuration Files
```hcl
resource "google_project_iam_policy" "google-project" {
  project       = "${var.gcp_project}"
  policy_data   = "${data.google_iam_policy.policy-bindings.policy_data}"
  authoritative = false
}

data "google_iam_policy" "policy-bindings" {
  binding {
    role = "roles/viewer"

    members = [
      "user:paddy@carvers.co",
    ]
  }

  binding {
    role = "roles/viewer"

    members = [
      "user:paddy@hashicorp.com",
    ]
  }
}
```

### Expected Behavior
After applying this, there should be no diff for `terraform plan`.

### Actual Behavior
After applying this, there's a diff on `terraform plan`:

```
    policy_data: "{\"bindings\":[{\"members\":[\"user:paddy@carvers.co\",\"user:paddy@hashicorp.com\"],\"role\":\"roles/viewer\"}]}" => "{\"bindings\":[{\"members\":[\"user:paddy@hashicorp.com\"],\"role\":\"roles/viewer\"},{\"members\":[\"user:paddy@carvers.co\"],\"role\":\"roles/viewer\"}]}"
```

### Steps to Reproduce
1. `terraform apply`
2. `terraform plan`

This is just a matter of getting the DiffSuppressFunc to collapse/expand policies as much as possible before comparing them, which will give us a common representation.

### PR DESCRIPTION
**Pull request by paddyforan**
When comparing the config and state for google_project_iam_policy,
always merge the bindings down to a common representation, to avoid a
perpetual diff.

Fixes #11763.

I also added a test to ensure the fix worked. Output of the test without the fix in place:

```
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/03/02 13:59:46 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/google -v -run=TestAccGoogleProjectIamPolicy_expanded -timeout 120m
=== RUN   TestAccGoogleProjectIamPolicy_expanded
--- FAIL: TestAccGoogleProjectIamPolicy_expanded (20.58s)
        testing.go:265: Step 0 error: After applying this step, the plan was not empty:

                DIFF:

                UPDATE: google_project_iam_policy.acceptance
                  policy_data: "{\"bindings\":[{\"members\":[\"user:paddy@carvers.co\",\"user:paddy@hashicorp.com\"],\"role\":\"roles/viewer\"}]}" => "{\"bindings\":[{\"members\":[\"user:paddy@hashicorp.com\"],\"role\":\"roles/viewer\"},{\"members\":[\"user:paddy@carvers.co\"],\"role\":\"roles/viewer\"}]}"

                STATE:

                data.google_iam_policy.expanded:
                  ID = 1322415602
                  binding.# = 2
                  binding.1102091722.members.# = 1
                  binding.1102091722.members.2912398366 = user:paddy@hashicorp.com
                  binding.1102091722.role = roles/viewer
                  binding.4049261743.members.# = 1
                  binding.4049261743.members.360503667 = user:paddy@carvers.co
                  binding.4049261743.role = roles/viewer
                  policy_data = {"bindings":[{"members":["user:paddy@hashicorp.com"],"role":"roles/viewer"},{"members":["user:paddy@carvers.co"],"role":"roles/viewer"}]}
                google_project.acceptance:
                  ID = terraform-pjewz40hq3
                  name = Terraform Acceptance Tests
                  number = 609045719484
                  org_id = 622235425790
                  project_id = terraform-pjewz40hq3
                google_project_iam_policy.acceptance:
                  ID = terraform-pjewz40hq3
                  authoritative = false
                  etag = BwVJxo1shsw=
                  policy_data = {"bindings":[{"members":["user:paddy@carvers.co","user:paddy@hashicorp.com"],"role":"roles/viewer"}]}
                  project = terraform-pjewz40hq3
                  restore_policy = {"bindings":[{"members":["serviceAccount:terraform-acceptance-tests@hc-terraform-testing.iam.gserviceaccount.com"],"role":"roles/owner"}],"etag":"BwVJxo0AAQ4=","version":1}

                  Dependencies:
                    google_project.acceptance
                    data.google_iam_policy.expanded
FAIL
exit status 1
FAIL    github.com/hashicorp/terraform/builtin/providers/google 20.584s
Makefile:48: recipe for target 'testacc' failed
make: *** [testacc] Error 1
```

Output after fix:

```
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/03/02 14:00:32 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/google -v -run=TestAccGoogleProjectIamPolicy_expanded -timeout 120m
=== RUN   TestAccGoogleProjectIamPolicy_expanded
--- PASS: TestAccGoogleProjectIamPolicy_expanded (19.65s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/google 19.659s
```

### CODE REVIEW

File: builtin/providers/google/resource_google_project_iam_policy_test.go [hunk 1]
```diff
@@ -290,11 +307,56 @@ func testAccCheckGoogleProjectIamPolicyIsMerged(projectRes, policyRes, pid strin
...
 		sort.Sort(sortableBindings(projectP.Bindings))
 		sort.Sort(sortableBindings(policyP.Bindings))
 		if !reflect.DeepEqual(derefBindings(projectP.Bindings), derefBindings(policyP.Bindings)) {
 			return fmt.Errorf("Project and data source policies do not match: project policy is %+v, data resource policy is  %+v", derefBindings(projectP.Bindings), derefBindings(policyP.Bindings))
 		}
+		return nil
+	}
+}
+
+func testAccCheckGoogleProjectIamPolicyIsMerged(projectRes, policyRes, pid string) resource.TestCheckFunc {
```
Comment (danawillow) [inline builtin/providers/google/resource_google_project_iam_policy_test.go]: A lot of the error checking in this function is duplicated from `testAccCheckGoogleProjectIamPolicyExists`, which is called from this fn. I wouldn't mind seeing something like (either or some combination of):
* The error-checking is removed from this function since calling the other one takes care of it
* A helper function could take care of getting the `projectP` and `policyP` values (and doing the error-checking) that gets called from both functions

File: builtin/providers/google/resource_google_project_iam_policy_test.go [hunk 2]
```diff
@@ -634,3 +696,32 @@ resource "google_project" "acceptance" {
...
+}
+resource "google_project_iam_policy" "acceptance" {
+    project = "${google_project.acceptance.id}"
+    policy_data = "${data.google_iam_policy.expanded.policy_data}"
+    authoritative = false
+}
+data "google_iam_policy" "expanded" {
+    binding {
+        role = "roles/viewer"
+	members = [
```
Comment (danawillow) [inline builtin/providers/google/resource_google_project_iam_policy_test.go]: nit: indentation (make this spaces instead of tabs)

File: builtin/providers/google/resource_google_project_iam_policy_test.go [hunk 3]
```diff
@@ -634,3 +696,32 @@ resource "google_project" "acceptance" {
...
+	    "user:paddy@carvers.co",
+	]
+    }
+    
+    binding {
+        role = "roles/viewer"
+	members = [
```
Comment (danawillow) [inline builtin/providers/google/resource_google_project_iam_policy_test.go]: and here

**Comment by paddyforan** [comment]
Comments should be addressed. :)

**Comment by danawillow** [comment]
Looks good, thanks!
