### PR TITLE
fix: avoid sending HEAD request on provider download

### LINKED ISSUE #36987: Behavior break in 1.11.x : Unexpected HEAD request in getting provider
### Terraform Version

```shell
1.11.x
```

### Terraform Configuration Files

We use [boring-registry](https://boring-registry.github.io/boring-registry/latest/) to implement our own S3 backed terraform registry.
This tool produces S3 presigned URL as download URL returned in the specific release metadata.

Up to terraform 1.10.x - terraform could download from presigned S3 URL in `terraform init`.

Starting from terraform 1.11.0 we started getting 403 for HEAD requests.
The reason is that the presigned URL is only good for GET requests.

Do you think it makes sense to disable HEAD request. I see that the HttpGetter [supports that option](https://github.com/hashicorp/go-getter/blob/f6bd417710ec3151453902bb3606413d19678cb3/get_http.go#L420) but [we don't use it](https://github.com/hashicorp/terraform/pull/35843/files#diff-2ed1e39b4f29d40dc1b7935afeb13742b30eebdb124edd840f3bd263ec3b898cR33). For the very least -  we should make this configurable to allow mitigating the behavior break.

### Debug Output

```
# terraform init

Initializing the backend...
Initializing provider plugins...
- Finding latest version of tf.app.wiz.io/wizsec/wiz...
- Installing tf.app.wiz.io/wizsec/wiz v1.24.8407...
╷
│ Error: Failed to install provider
│ 
│ Error while installing tf.app.wiz.io/wizsec/wiz v1.24.8407: terraform-server-prod.s3.us-east-2.amazonaws.com: bad response code: 403
╵
```

### Expected Behavior

This should work :) in version < 1.11.0 it just works.

### Actual Behavior

It fails with 403 on the HEAD request.

### Steps to Reproduce

1. Copy the following code:
```terraform
terraform {
    required_providers {
        wiz = {
            source  = "tf.app.wiz.io/wizsec/wiz"
        }
    }
}

provider "wiz" {
    client_id     = "foo"
    client_secret = "bar"
    tenant_id     = "baz"
}
```
2. Run `terraform init` with terraform version 1.11.x

### Additional Context

_No response_

### References

_No response_

### Generative AI / LLM assisted development?

_No response_

### PR DESCRIPTION
**Pull request by or-shachar**
Avoiding the new HEAD request that happens before GET request to get provider binary.

Fixes #36987

## Target Release

1.11.x
1.12.x
1.13.x

### BUG FIXES
- `terraform init` - avoid sending a HEAD request when fetching providers

### CODE REVIEW

File: internal/providercache/package_install.go [hunk 1]
```diff
@@ -34,6 +34,7 @@ func installFromHTTPURL(ctx context.Context, meta getproviders.PackageMeta, targ
 		Client:                httpclient.New(),
 		Netrc:                 true,
 		XTerraformGetDisabled: true,
+		DoNotCheckHeadFirst:   false,
```
Comment (bbdev442) [inline internal/providercache/package_install.go:37]: This will need to be `true` to prevent the HEAD request.

**Comment by crw** [comment]
Thanks for this submission! I will raise it in triage.

**Comment by liamcervante** [comment]
Hi @or-shachar, this looks good to me. Can you add a CHANGELOG entry to the `terraform/.changes/v1.12` directory? Due to the release schedule, we'd aim to release this in v1.12.1 next week. Thanks!

**Comment by or-shachar** [comment]
@liamcervante can we backport this also to 1.11 ?

File: .changes/v1.12/BUG FIXES-20250514-184357.yaml [hunk 2]
```diff
@@ -0,0 +1,5 @@
+kind: BUG FIXES
+body: avoid sending HEAD request on provider download
```
Comment (liamcervante) [inline .changes/v1.12/BUG FIXES-20250514-184357.yaml:2]:
```suggestion
body: Fix regression during provider installation by reverting back to not sending HEAD requests.
```

File: .changes/v1.12/BUG FIXES-20250514-184357.yaml [hunk 3]
```diff
@@ -0,0 +1,5 @@
...
+time: 2025-05-14T18:43:57.332193-04:00
+custom:
+    Issue: "36987"
```
Comment (liamcervante) [inline .changes/v1.12/BUG FIXES-20250514-184357.yaml:5]:
```suggestion
    Issue: "36998"
```

**Review by liamcervante — APPROVED** [review]
With the release of v1.12.0 yesterday, we don't have plans for any more v1.11 patch releases so a backport doesn't really make sense.

**Review by SarahFrench — APPROVED** [review]
