### PR TITLE
providers/aws: more guards against crashy cases [GH-2308]

### LINKED ISSUE #2308: provider/aws: Crash during aws_security_group_rule creation
This is against v0.5.3. The crash.log is available at https://gist.githubusercontent.com/mpage/cc1c160d1cd17803576b/raw/gistfile1.txt

Sorry for the relatively unhelpful bug report. The crash log is ~25k lines long, so it's hard for me to get a sense of what is going wrong. Happy to provide any extra context that I can.

### PR DESCRIPTION
**Pull request by mitchellh**
Fixes #2308 

I think this was already fixed, but this adds another guard to it.

### CODE REVIEW

**Comment by phinze** [comment]
Yeah doesn't hurt to be safe.

**Comment by phinze** [comment]
LGTM

File: builtin/providers/aws/resource_aws_security_group_rule.go [hunk 1]
```diff
@@ -257,7 +257,7 @@ func findResourceSecurityGroup(conn *ec2.EC2, id string) (*ec2.SecurityGroup, er
 	if err != nil {
 		return nil, err
 	}
-	if len(resp.SecurityGroups) != 1 {
+	if resp == nil || len(resp.SecurityGroups) != 1 || resp.SecurityGroups[0] == nil {
```
Comment (dtolnay) [inline builtin/providers/aws/resource_aws_security_group_rule.go]: If `resp == nil` then `resp.SecurityGroups` will panic on the next line.
