### PR TITLE
provider/aws: Fix issue updating ElasticBeanstalk Environment Settings

### LINKED ISSUE #6890: Removing Elastic Beanstalk Environment Variables
On terraform 0.6.16

If I remove a `setting` with the namespace of `aws:elasticbeanstalk:application:environment`, terraform says its removed, however the AWS console still has that setting, as well as the API still returns a value for that setting.

Also, if I add a environment variable manually in the AWS console and then re-run a plan, terraform doesn't seem to see that value and try to remove it.

It looks like when terraform refreshes its state from AWS, it doesn't properly catalog `aws:elasticbeanstalk:application:environment` keys, certainly not ensuring that there are not extra or missing keys.

### PR DESCRIPTION
**Pull request by catsby**
Fixes the logic that updated settings for Elastic Beanstalk Environments.
Because the update is done in the same API call, we need to split removals /
additions.

Fixes #6890

### CODE REVIEW

File: builtin/providers/aws/resource_aws_elastic_beanstalk_environment.go [hunk 1]
```diff
@@ -327,7 +326,39 @@ func resourceAwsElasticBeanstalkEnvironmentUpdate(d *schema.ResourceData, meta i
...
+		// Because of this, we need to remove any settings in the "removable"
+		// settings that are also found in the "add" settings, otherwise they
+		// conflict. Here we loop through all the initial removables from the set
+		// difference, and we build up a slice of settings not found in the "add"
+		// set
+		var remove []*elasticbeanstalk.ConfigurationOptionSetting
+		if len(add) > 0 {
+			for _, r := range rm {
+				for _, a := range add {
+					if *r.Namespace == *a.Namespace && *r.OptionName == *a.OptionName {
```
Comment (dharrisio) [inline builtin/providers/aws/resource_aws_elastic_beanstalk_environment.go]: @catsby do we need to take into account the ResourceName setting attribute here as well? I have a feeling this may not work as intended with more than one scheduled action (http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html#command-options-general-autoscalingscheduledaction)

This attribute can be a bit frustrating, because it is only documented for scheduled actions, but is returned by the api for some other settings. To avoid the  issues that caused I had to do this https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_elastic_beanstalk_environment.go#L717

Comment (catsby) [inline builtin/providers/aws/resource_aws_elastic_beanstalk_environment.go]: In the statefile, we ignore `ResourceName` unless it's a scheduled action. I think here I'll check if the local setting has `ResourceName` and then check if they match, continuing if they do not match. If we don't have it set locally, I'll just continue on as we have here. Does that sound reasonable?

Comment (catsby) [inline builtin/providers/aws/resource_aws_elastic_beanstalk_environment.go]: I added a check in https://github.com/hashicorp/terraform/pull/7777/commits/0cec643907e2c3f0ab30514422b5efdaeb2f6efe that I think covers this

**Comment by catsby** [comment]
updated with acc test

File: builtin/providers/aws/resource_aws_elastic_beanstalk_environment.go (hunk 1 above)
Comment (dharrisio) [inline builtin/providers/aws/resource_aws_elastic_beanstalk_environment.go]: @catsby Sorry for the delayed response here, been out for a bit. This sounds good to me!

Thanks!

**Comment by stack72** [comment]
LGTM!
