### PR TITLE
terraform test: Push evaluation of variables to as late as possible

### LINKED ISSUE #35005: terraform test command does not honor TF_VAR_* environment variables when "module" is specified after 1.8.0
### Terraform Version

```shell
Terraform v1.8.0
on linux_amd64
```

### Terraform Configuration Files

a dummy module, with a test, and a module used by the test:

main.tf:
```hcl
resource null_resource foo {}
```

foo/main.tf:
```hcl
variable "foo" {}
output "foo" {
    value = var.foo
}
```

foo.tftest.hcl:
```hcl
run "foo" {
    module {
        source = "./foo"
    }
}
```

### Debug Output

cannot post publicly.

### Expected Behavior

```bash
$ TF_VAR_foo=something terraform test
foo.tftest.hcl... in progress
  run "foo"... pass
foo.tftest.hcl... tearing down
foo.tftest.hcl... pass

Success! 1 passed, 0 failed.
```

### Actual Behavior

```bash
$ TF_VAR_foo=something terraform test
foo.tftest.hcl... in progress
  run "foo"... fail
╷
│ Error: Required variable not set
│ 
│   on foo/main.tf line 1:
│    1: variable "foo" {}
│ 
│ The variable "foo" is required, but is not set.
╵
foo.tftest.hcl... tearing down
foo.tftest.hcl... fail
Failure! 0 passed, 1 failed.
```

### Steps to Reproduce

```bash
TF_VAR_foo=something terraform test
```

### Additional Context

this does not happen on 1.7.x terraform versions. This also only seems to happen for tests with a custom module, ie:
```hcl
run {
  module {
    source = "./a-custom-module"
  }
}
```

### References

_No response_

### PR DESCRIPTION
**Pull request by liamcervante**
This PR pulls out the logic of evaluating variables for the terraform test framework into a shared variable cache. This cache can then be shared between the provider configurations and the run blocks. Within the testing framework we have to avoid evaluating variables until we know which run block they will be used in. This is because the `variable` block provides the type of the variable, and helps us to parse it properly. The `variable` blocks are only available via the configuration under test, and this is not available until the run blocks are executing.

Previously, we were evaluating all the file level variables once at the beginning of the test execution. This led to variables that were required by the modules other than the main configuration being misconfigured due to missing `variable` blocks. Now, we delay evaluating the file level variables until they are needed via the cache. The cache ensures that we don't evaluate the same variable twice when processing provider configurations and run block variables as they happen separately.

A follow up PR to this will be introduced in time for v1.9, which will allow variable blocks to be defined within the test file itself. This will allow users to specify the type of file level and global variables without needing to tie them to a specific run block.

Fixes #35005 

## Target Release

1.8.2

### BUG FIXES 

 

-  `terraform test`: Restore `TF_ENV_*` variables being made available to testing modules.

### CODE REVIEW

File: internal/moduletest/hcl/variable_cache.go [hunk 1]
```diff
@@ -0,0 +1,173 @@
...
+			files:   make(terraform.InputValues),
+			values:  caches,
+		}
+		caches.caches[name] = cache
+	}
+	return cache
+}
+
+// GetGlobalVariable returns a value for the named global variable evaluated
+// against the named run.
```
Comment (kmoe) [inline internal/moduletest/hcl/variable_cache.go:63]:
```suggestion
// against the run.
```

File: internal/moduletest/hcl/variable_cache.go [hunk 2]
```diff
@@ -0,0 +1,173 @@
...
+	//   file itself. Suggestion, optional variable blocks.
+	parsingMode := configs.VariableParseHCL
+
+	if cfg, exists := cache.config.Module.Variables[name]; exists {
+		parsingMode = cfg.ParsingMode
+	}
+
+	value, diags := variable.ParseVariableValue(parsingMode)
+	if diags.HasErrors() {
+		// In this case, the variable exists but we couldn't parse it. We'll
```
Comment (kmoe) [inline internal/moduletest/hcl/variable_cache.go:88]: Recommend adding to the function comments for `GetGlobalVariable` and `GetFileVariable` to say what gets returned if the variable can't be parsed or evaluated and remind callers to check diags before trying to use the value.

**Review by kmoe — APPROVED** [review]

File: internal/moduletest/hcl/variable_cache.go (hunk 2 above)
Comment (liamcervante) [reply internal/moduletest/hcl/variable_cache.go:93]: Done!
