### PR TITLE
helper/schema: empty map in state should not compute map

### LINKED ISSUE #1607: helper/schema: Computed Map fields generate perpetual diff when empty
This is currently breaking a bunch of acceptance tests since we've landed #1443.

For example, `TestAccHerokuApp_NukeVars`:

```
--- FAIL: TestAccHerokuApp_NukeVars (6.09s)
        testing.go:131: Step 1 error: After applying this step, the plan was not empty:

                DIFF:

                UPDATE: heroku_app.foobar
                  all_config_vars.#: "" => "<computed>"

                STATE:

                heroku_app.foobar:
                  ID = terraform-test-app
                  all_config_vars.# = 0
                  config_vars.# = 0
                  git_url = git@heroku.com:terraform-test-app.git
                  heroku_hostname = terraform-test-app.herokuapp.com
                  name = terraform-test-app
                  region = us
                  stack = cedar-14
                  web_url = https://terraform-test-app.herokuapp.com/
FAIL
```

The issue centers around how `helper/schema` distinguishes between the following two scenarios:

 * Map is empty in config, state is nil, future value of map is unknown (should generate a diff)
 * Map is empty in config, state has been written as empty, future value of map is known to be empty (should not generate a diff)

Important locations for relevant behavior:

 * `(m schemaMap) diffMap`
 * `(r *MapFieldReader) readMap`
 * `(r *MapFieldWriter) writeMap`
 * `(m schemaMap) finalizeDiff`

Pushing a branch with a failing test and some debug logging shortly.

### PR DESCRIPTION
**Pull request by mitchellh**
Fixes #1607

This makes it so that having an empty map in the state (`map.# = 0`) and a computed map element in the schema, that the diff should be empty.

### CODE REVIEW

File: helper/schema/field_reader_config.go [hunk 1]
```diff
@@ -105,34 +105,67 @@ func (r *ConfigFieldReader) readField(
 }
 
 func (r *ConfigFieldReader) readMap(k string) (FieldReadResult, error) {
-	mraw, ok := r.Config.Get(k)
+	// We want both the raw value and the interpolated. We use the interpolated
+	// to store actual values and we use the raw one to check for
+	// computed keys.
+	mraw, ok := r.Config.GetRaw(k)
```
Comment (mitchellh) [inline helper/schema/field_reader_config.go]: The changes to this whole function are the saddest. The ConfigFieldReader before simply never marked the map as computed, ever. But this isn't the case. Unfortunately we have no real way to check if its computed other than checking every field.

File: helper/schema/field_reader_map.go [hunk 2]
```diff
@@ -56,10 +56,11 @@ func (r *MapFieldReader) readMap(k string) (FieldReadResult, error) {
 	prefix := k + "."
 	r.Map.Range(func(k, v string) bool {
 		if strings.HasPrefix(k, prefix) {
+			resultSet = true
+
 			key := k[len(prefix):]
 			if key != "#" {
 				result[key] = v
-				resultSet = true
 			}
```
Comment (mitchellh) [inline helper/schema/field_reader_map.go]: This fixes another issue where MapFieldReader would not map a read map as `Exists == true` unless it had one non-`#` element.

**Comment by phinze** [comment]
LGTM :bow:
